<?php

use Illuminate\Database\Seeder;

class state42TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of SD - South Dakota.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Plankinton', 'state_id' => 3968],
                ['name' => 'Stickney', 'state_id' => 3968],
                ['name' => 'White Lake', 'state_id' => 3968],
                ['name' => 'Cavour', 'state_id' => 3968],
                ['name' => 'Hitchcock', 'state_id' => 3968],
                ['name' => 'Huron', 'state_id' => 3968],
                ['name' => 'Virgil', 'state_id' => 3968],
                ['name' => 'Wessington', 'state_id' => 3968],
                ['name' => 'Wolsey', 'state_id' => 3968],
                ['name' => 'Yale', 'state_id' => 3968],
                ['name' => 'Martin', 'state_id' => 3968],
                ['name' => 'Tuthill', 'state_id' => 3968],
                ['name' => 'Allen', 'state_id' => 3968],
                ['name' => 'Scotland', 'state_id' => 3968],
                ['name' => 'Springfield', 'state_id' => 3968],
                ['name' => 'Tabor', 'state_id' => 3968],
                ['name' => 'Tyndall', 'state_id' => 3968],
                ['name' => 'Avon', 'state_id' => 3968],
                ['name' => 'Aurora', 'state_id' => 3968],
                ['name' => 'Brookings', 'state_id' => 3968],
                ['name' => 'Elkton', 'state_id' => 3968],
                ['name' => 'Sinai', 'state_id' => 3968],
                ['name' => 'Volga', 'state_id' => 3968],
                ['name' => 'Bruce', 'state_id' => 3968],
                ['name' => 'White', 'state_id' => 3968],
                ['name' => 'Aberdeen', 'state_id' => 3968],
                ['name' => 'Barnard', 'state_id' => 3968],
                ['name' => 'Bath', 'state_id' => 3968],
                ['name' => 'Claremont', 'state_id' => 3968],
                ['name' => 'Columbia', 'state_id' => 3968],
                ['name' => 'Ferney', 'state_id' => 3968],
                ['name' => 'Frederick', 'state_id' => 3968],
                ['name' => 'Groton', 'state_id' => 3968],
                ['name' => 'Hecla', 'state_id' => 3968],
                ['name' => 'Houghton', 'state_id' => 3968],
                ['name' => 'Stratford', 'state_id' => 3968],
                ['name' => 'Warner', 'state_id' => 3968],
                ['name' => 'Westport', 'state_id' => 3968],
                ['name' => 'Chamberlain', 'state_id' => 3968],
                ['name' => 'Kimball', 'state_id' => 3968],
                ['name' => 'Pukwana', 'state_id' => 3968],
                ['name' => 'Fort Thompson', 'state_id' => 3968],
                ['name' => 'Gann Valley', 'state_id' => 3968],
                ['name' => 'Belle Fourche', 'state_id' => 3968],
                ['name' => 'Newell', 'state_id' => 3968],
                ['name' => 'Nisland', 'state_id' => 3968],
                ['name' => 'Vale', 'state_id' => 3968],
                ['name' => 'Herreid', 'state_id' => 3968],
                ['name' => 'Mound City', 'state_id' => 3968],
                ['name' => 'Pollock', 'state_id' => 3968],
                ['name' => 'Dante', 'state_id' => 3968],
                ['name' => 'Geddes', 'state_id' => 3968],
                ['name' => 'Lake Andes', 'state_id' => 3968],
                ['name' => 'Marty', 'state_id' => 3968],
                ['name' => 'Pickstown', 'state_id' => 3968],
                ['name' => 'Platte', 'state_id' => 3968],
                ['name' => 'Wagner', 'state_id' => 3968],
                ['name' => 'Bradley', 'state_id' => 3968],
                ['name' => 'Clark', 'state_id' => 3968],
                ['name' => 'Garden City', 'state_id' => 3968],
                ['name' => 'Raymond', 'state_id' => 3968],
                ['name' => 'Vienna', 'state_id' => 3968],
                ['name' => 'Willow Lake', 'state_id' => 3968],
                ['name' => 'Carpenter', 'state_id' => 3968],
                ['name' => 'Burbank', 'state_id' => 3968],
                ['name' => 'Irene', 'state_id' => 3968],
                ['name' => 'Vermillion', 'state_id' => 3968],
                ['name' => 'Wakonda', 'state_id' => 3968],
                ['name' => 'Watertown', 'state_id' => 3968],
                ['name' => 'Florence', 'state_id' => 3968],
                ['name' => 'Henry', 'state_id' => 3968],
                ['name' => 'Kranzburg', 'state_id' => 3968],
                ['name' => 'South Shore', 'state_id' => 3968],
                ['name' => 'Wallace', 'state_id' => 3968],
                ['name' => 'Bullhead', 'state_id' => 3968],
                ['name' => 'Keldron', 'state_id' => 3968],
                ['name' => 'Little Eagle', 'state_id' => 3968],
                ['name' => 'Mc Intosh', 'state_id' => 3968],
                ['name' => 'Mc Laughlin', 'state_id' => 3968],
                ['name' => 'Morristown', 'state_id' => 3968],
                ['name' => 'Trail City', 'state_id' => 3968],
                ['name' => 'Wakpala', 'state_id' => 3968],
                ['name' => 'Walker', 'state_id' => 3968],
                ['name' => 'Watauga', 'state_id' => 3968],
                ['name' => 'Buffalo Gap', 'state_id' => 3968],
                ['name' => 'Custer', 'state_id' => 3968],
                ['name' => 'Fairburn', 'state_id' => 3968],
                ['name' => 'Hermosa', 'state_id' => 3968],
                ['name' => 'Pringle', 'state_id' => 3968],
                ['name' => 'Mitchell', 'state_id' => 3968],
                ['name' => 'Ethan', 'state_id' => 3968],
                ['name' => 'Mount Vernon', 'state_id' => 3968],
                ['name' => 'Bristol', 'state_id' => 3968],
                ['name' => 'Grenville', 'state_id' => 3968],
                ['name' => 'Roslyn', 'state_id' => 3968],
                ['name' => 'Waubay', 'state_id' => 3968],
                ['name' => 'Webster', 'state_id' => 3968],
                ['name' => 'Andover', 'state_id' => 3968],
                ['name' => 'Pierpont', 'state_id' => 3968],
                ['name' => 'Astoria', 'state_id' => 3968],
                ['name' => 'Brandt', 'state_id' => 3968],
                ['name' => 'Clear Lake', 'state_id' => 3968],
                ['name' => 'Gary', 'state_id' => 3968],
                ['name' => 'Goodwin', 'state_id' => 3968],
                ['name' => 'Toronto', 'state_id' => 3968],
                ['name' => 'Eagle Butte', 'state_id' => 3968],
                ['name' => 'Glencross', 'state_id' => 3968],
                ['name' => 'Isabel', 'state_id' => 3968],
                ['name' => 'Lantry', 'state_id' => 3968],
                ['name' => 'Ridgeview', 'state_id' => 3968],
                ['name' => 'Timber Lake', 'state_id' => 3968],
                ['name' => 'Whitehorse', 'state_id' => 3968],
                ['name' => 'Armour', 'state_id' => 3968],
                ['name' => 'Corsica', 'state_id' => 3968],
                ['name' => 'Delmont', 'state_id' => 3968],
                ['name' => 'Harrison', 'state_id' => 3968],
                ['name' => 'New Holland', 'state_id' => 3968],
                ['name' => 'Bowdle', 'state_id' => 3968],
                ['name' => 'Hosmer', 'state_id' => 3968],
                ['name' => 'Ipswich', 'state_id' => 3968],
                ['name' => 'Roscoe', 'state_id' => 3968],
                ['name' => 'Edgemont', 'state_id' => 3968],
                ['name' => 'Hot Springs', 'state_id' => 3968],
                ['name' => 'Oelrichs', 'state_id' => 3968],
                ['name' => 'Oral', 'state_id' => 3968],
                ['name' => 'Smithwick', 'state_id' => 3968],
                ['name' => 'Cresbard', 'state_id' => 3968],
                ['name' => 'Faulkton', 'state_id' => 3968],
                ['name' => 'Onaka', 'state_id' => 3968],
                ['name' => 'Orient', 'state_id' => 3968],
                ['name' => 'Rockham', 'state_id' => 3968],
                ['name' => 'Seneca', 'state_id' => 3968],
                ['name' => 'Big Stone City', 'state_id' => 3968],
                ['name' => 'Labolt', 'state_id' => 3968],
                ['name' => 'Marvin', 'state_id' => 3968],
                ['name' => 'Milbank', 'state_id' => 3968],
                ['name' => 'Revillo', 'state_id' => 3968],
                ['name' => 'Stockholm', 'state_id' => 3968],
                ['name' => 'Strandburg', 'state_id' => 3968],
                ['name' => 'Twin Brooks', 'state_id' => 3968],
                ['name' => 'Bonesteel', 'state_id' => 3968],
                ['name' => 'Fairfax', 'state_id' => 3968],
                ['name' => 'Burke', 'state_id' => 3968],
                ['name' => 'Dallas', 'state_id' => 3968],
                ['name' => 'Gregory', 'state_id' => 3968],
                ['name' => 'Herrick', 'state_id' => 3968],
                ['name' => 'Saint Charles', 'state_id' => 3968],
                ['name' => 'Midland', 'state_id' => 3968],
                ['name' => 'Milesville', 'state_id' => 3968],
                ['name' => 'Philip', 'state_id' => 3968],
                ['name' => 'Bryant', 'state_id' => 3968],
                ['name' => 'Castlewood', 'state_id' => 3968],
                ['name' => 'Estelline', 'state_id' => 3968],
                ['name' => 'Hayti', 'state_id' => 3968],
                ['name' => 'Hazel', 'state_id' => 3968],
                ['name' => 'Lake Norden', 'state_id' => 3968],
                ['name' => 'Miller', 'state_id' => 3968],
                ['name' => 'Ree Heights', 'state_id' => 3968],
                ['name' => 'Saint Lawrence', 'state_id' => 3968],
                ['name' => 'Alexandria', 'state_id' => 3968],
                ['name' => 'Emery', 'state_id' => 3968],
                ['name' => 'Fulton', 'state_id' => 3968],
                ['name' => 'Ralph', 'state_id' => 3968],
                ['name' => 'Reva', 'state_id' => 3968],
                ['name' => 'Buffalo', 'state_id' => 3968],
                ['name' => 'Camp Crook', 'state_id' => 3968],
                ['name' => 'Ludlow', 'state_id' => 3968],
                ['name' => 'Redig', 'state_id' => 3968],
                ['name' => 'Pierre', 'state_id' => 3968],
                ['name' => 'Blunt', 'state_id' => 3968],
                ['name' => 'Harrold', 'state_id' => 3968],
                ['name' => 'Freeman', 'state_id' => 3968],
                ['name' => 'Menno', 'state_id' => 3968],
                ['name' => 'Olivet', 'state_id' => 3968],
                ['name' => 'Dimock', 'state_id' => 3968],
                ['name' => 'Kaylor', 'state_id' => 3968],
                ['name' => 'Parkston', 'state_id' => 3968],
                ['name' => 'Tripp', 'state_id' => 3968],
                ['name' => 'Highmore', 'state_id' => 3968],
                ['name' => 'Stephan', 'state_id' => 3968],
                ['name' => 'Holabird', 'state_id' => 3968],
                ['name' => 'Belvidere', 'state_id' => 3968],
                ['name' => 'Kadoka', 'state_id' => 3968],
                ['name' => 'Long Valley', 'state_id' => 3968],
                ['name' => 'Wanblee', 'state_id' => 3968],
                ['name' => 'Interior', 'state_id' => 3968],
                ['name' => 'Alpena', 'state_id' => 3968],
                ['name' => 'Lane', 'state_id' => 3968],
                ['name' => 'Wessington Springs', 'state_id' => 3968],
                ['name' => 'Draper', 'state_id' => 3968],
                ['name' => 'Murdo', 'state_id' => 3968],
                ['name' => 'Okaton', 'state_id' => 3968],
                ['name' => 'Oldham', 'state_id' => 3968],
                ['name' => 'Arlington', 'state_id' => 3968],
                ['name' => 'Badger', 'state_id' => 3968],
                ['name' => 'De Smet', 'state_id' => 3968],
                ['name' => 'Erwin', 'state_id' => 3968],
                ['name' => 'Lake Preston', 'state_id' => 3968],
                ['name' => 'Iroquois', 'state_id' => 3968],
                ['name' => 'Chester', 'state_id' => 3968],
                ['name' => 'Madison', 'state_id' => 3968],
                ['name' => 'Nunda', 'state_id' => 3968],
                ['name' => 'Ramona', 'state_id' => 3968],
                ['name' => 'Rutland', 'state_id' => 3968],
                ['name' => 'Wentworth', 'state_id' => 3968],
                ['name' => 'Winfred', 'state_id' => 3968],
                ['name' => 'Deadwood', 'state_id' => 3968],
                ['name' => 'Lead', 'state_id' => 3968],
                ['name' => 'Nemo', 'state_id' => 3968],
                ['name' => 'Saint Onge', 'state_id' => 3968],
                ['name' => 'Spearfish', 'state_id' => 3968],
                ['name' => 'Whitewood', 'state_id' => 3968],
                ['name' => 'Canton', 'state_id' => 3968],
                ['name' => 'Fairview', 'state_id' => 3968],
                ['name' => 'Harrisburg', 'state_id' => 3968],
                ['name' => 'Hudson', 'state_id' => 3968],
                ['name' => 'Lennox', 'state_id' => 3968],
                ['name' => 'Tea', 'state_id' => 3968],
                ['name' => 'Worthing', 'state_id' => 3968],
                ['name' => 'Oacoma', 'state_id' => 3968],
                ['name' => 'Kennebec', 'state_id' => 3968],
                ['name' => 'Lower Brule', 'state_id' => 3968],
                ['name' => 'Presho', 'state_id' => 3968],
                ['name' => 'Reliance', 'state_id' => 3968],
                ['name' => 'Vivian', 'state_id' => 3968],
                ['name' => 'Canistota', 'state_id' => 3968],
                ['name' => 'Montrose', 'state_id' => 3968],
                ['name' => 'Salem', 'state_id' => 3968],
                ['name' => 'Bridgewater', 'state_id' => 3968],
                ['name' => 'Spencer', 'state_id' => 3968],
                ['name' => 'Eureka', 'state_id' => 3968],
                ['name' => 'Leola', 'state_id' => 3968],
                ['name' => 'Long Lake', 'state_id' => 3968],
                ['name' => 'Eden', 'state_id' => 3968],
                ['name' => 'Lake City', 'state_id' => 3968],
                ['name' => 'Veblen', 'state_id' => 3968],
                ['name' => 'Amherst', 'state_id' => 3968],
                ['name' => 'Britton', 'state_id' => 3968],
                ['name' => 'Langford', 'state_id' => 3968],
                ['name' => 'Faith', 'state_id' => 3968],
                ['name' => 'Ellsworth Afb', 'state_id' => 3968],
                ['name' => 'Black Hawk', 'state_id' => 3968],
                ['name' => 'Enning', 'state_id' => 3968],
                ['name' => 'Fort Meade', 'state_id' => 3968],
                ['name' => 'Howes', 'state_id' => 3968],
                ['name' => 'Mud Butte', 'state_id' => 3968],
                ['name' => 'Piedmont', 'state_id' => 3968],
                ['name' => 'Sturgis', 'state_id' => 3968],
                ['name' => 'Union Center', 'state_id' => 3968],
                ['name' => 'White Owl', 'state_id' => 3968],
                ['name' => 'Norris', 'state_id' => 3968],
                ['name' => 'White River', 'state_id' => 3968],
                ['name' => 'Wood', 'state_id' => 3968],
                ['name' => 'Canova', 'state_id' => 3968],
                ['name' => 'Carthage', 'state_id' => 3968],
                ['name' => 'Fedora', 'state_id' => 3968],
                ['name' => 'Howard', 'state_id' => 3968],
                ['name' => 'Baltic', 'state_id' => 3968],
                ['name' => 'Brandon', 'state_id' => 3968],
                ['name' => 'Colton', 'state_id' => 3968],
                ['name' => 'Crooks', 'state_id' => 3968],
                ['name' => 'Dell Rapids', 'state_id' => 3968],
                ['name' => 'Garretson', 'state_id' => 3968],
                ['name' => 'Hartford', 'state_id' => 3968],
                ['name' => 'Humboldt', 'state_id' => 3968],
                ['name' => 'Lyons', 'state_id' => 3968],
                ['name' => 'Renner', 'state_id' => 3968],
                ['name' => 'Valley Springs', 'state_id' => 3968],
                ['name' => 'Sioux Falls', 'state_id' => 3968],
                ['name' => 'Colman', 'state_id' => 3968],
                ['name' => 'Egan', 'state_id' => 3968],
                ['name' => 'Flandreau', 'state_id' => 3968],
                ['name' => 'Trent', 'state_id' => 3968],
                ['name' => 'Rapid City', 'state_id' => 3968],
                ['name' => 'Box Elder', 'state_id' => 3968],
                ['name' => 'Caputa', 'state_id' => 3968],
                ['name' => 'Hill City', 'state_id' => 3968],
                ['name' => 'Keystone', 'state_id' => 3968],
                ['name' => 'New Underwood', 'state_id' => 3968],
                ['name' => 'Owanka', 'state_id' => 3968],
                ['name' => 'Quinn', 'state_id' => 3968],
                ['name' => 'Scenic', 'state_id' => 3968],
                ['name' => 'Wall', 'state_id' => 3968],
                ['name' => 'Wasta', 'state_id' => 3968],
                ['name' => 'Bison', 'state_id' => 3968],
                ['name' => 'Lemmon', 'state_id' => 3968],
                ['name' => 'Lodgepole', 'state_id' => 3968],
                ['name' => 'Meadow', 'state_id' => 3968],
                ['name' => 'Prairie City', 'state_id' => 3968],
                ['name' => 'Gettysburg', 'state_id' => 3968],
                ['name' => 'Hoven', 'state_id' => 3968],
                ['name' => 'Lebanon', 'state_id' => 3968],
                ['name' => 'Tolstoy', 'state_id' => 3968],
                ['name' => 'Claire City', 'state_id' => 3968],
                ['name' => 'Corona', 'state_id' => 3968],
                ['name' => 'New Effington', 'state_id' => 3968],
                ['name' => 'Ortley', 'state_id' => 3968],
                ['name' => 'Peever', 'state_id' => 3968],
                ['name' => 'Rosholt', 'state_id' => 3968],
                ['name' => 'Sisseton', 'state_id' => 3968],
                ['name' => 'Summit', 'state_id' => 3968],
                ['name' => 'Wilmot', 'state_id' => 3968],
                ['name' => 'Artesian', 'state_id' => 3968],
                ['name' => 'Letcher', 'state_id' => 3968],
                ['name' => 'Woonsocket', 'state_id' => 3968],
                ['name' => 'Batesland', 'state_id' => 3968],
                ['name' => 'Kyle', 'state_id' => 3968],
                ['name' => 'Manderson', 'state_id' => 3968],
                ['name' => 'Oglala', 'state_id' => 3968],
                ['name' => 'Pine Ridge', 'state_id' => 3968],
                ['name' => 'Porcupine', 'state_id' => 3968],
                ['name' => 'Wounded Knee', 'state_id' => 3968],
                ['name' => 'Ashton', 'state_id' => 3968],
                ['name' => 'Brentford', 'state_id' => 3968],
                ['name' => 'Conde', 'state_id' => 3968],
                ['name' => 'Doland', 'state_id' => 3968],
                ['name' => 'Frankfort', 'state_id' => 3968],
                ['name' => 'Mansfield', 'state_id' => 3968],
                ['name' => 'Mellette', 'state_id' => 3968],
                ['name' => 'Northville', 'state_id' => 3968],
                ['name' => 'Redfield', 'state_id' => 3968],
                ['name' => 'Tulare', 'state_id' => 3968],
                ['name' => 'Turton', 'state_id' => 3968],
                ['name' => 'Fort Pierre', 'state_id' => 3968],
                ['name' => 'Hayes', 'state_id' => 3968],
                ['name' => 'Agar', 'state_id' => 3968],
                ['name' => 'Onida', 'state_id' => 3968],
                ['name' => 'Mission', 'state_id' => 3968],
                ['name' => 'Okreek', 'state_id' => 3968],
                ['name' => 'Parmelee', 'state_id' => 3968],
                ['name' => 'Rosebud', 'state_id' => 3968],
                ['name' => 'Saint Francis', 'state_id' => 3968],
                ['name' => 'Colome', 'state_id' => 3968],
                ['name' => 'Hamill', 'state_id' => 3968],
                ['name' => 'Ideal', 'state_id' => 3968],
                ['name' => 'Winner', 'state_id' => 3968],
                ['name' => 'Witten', 'state_id' => 3968],
                ['name' => 'Centerville', 'state_id' => 3968],
                ['name' => 'Chancellor', 'state_id' => 3968],
                ['name' => 'Davis', 'state_id' => 3968],
                ['name' => 'Hurley', 'state_id' => 3968],
                ['name' => 'Marion', 'state_id' => 3968],
                ['name' => 'Monroe', 'state_id' => 3968],
                ['name' => 'Parker', 'state_id' => 3968],
                ['name' => 'Viborg', 'state_id' => 3968],
                ['name' => 'Alcester', 'state_id' => 3968],
                ['name' => 'Beresford', 'state_id' => 3968],
                ['name' => 'Elk Point', 'state_id' => 3968],
                ['name' => 'Jefferson', 'state_id' => 3968],
                ['name' => 'North Sioux City', 'state_id' => 3968],
                ['name' => 'Akaska', 'state_id' => 3968],
                ['name' => 'Java', 'state_id' => 3968],
                ['name' => 'Selby', 'state_id' => 3968],
                ['name' => 'Mobridge', 'state_id' => 3968],
                ['name' => 'Glenham', 'state_id' => 3968],
                ['name' => 'Gayville', 'state_id' => 3968],
                ['name' => 'Lesterville', 'state_id' => 3968],
                ['name' => 'Mission Hill', 'state_id' => 3968],
                ['name' => 'Utica', 'state_id' => 3968],
                ['name' => 'Volin', 'state_id' => 3968],
                ['name' => 'Yankton', 'state_id' => 3968],
                ['name' => 'Cherry Creek', 'state_id' => 3968],
                ['name' => 'Dupree', 'state_id' => 3968]
            ]);
        }
    }
}
