<?php

use Illuminate\Database\Seeder;

class state49TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WI - Wisconsin.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Adams', 'state_id' => 3978],
                ['name' => 'Dellwood', 'state_id' => 3978],
                ['name' => 'Friendship', 'state_id' => 3978],
                ['name' => 'Grand Marsh', 'state_id' => 3978],
                ['name' => 'Arkdale', 'state_id' => 3978],
                ['name' => 'Butternut', 'state_id' => 3978],
                ['name' => 'Clam Lake', 'state_id' => 3978],
                ['name' => 'Glidden', 'state_id' => 3978],
                ['name' => 'Mellen', 'state_id' => 3978],
                ['name' => 'Ashland', 'state_id' => 3978],
                ['name' => 'High Bridge', 'state_id' => 3978],
                ['name' => 'La Pointe', 'state_id' => 3978],
                ['name' => 'Marengo', 'state_id' => 3978],
                ['name' => 'Odanah', 'state_id' => 3978],
                ['name' => 'Chetek', 'state_id' => 3978],
                ['name' => 'Dallas', 'state_id' => 3978],
                ['name' => 'Prairie Farm', 'state_id' => 3978],
                ['name' => 'Almena', 'state_id' => 3978],
                ['name' => 'Barron', 'state_id' => 3978],
                ['name' => 'Barronett', 'state_id' => 3978],
                ['name' => 'Brill', 'state_id' => 3978],
                ['name' => 'Cameron', 'state_id' => 3978],
                ['name' => 'Comstock', 'state_id' => 3978],
                ['name' => 'Cumberland', 'state_id' => 3978],
                ['name' => 'Haugen', 'state_id' => 3978],
                ['name' => 'Mikana', 'state_id' => 3978],
                ['name' => 'Rice Lake', 'state_id' => 3978],
                ['name' => 'Turtle Lake', 'state_id' => 3978],
                ['name' => 'Bayfield', 'state_id' => 3978],
                ['name' => 'Benoit', 'state_id' => 3978],
                ['name' => 'Cable', 'state_id' => 3978],
                ['name' => 'Cornucopia', 'state_id' => 3978],
                ['name' => 'Drummond', 'state_id' => 3978],
                ['name' => 'Grand View', 'state_id' => 3978],
                ['name' => 'Herbster', 'state_id' => 3978],
                ['name' => 'Iron River', 'state_id' => 3978],
                ['name' => 'Mason', 'state_id' => 3978],
                ['name' => 'Port Wing', 'state_id' => 3978],
                ['name' => 'Washburn', 'state_id' => 3978],
                ['name' => 'De Pere', 'state_id' => 3978],
                ['name' => 'Greenleaf', 'state_id' => 3978],
                ['name' => 'Pulaski', 'state_id' => 3978],
                ['name' => 'Suamico', 'state_id' => 3978],
                ['name' => 'Wrightstown', 'state_id' => 3978],
                ['name' => 'Denmark', 'state_id' => 3978],
                ['name' => 'New Franken', 'state_id' => 3978],
                ['name' => 'Green Bay', 'state_id' => 3978],
                ['name' => 'Alma', 'state_id' => 3978],
                ['name' => 'Cochrane', 'state_id' => 3978],
                ['name' => 'Fountain City', 'state_id' => 3978],
                ['name' => 'Gilmanton', 'state_id' => 3978],
                ['name' => 'Mondovi', 'state_id' => 3978],
                ['name' => 'Nelson', 'state_id' => 3978],
                ['name' => 'Danbury', 'state_id' => 3978],
                ['name' => 'Grantsburg', 'state_id' => 3978],
                ['name' => 'Hertel', 'state_id' => 3978],
                ['name' => 'Siren', 'state_id' => 3978],
                ['name' => 'Webster', 'state_id' => 3978],
                ['name' => 'Chilton', 'state_id' => 3978],
                ['name' => 'New Holstein', 'state_id' => 3978],
                ['name' => 'Stockbridge', 'state_id' => 3978],
                ['name' => 'Brillion', 'state_id' => 3978],
                ['name' => 'Forest Junction', 'state_id' => 3978],
                ['name' => 'Hilbert', 'state_id' => 3978],
                ['name' => 'Potter', 'state_id' => 3978],
                ['name' => 'Sherwood', 'state_id' => 3978],
                ['name' => 'Bloomer', 'state_id' => 3978],
                ['name' => 'Boyd', 'state_id' => 3978],
                ['name' => 'Cadott', 'state_id' => 3978],
                ['name' => 'Chippewa Falls', 'state_id' => 3978],
                ['name' => 'Cornell', 'state_id' => 3978],
                ['name' => 'Holcombe', 'state_id' => 3978],
                ['name' => 'Jim Falls', 'state_id' => 3978],
                ['name' => 'New Auburn', 'state_id' => 3978],
                ['name' => 'Stanley', 'state_id' => 3978],
                ['name' => 'Abbotsford', 'state_id' => 3978],
                ['name' => 'Chili', 'state_id' => 3978],
                ['name' => 'Colby', 'state_id' => 3978],
                ['name' => 'Curtiss', 'state_id' => 3978],
                ['name' => 'Dorchester', 'state_id' => 3978],
                ['name' => 'Granton', 'state_id' => 3978],
                ['name' => 'Greenwood', 'state_id' => 3978],
                ['name' => 'Loyal', 'state_id' => 3978],
                ['name' => 'Neillsville', 'state_id' => 3978],
                ['name' => 'Owen', 'state_id' => 3978],
                ['name' => 'Willard', 'state_id' => 3978],
                ['name' => 'Withee', 'state_id' => 3978],
                ['name' => 'Humbird', 'state_id' => 3978],
                ['name' => 'Thorp', 'state_id' => 3978],
                ['name' => 'Lodi', 'state_id' => 3978],
                ['name' => 'Portage', 'state_id' => 3978],
                ['name' => 'Arlington', 'state_id' => 3978],
                ['name' => 'Cambria', 'state_id' => 3978],
                ['name' => 'Columbus', 'state_id' => 3978],
                ['name' => 'Doylestown', 'state_id' => 3978],
                ['name' => 'Fall River', 'state_id' => 3978],
                ['name' => 'Friesland', 'state_id' => 3978],
                ['name' => 'Pardeeville', 'state_id' => 3978],
                ['name' => 'Poynette', 'state_id' => 3978],
                ['name' => 'Randolph', 'state_id' => 3978],
                ['name' => 'Rio', 'state_id' => 3978],
                ['name' => 'Wisconsin Dells', 'state_id' => 3978],
                ['name' => 'Wyocena', 'state_id' => 3978],
                ['name' => 'Prairie Du Chien', 'state_id' => 3978],
                ['name' => 'Wauzeka', 'state_id' => 3978],
                ['name' => 'Eastman', 'state_id' => 3978],
                ['name' => 'Ferryville', 'state_id' => 3978],
                ['name' => 'Gays Mills', 'state_id' => 3978],
                ['name' => 'Lynxville', 'state_id' => 3978],
                ['name' => 'Mount Sterling', 'state_id' => 3978],
                ['name' => 'Seneca', 'state_id' => 3978],
                ['name' => 'Soldiers Grove', 'state_id' => 3978],
                ['name' => 'Steuben', 'state_id' => 3978],
                ['name' => 'Belleville', 'state_id' => 3978],
                ['name' => 'Black Earth', 'state_id' => 3978],
                ['name' => 'Blue Mounds', 'state_id' => 3978],
                ['name' => 'Cambridge', 'state_id' => 3978],
                ['name' => 'Cottage Grove', 'state_id' => 3978],
                ['name' => 'Cross Plains', 'state_id' => 3978],
                ['name' => 'Dane', 'state_id' => 3978],
                ['name' => 'Deerfield', 'state_id' => 3978],
                ['name' => 'Deforest', 'state_id' => 3978],
                ['name' => 'Mc Farland', 'state_id' => 3978],
                ['name' => 'Marshall', 'state_id' => 3978],
                ['name' => 'Mazomanie', 'state_id' => 3978],
                ['name' => 'Middleton', 'state_id' => 3978],
                ['name' => 'Morrisonville', 'state_id' => 3978],
                ['name' => 'Mount Horeb', 'state_id' => 3978],
                ['name' => 'Oregon', 'state_id' => 3978],
                ['name' => 'Stoughton', 'state_id' => 3978],
                ['name' => 'Sun Prairie', 'state_id' => 3978],
                ['name' => 'Verona', 'state_id' => 3978],
                ['name' => 'Waunakee', 'state_id' => 3978],
                ['name' => 'Windsor', 'state_id' => 3978],
                ['name' => 'Madison', 'state_id' => 3978],
                ['name' => 'Ashippun', 'state_id' => 3978],
                ['name' => 'Brownsville', 'state_id' => 3978],
                ['name' => 'Clyman', 'state_id' => 3978],
                ['name' => 'Horicon', 'state_id' => 3978],
                ['name' => 'Hustisford', 'state_id' => 3978],
                ['name' => 'Iron Ridge', 'state_id' => 3978],
                ['name' => 'Juneau', 'state_id' => 3978],
                ['name' => 'Lebanon', 'state_id' => 3978],
                ['name' => 'Lomira', 'state_id' => 3978],
                ['name' => 'Mayville', 'state_id' => 3978],
                ['name' => 'Neosho', 'state_id' => 3978],
                ['name' => 'Rubicon', 'state_id' => 3978],
                ['name' => 'Theresa', 'state_id' => 3978],
                ['name' => 'Watertown', 'state_id' => 3978],
                ['name' => 'Woodland', 'state_id' => 3978],
                ['name' => 'Lowell', 'state_id' => 3978],
                ['name' => 'Reeseville', 'state_id' => 3978],
                ['name' => 'Beaver Dam', 'state_id' => 3978],
                ['name' => 'Burnett', 'state_id' => 3978],
                ['name' => 'Fox Lake', 'state_id' => 3978],
                ['name' => 'Waupun', 'state_id' => 3978],
                ['name' => 'Baileys Harbor', 'state_id' => 3978],
                ['name' => 'Brussels', 'state_id' => 3978],
                ['name' => 'Egg Harbor', 'state_id' => 3978],
                ['name' => 'Ellison Bay', 'state_id' => 3978],
                ['name' => 'Ephraim', 'state_id' => 3978],
                ['name' => 'Fish Creek', 'state_id' => 3978],
                ['name' => 'Forestville', 'state_id' => 3978],
                ['name' => 'Maplewood', 'state_id' => 3978],
                ['name' => 'Sister Bay', 'state_id' => 3978],
                ['name' => 'Sturgeon Bay', 'state_id' => 3978],
                ['name' => 'Washington Island', 'state_id' => 3978],
                ['name' => 'Brule', 'state_id' => 3978],
                ['name' => 'Foxboro', 'state_id' => 3978],
                ['name' => 'Gordon', 'state_id' => 3978],
                ['name' => 'Hawthorne', 'state_id' => 3978],
                ['name' => 'Lake Nebagamon', 'state_id' => 3978],
                ['name' => 'Maple', 'state_id' => 3978],
                ['name' => 'Poplar', 'state_id' => 3978],
                ['name' => 'Solon Springs', 'state_id' => 3978],
                ['name' => 'South Range', 'state_id' => 3978],
                ['name' => 'Superior', 'state_id' => 3978],
                ['name' => 'Wascott', 'state_id' => 3978],
                ['name' => 'Boyceville', 'state_id' => 3978],
                ['name' => 'Colfax', 'state_id' => 3978],
                ['name' => 'Downing', 'state_id' => 3978],
                ['name' => 'Downsville', 'state_id' => 3978],
                ['name' => 'Eau Galle', 'state_id' => 3978],
                ['name' => 'Elk Mound', 'state_id' => 3978],
                ['name' => 'Knapp', 'state_id' => 3978],
                ['name' => 'Menomonie', 'state_id' => 3978],
                ['name' => 'Ridgeland', 'state_id' => 3978],
                ['name' => 'Rock Falls', 'state_id' => 3978],
                ['name' => 'Sand Creek', 'state_id' => 3978],
                ['name' => 'Wheeler', 'state_id' => 3978],
                ['name' => 'Eau Claire', 'state_id' => 3978],
                ['name' => 'Altoona', 'state_id' => 3978],
                ['name' => 'Augusta', 'state_id' => 3978],
                ['name' => 'Fairchild', 'state_id' => 3978],
                ['name' => 'Fall Creek', 'state_id' => 3978],
                ['name' => 'Fence', 'state_id' => 3978],
                ['name' => 'Florence', 'state_id' => 3978],
                ['name' => 'Long Lake', 'state_id' => 3978],
                ['name' => 'Campbellsport', 'state_id' => 3978],
                ['name' => 'Eden', 'state_id' => 3978],
                ['name' => 'Malone', 'state_id' => 3978],
                ['name' => 'Mount Calvary', 'state_id' => 3978],
                ['name' => 'Oakfield', 'state_id' => 3978],
                ['name' => 'Saint Cloud', 'state_id' => 3978],
                ['name' => 'Brandon', 'state_id' => 3978],
                ['name' => 'Fairwater', 'state_id' => 3978],
                ['name' => 'Eldorado', 'state_id' => 3978],
                ['name' => 'Fond Du Lac', 'state_id' => 3978],
                ['name' => 'Ripon', 'state_id' => 3978],
                ['name' => 'Rosendale', 'state_id' => 3978],
                ['name' => 'Van Dyne', 'state_id' => 3978],
                ['name' => 'Armstrong Creek', 'state_id' => 3978],
                ['name' => 'Argonne', 'state_id' => 3978],
                ['name' => 'Crandon', 'state_id' => 3978],
                ['name' => 'Laona', 'state_id' => 3978],
                ['name' => 'Wabeno', 'state_id' => 3978],
                ['name' => 'Blue River', 'state_id' => 3978],
                ['name' => 'Livingston', 'state_id' => 3978],
                ['name' => 'Montfort', 'state_id' => 3978],
                ['name' => 'Muscoda', 'state_id' => 3978],
                ['name' => 'Bagley', 'state_id' => 3978],
                ['name' => 'Beetown', 'state_id' => 3978],
                ['name' => 'Bloomington', 'state_id' => 3978],
                ['name' => 'Boscobel', 'state_id' => 3978],
                ['name' => 'Cassville', 'state_id' => 3978],
                ['name' => 'Cuba City', 'state_id' => 3978],
                ['name' => 'Dickeyville', 'state_id' => 3978],
                ['name' => 'Fennimore', 'state_id' => 3978],
                ['name' => 'Glen Haven', 'state_id' => 3978],
                ['name' => 'Hazel Green', 'state_id' => 3978],
                ['name' => 'Kieler', 'state_id' => 3978],
                ['name' => 'Lancaster', 'state_id' => 3978],
                ['name' => 'Mount Hope', 'state_id' => 3978],
                ['name' => 'Patch Grove', 'state_id' => 3978],
                ['name' => 'Platteville', 'state_id' => 3978],
                ['name' => 'Potosi', 'state_id' => 3978],
                ['name' => 'Sinsinawa', 'state_id' => 3978],
                ['name' => 'Stitzer', 'state_id' => 3978],
                ['name' => 'Woodman', 'state_id' => 3978],
                ['name' => 'Albany', 'state_id' => 3978],
                ['name' => 'Brodhead', 'state_id' => 3978],
                ['name' => 'Brooklyn', 'state_id' => 3978],
                ['name' => 'Browntown', 'state_id' => 3978],
                ['name' => 'Juda', 'state_id' => 3978],
                ['name' => 'Monroe', 'state_id' => 3978],
                ['name' => 'Monticello', 'state_id' => 3978],
                ['name' => 'New Glarus', 'state_id' => 3978],
                ['name' => 'Dalton', 'state_id' => 3978],
                ['name' => 'Kingston', 'state_id' => 3978],
                ['name' => 'Markesan', 'state_id' => 3978],
                ['name' => 'Marquette', 'state_id' => 3978],
                ['name' => 'Berlin', 'state_id' => 3978],
                ['name' => 'Green Lake', 'state_id' => 3978],
                ['name' => 'Princeton', 'state_id' => 3978],
                ['name' => 'Arena', 'state_id' => 3978],
                ['name' => 'Avoca', 'state_id' => 3978],
                ['name' => 'Barneveld', 'state_id' => 3978],
                ['name' => 'Cobb', 'state_id' => 3978],
                ['name' => 'Dodgeville', 'state_id' => 3978],
                ['name' => 'Edmund', 'state_id' => 3978],
                ['name' => 'Highland', 'state_id' => 3978],
                ['name' => 'Hollandale', 'state_id' => 3978],
                ['name' => 'Linden', 'state_id' => 3978],
                ['name' => 'Mineral Point', 'state_id' => 3978],
                ['name' => 'Rewey', 'state_id' => 3978],
                ['name' => 'Ridgeway', 'state_id' => 3978],
                ['name' => 'Gile', 'state_id' => 3978],
                ['name' => 'Hurley', 'state_id' => 3978],
                ['name' => 'Iron Belt', 'state_id' => 3978],
                ['name' => 'Mercer', 'state_id' => 3978],
                ['name' => 'Montreal', 'state_id' => 3978],
                ['name' => 'Saxon', 'state_id' => 3978],
                ['name' => 'Upson', 'state_id' => 3978],
                ['name' => 'Alma Center', 'state_id' => 3978],
                ['name' => 'Black River Falls', 'state_id' => 3978],
                ['name' => 'Hixton', 'state_id' => 3978],
                ['name' => 'Melrose', 'state_id' => 3978],
                ['name' => 'Millston', 'state_id' => 3978],
                ['name' => 'Taylor', 'state_id' => 3978],
                ['name' => 'Merrillan', 'state_id' => 3978],
                ['name' => 'Ixonia', 'state_id' => 3978],
                ['name' => 'Johnson Creek', 'state_id' => 3978],
                ['name' => 'Helenville', 'state_id' => 3978],
                ['name' => 'Palmyra', 'state_id' => 3978],
                ['name' => 'Sullivan', 'state_id' => 3978],
                ['name' => 'Fort Atkinson', 'state_id' => 3978],
                ['name' => 'Jefferson', 'state_id' => 3978],
                ['name' => 'Lake Mills', 'state_id' => 3978],
                ['name' => 'Waterloo', 'state_id' => 3978],
                ['name' => 'Elroy', 'state_id' => 3978],
                ['name' => 'Lyndon Station', 'state_id' => 3978],
                ['name' => 'Mauston', 'state_id' => 3978],
                ['name' => 'New Lisbon', 'state_id' => 3978],
                ['name' => 'Union Center', 'state_id' => 3978],
                ['name' => 'Wonewoc', 'state_id' => 3978],
                ['name' => 'Camp Douglas', 'state_id' => 3978],
                ['name' => 'Hustler', 'state_id' => 3978],
                ['name' => 'Mather', 'state_id' => 3978],
                ['name' => 'Necedah', 'state_id' => 3978],
                ['name' => 'Bassett', 'state_id' => 3978],
                ['name' => 'Benet Lake', 'state_id' => 3978],
                ['name' => 'Bristol', 'state_id' => 3978],
                ['name' => 'Camp Lake', 'state_id' => 3978],
                ['name' => 'Kenosha', 'state_id' => 3978],
                ['name' => 'New Munster', 'state_id' => 3978],
                ['name' => 'Pleasant Prairie', 'state_id' => 3978],
                ['name' => 'Powers Lake', 'state_id' => 3978],
                ['name' => 'Salem', 'state_id' => 3978],
                ['name' => 'Silver Lake', 'state_id' => 3978],
                ['name' => 'Somers', 'state_id' => 3978],
                ['name' => 'Trevor', 'state_id' => 3978],
                ['name' => 'Twin Lakes', 'state_id' => 3978],
                ['name' => 'Wilmot', 'state_id' => 3978],
                ['name' => 'Woodworth', 'state_id' => 3978],
                ['name' => 'Algoma', 'state_id' => 3978],
                ['name' => 'Casco', 'state_id' => 3978],
                ['name' => 'Kewaunee', 'state_id' => 3978],
                ['name' => 'Luxemburg', 'state_id' => 3978],
                ['name' => 'La Crosse', 'state_id' => 3978],
                ['name' => 'Bangor', 'state_id' => 3978],
                ['name' => 'Holmen', 'state_id' => 3978],
                ['name' => 'Mindoro', 'state_id' => 3978],
                ['name' => 'Onalaska', 'state_id' => 3978],
                ['name' => 'Rockland', 'state_id' => 3978],
                ['name' => 'West Salem', 'state_id' => 3978],
                ['name' => 'Argyle', 'state_id' => 3978],
                ['name' => 'Belmont', 'state_id' => 3978],
                ['name' => 'Blanchardville', 'state_id' => 3978],
                ['name' => 'Darlington', 'state_id' => 3978],
                ['name' => 'Gratiot', 'state_id' => 3978],
                ['name' => 'Shullsburg', 'state_id' => 3978],
                ['name' => 'South Wayne', 'state_id' => 3978],
                ['name' => 'Woodford', 'state_id' => 3978],
                ['name' => 'Benton', 'state_id' => 3978],
                ['name' => 'Antigo', 'state_id' => 3978],
                ['name' => 'Bryant', 'state_id' => 3978],
                ['name' => 'Deerbrook', 'state_id' => 3978],
                ['name' => 'Elcho', 'state_id' => 3978],
                ['name' => 'Elton', 'state_id' => 3978],
                ['name' => 'Pearson', 'state_id' => 3978],
                ['name' => 'Phlox', 'state_id' => 3978],
                ['name' => 'Pickerel', 'state_id' => 3978],
                ['name' => 'Summit Lake', 'state_id' => 3978],
                ['name' => 'White Lake', 'state_id' => 3978],
                ['name' => 'Gleason', 'state_id' => 3978],
                ['name' => 'Irma', 'state_id' => 3978],
                ['name' => 'Merrill', 'state_id' => 3978],
                ['name' => 'Tomahawk', 'state_id' => 3978],
                ['name' => 'Heafford Junction', 'state_id' => 3978],
                ['name' => 'Cleveland', 'state_id' => 3978],
                ['name' => 'Kiel', 'state_id' => 3978],
                ['name' => 'Newton', 'state_id' => 3978],
                ['name' => 'Collins', 'state_id' => 3978],
                ['name' => 'Francis Creek', 'state_id' => 3978],
                ['name' => 'Kellnersville', 'state_id' => 3978],
                ['name' => 'Manitowoc', 'state_id' => 3978],
                ['name' => 'Maribel', 'state_id' => 3978],
                ['name' => 'Mishicot', 'state_id' => 3978],
                ['name' => 'Reedsville', 'state_id' => 3978],
                ['name' => 'Saint Nazianz', 'state_id' => 3978],
                ['name' => 'Tisch Mills', 'state_id' => 3978],
                ['name' => 'Two Rivers', 'state_id' => 3978],
                ['name' => 'Valders', 'state_id' => 3978],
                ['name' => 'Whitelaw', 'state_id' => 3978],
                ['name' => 'Wausau', 'state_id' => 3978],
                ['name' => 'Aniwa', 'state_id' => 3978],
                ['name' => 'Athens', 'state_id' => 3978],
                ['name' => 'Brokaw', 'state_id' => 3978],
                ['name' => 'Edgar', 'state_id' => 3978],
                ['name' => 'Eland', 'state_id' => 3978],
                ['name' => 'Elderon', 'state_id' => 3978],
                ['name' => 'Galloway', 'state_id' => 3978],
                ['name' => 'Hatley', 'state_id' => 3978],
                ['name' => 'Marathon', 'state_id' => 3978],
                ['name' => 'Mosinee', 'state_id' => 3978],
                ['name' => 'Ringle', 'state_id' => 3978],
                ['name' => 'Rothschild', 'state_id' => 3978],
                ['name' => 'Schofield', 'state_id' => 3978],
                ['name' => 'Spencer', 'state_id' => 3978],
                ['name' => 'Stratford', 'state_id' => 3978],
                ['name' => 'Unity', 'state_id' => 3978],
                ['name' => 'Amberg', 'state_id' => 3978],
                ['name' => 'Athelstane', 'state_id' => 3978],
                ['name' => 'Coleman', 'state_id' => 3978],
                ['name' => 'Crivitz', 'state_id' => 3978],
                ['name' => 'Dunbar', 'state_id' => 3978],
                ['name' => 'Goodman', 'state_id' => 3978],
                ['name' => 'Marinette', 'state_id' => 3978],
                ['name' => 'Niagara', 'state_id' => 3978],
                ['name' => 'Pembine', 'state_id' => 3978],
                ['name' => 'Peshtigo', 'state_id' => 3978],
                ['name' => 'Porterfield', 'state_id' => 3978],
                ['name' => 'Pound', 'state_id' => 3978],
                ['name' => 'Wausaukee', 'state_id' => 3978],
                ['name' => 'Briggsville', 'state_id' => 3978],
                ['name' => 'Endeavor', 'state_id' => 3978],
                ['name' => 'Montello', 'state_id' => 3978],
                ['name' => 'Oxford', 'state_id' => 3978],
                ['name' => 'Packwaukee', 'state_id' => 3978],
                ['name' => 'Westfield', 'state_id' => 3978],
                ['name' => 'Neshkoro', 'state_id' => 3978],
                ['name' => 'Keshena', 'state_id' => 3978],
                ['name' => 'Neopit', 'state_id' => 3978],
                ['name' => 'Cudahy', 'state_id' => 3978],
                ['name' => 'Greendale', 'state_id' => 3978],
                ['name' => 'Hales Corners', 'state_id' => 3978],
                ['name' => 'Franklin', 'state_id' => 3978],
                ['name' => 'Oak Creek', 'state_id' => 3978],
                ['name' => 'South Milwaukee', 'state_id' => 3978],
                ['name' => 'Milwaukee', 'state_id' => 3978],
                ['name' => 'Saint Francis', 'state_id' => 3978],
                ['name' => 'Cashton', 'state_id' => 3978],
                ['name' => 'Cataract', 'state_id' => 3978],
                ['name' => 'Kendall', 'state_id' => 3978],
                ['name' => 'Norwalk', 'state_id' => 3978],
                ['name' => 'Oakdale', 'state_id' => 3978],
                ['name' => 'Sparta', 'state_id' => 3978],
                ['name' => 'Tomah', 'state_id' => 3978],
                ['name' => 'Tunnel City', 'state_id' => 3978],
                ['name' => 'Warrens', 'state_id' => 3978],
                ['name' => 'Wilton', 'state_id' => 3978],
                ['name' => 'Abrams', 'state_id' => 3978],
                ['name' => 'Gillett', 'state_id' => 3978],
                ['name' => 'Lakewood', 'state_id' => 3978],
                ['name' => 'Lena', 'state_id' => 3978],
                ['name' => 'Little Suamico', 'state_id' => 3978],
                ['name' => 'Mountain', 'state_id' => 3978],
                ['name' => 'Oconto', 'state_id' => 3978],
                ['name' => 'Oconto Falls', 'state_id' => 3978],
                ['name' => 'Sobieski', 'state_id' => 3978],
                ['name' => 'Suring', 'state_id' => 3978],
                ['name' => 'Townsend', 'state_id' => 3978],
                ['name' => 'Pelican Lake', 'state_id' => 3978],
                ['name' => 'Rhinelander', 'state_id' => 3978],
                ['name' => 'Harshaw', 'state_id' => 3978],
                ['name' => 'Hazelhurst', 'state_id' => 3978],
                ['name' => 'Lake Tomahawk', 'state_id' => 3978],
                ['name' => 'Mc Naughton', 'state_id' => 3978],
                ['name' => 'Minocqua', 'state_id' => 3978],
                ['name' => 'Three Lakes', 'state_id' => 3978],
                ['name' => 'Tripoli', 'state_id' => 3978],
                ['name' => 'Woodruff', 'state_id' => 3978],
                ['name' => 'Black Creek', 'state_id' => 3978],
                ['name' => 'Combined Locks', 'state_id' => 3978],
                ['name' => 'Kaukauna', 'state_id' => 3978],
                ['name' => 'Freedom', 'state_id' => 3978],
                ['name' => 'Kimberly', 'state_id' => 3978],
                ['name' => 'Little Chute', 'state_id' => 3978],
                ['name' => 'Nichols', 'state_id' => 3978],
                ['name' => 'Oneida', 'state_id' => 3978],
                ['name' => 'Seymour', 'state_id' => 3978],
                ['name' => 'Shiocton', 'state_id' => 3978],
                ['name' => 'Appleton', 'state_id' => 3978],
                ['name' => 'Bear Creek', 'state_id' => 3978],
                ['name' => 'Dale', 'state_id' => 3978],
                ['name' => 'Greenville', 'state_id' => 3978],
                ['name' => 'Hortonville', 'state_id' => 3978],
                ['name' => 'Belgium', 'state_id' => 3978],
                ['name' => 'Cedarburg', 'state_id' => 3978],
                ['name' => 'Fredonia', 'state_id' => 3978],
                ['name' => 'Grafton', 'state_id' => 3978],
                ['name' => 'Port Washington', 'state_id' => 3978],
                ['name' => 'Saukville', 'state_id' => 3978],
                ['name' => 'Mequon', 'state_id' => 3978],
                ['name' => 'Arkansaw', 'state_id' => 3978],
                ['name' => 'Durand', 'state_id' => 3978],
                ['name' => 'Pepin', 'state_id' => 3978],
                ['name' => 'Stockholm', 'state_id' => 3978],
                ['name' => 'Beldenville', 'state_id' => 3978],
                ['name' => 'East Ellsworth', 'state_id' => 3978],
                ['name' => 'Ellsworth', 'state_id' => 3978],
                ['name' => 'Hager City', 'state_id' => 3978],
                ['name' => 'Prescott', 'state_id' => 3978],
                ['name' => 'River Falls', 'state_id' => 3978],
                ['name' => 'Bay City', 'state_id' => 3978],
                ['name' => 'Elmwood', 'state_id' => 3978],
                ['name' => 'Maiden Rock', 'state_id' => 3978],
                ['name' => 'Plum City', 'state_id' => 3978],
                ['name' => 'Spring Valley', 'state_id' => 3978],
                ['name' => 'Amery', 'state_id' => 3978],
                ['name' => 'Clayton', 'state_id' => 3978],
                ['name' => 'Clear Lake', 'state_id' => 3978],
                ['name' => 'Cushing', 'state_id' => 3978],
                ['name' => 'Dresser', 'state_id' => 3978],
                ['name' => 'Osceola', 'state_id' => 3978],
                ['name' => 'Saint Croix Falls', 'state_id' => 3978],
                ['name' => 'Star Prairie', 'state_id' => 3978],
                ['name' => 'Balsam Lake', 'state_id' => 3978],
                ['name' => 'Centuria', 'state_id' => 3978],
                ['name' => 'Frederic', 'state_id' => 3978],
                ['name' => 'Luck', 'state_id' => 3978],
                ['name' => 'Milltown', 'state_id' => 3978],
                ['name' => 'Amherst', 'state_id' => 3978],
                ['name' => 'Amherst Junction', 'state_id' => 3978],
                ['name' => 'Custer', 'state_id' => 3978],
                ['name' => 'Junction City', 'state_id' => 3978],
                ['name' => 'Nelsonville', 'state_id' => 3978],
                ['name' => 'Plover', 'state_id' => 3978],
                ['name' => 'Rosholt', 'state_id' => 3978],
                ['name' => 'Stevens Point', 'state_id' => 3978],
                ['name' => 'Almond', 'state_id' => 3978],
                ['name' => 'Bancroft', 'state_id' => 3978],
                ['name' => 'Ogema', 'state_id' => 3978],
                ['name' => 'Brantwood', 'state_id' => 3978],
                ['name' => 'Catawba', 'state_id' => 3978],
                ['name' => 'Fifield', 'state_id' => 3978],
                ['name' => 'Kennan', 'state_id' => 3978],
                ['name' => 'Park Falls', 'state_id' => 3978],
                ['name' => 'Phillips', 'state_id' => 3978],
                ['name' => 'Prentice', 'state_id' => 3978],
                ['name' => 'Burlington', 'state_id' => 3978],
                ['name' => 'Caledonia', 'state_id' => 3978],
                ['name' => 'Franksville', 'state_id' => 3978],
                ['name' => 'Kansasville', 'state_id' => 3978],
                ['name' => 'Rochester', 'state_id' => 3978],
                ['name' => 'Sturtevant', 'state_id' => 3978],
                ['name' => 'Union Grove', 'state_id' => 3978],
                ['name' => 'Waterford', 'state_id' => 3978],
                ['name' => 'Racine', 'state_id' => 3978],
                ['name' => 'Gotham', 'state_id' => 3978],
                ['name' => 'Lone Rock', 'state_id' => 3978],
                ['name' => 'Richland Center', 'state_id' => 3978],
                ['name' => 'Sextonville', 'state_id' => 3978],
                ['name' => 'Cazenovia', 'state_id' => 3978],
                ['name' => 'Afton', 'state_id' => 3978],
                ['name' => 'Avalon', 'state_id' => 3978],
                ['name' => 'Beloit', 'state_id' => 3978],
                ['name' => 'Clinton', 'state_id' => 3978],
                ['name' => 'Edgerton', 'state_id' => 3978],
                ['name' => 'Evansville', 'state_id' => 3978],
                ['name' => 'Footville', 'state_id' => 3978],
                ['name' => 'Hanover', 'state_id' => 3978],
                ['name' => 'Janesville', 'state_id' => 3978],
                ['name' => 'Milton', 'state_id' => 3978],
                ['name' => 'Orfordville', 'state_id' => 3978],
                ['name' => 'Glen Flora', 'state_id' => 3978],
                ['name' => 'Hawkins', 'state_id' => 3978],
                ['name' => 'Tony', 'state_id' => 3978],
                ['name' => 'Conrath', 'state_id' => 3978],
                ['name' => 'Sheldon', 'state_id' => 3978],
                ['name' => 'Bruce', 'state_id' => 3978],
                ['name' => 'Ladysmith', 'state_id' => 3978],
                ['name' => 'Weyerhaeuser', 'state_id' => 3978],
                ['name' => 'Baldwin', 'state_id' => 3978],
                ['name' => 'Deer Park', 'state_id' => 3978],
                ['name' => 'Glenwood City', 'state_id' => 3978],
                ['name' => 'Hammond', 'state_id' => 3978],
                ['name' => 'Hudson', 'state_id' => 3978],
                ['name' => 'New Richmond', 'state_id' => 3978],
                ['name' => 'Roberts', 'state_id' => 3978],
                ['name' => 'Somerset', 'state_id' => 3978],
                ['name' => 'Wilson', 'state_id' => 3978],
                ['name' => 'Woodville', 'state_id' => 3978],
                ['name' => 'Houlton', 'state_id' => 3978],
                ['name' => 'Merrimac', 'state_id' => 3978],
                ['name' => 'Plain', 'state_id' => 3978],
                ['name' => 'Prairie Du Sac', 'state_id' => 3978],
                ['name' => 'Sauk City', 'state_id' => 3978],
                ['name' => 'Spring Green', 'state_id' => 3978],
                ['name' => 'Baraboo', 'state_id' => 3978],
                ['name' => 'Hillpoint', 'state_id' => 3978],
                ['name' => 'Lake Delton', 'state_id' => 3978],
                ['name' => 'La Valle', 'state_id' => 3978],
                ['name' => 'Lime Ridge', 'state_id' => 3978],
                ['name' => 'Loganville', 'state_id' => 3978],
                ['name' => 'North Freedom', 'state_id' => 3978],
                ['name' => 'Reedsburg', 'state_id' => 3978],
                ['name' => 'Rock Springs', 'state_id' => 3978],
                ['name' => 'Couderay', 'state_id' => 3978],
                ['name' => 'Edgewater', 'state_id' => 3978],
                ['name' => 'Exeland', 'state_id' => 3978],
                ['name' => 'Hayward', 'state_id' => 3978],
                ['name' => 'Ojibwa', 'state_id' => 3978],
                ['name' => 'Radisson', 'state_id' => 3978],
                ['name' => 'Stone Lake', 'state_id' => 3978],
                ['name' => 'Winter', 'state_id' => 3978],
                ['name' => 'Bonduel', 'state_id' => 3978],
                ['name' => 'Cecil', 'state_id' => 3978],
                ['name' => 'Green Valley', 'state_id' => 3978],
                ['name' => 'Gresham', 'state_id' => 3978],
                ['name' => 'Krakow', 'state_id' => 3978],
                ['name' => 'Shawano', 'state_id' => 3978],
                ['name' => 'Zachow', 'state_id' => 3978],
                ['name' => 'Birnamwood', 'state_id' => 3978],
                ['name' => 'Bowler', 'state_id' => 3978],
                ['name' => 'Mattoon', 'state_id' => 3978],
                ['name' => 'Tigerton', 'state_id' => 3978],
                ['name' => 'Wittenberg', 'state_id' => 3978],
                ['name' => 'Caroline', 'state_id' => 3978],
                ['name' => 'Leopolis', 'state_id' => 3978],
                ['name' => 'Tilleda', 'state_id' => 3978],
                ['name' => 'Adell', 'state_id' => 3978],
                ['name' => 'Cascade', 'state_id' => 3978],
                ['name' => 'Cedar Grove', 'state_id' => 3978],
                ['name' => 'Elkhart Lake', 'state_id' => 3978],
                ['name' => 'Glenbeulah', 'state_id' => 3978],
                ['name' => 'Greenbush', 'state_id' => 3978],
                ['name' => 'Hingham', 'state_id' => 3978],
                ['name' => 'Kohler', 'state_id' => 3978],
                ['name' => 'Oostburg', 'state_id' => 3978],
                ['name' => 'Plymouth', 'state_id' => 3978],
                ['name' => 'Random Lake', 'state_id' => 3978],
                ['name' => 'Sheboygan', 'state_id' => 3978],
                ['name' => 'Sheboygan Falls', 'state_id' => 3978],
                ['name' => 'Waldo', 'state_id' => 3978],
                ['name' => 'Gilman', 'state_id' => 3978],
                ['name' => 'Jump River', 'state_id' => 3978],
                ['name' => 'Hannibal', 'state_id' => 3978],
                ['name' => 'Lublin', 'state_id' => 3978],
                ['name' => 'Medford', 'state_id' => 3978],
                ['name' => 'Rib Lake', 'state_id' => 3978],
                ['name' => 'Stetsonville', 'state_id' => 3978],
                ['name' => 'Westboro', 'state_id' => 3978],
                ['name' => 'Arcadia', 'state_id' => 3978],
                ['name' => 'Blair', 'state_id' => 3978],
                ['name' => 'Dodge', 'state_id' => 3978],
                ['name' => 'Ettrick', 'state_id' => 3978],
                ['name' => 'Galesville', 'state_id' => 3978],
                ['name' => 'Trempealeau', 'state_id' => 3978],
                ['name' => 'Eleva', 'state_id' => 3978],
                ['name' => 'Independence', 'state_id' => 3978],
                ['name' => 'Osseo', 'state_id' => 3978],
                ['name' => 'Pigeon Falls', 'state_id' => 3978],
                ['name' => 'Strum', 'state_id' => 3978],
                ['name' => 'Whitehall', 'state_id' => 3978],
                ['name' => 'Chaseburg', 'state_id' => 3978],
                ['name' => 'Coon Valley', 'state_id' => 3978],
                ['name' => 'De Soto', 'state_id' => 3978],
                ['name' => 'Genoa', 'state_id' => 3978],
                ['name' => 'Hillsboro', 'state_id' => 3978],
                ['name' => 'La Farge', 'state_id' => 3978],
                ['name' => 'Ontario', 'state_id' => 3978],
                ['name' => 'Readstown', 'state_id' => 3978],
                ['name' => 'Stoddard', 'state_id' => 3978],
                ['name' => 'Viola', 'state_id' => 3978],
                ['name' => 'Viroqua', 'state_id' => 3978],
                ['name' => 'Westby', 'state_id' => 3978],
                ['name' => 'Boulder Junction', 'state_id' => 3978],
                ['name' => 'Conover', 'state_id' => 3978],
                ['name' => 'Eagle River', 'state_id' => 3978],
                ['name' => 'Lac Du Flambeau', 'state_id' => 3978],
                ['name' => 'Land O Lakes', 'state_id' => 3978],
                ['name' => 'Manitowish Waters', 'state_id' => 3978],
                ['name' => 'Phelps', 'state_id' => 3978],
                ['name' => 'Presque Isle', 'state_id' => 3978],
                ['name' => 'Saint Germain', 'state_id' => 3978],
                ['name' => 'Sayner', 'state_id' => 3978],
                ['name' => 'Star Lake', 'state_id' => 3978],
                ['name' => 'Darien', 'state_id' => 3978],
                ['name' => 'Delavan', 'state_id' => 3978],
                ['name' => 'East Troy', 'state_id' => 3978],
                ['name' => 'Elkhorn', 'state_id' => 3978],
                ['name' => 'Fontana', 'state_id' => 3978],
                ['name' => 'Genoa City', 'state_id' => 3978],
                ['name' => 'Honey Creek', 'state_id' => 3978],
                ['name' => 'Lake Geneva', 'state_id' => 3978],
                ['name' => 'Lyons', 'state_id' => 3978],
                ['name' => 'Pell Lake', 'state_id' => 3978],
                ['name' => 'Springfield', 'state_id' => 3978],
                ['name' => 'Walworth', 'state_id' => 3978],
                ['name' => 'Whitewater', 'state_id' => 3978],
                ['name' => 'Williams Bay', 'state_id' => 3978],
                ['name' => 'Zenda', 'state_id' => 3978],
                ['name' => 'Sharon', 'state_id' => 3978],
                ['name' => 'Spooner', 'state_id' => 3978],
                ['name' => 'Birchwood', 'state_id' => 3978],
                ['name' => 'Minong', 'state_id' => 3978],
                ['name' => 'Sarona', 'state_id' => 3978],
                ['name' => 'Shell Lake', 'state_id' => 3978],
                ['name' => 'Springbrook', 'state_id' => 3978],
                ['name' => 'Trego', 'state_id' => 3978],
                ['name' => 'Allenton', 'state_id' => 3978],
                ['name' => 'Colgate', 'state_id' => 3978],
                ['name' => 'Germantown', 'state_id' => 3978],
                ['name' => 'Hartford', 'state_id' => 3978],
                ['name' => 'Hubertus', 'state_id' => 3978],
                ['name' => 'Jackson', 'state_id' => 3978],
                ['name' => 'Kewaskum', 'state_id' => 3978],
                ['name' => 'Newburg', 'state_id' => 3978],
                ['name' => 'Richfield', 'state_id' => 3978],
                ['name' => 'Slinger', 'state_id' => 3978],
                ['name' => 'West Bend', 'state_id' => 3978],
                ['name' => 'Brookfield', 'state_id' => 3978],
                ['name' => 'Butler', 'state_id' => 3978],
                ['name' => 'Delafield', 'state_id' => 3978],
                ['name' => 'Hartland', 'state_id' => 3978],
                ['name' => 'Lannon', 'state_id' => 3978],
                ['name' => 'Menomonee Falls', 'state_id' => 3978],
                ['name' => 'Merton', 'state_id' => 3978],
                ['name' => 'Nashotah', 'state_id' => 3978],
                ['name' => 'North Lake', 'state_id' => 3978],
                ['name' => 'Oconomowoc', 'state_id' => 3978],
                ['name' => 'Okauchee', 'state_id' => 3978],
                ['name' => 'Pewaukee', 'state_id' => 3978],
                ['name' => 'Sussex', 'state_id' => 3978],
                ['name' => 'Big Bend', 'state_id' => 3978],
                ['name' => 'Dousman', 'state_id' => 3978],
                ['name' => 'Eagle', 'state_id' => 3978],
                ['name' => 'Elm Grove', 'state_id' => 3978],
                ['name' => 'Genesee Depot', 'state_id' => 3978],
                ['name' => 'New Berlin', 'state_id' => 3978],
                ['name' => 'Mukwonago', 'state_id' => 3978],
                ['name' => 'Muskego', 'state_id' => 3978],
                ['name' => 'North Prairie', 'state_id' => 3978],
                ['name' => 'Wales', 'state_id' => 3978],
                ['name' => 'Waukesha', 'state_id' => 3978],
                ['name' => 'Big Falls', 'state_id' => 3978],
                ['name' => 'Clintonville', 'state_id' => 3978],
                ['name' => 'Embarrass', 'state_id' => 3978],
                ['name' => 'Fremont', 'state_id' => 3978],
                ['name' => 'Iola', 'state_id' => 3978],
                ['name' => 'King', 'state_id' => 3978],
                ['name' => 'Manawa', 'state_id' => 3978],
                ['name' => 'Marion', 'state_id' => 3978],
                ['name' => 'New London', 'state_id' => 3978],
                ['name' => 'Ogdensburg', 'state_id' => 3978],
                ['name' => 'Readfield', 'state_id' => 3978],
                ['name' => 'Scandinavia', 'state_id' => 3978],
                ['name' => 'Waupaca', 'state_id' => 3978],
                ['name' => 'Weyauwega', 'state_id' => 3978],
                ['name' => 'Coloma', 'state_id' => 3978],
                ['name' => 'Hancock', 'state_id' => 3978],
                ['name' => 'Pine River', 'state_id' => 3978],
                ['name' => 'Plainfield', 'state_id' => 3978],
                ['name' => 'Poy Sippi', 'state_id' => 3978],
                ['name' => 'Redgranite', 'state_id' => 3978],
                ['name' => 'Saxeville', 'state_id' => 3978],
                ['name' => 'Wautoma', 'state_id' => 3978],
                ['name' => 'Wild Rose', 'state_id' => 3978],
                ['name' => 'Oshkosh', 'state_id' => 3978],
                ['name' => 'Butte Des Morts', 'state_id' => 3978],
                ['name' => 'Eureka', 'state_id' => 3978],
                ['name' => 'Larsen', 'state_id' => 3978],
                ['name' => 'Menasha', 'state_id' => 3978],
                ['name' => 'Neenah', 'state_id' => 3978],
                ['name' => 'Omro', 'state_id' => 3978],
                ['name' => 'Pickett', 'state_id' => 3978],
                ['name' => 'Waukau', 'state_id' => 3978],
                ['name' => 'Winnebago', 'state_id' => 3978],
                ['name' => 'Winneconne', 'state_id' => 3978],
                ['name' => 'Marshfield', 'state_id' => 3978],
                ['name' => 'Arpin', 'state_id' => 3978],
                ['name' => 'Auburndale', 'state_id' => 3978],
                ['name' => 'Babcock', 'state_id' => 3978],
                ['name' => 'Blenker', 'state_id' => 3978],
                ['name' => 'Hewitt', 'state_id' => 3978],
                ['name' => 'Milladore', 'state_id' => 3978],
                ['name' => 'Nekoosa', 'state_id' => 3978],
                ['name' => 'Pittsville', 'state_id' => 3978],
                ['name' => 'Port Edwards', 'state_id' => 3978],
                ['name' => 'Rudolph', 'state_id' => 3978],
                ['name' => 'Vesper', 'state_id' => 3978],
                ['name' => 'Wisconsin Rapids', 'state_id' => 3978]
            ]);
        }
    }
}
