<?php

use Illuminate\Database\Seeder;

class state30TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NE - Nebraska.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Hastings', 'state_id' => 3951],
                ['name' => 'Ayr', 'state_id' => 3951],
                ['name' => 'Holstein', 'state_id' => 3951],
                ['name' => 'Juniata', 'state_id' => 3951],
                ['name' => 'Kenesaw', 'state_id' => 3951],
                ['name' => 'Roseland', 'state_id' => 3951],
                ['name' => 'Elgin', 'state_id' => 3951],
                ['name' => 'Brunswick', 'state_id' => 3951],
                ['name' => 'Clearwater', 'state_id' => 3951],
                ['name' => 'Neligh', 'state_id' => 3951],
                ['name' => 'Oakdale', 'state_id' => 3951],
                ['name' => 'Orchard', 'state_id' => 3951],
                ['name' => 'Royal', 'state_id' => 3951],
                ['name' => 'Arthur', 'state_id' => 3951],
                ['name' => 'Harrisburg', 'state_id' => 3951],
                ['name' => 'Brewster', 'state_id' => 3951],
                ['name' => 'Dunning', 'state_id' => 3951],
                ['name' => 'Purdum', 'state_id' => 3951],
                ['name' => 'Albion', 'state_id' => 3951],
                ['name' => 'Cedar Rapids', 'state_id' => 3951],
                ['name' => 'Petersburg', 'state_id' => 3951],
                ['name' => 'Primrose', 'state_id' => 3951],
                ['name' => 'Saint Edward', 'state_id' => 3951],
                ['name' => 'Alliance', 'state_id' => 3951],
                ['name' => 'Hemingford', 'state_id' => 3951],
                ['name' => 'Bristow', 'state_id' => 3951],
                ['name' => 'Butte', 'state_id' => 3951],
                ['name' => 'Lynch', 'state_id' => 3951],
                ['name' => 'Naper', 'state_id' => 3951],
                ['name' => 'Spencer', 'state_id' => 3951],
                ['name' => 'Ainsworth', 'state_id' => 3951],
                ['name' => 'Johnstown', 'state_id' => 3951],
                ['name' => 'Long Pine', 'state_id' => 3951],
                ['name' => 'Amherst', 'state_id' => 3951],
                ['name' => 'Elm Creek', 'state_id' => 3951],
                ['name' => 'Gibbon', 'state_id' => 3951],
                ['name' => 'Kearney', 'state_id' => 3951],
                ['name' => 'Miller', 'state_id' => 3951],
                ['name' => 'Odessa', 'state_id' => 3951],
                ['name' => 'Pleasanton', 'state_id' => 3951],
                ['name' => 'Ravenna', 'state_id' => 3951],
                ['name' => 'Riverdale', 'state_id' => 3951],
                ['name' => 'Shelton', 'state_id' => 3951],
                ['name' => 'Craig', 'state_id' => 3951],
                ['name' => 'Decatur', 'state_id' => 3951],
                ['name' => 'Lyons', 'state_id' => 3951],
                ['name' => 'Oakland', 'state_id' => 3951],
                ['name' => 'Tekamah', 'state_id' => 3951],
                ['name' => 'Abie', 'state_id' => 3951],
                ['name' => 'Bruno', 'state_id' => 3951],
                ['name' => 'Linwood', 'state_id' => 3951],
                ['name' => 'Bellwood', 'state_id' => 3951],
                ['name' => 'Brainard', 'state_id' => 3951],
                ['name' => 'David City', 'state_id' => 3951],
                ['name' => 'Dwight', 'state_id' => 3951],
                ['name' => 'Rising City', 'state_id' => 3951],
                ['name' => 'Surprise', 'state_id' => 3951],
                ['name' => 'Ulysses', 'state_id' => 3951],
                ['name' => 'Cedar Creek', 'state_id' => 3951],
                ['name' => 'Louisville', 'state_id' => 3951],
                ['name' => 'Plattsmouth', 'state_id' => 3951],
                ['name' => 'South Bend', 'state_id' => 3951],
                ['name' => 'Alvo', 'state_id' => 3951],
                ['name' => 'Avoca', 'state_id' => 3951],
                ['name' => 'Eagle', 'state_id' => 3951],
                ['name' => 'Elmwood', 'state_id' => 3951],
                ['name' => 'Greenwood', 'state_id' => 3951],
                ['name' => 'Manley', 'state_id' => 3951],
                ['name' => 'Murdock', 'state_id' => 3951],
                ['name' => 'Murray', 'state_id' => 3951],
                ['name' => 'Nehawka', 'state_id' => 3951],
                ['name' => 'Union', 'state_id' => 3951],
                ['name' => 'Weeping Water', 'state_id' => 3951],
                ['name' => 'Belden', 'state_id' => 3951],
                ['name' => 'Coleridge', 'state_id' => 3951],
                ['name' => 'Fordyce', 'state_id' => 3951],
                ['name' => 'Hartington', 'state_id' => 3951],
                ['name' => 'Laurel', 'state_id' => 3951],
                ['name' => 'Magnet', 'state_id' => 3951],
                ['name' => 'Randolph', 'state_id' => 3951],
                ['name' => 'Saint Helena', 'state_id' => 3951],
                ['name' => 'Wynot', 'state_id' => 3951],
                ['name' => 'Champion', 'state_id' => 3951],
                ['name' => 'Enders', 'state_id' => 3951],
                ['name' => 'Imperial', 'state_id' => 3951],
                ['name' => 'Wauneta', 'state_id' => 3951],
                ['name' => 'Elsmere', 'state_id' => 3951],
                ['name' => 'Valentine', 'state_id' => 3951],
                ['name' => 'Cody', 'state_id' => 3951],
                ['name' => 'Crookston', 'state_id' => 3951],
                ['name' => 'Kilgore', 'state_id' => 3951],
                ['name' => 'Merriman', 'state_id' => 3951],
                ['name' => 'Nenzel', 'state_id' => 3951],
                ['name' => 'Sparks', 'state_id' => 3951],
                ['name' => 'Wood Lake', 'state_id' => 3951],
                ['name' => 'Dalton', 'state_id' => 3951],
                ['name' => 'Gurley', 'state_id' => 3951],
                ['name' => 'Lodgepole', 'state_id' => 3951],
                ['name' => 'Potter', 'state_id' => 3951],
                ['name' => 'Sidney', 'state_id' => 3951],
                ['name' => 'Ong', 'state_id' => 3951],
                ['name' => 'Clay Center', 'state_id' => 3951],
                ['name' => 'Deweese', 'state_id' => 3951],
                ['name' => 'Edgar', 'state_id' => 3951],
                ['name' => 'Fairfield', 'state_id' => 3951],
                ['name' => 'Glenvil', 'state_id' => 3951],
                ['name' => 'Harvard', 'state_id' => 3951],
                ['name' => 'Inland', 'state_id' => 3951],
                ['name' => 'Saronville', 'state_id' => 3951],
                ['name' => 'Sutton', 'state_id' => 3951],
                ['name' => 'Trumbull', 'state_id' => 3951],
                ['name' => 'Clarkson', 'state_id' => 3951],
                ['name' => 'Howells', 'state_id' => 3951],
                ['name' => 'Leigh', 'state_id' => 3951],
                ['name' => 'Rogers', 'state_id' => 3951],
                ['name' => 'Schuyler', 'state_id' => 3951],
                ['name' => 'Bancroft', 'state_id' => 3951],
                ['name' => 'Beemer', 'state_id' => 3951],
                ['name' => 'West Point', 'state_id' => 3951],
                ['name' => 'Wisner', 'state_id' => 3951],
                ['name' => 'Anselmo', 'state_id' => 3951],
                ['name' => 'Ansley', 'state_id' => 3951],
                ['name' => 'Broken Bow', 'state_id' => 3951],
                ['name' => 'Callaway', 'state_id' => 3951],
                ['name' => 'Comstock', 'state_id' => 3951],
                ['name' => 'Mason City', 'state_id' => 3951],
                ['name' => 'Merna', 'state_id' => 3951],
                ['name' => 'Oconto', 'state_id' => 3951],
                ['name' => 'Sargent', 'state_id' => 3951],
                ['name' => 'Westerville', 'state_id' => 3951],
                ['name' => 'Arnold', 'state_id' => 3951],
                ['name' => 'Homer', 'state_id' => 3951],
                ['name' => 'Dakota City', 'state_id' => 3951],
                ['name' => 'Emerson', 'state_id' => 3951],
                ['name' => 'Hubbard', 'state_id' => 3951],
                ['name' => 'Jackson', 'state_id' => 3951],
                ['name' => 'South Sioux City', 'state_id' => 3951],
                ['name' => 'Chadron', 'state_id' => 3951],
                ['name' => 'Crawford', 'state_id' => 3951],
                ['name' => 'Marsland', 'state_id' => 3951],
                ['name' => 'Whitney', 'state_id' => 3951],
                ['name' => 'Eddyville', 'state_id' => 3951],
                ['name' => 'Lexington', 'state_id' => 3951],
                ['name' => 'Overton', 'state_id' => 3951],
                ['name' => 'Sumner', 'state_id' => 3951],
                ['name' => 'Farnam', 'state_id' => 3951],
                ['name' => 'Cozad', 'state_id' => 3951],
                ['name' => 'Gothenburg', 'state_id' => 3951],
                ['name' => 'Willow Island', 'state_id' => 3951],
                ['name' => 'Big Springs', 'state_id' => 3951],
                ['name' => 'Chappell', 'state_id' => 3951],
                ['name' => 'Allen', 'state_id' => 3951],
                ['name' => 'Concord', 'state_id' => 3951],
                ['name' => 'Dixon', 'state_id' => 3951],
                ['name' => 'Maskell', 'state_id' => 3951],
                ['name' => 'Newcastle', 'state_id' => 3951],
                ['name' => 'Ponca', 'state_id' => 3951],
                ['name' => 'Wakefield', 'state_id' => 3951],
                ['name' => 'Waterbury', 'state_id' => 3951],
                ['name' => 'Fremont', 'state_id' => 3951],
                ['name' => 'Hooper', 'state_id' => 3951],
                ['name' => 'Nickerson', 'state_id' => 3951],
                ['name' => 'Scribner', 'state_id' => 3951],
                ['name' => 'Uehling', 'state_id' => 3951],
                ['name' => 'Winslow', 'state_id' => 3951],
                ['name' => 'Ames', 'state_id' => 3951],
                ['name' => 'Dodge', 'state_id' => 3951],
                ['name' => 'North Bend', 'state_id' => 3951],
                ['name' => 'Snyder', 'state_id' => 3951],
                ['name' => 'Bennington', 'state_id' => 3951],
                ['name' => 'Boys Town', 'state_id' => 3951],
                ['name' => 'Elkhorn', 'state_id' => 3951],
                ['name' => 'Valley', 'state_id' => 3951],
                ['name' => 'Waterloo', 'state_id' => 3951],
                ['name' => 'Omaha', 'state_id' => 3951],
                ['name' => 'Benkelman', 'state_id' => 3951],
                ['name' => 'Haigler', 'state_id' => 3951],
                ['name' => 'Max', 'state_id' => 3951],
                ['name' => 'Parks', 'state_id' => 3951],
                ['name' => 'Exeter', 'state_id' => 3951],
                ['name' => 'Fairmont', 'state_id' => 3951],
                ['name' => 'Geneva', 'state_id' => 3951],
                ['name' => 'Grafton', 'state_id' => 3951],
                ['name' => 'Milligan', 'state_id' => 3951],
                ['name' => 'Ohiowa', 'state_id' => 3951],
                ['name' => 'Shickley', 'state_id' => 3951],
                ['name' => 'Strang', 'state_id' => 3951],
                ['name' => 'Bloomington', 'state_id' => 3951],
                ['name' => 'Campbell', 'state_id' => 3951],
                ['name' => 'Franklin', 'state_id' => 3951],
                ['name' => 'Hildreth', 'state_id' => 3951],
                ['name' => 'Naponee', 'state_id' => 3951],
                ['name' => 'Riverton', 'state_id' => 3951],
                ['name' => 'Upland', 'state_id' => 3951],
                ['name' => 'Curtis', 'state_id' => 3951],
                ['name' => 'Eustis', 'state_id' => 3951],
                ['name' => 'Maywood', 'state_id' => 3951],
                ['name' => 'Moorefield', 'state_id' => 3951],
                ['name' => 'Stockville', 'state_id' => 3951],
                ['name' => 'Arapahoe', 'state_id' => 3951],
                ['name' => 'Beaver City', 'state_id' => 3951],
                ['name' => 'Edison', 'state_id' => 3951],
                ['name' => 'Hendley', 'state_id' => 3951],
                ['name' => 'Holbrook', 'state_id' => 3951],
                ['name' => 'Oxford', 'state_id' => 3951],
                ['name' => 'Cambridge', 'state_id' => 3951],
                ['name' => 'Wilsonville', 'state_id' => 3951],
                ['name' => 'Adams', 'state_id' => 3951],
                ['name' => 'Barneston', 'state_id' => 3951],
                ['name' => 'Beatrice', 'state_id' => 3951],
                ['name' => 'Blue Springs', 'state_id' => 3951],
                ['name' => 'Clatonia', 'state_id' => 3951],
                ['name' => 'Cortland', 'state_id' => 3951],
                ['name' => 'Filley', 'state_id' => 3951],
                ['name' => 'Liberty', 'state_id' => 3951],
                ['name' => 'Odell', 'state_id' => 3951],
                ['name' => 'Pickrell', 'state_id' => 3951],
                ['name' => 'Virginia', 'state_id' => 3951],
                ['name' => 'Wymore', 'state_id' => 3951],
                ['name' => 'Lewellen', 'state_id' => 3951],
                ['name' => 'Lisco', 'state_id' => 3951],
                ['name' => 'Oshkosh', 'state_id' => 3951],
                ['name' => 'Burwell', 'state_id' => 3951],
                ['name' => 'Elwood', 'state_id' => 3951],
                ['name' => 'Smithfield', 'state_id' => 3951],
                ['name' => 'Ashby', 'state_id' => 3951],
                ['name' => 'Hyannis', 'state_id' => 3951],
                ['name' => 'Whitman', 'state_id' => 3951],
                ['name' => 'Spalding', 'state_id' => 3951],
                ['name' => 'Greeley', 'state_id' => 3951],
                ['name' => 'Scotia', 'state_id' => 3951],
                ['name' => 'Wolbach', 'state_id' => 3951],
                ['name' => 'Grand Island', 'state_id' => 3951],
                ['name' => 'Alda', 'state_id' => 3951],
                ['name' => 'Cairo', 'state_id' => 3951],
                ['name' => 'Doniphan', 'state_id' => 3951],
                ['name' => 'Wood River', 'state_id' => 3951],
                ['name' => 'Aurora', 'state_id' => 3951],
                ['name' => 'Giltner', 'state_id' => 3951],
                ['name' => 'Hampton', 'state_id' => 3951],
                ['name' => 'Hordville', 'state_id' => 3951],
                ['name' => 'Marquette', 'state_id' => 3951],
                ['name' => 'Phillips', 'state_id' => 3951],
                ['name' => 'Alma', 'state_id' => 3951],
                ['name' => 'Orleans', 'state_id' => 3951],
                ['name' => 'Ragan', 'state_id' => 3951],
                ['name' => 'Republican City', 'state_id' => 3951],
                ['name' => 'Stamford', 'state_id' => 3951],
                ['name' => 'Hayes Center', 'state_id' => 3951],
                ['name' => 'Culbertson', 'state_id' => 3951],
                ['name' => 'Palisade', 'state_id' => 3951],
                ['name' => 'Stratton', 'state_id' => 3951],
                ['name' => 'Trenton', 'state_id' => 3951],
                ['name' => 'Amelia', 'state_id' => 3951],
                ['name' => 'Atkinson', 'state_id' => 3951],
                ['name' => 'Chambers', 'state_id' => 3951],
                ['name' => 'Emmet', 'state_id' => 3951],
                ['name' => 'Ewing', 'state_id' => 3951],
                ['name' => 'Inman', 'state_id' => 3951],
                ['name' => 'Oneill', 'state_id' => 3951],
                ['name' => 'Page', 'state_id' => 3951],
                ['name' => 'Stuart', 'state_id' => 3951],
                ['name' => 'Mullen', 'state_id' => 3951],
                ['name' => 'Boelus', 'state_id' => 3951],
                ['name' => 'Dannebrog', 'state_id' => 3951],
                ['name' => 'Elba', 'state_id' => 3951],
                ['name' => 'Farwell', 'state_id' => 3951],
                ['name' => 'Saint Libory', 'state_id' => 3951],
                ['name' => 'Saint Paul', 'state_id' => 3951],
                ['name' => 'Daykin', 'state_id' => 3951],
                ['name' => 'Diller', 'state_id' => 3951],
                ['name' => 'Endicott', 'state_id' => 3951],
                ['name' => 'Fairbury', 'state_id' => 3951],
                ['name' => 'Jansen', 'state_id' => 3951],
                ['name' => 'Plymouth', 'state_id' => 3951],
                ['name' => 'Steele City', 'state_id' => 3951],
                ['name' => 'Cook', 'state_id' => 3951],
                ['name' => 'Crab Orchard', 'state_id' => 3951],
                ['name' => 'Elk Creek', 'state_id' => 3951],
                ['name' => 'Sterling', 'state_id' => 3951],
                ['name' => 'Tecumseh', 'state_id' => 3951],
                ['name' => 'Axtell', 'state_id' => 3951],
                ['name' => 'Heartwell', 'state_id' => 3951],
                ['name' => 'Minden', 'state_id' => 3951],
                ['name' => 'Wilcox', 'state_id' => 3951],
                ['name' => 'Brule', 'state_id' => 3951],
                ['name' => 'Keystone', 'state_id' => 3951],
                ['name' => 'Lemoyne', 'state_id' => 3951],
                ['name' => 'Ogallala', 'state_id' => 3951],
                ['name' => 'Paxton', 'state_id' => 3951],
                ['name' => 'Mills', 'state_id' => 3951],
                ['name' => 'Newport', 'state_id' => 3951],
                ['name' => 'Springview', 'state_id' => 3951],
                ['name' => 'Bushnell', 'state_id' => 3951],
                ['name' => 'Dix', 'state_id' => 3951],
                ['name' => 'Kimball', 'state_id' => 3951],
                ['name' => 'Bloomfield', 'state_id' => 3951],
                ['name' => 'Center', 'state_id' => 3951],
                ['name' => 'Creighton', 'state_id' => 3951],
                ['name' => 'Crofton', 'state_id' => 3951],
                ['name' => 'Niobrara', 'state_id' => 3951],
                ['name' => 'Verdigre', 'state_id' => 3951],
                ['name' => 'Wausa', 'state_id' => 3951],
                ['name' => 'Winnetoon', 'state_id' => 3951],
                ['name' => 'Bennet', 'state_id' => 3951],
                ['name' => 'Davey', 'state_id' => 3951],
                ['name' => 'Denton', 'state_id' => 3951],
                ['name' => 'Firth', 'state_id' => 3951],
                ['name' => 'Hallam', 'state_id' => 3951],
                ['name' => 'Hickman', 'state_id' => 3951],
                ['name' => 'Malcolm', 'state_id' => 3951],
                ['name' => 'Martell', 'state_id' => 3951],
                ['name' => 'Panama', 'state_id' => 3951],
                ['name' => 'Raymond', 'state_id' => 3951],
                ['name' => 'Roca', 'state_id' => 3951],
                ['name' => 'Sprague', 'state_id' => 3951],
                ['name' => 'Walton', 'state_id' => 3951],
                ['name' => 'Waverly', 'state_id' => 3951],
                ['name' => 'Lincoln', 'state_id' => 3951],
                ['name' => 'North Platte', 'state_id' => 3951],
                ['name' => 'Brady', 'state_id' => 3951],
                ['name' => 'Dickens', 'state_id' => 3951],
                ['name' => 'Hershey', 'state_id' => 3951],
                ['name' => 'Maxwell', 'state_id' => 3951],
                ['name' => 'Sutherland', 'state_id' => 3951],
                ['name' => 'Wallace', 'state_id' => 3951],
                ['name' => 'Wellfleet', 'state_id' => 3951],
                ['name' => 'Stapleton', 'state_id' => 3951],
                ['name' => 'Taylor', 'state_id' => 3951],
                ['name' => 'Tryon', 'state_id' => 3951],
                ['name' => 'Norfolk', 'state_id' => 3951],
                ['name' => 'Battle Creek', 'state_id' => 3951],
                ['name' => 'Madison', 'state_id' => 3951],
                ['name' => 'Meadow Grove', 'state_id' => 3951],
                ['name' => 'Newman Grove', 'state_id' => 3951],
                ['name' => 'Tilden', 'state_id' => 3951],
                ['name' => 'Clarks', 'state_id' => 3951],
                ['name' => 'Silver Creek', 'state_id' => 3951],
                ['name' => 'Archer', 'state_id' => 3951],
                ['name' => 'Central City', 'state_id' => 3951],
                ['name' => 'Chapman', 'state_id' => 3951],
                ['name' => 'Palmer', 'state_id' => 3951],
                ['name' => 'Broadwater', 'state_id' => 3951],
                ['name' => 'Angora', 'state_id' => 3951],
                ['name' => 'Bayard', 'state_id' => 3951],
                ['name' => 'Bridgeport', 'state_id' => 3951],
                ['name' => 'Belgrade', 'state_id' => 3951],
                ['name' => 'Fullerton', 'state_id' => 3951],
                ['name' => 'Genoa', 'state_id' => 3951],
                ['name' => 'Auburn', 'state_id' => 3951],
                ['name' => 'Brock', 'state_id' => 3951],
                ['name' => 'Brownville', 'state_id' => 3951],
                ['name' => 'Johnson', 'state_id' => 3951],
                ['name' => 'Julian', 'state_id' => 3951],
                ['name' => 'Nemaha', 'state_id' => 3951],
                ['name' => 'Peru', 'state_id' => 3951],
                ['name' => 'Hardy', 'state_id' => 3951],
                ['name' => 'Lawrence', 'state_id' => 3951],
                ['name' => 'Nelson', 'state_id' => 3951],
                ['name' => 'Oak', 'state_id' => 3951],
                ['name' => 'Ruskin', 'state_id' => 3951],
                ['name' => 'Superior', 'state_id' => 3951],
                ['name' => 'Burr', 'state_id' => 3951],
                ['name' => 'Douglas', 'state_id' => 3951],
                ['name' => 'Dunbar', 'state_id' => 3951],
                ['name' => 'Lorton', 'state_id' => 3951],
                ['name' => 'Nebraska City', 'state_id' => 3951],
                ['name' => 'Otoe', 'state_id' => 3951],
                ['name' => 'Palmyra', 'state_id' => 3951],
                ['name' => 'Syracuse', 'state_id' => 3951],
                ['name' => 'Talmage', 'state_id' => 3951],
                ['name' => 'Unadilla', 'state_id' => 3951],
                ['name' => 'Burchard', 'state_id' => 3951],
                ['name' => 'Du Bois', 'state_id' => 3951],
                ['name' => 'Lewiston', 'state_id' => 3951],
                ['name' => 'Pawnee City', 'state_id' => 3951],
                ['name' => 'Steinauer', 'state_id' => 3951],
                ['name' => 'Table Rock', 'state_id' => 3951],
                ['name' => 'Elsie', 'state_id' => 3951],
                ['name' => 'Grant', 'state_id' => 3951],
                ['name' => 'Madrid', 'state_id' => 3951],
                ['name' => 'Venango', 'state_id' => 3951],
                ['name' => 'Atlanta', 'state_id' => 3951],
                ['name' => 'Bertrand', 'state_id' => 3951],
                ['name' => 'Funk', 'state_id' => 3951],
                ['name' => 'Holdrege', 'state_id' => 3951],
                ['name' => 'Loomis', 'state_id' => 3951],
                ['name' => 'Hadar', 'state_id' => 3951],
                ['name' => 'Mclean', 'state_id' => 3951],
                ['name' => 'Osmond', 'state_id' => 3951],
                ['name' => 'Pierce', 'state_id' => 3951],
                ['name' => 'Plainview', 'state_id' => 3951],
                ['name' => 'Columbus', 'state_id' => 3951],
                ['name' => 'Creston', 'state_id' => 3951],
                ['name' => 'Duncan', 'state_id' => 3951],
                ['name' => 'Humphrey', 'state_id' => 3951],
                ['name' => 'Lindsay', 'state_id' => 3951],
                ['name' => 'Monroe', 'state_id' => 3951],
                ['name' => 'Platte Center', 'state_id' => 3951],
                ['name' => 'Osceola', 'state_id' => 3951],
                ['name' => 'Polk', 'state_id' => 3951],
                ['name' => 'Shelby', 'state_id' => 3951],
                ['name' => 'Stromsburg', 'state_id' => 3951],
                ['name' => 'Mc Cook', 'state_id' => 3951],
                ['name' => 'Bartley', 'state_id' => 3951],
                ['name' => 'Danbury', 'state_id' => 3951],
                ['name' => 'Indianola', 'state_id' => 3951],
                ['name' => 'Lebanon', 'state_id' => 3951],
                ['name' => 'Dawson', 'state_id' => 3951],
                ['name' => 'Falls City', 'state_id' => 3951],
                ['name' => 'Humboldt', 'state_id' => 3951],
                ['name' => 'Rulo', 'state_id' => 3951],
                ['name' => 'Salem', 'state_id' => 3951],
                ['name' => 'Shubert', 'state_id' => 3951],
                ['name' => 'Stella', 'state_id' => 3951],
                ['name' => 'Verdon', 'state_id' => 3951],
                ['name' => 'Bassett', 'state_id' => 3951],
                ['name' => 'Crete', 'state_id' => 3951],
                ['name' => 'De Witt', 'state_id' => 3951],
                ['name' => 'Dorchester', 'state_id' => 3951],
                ['name' => 'Friend', 'state_id' => 3951],
                ['name' => 'Swanton', 'state_id' => 3951],
                ['name' => 'Tobias', 'state_id' => 3951],
                ['name' => 'Western', 'state_id' => 3951],
                ['name' => 'Wilber', 'state_id' => 3951],
                ['name' => 'Bellevue', 'state_id' => 3951],
                ['name' => 'Gretna', 'state_id' => 3951],
                ['name' => 'Papillion', 'state_id' => 3951],
                ['name' => 'St Columbans', 'state_id' => 3951],
                ['name' => 'Springfield', 'state_id' => 3951],
                ['name' => 'Offutt Afb', 'state_id' => 3951],
                ['name' => 'La Vista', 'state_id' => 3951],
                ['name' => 'Ashland', 'state_id' => 3951],
                ['name' => 'Cedar Bluffs', 'state_id' => 3951],
                ['name' => 'Ceresco', 'state_id' => 3951],
                ['name' => 'Colon', 'state_id' => 3951],
                ['name' => 'Ithaca', 'state_id' => 3951],
                ['name' => 'Malmo', 'state_id' => 3951],
                ['name' => 'Mead', 'state_id' => 3951],
                ['name' => 'Memphis', 'state_id' => 3951],
                ['name' => 'Prague', 'state_id' => 3951],
                ['name' => 'Valparaiso', 'state_id' => 3951],
                ['name' => 'Wahoo', 'state_id' => 3951],
                ['name' => 'Weston', 'state_id' => 3951],
                ['name' => 'Yutan', 'state_id' => 3951],
                ['name' => 'Morse Bluff', 'state_id' => 3951],
                ['name' => 'Gering', 'state_id' => 3951],
                ['name' => 'Lyman', 'state_id' => 3951],
                ['name' => 'Mcgrew', 'state_id' => 3951],
                ['name' => 'Melbeta', 'state_id' => 3951],
                ['name' => 'Minatare', 'state_id' => 3951],
                ['name' => 'Mitchell', 'state_id' => 3951],
                ['name' => 'Morrill', 'state_id' => 3951],
                ['name' => 'Scottsbluff', 'state_id' => 3951],
                ['name' => 'Beaver Crossing', 'state_id' => 3951],
                ['name' => 'Bee', 'state_id' => 3951],
                ['name' => 'Cordova', 'state_id' => 3951],
                ['name' => 'Garland', 'state_id' => 3951],
                ['name' => 'Goehner', 'state_id' => 3951],
                ['name' => 'Milford', 'state_id' => 3951],
                ['name' => 'Pleasant Dale', 'state_id' => 3951],
                ['name' => 'Seward', 'state_id' => 3951],
                ['name' => 'Staplehurst', 'state_id' => 3951],
                ['name' => 'Utica', 'state_id' => 3951],
                ['name' => 'Bingham', 'state_id' => 3951],
                ['name' => 'Ellsworth', 'state_id' => 3951],
                ['name' => 'Gordon', 'state_id' => 3951],
                ['name' => 'Hay Springs', 'state_id' => 3951],
                ['name' => 'Lakeside', 'state_id' => 3951],
                ['name' => 'Rushville', 'state_id' => 3951],
                ['name' => 'Whiteclay', 'state_id' => 3951],
                ['name' => 'Ashton', 'state_id' => 3951],
                ['name' => 'Hazard', 'state_id' => 3951],
                ['name' => 'Litchfield', 'state_id' => 3951],
                ['name' => 'Loup City', 'state_id' => 3951],
                ['name' => 'Rockville', 'state_id' => 3951],
                ['name' => 'Harrison', 'state_id' => 3951],
                ['name' => 'Pilger', 'state_id' => 3951],
                ['name' => 'Stanton', 'state_id' => 3951],
                ['name' => 'Alexandria', 'state_id' => 3951],
                ['name' => 'Belvidere', 'state_id' => 3951],
                ['name' => 'Bruning', 'state_id' => 3951],
                ['name' => 'Byron', 'state_id' => 3951],
                ['name' => 'Carleton', 'state_id' => 3951],
                ['name' => 'Chester', 'state_id' => 3951],
                ['name' => 'Davenport', 'state_id' => 3951],
                ['name' => 'Deshler', 'state_id' => 3951],
                ['name' => 'Gilead', 'state_id' => 3951],
                ['name' => 'Hebron', 'state_id' => 3951],
                ['name' => 'Hubbell', 'state_id' => 3951],
                ['name' => 'Reynolds', 'state_id' => 3951],
                ['name' => 'Halsey', 'state_id' => 3951],
                ['name' => 'Seneca', 'state_id' => 3951],
                ['name' => 'Thedford', 'state_id' => 3951],
                ['name' => 'Macy', 'state_id' => 3951],
                ['name' => 'Pender', 'state_id' => 3951],
                ['name' => 'Rosalie', 'state_id' => 3951],
                ['name' => 'Thurston', 'state_id' => 3951],
                ['name' => 'Walthill', 'state_id' => 3951],
                ['name' => 'Winnebago', 'state_id' => 3951],
                ['name' => 'Arcadia', 'state_id' => 3951],
                ['name' => 'Elyria', 'state_id' => 3951],
                ['name' => 'North Loup', 'state_id' => 3951],
                ['name' => 'Ord', 'state_id' => 3951],
                ['name' => 'Arlington', 'state_id' => 3951],
                ['name' => 'Blair', 'state_id' => 3951],
                ['name' => 'Fort Calhoun', 'state_id' => 3951],
                ['name' => 'Herman', 'state_id' => 3951],
                ['name' => 'Kennard', 'state_id' => 3951],
                ['name' => 'Washington', 'state_id' => 3951],
                ['name' => 'Carroll', 'state_id' => 3951],
                ['name' => 'Hoskins', 'state_id' => 3951],
                ['name' => 'Wayne', 'state_id' => 3951],
                ['name' => 'Winside', 'state_id' => 3951],
                ['name' => 'Bladen', 'state_id' => 3951],
                ['name' => 'Blue Hill', 'state_id' => 3951],
                ['name' => 'Guide Rock', 'state_id' => 3951],
                ['name' => 'Inavale', 'state_id' => 3951],
                ['name' => 'Red Cloud', 'state_id' => 3951],
                ['name' => 'Bartlett', 'state_id' => 3951],
                ['name' => 'Ericson', 'state_id' => 3951],
                ['name' => 'Benedict', 'state_id' => 3951],
                ['name' => 'Bradshaw', 'state_id' => 3951],
                ['name' => 'Gresham', 'state_id' => 3951],
                ['name' => 'Henderson', 'state_id' => 3951],
                ['name' => 'Mc Cool Junction', 'state_id' => 3951],
                ['name' => 'Waco', 'state_id' => 3951],
                ['name' => 'York', 'state_id' => 3951]
            ]);
        }
    }
}
