<?php

use Illuminate\Database\Seeder;

class state21TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MD - Maryland.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Cumberland', 'state_id' => 3943],
                ['name' => 'Barton', 'state_id' => 3943],
                ['name' => 'Corriganville', 'state_id' => 3943],
                ['name' => 'Eckhart Mines', 'state_id' => 3943],
                ['name' => 'Ellerslie', 'state_id' => 3943],
                ['name' => 'Flintstone', 'state_id' => 3943],
                ['name' => 'Frostburg', 'state_id' => 3943],
                ['name' => 'Lonaconing', 'state_id' => 3943],
                ['name' => 'Luke', 'state_id' => 3943],
                ['name' => 'Midland', 'state_id' => 3943],
                ['name' => 'Midlothian', 'state_id' => 3943],
                ['name' => 'Mount Savage', 'state_id' => 3943],
                ['name' => 'Oldtown', 'state_id' => 3943],
                ['name' => 'Pinto', 'state_id' => 3943],
                ['name' => 'Rawlings', 'state_id' => 3943],
                ['name' => 'Spring Gap', 'state_id' => 3943],
                ['name' => 'Westernport', 'state_id' => 3943],
                ['name' => 'Little Orleans', 'state_id' => 3943],
                ['name' => 'Lothian', 'state_id' => 3943],
                ['name' => 'Laurel', 'state_id' => 3943],
                ['name' => 'Churchton', 'state_id' => 3943],
                ['name' => 'Deale', 'state_id' => 3943],
                ['name' => 'Fort George G Meade', 'state_id' => 3943],
                ['name' => 'Friendship', 'state_id' => 3943],
                ['name' => 'Shady Side', 'state_id' => 3943],
                ['name' => 'Galesville', 'state_id' => 3943],
                ['name' => 'Harwood', 'state_id' => 3943],
                ['name' => 'West River', 'state_id' => 3943],
                ['name' => 'Tracys Landing', 'state_id' => 3943],
                ['name' => 'Arnold', 'state_id' => 3943],
                ['name' => 'Crownsville', 'state_id' => 3943],
                ['name' => 'Davidsonville', 'state_id' => 3943],
                ['name' => 'Edgewater', 'state_id' => 3943],
                ['name' => 'Gambrills', 'state_id' => 3943],
                ['name' => 'Gibson Island', 'state_id' => 3943],
                ['name' => 'Glen Burnie', 'state_id' => 3943],
                ['name' => 'Hanover', 'state_id' => 3943],
                ['name' => 'Harmans', 'state_id' => 3943],
                ['name' => 'Linthicum Heights', 'state_id' => 3943],
                ['name' => 'Mayo', 'state_id' => 3943],
                ['name' => 'Millersville', 'state_id' => 3943],
                ['name' => 'Odenton', 'state_id' => 3943],
                ['name' => 'Crofton', 'state_id' => 3943],
                ['name' => 'Pasadena', 'state_id' => 3943],
                ['name' => 'Riva', 'state_id' => 3943],
                ['name' => 'Severn', 'state_id' => 3943],
                ['name' => 'Severna Park', 'state_id' => 3943],
                ['name' => 'Brooklyn', 'state_id' => 3943],
                ['name' => 'Curtis Bay', 'state_id' => 3943],
                ['name' => 'Baltimore', 'state_id' => 3943],
                ['name' => 'Annapolis', 'state_id' => 3943],
                ['name' => 'Baldwin', 'state_id' => 3943],
                ['name' => 'Boring', 'state_id' => 3943],
                ['name' => 'Brooklandville', 'state_id' => 3943],
                ['name' => 'Butler', 'state_id' => 3943],
                ['name' => 'Chase', 'state_id' => 3943],
                ['name' => 'Cockeysville', 'state_id' => 3943],
                ['name' => 'Hunt Valley', 'state_id' => 3943],
                ['name' => 'Fork', 'state_id' => 3943],
                ['name' => 'Fort Howard', 'state_id' => 3943],
                ['name' => 'Freeland', 'state_id' => 3943],
                ['name' => 'Glen Arm', 'state_id' => 3943],
                ['name' => 'Glyndon', 'state_id' => 3943],
                ['name' => 'Hydes', 'state_id' => 3943],
                ['name' => 'Kingsville', 'state_id' => 3943],
                ['name' => 'Long Green', 'state_id' => 3943],
                ['name' => 'Lutherville Timonium', 'state_id' => 3943],
                ['name' => 'Maryland Line', 'state_id' => 3943],
                ['name' => 'Monkton', 'state_id' => 3943],
                ['name' => 'Owings Mills', 'state_id' => 3943],
                ['name' => 'Parkton', 'state_id' => 3943],
                ['name' => 'Perry Hall', 'state_id' => 3943],
                ['name' => 'Phoenix', 'state_id' => 3943],
                ['name' => 'Randallstown', 'state_id' => 3943],
                ['name' => 'Reisterstown', 'state_id' => 3943],
                ['name' => 'Riderwood', 'state_id' => 3943],
                ['name' => 'Sparks Glencoe', 'state_id' => 3943],
                ['name' => 'Stevenson', 'state_id' => 3943],
                ['name' => 'Upperco', 'state_id' => 3943],
                ['name' => 'Upper Falls', 'state_id' => 3943],
                ['name' => 'White Marsh', 'state_id' => 3943],
                ['name' => 'Woodstock', 'state_id' => 3943],
                ['name' => 'Towson', 'state_id' => 3943],
                ['name' => 'Gwynn Oak', 'state_id' => 3943],
                ['name' => 'Pikesville', 'state_id' => 3943],
                ['name' => 'Sparrows Point', 'state_id' => 3943],
                ['name' => 'Middle River', 'state_id' => 3943],
                ['name' => 'Essex', 'state_id' => 3943],
                ['name' => 'Dundalk', 'state_id' => 3943],
                ['name' => 'Halethorpe', 'state_id' => 3943],
                ['name' => 'Catonsville', 'state_id' => 3943],
                ['name' => 'Parkville', 'state_id' => 3943],
                ['name' => 'Nottingham', 'state_id' => 3943],
                ['name' => 'Rosedale', 'state_id' => 3943],
                ['name' => 'Windsor Mill', 'state_id' => 3943],
                ['name' => 'Barstow', 'state_id' => 3943],
                ['name' => 'Broomes Island', 'state_id' => 3943],
                ['name' => 'Dowell', 'state_id' => 3943],
                ['name' => 'Huntingtown', 'state_id' => 3943],
                ['name' => 'Lusby', 'state_id' => 3943],
                ['name' => 'Port Republic', 'state_id' => 3943],
                ['name' => 'Prince Frederick', 'state_id' => 3943],
                ['name' => 'Saint Leonard', 'state_id' => 3943],
                ['name' => 'Solomons', 'state_id' => 3943],
                ['name' => 'Sunderland', 'state_id' => 3943],
                ['name' => 'North Beach', 'state_id' => 3943],
                ['name' => 'Chesapeake Beach', 'state_id' => 3943],
                ['name' => 'Owings', 'state_id' => 3943],
                ['name' => 'Dunkirk', 'state_id' => 3943],
                ['name' => 'Bethlehem', 'state_id' => 3943],
                ['name' => 'Denton', 'state_id' => 3943],
                ['name' => 'Federalsburg', 'state_id' => 3943],
                ['name' => 'Goldsboro', 'state_id' => 3943],
                ['name' => 'Greensboro', 'state_id' => 3943],
                ['name' => 'Henderson', 'state_id' => 3943],
                ['name' => 'Hillsboro', 'state_id' => 3943],
                ['name' => 'Marydel', 'state_id' => 3943],
                ['name' => 'Preston', 'state_id' => 3943],
                ['name' => 'Ridgely', 'state_id' => 3943],
                ['name' => 'Templeville', 'state_id' => 3943],
                ['name' => 'Finksburg', 'state_id' => 3943],
                ['name' => 'Hampstead', 'state_id' => 3943],
                ['name' => 'Lineboro', 'state_id' => 3943],
                ['name' => 'Manchester', 'state_id' => 3943],
                ['name' => 'Marriottsville', 'state_id' => 3943],
                ['name' => 'Westminster', 'state_id' => 3943],
                ['name' => 'Keymar', 'state_id' => 3943],
                ['name' => 'New Windsor', 'state_id' => 3943],
                ['name' => 'Sykesville', 'state_id' => 3943],
                ['name' => 'Taneytown', 'state_id' => 3943],
                ['name' => 'Union Bridge', 'state_id' => 3943],
                ['name' => 'Woodbine', 'state_id' => 3943],
                ['name' => 'North East', 'state_id' => 3943],
                ['name' => 'Perry Point', 'state_id' => 3943],
                ['name' => 'Perryville', 'state_id' => 3943],
                ['name' => 'Port Deposit', 'state_id' => 3943],
                ['name' => 'Rising Sun', 'state_id' => 3943],
                ['name' => 'Warwick', 'state_id' => 3943],
                ['name' => 'Cecilton', 'state_id' => 3943],
                ['name' => 'Charlestown', 'state_id' => 3943],
                ['name' => 'Chesapeake City', 'state_id' => 3943],
                ['name' => 'Childs', 'state_id' => 3943],
                ['name' => 'Colora', 'state_id' => 3943],
                ['name' => 'Conowingo', 'state_id' => 3943],
                ['name' => 'Earleville', 'state_id' => 3943],
                ['name' => 'Elk Mills', 'state_id' => 3943],
                ['name' => 'Elkton', 'state_id' => 3943],
                ['name' => 'Georgetown', 'state_id' => 3943],
                ['name' => 'Waldorf', 'state_id' => 3943],
                ['name' => 'Bel Alton', 'state_id' => 3943],
                ['name' => 'Benedict', 'state_id' => 3943],
                ['name' => 'Bryans Road', 'state_id' => 3943],
                ['name' => 'Bryantown', 'state_id' => 3943],
                ['name' => 'Cobb Island', 'state_id' => 3943],
                ['name' => 'Faulkner', 'state_id' => 3943],
                ['name' => 'Hughesville', 'state_id' => 3943],
                ['name' => 'Indian Head', 'state_id' => 3943],
                ['name' => 'Ironsides', 'state_id' => 3943],
                ['name' => 'Issue', 'state_id' => 3943],
                ['name' => 'La Plata', 'state_id' => 3943],
                ['name' => 'Marbury', 'state_id' => 3943],
                ['name' => 'Mount Victoria', 'state_id' => 3943],
                ['name' => 'Nanjemoy', 'state_id' => 3943],
                ['name' => 'Newburg', 'state_id' => 3943],
                ['name' => 'Pomfret', 'state_id' => 3943],
                ['name' => 'Port Tobacco', 'state_id' => 3943],
                ['name' => 'Rock Point', 'state_id' => 3943],
                ['name' => 'Welcome', 'state_id' => 3943],
                ['name' => 'White Plains', 'state_id' => 3943],
                ['name' => 'Cambridge', 'state_id' => 3943],
                ['name' => 'Church Creek', 'state_id' => 3943],
                ['name' => 'Crapo', 'state_id' => 3943],
                ['name' => 'Crocheron', 'state_id' => 3943],
                ['name' => 'East New Market', 'state_id' => 3943],
                ['name' => 'Fishing Creek', 'state_id' => 3943],
                ['name' => 'Hurlock', 'state_id' => 3943],
                ['name' => 'Madison', 'state_id' => 3943],
                ['name' => 'Rhodesdale', 'state_id' => 3943],
                ['name' => 'Secretary', 'state_id' => 3943],
                ['name' => 'Taylors Island', 'state_id' => 3943],
                ['name' => 'Toddville', 'state_id' => 3943],
                ['name' => 'Wingate', 'state_id' => 3943],
                ['name' => 'Woolford', 'state_id' => 3943],
                ['name' => 'Linkwood', 'state_id' => 3943],
                ['name' => 'Vienna', 'state_id' => 3943],
                ['name' => 'Frederick', 'state_id' => 3943],
                ['name' => 'Adamstown', 'state_id' => 3943],
                ['name' => 'Braddock Heights', 'state_id' => 3943],
                ['name' => 'Brunswick', 'state_id' => 3943],
                ['name' => 'Buckeystown', 'state_id' => 3943],
                ['name' => 'Burkittsville', 'state_id' => 3943],
                ['name' => 'Emmitsburg', 'state_id' => 3943],
                ['name' => 'Ijamsville', 'state_id' => 3943],
                ['name' => 'Jefferson', 'state_id' => 3943],
                ['name' => 'Knoxville', 'state_id' => 3943],
                ['name' => 'Ladiesburg', 'state_id' => 3943],
                ['name' => 'Libertytown', 'state_id' => 3943],
                ['name' => 'Middletown', 'state_id' => 3943],
                ['name' => 'Monrovia', 'state_id' => 3943],
                ['name' => 'Mount Airy', 'state_id' => 3943],
                ['name' => 'Myersville', 'state_id' => 3943],
                ['name' => 'New Market', 'state_id' => 3943],
                ['name' => 'New Midway', 'state_id' => 3943],
                ['name' => 'Point Of Rocks', 'state_id' => 3943],
                ['name' => 'Rocky Ridge', 'state_id' => 3943],
                ['name' => 'Sabillasville', 'state_id' => 3943],
                ['name' => 'Thurmont', 'state_id' => 3943],
                ['name' => 'Tuscarora', 'state_id' => 3943],
                ['name' => 'Unionville', 'state_id' => 3943],
                ['name' => 'Walkersville', 'state_id' => 3943],
                ['name' => 'Woodsboro', 'state_id' => 3943],
                ['name' => 'Accident', 'state_id' => 3943],
                ['name' => 'Bittinger', 'state_id' => 3943],
                ['name' => 'Bloomington', 'state_id' => 3943],
                ['name' => 'Friendsville', 'state_id' => 3943],
                ['name' => 'Grantsville', 'state_id' => 3943],
                ['name' => 'Kitzmiller', 'state_id' => 3943],
                ['name' => 'Mc Henry', 'state_id' => 3943],
                ['name' => 'Oakland', 'state_id' => 3943],
                ['name' => 'Swanton', 'state_id' => 3943],
                ['name' => 'Aberdeen', 'state_id' => 3943],
                ['name' => 'Aberdeen Proving Ground', 'state_id' => 3943],
                ['name' => 'Abingdon', 'state_id' => 3943],
                ['name' => 'Gunpowder', 'state_id' => 3943],
                ['name' => 'Bel Air', 'state_id' => 3943],
                ['name' => 'Belcamp', 'state_id' => 3943],
                ['name' => 'Benson', 'state_id' => 3943],
                ['name' => 'Churchville', 'state_id' => 3943],
                ['name' => 'Darlington', 'state_id' => 3943],
                ['name' => 'Edgewood', 'state_id' => 3943],
                ['name' => 'Fallston', 'state_id' => 3943],
                ['name' => 'Forest Hill', 'state_id' => 3943],
                ['name' => 'Havre De Grace', 'state_id' => 3943],
                ['name' => 'Jarrettsville', 'state_id' => 3943],
                ['name' => 'Joppa', 'state_id' => 3943],
                ['name' => 'Perryman', 'state_id' => 3943],
                ['name' => 'Pylesville', 'state_id' => 3943],
                ['name' => 'Street', 'state_id' => 3943],
                ['name' => 'Whiteford', 'state_id' => 3943],
                ['name' => 'White Hall', 'state_id' => 3943],
                ['name' => 'Dhs', 'state_id' => 3943],
                ['name' => 'Annapolis Junction', 'state_id' => 3943],
                ['name' => 'Fulton', 'state_id' => 3943],
                ['name' => 'Savage', 'state_id' => 3943],
                ['name' => 'Highland', 'state_id' => 3943],
                ['name' => 'Jessup', 'state_id' => 3943],
                ['name' => 'Clarksville', 'state_id' => 3943],
                ['name' => 'Dayton', 'state_id' => 3943],
                ['name' => 'Ellicott City', 'state_id' => 3943],
                ['name' => 'Columbia', 'state_id' => 3943],
                ['name' => 'Elkridge', 'state_id' => 3943],
                ['name' => 'Simpsonville', 'state_id' => 3943],
                ['name' => 'Cooksville', 'state_id' => 3943],
                ['name' => 'Glenelg', 'state_id' => 3943],
                ['name' => 'Glenwood', 'state_id' => 3943],
                ['name' => 'Lisbon', 'state_id' => 3943],
                ['name' => 'West Friendship', 'state_id' => 3943],
                ['name' => 'Betterton', 'state_id' => 3943],
                ['name' => 'Chestertown', 'state_id' => 3943],
                ['name' => 'Galena', 'state_id' => 3943],
                ['name' => 'Kennedyville', 'state_id' => 3943],
                ['name' => 'Massey', 'state_id' => 3943],
                ['name' => 'Millington', 'state_id' => 3943],
                ['name' => 'Rock Hall', 'state_id' => 3943],
                ['name' => 'Still Pond', 'state_id' => 3943],
                ['name' => 'Worton', 'state_id' => 3943],
                ['name' => 'Bethesda', 'state_id' => 3943],
                ['name' => 'Glen Echo', 'state_id' => 3943],
                ['name' => 'Chevy Chase', 'state_id' => 3943],
                ['name' => 'Cabin John', 'state_id' => 3943],
                ['name' => 'Olney', 'state_id' => 3943],
                ['name' => 'Brookeville', 'state_id' => 3943],
                ['name' => 'Poolesville', 'state_id' => 3943],
                ['name' => 'Barnesville', 'state_id' => 3943],
                ['name' => 'Beallsville', 'state_id' => 3943],
                ['name' => 'Boyds', 'state_id' => 3943],
                ['name' => 'Dickerson', 'state_id' => 3943],
                ['name' => 'Rockville', 'state_id' => 3943],
                ['name' => 'Potomac', 'state_id' => 3943],
                ['name' => 'Derwood', 'state_id' => 3943],
                ['name' => 'Sandy Spring', 'state_id' => 3943],
                ['name' => 'Ashton', 'state_id' => 3943],
                ['name' => 'Brinklow', 'state_id' => 3943],
                ['name' => 'Burtonsville', 'state_id' => 3943],
                ['name' => 'Spencerville', 'state_id' => 3943],
                ['name' => 'Clarksburg', 'state_id' => 3943],
                ['name' => 'Damascus', 'state_id' => 3943],
                ['name' => 'Germantown', 'state_id' => 3943],
                ['name' => 'Gaithersburg', 'state_id' => 3943],
                ['name' => 'Washington Grove', 'state_id' => 3943],
                ['name' => 'Montgomery Village', 'state_id' => 3943],
                ['name' => 'Kensington', 'state_id' => 3943],
                ['name' => 'Garrett Park', 'state_id' => 3943],
                ['name' => 'Suburb Maryland Fac', 'state_id' => 3943],
                ['name' => 'Silver Spring', 'state_id' => 3943],
                ['name' => 'Takoma Park', 'state_id' => 3943],
                ['name' => 'Accokeek', 'state_id' => 3943],
                ['name' => 'Aquasco', 'state_id' => 3943],
                ['name' => 'Brandywine', 'state_id' => 3943],
                ['name' => 'Cheltenham', 'state_id' => 3943],
                ['name' => 'Southern Md Facility', 'state_id' => 3943],
                ['name' => 'Lanham', 'state_id' => 3943],
                ['name' => 'Beltsville', 'state_id' => 3943],
                ['name' => 'Bladensburg', 'state_id' => 3943],
                ['name' => 'Mount Rainier', 'state_id' => 3943],
                ['name' => 'Bowie', 'state_id' => 3943],
                ['name' => 'Brentwood', 'state_id' => 3943],
                ['name' => 'Capitol Heights', 'state_id' => 3943],
                ['name' => 'Clinton', 'state_id' => 3943],
                ['name' => 'Riverdale', 'state_id' => 3943],
                ['name' => 'College Park', 'state_id' => 3943],
                ['name' => 'Fort Washington', 'state_id' => 3943],
                ['name' => 'Oxon Hill', 'state_id' => 3943],
                ['name' => 'Suitland', 'state_id' => 3943],
                ['name' => 'District Heights', 'state_id' => 3943],
                ['name' => 'Temple Hills', 'state_id' => 3943],
                ['name' => 'Andrews Air Force Base', 'state_id' => 3943],
                ['name' => 'Greenbelt', 'state_id' => 3943],
                ['name' => 'Glenn Dale', 'state_id' => 3943],
                ['name' => 'Upper Marlboro', 'state_id' => 3943],
                ['name' => 'Hyattsville', 'state_id' => 3943],
                ['name' => 'Barclay', 'state_id' => 3943],
                ['name' => 'Centreville', 'state_id' => 3943],
                ['name' => 'Chester', 'state_id' => 3943],
                ['name' => 'Church Hill', 'state_id' => 3943],
                ['name' => 'Crumpton', 'state_id' => 3943],
                ['name' => 'Grasonville', 'state_id' => 3943],
                ['name' => 'Ingleside', 'state_id' => 3943],
                ['name' => 'Price', 'state_id' => 3943],
                ['name' => 'Queen Anne', 'state_id' => 3943],
                ['name' => 'Queenstown', 'state_id' => 3943],
                ['name' => 'Stevensville', 'state_id' => 3943],
                ['name' => 'Sudlersville', 'state_id' => 3943],
                ['name' => 'Abell', 'state_id' => 3943],
                ['name' => 'Avenue', 'state_id' => 3943],
                ['name' => 'Bushwood', 'state_id' => 3943],
                ['name' => 'California', 'state_id' => 3943],
                ['name' => 'Callaway', 'state_id' => 3943],
                ['name' => 'Chaptico', 'state_id' => 3943],
                ['name' => 'Charlotte Hall', 'state_id' => 3943],
                ['name' => 'Clements', 'state_id' => 3943],
                ['name' => 'Coltons Point', 'state_id' => 3943],
                ['name' => 'Compton', 'state_id' => 3943],
                ['name' => 'Dameron', 'state_id' => 3943],
                ['name' => 'Drayden', 'state_id' => 3943],
                ['name' => 'Great Mills', 'state_id' => 3943],
                ['name' => 'Helen', 'state_id' => 3943],
                ['name' => 'Hollywood', 'state_id' => 3943],
                ['name' => 'Leonardtown', 'state_id' => 3943],
                ['name' => 'Lexington Park', 'state_id' => 3943],
                ['name' => 'Loveville', 'state_id' => 3943],
                ['name' => 'Mechanicsville', 'state_id' => 3943],
                ['name' => 'Morganza', 'state_id' => 3943],
                ['name' => 'Park Hall', 'state_id' => 3943],
                ['name' => 'Patuxent River', 'state_id' => 3943],
                ['name' => 'Piney Point', 'state_id' => 3943],
                ['name' => 'Ridge', 'state_id' => 3943],
                ['name' => 'Saint Inigoes', 'state_id' => 3943],
                ['name' => 'Saint Marys City', 'state_id' => 3943],
                ['name' => 'Scotland', 'state_id' => 3943],
                ['name' => 'Tall Timbers', 'state_id' => 3943],
                ['name' => 'Valley Lee', 'state_id' => 3943],
                ['name' => 'Crisfield', 'state_id' => 3943],
                ['name' => 'Deal Island', 'state_id' => 3943],
                ['name' => 'Ewell', 'state_id' => 3943],
                ['name' => 'Manokin', 'state_id' => 3943],
                ['name' => 'Marion Station', 'state_id' => 3943],
                ['name' => 'Princess Anne', 'state_id' => 3943],
                ['name' => 'Rehobeth', 'state_id' => 3943],
                ['name' => 'Tylerton', 'state_id' => 3943],
                ['name' => 'Upper Fairmount', 'state_id' => 3943],
                ['name' => 'Westover', 'state_id' => 3943],
                ['name' => 'Easton', 'state_id' => 3943],
                ['name' => 'Bozman', 'state_id' => 3943],
                ['name' => 'Claiborne', 'state_id' => 3943],
                ['name' => 'Cordova', 'state_id' => 3943],
                ['name' => 'Mcdaniel', 'state_id' => 3943],
                ['name' => 'Neavitt', 'state_id' => 3943],
                ['name' => 'Newcomb', 'state_id' => 3943],
                ['name' => 'Oxford', 'state_id' => 3943],
                ['name' => 'Royal Oak', 'state_id' => 3943],
                ['name' => 'Saint Michaels', 'state_id' => 3943],
                ['name' => 'Sherwood', 'state_id' => 3943],
                ['name' => 'Tilghman', 'state_id' => 3943],
                ['name' => 'Trappe', 'state_id' => 3943],
                ['name' => 'Wittman', 'state_id' => 3943],
                ['name' => 'Wye Mills', 'state_id' => 3943],
                ['name' => 'Big Pool', 'state_id' => 3943],
                ['name' => 'Boonsboro', 'state_id' => 3943],
                ['name' => 'Brownsville', 'state_id' => 3943],
                ['name' => 'Cascade', 'state_id' => 3943],
                ['name' => 'Cavetown', 'state_id' => 3943],
                ['name' => 'Chewsville', 'state_id' => 3943],
                ['name' => 'Clear Spring', 'state_id' => 3943],
                ['name' => 'Fairplay', 'state_id' => 3943],
                ['name' => 'Funkstown', 'state_id' => 3943],
                ['name' => 'Hagerstown', 'state_id' => 3943],
                ['name' => 'Hancock', 'state_id' => 3943],
                ['name' => 'Keedysville', 'state_id' => 3943],
                ['name' => 'Maugansville', 'state_id' => 3943],
                ['name' => 'Rohrersville', 'state_id' => 3943],
                ['name' => 'Saint James', 'state_id' => 3943],
                ['name' => 'Sharpsburg', 'state_id' => 3943],
                ['name' => 'Smithsburg', 'state_id' => 3943],
                ['name' => 'Williamsport', 'state_id' => 3943],
                ['name' => 'Salisbury', 'state_id' => 3943],
                ['name' => 'Allen', 'state_id' => 3943],
                ['name' => 'Bivalve', 'state_id' => 3943],
                ['name' => 'Fruitland', 'state_id' => 3943],
                ['name' => 'Hebron', 'state_id' => 3943],
                ['name' => 'Mardela Springs', 'state_id' => 3943],
                ['name' => 'Nanticoke', 'state_id' => 3943],
                ['name' => 'Parsonsburg', 'state_id' => 3943],
                ['name' => 'Pittsville', 'state_id' => 3943],
                ['name' => 'Powellville', 'state_id' => 3943],
                ['name' => 'Quantico', 'state_id' => 3943],
                ['name' => 'Sharptown', 'state_id' => 3943],
                ['name' => 'Tyaskin', 'state_id' => 3943],
                ['name' => 'Willards', 'state_id' => 3943],
                ['name' => 'Delmar', 'state_id' => 3943],
                ['name' => 'Berlin', 'state_id' => 3943],
                ['name' => 'Bishopville', 'state_id' => 3943],
                ['name' => 'Eden', 'state_id' => 3943],
                ['name' => 'Girdletree', 'state_id' => 3943],
                ['name' => 'Newark', 'state_id' => 3943],
                ['name' => 'Ocean City', 'state_id' => 3943],
                ['name' => 'Pocomoke City', 'state_id' => 3943],
                ['name' => 'Showell', 'state_id' => 3943],
                ['name' => 'Snow Hill', 'state_id' => 3943],
                ['name' => 'Stockton', 'state_id' => 3943],
                ['name' => 'Whaleyville', 'state_id' => 3943]
            ]);
        }
    }
}
