<?php

use Illuminate\Database\Seeder;

class state10TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of FL - Florida.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Gainesville', 'state_id' => 3931],
                ['name' => 'Alachua', 'state_id' => 3931],
                ['name' => 'Archer', 'state_id' => 3931],
                ['name' => 'Earleton', 'state_id' => 3931],
                ['name' => 'Evinston', 'state_id' => 3931],
                ['name' => 'Hawthorne', 'state_id' => 3931],
                ['name' => 'High Springs', 'state_id' => 3931],
                ['name' => 'Island Grove', 'state_id' => 3931],
                ['name' => 'La Crosse', 'state_id' => 3931],
                ['name' => 'Lochloosa', 'state_id' => 3931],
                ['name' => 'Micanopy', 'state_id' => 3931],
                ['name' => 'Newberry', 'state_id' => 3931],
                ['name' => 'Waldo', 'state_id' => 3931],
                ['name' => 'Glen Saint Mary', 'state_id' => 3931],
                ['name' => 'Macclenny', 'state_id' => 3931],
                ['name' => 'Olustee', 'state_id' => 3931],
                ['name' => 'Sanderson', 'state_id' => 3931],
                ['name' => 'Panama City', 'state_id' => 3931],
                ['name' => 'Panama City Beach', 'state_id' => 3931],
                ['name' => 'Mexico Beach', 'state_id' => 3931],
                ['name' => 'Fountain', 'state_id' => 3931],
                ['name' => 'Lynn Haven', 'state_id' => 3931],
                ['name' => 'Youngstown', 'state_id' => 3931],
                ['name' => 'Graham', 'state_id' => 3931],
                ['name' => 'Hampton', 'state_id' => 3931],
                ['name' => 'Lawtey', 'state_id' => 3931],
                ['name' => 'Starke', 'state_id' => 3931],
                ['name' => 'Brooker', 'state_id' => 3931],
                ['name' => 'Mims', 'state_id' => 3931],
                ['name' => 'Scottsmoor', 'state_id' => 3931],
                ['name' => 'Titusville', 'state_id' => 3931],
                ['name' => 'Orlando', 'state_id' => 3931],
                ['name' => 'Melbourne', 'state_id' => 3931],
                ['name' => 'Indialantic', 'state_id' => 3931],
                ['name' => 'Palm Bay', 'state_id' => 3931],
                ['name' => 'Cape Canaveral', 'state_id' => 3931],
                ['name' => 'Cocoa', 'state_id' => 3931],
                ['name' => 'Patrick Afb', 'state_id' => 3931],
                ['name' => 'Cocoa Beach', 'state_id' => 3931],
                ['name' => 'Satellite Beach', 'state_id' => 3931],
                ['name' => 'Grant', 'state_id' => 3931],
                ['name' => 'Malabar', 'state_id' => 3931],
                ['name' => 'Melbourne Beach', 'state_id' => 3931],
                ['name' => 'Merritt Island', 'state_id' => 3931],
                ['name' => 'Rockledge', 'state_id' => 3931],
                ['name' => 'Sharpes', 'state_id' => 3931],
                ['name' => 'Sebastian', 'state_id' => 3931],
                ['name' => 'Dania', 'state_id' => 3931],
                ['name' => 'Hallandale', 'state_id' => 3931],
                ['name' => 'Hollywood', 'state_id' => 3931],
                ['name' => 'Pembroke Pines', 'state_id' => 3931],
                ['name' => 'Pompano Beach', 'state_id' => 3931],
                ['name' => 'Coral Springs', 'state_id' => 3931],
                ['name' => 'Margate', 'state_id' => 3931],
                ['name' => 'Coconut Creek', 'state_id' => 3931],
                ['name' => 'Fort Lauderdale', 'state_id' => 3931],
                ['name' => 'Plantation', 'state_id' => 3931],
                ['name' => 'Deerfield Beach', 'state_id' => 3931],
                ['name' => 'Lehigh Acres', 'state_id' => 3931],
                ['name' => 'Altha', 'state_id' => 3931],
                ['name' => 'Blountstown', 'state_id' => 3931],
                ['name' => 'Clarksville', 'state_id' => 3931],
                ['name' => 'Wewahitchka', 'state_id' => 3931],
                ['name' => 'El Jobean', 'state_id' => 3931],
                ['name' => 'Murdock', 'state_id' => 3931],
                ['name' => 'Placida', 'state_id' => 3931],
                ['name' => 'Rotonda West', 'state_id' => 3931],
                ['name' => 'Port Charlotte', 'state_id' => 3931],
                ['name' => 'Punta Gorda', 'state_id' => 3931],
                ['name' => 'Crystal River', 'state_id' => 3931],
                ['name' => 'Dunnellon', 'state_id' => 3931],
                ['name' => 'Floral City', 'state_id' => 3931],
                ['name' => 'Hernando', 'state_id' => 3931],
                ['name' => 'Holder', 'state_id' => 3931],
                ['name' => 'Homosassa', 'state_id' => 3931],
                ['name' => 'Homosassa Springs', 'state_id' => 3931],
                ['name' => 'Inverness', 'state_id' => 3931],
                ['name' => 'Lecanto', 'state_id' => 3931],
                ['name' => 'Beverly Hills', 'state_id' => 3931],
                ['name' => 'Fleming Island', 'state_id' => 3931],
                ['name' => 'Doctors Inlet', 'state_id' => 3931],
                ['name' => 'Green Cove Springs', 'state_id' => 3931],
                ['name' => 'Middleburg', 'state_id' => 3931],
                ['name' => 'Orange Park', 'state_id' => 3931],
                ['name' => 'Penney Farms', 'state_id' => 3931],
                ['name' => 'Lake Geneva', 'state_id' => 3931],
                ['name' => 'Keystone Heights', 'state_id' => 3931],
                ['name' => 'Naples', 'state_id' => 3931],
                ['name' => 'Copeland', 'state_id' => 3931],
                ['name' => 'Chokoloskee', 'state_id' => 3931],
                ['name' => 'Everglades City', 'state_id' => 3931],
                ['name' => 'Goodland', 'state_id' => 3931],
                ['name' => 'Ochopee', 'state_id' => 3931],
                ['name' => 'Immokalee', 'state_id' => 3931],
                ['name' => 'Marco Island', 'state_id' => 3931],
                ['name' => 'Lake City', 'state_id' => 3931],
                ['name' => 'Fort White', 'state_id' => 3931],
                ['name' => 'Lulu', 'state_id' => 3931],
                ['name' => 'Arcadia', 'state_id' => 3931],
                ['name' => 'Fort Ogden', 'state_id' => 3931],
                ['name' => 'Nocatee', 'state_id' => 3931],
                ['name' => 'Cross City', 'state_id' => 3931],
                ['name' => 'Horseshoe Beach', 'state_id' => 3931],
                ['name' => 'Old Town', 'state_id' => 3931],
                ['name' => 'Suwannee', 'state_id' => 3931],
                ['name' => 'Jacksonville', 'state_id' => 3931],
                ['name' => 'Atlantic Beach', 'state_id' => 3931],
                ['name' => 'Jacksonville Beach', 'state_id' => 3931],
                ['name' => 'Neptune Beach', 'state_id' => 3931],
                ['name' => 'Pensacola', 'state_id' => 3931],
                ['name' => 'Cantonment', 'state_id' => 3931],
                ['name' => 'Century', 'state_id' => 3931],
                ['name' => 'Gonzalez', 'state_id' => 3931],
                ['name' => 'Mc David', 'state_id' => 3931],
                ['name' => 'Molino', 'state_id' => 3931],
                ['name' => 'Bunnell', 'state_id' => 3931],
                ['name' => 'Palm Coast', 'state_id' => 3931],
                ['name' => 'Flagler Beach', 'state_id' => 3931],
                ['name' => 'Tallahassee', 'state_id' => 3931],
                ['name' => 'Apalachicola', 'state_id' => 3931],
                ['name' => 'Carrabelle', 'state_id' => 3931],
                ['name' => 'Lanark Village', 'state_id' => 3931],
                ['name' => 'Eastpoint', 'state_id' => 3931],
                ['name' => 'Chattahoochee', 'state_id' => 3931],
                ['name' => 'Greensboro', 'state_id' => 3931],
                ['name' => 'Gretna', 'state_id' => 3931],
                ['name' => 'Havana', 'state_id' => 3931],
                ['name' => 'Midway', 'state_id' => 3931],
                ['name' => 'Quincy', 'state_id' => 3931],
                ['name' => 'Bell', 'state_id' => 3931],
                ['name' => 'Trenton', 'state_id' => 3931],
                ['name' => 'Moore Haven', 'state_id' => 3931],
                ['name' => 'Palmdale', 'state_id' => 3931],
                ['name' => 'Port Saint Joe', 'state_id' => 3931],
                ['name' => 'Jasper', 'state_id' => 3931],
                ['name' => 'Jennings', 'state_id' => 3931],
                ['name' => 'White Springs', 'state_id' => 3931],
                ['name' => 'Bowling Green', 'state_id' => 3931],
                ['name' => 'Ona', 'state_id' => 3931],
                ['name' => 'Wauchula', 'state_id' => 3931],
                ['name' => 'Zolfo Springs', 'state_id' => 3931],
                ['name' => 'Clewiston', 'state_id' => 3931],
                ['name' => 'Felda', 'state_id' => 3931],
                ['name' => 'Labelle', 'state_id' => 3931],
                ['name' => 'Brooksville', 'state_id' => 3931],
                ['name' => 'Spring Hill', 'state_id' => 3931],
                ['name' => 'Istachatta', 'state_id' => 3931],
                ['name' => 'Nobleton', 'state_id' => 3931],
                ['name' => 'Avon Park', 'state_id' => 3931],
                ['name' => 'Lake Placid', 'state_id' => 3931],
                ['name' => 'Lorida', 'state_id' => 3931],
                ['name' => 'Sebring', 'state_id' => 3931],
                ['name' => 'Venus', 'state_id' => 3931],
                ['name' => 'Balm', 'state_id' => 3931],
                ['name' => 'Brandon', 'state_id' => 3931],
                ['name' => 'Dover', 'state_id' => 3931],
                ['name' => 'Durant', 'state_id' => 3931],
                ['name' => 'Gibsonton', 'state_id' => 3931],
                ['name' => 'Lithia', 'state_id' => 3931],
                ['name' => 'Lutz', 'state_id' => 3931],
                ['name' => 'Mango', 'state_id' => 3931],
                ['name' => 'Odessa', 'state_id' => 3931],
                ['name' => 'Plant City', 'state_id' => 3931],
                ['name' => 'Riverview', 'state_id' => 3931],
                ['name' => 'Ruskin', 'state_id' => 3931],
                ['name' => 'Sun City Center', 'state_id' => 3931],
                ['name' => 'Apollo Beach', 'state_id' => 3931],
                ['name' => 'Seffner', 'state_id' => 3931],
                ['name' => 'Sun City', 'state_id' => 3931],
                ['name' => 'Sydney', 'state_id' => 3931],
                ['name' => 'Thonotosassa', 'state_id' => 3931],
                ['name' => 'Valrico', 'state_id' => 3931],
                ['name' => 'Wimauma', 'state_id' => 3931],
                ['name' => 'Tampa', 'state_id' => 3931],
                ['name' => 'Bonifay', 'state_id' => 3931],
                ['name' => 'Noma', 'state_id' => 3931],
                ['name' => 'Ponce De Leon', 'state_id' => 3931],
                ['name' => 'Westville', 'state_id' => 3931],
                ['name' => 'Fellsmere', 'state_id' => 3931],
                ['name' => 'Roseland', 'state_id' => 3931],
                ['name' => 'Vero Beach', 'state_id' => 3931],
                ['name' => 'Wabasso', 'state_id' => 3931],
                ['name' => 'Winter Beach', 'state_id' => 3931],
                ['name' => 'Alford', 'state_id' => 3931],
                ['name' => 'Bascom', 'state_id' => 3931],
                ['name' => 'Campbellton', 'state_id' => 3931],
                ['name' => 'Cottondale', 'state_id' => 3931],
                ['name' => 'Cypress', 'state_id' => 3931],
                ['name' => 'Graceville', 'state_id' => 3931],
                ['name' => 'Grand Ridge', 'state_id' => 3931],
                ['name' => 'Greenwood', 'state_id' => 3931],
                ['name' => 'Malone', 'state_id' => 3931],
                ['name' => 'Marianna', 'state_id' => 3931],
                ['name' => 'Sneads', 'state_id' => 3931],
                ['name' => 'Lamont', 'state_id' => 3931],
                ['name' => 'Lloyd', 'state_id' => 3931],
                ['name' => 'Monticello', 'state_id' => 3931],
                ['name' => 'Wacissa', 'state_id' => 3931],
                ['name' => 'Debary', 'state_id' => 3931],
                ['name' => 'Day', 'state_id' => 3931],
                ['name' => 'Mayo', 'state_id' => 3931],
                ['name' => 'Astor', 'state_id' => 3931],
                ['name' => 'Lady Lake', 'state_id' => 3931],
                ['name' => 'Altoona', 'state_id' => 3931],
                ['name' => 'Eustis', 'state_id' => 3931],
                ['name' => 'Grand Island', 'state_id' => 3931],
                ['name' => 'Mount Dora', 'state_id' => 3931],
                ['name' => 'Paisley', 'state_id' => 3931],
                ['name' => 'Sorrento', 'state_id' => 3931],
                ['name' => 'Tavares', 'state_id' => 3931],
                ['name' => 'Umatilla', 'state_id' => 3931],
                ['name' => 'Astatula', 'state_id' => 3931],
                ['name' => 'Clermont', 'state_id' => 3931],
                ['name' => 'Ferndale', 'state_id' => 3931],
                ['name' => 'Fruitland Park', 'state_id' => 3931],
                ['name' => 'Groveland', 'state_id' => 3931],
                ['name' => 'Howey In The Hills', 'state_id' => 3931],
                ['name' => 'Leesburg', 'state_id' => 3931],
                ['name' => 'Mascotte', 'state_id' => 3931],
                ['name' => 'Minneola', 'state_id' => 3931],
                ['name' => 'Montverde', 'state_id' => 3931],
                ['name' => 'Okahumpka', 'state_id' => 3931],
                ['name' => 'Yalaha', 'state_id' => 3931],
                ['name' => 'Fort Myers', 'state_id' => 3931],
                ['name' => 'North Fort Myers', 'state_id' => 3931],
                ['name' => 'Cape Coral', 'state_id' => 3931],
                ['name' => 'Alva', 'state_id' => 3931],
                ['name' => 'Boca Grande', 'state_id' => 3931],
                ['name' => 'Bokeelia', 'state_id' => 3931],
                ['name' => 'Captiva', 'state_id' => 3931],
                ['name' => 'Estero', 'state_id' => 3931],
                ['name' => 'Fort Myers Beach', 'state_id' => 3931],
                ['name' => 'Pineland', 'state_id' => 3931],
                ['name' => 'Saint James City', 'state_id' => 3931],
                ['name' => 'Sanibel', 'state_id' => 3931],
                ['name' => 'Bonita Springs', 'state_id' => 3931],
                ['name' => 'Woodville', 'state_id' => 3931],
                ['name' => 'Bronson', 'state_id' => 3931],
                ['name' => 'Cedar Key', 'state_id' => 3931],
                ['name' => 'Chiefland', 'state_id' => 3931],
                ['name' => 'Gulf Hammock', 'state_id' => 3931],
                ['name' => 'Morriston', 'state_id' => 3931],
                ['name' => 'Otter Creek', 'state_id' => 3931],
                ['name' => 'Williston', 'state_id' => 3931],
                ['name' => 'Inglis', 'state_id' => 3931],
                ['name' => 'Yankeetown', 'state_id' => 3931],
                ['name' => 'Bristol', 'state_id' => 3931],
                ['name' => 'Hosford', 'state_id' => 3931],
                ['name' => 'Sumatra', 'state_id' => 3931],
                ['name' => 'Telogia', 'state_id' => 3931],
                ['name' => 'Lee', 'state_id' => 3931],
                ['name' => 'Greenville', 'state_id' => 3931],
                ['name' => 'Madison', 'state_id' => 3931],
                ['name' => 'Pinetta', 'state_id' => 3931],
                ['name' => 'Bradenton', 'state_id' => 3931],
                ['name' => 'Cortez', 'state_id' => 3931],
                ['name' => 'Anna Maria', 'state_id' => 3931],
                ['name' => 'Bradenton Beach', 'state_id' => 3931],
                ['name' => 'Holmes Beach', 'state_id' => 3931],
                ['name' => 'Parrish', 'state_id' => 3931],
                ['name' => 'Palmetto', 'state_id' => 3931],
                ['name' => 'Ellenton', 'state_id' => 3931],
                ['name' => 'Longboat Key', 'state_id' => 3931],
                ['name' => 'Sarasota', 'state_id' => 3931],
                ['name' => 'Terra Ceia', 'state_id' => 3931],
                ['name' => 'Myakka City', 'state_id' => 3931],
                ['name' => 'Manasota', 'state_id' => 3931],
                ['name' => 'Oneco', 'state_id' => 3931],
                ['name' => 'Tallevast', 'state_id' => 3931],
                ['name' => 'Candler', 'state_id' => 3931],
                ['name' => 'Citra', 'state_id' => 3931],
                ['name' => 'Eastlake Weir', 'state_id' => 3931],
                ['name' => 'Fort Mc Coy', 'state_id' => 3931],
                ['name' => 'Ocklawaha', 'state_id' => 3931],
                ['name' => 'Orange Springs', 'state_id' => 3931],
                ['name' => 'Sparr', 'state_id' => 3931],
                ['name' => 'Weirsdale', 'state_id' => 3931],
                ['name' => 'Anthony', 'state_id' => 3931],
                ['name' => 'Fairfield', 'state_id' => 3931],
                ['name' => 'Lowell', 'state_id' => 3931],
                ['name' => 'Mc Intosh', 'state_id' => 3931],
                ['name' => 'Orange Lake', 'state_id' => 3931],
                ['name' => 'Reddick', 'state_id' => 3931],
                ['name' => 'Belleview', 'state_id' => 3931],
                ['name' => 'Ocala', 'state_id' => 3931],
                ['name' => 'Silver Springs', 'state_id' => 3931],
                ['name' => 'Summerfield', 'state_id' => 3931],
                ['name' => 'Hobe Sound', 'state_id' => 3931],
                ['name' => 'Indiantown', 'state_id' => 3931],
                ['name' => 'Jensen Beach', 'state_id' => 3931],
                ['name' => 'Palm City', 'state_id' => 3931],
                ['name' => 'Port Salerno', 'state_id' => 3931],
                ['name' => 'Stuart', 'state_id' => 3931],
                ['name' => 'Hialeah', 'state_id' => 3931],
                ['name' => 'Homestead', 'state_id' => 3931],
                ['name' => 'Opa Locka', 'state_id' => 3931],
                ['name' => 'Miami Gardens', 'state_id' => 3931],
                ['name' => 'Miami', 'state_id' => 3931],
                ['name' => 'Miami Beach', 'state_id' => 3931],
                ['name' => 'Coral Gables', 'state_id' => 3931],
                ['name' => 'Key Biscayne', 'state_id' => 3931],
                ['name' => 'North Miami Beach', 'state_id' => 3931],
                ['name' => 'Long Key', 'state_id' => 3931],
                ['name' => 'Islamorada', 'state_id' => 3931],
                ['name' => 'Key Largo', 'state_id' => 3931],
                ['name' => 'Key West', 'state_id' => 3931],
                ['name' => 'Summerland Key', 'state_id' => 3931],
                ['name' => 'Big Pine Key', 'state_id' => 3931],
                ['name' => 'Marathon', 'state_id' => 3931],
                ['name' => 'Key Colony Beach', 'state_id' => 3931],
                ['name' => 'Marathon Shores', 'state_id' => 3931],
                ['name' => 'Tavernier', 'state_id' => 3931],
                ['name' => 'Bryceville', 'state_id' => 3931],
                ['name' => 'Callahan', 'state_id' => 3931],
                ['name' => 'Fernandina Beach', 'state_id' => 3931],
                ['name' => 'Yulee', 'state_id' => 3931],
                ['name' => 'Hilliard', 'state_id' => 3931],
                ['name' => 'Baker', 'state_id' => 3931],
                ['name' => 'Crestview', 'state_id' => 3931],
                ['name' => 'Milligan', 'state_id' => 3931],
                ['name' => 'Destin', 'state_id' => 3931],
                ['name' => 'Eglin Afb', 'state_id' => 3931],
                ['name' => 'Hurlburt Field', 'state_id' => 3931],
                ['name' => 'Fort Walton Beach', 'state_id' => 3931],
                ['name' => 'Holt', 'state_id' => 3931],
                ['name' => 'Laurel Hill', 'state_id' => 3931],
                ['name' => 'Mary Esther', 'state_id' => 3931],
                ['name' => 'Niceville', 'state_id' => 3931],
                ['name' => 'Shalimar', 'state_id' => 3931],
                ['name' => 'Valparaiso', 'state_id' => 3931],
                ['name' => 'Okeechobee', 'state_id' => 3931],
                ['name' => 'Apopka', 'state_id' => 3931],
                ['name' => 'Christmas', 'state_id' => 3931],
                ['name' => 'Clarcona', 'state_id' => 3931],
                ['name' => 'Maitland', 'state_id' => 3931],
                ['name' => 'Plymouth', 'state_id' => 3931],
                ['name' => 'Tangerine', 'state_id' => 3931],
                ['name' => 'Winter Park', 'state_id' => 3931],
                ['name' => 'Zellwood', 'state_id' => 3931],
                ['name' => 'Gotha', 'state_id' => 3931],
                ['name' => 'Killarney', 'state_id' => 3931],
                ['name' => 'Oakland', 'state_id' => 3931],
                ['name' => 'Ocoee', 'state_id' => 3931],
                ['name' => 'Winter Garden', 'state_id' => 3931],
                ['name' => 'Windermere', 'state_id' => 3931],
                ['name' => 'Intercession City', 'state_id' => 3931],
                ['name' => 'Kenansville', 'state_id' => 3931],
                ['name' => 'Kissimmee', 'state_id' => 3931],
                ['name' => 'Saint Cloud', 'state_id' => 3931],
                ['name' => 'West Palm Beach', 'state_id' => 3931],
                ['name' => 'North Palm Beach', 'state_id' => 3931],
                ['name' => 'Palm Beach Gardens', 'state_id' => 3931],
                ['name' => 'Wellington', 'state_id' => 3931],
                ['name' => 'Royal Palm Beach', 'state_id' => 3931],
                ['name' => 'Boynton Beach', 'state_id' => 3931],
                ['name' => 'Boca Raton', 'state_id' => 3931],
                ['name' => 'Belle Glade', 'state_id' => 3931],
                ['name' => 'Canal Point', 'state_id' => 3931],
                ['name' => 'Delray Beach', 'state_id' => 3931],
                ['name' => 'Lake Worth', 'state_id' => 3931],
                ['name' => 'Greenacres', 'state_id' => 3931],
                ['name' => 'Jupiter', 'state_id' => 3931],
                ['name' => 'Lake Harbor', 'state_id' => 3931],
                ['name' => 'Loxahatchee', 'state_id' => 3931],
                ['name' => 'Pahokee', 'state_id' => 3931],
                ['name' => 'Palm Beach', 'state_id' => 3931],
                ['name' => 'South Bay', 'state_id' => 3931],
                ['name' => 'Dade City', 'state_id' => 3931],
                ['name' => 'Crystal Springs', 'state_id' => 3931],
                ['name' => 'Lacoochee', 'state_id' => 3931],
                ['name' => 'Zephyrhills', 'state_id' => 3931],
                ['name' => 'Wesley Chapel', 'state_id' => 3931],
                ['name' => 'Saint Leo', 'state_id' => 3931],
                ['name' => 'San Antonio', 'state_id' => 3931],
                ['name' => 'Trilby', 'state_id' => 3931],
                ['name' => 'Land O Lakes', 'state_id' => 3931],
                ['name' => 'New Port Richey', 'state_id' => 3931],
                ['name' => 'Hudson', 'state_id' => 3931],
                ['name' => 'Port Richey', 'state_id' => 3931],
                ['name' => 'Aripeka', 'state_id' => 3931],
                ['name' => 'Elfers', 'state_id' => 3931],
                ['name' => 'Holiday', 'state_id' => 3931],
                ['name' => 'Saint Petersburg', 'state_id' => 3931],
                ['name' => 'Bay Pines', 'state_id' => 3931],
                ['name' => 'Clearwater', 'state_id' => 3931],
                ['name' => 'Clearwater Beach', 'state_id' => 3931],
                ['name' => 'Largo', 'state_id' => 3931],
                ['name' => 'Seminole', 'state_id' => 3931],
                ['name' => 'Pinellas Park', 'state_id' => 3931],
                ['name' => 'Indian Rocks Beach', 'state_id' => 3931],
                ['name' => 'Belleair Beach', 'state_id' => 3931],
                ['name' => 'Ozona', 'state_id' => 3931],
                ['name' => 'Oldsmar', 'state_id' => 3931],
                ['name' => 'Crystal Beach', 'state_id' => 3931],
                ['name' => 'Palm Harbor', 'state_id' => 3931],
                ['name' => 'Tarpon Springs', 'state_id' => 3931],
                ['name' => 'Safety Harbor', 'state_id' => 3931],
                ['name' => 'Dunedin', 'state_id' => 3931],
                ['name' => 'Lakeland', 'state_id' => 3931],
                ['name' => 'Alturas', 'state_id' => 3931],
                ['name' => 'Auburndale', 'state_id' => 3931],
                ['name' => 'Babson Park', 'state_id' => 3931],
                ['name' => 'Bartow', 'state_id' => 3931],
                ['name' => 'Bradley', 'state_id' => 3931],
                ['name' => 'Davenport', 'state_id' => 3931],
                ['name' => 'Dundee', 'state_id' => 3931],
                ['name' => 'Eagle Lake', 'state_id' => 3931],
                ['name' => 'Eaton Park', 'state_id' => 3931],
                ['name' => 'Fort Meade', 'state_id' => 3931],
                ['name' => 'Frostproof', 'state_id' => 3931],
                ['name' => 'Haines City', 'state_id' => 3931],
                ['name' => 'Highland City', 'state_id' => 3931],
                ['name' => 'Homeland', 'state_id' => 3931],
                ['name' => 'Kathleen', 'state_id' => 3931],
                ['name' => 'Lake Alfred', 'state_id' => 3931],
                ['name' => 'Lake Hamilton', 'state_id' => 3931],
                ['name' => 'Lake Wales', 'state_id' => 3931],
                ['name' => 'Lakeshore', 'state_id' => 3931],
                ['name' => 'Indian Lake Estates', 'state_id' => 3931],
                ['name' => 'Nalcrest', 'state_id' => 3931],
                ['name' => 'Loughman', 'state_id' => 3931],
                ['name' => 'Mulberry', 'state_id' => 3931],
                ['name' => 'Nichols', 'state_id' => 3931],
                ['name' => 'River Ranch', 'state_id' => 3931],
                ['name' => 'Polk City', 'state_id' => 3931],
                ['name' => 'Waverly', 'state_id' => 3931],
                ['name' => 'Winter Haven', 'state_id' => 3931],
                ['name' => 'Bostwick', 'state_id' => 3931],
                ['name' => 'Crescent City', 'state_id' => 3931],
                ['name' => 'East Palatka', 'state_id' => 3931],
                ['name' => 'Grandin', 'state_id' => 3931],
                ['name' => 'Georgetown', 'state_id' => 3931],
                ['name' => 'Florahome', 'state_id' => 3931],
                ['name' => 'Hollister', 'state_id' => 3931],
                ['name' => 'Interlachen', 'state_id' => 3931],
                ['name' => 'Lake Como', 'state_id' => 3931],
                ['name' => 'Palatka', 'state_id' => 3931],
                ['name' => 'Pomona Park', 'state_id' => 3931],
                ['name' => 'Putnam Hall', 'state_id' => 3931],
                ['name' => 'San Mateo', 'state_id' => 3931],
                ['name' => 'Satsuma', 'state_id' => 3931],
                ['name' => 'Welaka', 'state_id' => 3931],
                ['name' => 'Melrose', 'state_id' => 3931],
                ['name' => 'Ponte Vedra Beach', 'state_id' => 3931],
                ['name' => 'Elkton', 'state_id' => 3931],
                ['name' => 'Saint Augustine', 'state_id' => 3931],
                ['name' => 'Ponte Vedra', 'state_id' => 3931],
                ['name' => 'Hastings', 'state_id' => 3931],
                ['name' => 'Saint Johns', 'state_id' => 3931],
                ['name' => 'Fort Pierce', 'state_id' => 3931],
                ['name' => 'Port Saint Lucie', 'state_id' => 3931],
                ['name' => 'Bagdad', 'state_id' => 3931],
                ['name' => 'Gulf Breeze', 'state_id' => 3931],
                ['name' => 'Jay', 'state_id' => 3931],
                ['name' => 'Navarre', 'state_id' => 3931],
                ['name' => 'Milton', 'state_id' => 3931],
                ['name' => 'Englewood', 'state_id' => 3931],
                ['name' => 'Osprey', 'state_id' => 3931],
                ['name' => 'Laurel', 'state_id' => 3931],
                ['name' => 'Nokomis', 'state_id' => 3931],
                ['name' => 'Venice', 'state_id' => 3931],
                ['name' => 'North Port', 'state_id' => 3931],
                ['name' => 'Altamonte Springs', 'state_id' => 3931],
                ['name' => 'Casselberry', 'state_id' => 3931],
                ['name' => 'Winter Springs', 'state_id' => 3931],
                ['name' => 'Geneva', 'state_id' => 3931],
                ['name' => 'Goldenrod', 'state_id' => 3931],
                ['name' => 'Lake Mary', 'state_id' => 3931],
                ['name' => 'Lake Monroe', 'state_id' => 3931],
                ['name' => 'Longwood', 'state_id' => 3931],
                ['name' => 'Oviedo', 'state_id' => 3931],
                ['name' => 'Sanford', 'state_id' => 3931],
                ['name' => 'Mid Florida', 'state_id' => 3931],
                ['name' => 'The Villages', 'state_id' => 3931],
                ['name' => 'Bushnell', 'state_id' => 3931],
                ['name' => 'Center Hill', 'state_id' => 3931],
                ['name' => 'Coleman', 'state_id' => 3931],
                ['name' => 'Lake Panasoffkee', 'state_id' => 3931],
                ['name' => 'Sumterville', 'state_id' => 3931],
                ['name' => 'Webster', 'state_id' => 3931],
                ['name' => 'Oxford', 'state_id' => 3931],
                ['name' => 'Wildwood', 'state_id' => 3931],
                ['name' => 'Branford', 'state_id' => 3931],
                ['name' => 'Live Oak', 'state_id' => 3931],
                ['name' => 'Mc Alpin', 'state_id' => 3931],
                ['name' => 'O Brien', 'state_id' => 3931],
                ['name' => 'Wellborn', 'state_id' => 3931],
                ['name' => 'Perry', 'state_id' => 3931],
                ['name' => 'Salem', 'state_id' => 3931],
                ['name' => 'Shady Grove', 'state_id' => 3931],
                ['name' => 'Steinhatchee', 'state_id' => 3931],
                ['name' => 'Raiford', 'state_id' => 3931],
                ['name' => 'Lake Butler', 'state_id' => 3931],
                ['name' => 'Worthington Springs', 'state_id' => 3931],
                ['name' => 'Barberville', 'state_id' => 3931],
                ['name' => 'Daytona Beach', 'state_id' => 3931],
                ['name' => 'Port Orange', 'state_id' => 3931],
                ['name' => 'De Leon Springs', 'state_id' => 3931],
                ['name' => 'Edgewater', 'state_id' => 3931],
                ['name' => 'New Smyrna Beach', 'state_id' => 3931],
                ['name' => 'Ormond Beach', 'state_id' => 3931],
                ['name' => 'Pierson', 'state_id' => 3931],
                ['name' => 'Seville', 'state_id' => 3931],
                ['name' => 'Cassadaga', 'state_id' => 3931],
                ['name' => 'Deland', 'state_id' => 3931],
                ['name' => 'Glenwood', 'state_id' => 3931],
                ['name' => 'Deltona', 'state_id' => 3931],
                ['name' => 'Lake Helen', 'state_id' => 3931],
                ['name' => 'Oak Hill', 'state_id' => 3931],
                ['name' => 'Orange City', 'state_id' => 3931],
                ['name' => 'Osteen', 'state_id' => 3931],
                ['name' => 'Crawfordville', 'state_id' => 3931],
                ['name' => 'Panacea', 'state_id' => 3931],
                ['name' => 'Saint Marks', 'state_id' => 3931],
                ['name' => 'Sopchoppy', 'state_id' => 3931],
                ['name' => 'Argyle', 'state_id' => 3931],
                ['name' => 'Defuniak Springs', 'state_id' => 3931],
                ['name' => 'Mossy Head', 'state_id' => 3931],
                ['name' => 'Freeport', 'state_id' => 3931],
                ['name' => 'Santa Rosa Beach', 'state_id' => 3931],
                ['name' => 'Rosemary Beach', 'state_id' => 3931],
                ['name' => 'Paxton', 'state_id' => 3931],
                ['name' => 'Miramar Beach', 'state_id' => 3931],
                ['name' => 'Caryville', 'state_id' => 3931],
                ['name' => 'Chipley', 'state_id' => 3931],
                ['name' => 'Ebro', 'state_id' => 3931],
                ['name' => 'Vernon', 'state_id' => 3931],
                ['name' => 'Wausau', 'state_id' => 3931]
            ]);
        }
    }
}
