<?php

use Illuminate\Database\Seeder;

class state20TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MA - Massachusetts.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Buzzards Bay', 'state_id' => 3944],
                ['name' => 'Cataumet', 'state_id' => 3944],
                ['name' => 'East Falmouth', 'state_id' => 3944],
                ['name' => 'East Sandwich', 'state_id' => 3944],
                ['name' => 'Falmouth', 'state_id' => 3944],
                ['name' => 'Woods Hole', 'state_id' => 3944],
                ['name' => 'Monument Beach', 'state_id' => 3944],
                ['name' => 'North Falmouth', 'state_id' => 3944],
                ['name' => 'Pocasset', 'state_id' => 3944],
                ['name' => 'Sagamore', 'state_id' => 3944],
                ['name' => 'Sagamore Beach', 'state_id' => 3944],
                ['name' => 'Sandwich', 'state_id' => 3944],
                ['name' => 'West Falmouth', 'state_id' => 3944],
                ['name' => 'Hyannis', 'state_id' => 3944],
                ['name' => 'Barnstable', 'state_id' => 3944],
                ['name' => 'Brewster', 'state_id' => 3944],
                ['name' => 'Centerville', 'state_id' => 3944],
                ['name' => 'Chatham', 'state_id' => 3944],
                ['name' => 'Cotuit', 'state_id' => 3944],
                ['name' => 'Cummaquid', 'state_id' => 3944],
                ['name' => 'Dennis', 'state_id' => 3944],
                ['name' => 'Dennis Port', 'state_id' => 3944],
                ['name' => 'East Dennis', 'state_id' => 3944],
                ['name' => 'Eastham', 'state_id' => 3944],
                ['name' => 'East Orleans', 'state_id' => 3944],
                ['name' => 'Forestdale', 'state_id' => 3944],
                ['name' => 'Harwich', 'state_id' => 3944],
                ['name' => 'Harwich Port', 'state_id' => 3944],
                ['name' => 'Hyannis Port', 'state_id' => 3944],
                ['name' => 'Marstons Mills', 'state_id' => 3944],
                ['name' => 'Mashpee', 'state_id' => 3944],
                ['name' => 'North Chatham', 'state_id' => 3944],
                ['name' => 'North Eastham', 'state_id' => 3944],
                ['name' => 'North Truro', 'state_id' => 3944],
                ['name' => 'Orleans', 'state_id' => 3944],
                ['name' => 'Osterville', 'state_id' => 3944],
                ['name' => 'Provincetown', 'state_id' => 3944],
                ['name' => 'South Chatham', 'state_id' => 3944],
                ['name' => 'South Dennis', 'state_id' => 3944],
                ['name' => 'South Harwich', 'state_id' => 3944],
                ['name' => 'South Orleans', 'state_id' => 3944],
                ['name' => 'South Wellfleet', 'state_id' => 3944],
                ['name' => 'South Yarmouth', 'state_id' => 3944],
                ['name' => 'Truro', 'state_id' => 3944],
                ['name' => 'Wellfleet', 'state_id' => 3944],
                ['name' => 'West Barnstable', 'state_id' => 3944],
                ['name' => 'West Chatham', 'state_id' => 3944],
                ['name' => 'West Dennis', 'state_id' => 3944],
                ['name' => 'West Harwich', 'state_id' => 3944],
                ['name' => 'West Hyannisport', 'state_id' => 3944],
                ['name' => 'West Yarmouth', 'state_id' => 3944],
                ['name' => 'Yarmouth Port', 'state_id' => 3944],
                ['name' => 'East Otis', 'state_id' => 3944],
                ['name' => 'Pittsfield', 'state_id' => 3944],
                ['name' => 'Adams', 'state_id' => 3944],
                ['name' => 'Ashley Falls', 'state_id' => 3944],
                ['name' => 'Becket', 'state_id' => 3944],
                ['name' => 'Berkshire', 'state_id' => 3944],
                ['name' => 'Cheshire', 'state_id' => 3944],
                ['name' => 'Dalton', 'state_id' => 3944],
                ['name' => 'Glendale', 'state_id' => 3944],
                ['name' => 'Great Barrington', 'state_id' => 3944],
                ['name' => 'Hinsdale', 'state_id' => 3944],
                ['name' => 'Housatonic', 'state_id' => 3944],
                ['name' => 'Lanesborough', 'state_id' => 3944],
                ['name' => 'Lee', 'state_id' => 3944],
                ['name' => 'Lenox', 'state_id' => 3944],
                ['name' => 'Lenox Dale', 'state_id' => 3944],
                ['name' => 'Mill River', 'state_id' => 3944],
                ['name' => 'Monterey', 'state_id' => 3944],
                ['name' => 'North Adams', 'state_id' => 3944],
                ['name' => 'North Egremont', 'state_id' => 3944],
                ['name' => 'Otis', 'state_id' => 3944],
                ['name' => 'Richmond', 'state_id' => 3944],
                ['name' => 'Sandisfield', 'state_id' => 3944],
                ['name' => 'Savoy', 'state_id' => 3944],
                ['name' => 'Sheffield', 'state_id' => 3944],
                ['name' => 'South Egremont', 'state_id' => 3944],
                ['name' => 'Southfield', 'state_id' => 3944],
                ['name' => 'South Lee', 'state_id' => 3944],
                ['name' => 'Stockbridge', 'state_id' => 3944],
                ['name' => 'Tyringham', 'state_id' => 3944],
                ['name' => 'West Stockbridge', 'state_id' => 3944],
                ['name' => 'Williamstown', 'state_id' => 3944],
                ['name' => 'Windsor', 'state_id' => 3944],
                ['name' => 'Drury', 'state_id' => 3944],
                ['name' => 'Mansfield', 'state_id' => 3944],
                ['name' => 'Easton', 'state_id' => 3944],
                ['name' => 'North Easton', 'state_id' => 3944],
                ['name' => 'South Easton', 'state_id' => 3944],
                ['name' => 'Assonet', 'state_id' => 3944],
                ['name' => 'Attleboro', 'state_id' => 3944],
                ['name' => 'Chartley', 'state_id' => 3944],
                ['name' => 'Dartmouth', 'state_id' => 3944],
                ['name' => 'Dighton', 'state_id' => 3944],
                ['name' => 'East Freetown', 'state_id' => 3944],
                ['name' => 'East Taunton', 'state_id' => 3944],
                ['name' => 'Fairhaven', 'state_id' => 3944],
                ['name' => 'Fall River', 'state_id' => 3944],
                ['name' => 'Somerset', 'state_id' => 3944],
                ['name' => 'New Bedford', 'state_id' => 3944],
                ['name' => 'Acushnet', 'state_id' => 3944],
                ['name' => 'North Dartmouth', 'state_id' => 3944],
                ['name' => 'South Dartmouth', 'state_id' => 3944],
                ['name' => 'North Attleboro', 'state_id' => 3944],
                ['name' => 'Attleboro Falls', 'state_id' => 3944],
                ['name' => 'North Dighton', 'state_id' => 3944],
                ['name' => 'Norton', 'state_id' => 3944],
                ['name' => 'Raynham', 'state_id' => 3944],
                ['name' => 'Raynham Center', 'state_id' => 3944],
                ['name' => 'Rehoboth', 'state_id' => 3944],
                ['name' => 'Seekonk', 'state_id' => 3944],
                ['name' => 'Swansea', 'state_id' => 3944],
                ['name' => 'Berkley', 'state_id' => 3944],
                ['name' => 'Taunton', 'state_id' => 3944],
                ['name' => 'Westport', 'state_id' => 3944],
                ['name' => 'Westport Point', 'state_id' => 3944],
                ['name' => 'Chilmark', 'state_id' => 3944],
                ['name' => 'Edgartown', 'state_id' => 3944],
                ['name' => 'Menemsha', 'state_id' => 3944],
                ['name' => 'Oak Bluffs', 'state_id' => 3944],
                ['name' => 'Vineyard Haven', 'state_id' => 3944],
                ['name' => 'West Tisbury', 'state_id' => 3944],
                ['name' => 'Cuttyhunk', 'state_id' => 3944],
                ['name' => 'Andover', 'state_id' => 3944],
                ['name' => 'Haverhill', 'state_id' => 3944],
                ['name' => 'Georgetown', 'state_id' => 3944],
                ['name' => 'Groveland', 'state_id' => 3944],
                ['name' => 'Lawrence', 'state_id' => 3944],
                ['name' => 'Methuen', 'state_id' => 3944],
                ['name' => 'North Andover', 'state_id' => 3944],
                ['name' => 'Merrimac', 'state_id' => 3944],
                ['name' => 'West Boxford', 'state_id' => 3944],
                ['name' => 'Lynn', 'state_id' => 3944],
                ['name' => 'Saugus', 'state_id' => 3944],
                ['name' => 'Swampscott', 'state_id' => 3944],
                ['name' => 'Nahant', 'state_id' => 3944],
                ['name' => 'Amesbury', 'state_id' => 3944],
                ['name' => 'Beverly', 'state_id' => 3944],
                ['name' => 'Boxford', 'state_id' => 3944],
                ['name' => 'Byfield', 'state_id' => 3944],
                ['name' => 'Danvers', 'state_id' => 3944],
                ['name' => 'Essex', 'state_id' => 3944],
                ['name' => 'Gloucester', 'state_id' => 3944],
                ['name' => 'Hamilton', 'state_id' => 3944],
                ['name' => 'Hathorne', 'state_id' => 3944],
                ['name' => 'Ipswich', 'state_id' => 3944],
                ['name' => 'Lynnfield', 'state_id' => 3944],
                ['name' => 'Manchester', 'state_id' => 3944],
                ['name' => 'Marblehead', 'state_id' => 3944],
                ['name' => 'Middleton', 'state_id' => 3944],
                ['name' => 'Newburyport', 'state_id' => 3944],
                ['name' => 'Newbury', 'state_id' => 3944],
                ['name' => 'Salisbury', 'state_id' => 3944],
                ['name' => 'Peabody', 'state_id' => 3944],
                ['name' => 'Prides Crossing', 'state_id' => 3944],
                ['name' => 'Rockport', 'state_id' => 3944],
                ['name' => 'Rowley', 'state_id' => 3944],
                ['name' => 'Salem', 'state_id' => 3944],
                ['name' => 'South Hamilton', 'state_id' => 3944],
                ['name' => 'Topsfield', 'state_id' => 3944],
                ['name' => 'Wenham', 'state_id' => 3944],
                ['name' => 'West Newbury', 'state_id' => 3944],
                ['name' => 'Leverett', 'state_id' => 3944],
                ['name' => 'Shutesbury', 'state_id' => 3944],
                ['name' => 'Whately', 'state_id' => 3944],
                ['name' => 'Greenfield', 'state_id' => 3944],
                ['name' => 'Ashfield', 'state_id' => 3944],
                ['name' => 'Bernardston', 'state_id' => 3944],
                ['name' => 'Buckland', 'state_id' => 3944],
                ['name' => 'Charlemont', 'state_id' => 3944],
                ['name' => 'Colrain', 'state_id' => 3944],
                ['name' => 'Conway', 'state_id' => 3944],
                ['name' => 'Deerfield', 'state_id' => 3944],
                ['name' => 'Erving', 'state_id' => 3944],
                ['name' => 'Heath', 'state_id' => 3944],
                ['name' => 'Lake Pleasant', 'state_id' => 3944],
                ['name' => 'Millers Falls', 'state_id' => 3944],
                ['name' => 'Monroe Bridge', 'state_id' => 3944],
                ['name' => 'Montague', 'state_id' => 3944],
                ['name' => 'Gill', 'state_id' => 3944],
                ['name' => 'New Salem', 'state_id' => 3944],
                ['name' => 'Northfield', 'state_id' => 3944],
                ['name' => 'Orange', 'state_id' => 3944],
                ['name' => 'Rowe', 'state_id' => 3944],
                ['name' => 'Shelburne Falls', 'state_id' => 3944],
                ['name' => 'South Deerfield', 'state_id' => 3944],
                ['name' => 'Sunderland', 'state_id' => 3944],
                ['name' => 'Turners Falls', 'state_id' => 3944],
                ['name' => 'Warwick', 'state_id' => 3944],
                ['name' => 'Wendell', 'state_id' => 3944],
                ['name' => 'Wendell Depot', 'state_id' => 3944],
                ['name' => 'Agawam', 'state_id' => 3944],
                ['name' => 'Blandford', 'state_id' => 3944],
                ['name' => 'Bondsville', 'state_id' => 3944],
                ['name' => 'Brimfield', 'state_id' => 3944],
                ['name' => 'Chester', 'state_id' => 3944],
                ['name' => 'Chicopee', 'state_id' => 3944],
                ['name' => 'East Longmeadow', 'state_id' => 3944],
                ['name' => 'Feeding Hills', 'state_id' => 3944],
                ['name' => 'Granville', 'state_id' => 3944],
                ['name' => 'Hampden', 'state_id' => 3944],
                ['name' => 'Holyoke', 'state_id' => 3944],
                ['name' => 'Ludlow', 'state_id' => 3944],
                ['name' => 'Monson', 'state_id' => 3944],
                ['name' => 'Palmer', 'state_id' => 3944],
                ['name' => 'Russell', 'state_id' => 3944],
                ['name' => 'Southwick', 'state_id' => 3944],
                ['name' => 'Thorndike', 'state_id' => 3944],
                ['name' => 'Three Rivers', 'state_id' => 3944],
                ['name' => 'Wales', 'state_id' => 3944],
                ['name' => 'Westfield', 'state_id' => 3944],
                ['name' => 'West Springfield', 'state_id' => 3944],
                ['name' => 'Wilbraham', 'state_id' => 3944],
                ['name' => 'Woronoco', 'state_id' => 3944],
                ['name' => 'Springfield', 'state_id' => 3944],
                ['name' => 'Longmeadow', 'state_id' => 3944],
                ['name' => 'Indian Orchard', 'state_id' => 3944],
                ['name' => 'Holland', 'state_id' => 3944],
                ['name' => 'Amherst', 'state_id' => 3944],
                ['name' => 'Belchertown', 'state_id' => 3944],
                ['name' => 'Chesterfield', 'state_id' => 3944],
                ['name' => 'Cummington', 'state_id' => 3944],
                ['name' => 'Easthampton', 'state_id' => 3944],
                ['name' => 'Goshen', 'state_id' => 3944],
                ['name' => 'Granby', 'state_id' => 3944],
                ['name' => 'Hadley', 'state_id' => 3944],
                ['name' => 'Hatfield', 'state_id' => 3944],
                ['name' => 'Haydenville', 'state_id' => 3944],
                ['name' => 'Huntington', 'state_id' => 3944],
                ['name' => 'Leeds', 'state_id' => 3944],
                ['name' => 'North Amherst', 'state_id' => 3944],
                ['name' => 'Northampton', 'state_id' => 3944],
                ['name' => 'Florence', 'state_id' => 3944],
                ['name' => 'North Hatfield', 'state_id' => 3944],
                ['name' => 'Plainfield', 'state_id' => 3944],
                ['name' => 'Southampton', 'state_id' => 3944],
                ['name' => 'South Hadley', 'state_id' => 3944],
                ['name' => 'Ware', 'state_id' => 3944],
                ['name' => 'West Chesterfield', 'state_id' => 3944],
                ['name' => 'West Hatfield', 'state_id' => 3944],
                ['name' => 'Williamsburg', 'state_id' => 3944],
                ['name' => 'Worthington', 'state_id' => 3944],
                ['name' => 'Middlefield', 'state_id' => 3944],
                ['name' => 'Ashby', 'state_id' => 3944],
                ['name' => 'Ayer', 'state_id' => 3944],
                ['name' => 'Groton', 'state_id' => 3944],
                ['name' => 'Littleton', 'state_id' => 3944],
                ['name' => 'Pepperell', 'state_id' => 3944],
                ['name' => 'Shirley', 'state_id' => 3944],
                ['name' => 'Townsend', 'state_id' => 3944],
                ['name' => 'West Groton', 'state_id' => 3944],
                ['name' => 'West Townsend', 'state_id' => 3944],
                ['name' => 'Framingham', 'state_id' => 3944],
                ['name' => 'Acton', 'state_id' => 3944],
                ['name' => 'Boxborough', 'state_id' => 3944],
                ['name' => 'Ashland', 'state_id' => 3944],
                ['name' => 'Bedford', 'state_id' => 3944],
                ['name' => 'Hanscom Afb', 'state_id' => 3944],
                ['name' => 'Carlisle', 'state_id' => 3944],
                ['name' => 'Concord', 'state_id' => 3944],
                ['name' => 'Holliston', 'state_id' => 3944],
                ['name' => 'Hopkinton', 'state_id' => 3944],
                ['name' => 'Hudson', 'state_id' => 3944],
                ['name' => 'Marlborough', 'state_id' => 3944],
                ['name' => 'Maynard', 'state_id' => 3944],
                ['name' => 'Natick', 'state_id' => 3944],
                ['name' => 'Sherborn', 'state_id' => 3944],
                ['name' => 'Lincoln', 'state_id' => 3944],
                ['name' => 'Stow', 'state_id' => 3944],
                ['name' => 'Sudbury', 'state_id' => 3944],
                ['name' => 'Wayland', 'state_id' => 3944],
                ['name' => 'Woodville', 'state_id' => 3944],
                ['name' => 'Woburn', 'state_id' => 3944],
                ['name' => 'Burlington', 'state_id' => 3944],
                ['name' => 'Billerica', 'state_id' => 3944],
                ['name' => 'Chelmsford', 'state_id' => 3944],
                ['name' => 'Dracut', 'state_id' => 3944],
                ['name' => 'Dunstable', 'state_id' => 3944],
                ['name' => 'Lowell', 'state_id' => 3944],
                ['name' => 'North Billerica', 'state_id' => 3944],
                ['name' => 'North Chelmsford', 'state_id' => 3944],
                ['name' => 'North Reading', 'state_id' => 3944],
                ['name' => 'Nutting Lake', 'state_id' => 3944],
                ['name' => 'Pinehurst', 'state_id' => 3944],
                ['name' => 'Reading', 'state_id' => 3944],
                ['name' => 'Tewksbury', 'state_id' => 3944],
                ['name' => 'Tyngsboro', 'state_id' => 3944],
                ['name' => 'Wakefield', 'state_id' => 3944],
                ['name' => 'Westford', 'state_id' => 3944],
                ['name' => 'Wilmington', 'state_id' => 3944],
                ['name' => 'Winchester', 'state_id' => 3944],
                ['name' => 'Cambridge', 'state_id' => 3944],
                ['name' => 'Somerville', 'state_id' => 3944],
                ['name' => 'Malden', 'state_id' => 3944],
                ['name' => 'Everett', 'state_id' => 3944],
                ['name' => 'Medford', 'state_id' => 3944],
                ['name' => 'West Medford', 'state_id' => 3944],
                ['name' => 'Melrose', 'state_id' => 3944],
                ['name' => 'Stoneham', 'state_id' => 3944],
                ['name' => 'Boston', 'state_id' => 3944],
                ['name' => 'Lexington', 'state_id' => 3944],
                ['name' => 'Waltham', 'state_id' => 3944],
                ['name' => 'North Waltham', 'state_id' => 3944],
                ['name' => 'New Town', 'state_id' => 3944],
                ['name' => 'Newton', 'state_id' => 3944],
                ['name' => 'Newton Center', 'state_id' => 3944],
                ['name' => 'Newtonville', 'state_id' => 3944],
                ['name' => 'Newton Highlands', 'state_id' => 3944],
                ['name' => 'Newton Lower Falls', 'state_id' => 3944],
                ['name' => 'Newton Upper Falls', 'state_id' => 3944],
                ['name' => 'West Newton', 'state_id' => 3944],
                ['name' => 'Auburndale', 'state_id' => 3944],
                ['name' => 'Chestnut Hill', 'state_id' => 3944],
                ['name' => 'Waban', 'state_id' => 3944],
                ['name' => 'Watertown', 'state_id' => 3944],
                ['name' => 'Arlington', 'state_id' => 3944],
                ['name' => 'Arlington Heights', 'state_id' => 3944],
                ['name' => 'Belmont', 'state_id' => 3944],
                ['name' => 'Waverley', 'state_id' => 3944],
                ['name' => 'Weston', 'state_id' => 3944],
                ['name' => 'Nonantum', 'state_id' => 3944],
                ['name' => 'Nantucket', 'state_id' => 3944],
                ['name' => 'Siasconset', 'state_id' => 3944],
                ['name' => 'Bellingham', 'state_id' => 3944],
                ['name' => 'Canton', 'state_id' => 3944],
                ['name' => 'Cohasset', 'state_id' => 3944],
                ['name' => 'Dedham', 'state_id' => 3944],
                ['name' => 'Dover', 'state_id' => 3944],
                ['name' => 'East Walpole', 'state_id' => 3944],
                ['name' => 'Foxboro', 'state_id' => 3944],
                ['name' => 'Franklin', 'state_id' => 3944],
                ['name' => 'Medfield', 'state_id' => 3944],
                ['name' => 'Medway', 'state_id' => 3944],
                ['name' => 'Millis', 'state_id' => 3944],
                ['name' => 'Norfolk', 'state_id' => 3944],
                ['name' => 'Norwood', 'state_id' => 3944],
                ['name' => 'Sharon', 'state_id' => 3944],
                ['name' => 'Sheldonville', 'state_id' => 3944],
                ['name' => 'South Walpole', 'state_id' => 3944],
                ['name' => 'Stoughton', 'state_id' => 3944],
                ['name' => 'Walpole', 'state_id' => 3944],
                ['name' => 'Westwood', 'state_id' => 3944],
                ['name' => 'Wrentham', 'state_id' => 3944],
                ['name' => 'Quincy', 'state_id' => 3944],
                ['name' => 'Braintree', 'state_id' => 3944],
                ['name' => 'Milton', 'state_id' => 3944],
                ['name' => 'Milton Village', 'state_id' => 3944],
                ['name' => 'Weymouth', 'state_id' => 3944],
                ['name' => 'East Weymouth', 'state_id' => 3944],
                ['name' => 'South Weymouth', 'state_id' => 3944],
                ['name' => 'North Weymouth', 'state_id' => 3944],
                ['name' => 'Avon', 'state_id' => 3944],
                ['name' => 'Holbrook', 'state_id' => 3944],
                ['name' => 'Randolph', 'state_id' => 3944],
                ['name' => 'Brookline', 'state_id' => 3944],
                ['name' => 'Brookline Village', 'state_id' => 3944],
                ['name' => 'Babson Park', 'state_id' => 3944],
                ['name' => 'Wellesley Hills', 'state_id' => 3944],
                ['name' => 'Wellesley', 'state_id' => 3944],
                ['name' => 'Needham', 'state_id' => 3944],
                ['name' => 'Needham Heights', 'state_id' => 3944],
                ['name' => 'Plainville', 'state_id' => 3944],
                ['name' => 'Accord', 'state_id' => 3944],
                ['name' => 'Brant Rock', 'state_id' => 3944],
                ['name' => 'Greenbush', 'state_id' => 3944],
                ['name' => 'Green Harbor', 'state_id' => 3944],
                ['name' => 'Hingham', 'state_id' => 3944],
                ['name' => 'Hull', 'state_id' => 3944],
                ['name' => 'Humarock', 'state_id' => 3944],
                ['name' => 'Marshfield', 'state_id' => 3944],
                ['name' => 'Marshfield Hills', 'state_id' => 3944],
                ['name' => 'Minot', 'state_id' => 3944],
                ['name' => 'North Marshfield', 'state_id' => 3944],
                ['name' => 'North Scituate', 'state_id' => 3944],
                ['name' => 'Norwell', 'state_id' => 3944],
                ['name' => 'Ocean Bluff', 'state_id' => 3944],
                ['name' => 'Scituate', 'state_id' => 3944],
                ['name' => 'Brockton', 'state_id' => 3944],
                ['name' => 'Bridgewater', 'state_id' => 3944],
                ['name' => 'Bryantville', 'state_id' => 3944],
                ['name' => 'Carver', 'state_id' => 3944],
                ['name' => 'Duxbury', 'state_id' => 3944],
                ['name' => 'East Bridgewater', 'state_id' => 3944],
                ['name' => 'Elmwood', 'state_id' => 3944],
                ['name' => 'Halifax', 'state_id' => 3944],
                ['name' => 'Hanover', 'state_id' => 3944],
                ['name' => 'Hanson', 'state_id' => 3944],
                ['name' => 'Middleboro', 'state_id' => 3944],
                ['name' => 'Manomet', 'state_id' => 3944],
                ['name' => 'Lakeville', 'state_id' => 3944],
                ['name' => 'Monponsett', 'state_id' => 3944],
                ['name' => 'Abington', 'state_id' => 3944],
                ['name' => 'North Carver', 'state_id' => 3944],
                ['name' => 'North Pembroke', 'state_id' => 3944],
                ['name' => 'Pembroke', 'state_id' => 3944],
                ['name' => 'Plymouth', 'state_id' => 3944],
                ['name' => 'Kingston', 'state_id' => 3944],
                ['name' => 'South Carver', 'state_id' => 3944],
                ['name' => 'Plympton', 'state_id' => 3944],
                ['name' => 'Rockland', 'state_id' => 3944],
                ['name' => 'West Bridgewater', 'state_id' => 3944],
                ['name' => 'White Horse Beach', 'state_id' => 3944],
                ['name' => 'Whitman', 'state_id' => 3944],
                ['name' => 'East Wareham', 'state_id' => 3944],
                ['name' => 'Onset', 'state_id' => 3944],
                ['name' => 'Wareham', 'state_id' => 3944],
                ['name' => 'West Wareham', 'state_id' => 3944],
                ['name' => 'Marion', 'state_id' => 3944],
                ['name' => 'Mattapoisett', 'state_id' => 3944],
                ['name' => 'Rochester', 'state_id' => 3944],
                ['name' => 'Roxbury', 'state_id' => 3944],
                ['name' => 'Roxbury Crossing', 'state_id' => 3944],
                ['name' => 'Dorchester', 'state_id' => 3944],
                ['name' => 'Dorchester Center', 'state_id' => 3944],
                ['name' => 'Mattapan', 'state_id' => 3944],
                ['name' => 'Charlestown', 'state_id' => 3944],
                ['name' => 'Jamaica Plain', 'state_id' => 3944],
                ['name' => 'Roslindale', 'state_id' => 3944],
                ['name' => 'West Roxbury', 'state_id' => 3944],
                ['name' => 'Allston', 'state_id' => 3944],
                ['name' => 'Brighton', 'state_id' => 3944],
                ['name' => 'Hyde Park', 'state_id' => 3944],
                ['name' => 'Readville', 'state_id' => 3944],
                ['name' => 'Chelsea', 'state_id' => 3944],
                ['name' => 'Revere', 'state_id' => 3944],
                ['name' => 'Winthrop', 'state_id' => 3944],
                ['name' => 'Barre', 'state_id' => 3944],
                ['name' => 'Gilbertville', 'state_id' => 3944],
                ['name' => 'Hardwick', 'state_id' => 3944],
                ['name' => 'Oakham', 'state_id' => 3944],
                ['name' => 'South Barre', 'state_id' => 3944],
                ['name' => 'Warren', 'state_id' => 3944],
                ['name' => 'West Warren', 'state_id' => 3944],
                ['name' => 'Wheelwright', 'state_id' => 3944],
                ['name' => 'Athol', 'state_id' => 3944],
                ['name' => 'Petersham', 'state_id' => 3944],
                ['name' => 'Royalston', 'state_id' => 3944],
                ['name' => 'Fitchburg', 'state_id' => 3944],
                ['name' => 'Ashburnham', 'state_id' => 3944],
                ['name' => 'Devens', 'state_id' => 3944],
                ['name' => 'Baldwinville', 'state_id' => 3944],
                ['name' => 'East Templeton', 'state_id' => 3944],
                ['name' => 'Gardner', 'state_id' => 3944],
                ['name' => 'Westminster', 'state_id' => 3944],
                ['name' => 'Harvard', 'state_id' => 3944],
                ['name' => 'Hubbardston', 'state_id' => 3944],
                ['name' => 'Leominster', 'state_id' => 3944],
                ['name' => 'Lunenburg', 'state_id' => 3944],
                ['name' => 'Still River', 'state_id' => 3944],
                ['name' => 'Templeton', 'state_id' => 3944],
                ['name' => 'Winchendon', 'state_id' => 3944],
                ['name' => 'Auburn', 'state_id' => 3944],
                ['name' => 'Berlin', 'state_id' => 3944],
                ['name' => 'Blackstone', 'state_id' => 3944],
                ['name' => 'Boylston', 'state_id' => 3944],
                ['name' => 'Brookfield', 'state_id' => 3944],
                ['name' => 'Charlton', 'state_id' => 3944],
                ['name' => 'Charlton City', 'state_id' => 3944],
                ['name' => 'Charlton Depot', 'state_id' => 3944],
                ['name' => 'Clinton', 'state_id' => 3944],
                ['name' => 'East Brookfield', 'state_id' => 3944],
                ['name' => 'Douglas', 'state_id' => 3944],
                ['name' => 'Fiskdale', 'state_id' => 3944],
                ['name' => 'Grafton', 'state_id' => 3944],
                ['name' => 'Holden', 'state_id' => 3944],
                ['name' => 'Jefferson', 'state_id' => 3944],
                ['name' => 'Lancaster', 'state_id' => 3944],
                ['name' => 'Leicester', 'state_id' => 3944],
                ['name' => 'Linwood', 'state_id' => 3944],
                ['name' => 'Manchaug', 'state_id' => 3944],
                ['name' => 'Millbury', 'state_id' => 3944],
                ['name' => 'Millville', 'state_id' => 3944],
                ['name' => 'New Braintree', 'state_id' => 3944],
                ['name' => 'Northborough', 'state_id' => 3944],
                ['name' => 'Northbridge', 'state_id' => 3944],
                ['name' => 'North Brookfield', 'state_id' => 3944],
                ['name' => 'North Grafton', 'state_id' => 3944],
                ['name' => 'North Oxford', 'state_id' => 3944],
                ['name' => 'North Uxbridge', 'state_id' => 3944],
                ['name' => 'Oxford', 'state_id' => 3944],
                ['name' => 'Princeton', 'state_id' => 3944],
                ['name' => 'Rochdale', 'state_id' => 3944],
                ['name' => 'Rutland', 'state_id' => 3944],
                ['name' => 'Shrewsbury', 'state_id' => 3944],
                ['name' => 'Southbridge', 'state_id' => 3944],
                ['name' => 'South Grafton', 'state_id' => 3944],
                ['name' => 'South Lancaster', 'state_id' => 3944],
                ['name' => 'Spencer', 'state_id' => 3944],
                ['name' => 'Sterling', 'state_id' => 3944],
                ['name' => 'Sturbridge', 'state_id' => 3944],
                ['name' => 'Upton', 'state_id' => 3944],
                ['name' => 'Uxbridge', 'state_id' => 3944],
                ['name' => 'Webster', 'state_id' => 3944],
                ['name' => 'Dudley', 'state_id' => 3944],
                ['name' => 'Westborough', 'state_id' => 3944],
                ['name' => 'West Boylston', 'state_id' => 3944],
                ['name' => 'West Brookfield', 'state_id' => 3944],
                ['name' => 'West Millbury', 'state_id' => 3944],
                ['name' => 'Whitinsville', 'state_id' => 3944],
                ['name' => 'Sutton', 'state_id' => 3944],
                ['name' => 'Worcester', 'state_id' => 3944],
                ['name' => 'Cherry Valley', 'state_id' => 3944],
                ['name' => 'Paxton', 'state_id' => 3944],
                ['name' => 'Bolton', 'state_id' => 3944],
                ['name' => 'Fayville', 'state_id' => 3944],
                ['name' => 'Hopedale', 'state_id' => 3944],
                ['name' => 'Mendon', 'state_id' => 3944],
                ['name' => 'Milford', 'state_id' => 3944],
                ['name' => 'Southborough', 'state_id' => 3944]
            ]);
        }
    }
}
