<?php

use Illuminate\Database\Seeder;

class state34TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NV - Nevada.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Fallon', 'state_id' => 3952],
                ['name' => 'The Lakes', 'state_id' => 3952],
                ['name' => 'Henderson', 'state_id' => 3952],
                ['name' => 'Blue Diamond', 'state_id' => 3952],
                ['name' => 'Boulder City', 'state_id' => 3952],
                ['name' => 'Bunkerville', 'state_id' => 3952],
                ['name' => 'Indian Springs', 'state_id' => 3952],
                ['name' => 'Jean', 'state_id' => 3952],
                ['name' => 'Logandale', 'state_id' => 3952],
                ['name' => 'Mesquite', 'state_id' => 3952],
                ['name' => 'Moapa', 'state_id' => 3952],
                ['name' => 'Laughlin', 'state_id' => 3952],
                ['name' => 'North Las Vegas', 'state_id' => 3952],
                ['name' => 'Coyote Springs', 'state_id' => 3952],
                ['name' => 'Cal Nev Ari', 'state_id' => 3952],
                ['name' => 'Overton', 'state_id' => 3952],
                ['name' => 'Searchlight', 'state_id' => 3952],
                ['name' => 'Sloan', 'state_id' => 3952],
                ['name' => 'Las Vegas', 'state_id' => 3952],
                ['name' => 'Nellis Afb', 'state_id' => 3952],
                ['name' => 'Gardnerville', 'state_id' => 3952],
                ['name' => 'Genoa', 'state_id' => 3952],
                ['name' => 'Glenbrook', 'state_id' => 3952],
                ['name' => 'Minden', 'state_id' => 3952],
                ['name' => 'Zephyr Cove', 'state_id' => 3952],
                ['name' => 'Stateline', 'state_id' => 3952],
                ['name' => 'Carson City', 'state_id' => 3952],
                ['name' => 'Elko', 'state_id' => 3952],
                ['name' => 'Spring Creek', 'state_id' => 3952],
                ['name' => 'Carlin', 'state_id' => 3952],
                ['name' => 'Deeth', 'state_id' => 3952],
                ['name' => 'Jackpot', 'state_id' => 3952],
                ['name' => 'Jarbidge', 'state_id' => 3952],
                ['name' => 'Lamoille', 'state_id' => 3952],
                ['name' => 'Montello', 'state_id' => 3952],
                ['name' => 'Mountain City', 'state_id' => 3952],
                ['name' => 'Owyhee', 'state_id' => 3952],
                ['name' => 'Ruby Valley', 'state_id' => 3952],
                ['name' => 'Tuscarora', 'state_id' => 3952],
                ['name' => 'Wells', 'state_id' => 3952],
                ['name' => 'West Wendover', 'state_id' => 3952],
                ['name' => 'Dyer', 'state_id' => 3952],
                ['name' => 'Goldfield', 'state_id' => 3952],
                ['name' => 'Silverpeak', 'state_id' => 3952],
                ['name' => 'Eureka', 'state_id' => 3952],
                ['name' => 'Crescent Valley', 'state_id' => 3952],
                ['name' => 'Denio', 'state_id' => 3952],
                ['name' => 'Golconda', 'state_id' => 3952],
                ['name' => 'Mc Dermitt', 'state_id' => 3952],
                ['name' => 'Orovada', 'state_id' => 3952],
                ['name' => 'Paradise Valley', 'state_id' => 3952],
                ['name' => 'Valmy', 'state_id' => 3952],
                ['name' => 'Winnemucca', 'state_id' => 3952],
                ['name' => 'Austin', 'state_id' => 3952],
                ['name' => 'Battle Mountain', 'state_id' => 3952],
                ['name' => 'Alamo', 'state_id' => 3952],
                ['name' => 'Caliente', 'state_id' => 3952],
                ['name' => 'Hiko', 'state_id' => 3952],
                ['name' => 'Panaca', 'state_id' => 3952],
                ['name' => 'Pioche', 'state_id' => 3952],
                ['name' => 'Dayton', 'state_id' => 3952],
                ['name' => 'Fernley', 'state_id' => 3952],
                ['name' => 'Silver City', 'state_id' => 3952],
                ['name' => 'Silver Springs', 'state_id' => 3952],
                ['name' => 'Smith', 'state_id' => 3952],
                ['name' => 'Wellington', 'state_id' => 3952],
                ['name' => 'Yerington', 'state_id' => 3952],
                ['name' => 'Hawthorne', 'state_id' => 3952],
                ['name' => 'Luning', 'state_id' => 3952],
                ['name' => 'Mina', 'state_id' => 3952],
                ['name' => 'Schurz', 'state_id' => 3952],
                ['name' => 'Beatty', 'state_id' => 3952],
                ['name' => 'Amargosa Valley', 'state_id' => 3952],
                ['name' => 'Manhattan', 'state_id' => 3952],
                ['name' => 'Mercury', 'state_id' => 3952],
                ['name' => 'Pahrump', 'state_id' => 3952],
                ['name' => 'Round Mountain', 'state_id' => 3952],
                ['name' => 'Tonopah', 'state_id' => 3952],
                ['name' => 'Gabbs', 'state_id' => 3952],
                ['name' => 'Imlay', 'state_id' => 3952],
                ['name' => 'Lovelock', 'state_id' => 3952],
                ['name' => 'Virginia City', 'state_id' => 3952],
                ['name' => 'Crystal Bay', 'state_id' => 3952],
                ['name' => 'Empire', 'state_id' => 3952],
                ['name' => 'Gerlach', 'state_id' => 3952],
                ['name' => 'Nixon', 'state_id' => 3952],
                ['name' => 'Sparks', 'state_id' => 3952],
                ['name' => 'Sun Valley', 'state_id' => 3952],
                ['name' => 'Verdi', 'state_id' => 3952],
                ['name' => 'Wadsworth', 'state_id' => 3952],
                ['name' => 'Incline Village', 'state_id' => 3952],
                ['name' => 'Reno', 'state_id' => 3952],
                ['name' => 'Washoe Valley', 'state_id' => 3952],
                ['name' => 'Ely', 'state_id' => 3952],
                ['name' => 'Baker', 'state_id' => 3952],
                ['name' => 'Duckwater', 'state_id' => 3952],
                ['name' => 'Lund', 'state_id' => 3952],
                ['name' => 'Mc Gill', 'state_id' => 3952],
                ['name' => 'Ruth', 'state_id' => 3952]
            ]);
        }
    }
}
