<?php

use Illuminate\Database\Seeder;

class state2TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AL - Alabama.
        //If the table 'cities' exists, insert the data to the table.
            DB::table('cities')->insert([
                ['name' => 'Autaugaville', 'state_id' => 3920],
                ['name' => 'Billingsley', 'state_id' => 3920],
                ['name' => 'Booth', 'state_id' => 3920],
                ['name' => 'Marbury', 'state_id' => 3920],
                ['name' => 'Prattville', 'state_id' => 3920],
                ['name' => 'Jones', 'state_id' => 3920],
                ['name' => 'Bay Minette', 'state_id' => 3920],
                ['name' => 'Bon Secour', 'state_id' => 3920],
                ['name' => 'Daphne', 'state_id' => 3920],
                ['name' => 'Spanish Fort', 'state_id' => 3920],
                ['name' => 'Elberta', 'state_id' => 3920],
                ['name' => 'Fairhope', 'state_id' => 3920],
                ['name' => 'Foley', 'state_id' => 3920],
                ['name' => 'Gulf Shores', 'state_id' => 3920],
                ['name' => 'Lillian', 'state_id' => 3920],
                ['name' => 'Little River', 'state_id' => 3920],
                ['name' => 'Loxley', 'state_id' => 3920],
                ['name' => 'Magnolia Springs', 'state_id' => 3920],
                ['name' => 'Montrose', 'state_id' => 3920],
                ['name' => 'Orange Beach', 'state_id' => 3920],
                ['name' => 'Perdido', 'state_id' => 3920],
                ['name' => 'Point Clear', 'state_id' => 3920],
                ['name' => 'Robertsdale', 'state_id' => 3920],
                ['name' => 'Seminole', 'state_id' => 3920],
                ['name' => 'Silverhill', 'state_id' => 3920],
                ['name' => 'Stapleton', 'state_id' => 3920],
                ['name' => 'Stockton', 'state_id' => 3920],
                ['name' => 'Summerdale', 'state_id' => 3920],
                ['name' => 'Clayton', 'state_id' => 3920],
                ['name' => 'Clio', 'state_id' => 3920],
                ['name' => 'Eufaula', 'state_id' => 3920],
                ['name' => 'Louisville', 'state_id' => 3920],
                ['name' => 'Brent', 'state_id' => 3920],
                ['name' => 'Brierfield', 'state_id' => 3920],
                ['name' => 'Centreville', 'state_id' => 3920],
                ['name' => 'Green Pond', 'state_id' => 3920],
                ['name' => 'West Blocton', 'state_id' => 3920],
                ['name' => 'Woodstock', 'state_id' => 3920],
                ['name' => 'Randolph', 'state_id' => 3920],
                ['name' => 'Lawley', 'state_id' => 3920],
                ['name' => 'Allgood', 'state_id' => 3920],
                ['name' => 'Blountsville', 'state_id' => 3920],
                ['name' => 'Cleveland', 'state_id' => 3920],
                ['name' => 'Hayden', 'state_id' => 3920],
                ['name' => 'Locust Fork', 'state_id' => 3920],
                ['name' => 'Oneonta', 'state_id' => 3920],
                ['name' => 'Remlap', 'state_id' => 3920],
                ['name' => 'Fitzpatrick', 'state_id' => 3920],
                ['name' => 'Midway', 'state_id' => 3920],
                ['name' => 'Perote', 'state_id' => 3920],
                ['name' => 'Union Springs', 'state_id' => 3920],
                ['name' => 'Chapman', 'state_id' => 3920],
                ['name' => 'Forest Home', 'state_id' => 3920],
                ['name' => 'Georgiana', 'state_id' => 3920],
                ['name' => 'Greenville', 'state_id' => 3920],
                ['name' => 'Mc Kenzie', 'state_id' => 3920],
                ['name' => 'Anniston', 'state_id' => 3920],
                ['name' => 'Oxford', 'state_id' => 3920],
                ['name' => 'Alexandria', 'state_id' => 3920],
                ['name' => 'Bynum', 'state_id' => 3920],
                ['name' => 'Choccolocco', 'state_id' => 3920],
                ['name' => 'De Armanville', 'state_id' => 3920],
                ['name' => 'Eastaboga', 'state_id' => 3920],
                ['name' => 'Jacksonville', 'state_id' => 3920],
                ['name' => 'Ohatchee', 'state_id' => 3920],
                ['name' => 'Piedmont', 'state_id' => 3920],
                ['name' => 'Weaver', 'state_id' => 3920],
                ['name' => 'Wellington', 'state_id' => 3920],
                ['name' => 'Cusseta', 'state_id' => 3920],
                ['name' => 'Valley', 'state_id' => 3920],
                ['name' => 'Five Points', 'state_id' => 3920],
                ['name' => 'Lafayette', 'state_id' => 3920],
                ['name' => 'Lanett', 'state_id' => 3920],
                ['name' => 'Cedar Bluff', 'state_id' => 3920],
                ['name' => 'Centre', 'state_id' => 3920],
                ['name' => 'Gaylesville', 'state_id' => 3920],
                ['name' => 'Leesburg', 'state_id' => 3920],
                ['name' => 'Spring Garden', 'state_id' => 3920],
                ['name' => 'Clanton', 'state_id' => 3920],
                ['name' => 'Jemison', 'state_id' => 3920],
                ['name' => 'Thorsby', 'state_id' => 3920],
                ['name' => 'Verbena', 'state_id' => 3920],
                ['name' => 'Maplesville', 'state_id' => 3920],
                ['name' => 'Stanton', 'state_id' => 3920],
                ['name' => 'Butler', 'state_id' => 3920],
                ['name' => 'Gilbertown', 'state_id' => 3920],
                ['name' => 'Jachin', 'state_id' => 3920],
                ['name' => 'Lisman', 'state_id' => 3920],
                ['name' => 'Melvin', 'state_id' => 3920],
                ['name' => 'Needham', 'state_id' => 3920],
                ['name' => 'Pennington', 'state_id' => 3920],
                ['name' => 'Silas', 'state_id' => 3920],
                ['name' => 'Toxey', 'state_id' => 3920],
                ['name' => 'Ward', 'state_id' => 3920],
                ['name' => 'Dickinson', 'state_id' => 3920],
                ['name' => 'Fulton', 'state_id' => 3920],
                ['name' => 'Grove Hill', 'state_id' => 3920],
                ['name' => 'Whatley', 'state_id' => 3920],
                ['name' => 'Coffeeville', 'state_id' => 3920],
                ['name' => 'Gainestown', 'state_id' => 3920],
                ['name' => 'Jackson', 'state_id' => 3920],
                ['name' => 'Campbell', 'state_id' => 3920],
                ['name' => 'Thomasville', 'state_id' => 3920],
                ['name' => 'Hollins', 'state_id' => 3920],
                ['name' => 'Ashland', 'state_id' => 3920],
                ['name' => 'Cragford', 'state_id' => 3920],
                ['name' => 'Delta', 'state_id' => 3920],
                ['name' => 'Lineville', 'state_id' => 3920],
                ['name' => 'Millerville', 'state_id' => 3920],
                ['name' => 'Edwardsville', 'state_id' => 3920],
                ['name' => 'Fruithurst', 'state_id' => 3920],
                ['name' => 'Heflin', 'state_id' => 3920],
                ['name' => 'Muscadine', 'state_id' => 3920],
                ['name' => 'Ranburne', 'state_id' => 3920],
                ['name' => 'Elba', 'state_id' => 3920],
                ['name' => 'Enterprise', 'state_id' => 3920],
                ['name' => 'Jack', 'state_id' => 3920],
                ['name' => 'New Brockton', 'state_id' => 3920],
                ['name' => 'Kinston', 'state_id' => 3920],
                ['name' => 'Cherokee', 'state_id' => 3920],
                ['name' => 'Leighton', 'state_id' => 3920],
                ['name' => 'Sheffield', 'state_id' => 3920],
                ['name' => 'Muscle Shoals', 'state_id' => 3920],
                ['name' => 'Tuscumbia', 'state_id' => 3920],
                ['name' => 'Evergreen', 'state_id' => 3920],
                ['name' => 'Brooklyn', 'state_id' => 3920],
                ['name' => 'Castleberry', 'state_id' => 3920],
                ['name' => 'Lenox', 'state_id' => 3920],
                ['name' => 'Range', 'state_id' => 3920],
                ['name' => 'Repton', 'state_id' => 3920],
                ['name' => 'Goodwater', 'state_id' => 3920],
                ['name' => 'Kellyton', 'state_id' => 3920],
                ['name' => 'Rockford', 'state_id' => 3920],
                ['name' => 'Weogufka', 'state_id' => 3920],
                ['name' => 'Equality', 'state_id' => 3920],
                ['name' => 'Gantt', 'state_id' => 3920],
                ['name' => 'Andalusia', 'state_id' => 3920],
                ['name' => 'Florala', 'state_id' => 3920],
                ['name' => 'Lockhart', 'state_id' => 3920],
                ['name' => 'Opp', 'state_id' => 3920],
                ['name' => 'Red Level', 'state_id' => 3920],
                ['name' => 'River Falls', 'state_id' => 3920],
                ['name' => 'Wing', 'state_id' => 3920],
                ['name' => 'Brantley', 'state_id' => 3920],
                ['name' => 'Dozier', 'state_id' => 3920],
                ['name' => 'Glenwood', 'state_id' => 3920],
                ['name' => 'Highland Home', 'state_id' => 3920],
                ['name' => 'Honoraville', 'state_id' => 3920],
                ['name' => 'Luverne', 'state_id' => 3920],
                ['name' => 'Petrey', 'state_id' => 3920],
                ['name' => 'Rutledge', 'state_id' => 3920],
                ['name' => 'Baileyton', 'state_id' => 3920],
                ['name' => 'Bremen', 'state_id' => 3920],
                ['name' => 'Crane Hill', 'state_id' => 3920],
                ['name' => 'Cullman', 'state_id' => 3920],
                ['name' => 'Garden City', 'state_id' => 3920],
                ['name' => 'Hanceville', 'state_id' => 3920],
                ['name' => 'Holly Pond', 'state_id' => 3920],
                ['name' => 'Joppa', 'state_id' => 3920],
                ['name' => 'Logan', 'state_id' => 3920],
                ['name' => 'Vinemont', 'state_id' => 3920],
                ['name' => 'Ariton', 'state_id' => 3920],
                ['name' => 'Clopton', 'state_id' => 3920],
                ['name' => 'Daleville', 'state_id' => 3920],
                ['name' => 'Midland City', 'state_id' => 3920],
                ['name' => 'Newton', 'state_id' => 3920],
                ['name' => 'Ozark', 'state_id' => 3920],
                ['name' => 'Fort Rucker', 'state_id' => 3920],
                ['name' => 'Pinckard', 'state_id' => 3920],
                ['name' => 'Skipperville', 'state_id' => 3920],
                ['name' => 'Selma', 'state_id' => 3920],
                ['name' => 'Plantersville', 'state_id' => 3920],
                ['name' => 'Marion Junction', 'state_id' => 3920],
                ['name' => 'Minter', 'state_id' => 3920],
                ['name' => 'Orrville', 'state_id' => 3920],
                ['name' => 'Safford', 'state_id' => 3920],
                ['name' => 'Sardis', 'state_id' => 3920],
                ['name' => 'Tyler', 'state_id' => 3920],
                ['name' => 'Collinsville', 'state_id' => 3920],
                ['name' => 'Crossville', 'state_id' => 3920],
                ['name' => 'Dawson', 'state_id' => 3920],
                ['name' => 'Fort Payne', 'state_id' => 3920],
                ['name' => 'Fyffe', 'state_id' => 3920],
                ['name' => 'Geraldine', 'state_id' => 3920],
                ['name' => 'Groveoak', 'state_id' => 3920],
                ['name' => 'Henagar', 'state_id' => 3920],
                ['name' => 'Ider', 'state_id' => 3920],
                ['name' => 'Mentone', 'state_id' => 3920],
                ['name' => 'Rainsville', 'state_id' => 3920],
                ['name' => 'Sylvania', 'state_id' => 3920],
                ['name' => 'Valley Head', 'state_id' => 3920],
                ['name' => 'Coosada', 'state_id' => 3920],
                ['name' => 'Deatsville', 'state_id' => 3920],
                ['name' => 'Eclectic', 'state_id' => 3920],
                ['name' => 'Elmore', 'state_id' => 3920],
                ['name' => 'Kent', 'state_id' => 3920],
                ['name' => 'Millbrook', 'state_id' => 3920],
                ['name' => 'Tallassee', 'state_id' => 3920],
                ['name' => 'Titus', 'state_id' => 3920],
                ['name' => 'Wetumpka', 'state_id' => 3920],
                ['name' => 'Brewton', 'state_id' => 3920],
                ['name' => 'Flomaton', 'state_id' => 3920],
                ['name' => 'Atmore', 'state_id' => 3920],
                ['name' => 'Huxford', 'state_id' => 3920],
                ['name' => 'Gadsden', 'state_id' => 3920],
                ['name' => 'Rainbow City', 'state_id' => 3920],
                ['name' => 'Altoona', 'state_id' => 3920],
                ['name' => 'Attalla', 'state_id' => 3920],
                ['name' => 'Gallant', 'state_id' => 3920],
                ['name' => 'Walnut Grove', 'state_id' => 3920],
                ['name' => 'Bankston', 'state_id' => 3920],
                ['name' => 'Belk', 'state_id' => 3920],
                ['name' => 'Berry', 'state_id' => 3920],
                ['name' => 'Fayette', 'state_id' => 3920],
                ['name' => 'Glen Allen', 'state_id' => 3920],
                ['name' => 'Hodges', 'state_id' => 3920],
                ['name' => 'Phil Campbell', 'state_id' => 3920],
                ['name' => 'Red Bay', 'state_id' => 3920],
                ['name' => 'Spruce Pine', 'state_id' => 3920],
                ['name' => 'Vina', 'state_id' => 3920],
                ['name' => 'Russellville', 'state_id' => 3920],
                ['name' => 'Bellwood', 'state_id' => 3920],
                ['name' => 'Black', 'state_id' => 3920],
                ['name' => 'Chancellor', 'state_id' => 3920],
                ['name' => 'Coffee Springs', 'state_id' => 3920],
                ['name' => 'Geneva', 'state_id' => 3920],
                ['name' => 'Hartford', 'state_id' => 3920],
                ['name' => 'Malvern', 'state_id' => 3920],
                ['name' => 'Slocomb', 'state_id' => 3920],
                ['name' => 'Samson', 'state_id' => 3920],
                ['name' => 'Boligee', 'state_id' => 3920],
                ['name' => 'Clinton', 'state_id' => 3920],
                ['name' => 'Eutaw', 'state_id' => 3920],
                ['name' => 'Knoxville', 'state_id' => 3920],
                ['name' => 'West Greene', 'state_id' => 3920],
                ['name' => 'Forkland', 'state_id' => 3920],
                ['name' => 'Akron', 'state_id' => 3920],
                ['name' => 'Moundville', 'state_id' => 3920],
                ['name' => 'Gallion', 'state_id' => 3920],
                ['name' => 'Greensboro', 'state_id' => 3920],
                ['name' => 'Newbern', 'state_id' => 3920],
                ['name' => 'Sawyerville', 'state_id' => 3920],
                ['name' => 'Abbeville', 'state_id' => 3920],
                ['name' => 'Headland', 'state_id' => 3920],
                ['name' => 'Newville', 'state_id' => 3920],
                ['name' => 'Shorterville', 'state_id' => 3920],
                ['name' => 'Dothan', 'state_id' => 3920],
                ['name' => 'Ashford', 'state_id' => 3920],
                ['name' => 'Columbia', 'state_id' => 3920],
                ['name' => 'Cottonwood', 'state_id' => 3920],
                ['name' => 'Cowarts', 'state_id' => 3920],
                ['name' => 'Gordon', 'state_id' => 3920],
                ['name' => 'Pansey', 'state_id' => 3920],
                ['name' => 'Webb', 'state_id' => 3920],
                ['name' => 'Bridgeport', 'state_id' => 3920],
                ['name' => 'Dutton', 'state_id' => 3920],
                ['name' => 'Estillfork', 'state_id' => 3920],
                ['name' => 'Fackler', 'state_id' => 3920],
                ['name' => 'Hollytree', 'state_id' => 3920],
                ['name' => 'Hollywood', 'state_id' => 3920],
                ['name' => 'Langston', 'state_id' => 3920],
                ['name' => 'Paint Rock', 'state_id' => 3920],
                ['name' => 'Pisgah', 'state_id' => 3920],
                ['name' => 'Princeton', 'state_id' => 3920],
                ['name' => 'Scottsboro', 'state_id' => 3920],
                ['name' => 'Section', 'state_id' => 3920],
                ['name' => 'Stevenson', 'state_id' => 3920],
                ['name' => 'Trenton', 'state_id' => 3920],
                ['name' => 'Woodville', 'state_id' => 3920],
                ['name' => 'Bryant', 'state_id' => 3920],
                ['name' => 'Flat Rock', 'state_id' => 3920],
                ['name' => 'Higdon', 'state_id' => 3920],
                ['name' => 'Adamsville', 'state_id' => 3920],
                ['name' => 'Adger', 'state_id' => 3920],
                ['name' => 'Alton', 'state_id' => 3920],
                ['name' => 'Bessemer', 'state_id' => 3920],
                ['name' => 'Brookside', 'state_id' => 3920],
                ['name' => 'Clay', 'state_id' => 3920],
                ['name' => 'Docena', 'state_id' => 3920],
                ['name' => 'Dolomite', 'state_id' => 3920],
                ['name' => 'Fairfield', 'state_id' => 3920],
                ['name' => 'Fultondale', 'state_id' => 3920],
                ['name' => 'Gardendale', 'state_id' => 3920],
                ['name' => 'Graysville', 'state_id' => 3920],
                ['name' => 'Kimberly', 'state_id' => 3920],
                ['name' => 'Leeds', 'state_id' => 3920],
                ['name' => 'Mc Calla', 'state_id' => 3920],
                ['name' => 'Morris', 'state_id' => 3920],
                ['name' => 'Mount Olive', 'state_id' => 3920],
                ['name' => 'Mulga', 'state_id' => 3920],
                ['name' => 'New Castle', 'state_id' => 3920],
                ['name' => 'Palmerdale', 'state_id' => 3920],
                ['name' => 'Pinson', 'state_id' => 3920],
                ['name' => 'Pleasant Grove', 'state_id' => 3920],
                ['name' => 'Sayre', 'state_id' => 3920],
                ['name' => 'Shannon', 'state_id' => 3920],
                ['name' => 'Trafford', 'state_id' => 3920],
                ['name' => 'Trussville', 'state_id' => 3920],
                ['name' => 'Warrior', 'state_id' => 3920],
                ['name' => 'Watson', 'state_id' => 3920],
                ['name' => 'Birmingham', 'state_id' => 3920],
                ['name' => 'Beaverton', 'state_id' => 3920],
                ['name' => 'Detroit', 'state_id' => 3920],
                ['name' => 'Kennedy', 'state_id' => 3920],
                ['name' => 'Millport', 'state_id' => 3920],
                ['name' => 'Sulligent', 'state_id' => 3920],
                ['name' => 'Vernon', 'state_id' => 3920],
                ['name' => 'Anderson', 'state_id' => 3920],
                ['name' => 'Cloverdale', 'state_id' => 3920],
                ['name' => 'Florence', 'state_id' => 3920],
                ['name' => 'Killen', 'state_id' => 3920],
                ['name' => 'Lexington', 'state_id' => 3920],
                ['name' => 'Rogersville', 'state_id' => 3920],
                ['name' => 'Waterloo', 'state_id' => 3920],
                ['name' => 'Courtland', 'state_id' => 3920],
                ['name' => 'Hillsboro', 'state_id' => 3920],
                ['name' => 'Moulton', 'state_id' => 3920],
                ['name' => 'Mount Hope', 'state_id' => 3920],
                ['name' => 'Town Creek', 'state_id' => 3920],
                ['name' => 'Opelika', 'state_id' => 3920],
                ['name' => 'Auburn', 'state_id' => 3920],
                ['name' => 'Auburn University', 'state_id' => 3920],
                ['name' => 'Loachapoka', 'state_id' => 3920],
                ['name' => 'Salem', 'state_id' => 3920],
                ['name' => 'Smiths Station', 'state_id' => 3920],
                ['name' => 'Waverly', 'state_id' => 3920],
                ['name' => 'Athens', 'state_id' => 3920],
                ['name' => 'Belle Mina', 'state_id' => 3920],
                ['name' => 'Elkmont', 'state_id' => 3920],
                ['name' => 'Lester', 'state_id' => 3920],
                ['name' => 'Mooresville', 'state_id' => 3920],
                ['name' => 'Tanner', 'state_id' => 3920],
                ['name' => 'Ardmore', 'state_id' => 3920],
                ['name' => 'Capshaw', 'state_id' => 3920],
                ['name' => 'Fort Deposit', 'state_id' => 3920],
                ['name' => 'Hayneville', 'state_id' => 3920],
                ['name' => 'Letohatchee', 'state_id' => 3920],
                ['name' => 'Lowndesboro', 'state_id' => 3920],
                ['name' => 'Fort Davis', 'state_id' => 3920],
                ['name' => 'Hardaway', 'state_id' => 3920],
                ['name' => 'Shorter', 'state_id' => 3920],
                ['name' => 'Tuskegee', 'state_id' => 3920],
                ['name' => 'Tuskegee Institute', 'state_id' => 3920],
                ['name' => 'Notasulga', 'state_id' => 3920],
                ['name' => 'Brownsboro', 'state_id' => 3920],
                ['name' => 'Gurley', 'state_id' => 3920],
                ['name' => 'Harvest', 'state_id' => 3920],
                ['name' => 'Hazel Green', 'state_id' => 3920],
                ['name' => 'Madison', 'state_id' => 3920],
                ['name' => 'Meridianville', 'state_id' => 3920],
                ['name' => 'New Hope', 'state_id' => 3920],
                ['name' => 'New Market', 'state_id' => 3920],
                ['name' => 'Normal', 'state_id' => 3920],
                ['name' => 'Owens Cross Roads', 'state_id' => 3920],
                ['name' => 'Ryland', 'state_id' => 3920],
                ['name' => 'Toney', 'state_id' => 3920],
                ['name' => 'Huntsville', 'state_id' => 3920],
                ['name' => 'Demopolis', 'state_id' => 3920],
                ['name' => 'Dixons Mills', 'state_id' => 3920],
                ['name' => 'Faunsdale', 'state_id' => 3920],
                ['name' => 'Jefferson', 'state_id' => 3920],
                ['name' => 'Linden', 'state_id' => 3920],
                ['name' => 'Magnolia', 'state_id' => 3920],
                ['name' => 'Myrtlewood', 'state_id' => 3920],
                ['name' => 'Nanafalia', 'state_id' => 3920],
                ['name' => 'Sweet Water', 'state_id' => 3920],
                ['name' => 'Thomaston', 'state_id' => 3920],
                ['name' => 'Bear Creek', 'state_id' => 3920],
                ['name' => 'Brilliant', 'state_id' => 3920],
                ['name' => 'Guin', 'state_id' => 3920],
                ['name' => 'Hackleburg', 'state_id' => 3920],
                ['name' => 'Hamilton', 'state_id' => 3920],
                ['name' => 'Winfield', 'state_id' => 3920],
                ['name' => 'Arab', 'state_id' => 3920],
                ['name' => 'Union Grove', 'state_id' => 3920],
                ['name' => 'Grant', 'state_id' => 3920],
                ['name' => 'Albertville', 'state_id' => 3920],
                ['name' => 'Boaz', 'state_id' => 3920],
                ['name' => 'Douglas', 'state_id' => 3920],
                ['name' => 'Guntersville', 'state_id' => 3920],
                ['name' => 'Horton', 'state_id' => 3920],
                ['name' => 'Axis', 'state_id' => 3920],
                ['name' => 'Bayou La Batre', 'state_id' => 3920],
                ['name' => 'Bucks', 'state_id' => 3920],
                ['name' => 'Chunchula', 'state_id' => 3920],
                ['name' => 'Citronelle', 'state_id' => 3920],
                ['name' => 'Coden', 'state_id' => 3920],
                ['name' => 'Creola', 'state_id' => 3920],
                ['name' => 'Dauphin Island', 'state_id' => 3920],
                ['name' => 'Grand Bay', 'state_id' => 3920],
                ['name' => 'Irvington', 'state_id' => 3920],
                ['name' => 'Mount Vernon', 'state_id' => 3920],
                ['name' => 'Saint Elmo', 'state_id' => 3920],
                ['name' => 'Saraland', 'state_id' => 3920],
                ['name' => 'Satsuma', 'state_id' => 3920],
                ['name' => 'Semmes', 'state_id' => 3920],
                ['name' => 'Theodore', 'state_id' => 3920],
                ['name' => 'Wilmer', 'state_id' => 3920],
                ['name' => 'Mobile', 'state_id' => 3920],
                ['name' => 'Eight Mile', 'state_id' => 3920],
                ['name' => 'Beatrice', 'state_id' => 3920],
                ['name' => 'Excel', 'state_id' => 3920],
                ['name' => 'Franklin', 'state_id' => 3920],
                ['name' => 'Frisco City', 'state_id' => 3920],
                ['name' => 'Goodway', 'state_id' => 3920],
                ['name' => 'Megargel', 'state_id' => 3920],
                ['name' => 'Mexia', 'state_id' => 3920],
                ['name' => 'Monroeville', 'state_id' => 3920],
                ['name' => 'Perdue Hill', 'state_id' => 3920],
                ['name' => 'Peterman', 'state_id' => 3920],
                ['name' => 'Uriah', 'state_id' => 3920],
                ['name' => 'Vredenburgh', 'state_id' => 3920],
                ['name' => 'Cecil', 'state_id' => 3920],
                ['name' => 'Grady', 'state_id' => 3920],
                ['name' => 'Hope Hull', 'state_id' => 3920],
                ['name' => 'Lapine', 'state_id' => 3920],
                ['name' => 'Mathews', 'state_id' => 3920],
                ['name' => 'Mount Meigs', 'state_id' => 3920],
                ['name' => 'Pike Road', 'state_id' => 3920],
                ['name' => 'Pine Level', 'state_id' => 3920],
                ['name' => 'Ramer', 'state_id' => 3920],
                ['name' => 'Montgomery', 'state_id' => 3920],
                ['name' => 'Decatur', 'state_id' => 3920],
                ['name' => 'Danville', 'state_id' => 3920],
                ['name' => 'Eva', 'state_id' => 3920],
                ['name' => 'Falkville', 'state_id' => 3920],
                ['name' => 'Hartselle', 'state_id' => 3920],
                ['name' => 'Somerville', 'state_id' => 3920],
                ['name' => 'Trinity', 'state_id' => 3920],
                ['name' => 'Laceys Spring', 'state_id' => 3920],
                ['name' => 'Valhermoso Springs', 'state_id' => 3920],
                ['name' => 'Marion', 'state_id' => 3920],
                ['name' => 'Uniontown', 'state_id' => 3920],
                ['name' => 'Aliceville', 'state_id' => 3920],
                ['name' => 'Carrollton', 'state_id' => 3920],
                ['name' => 'Ethelsville', 'state_id' => 3920],
                ['name' => 'Gordo', 'state_id' => 3920],
                ['name' => 'Mc Shan', 'state_id' => 3920],
                ['name' => 'Reform', 'state_id' => 3920],
                ['name' => 'Banks', 'state_id' => 3920],
                ['name' => 'Brundidge', 'state_id' => 3920],
                ['name' => 'Goshen', 'state_id' => 3920],
                ['name' => 'Troy', 'state_id' => 3920],
                ['name' => 'Graham', 'state_id' => 3920],
                ['name' => 'Roanoke', 'state_id' => 3920],
                ['name' => 'Wadley', 'state_id' => 3920],
                ['name' => 'Wedowee', 'state_id' => 3920],
                ['name' => 'Woodland', 'state_id' => 3920],
                ['name' => 'Cottonton', 'state_id' => 3920],
                ['name' => 'Fort Mitchell', 'state_id' => 3920],
                ['name' => 'Hatchechubbee', 'state_id' => 3920],
                ['name' => 'Holy Trinity', 'state_id' => 3920],
                ['name' => 'Hurtsboro', 'state_id' => 3920],
                ['name' => 'Phenix City', 'state_id' => 3920],
                ['name' => 'Pittsview', 'state_id' => 3920],
                ['name' => 'Seale', 'state_id' => 3920],
                ['name' => 'Moody', 'state_id' => 3920],
                ['name' => 'Cook Springs', 'state_id' => 3920],
                ['name' => 'Cropwell', 'state_id' => 3920],
                ['name' => 'Margaret', 'state_id' => 3920],
                ['name' => 'Odenville', 'state_id' => 3920],
                ['name' => 'Pell City', 'state_id' => 3920],
                ['name' => 'Ragland', 'state_id' => 3920],
                ['name' => 'Riverside', 'state_id' => 3920],
                ['name' => 'Springville', 'state_id' => 3920],
                ['name' => 'Wattsville', 'state_id' => 3920],
                ['name' => 'Ashville', 'state_id' => 3920],
                ['name' => 'Steele', 'state_id' => 3920],
                ['name' => 'Alabaster', 'state_id' => 3920],
                ['name' => 'Calera', 'state_id' => 3920],
                ['name' => 'Chelsea', 'state_id' => 3920],
                ['name' => 'Columbiana', 'state_id' => 3920],
                ['name' => 'Harpersville', 'state_id' => 3920],
                ['name' => 'Helena', 'state_id' => 3920],
                ['name' => 'Maylene', 'state_id' => 3920],
                ['name' => 'Montevallo', 'state_id' => 3920],
                ['name' => 'Pelham', 'state_id' => 3920],
                ['name' => 'Saginaw', 'state_id' => 3920],
                ['name' => 'Shelby', 'state_id' => 3920],
                ['name' => 'Siluria', 'state_id' => 3920],
                ['name' => 'Sterrett', 'state_id' => 3920],
                ['name' => 'Vandiver', 'state_id' => 3920],
                ['name' => 'Vincent', 'state_id' => 3920],
                ['name' => 'Westover', 'state_id' => 3920],
                ['name' => 'Wilsonville', 'state_id' => 3920],
                ['name' => 'Wilton', 'state_id' => 3920],
                ['name' => 'Emelle', 'state_id' => 3920],
                ['name' => 'Epes', 'state_id' => 3920],
                ['name' => 'Gainesville', 'state_id' => 3920],
                ['name' => 'Livingston', 'state_id' => 3920],
                ['name' => 'Panola', 'state_id' => 3920],
                ['name' => 'Bellamy', 'state_id' => 3920],
                ['name' => 'Cuba', 'state_id' => 3920],
                ['name' => 'York', 'state_id' => 3920],
                ['name' => 'Alpine', 'state_id' => 3920],
                ['name' => 'Bon Air', 'state_id' => 3920],
                ['name' => 'Childersburg', 'state_id' => 3920],
                ['name' => 'Lincoln', 'state_id' => 3920],
                ['name' => 'Sycamore', 'state_id' => 3920],
                ['name' => 'Sylacauga', 'state_id' => 3920],
                ['name' => 'Talladega', 'state_id' => 3920],
                ['name' => 'Munford', 'state_id' => 3920],
                ['name' => 'Alexander City', 'state_id' => 3920],
                ['name' => 'East Tallassee', 'state_id' => 3920],
                ['name' => 'Daviston', 'state_id' => 3920],
                ['name' => 'Camp Hill', 'state_id' => 3920],
                ['name' => 'Dadeville', 'state_id' => 3920],
                ['name' => 'Jacksons Gap', 'state_id' => 3920],
                ['name' => 'Tuscaloosa', 'state_id' => 3920],
                ['name' => 'Abernant', 'state_id' => 3920],
                ['name' => 'Brookwood', 'state_id' => 3920],
                ['name' => 'Buhl', 'state_id' => 3920],
                ['name' => 'Coaling', 'state_id' => 3920],
                ['name' => 'Coker', 'state_id' => 3920],
                ['name' => 'Cottondale', 'state_id' => 3920],
                ['name' => 'Duncanville', 'state_id' => 3920],
                ['name' => 'Echola', 'state_id' => 3920],
                ['name' => 'Elrod', 'state_id' => 3920],
                ['name' => 'Fosters', 'state_id' => 3920],
                ['name' => 'Kellerman', 'state_id' => 3920],
                ['name' => 'Northport', 'state_id' => 3920],
                ['name' => 'Peterson', 'state_id' => 3920],
                ['name' => 'Ralph', 'state_id' => 3920],
                ['name' => 'Samantha', 'state_id' => 3920],
                ['name' => 'Vance', 'state_id' => 3920],
                ['name' => 'Burnwell', 'state_id' => 3920],
                ['name' => 'Dora', 'state_id' => 3920],
                ['name' => 'Empire', 'state_id' => 3920],
                ['name' => 'Quinton', 'state_id' => 3920],
                ['name' => 'Sumiton', 'state_id' => 3920],
                ['name' => 'Jasper', 'state_id' => 3920],
                ['name' => 'Carbon Hill', 'state_id' => 3920],
                ['name' => 'Cordova', 'state_id' => 3920],
                ['name' => 'Eldridge', 'state_id' => 3920],
                ['name' => 'Goodsprings', 'state_id' => 3920],
                ['name' => 'Kansas', 'state_id' => 3920],
                ['name' => 'Nauvoo', 'state_id' => 3920],
                ['name' => 'Oakman', 'state_id' => 3920],
                ['name' => 'Parrish', 'state_id' => 3920],
                ['name' => 'Sipsey', 'state_id' => 3920],
                ['name' => 'Townley', 'state_id' => 3920],
                ['name' => 'Calvert', 'state_id' => 3920],
                ['name' => 'Chatom', 'state_id' => 3920],
                ['name' => 'Deer Park', 'state_id' => 3920],
                ['name' => 'Frankville', 'state_id' => 3920],
                ['name' => 'Fruitdale', 'state_id' => 3920],
                ['name' => 'Leroy', 'state_id' => 3920],
                ['name' => 'Mc Intosh', 'state_id' => 3920],
                ['name' => 'Malcolm', 'state_id' => 3920],
                ['name' => 'Millry', 'state_id' => 3920],
                ['name' => 'Saint Stephens', 'state_id' => 3920],
                ['name' => 'Sunflower', 'state_id' => 3920],
                ['name' => 'Tibbie', 'state_id' => 3920],
                ['name' => 'Vinegar Bend', 'state_id' => 3920],
                ['name' => 'Wagarville', 'state_id' => 3920],
                ['name' => 'Coy', 'state_id' => 3920],
                ['name' => 'Alberta', 'state_id' => 3920],
                ['name' => 'Arlington', 'state_id' => 3920],
                ['name' => 'Boykin', 'state_id' => 3920],
                ['name' => 'Camden', 'state_id' => 3920],
                ['name' => 'Catherine', 'state_id' => 3920],
                ['name' => 'Furman', 'state_id' => 3920],
                ['name' => 'Lower Peach Tree', 'state_id' => 3920],
                ['name' => 'Mc Williams', 'state_id' => 3920],
                ['name' => 'Oak Hill', 'state_id' => 3920],
                ['name' => 'Pine Apple', 'state_id' => 3920],
                ['name' => 'Pine Hill', 'state_id' => 3920],
                ['name' => 'Addison', 'state_id' => 3920],
                ['name' => 'Arley', 'state_id' => 3920],
                ['name' => 'Delmar', 'state_id' => 3920],
                ['name' => 'Double Springs', 'state_id' => 3920],
                ['name' => 'Haleyville', 'state_id' => 3920],
                ['name' => 'Houston', 'state_id' => 3920],
                ['name' => 'Lynn', 'state_id' => 3920],
                ['name' => 'Natural Bridge', 'state_id' => 3920]
            ]);
    }
}
