<?php

use Illuminate\Database\Seeder;

class state43TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of TN - Tennessee.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Andersonville', 'state_id' => 3970],
                ['name' => 'Briceville', 'state_id' => 3970],
                ['name' => 'Clinton', 'state_id' => 3970],
                ['name' => 'Lake City', 'state_id' => 3970],
                ['name' => 'Norris', 'state_id' => 3970],
                ['name' => 'Oak Ridge', 'state_id' => 3970],
                ['name' => 'Bell Buckle', 'state_id' => 3970],
                ['name' => 'Shelbyville', 'state_id' => 3970],
                ['name' => 'Unionville', 'state_id' => 3970],
                ['name' => 'Wartrace', 'state_id' => 3970],
                ['name' => 'Normandy', 'state_id' => 3970],
                ['name' => 'Big Sandy', 'state_id' => 3970],
                ['name' => 'Camden', 'state_id' => 3970],
                ['name' => 'Eva', 'state_id' => 3970],
                ['name' => 'Holladay', 'state_id' => 3970],
                ['name' => 'Pikeville', 'state_id' => 3970],
                ['name' => 'Alcoa', 'state_id' => 3970],
                ['name' => 'Friendsville', 'state_id' => 3970],
                ['name' => 'Louisville', 'state_id' => 3970],
                ['name' => 'Maryville', 'state_id' => 3970],
                ['name' => 'Rockford', 'state_id' => 3970],
                ['name' => 'Tallassee', 'state_id' => 3970],
                ['name' => 'Townsend', 'state_id' => 3970],
                ['name' => 'Walland', 'state_id' => 3970],
                ['name' => 'Charleston', 'state_id' => 3970],
                ['name' => 'Cleveland', 'state_id' => 3970],
                ['name' => 'Mc Donald', 'state_id' => 3970],
                ['name' => 'Caryville', 'state_id' => 3970],
                ['name' => 'Duff', 'state_id' => 3970],
                ['name' => 'Jacksboro', 'state_id' => 3970],
                ['name' => 'Jellico', 'state_id' => 3970],
                ['name' => 'La Follette', 'state_id' => 3970],
                ['name' => 'Newcomb', 'state_id' => 3970],
                ['name' => 'Pioneer', 'state_id' => 3970],
                ['name' => 'Auburntown', 'state_id' => 3970],
                ['name' => 'Bradyville', 'state_id' => 3970],
                ['name' => 'Readyville', 'state_id' => 3970],
                ['name' => 'Woodbury', 'state_id' => 3970],
                ['name' => 'Mc Kenzie', 'state_id' => 3970],
                ['name' => 'Atwood', 'state_id' => 3970],
                ['name' => 'Mc Lemoresville', 'state_id' => 3970],
                ['name' => 'Trezevant', 'state_id' => 3970],
                ['name' => 'Bruceton', 'state_id' => 3970],
                ['name' => 'Buena Vista', 'state_id' => 3970],
                ['name' => 'Cedar Grove', 'state_id' => 3970],
                ['name' => 'Clarksburg', 'state_id' => 3970],
                ['name' => 'Hollow Rock', 'state_id' => 3970],
                ['name' => 'Huntingdon', 'state_id' => 3970],
                ['name' => 'Lavinia', 'state_id' => 3970],
                ['name' => 'Westport', 'state_id' => 3970],
                ['name' => 'Yuma', 'state_id' => 3970],
                ['name' => 'Elizabethton', 'state_id' => 3970],
                ['name' => 'Hampton', 'state_id' => 3970],
                ['name' => 'Milligan College', 'state_id' => 3970],
                ['name' => 'Roan Mountain', 'state_id' => 3970],
                ['name' => 'Watauga', 'state_id' => 3970],
                ['name' => 'Ashland City', 'state_id' => 3970],
                ['name' => 'Chapmansboro', 'state_id' => 3970],
                ['name' => 'Kingston Springs', 'state_id' => 3970],
                ['name' => 'Pegram', 'state_id' => 3970],
                ['name' => 'Pleasant View', 'state_id' => 3970],
                ['name' => 'Enville', 'state_id' => 3970],
                ['name' => 'Henderson', 'state_id' => 3970],
                ['name' => 'Jacks Creek', 'state_id' => 3970],
                ['name' => 'Luray', 'state_id' => 3970],
                ['name' => 'Arthur', 'state_id' => 3970],
                ['name' => 'Clairfield', 'state_id' => 3970],
                ['name' => 'Cumberland Gap', 'state_id' => 3970],
                ['name' => 'Eagan', 'state_id' => 3970],
                ['name' => 'Harrogate', 'state_id' => 3970],
                ['name' => 'Lone Mountain', 'state_id' => 3970],
                ['name' => 'New Tazewell', 'state_id' => 3970],
                ['name' => 'Pruden', 'state_id' => 3970],
                ['name' => 'Shawanee', 'state_id' => 3970],
                ['name' => 'Speedwell', 'state_id' => 3970],
                ['name' => 'Tazewell', 'state_id' => 3970],
                ['name' => 'Celina', 'state_id' => 3970],
                ['name' => 'Moss', 'state_id' => 3970],
                ['name' => 'Bybee', 'state_id' => 3970],
                ['name' => 'Cosby', 'state_id' => 3970],
                ['name' => 'Del Rio', 'state_id' => 3970],
                ['name' => 'Hartford', 'state_id' => 3970],
                ['name' => 'Newport', 'state_id' => 3970],
                ['name' => 'Parrottsville', 'state_id' => 3970],
                ['name' => 'Beechgrove', 'state_id' => 3970],
                ['name' => 'Hillsboro', 'state_id' => 3970],
                ['name' => 'Manchester', 'state_id' => 3970],
                ['name' => 'Summitville', 'state_id' => 3970],
                ['name' => 'Tullahoma', 'state_id' => 3970],
                ['name' => 'Arnold Afb', 'state_id' => 3970],
                ['name' => 'Alamo', 'state_id' => 3970],
                ['name' => 'Bells', 'state_id' => 3970],
                ['name' => 'Crockett Mills', 'state_id' => 3970],
                ['name' => 'Friendship', 'state_id' => 3970],
                ['name' => 'Maury City', 'state_id' => 3970],
                ['name' => 'Fruitvale', 'state_id' => 3970],
                ['name' => 'Gadsden', 'state_id' => 3970],
                ['name' => 'Crab Orchard', 'state_id' => 3970],
                ['name' => 'Crossville', 'state_id' => 3970],
                ['name' => 'Pleasant Hill', 'state_id' => 3970],
                ['name' => 'Antioch', 'state_id' => 3970],
                ['name' => 'Goodlettsville', 'state_id' => 3970],
                ['name' => 'Hermitage', 'state_id' => 3970],
                ['name' => 'Joelton', 'state_id' => 3970],
                ['name' => 'Madison', 'state_id' => 3970],
                ['name' => 'Old Hickory', 'state_id' => 3970],
                ['name' => 'Whites Creek', 'state_id' => 3970],
                ['name' => 'Nashville', 'state_id' => 3970],
                ['name' => 'Bath Springs', 'state_id' => 3970],
                ['name' => 'Decaturville', 'state_id' => 3970],
                ['name' => 'Parsons', 'state_id' => 3970],
                ['name' => 'Scotts Hill', 'state_id' => 3970],
                ['name' => 'Sugar Tree', 'state_id' => 3970],
                ['name' => 'Alexandria', 'state_id' => 3970],
                ['name' => 'Dowelltown', 'state_id' => 3970],
                ['name' => 'Liberty', 'state_id' => 3970],
                ['name' => 'Smithville', 'state_id' => 3970],
                ['name' => 'Burns', 'state_id' => 3970],
                ['name' => 'Charlotte', 'state_id' => 3970],
                ['name' => 'Cumberland Furnace', 'state_id' => 3970],
                ['name' => 'Dickson', 'state_id' => 3970],
                ['name' => 'Slayden', 'state_id' => 3970],
                ['name' => 'Vanleer', 'state_id' => 3970],
                ['name' => 'White Bluff', 'state_id' => 3970],
                ['name' => 'Bogota', 'state_id' => 3970],
                ['name' => 'Dyersburg', 'state_id' => 3970],
                ['name' => 'Finley', 'state_id' => 3970],
                ['name' => 'Lenox', 'state_id' => 3970],
                ['name' => 'Newbern', 'state_id' => 3970],
                ['name' => 'Tigrett', 'state_id' => 3970],
                ['name' => 'Trimble', 'state_id' => 3970],
                ['name' => 'Braden', 'state_id' => 3970],
                ['name' => 'Gallaway', 'state_id' => 3970],
                ['name' => 'Laconia', 'state_id' => 3970],
                ['name' => 'La Grange', 'state_id' => 3970],
                ['name' => 'Macon', 'state_id' => 3970],
                ['name' => 'Moscow', 'state_id' => 3970],
                ['name' => 'Oakland', 'state_id' => 3970],
                ['name' => 'Rossville', 'state_id' => 3970],
                ['name' => 'Somerville', 'state_id' => 3970],
                ['name' => 'Williston', 'state_id' => 3970],
                ['name' => 'Allardt', 'state_id' => 3970],
                ['name' => 'Clarkrange', 'state_id' => 3970],
                ['name' => 'Jamestown', 'state_id' => 3970],
                ['name' => 'Grimsley', 'state_id' => 3970],
                ['name' => 'Pall Mall', 'state_id' => 3970],
                ['name' => 'Wilder', 'state_id' => 3970],
                ['name' => 'Belvidere', 'state_id' => 3970],
                ['name' => 'Cowan', 'state_id' => 3970],
                ['name' => 'Decherd', 'state_id' => 3970],
                ['name' => 'Estill Springs', 'state_id' => 3970],
                ['name' => 'Huntland', 'state_id' => 3970],
                ['name' => 'Sewanee', 'state_id' => 3970],
                ['name' => 'Sherwood', 'state_id' => 3970],
                ['name' => 'Winchester', 'state_id' => 3970],
                ['name' => 'Kenton', 'state_id' => 3970],
                ['name' => 'Bradford', 'state_id' => 3970],
                ['name' => 'Dyer', 'state_id' => 3970],
                ['name' => 'Eaton', 'state_id' => 3970],
                ['name' => 'Gibson', 'state_id' => 3970],
                ['name' => 'Humboldt', 'state_id' => 3970],
                ['name' => 'Idlewild', 'state_id' => 3970],
                ['name' => 'Medina', 'state_id' => 3970],
                ['name' => 'Milan', 'state_id' => 3970],
                ['name' => 'Rutherford', 'state_id' => 3970],
                ['name' => 'Trenton', 'state_id' => 3970],
                ['name' => 'Yorkville', 'state_id' => 3970],
                ['name' => 'Ardmore', 'state_id' => 3970],
                ['name' => 'Elkton', 'state_id' => 3970],
                ['name' => 'Frankewing', 'state_id' => 3970],
                ['name' => 'Goodspring', 'state_id' => 3970],
                ['name' => 'Lynnville', 'state_id' => 3970],
                ['name' => 'Minor Hill', 'state_id' => 3970],
                ['name' => 'Prospect', 'state_id' => 3970],
                ['name' => 'Pulaski', 'state_id' => 3970],
                ['name' => 'Bean Station', 'state_id' => 3970],
                ['name' => 'Blaine', 'state_id' => 3970],
                ['name' => 'Powder Springs', 'state_id' => 3970],
                ['name' => 'Rutledge', 'state_id' => 3970],
                ['name' => 'Thorn Hill', 'state_id' => 3970],
                ['name' => 'Washburn', 'state_id' => 3970],
                ['name' => 'Afton', 'state_id' => 3970],
                ['name' => 'Chuckey', 'state_id' => 3970],
                ['name' => 'Greeneville', 'state_id' => 3970],
                ['name' => 'Midway', 'state_id' => 3970],
                ['name' => 'Mohawk', 'state_id' => 3970],
                ['name' => 'Mosheim', 'state_id' => 3970],
                ['name' => 'Altamont', 'state_id' => 3970],
                ['name' => 'Beersheba Springs', 'state_id' => 3970],
                ['name' => 'Coalmont', 'state_id' => 3970],
                ['name' => 'Gruetli Laager', 'state_id' => 3970],
                ['name' => 'Monteagle', 'state_id' => 3970],
                ['name' => 'Palmer', 'state_id' => 3970],
                ['name' => 'Pelham', 'state_id' => 3970],
                ['name' => 'Tracy City', 'state_id' => 3970],
                ['name' => 'Lowland', 'state_id' => 3970],
                ['name' => 'Morristown', 'state_id' => 3970],
                ['name' => 'Russellville', 'state_id' => 3970],
                ['name' => 'Talbott', 'state_id' => 3970],
                ['name' => 'Whitesburg', 'state_id' => 3970],
                ['name' => 'Apison', 'state_id' => 3970],
                ['name' => 'Bakewell', 'state_id' => 3970],
                ['name' => 'Birchwood', 'state_id' => 3970],
                ['name' => 'Collegedale', 'state_id' => 3970],
                ['name' => 'Harrison', 'state_id' => 3970],
                ['name' => 'Hixson', 'state_id' => 3970],
                ['name' => 'Lookout Mountain', 'state_id' => 3970],
                ['name' => 'Lupton City', 'state_id' => 3970],
                ['name' => 'Ooltewah', 'state_id' => 3970],
                ['name' => 'Sale Creek', 'state_id' => 3970],
                ['name' => 'Signal Mountain', 'state_id' => 3970],
                ['name' => 'Soddy Daisy', 'state_id' => 3970],
                ['name' => 'Chattanooga', 'state_id' => 3970],
                ['name' => 'Kyles Ford', 'state_id' => 3970],
                ['name' => 'Sneedville', 'state_id' => 3970],
                ['name' => 'Bolivar', 'state_id' => 3970],
                ['name' => 'Grand Junction', 'state_id' => 3970],
                ['name' => 'Hickory Valley', 'state_id' => 3970],
                ['name' => 'Hornsby', 'state_id' => 3970],
                ['name' => 'Middleton', 'state_id' => 3970],
                ['name' => 'Pocahontas', 'state_id' => 3970],
                ['name' => 'Saulsbury', 'state_id' => 3970],
                ['name' => 'Whiteville', 'state_id' => 3970],
                ['name' => 'Silerton', 'state_id' => 3970],
                ['name' => 'Toone', 'state_id' => 3970],
                ['name' => 'Counce', 'state_id' => 3970],
                ['name' => 'Crump', 'state_id' => 3970],
                ['name' => 'Morris Chapel', 'state_id' => 3970],
                ['name' => 'Pickwick Dam', 'state_id' => 3970],
                ['name' => 'Saltillo', 'state_id' => 3970],
                ['name' => 'Savannah', 'state_id' => 3970],
                ['name' => 'Shiloh', 'state_id' => 3970],
                ['name' => 'Olivehill', 'state_id' => 3970],
                ['name' => 'Church Hill', 'state_id' => 3970],
                ['name' => 'Mount Carmel', 'state_id' => 3970],
                ['name' => 'Bulls Gap', 'state_id' => 3970],
                ['name' => 'Eidson', 'state_id' => 3970],
                ['name' => 'Mooresburg', 'state_id' => 3970],
                ['name' => 'Rogersville', 'state_id' => 3970],
                ['name' => 'Surgoinsville', 'state_id' => 3970],
                ['name' => 'Brownsville', 'state_id' => 3970],
                ['name' => 'Stanton', 'state_id' => 3970],
                ['name' => 'Darden', 'state_id' => 3970],
                ['name' => 'Huron', 'state_id' => 3970],
                ['name' => 'Lexington', 'state_id' => 3970],
                ['name' => 'Reagan', 'state_id' => 3970],
                ['name' => 'Sardis', 'state_id' => 3970],
                ['name' => 'Wildersville', 'state_id' => 3970],
                ['name' => 'Buchanan', 'state_id' => 3970],
                ['name' => 'Como', 'state_id' => 3970],
                ['name' => 'Cottage Grove', 'state_id' => 3970],
                ['name' => 'Henry', 'state_id' => 3970],
                ['name' => 'Mansfield', 'state_id' => 3970],
                ['name' => 'Paris', 'state_id' => 3970],
                ['name' => 'Puryear', 'state_id' => 3970],
                ['name' => 'Springville', 'state_id' => 3970],
                ['name' => 'Bon Aqua', 'state_id' => 3970],
                ['name' => 'Centerville', 'state_id' => 3970],
                ['name' => 'Lyles', 'state_id' => 3970],
                ['name' => 'Nunnelly', 'state_id' => 3970],
                ['name' => 'Only', 'state_id' => 3970],
                ['name' => 'Duck River', 'state_id' => 3970],
                ['name' => 'Primm Springs', 'state_id' => 3970],
                ['name' => 'Erin', 'state_id' => 3970],
                ['name' => 'Stewart', 'state_id' => 3970],
                ['name' => 'Tennessee Ridge', 'state_id' => 3970],
                ['name' => 'Hurricane Mills', 'state_id' => 3970],
                ['name' => 'Mc Ewen', 'state_id' => 3970],
                ['name' => 'New Johnsonville', 'state_id' => 3970],
                ['name' => 'Waverly', 'state_id' => 3970],
                ['name' => 'Gainesboro', 'state_id' => 3970],
                ['name' => 'Granville', 'state_id' => 3970],
                ['name' => 'Whitleyville', 'state_id' => 3970],
                ['name' => 'Dandridge', 'state_id' => 3970],
                ['name' => 'Jefferson City', 'state_id' => 3970],
                ['name' => 'New Market', 'state_id' => 3970],
                ['name' => 'Strawberry Plains', 'state_id' => 3970],
                ['name' => 'White Pine', 'state_id' => 3970],
                ['name' => 'Butler', 'state_id' => 3970],
                ['name' => 'Laurel Bloomery', 'state_id' => 3970],
                ['name' => 'Mountain City', 'state_id' => 3970],
                ['name' => 'Shady Valley', 'state_id' => 3970],
                ['name' => 'Trade', 'state_id' => 3970],
                ['name' => 'Corryton', 'state_id' => 3970],
                ['name' => 'Heiskell', 'state_id' => 3970],
                ['name' => 'Mascot', 'state_id' => 3970],
                ['name' => 'Powell', 'state_id' => 3970],
                ['name' => 'Knoxville', 'state_id' => 3970],
                ['name' => 'Wynnburg', 'state_id' => 3970],
                ['name' => 'Tiptonville', 'state_id' => 3970],
                ['name' => 'Ridgely', 'state_id' => 3970],
                ['name' => 'Gates', 'state_id' => 3970],
                ['name' => 'Halls', 'state_id' => 3970],
                ['name' => 'Henning', 'state_id' => 3970],
                ['name' => 'Ripley', 'state_id' => 3970],
                ['name' => 'Ethridge', 'state_id' => 3970],
                ['name' => 'Five Points', 'state_id' => 3970],
                ['name' => 'Iron City', 'state_id' => 3970],
                ['name' => 'Lawrenceburg', 'state_id' => 3970],
                ['name' => 'Leoma', 'state_id' => 3970],
                ['name' => 'Loretto', 'state_id' => 3970],
                ['name' => 'Saint Joseph', 'state_id' => 3970],
                ['name' => 'Summertown', 'state_id' => 3970],
                ['name' => 'Westpoint', 'state_id' => 3970],
                ['name' => 'Hohenwald', 'state_id' => 3970],
                ['name' => 'Petersburg', 'state_id' => 3970],
                ['name' => 'Elora', 'state_id' => 3970],
                ['name' => 'Fayetteville', 'state_id' => 3970],
                ['name' => 'Flintville', 'state_id' => 3970],
                ['name' => 'Kelso', 'state_id' => 3970],
                ['name' => 'Mulberry', 'state_id' => 3970],
                ['name' => 'Dellrose', 'state_id' => 3970],
                ['name' => 'Taft', 'state_id' => 3970],
                ['name' => 'Greenback', 'state_id' => 3970],
                ['name' => 'Lenoir City', 'state_id' => 3970],
                ['name' => 'Loudon', 'state_id' => 3970],
                ['name' => 'Philadelphia', 'state_id' => 3970],
                ['name' => 'Athens', 'state_id' => 3970],
                ['name' => 'Calhoun', 'state_id' => 3970],
                ['name' => 'Englewood', 'state_id' => 3970],
                ['name' => 'Etowah', 'state_id' => 3970],
                ['name' => 'Riceville', 'state_id' => 3970],
                ['name' => 'Niota', 'state_id' => 3970],
                ['name' => 'Adamsville', 'state_id' => 3970],
                ['name' => 'Bethel Springs', 'state_id' => 3970],
                ['name' => 'Finger', 'state_id' => 3970],
                ['name' => 'Guys', 'state_id' => 3970],
                ['name' => 'Michie', 'state_id' => 3970],
                ['name' => 'Milledgeville', 'state_id' => 3970],
                ['name' => 'Ramer', 'state_id' => 3970],
                ['name' => 'Selmer', 'state_id' => 3970],
                ['name' => 'Stantonville', 'state_id' => 3970],
                ['name' => 'Chewalla', 'state_id' => 3970],
                ['name' => 'Lafayette', 'state_id' => 3970],
                ['name' => 'Red Boiling Springs', 'state_id' => 3970],
                ['name' => 'Jackson', 'state_id' => 3970],
                ['name' => 'Beech Bluff', 'state_id' => 3970],
                ['name' => 'Medon', 'state_id' => 3970],
                ['name' => 'Oakfield', 'state_id' => 3970],
                ['name' => 'Pinson', 'state_id' => 3970],
                ['name' => 'Spring Creek', 'state_id' => 3970],
                ['name' => 'Denmark', 'state_id' => 3970],
                ['name' => 'Mercer', 'state_id' => 3970],
                ['name' => 'Guild', 'state_id' => 3970],
                ['name' => 'Jasper', 'state_id' => 3970],
                ['name' => 'Sequatchie', 'state_id' => 3970],
                ['name' => 'South Pittsburg', 'state_id' => 3970],
                ['name' => 'Whiteside', 'state_id' => 3970],
                ['name' => 'Whitwell', 'state_id' => 3970],
                ['name' => 'Belfast', 'state_id' => 3970],
                ['name' => 'Chapel Hill', 'state_id' => 3970],
                ['name' => 'Cornersville', 'state_id' => 3970],
                ['name' => 'Lewisburg', 'state_id' => 3970],
                ['name' => 'Spring Hill', 'state_id' => 3970],
                ['name' => 'Columbia', 'state_id' => 3970],
                ['name' => 'Culleoka', 'state_id' => 3970],
                ['name' => 'Hampshire', 'state_id' => 3970],
                ['name' => 'Mount Pleasant', 'state_id' => 3970],
                ['name' => 'Santa Fe', 'state_id' => 3970],
                ['name' => 'Williamsport', 'state_id' => 3970],
                ['name' => 'Decatur', 'state_id' => 3970],
                ['name' => 'Georgetown', 'state_id' => 3970],
                ['name' => 'Ten Mile', 'state_id' => 3970],
                ['name' => 'Cokercreek', 'state_id' => 3970],
                ['name' => 'Madisonville', 'state_id' => 3970],
                ['name' => 'Tellico Plains', 'state_id' => 3970],
                ['name' => 'Sweetwater', 'state_id' => 3970],
                ['name' => 'Vonore', 'state_id' => 3970],
                ['name' => 'Clarksville', 'state_id' => 3970],
                ['name' => 'Cunningham', 'state_id' => 3970],
                ['name' => 'Palmyra', 'state_id' => 3970],
                ['name' => 'Southside', 'state_id' => 3970],
                ['name' => 'Woodlawn', 'state_id' => 3970],
                ['name' => 'Lynchburg', 'state_id' => 3970],
                ['name' => 'Coalfield', 'state_id' => 3970],
                ['name' => 'Deer Lodge', 'state_id' => 3970],
                ['name' => 'Rugby', 'state_id' => 3970],
                ['name' => 'Lancing', 'state_id' => 3970],
                ['name' => 'Oakdale', 'state_id' => 3970],
                ['name' => 'Oliver Springs', 'state_id' => 3970],
                ['name' => 'Petros', 'state_id' => 3970],
                ['name' => 'Sunbright', 'state_id' => 3970],
                ['name' => 'Wartburg', 'state_id' => 3970],
                ['name' => 'Hornbeak', 'state_id' => 3970],
                ['name' => 'Obion', 'state_id' => 3970],
                ['name' => 'Rives', 'state_id' => 3970],
                ['name' => 'Samburg', 'state_id' => 3970],
                ['name' => 'South Fulton', 'state_id' => 3970],
                ['name' => 'Troy', 'state_id' => 3970],
                ['name' => 'Union City', 'state_id' => 3970],
                ['name' => 'Woodland Mills', 'state_id' => 3970],
                ['name' => 'Allons', 'state_id' => 3970],
                ['name' => 'Allred', 'state_id' => 3970],
                ['name' => 'Alpine', 'state_id' => 3970],
                ['name' => 'Crawford', 'state_id' => 3970],
                ['name' => 'Hilham', 'state_id' => 3970],
                ['name' => 'Livingston', 'state_id' => 3970],
                ['name' => 'Monroe', 'state_id' => 3970],
                ['name' => 'Rickman', 'state_id' => 3970],
                ['name' => 'Linden', 'state_id' => 3970],
                ['name' => 'Lobelville', 'state_id' => 3970],
                ['name' => 'Byrdstown', 'state_id' => 3970],
                ['name' => 'Benton', 'state_id' => 3970],
                ['name' => 'Conasauga', 'state_id' => 3970],
                ['name' => 'Copperhill', 'state_id' => 3970],
                ['name' => 'Delano', 'state_id' => 3970],
                ['name' => 'Ducktown', 'state_id' => 3970],
                ['name' => 'Farner', 'state_id' => 3970],
                ['name' => 'Ocoee', 'state_id' => 3970],
                ['name' => 'Old Fort', 'state_id' => 3970],
                ['name' => 'Reliance', 'state_id' => 3970],
                ['name' => 'Turtletown', 'state_id' => 3970],
                ['name' => 'Cookeville', 'state_id' => 3970],
                ['name' => 'Baxter', 'state_id' => 3970],
                ['name' => 'Bloomington Springs', 'state_id' => 3970],
                ['name' => 'Buffalo Valley', 'state_id' => 3970],
                ['name' => 'Monterey', 'state_id' => 3970],
                ['name' => 'Silver Point', 'state_id' => 3970],
                ['name' => 'Dayton', 'state_id' => 3970],
                ['name' => 'Evensville', 'state_id' => 3970],
                ['name' => 'Grandview', 'state_id' => 3970],
                ['name' => 'Graysville', 'state_id' => 3970],
                ['name' => 'Spring City', 'state_id' => 3970],
                ['name' => 'Harriman', 'state_id' => 3970],
                ['name' => 'Kingston', 'state_id' => 3970],
                ['name' => 'Rockwood', 'state_id' => 3970],
                ['name' => 'Adams', 'state_id' => 3970],
                ['name' => 'Cedar Hill', 'state_id' => 3970],
                ['name' => 'Cross Plains', 'state_id' => 3970],
                ['name' => 'Greenbrier', 'state_id' => 3970],
                ['name' => 'Orlinda', 'state_id' => 3970],
                ['name' => 'Ridgetop', 'state_id' => 3970],
                ['name' => 'Springfield', 'state_id' => 3970],
                ['name' => 'White House', 'state_id' => 3970],
                ['name' => 'Christiana', 'state_id' => 3970],
                ['name' => 'Eagleville', 'state_id' => 3970],
                ['name' => 'Fosterville', 'state_id' => 3970],
                ['name' => 'Lascassas', 'state_id' => 3970],
                ['name' => 'La Vergne', 'state_id' => 3970],
                ['name' => 'Milton', 'state_id' => 3970],
                ['name' => 'Murfreesboro', 'state_id' => 3970],
                ['name' => 'Rockvale', 'state_id' => 3970],
                ['name' => 'Smyrna', 'state_id' => 3970],
                ['name' => 'Elgin', 'state_id' => 3970],
                ['name' => 'Helenwood', 'state_id' => 3970],
                ['name' => 'Huntsville', 'state_id' => 3970],
                ['name' => 'Oneida', 'state_id' => 3970],
                ['name' => 'Robbins', 'state_id' => 3970],
                ['name' => 'Winfield', 'state_id' => 3970],
                ['name' => 'Dunlap', 'state_id' => 3970],
                ['name' => 'Gatlinburg', 'state_id' => 3970],
                ['name' => 'Kodak', 'state_id' => 3970],
                ['name' => 'Sevierville', 'state_id' => 3970],
                ['name' => 'Pigeon Forge', 'state_id' => 3970],
                ['name' => 'Seymour', 'state_id' => 3970],
                ['name' => 'Memphis', 'state_id' => 3970],
                ['name' => 'Arlington', 'state_id' => 3970],
                ['name' => 'Brunswick', 'state_id' => 3970],
                ['name' => 'Cordova', 'state_id' => 3970],
                ['name' => 'Collierville', 'state_id' => 3970],
                ['name' => 'Eads', 'state_id' => 3970],
                ['name' => 'Ellendale', 'state_id' => 3970],
                ['name' => 'Millington', 'state_id' => 3970],
                ['name' => 'Germantown', 'state_id' => 3970],
                ['name' => 'Carthage', 'state_id' => 3970],
                ['name' => 'Dixon Springs', 'state_id' => 3970],
                ['name' => 'Pleasant Shade', 'state_id' => 3970],
                ['name' => 'Riddleton', 'state_id' => 3970],
                ['name' => 'Brush Creek', 'state_id' => 3970],
                ['name' => 'Chestnut Mound', 'state_id' => 3970],
                ['name' => 'Elmwood', 'state_id' => 3970],
                ['name' => 'Gordonsville', 'state_id' => 3970],
                ['name' => 'Hickman', 'state_id' => 3970],
                ['name' => 'Lancaster', 'state_id' => 3970],
                ['name' => 'Big Rock', 'state_id' => 3970],
                ['name' => 'Bumpus Mills', 'state_id' => 3970],
                ['name' => 'Cumberland City', 'state_id' => 3970],
                ['name' => 'Dover', 'state_id' => 3970],
                ['name' => 'Indian Mound', 'state_id' => 3970],
                ['name' => 'Blountville', 'state_id' => 3970],
                ['name' => 'Bluff City', 'state_id' => 3970],
                ['name' => 'Bristol', 'state_id' => 3970],
                ['name' => 'Kingsport', 'state_id' => 3970],
                ['name' => 'Piney Flats', 'state_id' => 3970],
                ['name' => 'Bethpage', 'state_id' => 3970],
                ['name' => 'Castalian Springs', 'state_id' => 3970],
                ['name' => 'Cottontown', 'state_id' => 3970],
                ['name' => 'Gallatin', 'state_id' => 3970],
                ['name' => 'Hendersonville', 'state_id' => 3970],
                ['name' => 'Mitchellville', 'state_id' => 3970],
                ['name' => 'Portland', 'state_id' => 3970],
                ['name' => 'Westmoreland', 'state_id' => 3970],
                ['name' => 'Atoka', 'state_id' => 3970],
                ['name' => 'Brighton', 'state_id' => 3970],
                ['name' => 'Burlison', 'state_id' => 3970],
                ['name' => 'Covington', 'state_id' => 3970],
                ['name' => 'Drummonds', 'state_id' => 3970],
                ['name' => 'Mason', 'state_id' => 3970],
                ['name' => 'Munford', 'state_id' => 3970],
                ['name' => 'Tipton', 'state_id' => 3970],
                ['name' => 'Hartsville', 'state_id' => 3970],
                ['name' => 'Erwin', 'state_id' => 3970],
                ['name' => 'Flag Pond', 'state_id' => 3970],
                ['name' => 'Unicoi', 'state_id' => 3970],
                ['name' => 'Luttrell', 'state_id' => 3970],
                ['name' => 'Maynardville', 'state_id' => 3970],
                ['name' => 'Sharps Chapel', 'state_id' => 3970],
                ['name' => 'Spencer', 'state_id' => 3970],
                ['name' => 'Mcminnville', 'state_id' => 3970],
                ['name' => 'Morrison', 'state_id' => 3970],
                ['name' => 'Smartt', 'state_id' => 3970],
                ['name' => 'Viola', 'state_id' => 3970],
                ['name' => 'Campaign', 'state_id' => 3970],
                ['name' => 'Rock Island', 'state_id' => 3970],
                ['name' => 'Johnson City', 'state_id' => 3970],
                ['name' => 'Fall Branch', 'state_id' => 3970],
                ['name' => 'Jonesborough', 'state_id' => 3970],
                ['name' => 'Limestone', 'state_id' => 3970],
                ['name' => 'Mountain Home', 'state_id' => 3970],
                ['name' => 'Telford', 'state_id' => 3970],
                ['name' => 'Clifton', 'state_id' => 3970],
                ['name' => 'Collinwood', 'state_id' => 3970],
                ['name' => 'Cypress Inn', 'state_id' => 3970],
                ['name' => 'Lutts', 'state_id' => 3970],
                ['name' => 'Waynesboro', 'state_id' => 3970],
                ['name' => 'Dresden', 'state_id' => 3970],
                ['name' => 'Dukedom', 'state_id' => 3970],
                ['name' => 'Gleason', 'state_id' => 3970],
                ['name' => 'Greenfield', 'state_id' => 3970],
                ['name' => 'Martin', 'state_id' => 3970],
                ['name' => 'Palmersville', 'state_id' => 3970],
                ['name' => 'Sharon', 'state_id' => 3970],
                ['name' => 'Doyle', 'state_id' => 3970],
                ['name' => 'Quebeck', 'state_id' => 3970],
                ['name' => 'Sparta', 'state_id' => 3970],
                ['name' => 'Walling', 'state_id' => 3970],
                ['name' => 'Arrington', 'state_id' => 3970],
                ['name' => 'Brentwood', 'state_id' => 3970],
                ['name' => 'College Grove', 'state_id' => 3970],
                ['name' => 'Fairview', 'state_id' => 3970],
                ['name' => 'Franklin', 'state_id' => 3970],
                ['name' => 'Nolensville', 'state_id' => 3970],
                ['name' => 'Thompsons Station', 'state_id' => 3970],
                ['name' => 'Gladeville', 'state_id' => 3970],
                ['name' => 'Lebanon', 'state_id' => 3970],
                ['name' => 'Mount Juliet', 'state_id' => 3970],
                ['name' => 'Norene', 'state_id' => 3970],
                ['name' => 'Watertown', 'state_id' => 3970]
            ]);
        }
    }
}
