<?php

use Illuminate\Database\Seeder;

class state50TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WV - West Virginia.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Volga', 'state_id' => 3977],
                ['name' => 'Belington', 'state_id' => 3977],
                ['name' => 'Junior', 'state_id' => 3977],
                ['name' => 'Galloway', 'state_id' => 3977],
                ['name' => 'Moatsville', 'state_id' => 3977],
                ['name' => 'Philippi', 'state_id' => 3977],
                ['name' => 'Martinsburg', 'state_id' => 3977],
                ['name' => 'Bunker Hill', 'state_id' => 3977],
                ['name' => 'Falling Waters', 'state_id' => 3977],
                ['name' => 'Gerrardstown', 'state_id' => 3977],
                ['name' => 'Glengary', 'state_id' => 3977],
                ['name' => 'Hedgesville', 'state_id' => 3977],
                ['name' => 'Inwood', 'state_id' => 3977],
                ['name' => 'Ridgeway', 'state_id' => 3977],
                ['name' => 'Ashford', 'state_id' => 3977],
                ['name' => 'Bim', 'state_id' => 3977],
                ['name' => 'Bloomingrose', 'state_id' => 3977],
                ['name' => 'Bob White', 'state_id' => 3977],
                ['name' => 'Comfort', 'state_id' => 3977],
                ['name' => 'Costa', 'state_id' => 3977],
                ['name' => 'Danville', 'state_id' => 3977],
                ['name' => 'Foster', 'state_id' => 3977],
                ['name' => 'Gordon', 'state_id' => 3977],
                ['name' => 'Hewett', 'state_id' => 3977],
                ['name' => 'Jeffrey', 'state_id' => 3977],
                ['name' => 'Madison', 'state_id' => 3977],
                ['name' => 'Nellis', 'state_id' => 3977],
                ['name' => 'Orgas', 'state_id' => 3977],
                ['name' => 'Ottawa', 'state_id' => 3977],
                ['name' => 'Peytona', 'state_id' => 3977],
                ['name' => 'Racine', 'state_id' => 3977],
                ['name' => 'Ridgeview', 'state_id' => 3977],
                ['name' => 'Seth', 'state_id' => 3977],
                ['name' => 'Sylvester', 'state_id' => 3977],
                ['name' => 'Turtle Creek', 'state_id' => 3977],
                ['name' => 'Twilight', 'state_id' => 3977],
                ['name' => 'Uneeda', 'state_id' => 3977],
                ['name' => 'Van', 'state_id' => 3977],
                ['name' => 'Wharton', 'state_id' => 3977],
                ['name' => 'Whitesville', 'state_id' => 3977],
                ['name' => 'Julian', 'state_id' => 3977],
                ['name' => 'Burnsville', 'state_id' => 3977],
                ['name' => 'Sutton', 'state_id' => 3977],
                ['name' => 'Copen', 'state_id' => 3977],
                ['name' => 'Exchange', 'state_id' => 3977],
                ['name' => 'Flatwoods', 'state_id' => 3977],
                ['name' => 'Frametown', 'state_id' => 3977],
                ['name' => 'Gassaway', 'state_id' => 3977],
                ['name' => 'Heaters', 'state_id' => 3977],
                ['name' => 'Little Birch', 'state_id' => 3977],
                ['name' => 'Napier', 'state_id' => 3977],
                ['name' => 'Beech Bottom', 'state_id' => 3977],
                ['name' => 'Bethany', 'state_id' => 3977],
                ['name' => 'Colliers', 'state_id' => 3977],
                ['name' => 'Follansbee', 'state_id' => 3977],
                ['name' => 'Short Creek', 'state_id' => 3977],
                ['name' => 'Wellsburg', 'state_id' => 3977],
                ['name' => 'Windsor Heights', 'state_id' => 3977],
                ['name' => 'Barboursville', 'state_id' => 3977],
                ['name' => 'Culloden', 'state_id' => 3977],
                ['name' => 'Lesage', 'state_id' => 3977],
                ['name' => 'Milton', 'state_id' => 3977],
                ['name' => 'Ona', 'state_id' => 3977],
                ['name' => 'Salt Rock', 'state_id' => 3977],
                ['name' => 'Huntington', 'state_id' => 3977],
                ['name' => 'Arnoldsburg', 'state_id' => 3977],
                ['name' => 'Chloe', 'state_id' => 3977],
                ['name' => 'Millstone', 'state_id' => 3977],
                ['name' => 'Orma', 'state_id' => 3977],
                ['name' => 'Big Bend', 'state_id' => 3977],
                ['name' => 'Big Springs', 'state_id' => 3977],
                ['name' => 'Grantsville', 'state_id' => 3977],
                ['name' => 'Mount Zion', 'state_id' => 3977],
                ['name' => 'Bickmore', 'state_id' => 3977],
                ['name' => 'Bomont', 'state_id' => 3977],
                ['name' => 'Clay', 'state_id' => 3977],
                ['name' => 'Duck', 'state_id' => 3977],
                ['name' => 'Glen', 'state_id' => 3977],
                ['name' => 'Indore', 'state_id' => 3977],
                ['name' => 'Ivydale', 'state_id' => 3977],
                ['name' => 'Lizemores', 'state_id' => 3977],
                ['name' => 'Maysel', 'state_id' => 3977],
                ['name' => 'Nebo', 'state_id' => 3977],
                ['name' => 'Procious', 'state_id' => 3977],
                ['name' => 'Widen', 'state_id' => 3977],
                ['name' => 'Wallback', 'state_id' => 3977],
                ['name' => 'Dille', 'state_id' => 3977],
                ['name' => 'Center Point', 'state_id' => 3977],
                ['name' => 'New Milton', 'state_id' => 3977],
                ['name' => 'Smithburg', 'state_id' => 3977],
                ['name' => 'West Union', 'state_id' => 3977],
                ['name' => 'Alloy', 'state_id' => 3977],
                ['name' => 'Boomer', 'state_id' => 3977],
                ['name' => 'Cannelton', 'state_id' => 3977],
                ['name' => 'Charlton Heights', 'state_id' => 3977],
                ['name' => 'Deep Water', 'state_id' => 3977],
                ['name' => 'Gauley Bridge', 'state_id' => 3977],
                ['name' => 'Glen Ferris', 'state_id' => 3977],
                ['name' => 'Kanawha Falls', 'state_id' => 3977],
                ['name' => 'Kimberly', 'state_id' => 3977],
                ['name' => 'Kincaid', 'state_id' => 3977],
                ['name' => 'Montgomery', 'state_id' => 3977],
                ['name' => 'Mount Carbon', 'state_id' => 3977],
                ['name' => 'Page', 'state_id' => 3977],
                ['name' => 'Powellton', 'state_id' => 3977],
                ['name' => 'Robson', 'state_id' => 3977],
                ['name' => 'Mount Olive', 'state_id' => 3977],
                ['name' => 'Smithers', 'state_id' => 3977],
                ['name' => 'Ansted', 'state_id' => 3977],
                ['name' => 'Danese', 'state_id' => 3977],
                ['name' => 'Dothan', 'state_id' => 3977],
                ['name' => 'Edmond', 'state_id' => 3977],
                ['name' => 'Fayetteville', 'state_id' => 3977],
                ['name' => 'Glen Jean', 'state_id' => 3977],
                ['name' => 'Hico', 'state_id' => 3977],
                ['name' => 'Hilltop', 'state_id' => 3977],
                ['name' => 'Lansing', 'state_id' => 3977],
                ['name' => 'Layland', 'state_id' => 3977],
                ['name' => 'Lochgelly', 'state_id' => 3977],
                ['name' => 'Lookout', 'state_id' => 3977],
                ['name' => 'Minden', 'state_id' => 3977],
                ['name' => 'Mount Hope', 'state_id' => 3977],
                ['name' => 'Oak Hill', 'state_id' => 3977],
                ['name' => 'Pax', 'state_id' => 3977],
                ['name' => 'Prince', 'state_id' => 3977],
                ['name' => 'Scarbro', 'state_id' => 3977],
                ['name' => 'Thurmond', 'state_id' => 3977],
                ['name' => 'Victor', 'state_id' => 3977],
                ['name' => 'Winona', 'state_id' => 3977],
                ['name' => 'Meadow Bridge', 'state_id' => 3977],
                ['name' => 'Spring Dale', 'state_id' => 3977],
                ['name' => 'Nallen', 'state_id' => 3977],
                ['name' => 'Normantown', 'state_id' => 3977],
                ['name' => 'Coxs Mills', 'state_id' => 3977],
                ['name' => 'Glenville', 'state_id' => 3977],
                ['name' => 'Linn', 'state_id' => 3977],
                ['name' => 'Sand Fork', 'state_id' => 3977],
                ['name' => 'Troy', 'state_id' => 3977],
                ['name' => 'Cedarville', 'state_id' => 3977],
                ['name' => 'Rosedale', 'state_id' => 3977],
                ['name' => 'Shock', 'state_id' => 3977],
                ['name' => 'Bayard', 'state_id' => 3977],
                ['name' => 'Gormania', 'state_id' => 3977],
                ['name' => 'Lahmansville', 'state_id' => 3977],
                ['name' => 'Mount Storm', 'state_id' => 3977],
                ['name' => 'Maysville', 'state_id' => 3977],
                ['name' => 'Petersburg', 'state_id' => 3977],
                ['name' => 'Cabins', 'state_id' => 3977],
                ['name' => 'Lewisburg', 'state_id' => 3977],
                ['name' => 'Fairlea', 'state_id' => 3977],
                ['name' => 'Alderson', 'state_id' => 3977],
                ['name' => 'Asbury', 'state_id' => 3977],
                ['name' => 'Caldwell', 'state_id' => 3977],
                ['name' => 'Crawley', 'state_id' => 3977],
                ['name' => 'Frankford', 'state_id' => 3977],
                ['name' => 'Grassy Meadows', 'state_id' => 3977],
                ['name' => 'Maxwelton', 'state_id' => 3977],
                ['name' => 'Renick', 'state_id' => 3977],
                ['name' => 'Ronceverte', 'state_id' => 3977],
                ['name' => 'Smoot', 'state_id' => 3977],
                ['name' => 'White Sulphur Springs', 'state_id' => 3977],
                ['name' => 'Williamsburg', 'state_id' => 3977],
                ['name' => 'Charmco', 'state_id' => 3977],
                ['name' => 'Rainelle', 'state_id' => 3977],
                ['name' => 'Leslie', 'state_id' => 3977],
                ['name' => 'Quinwood', 'state_id' => 3977],
                ['name' => 'Rupert', 'state_id' => 3977],
                ['name' => 'Levels', 'state_id' => 3977],
                ['name' => 'Points', 'state_id' => 3977],
                ['name' => 'Slanesville', 'state_id' => 3977],
                ['name' => 'Augusta', 'state_id' => 3977],
                ['name' => 'Capon Bridge', 'state_id' => 3977],
                ['name' => 'Delray', 'state_id' => 3977],
                ['name' => 'Green Spring', 'state_id' => 3977],
                ['name' => 'Rio', 'state_id' => 3977],
                ['name' => 'Romney', 'state_id' => 3977],
                ['name' => 'Shanks', 'state_id' => 3977],
                ['name' => 'Springfield', 'state_id' => 3977],
                ['name' => 'High View', 'state_id' => 3977],
                ['name' => 'Bloomery', 'state_id' => 3977],
                ['name' => 'Capon Springs', 'state_id' => 3977],
                ['name' => 'Purgitsville', 'state_id' => 3977],
                ['name' => 'Yellow Spring', 'state_id' => 3977],
                ['name' => 'Chester', 'state_id' => 3977],
                ['name' => 'New Cumberland', 'state_id' => 3977],
                ['name' => 'Newell', 'state_id' => 3977],
                ['name' => 'New Manchester', 'state_id' => 3977],
                ['name' => 'Weirton', 'state_id' => 3977],
                ['name' => 'Baker', 'state_id' => 3977],
                ['name' => 'Lost City', 'state_id' => 3977],
                ['name' => 'Mathias', 'state_id' => 3977],
                ['name' => 'Fisher', 'state_id' => 3977],
                ['name' => 'Moorefield', 'state_id' => 3977],
                ['name' => 'Milam', 'state_id' => 3977],
                ['name' => 'Old Fields', 'state_id' => 3977],
                ['name' => 'Wardensville', 'state_id' => 3977],
                ['name' => 'Clarksburg', 'state_id' => 3977],
                ['name' => 'Anmoore', 'state_id' => 3977],
                ['name' => 'Bridgeport', 'state_id' => 3977],
                ['name' => 'Gypsy', 'state_id' => 3977],
                ['name' => 'Haywood', 'state_id' => 3977],
                ['name' => 'Hepzibah', 'state_id' => 3977],
                ['name' => 'Lost Creek', 'state_id' => 3977],
                ['name' => 'Lumberport', 'state_id' => 3977],
                ['name' => 'Meadowbrook', 'state_id' => 3977],
                ['name' => 'Mount Clare', 'state_id' => 3977],
                ['name' => 'Reynoldsville', 'state_id' => 3977],
                ['name' => 'Salem', 'state_id' => 3977],
                ['name' => 'Shinnston', 'state_id' => 3977],
                ['name' => 'Spelter', 'state_id' => 3977],
                ['name' => 'Wallace', 'state_id' => 3977],
                ['name' => 'West Milford', 'state_id' => 3977],
                ['name' => 'Wyatt', 'state_id' => 3977],
                ['name' => 'Enterprise', 'state_id' => 3977],
                ['name' => 'Advent', 'state_id' => 3977],
                ['name' => 'Cottageville', 'state_id' => 3977],
                ['name' => 'Evans', 'state_id' => 3977],
                ['name' => 'Gay', 'state_id' => 3977],
                ['name' => 'Given', 'state_id' => 3977],
                ['name' => 'Kenna', 'state_id' => 3977],
                ['name' => 'Le Roy', 'state_id' => 3977],
                ['name' => 'Millwood', 'state_id' => 3977],
                ['name' => 'Mount Alto', 'state_id' => 3977],
                ['name' => 'Ripley', 'state_id' => 3977],
                ['name' => 'Sandyville', 'state_id' => 3977],
                ['name' => 'Ravenswood', 'state_id' => 3977],
                ['name' => 'Bakerton', 'state_id' => 3977],
                ['name' => 'Charles Town', 'state_id' => 3977],
                ['name' => 'Halltown', 'state_id' => 3977],
                ['name' => 'Harpers Ferry', 'state_id' => 3977],
                ['name' => 'Kearneysville', 'state_id' => 3977],
                ['name' => 'Millville', 'state_id' => 3977],
                ['name' => 'Ranson', 'state_id' => 3977],
                ['name' => 'Rippon', 'state_id' => 3977],
                ['name' => 'Shenandoah Junction', 'state_id' => 3977],
                ['name' => 'Shepherdstown', 'state_id' => 3977],
                ['name' => 'Summit Point', 'state_id' => 3977],
                ['name' => 'Alum Creek', 'state_id' => 3977],
                ['name' => 'Belle', 'state_id' => 3977],
                ['name' => 'Blount', 'state_id' => 3977],
                ['name' => 'Blue Creek', 'state_id' => 3977],
                ['name' => 'Cabin Creek', 'state_id' => 3977],
                ['name' => 'Cedar Grove', 'state_id' => 3977],
                ['name' => 'Clendenin', 'state_id' => 3977],
                ['name' => 'Dawes', 'state_id' => 3977],
                ['name' => 'Drybranch', 'state_id' => 3977],
                ['name' => 'Dunbar', 'state_id' => 3977],
                ['name' => 'East Bank', 'state_id' => 3977],
                ['name' => 'Elkview', 'state_id' => 3977],
                ['name' => 'Eskdale', 'state_id' => 3977],
                ['name' => 'Falling Rock', 'state_id' => 3977],
                ['name' => 'Gallagher', 'state_id' => 3977],
                ['name' => 'Glasgow', 'state_id' => 3977],
                ['name' => 'Handley', 'state_id' => 3977],
                ['name' => 'Hansford', 'state_id' => 3977],
                ['name' => 'Hernshaw', 'state_id' => 3977],
                ['name' => 'Hugheston', 'state_id' => 3977],
                ['name' => 'Institute', 'state_id' => 3977],
                ['name' => 'London', 'state_id' => 3977],
                ['name' => 'Mammoth', 'state_id' => 3977],
                ['name' => 'Miami', 'state_id' => 3977],
                ['name' => 'Nitro', 'state_id' => 3977],
                ['name' => 'Pinch', 'state_id' => 3977],
                ['name' => 'Pond Gap', 'state_id' => 3977],
                ['name' => 'Pratt', 'state_id' => 3977],
                ['name' => 'Saint Albans', 'state_id' => 3977],
                ['name' => 'Tad', 'state_id' => 3977],
                ['name' => 'Tornado', 'state_id' => 3977],
                ['name' => 'Winifrede', 'state_id' => 3977],
                ['name' => 'Charleston', 'state_id' => 3977],
                ['name' => 'South Charleston', 'state_id' => 3977],
                ['name' => 'Alum Bridge', 'state_id' => 3977],
                ['name' => 'Camden', 'state_id' => 3977],
                ['name' => 'Crawford', 'state_id' => 3977],
                ['name' => 'Horner', 'state_id' => 3977],
                ['name' => 'Ireland', 'state_id' => 3977],
                ['name' => 'Jane Lew', 'state_id' => 3977],
                ['name' => 'Orlando', 'state_id' => 3977],
                ['name' => 'Walkersville', 'state_id' => 3977],
                ['name' => 'Weston', 'state_id' => 3977],
                ['name' => 'Alkol', 'state_id' => 3977],
                ['name' => 'Branchland', 'state_id' => 3977],
                ['name' => 'Griffithsville', 'state_id' => 3977],
                ['name' => 'Hamlin', 'state_id' => 3977],
                ['name' => 'Harts', 'state_id' => 3977],
                ['name' => 'Midkiff', 'state_id' => 3977],
                ['name' => 'Myra', 'state_id' => 3977],
                ['name' => 'Ranger', 'state_id' => 3977],
                ['name' => 'Sod', 'state_id' => 3977],
                ['name' => 'Spurlockville', 'state_id' => 3977],
                ['name' => 'Sumerco', 'state_id' => 3977],
                ['name' => 'West Hamlin', 'state_id' => 3977],
                ['name' => 'Woodville', 'state_id' => 3977],
                ['name' => 'Yawkey', 'state_id' => 3977],
                ['name' => 'Blair', 'state_id' => 3977],
                ['name' => 'Clothier', 'state_id' => 3977],
                ['name' => 'Ethel', 'state_id' => 3977],
                ['name' => 'Lake', 'state_id' => 3977],
                ['name' => 'Sharples', 'state_id' => 3977],
                ['name' => 'Big Creek', 'state_id' => 3977],
                ['name' => 'Chapmanville', 'state_id' => 3977],
                ['name' => 'Pecks Mill', 'state_id' => 3977],
                ['name' => 'Logan', 'state_id' => 3977],
                ['name' => 'Accoville', 'state_id' => 3977],
                ['name' => 'Amherstdale', 'state_id' => 3977],
                ['name' => 'Bruno', 'state_id' => 3977],
                ['name' => 'Chauncey', 'state_id' => 3977],
                ['name' => 'Cora', 'state_id' => 3977],
                ['name' => 'Davin', 'state_id' => 3977],
                ['name' => 'Henlawson', 'state_id' => 3977],
                ['name' => 'Holden', 'state_id' => 3977],
                ['name' => 'Kistler', 'state_id' => 3977],
                ['name' => 'Lorado', 'state_id' => 3977],
                ['name' => 'Lyburn', 'state_id' => 3977],
                ['name' => 'Mallory', 'state_id' => 3977],
                ['name' => 'Man', 'state_id' => 3977],
                ['name' => 'Mount Gay', 'state_id' => 3977],
                ['name' => 'Omar', 'state_id' => 3977],
                ['name' => 'Peach Creek', 'state_id' => 3977],
                ['name' => 'Sarah Ann', 'state_id' => 3977],
                ['name' => 'Stollings', 'state_id' => 3977],
                ['name' => 'Switzer', 'state_id' => 3977],
                ['name' => 'Verdunville', 'state_id' => 3977],
                ['name' => 'Whitman', 'state_id' => 3977],
                ['name' => 'Wilkinson', 'state_id' => 3977],
                ['name' => 'Yolyn', 'state_id' => 3977],
                ['name' => 'Welch', 'state_id' => 3977],
                ['name' => 'Anawalt', 'state_id' => 3977],
                ['name' => 'Avondale', 'state_id' => 3977],
                ['name' => 'Bartley', 'state_id' => 3977],
                ['name' => 'Berwind', 'state_id' => 3977],
                ['name' => 'Big Sandy', 'state_id' => 3977],
                ['name' => 'Bradshaw', 'state_id' => 3977],
                ['name' => 'Cucumber', 'state_id' => 3977],
                ['name' => 'Davy', 'state_id' => 3977],
                ['name' => 'Eckman', 'state_id' => 3977],
                ['name' => 'Elbert', 'state_id' => 3977],
                ['name' => 'Elkhorn', 'state_id' => 3977],
                ['name' => 'Gary', 'state_id' => 3977],
                ['name' => 'Hensley', 'state_id' => 3977],
                ['name' => 'Iaeger', 'state_id' => 3977],
                ['name' => 'Isaban', 'state_id' => 3977],
                ['name' => 'Jenkinjones', 'state_id' => 3977],
                ['name' => 'Jolo', 'state_id' => 3977],
                ['name' => 'Kimball', 'state_id' => 3977],
                ['name' => 'Kyle', 'state_id' => 3977],
                ['name' => 'Maybeury', 'state_id' => 3977],
                ['name' => 'Mohawk', 'state_id' => 3977],
                ['name' => 'Newhall', 'state_id' => 3977],
                ['name' => 'Northfork', 'state_id' => 3977],
                ['name' => 'Pageton', 'state_id' => 3977],
                ['name' => 'Panther', 'state_id' => 3977],
                ['name' => 'Paynesville', 'state_id' => 3977],
                ['name' => 'Premier', 'state_id' => 3977],
                ['name' => 'Raysal', 'state_id' => 3977],
                ['name' => 'Roderfield', 'state_id' => 3977],
                ['name' => 'Squire', 'state_id' => 3977],
                ['name' => 'Switchback', 'state_id' => 3977],
                ['name' => 'Thorpe', 'state_id' => 3977],
                ['name' => 'War', 'state_id' => 3977],
                ['name' => 'Warriormine', 'state_id' => 3977],
                ['name' => 'Wilcoe', 'state_id' => 3977],
                ['name' => 'Fairmont', 'state_id' => 3977],
                ['name' => 'Barrackville', 'state_id' => 3977],
                ['name' => 'Baxter', 'state_id' => 3977],
                ['name' => 'Carolina', 'state_id' => 3977],
                ['name' => 'Colfax', 'state_id' => 3977],
                ['name' => 'Fairview', 'state_id' => 3977],
                ['name' => 'Farmington', 'state_id' => 3977],
                ['name' => 'Four States', 'state_id' => 3977],
                ['name' => 'Grant Town', 'state_id' => 3977],
                ['name' => 'Idamay', 'state_id' => 3977],
                ['name' => 'Kingmont', 'state_id' => 3977],
                ['name' => 'Mannington', 'state_id' => 3977],
                ['name' => 'Metz', 'state_id' => 3977],
                ['name' => 'Montana Mines', 'state_id' => 3977],
                ['name' => 'Rachel', 'state_id' => 3977],
                ['name' => 'Rivesville', 'state_id' => 3977],
                ['name' => 'Worthington', 'state_id' => 3977],
                ['name' => 'Benwood', 'state_id' => 3977],
                ['name' => 'Cameron', 'state_id' => 3977],
                ['name' => 'Dallas', 'state_id' => 3977],
                ['name' => 'Glen Dale', 'state_id' => 3977],
                ['name' => 'Glen Easton', 'state_id' => 3977],
                ['name' => 'Mcmechen', 'state_id' => 3977],
                ['name' => 'Moundsville', 'state_id' => 3977],
                ['name' => 'Proctor', 'state_id' => 3977],
                ['name' => 'Henderson', 'state_id' => 3977],
                ['name' => 'Leon', 'state_id' => 3977],
                ['name' => 'Southside', 'state_id' => 3977],
                ['name' => 'Hartford', 'state_id' => 3977],
                ['name' => 'Letart', 'state_id' => 3977],
                ['name' => 'Mason', 'state_id' => 3977],
                ['name' => 'New Haven', 'state_id' => 3977],
                ['name' => 'West Columbia', 'state_id' => 3977],
                ['name' => 'Apple Grove', 'state_id' => 3977],
                ['name' => 'Ashton', 'state_id' => 3977],
                ['name' => 'Gallipolis Ferry', 'state_id' => 3977],
                ['name' => 'Glenwood', 'state_id' => 3977],
                ['name' => 'Point Pleasant', 'state_id' => 3977],
                ['name' => 'Bluefield', 'state_id' => 3977],
                ['name' => 'Athens', 'state_id' => 3977],
                ['name' => 'Beeson', 'state_id' => 3977],
                ['name' => 'Bramwell', 'state_id' => 3977],
                ['name' => 'Freeman', 'state_id' => 3977],
                ['name' => 'Hiawatha', 'state_id' => 3977],
                ['name' => 'Kegley', 'state_id' => 3977],
                ['name' => 'Kellysville', 'state_id' => 3977],
                ['name' => 'Lashmeet', 'state_id' => 3977],
                ['name' => 'Matoaka', 'state_id' => 3977],
                ['name' => 'Montcalm', 'state_id' => 3977],
                ['name' => 'Nemours', 'state_id' => 3977],
                ['name' => 'Princeton', 'state_id' => 3977],
                ['name' => 'Rock', 'state_id' => 3977],
                ['name' => 'Wolfe', 'state_id' => 3977],
                ['name' => 'Camp Creek', 'state_id' => 3977],
                ['name' => 'Flat Top', 'state_id' => 3977],
                ['name' => 'Spanishburg', 'state_id' => 3977],
                ['name' => 'Lerona', 'state_id' => 3977],
                ['name' => 'Burlington', 'state_id' => 3977],
                ['name' => 'Elk Garden', 'state_id' => 3977],
                ['name' => 'Fort Ashby', 'state_id' => 3977],
                ['name' => 'Keyser', 'state_id' => 3977],
                ['name' => 'New Creek', 'state_id' => 3977],
                ['name' => 'Piedmont', 'state_id' => 3977],
                ['name' => 'Ridgeley', 'state_id' => 3977],
                ['name' => 'Wiley Ford', 'state_id' => 3977],
                ['name' => 'Justice', 'state_id' => 3977],
                ['name' => 'Baisden', 'state_id' => 3977],
                ['name' => 'Gilbert', 'state_id' => 3977],
                ['name' => 'Verner', 'state_id' => 3977],
                ['name' => 'Wharncliffe', 'state_id' => 3977],
                ['name' => 'Williamson', 'state_id' => 3977],
                ['name' => 'Borderland', 'state_id' => 3977],
                ['name' => 'Breeden', 'state_id' => 3977],
                ['name' => 'Chattaroy', 'state_id' => 3977],
                ['name' => 'Delbarton', 'state_id' => 3977],
                ['name' => 'Dingess', 'state_id' => 3977],
                ['name' => 'Edgarton', 'state_id' => 3977],
                ['name' => 'Kermit', 'state_id' => 3977],
                ['name' => 'Lenore', 'state_id' => 3977],
                ['name' => 'Matewan', 'state_id' => 3977],
                ['name' => 'Naugatuck', 'state_id' => 3977],
                ['name' => 'Newtown', 'state_id' => 3977],
                ['name' => 'North Matewan', 'state_id' => 3977],
                ['name' => 'Ragland', 'state_id' => 3977],
                ['name' => 'Rawl', 'state_id' => 3977],
                ['name' => 'Red Jacket', 'state_id' => 3977],
                ['name' => 'Varney', 'state_id' => 3977],
                ['name' => 'Morgantown', 'state_id' => 3977],
                ['name' => 'Blacksville', 'state_id' => 3977],
                ['name' => 'Cassville', 'state_id' => 3977],
                ['name' => 'Dellslow', 'state_id' => 3977],
                ['name' => 'Granville', 'state_id' => 3977],
                ['name' => 'Maidsville', 'state_id' => 3977],
                ['name' => 'Osage', 'state_id' => 3977],
                ['name' => 'Pentress', 'state_id' => 3977],
                ['name' => 'Pursglove', 'state_id' => 3977],
                ['name' => 'Wana', 'state_id' => 3977],
                ['name' => 'Ballard', 'state_id' => 3977],
                ['name' => 'Gap Mills', 'state_id' => 3977],
                ['name' => 'Greenville', 'state_id' => 3977],
                ['name' => 'Lindside', 'state_id' => 3977],
                ['name' => 'Peterstown', 'state_id' => 3977],
                ['name' => 'Secondcreek', 'state_id' => 3977],
                ['name' => 'Sinks Grove', 'state_id' => 3977],
                ['name' => 'Union', 'state_id' => 3977],
                ['name' => 'Waiteville', 'state_id' => 3977],
                ['name' => 'Wayside', 'state_id' => 3977],
                ['name' => 'Wolfcreek', 'state_id' => 3977],
                ['name' => 'Berkeley Springs', 'state_id' => 3977],
                ['name' => 'Great Cacapon', 'state_id' => 3977],
                ['name' => 'Paw Paw', 'state_id' => 3977],
                ['name' => 'Dixie', 'state_id' => 3977],
                ['name' => 'Fenwick', 'state_id' => 3977],
                ['name' => 'Craigsville', 'state_id' => 3977],
                ['name' => 'Richwood', 'state_id' => 3977],
                ['name' => 'Birch River', 'state_id' => 3977],
                ['name' => 'Summersville', 'state_id' => 3977],
                ['name' => 'Belva', 'state_id' => 3977],
                ['name' => 'Calvin', 'state_id' => 3977],
                ['name' => 'Canvas', 'state_id' => 3977],
                ['name' => 'Drennen', 'state_id' => 3977],
                ['name' => 'Gilboa', 'state_id' => 3977],
                ['name' => 'Keslers Cross Lanes', 'state_id' => 3977],
                ['name' => 'Leivasy', 'state_id' => 3977],
                ['name' => 'Mount Lookout', 'state_id' => 3977],
                ['name' => 'Mount Nebo', 'state_id' => 3977],
                ['name' => 'Nettie', 'state_id' => 3977],
                ['name' => 'Pool', 'state_id' => 3977],
                ['name' => 'Swiss', 'state_id' => 3977],
                ['name' => 'Tioga', 'state_id' => 3977],
                ['name' => 'Wheeling', 'state_id' => 3977],
                ['name' => 'Triadelphia', 'state_id' => 3977],
                ['name' => 'Valley Grove', 'state_id' => 3977],
                ['name' => 'West Liberty', 'state_id' => 3977],
                ['name' => 'Brandywine', 'state_id' => 3977],
                ['name' => 'Circleville', 'state_id' => 3977],
                ['name' => 'Franklin', 'state_id' => 3977],
                ['name' => 'Riverton', 'state_id' => 3977],
                ['name' => 'Sugar Grove', 'state_id' => 3977],
                ['name' => 'Upper Tract', 'state_id' => 3977],
                ['name' => 'Seneca Rocks', 'state_id' => 3977],
                ['name' => 'Onego', 'state_id' => 3977],
                ['name' => 'Belmont', 'state_id' => 3977],
                ['name' => 'Saint Marys', 'state_id' => 3977],
                ['name' => 'Arbovale', 'state_id' => 3977],
                ['name' => 'Bartow', 'state_id' => 3977],
                ['name' => 'Buckeye', 'state_id' => 3977],
                ['name' => 'Cass', 'state_id' => 3977],
                ['name' => 'Dunmore', 'state_id' => 3977],
                ['name' => 'Green Bank', 'state_id' => 3977],
                ['name' => 'Hillsboro', 'state_id' => 3977],
                ['name' => 'Marlinton', 'state_id' => 3977],
                ['name' => 'Snowshoe', 'state_id' => 3977],
                ['name' => 'Durbin', 'state_id' => 3977],
                ['name' => 'Slatyfork', 'state_id' => 3977],
                ['name' => 'Independence', 'state_id' => 3977],
                ['name' => 'Newburg', 'state_id' => 3977],
                ['name' => 'Rowlesburg', 'state_id' => 3977],
                ['name' => 'Tunnelton', 'state_id' => 3977],
                ['name' => 'Albright', 'state_id' => 3977],
                ['name' => 'Arthurdale', 'state_id' => 3977],
                ['name' => 'Bretz', 'state_id' => 3977],
                ['name' => 'Bruceton Mills', 'state_id' => 3977],
                ['name' => 'Kingwood', 'state_id' => 3977],
                ['name' => 'Masontown', 'state_id' => 3977],
                ['name' => 'Reedsville', 'state_id' => 3977],
                ['name' => 'Aurora', 'state_id' => 3977],
                ['name' => 'Eglon', 'state_id' => 3977],
                ['name' => 'Terra Alta', 'state_id' => 3977],
                ['name' => 'Bancroft', 'state_id' => 3977],
                ['name' => 'Buffalo', 'state_id' => 3977],
                ['name' => 'Eleanor', 'state_id' => 3977],
                ['name' => 'Fraziers Bottom', 'state_id' => 3977],
                ['name' => 'Hometown', 'state_id' => 3977],
                ['name' => 'Liberty', 'state_id' => 3977],
                ['name' => 'Poca', 'state_id' => 3977],
                ['name' => 'Red House', 'state_id' => 3977],
                ['name' => 'Winfield', 'state_id' => 3977],
                ['name' => 'Hurricane', 'state_id' => 3977],
                ['name' => 'Scott Depot', 'state_id' => 3977],
                ['name' => 'Teays', 'state_id' => 3977],
                ['name' => 'Arnett', 'state_id' => 3977],
                ['name' => 'Artie', 'state_id' => 3977],
                ['name' => 'Clear Creek', 'state_id' => 3977],
                ['name' => 'Colcord', 'state_id' => 3977],
                ['name' => 'Dorothy', 'state_id' => 3977],
                ['name' => 'Dry Creek', 'state_id' => 3977],
                ['name' => 'Naoma', 'state_id' => 3977],
                ['name' => 'Rock Creek', 'state_id' => 3977],
                ['name' => 'Saxon', 'state_id' => 3977],
                ['name' => 'Beckley', 'state_id' => 3977],
                ['name' => 'Beaver', 'state_id' => 3977],
                ['name' => 'Bolt', 'state_id' => 3977],
                ['name' => 'Bradley', 'state_id' => 3977],
                ['name' => 'Coal City', 'state_id' => 3977],
                ['name' => 'Cool Ridge', 'state_id' => 3977],
                ['name' => 'Crab Orchard', 'state_id' => 3977],
                ['name' => 'Daniels', 'state_id' => 3977],
                ['name' => 'Eccles', 'state_id' => 3977],
                ['name' => 'Fairdale', 'state_id' => 3977],
                ['name' => 'Ghent', 'state_id' => 3977],
                ['name' => 'Glen Daniel', 'state_id' => 3977],
                ['name' => 'Glen White', 'state_id' => 3977],
                ['name' => 'Harper', 'state_id' => 3977],
                ['name' => 'Helen', 'state_id' => 3977],
                ['name' => 'Josephine', 'state_id' => 3977],
                ['name' => 'Lanark', 'state_id' => 3977],
                ['name' => 'Lester', 'state_id' => 3977],
                ['name' => 'Mabscott', 'state_id' => 3977],
                ['name' => 'Mac Arthur', 'state_id' => 3977],
                ['name' => 'Midway', 'state_id' => 3977],
                ['name' => 'Odd', 'state_id' => 3977],
                ['name' => 'Piney View', 'state_id' => 3977],
                ['name' => 'Princewick', 'state_id' => 3977],
                ['name' => 'Prosperity', 'state_id' => 3977],
                ['name' => 'Raleigh', 'state_id' => 3977],
                ['name' => 'Rhodell', 'state_id' => 3977],
                ['name' => 'Shady Spring', 'state_id' => 3977],
                ['name' => 'Skelton', 'state_id' => 3977],
                ['name' => 'Slab Fork', 'state_id' => 3977],
                ['name' => 'Sophia', 'state_id' => 3977],
                ['name' => 'Stanaford', 'state_id' => 3977],
                ['name' => 'Surveyor', 'state_id' => 3977],
                ['name' => 'White Oak', 'state_id' => 3977],
                ['name' => 'Helvetia', 'state_id' => 3977],
                ['name' => 'Pickens', 'state_id' => 3977],
                ['name' => 'Elkins', 'state_id' => 3977],
                ['name' => 'Beverly', 'state_id' => 3977],
                ['name' => 'Bowden', 'state_id' => 3977],
                ['name' => 'Coalton', 'state_id' => 3977],
                ['name' => 'Dailey', 'state_id' => 3977],
                ['name' => 'Dryfork', 'state_id' => 3977],
                ['name' => 'Ellamore', 'state_id' => 3977],
                ['name' => 'Glady', 'state_id' => 3977],
                ['name' => 'Harman', 'state_id' => 3977],
                ['name' => 'Huttonsville', 'state_id' => 3977],
                ['name' => 'Kerens', 'state_id' => 3977],
                ['name' => 'Mabie', 'state_id' => 3977],
                ['name' => 'Mill Creek', 'state_id' => 3977],
                ['name' => 'Monterville', 'state_id' => 3977],
                ['name' => 'Montrose', 'state_id' => 3977],
                ['name' => 'Norton', 'state_id' => 3977],
                ['name' => 'Valley Bend', 'state_id' => 3977],
                ['name' => 'Valley Head', 'state_id' => 3977],
                ['name' => 'Whitmer', 'state_id' => 3977],
                ['name' => 'Macfarlan', 'state_id' => 3977],
                ['name' => 'Petroleum', 'state_id' => 3977],
                ['name' => 'Smithville', 'state_id' => 3977],
                ['name' => 'Auburn', 'state_id' => 3977],
                ['name' => 'Berea', 'state_id' => 3977],
                ['name' => 'Cairo', 'state_id' => 3977],
                ['name' => 'Ellenboro', 'state_id' => 3977],
                ['name' => 'Harrisville', 'state_id' => 3977],
                ['name' => 'Pennsboro', 'state_id' => 3977],
                ['name' => 'Pullman', 'state_id' => 3977],
                ['name' => 'Amma', 'state_id' => 3977],
                ['name' => 'Gandeeville', 'state_id' => 3977],
                ['name' => 'Left Hand', 'state_id' => 3977],
                ['name' => 'Looneyville', 'state_id' => 3977],
                ['name' => 'Newton', 'state_id' => 3977],
                ['name' => 'Reedy', 'state_id' => 3977],
                ['name' => 'Spencer', 'state_id' => 3977],
                ['name' => 'Walton', 'state_id' => 3977],
                ['name' => 'Forest Hill', 'state_id' => 3977],
                ['name' => 'Pence Springs', 'state_id' => 3977],
                ['name' => 'Talcott', 'state_id' => 3977],
                ['name' => 'Hinton', 'state_id' => 3977],
                ['name' => 'Green Sulphur Springs', 'state_id' => 3977],
                ['name' => 'Jumping Branch', 'state_id' => 3977],
                ['name' => 'Meadow Creek', 'state_id' => 3977],
                ['name' => 'Nimitz', 'state_id' => 3977],
                ['name' => 'Pipestem', 'state_id' => 3977],
                ['name' => 'Sandstone', 'state_id' => 3977],
                ['name' => 'Flemington', 'state_id' => 3977],
                ['name' => 'Grafton', 'state_id' => 3977],
                ['name' => 'Rosemont', 'state_id' => 3977],
                ['name' => 'Simpson', 'state_id' => 3977],
                ['name' => 'Thornton', 'state_id' => 3977],
                ['name' => 'Davis', 'state_id' => 3977],
                ['name' => 'Hambleton', 'state_id' => 3977],
                ['name' => 'Hendricks', 'state_id' => 3977],
                ['name' => 'Parsons', 'state_id' => 3977],
                ['name' => 'Red Creek', 'state_id' => 3977],
                ['name' => 'Thomas', 'state_id' => 3977],
                ['name' => 'Friendly', 'state_id' => 3977],
                ['name' => 'Middlebourne', 'state_id' => 3977],
                ['name' => 'Sistersville', 'state_id' => 3977],
                ['name' => 'Alma', 'state_id' => 3977],
                ['name' => 'Shirley', 'state_id' => 3977],
                ['name' => 'Buckhannon', 'state_id' => 3977],
                ['name' => 'Adrian', 'state_id' => 3977],
                ['name' => 'Cleveland', 'state_id' => 3977],
                ['name' => 'French Creek', 'state_id' => 3977],
                ['name' => 'Frenchton', 'state_id' => 3977],
                ['name' => 'Kanawha Head', 'state_id' => 3977],
                ['name' => 'Lorentz', 'state_id' => 3977],
                ['name' => 'Rock Cave', 'state_id' => 3977],
                ['name' => 'Selbyville', 'state_id' => 3977],
                ['name' => 'Tallmansville', 'state_id' => 3977],
                ['name' => 'Ceredo', 'state_id' => 3977],
                ['name' => 'Dunlow', 'state_id' => 3977],
                ['name' => 'East Lynn', 'state_id' => 3977],
                ['name' => 'Fort Gay', 'state_id' => 3977],
                ['name' => 'Genoa', 'state_id' => 3977],
                ['name' => 'Kenova', 'state_id' => 3977],
                ['name' => 'Kiahsville', 'state_id' => 3977],
                ['name' => 'Lavalette', 'state_id' => 3977],
                ['name' => 'Prichard', 'state_id' => 3977],
                ['name' => 'Shoals', 'state_id' => 3977],
                ['name' => 'Wayne', 'state_id' => 3977],
                ['name' => 'Crum', 'state_id' => 3977],
                ['name' => 'Wilsondale', 'state_id' => 3977],
                ['name' => 'Erbacon', 'state_id' => 3977],
                ['name' => 'Cowen', 'state_id' => 3977],
                ['name' => 'Camden On Gauley', 'state_id' => 3977],
                ['name' => 'Diana', 'state_id' => 3977],
                ['name' => 'Hacker Valley', 'state_id' => 3977],
                ['name' => 'Upperglade', 'state_id' => 3977],
                ['name' => 'Webster Springs', 'state_id' => 3977],
                ['name' => 'Bergoo', 'state_id' => 3977],
                ['name' => 'New Martinsville', 'state_id' => 3977],
                ['name' => 'Paden City', 'state_id' => 3977],
                ['name' => 'Porters Falls', 'state_id' => 3977],
                ['name' => 'Reader', 'state_id' => 3977],
                ['name' => 'Folsom', 'state_id' => 3977],
                ['name' => 'Jacksonburg', 'state_id' => 3977],
                ['name' => 'Pine Grove', 'state_id' => 3977],
                ['name' => 'Smithfield', 'state_id' => 3977],
                ['name' => 'Big Run', 'state_id' => 3977],
                ['name' => 'Burton', 'state_id' => 3977],
                ['name' => 'Hundred', 'state_id' => 3977],
                ['name' => 'Littleton', 'state_id' => 3977],
                ['name' => 'Brohard', 'state_id' => 3977],
                ['name' => 'Creston', 'state_id' => 3977],
                ['name' => 'Elizabeth', 'state_id' => 3977],
                ['name' => 'Munday', 'state_id' => 3977],
                ['name' => 'Palestine', 'state_id' => 3977],
                ['name' => 'Parkersburg', 'state_id' => 3977],
                ['name' => 'Vienna', 'state_id' => 3977],
                ['name' => 'Mineral Wells', 'state_id' => 3977],
                ['name' => 'Belleville', 'state_id' => 3977],
                ['name' => 'Davisville', 'state_id' => 3977],
                ['name' => 'Rockport', 'state_id' => 3977],
                ['name' => 'Walker', 'state_id' => 3977],
                ['name' => 'Washington', 'state_id' => 3977],
                ['name' => 'Waverly', 'state_id' => 3977],
                ['name' => 'Williamstown', 'state_id' => 3977],
                ['name' => 'Bud', 'state_id' => 3977],
                ['name' => 'Covel', 'state_id' => 3977],
                ['name' => 'Herndon', 'state_id' => 3977],
                ['name' => 'Brenton', 'state_id' => 3977],
                ['name' => 'Clear Fork', 'state_id' => 3977],
                ['name' => 'Coal Mountain', 'state_id' => 3977],
                ['name' => 'Cyclone', 'state_id' => 3977],
                ['name' => 'Fanrock', 'state_id' => 3977],
                ['name' => 'Hanover', 'state_id' => 3977],
                ['name' => 'Ikes Fork', 'state_id' => 3977],
                ['name' => 'Itmann', 'state_id' => 3977],
                ['name' => 'Jesse', 'state_id' => 3977],
                ['name' => 'Kopperston', 'state_id' => 3977],
                ['name' => 'Lynco', 'state_id' => 3977],
                ['name' => 'Marianna', 'state_id' => 3977],
                ['name' => 'Matheny', 'state_id' => 3977],
                ['name' => 'New Richmond', 'state_id' => 3977],
                ['name' => 'North Spring', 'state_id' => 3977],
                ['name' => 'Oceana', 'state_id' => 3977],
                ['name' => 'Pineville', 'state_id' => 3977],
                ['name' => 'Rock View', 'state_id' => 3977],
                ['name' => 'Simon', 'state_id' => 3977],
                ['name' => 'Wyoming', 'state_id' => 3977],
                ['name' => 'Allen Junction', 'state_id' => 3977],
                ['name' => 'Amigo', 'state_id' => 3977],
                ['name' => 'Corinne', 'state_id' => 3977],
                ['name' => 'Glen Fork', 'state_id' => 3977],
                ['name' => 'Glen Rogers', 'state_id' => 3977],
                ['name' => 'Maben', 'state_id' => 3977],
                ['name' => 'Mc Graws', 'state_id' => 3977],
                ['name' => 'Saulsville', 'state_id' => 3977],
                ['name' => 'Mullens', 'state_id' => 3977],
                ['name' => 'Ravencliff', 'state_id' => 3977],
                ['name' => 'Sabine', 'state_id' => 3977],
                ['name' => 'Stephenson', 'state_id' => 3977],
                ['name' => 'Wyco', 'state_id' => 3977]
            ]);
        }
    }
}
