<?php

use Illuminate\Database\Seeder;

class state26TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MS - Mississippi.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Natchez', 'state_id' => 3948],
                ['name' => 'Sibley', 'state_id' => 3948],
                ['name' => 'Washington', 'state_id' => 3948],
                ['name' => 'Corinth', 'state_id' => 3948],
                ['name' => 'Glen', 'state_id' => 3948],
                ['name' => 'Rienzi', 'state_id' => 3948],
                ['name' => 'Crosby', 'state_id' => 3948],
                ['name' => 'Gloster', 'state_id' => 3948],
                ['name' => 'Liberty', 'state_id' => 3948],
                ['name' => 'Smithdale', 'state_id' => 3948],
                ['name' => 'Ethel', 'state_id' => 3948],
                ['name' => 'Kosciusko', 'state_id' => 3948],
                ['name' => 'Mc Adams', 'state_id' => 3948],
                ['name' => 'Mc Cool', 'state_id' => 3948],
                ['name' => 'Sallis', 'state_id' => 3948],
                ['name' => 'Ashland', 'state_id' => 3948],
                ['name' => 'Hickory Flat', 'state_id' => 3948],
                ['name' => 'Michigan City', 'state_id' => 3948],
                ['name' => 'Alligator', 'state_id' => 3948],
                ['name' => 'Benoit', 'state_id' => 3948],
                ['name' => 'Beulah', 'state_id' => 3948],
                ['name' => 'Boyle', 'state_id' => 3948],
                ['name' => 'Cleveland', 'state_id' => 3948],
                ['name' => 'Duncan', 'state_id' => 3948],
                ['name' => 'Gunnison', 'state_id' => 3948],
                ['name' => 'Merigold', 'state_id' => 3948],
                ['name' => 'Mound Bayou', 'state_id' => 3948],
                ['name' => 'Pace', 'state_id' => 3948],
                ['name' => 'Rosedale', 'state_id' => 3948],
                ['name' => 'Scott', 'state_id' => 3948],
                ['name' => 'Shaw', 'state_id' => 3948],
                ['name' => 'Shelby', 'state_id' => 3948],
                ['name' => 'Winstonville', 'state_id' => 3948],
                ['name' => 'Derma', 'state_id' => 3948],
                ['name' => 'Vardaman', 'state_id' => 3948],
                ['name' => 'Banner', 'state_id' => 3948],
                ['name' => 'Big Creek', 'state_id' => 3948],
                ['name' => 'Bruce', 'state_id' => 3948],
                ['name' => 'Calhoun City', 'state_id' => 3948],
                ['name' => 'Pittsboro', 'state_id' => 3948],
                ['name' => 'Slate Spring', 'state_id' => 3948],
                ['name' => 'Mantee', 'state_id' => 3948],
                ['name' => 'Carrollton', 'state_id' => 3948],
                ['name' => 'Coila', 'state_id' => 3948],
                ['name' => 'Mc Carley', 'state_id' => 3948],
                ['name' => 'North Carrollton', 'state_id' => 3948],
                ['name' => 'Sidon', 'state_id' => 3948],
                ['name' => 'Vaiden', 'state_id' => 3948],
                ['name' => 'Houlka', 'state_id' => 3948],
                ['name' => 'Houston', 'state_id' => 3948],
                ['name' => 'Okolona', 'state_id' => 3948],
                ['name' => 'Trebloc', 'state_id' => 3948],
                ['name' => 'Van Vleet', 'state_id' => 3948],
                ['name' => 'Woodland', 'state_id' => 3948],
                ['name' => 'Ackerman', 'state_id' => 3948],
                ['name' => 'French Camp', 'state_id' => 3948],
                ['name' => 'Weir', 'state_id' => 3948],
                ['name' => 'Hermanville', 'state_id' => 3948],
                ['name' => 'Pattison', 'state_id' => 3948],
                ['name' => 'Port Gibson', 'state_id' => 3948],
                ['name' => 'Enterprise', 'state_id' => 3948],
                ['name' => 'Pachuta', 'state_id' => 3948],
                ['name' => 'Quitman', 'state_id' => 3948],
                ['name' => 'Shubuta', 'state_id' => 3948],
                ['name' => 'Stonewall', 'state_id' => 3948],
                ['name' => 'Cedarbluff', 'state_id' => 3948],
                ['name' => 'Montpelier', 'state_id' => 3948],
                ['name' => 'Pheba', 'state_id' => 3948],
                ['name' => 'West Point', 'state_id' => 3948],
                ['name' => 'Clarksdale', 'state_id' => 3948],
                ['name' => 'Coahoma', 'state_id' => 3948],
                ['name' => 'Farrell', 'state_id' => 3948],
                ['name' => 'Friars Point', 'state_id' => 3948],
                ['name' => 'Jonestown', 'state_id' => 3948],
                ['name' => 'Lula', 'state_id' => 3948],
                ['name' => 'Lyon', 'state_id' => 3948],
                ['name' => 'Sherard', 'state_id' => 3948],
                ['name' => 'Dublin', 'state_id' => 3948],
                ['name' => 'Rena Lara', 'state_id' => 3948],
                ['name' => 'Crystal Springs', 'state_id' => 3948],
                ['name' => 'Gallman', 'state_id' => 3948],
                ['name' => 'Georgetown', 'state_id' => 3948],
                ['name' => 'Hazlehurst', 'state_id' => 3948],
                ['name' => 'Wesson', 'state_id' => 3948],
                ['name' => 'Mount Olive', 'state_id' => 3948],
                ['name' => 'Collins', 'state_id' => 3948],
                ['name' => 'Seminary', 'state_id' => 3948],
                ['name' => 'Hernando', 'state_id' => 3948],
                ['name' => 'Horn Lake', 'state_id' => 3948],
                ['name' => 'Lake Cormorant', 'state_id' => 3948],
                ['name' => 'Nesbit', 'state_id' => 3948],
                ['name' => 'Olive Branch', 'state_id' => 3948],
                ['name' => 'Southaven', 'state_id' => 3948],
                ['name' => 'Walls', 'state_id' => 3948],
                ['name' => 'Hattiesburg', 'state_id' => 3948],
                ['name' => 'Brooklyn', 'state_id' => 3948],
                ['name' => 'Petal', 'state_id' => 3948],
                ['name' => 'Bude', 'state_id' => 3948],
                ['name' => 'Mc Call Creek', 'state_id' => 3948],
                ['name' => 'Meadville', 'state_id' => 3948],
                ['name' => 'Roxie', 'state_id' => 3948],
                ['name' => 'Lucedale', 'state_id' => 3948],
                ['name' => 'State Line', 'state_id' => 3948],
                ['name' => 'Leakesville', 'state_id' => 3948],
                ['name' => 'Mc Lain', 'state_id' => 3948],
                ['name' => 'Neely', 'state_id' => 3948],
                ['name' => 'Grenada', 'state_id' => 3948],
                ['name' => 'Elliott', 'state_id' => 3948],
                ['name' => 'Gore Springs', 'state_id' => 3948],
                ['name' => 'Holcomb', 'state_id' => 3948],
                ['name' => 'Tie Plant', 'state_id' => 3948],
                ['name' => 'Bay Saint Louis', 'state_id' => 3948],
                ['name' => 'Stennis Space Center', 'state_id' => 3948],
                ['name' => 'Diamondhead', 'state_id' => 3948],
                ['name' => 'Kiln', 'state_id' => 3948],
                ['name' => 'Lakeshore', 'state_id' => 3948],
                ['name' => 'Pearlington', 'state_id' => 3948],
                ['name' => 'Waveland', 'state_id' => 3948],
                ['name' => 'Gulfport', 'state_id' => 3948],
                ['name' => 'Biloxi', 'state_id' => 3948],
                ['name' => 'Diberville', 'state_id' => 3948],
                ['name' => 'Long Beach', 'state_id' => 3948],
                ['name' => 'Pass Christian', 'state_id' => 3948],
                ['name' => 'Saucier', 'state_id' => 3948],
                ['name' => 'Bolton', 'state_id' => 3948],
                ['name' => 'Clinton', 'state_id' => 3948],
                ['name' => 'Edwards', 'state_id' => 3948],
                ['name' => 'Raymond', 'state_id' => 3948],
                ['name' => 'Terry', 'state_id' => 3948],
                ['name' => 'Tougaloo', 'state_id' => 3948],
                ['name' => 'Utica', 'state_id' => 3948],
                ['name' => 'Jackson', 'state_id' => 3948],
                ['name' => 'Byram', 'state_id' => 3948],
                ['name' => 'Cruger', 'state_id' => 3948],
                ['name' => 'Durant', 'state_id' => 3948],
                ['name' => 'Goodman', 'state_id' => 3948],
                ['name' => 'Lexington', 'state_id' => 3948],
                ['name' => 'Pickens', 'state_id' => 3948],
                ['name' => 'Tchula', 'state_id' => 3948],
                ['name' => 'West', 'state_id' => 3948],
                ['name' => 'Isola', 'state_id' => 3948],
                ['name' => 'Belzoni', 'state_id' => 3948],
                ['name' => 'Louise', 'state_id' => 3948],
                ['name' => 'Midnight', 'state_id' => 3948],
                ['name' => 'Silver City', 'state_id' => 3948],
                ['name' => 'Grace', 'state_id' => 3948],
                ['name' => 'Mayersville', 'state_id' => 3948],
                ['name' => 'Valley Park', 'state_id' => 3948],
                ['name' => 'Fulton', 'state_id' => 3948],
                ['name' => 'Golden', 'state_id' => 3948],
                ['name' => 'Mantachie', 'state_id' => 3948],
                ['name' => 'Nettleton', 'state_id' => 3948],
                ['name' => 'Tremont', 'state_id' => 3948],
                ['name' => 'Escatawpa', 'state_id' => 3948],
                ['name' => 'Gautier', 'state_id' => 3948],
                ['name' => 'Hurley', 'state_id' => 3948],
                ['name' => 'Moss Point', 'state_id' => 3948],
                ['name' => 'Ocean Springs', 'state_id' => 3948],
                ['name' => 'Vancleave', 'state_id' => 3948],
                ['name' => 'Pascagoula', 'state_id' => 3948],
                ['name' => 'Louin', 'state_id' => 3948],
                ['name' => 'Paulding', 'state_id' => 3948],
                ['name' => 'Rose Hill', 'state_id' => 3948],
                ['name' => 'Vossburg', 'state_id' => 3948],
                ['name' => 'Bay Springs', 'state_id' => 3948],
                ['name' => 'Heidelberg', 'state_id' => 3948],
                ['name' => 'Moss', 'state_id' => 3948],
                ['name' => 'Stringer', 'state_id' => 3948],
                ['name' => 'Fayette', 'state_id' => 3948],
                ['name' => 'Harriston', 'state_id' => 3948],
                ['name' => 'Lorman', 'state_id' => 3948],
                ['name' => 'Union Church', 'state_id' => 3948],
                ['name' => 'Bassfield', 'state_id' => 3948],
                ['name' => 'Carson', 'state_id' => 3948],
                ['name' => 'Prentiss', 'state_id' => 3948],
                ['name' => 'Eastabuchie', 'state_id' => 3948],
                ['name' => 'Ellisville', 'state_id' => 3948],
                ['name' => 'Laurel', 'state_id' => 3948],
                ['name' => 'Moselle', 'state_id' => 3948],
                ['name' => 'Sandersville', 'state_id' => 3948],
                ['name' => 'Soso', 'state_id' => 3948],
                ['name' => 'De Kalb', 'state_id' => 3948],
                ['name' => 'Porterville', 'state_id' => 3948],
                ['name' => 'Preston', 'state_id' => 3948],
                ['name' => 'Scooba', 'state_id' => 3948],
                ['name' => 'Abbeville', 'state_id' => 3948],
                ['name' => 'Oxford', 'state_id' => 3948],
                ['name' => 'Taylor', 'state_id' => 3948],
                ['name' => 'Tula', 'state_id' => 3948],
                ['name' => 'University', 'state_id' => 3948],
                ['name' => 'Waterford', 'state_id' => 3948],
                ['name' => 'Toccopola', 'state_id' => 3948],
                ['name' => 'Paris', 'state_id' => 3948],
                ['name' => 'Lumberton', 'state_id' => 3948],
                ['name' => 'Purvis', 'state_id' => 3948],
                ['name' => 'Sumrall', 'state_id' => 3948],
                ['name' => 'Meridian', 'state_id' => 3948],
                ['name' => 'Bailey', 'state_id' => 3948],
                ['name' => 'Collinsville', 'state_id' => 3948],
                ['name' => 'Daleville', 'state_id' => 3948],
                ['name' => 'Lauderdale', 'state_id' => 3948],
                ['name' => 'Marion', 'state_id' => 3948],
                ['name' => 'Toomsuba', 'state_id' => 3948],
                ['name' => 'Newhebron', 'state_id' => 3948],
                ['name' => 'Jayess', 'state_id' => 3948],
                ['name' => 'Monticello', 'state_id' => 3948],
                ['name' => 'Oak Vale', 'state_id' => 3948],
                ['name' => 'Silver Creek', 'state_id' => 3948],
                ['name' => 'Sontag', 'state_id' => 3948],
                ['name' => 'Carthage', 'state_id' => 3948],
                ['name' => 'Lena', 'state_id' => 3948],
                ['name' => 'Madden', 'state_id' => 3948],
                ['name' => 'Thomastown', 'state_id' => 3948],
                ['name' => 'Walnut Grove', 'state_id' => 3948],
                ['name' => 'Tupelo', 'state_id' => 3948],
                ['name' => 'Baldwyn', 'state_id' => 3948],
                ['name' => 'Belden', 'state_id' => 3948],
                ['name' => 'Guntown', 'state_id' => 3948],
                ['name' => 'Mooreville', 'state_id' => 3948],
                ['name' => 'Plantersville', 'state_id' => 3948],
                ['name' => 'Saltillo', 'state_id' => 3948],
                ['name' => 'Shannon', 'state_id' => 3948],
                ['name' => 'Verona', 'state_id' => 3948],
                ['name' => 'Greenwood', 'state_id' => 3948],
                ['name' => 'Itta Bena', 'state_id' => 3948],
                ['name' => 'Minter City', 'state_id' => 3948],
                ['name' => 'Money', 'state_id' => 3948],
                ['name' => 'Morgan City', 'state_id' => 3948],
                ['name' => 'Schlater', 'state_id' => 3948],
                ['name' => 'Swiftown', 'state_id' => 3948],
                ['name' => 'Brookhaven', 'state_id' => 3948],
                ['name' => 'Bogue Chitto', 'state_id' => 3948],
                ['name' => 'Ruth', 'state_id' => 3948],
                ['name' => 'Columbus', 'state_id' => 3948],
                ['name' => 'Artesia', 'state_id' => 3948],
                ['name' => 'Crawford', 'state_id' => 3948],
                ['name' => 'Mayhew', 'state_id' => 3948],
                ['name' => 'Steens', 'state_id' => 3948],
                ['name' => 'Camden', 'state_id' => 3948],
                ['name' => 'Canton', 'state_id' => 3948],
                ['name' => 'Flora', 'state_id' => 3948],
                ['name' => 'Madison', 'state_id' => 3948],
                ['name' => 'Ridgeland', 'state_id' => 3948],
                ['name' => 'Sharon', 'state_id' => 3948],
                ['name' => 'Columbia', 'state_id' => 3948],
                ['name' => 'Sandy Hook', 'state_id' => 3948],
                ['name' => 'Foxworth', 'state_id' => 3948],
                ['name' => 'Kokomo', 'state_id' => 3948],
                ['name' => 'Byhalia', 'state_id' => 3948],
                ['name' => 'Holly Springs', 'state_id' => 3948],
                ['name' => 'Lamar', 'state_id' => 3948],
                ['name' => 'Mount Pleasant', 'state_id' => 3948],
                ['name' => 'Potts Camp', 'state_id' => 3948],
                ['name' => 'Red Banks', 'state_id' => 3948],
                ['name' => 'Victoria', 'state_id' => 3948],
                ['name' => 'Amory', 'state_id' => 3948],
                ['name' => 'Becker', 'state_id' => 3948],
                ['name' => 'Gattman', 'state_id' => 3948],
                ['name' => 'Greenwood Springs', 'state_id' => 3948],
                ['name' => 'Smithville', 'state_id' => 3948],
                ['name' => 'Aberdeen', 'state_id' => 3948],
                ['name' => 'Caledonia', 'state_id' => 3948],
                ['name' => 'Hamilton', 'state_id' => 3948],
                ['name' => 'Prairie', 'state_id' => 3948],
                ['name' => 'Duck Hill', 'state_id' => 3948],
                ['name' => 'Winona', 'state_id' => 3948],
                ['name' => 'Kilmichael', 'state_id' => 3948],
                ['name' => 'Stewart', 'state_id' => 3948],
                ['name' => 'Philadelphia', 'state_id' => 3948],
                ['name' => 'Union', 'state_id' => 3948],
                ['name' => 'Conehatta', 'state_id' => 3948],
                ['name' => 'Chunky', 'state_id' => 3948],
                ['name' => 'Decatur', 'state_id' => 3948],
                ['name' => 'Hickory', 'state_id' => 3948],
                ['name' => 'Lawrence', 'state_id' => 3948],
                ['name' => 'Little Rock', 'state_id' => 3948],
                ['name' => 'Newton', 'state_id' => 3948],
                ['name' => 'Macon', 'state_id' => 3948],
                ['name' => 'Shuqualak', 'state_id' => 3948],
                ['name' => 'Brooksville', 'state_id' => 3948],
                ['name' => 'Starkville', 'state_id' => 3948],
                ['name' => 'Mississippi State', 'state_id' => 3948],
                ['name' => 'Sturgis', 'state_id' => 3948],
                ['name' => 'Batesville', 'state_id' => 3948],
                ['name' => 'Como', 'state_id' => 3948],
                ['name' => 'Courtland', 'state_id' => 3948],
                ['name' => 'Crenshaw', 'state_id' => 3948],
                ['name' => 'Pope', 'state_id' => 3948],
                ['name' => 'Sarah', 'state_id' => 3948],
                ['name' => 'Sardis', 'state_id' => 3948],
                ['name' => 'Carriere', 'state_id' => 3948],
                ['name' => 'Mc Neill', 'state_id' => 3948],
                ['name' => 'Nicholson', 'state_id' => 3948],
                ['name' => 'Picayune', 'state_id' => 3948],
                ['name' => 'Poplarville', 'state_id' => 3948],
                ['name' => 'Beaumont', 'state_id' => 3948],
                ['name' => 'New Augusta', 'state_id' => 3948],
                ['name' => 'Ovett', 'state_id' => 3948],
                ['name' => 'Richton', 'state_id' => 3948],
                ['name' => 'Chatawa', 'state_id' => 3948],
                ['name' => 'Fernwood', 'state_id' => 3948],
                ['name' => 'Mccomb', 'state_id' => 3948],
                ['name' => 'Magnolia', 'state_id' => 3948],
                ['name' => 'Osyka', 'state_id' => 3948],
                ['name' => 'Summit', 'state_id' => 3948],
                ['name' => 'Algoma', 'state_id' => 3948],
                ['name' => 'Ecru', 'state_id' => 3948],
                ['name' => 'Pontotoc', 'state_id' => 3948],
                ['name' => 'Randolph', 'state_id' => 3948],
                ['name' => 'Sherman', 'state_id' => 3948],
                ['name' => 'Thaxton', 'state_id' => 3948],
                ['name' => 'Booneville', 'state_id' => 3948],
                ['name' => 'Marietta', 'state_id' => 3948],
                ['name' => 'New Site', 'state_id' => 3948],
                ['name' => 'Wheeler', 'state_id' => 3948],
                ['name' => 'Belen', 'state_id' => 3948],
                ['name' => 'Crowder', 'state_id' => 3948],
                ['name' => 'Darling', 'state_id' => 3948],
                ['name' => 'Falcon', 'state_id' => 3948],
                ['name' => 'Lambert', 'state_id' => 3948],
                ['name' => 'Marks', 'state_id' => 3948],
                ['name' => 'Vance', 'state_id' => 3948],
                ['name' => 'Brandon', 'state_id' => 3948],
                ['name' => 'Florence', 'state_id' => 3948],
                ['name' => 'Pelahatchie', 'state_id' => 3948],
                ['name' => 'Piney Woods', 'state_id' => 3948],
                ['name' => 'Puckett', 'state_id' => 3948],
                ['name' => 'Sandhill', 'state_id' => 3948],
                ['name' => 'Star', 'state_id' => 3948],
                ['name' => 'Whitfield', 'state_id' => 3948],
                ['name' => 'Pearl', 'state_id' => 3948],
                ['name' => 'Richland', 'state_id' => 3948],
                ['name' => 'Flowood', 'state_id' => 3948],
                ['name' => 'Forest', 'state_id' => 3948],
                ['name' => 'Harperville', 'state_id' => 3948],
                ['name' => 'Hillsboro', 'state_id' => 3948],
                ['name' => 'Lake', 'state_id' => 3948],
                ['name' => 'Ludlow', 'state_id' => 3948],
                ['name' => 'Morton', 'state_id' => 3948],
                ['name' => 'Pulaski', 'state_id' => 3948],
                ['name' => 'Sebastopol', 'state_id' => 3948],
                ['name' => 'Anguilla', 'state_id' => 3948],
                ['name' => 'Panther Burn', 'state_id' => 3948],
                ['name' => 'Cary', 'state_id' => 3948],
                ['name' => 'Delta City', 'state_id' => 3948],
                ['name' => 'Rolling Fork', 'state_id' => 3948],
                ['name' => 'Braxton', 'state_id' => 3948],
                ['name' => 'D Lo', 'state_id' => 3948],
                ['name' => 'Harrisville', 'state_id' => 3948],
                ['name' => 'Magee', 'state_id' => 3948],
                ['name' => 'Mendenhall', 'state_id' => 3948],
                ['name' => 'Pinola', 'state_id' => 3948],
                ['name' => 'Mize', 'state_id' => 3948],
                ['name' => 'Raleigh', 'state_id' => 3948],
                ['name' => 'Taylorsville', 'state_id' => 3948],
                ['name' => 'Mc Henry', 'state_id' => 3948],
                ['name' => 'Perkinston', 'state_id' => 3948],
                ['name' => 'Wiggins', 'state_id' => 3948],
                ['name' => 'Doddsville', 'state_id' => 3948],
                ['name' => 'Drew', 'state_id' => 3948],
                ['name' => 'Parchman', 'state_id' => 3948],
                ['name' => 'Indianola', 'state_id' => 3948],
                ['name' => 'Inverness', 'state_id' => 3948],
                ['name' => 'Moorhead', 'state_id' => 3948],
                ['name' => 'Rome', 'state_id' => 3948],
                ['name' => 'Ruleville', 'state_id' => 3948],
                ['name' => 'Sunflower', 'state_id' => 3948],
                ['name' => 'Cascilla', 'state_id' => 3948],
                ['name' => 'Charleston', 'state_id' => 3948],
                ['name' => 'Enid', 'state_id' => 3948],
                ['name' => 'Glendora', 'state_id' => 3948],
                ['name' => 'Philipp', 'state_id' => 3948],
                ['name' => 'Sumner', 'state_id' => 3948],
                ['name' => 'Swan Lake', 'state_id' => 3948],
                ['name' => 'Tippo', 'state_id' => 3948],
                ['name' => 'Tutwiler', 'state_id' => 3948],
                ['name' => 'Webb', 'state_id' => 3948],
                ['name' => 'Arkabutla', 'state_id' => 3948],
                ['name' => 'Coldwater', 'state_id' => 3948],
                ['name' => 'Independence', 'state_id' => 3948],
                ['name' => 'Senatobia', 'state_id' => 3948],
                ['name' => 'Blue Mountain', 'state_id' => 3948],
                ['name' => 'Dumas', 'state_id' => 3948],
                ['name' => 'Falkner', 'state_id' => 3948],
                ['name' => 'Ripley', 'state_id' => 3948],
                ['name' => 'Tiplersville', 'state_id' => 3948],
                ['name' => 'Walnut', 'state_id' => 3948],
                ['name' => 'Belmont', 'state_id' => 3948],
                ['name' => 'Burnsville', 'state_id' => 3948],
                ['name' => 'Dennis', 'state_id' => 3948],
                ['name' => 'Iuka', 'state_id' => 3948],
                ['name' => 'Tishomingo', 'state_id' => 3948],
                ['name' => 'Dundee', 'state_id' => 3948],
                ['name' => 'Robinsonville', 'state_id' => 3948],
                ['name' => 'Sledge', 'state_id' => 3948],
                ['name' => 'Tunica', 'state_id' => 3948],
                ['name' => 'Etta', 'state_id' => 3948],
                ['name' => 'Myrtle', 'state_id' => 3948],
                ['name' => 'New Albany', 'state_id' => 3948],
                ['name' => 'Blue Springs', 'state_id' => 3948],
                ['name' => 'Tylertown', 'state_id' => 3948],
                ['name' => 'Redwood', 'state_id' => 3948],
                ['name' => 'Vicksburg', 'state_id' => 3948],
                ['name' => 'Greenville', 'state_id' => 3948],
                ['name' => 'Arcola', 'state_id' => 3948],
                ['name' => 'Avon', 'state_id' => 3948],
                ['name' => 'Chatham', 'state_id' => 3948],
                ['name' => 'Glen Allan', 'state_id' => 3948],
                ['name' => 'Hollandale', 'state_id' => 3948],
                ['name' => 'Leland', 'state_id' => 3948],
                ['name' => 'Metcalfe', 'state_id' => 3948],
                ['name' => 'Stoneville', 'state_id' => 3948],
                ['name' => 'Wayside', 'state_id' => 3948],
                ['name' => 'Winterville', 'state_id' => 3948],
                ['name' => 'Buckatunna', 'state_id' => 3948],
                ['name' => 'Clara', 'state_id' => 3948],
                ['name' => 'Waynesboro', 'state_id' => 3948],
                ['name' => 'Bellefontaine', 'state_id' => 3948],
                ['name' => 'Eupora', 'state_id' => 3948],
                ['name' => 'Maben', 'state_id' => 3948],
                ['name' => 'Mathiston', 'state_id' => 3948],
                ['name' => 'Walthall', 'state_id' => 3948],
                ['name' => 'Centreville', 'state_id' => 3948],
                ['name' => 'Woodville', 'state_id' => 3948],
                ['name' => 'Louisville', 'state_id' => 3948],
                ['name' => 'Noxapater', 'state_id' => 3948],
                ['name' => 'Coffeeville', 'state_id' => 3948],
                ['name' => 'Oakland', 'state_id' => 3948],
                ['name' => 'Scobey', 'state_id' => 3948],
                ['name' => 'Tillatoba', 'state_id' => 3948],
                ['name' => 'Water Valley', 'state_id' => 3948],
                ['name' => 'Benton', 'state_id' => 3948],
                ['name' => 'Bentonia', 'state_id' => 3948],
                ['name' => 'Holly Bluff', 'state_id' => 3948],
                ['name' => 'Satartia', 'state_id' => 3948],
                ['name' => 'Tinsley', 'state_id' => 3948],
                ['name' => 'Vaughan', 'state_id' => 3948],
                ['name' => 'Yazoo City', 'state_id' => 3948]
            ]);
        }
    }
}
