<?php

use Illuminate\Database\Seeder;

class state14TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ID - Idaho.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Eagle', 'state_id' => 3934],
                ['name' => 'Kuna', 'state_id' => 3934],
                ['name' => 'Meridian', 'state_id' => 3934],
                ['name' => 'Star', 'state_id' => 3934],
                ['name' => 'Boise', 'state_id' => 3934],
                ['name' => 'Garden City', 'state_id' => 3934],
                ['name' => 'Council', 'state_id' => 3934],
                ['name' => 'Indian Valley', 'state_id' => 3934],
                ['name' => 'Mesa', 'state_id' => 3934],
                ['name' => 'New Meadows', 'state_id' => 3934],
                ['name' => 'Pocatello', 'state_id' => 3934],
                ['name' => 'Arimo', 'state_id' => 3934],
                ['name' => 'Downey', 'state_id' => 3934],
                ['name' => 'Inkom', 'state_id' => 3934],
                ['name' => 'Lava Hot Springs', 'state_id' => 3934],
                ['name' => 'McCammon', 'state_id' => 3934],
                ['name' => 'Swanlake', 'state_id' => 3934],
                ['name' => 'Bern', 'state_id' => 3934],
                ['name' => 'Bloomington', 'state_id' => 3934],
                ['name' => 'Dingle', 'state_id' => 3934],
                ['name' => 'Geneva', 'state_id' => 3934],
                ['name' => 'Georgetown', 'state_id' => 3934],
                ['name' => 'Montpelier', 'state_id' => 3934],
                ['name' => 'Paris', 'state_id' => 3934],
                ['name' => 'Saint Charles', 'state_id' => 3934],
                ['name' => 'Fish Haven', 'state_id' => 3934],
                ['name' => 'Desmet', 'state_id' => 3934],
                ['name' => 'Fernwood', 'state_id' => 3934],
                ['name' => 'Plummer', 'state_id' => 3934],
                ['name' => 'Saint Maries', 'state_id' => 3934],
                ['name' => 'Santa', 'state_id' => 3934],
                ['name' => 'Tensed', 'state_id' => 3934],
                ['name' => 'Fort Hall', 'state_id' => 3934],
                ['name' => 'Aberdeen', 'state_id' => 3934],
                ['name' => 'Atomic City', 'state_id' => 3934],
                ['name' => 'Basalt', 'state_id' => 3934],
                ['name' => 'Blackfoot', 'state_id' => 3934],
                ['name' => 'Firth', 'state_id' => 3934],
                ['name' => 'Moreland', 'state_id' => 3934],
                ['name' => 'Pingree', 'state_id' => 3934],
                ['name' => 'Shelley', 'state_id' => 3934],
                ['name' => 'Springfield', 'state_id' => 3934],
                ['name' => 'Bellevue', 'state_id' => 3934],
                ['name' => 'Carey', 'state_id' => 3934],
                ['name' => 'Hailey', 'state_id' => 3934],
                ['name' => 'Ketchum', 'state_id' => 3934],
                ['name' => 'Picabo', 'state_id' => 3934],
                ['name' => 'Sun Valley', 'state_id' => 3934],
                ['name' => 'Banks', 'state_id' => 3934],
                ['name' => 'Garden Valley', 'state_id' => 3934],
                ['name' => 'Horseshoe Bend', 'state_id' => 3934],
                ['name' => 'Idaho City', 'state_id' => 3934],
                ['name' => 'Lowman', 'state_id' => 3934],
                ['name' => 'Placerville', 'state_id' => 3934],
                ['name' => 'Blanchard', 'state_id' => 3934],
                ['name' => 'Careywood', 'state_id' => 3934],
                ['name' => 'Clark Fork', 'state_id' => 3934],
                ['name' => 'Cocolalla', 'state_id' => 3934],
                ['name' => 'Coolin', 'state_id' => 3934],
                ['name' => 'Oldtown', 'state_id' => 3934],
                ['name' => 'Dover', 'state_id' => 3934],
                ['name' => 'Hope', 'state_id' => 3934],
                ['name' => 'Kootenai', 'state_id' => 3934],
                ['name' => 'Laclede', 'state_id' => 3934],
                ['name' => 'Nordman', 'state_id' => 3934],
                ['name' => 'Ponderay', 'state_id' => 3934],
                ['name' => 'Priest River', 'state_id' => 3934],
                ['name' => 'Sagle', 'state_id' => 3934],
                ['name' => 'Sandpoint', 'state_id' => 3934],
                ['name' => 'Colburn', 'state_id' => 3934],
                ['name' => 'Idaho Falls', 'state_id' => 3934],
                ['name' => 'Iona', 'state_id' => 3934],
                ['name' => 'Irwin', 'state_id' => 3934],
                ['name' => 'Swan Valley', 'state_id' => 3934],
                ['name' => 'Ucon', 'state_id' => 3934],
                ['name' => 'Bonners Ferry', 'state_id' => 3934],
                ['name' => 'Eastport', 'state_id' => 3934],
                ['name' => 'Moyie Springs', 'state_id' => 3934],
                ['name' => 'Naples', 'state_id' => 3934],
                ['name' => 'Porthill', 'state_id' => 3934],
                ['name' => 'Arco', 'state_id' => 3934],
                ['name' => 'Howe', 'state_id' => 3934],
                ['name' => 'Moore', 'state_id' => 3934],
                ['name' => 'Corral', 'state_id' => 3934],
                ['name' => 'Fairfield', 'state_id' => 3934],
                ['name' => 'Hill City', 'state_id' => 3934],
                ['name' => 'Caldwell', 'state_id' => 3934],
                ['name' => 'Greenleaf', 'state_id' => 3934],
                ['name' => 'Huston', 'state_id' => 3934],
                ['name' => 'Melba', 'state_id' => 3934],
                ['name' => 'Middleton', 'state_id' => 3934],
                ['name' => 'Nampa', 'state_id' => 3934],
                ['name' => 'Notus', 'state_id' => 3934],
                ['name' => 'Parma', 'state_id' => 3934],
                ['name' => 'Wilder', 'state_id' => 3934],
                ['name' => 'Bancroft', 'state_id' => 3934],
                ['name' => 'Conda', 'state_id' => 3934],
                ['name' => 'Grace', 'state_id' => 3934],
                ['name' => 'Soda Springs', 'state_id' => 3934],
                ['name' => 'Wayan', 'state_id' => 3934],
                ['name' => 'Albion', 'state_id' => 3934],
                ['name' => 'Almo', 'state_id' => 3934],
                ['name' => 'Burley', 'state_id' => 3934],
                ['name' => 'Declo', 'state_id' => 3934],
                ['name' => 'Malta', 'state_id' => 3934],
                ['name' => 'Oakley', 'state_id' => 3934],
                ['name' => 'Dubois', 'state_id' => 3934],
                ['name' => 'Spencer', 'state_id' => 3934],
                ['name' => 'Ahsahka', 'state_id' => 3934],
                ['name' => 'Lenore', 'state_id' => 3934],
                ['name' => 'Orofino', 'state_id' => 3934],
                ['name' => 'Pierce', 'state_id' => 3934],
                ['name' => 'Weippe', 'state_id' => 3934],
                ['name' => 'Elk River', 'state_id' => 3934],
                ['name' => 'Challis', 'state_id' => 3934],
                ['name' => 'Clayton', 'state_id' => 3934],
                ['name' => 'Ellis', 'state_id' => 3934],
                ['name' => 'Mackay', 'state_id' => 3934],
                ['name' => 'Stanley', 'state_id' => 3934],
                ['name' => 'Atlanta', 'state_id' => 3934],
                ['name' => 'Glenns Ferry', 'state_id' => 3934],
                ['name' => 'Hammett', 'state_id' => 3934],
                ['name' => 'King Hill', 'state_id' => 3934],
                ['name' => 'Mountain Home', 'state_id' => 3934],
                ['name' => 'Mountain Home Afb', 'state_id' => 3934],
                ['name' => 'Clifton', 'state_id' => 3934],
                ['name' => 'Dayton', 'state_id' => 3934],
                ['name' => 'Franklin', 'state_id' => 3934],
                ['name' => 'Preston', 'state_id' => 3934],
                ['name' => 'Thatcher', 'state_id' => 3934],
                ['name' => 'Weston', 'state_id' => 3934],
                ['name' => 'Ashton', 'state_id' => 3934],
                ['name' => 'Chester', 'state_id' => 3934],
                ['name' => 'Island Park', 'state_id' => 3934],
                ['name' => 'Macks Inn', 'state_id' => 3934],
                ['name' => 'Newdale', 'state_id' => 3934],
                ['name' => 'Parker', 'state_id' => 3934],
                ['name' => 'Saint Anthony', 'state_id' => 3934],
                ['name' => 'Teton', 'state_id' => 3934],
                ['name' => 'Emmett', 'state_id' => 3934],
                ['name' => 'Letha', 'state_id' => 3934],
                ['name' => 'Ola', 'state_id' => 3934],
                ['name' => 'Sweet', 'state_id' => 3934],
                ['name' => 'Bliss', 'state_id' => 3934],
                ['name' => 'Gooding', 'state_id' => 3934],
                ['name' => 'Hagerman', 'state_id' => 3934],
                ['name' => 'Wendell', 'state_id' => 3934],
                ['name' => 'Cottonwood', 'state_id' => 3934],
                ['name' => 'Elk City', 'state_id' => 3934],
                ['name' => 'Ferdinand', 'state_id' => 3934],
                ['name' => 'Grangeville', 'state_id' => 3934],
                ['name' => 'Fenn', 'state_id' => 3934],
                ['name' => 'Greencreek', 'state_id' => 3934],
                ['name' => 'Kooskia', 'state_id' => 3934],
                ['name' => 'Lucile', 'state_id' => 3934],
                ['name' => 'Pollock', 'state_id' => 3934],
                ['name' => 'Riggins', 'state_id' => 3934],
                ['name' => 'Stites', 'state_id' => 3934],
                ['name' => 'White Bird', 'state_id' => 3934],
                ['name' => 'Warren', 'state_id' => 3934],
                ['name' => 'Hamer', 'state_id' => 3934],
                ['name' => 'Lewisville', 'state_id' => 3934],
                ['name' => 'Menan', 'state_id' => 3934],
                ['name' => 'Monteview', 'state_id' => 3934],
                ['name' => 'Rigby', 'state_id' => 3934],
                ['name' => 'Ririe', 'state_id' => 3934],
                ['name' => 'Roberts', 'state_id' => 3934],
                ['name' => 'Terreton', 'state_id' => 3934],
                ['name' => 'Eden', 'state_id' => 3934],
                ['name' => 'Hazelton', 'state_id' => 3934],
                ['name' => 'Jerome', 'state_id' => 3934],
                ['name' => 'Athol', 'state_id' => 3934],
                ['name' => 'Bayview', 'state_id' => 3934],
                ['name' => 'Cataldo', 'state_id' => 3934],
                ['name' => "Coeur d'Alene", 'state_id' => 3934],
                ['name' => 'Harrison', 'state_id' => 3934],
                ['name' => 'Hayden', 'state_id' => 3934],
                ['name' => 'Medimont', 'state_id' => 3934],
                ['name' => 'Post Falls', 'state_id' => 3934],
                ['name' => 'Rathdrum', 'state_id' => 3934],
                ['name' => 'Spirit Lake', 'state_id' => 3934],
                ['name' => 'Worley', 'state_id' => 3934],
                ['name' => 'Juliaetta', 'state_id' => 3934],
                ['name' => 'Kendrick', 'state_id' => 3934],
                ['name' => 'Bovill', 'state_id' => 3934],
                ['name' => 'Deary', 'state_id' => 3934],
                ['name' => 'Genesee', 'state_id' => 3934],
                ['name' => 'Harvard', 'state_id' => 3934],
                ['name' => 'Moscow', 'state_id' => 3934],
                ['name' => 'Potlatch', 'state_id' => 3934],
                ['name' => 'Princeton', 'state_id' => 3934],
                ['name' => 'Troy', 'state_id' => 3934],
                ['name' => 'Viola', 'state_id' => 3934],
                ['name' => 'Cobalt', 'state_id' => 3934],
                ['name' => 'May', 'state_id' => 3934],
                ['name' => 'Carmen', 'state_id' => 3934],
                ['name' => 'Gibbonsville', 'state_id' => 3934],
                ['name' => 'Leadore', 'state_id' => 3934],
                ['name' => 'Lemhi', 'state_id' => 3934],
                ['name' => 'North Fork', 'state_id' => 3934],
                ['name' => 'Salmon', 'state_id' => 3934],
                ['name' => 'Tendoy', 'state_id' => 3934],
                ['name' => 'Shoup', 'state_id' => 3934],
                ['name' => 'Craigmont', 'state_id' => 3934],
                ['name' => 'Kamiah', 'state_id' => 3934],
                ['name' => 'Nezperce', 'state_id' => 3934],
                ['name' => 'Reubens', 'state_id' => 3934],
                ['name' => 'Winchester', 'state_id' => 3934],
                ['name' => 'Dietrich', 'state_id' => 3934],
                ['name' => 'Richfield', 'state_id' => 3934],
                ['name' => 'Shoshone', 'state_id' => 3934],
                ['name' => 'Rexburg', 'state_id' => 3934],
                ['name' => 'Sugar City', 'state_id' => 3934],
                ['name' => 'Heyburn', 'state_id' => 3934],
                ['name' => 'Minidoka', 'state_id' => 3934],
                ['name' => 'Paul', 'state_id' => 3934],
                ['name' => 'Rupert', 'state_id' => 3934],
                ['name' => 'Lewiston', 'state_id' => 3934],
                ['name' => 'Culdesac', 'state_id' => 3934],
                ['name' => 'Lapwai', 'state_id' => 3934],
                ['name' => 'Peck', 'state_id' => 3934],
                ['name' => 'Holbrook', 'state_id' => 3934],
                ['name' => 'Malad City', 'state_id' => 3934],
                ['name' => 'Bruneau', 'state_id' => 3934],
                ['name' => 'Grand View', 'state_id' => 3934],
                ['name' => 'Homedale', 'state_id' => 3934],
                ['name' => 'Marsing', 'state_id' => 3934],
                ['name' => 'Murphy', 'state_id' => 3934],
                ['name' => 'Fruitland', 'state_id' => 3934],
                ['name' => 'New Plymouth', 'state_id' => 3934],
                ['name' => 'Payette', 'state_id' => 3934],
                ['name' => 'American Falls', 'state_id' => 3934],
                ['name' => 'Arbon', 'state_id' => 3934],
                ['name' => 'Rockland', 'state_id' => 3934],
                ['name' => 'Avery', 'state_id' => 3934],
                ['name' => 'Calder', 'state_id' => 3934],
                ['name' => 'Clarkia', 'state_id' => 3934],
                ['name' => 'Kellogg', 'state_id' => 3934],
                ['name' => 'Kingston', 'state_id' => 3934],
                ['name' => 'Mullan', 'state_id' => 3934],
                ['name' => 'Osburn', 'state_id' => 3934],
                ['name' => 'Pinehurst', 'state_id' => 3934],
                ['name' => 'Silverton', 'state_id' => 3934],
                ['name' => 'Smelterville', 'state_id' => 3934],
                ['name' => 'Wallace', 'state_id' => 3934],
                ['name' => 'Murray', 'state_id' => 3934],
                ['name' => 'Driggs', 'state_id' => 3934],
                ['name' => 'Felt', 'state_id' => 3934],
                ['name' => 'Tetonia', 'state_id' => 3934],
                ['name' => 'Victor', 'state_id' => 3934],
                ['name' => 'Twin Falls', 'state_id' => 3934],
                ['name' => 'Rogerson', 'state_id' => 3934],
                ['name' => 'Buhl', 'state_id' => 3934],
                ['name' => 'Castleford', 'state_id' => 3934],
                ['name' => 'Filer', 'state_id' => 3934],
                ['name' => 'Hansen', 'state_id' => 3934],
                ['name' => 'Kimberly', 'state_id' => 3934],
                ['name' => 'Murtaugh', 'state_id' => 3934],
                ['name' => 'Cascade', 'state_id' => 3934],
                ['name' => 'Donnelly', 'state_id' => 3934],
                ['name' => 'Lake Fork', 'state_id' => 3934],
                ['name' => 'McCall', 'state_id' => 3934],
                ['name' => 'Yellow Pine', 'state_id' => 3934],
                ['name' => 'Cambridge', 'state_id' => 3934],
                ['name' => 'Midvale', 'state_id' => 3934],
                ['name' => 'Weiser', 'state_id' => 3934]
            ]);
        }
    }
}
