<?php

use Illuminate\Database\Seeder;

class state11TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of GA - Georgia.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Baxley', 'state_id' => 3932],
                ['name' => 'Saint George', 'state_id' => 3932],
                ['name' => 'Surrency', 'state_id' => 3932],
                ['name' => 'Axson', 'state_id' => 3932],
                ['name' => 'Pearson', 'state_id' => 3932],
                ['name' => 'Willacoochee', 'state_id' => 3932],
                ['name' => 'Alma', 'state_id' => 3932],
                ['name' => 'Albany', 'state_id' => 3932],
                ['name' => 'Colquitt', 'state_id' => 3932],
                ['name' => 'Damascus', 'state_id' => 3932],
                ['name' => 'Donalsonville', 'state_id' => 3932],
                ['name' => 'Leary', 'state_id' => 3932],
                ['name' => 'Newton', 'state_id' => 3932],
                ['name' => 'Hardwick', 'state_id' => 3932],
                ['name' => 'Milledgeville', 'state_id' => 3932],
                ['name' => 'Baldwin', 'state_id' => 3932],
                ['name' => 'Homer', 'state_id' => 3932],
                ['name' => 'Maysville', 'state_id' => 3932],
                ['name' => 'Auburn', 'state_id' => 3932],
                ['name' => 'Bethlehem', 'state_id' => 3932],
                ['name' => 'Statham', 'state_id' => 3932],
                ['name' => 'Winder', 'state_id' => 3932],
                ['name' => 'Adairsville', 'state_id' => 3932],
                ['name' => 'Cartersville', 'state_id' => 3932],
                ['name' => 'Cassville', 'state_id' => 3932],
                ['name' => 'Emerson', 'state_id' => 3932],
                ['name' => 'Kingston', 'state_id' => 3932],
                ['name' => 'Rydal', 'state_id' => 3932],
                ['name' => 'Taylorsville', 'state_id' => 3932],
                ['name' => 'White', 'state_id' => 3932],
                ['name' => 'Fitzgerald', 'state_id' => 3932],
                ['name' => 'Cuthbert', 'state_id' => 3932],
                ['name' => 'Alapaha', 'state_id' => 3932],
                ['name' => 'Nashville', 'state_id' => 3932],
                ['name' => 'Ray City', 'state_id' => 3932],
                ['name' => 'Enigma', 'state_id' => 3932],
                ['name' => 'Lizella', 'state_id' => 3932],
                ['name' => 'Macon', 'state_id' => 3932],
                ['name' => 'Cochran', 'state_id' => 3932],
                ['name' => 'Hoboken', 'state_id' => 3932],
                ['name' => 'Hortense', 'state_id' => 3932],
                ['name' => 'Nahunta', 'state_id' => 3932],
                ['name' => 'Waynesville', 'state_id' => 3932],
                ['name' => 'Barney', 'state_id' => 3932],
                ['name' => 'Dixie', 'state_id' => 3932],
                ['name' => 'Morven', 'state_id' => 3932],
                ['name' => 'Quitman', 'state_id' => 3932],
                ['name' => 'Barwick', 'state_id' => 3932],
                ['name' => 'Ellabell', 'state_id' => 3932],
                ['name' => 'Pembroke', 'state_id' => 3932],
                ['name' => 'Richmond Hill', 'state_id' => 3932],
                ['name' => 'Brooklet', 'state_id' => 3932],
                ['name' => 'Portal', 'state_id' => 3932],
                ['name' => 'Register', 'state_id' => 3932],
                ['name' => 'Statesboro', 'state_id' => 3932],
                ['name' => 'Girard', 'state_id' => 3932],
                ['name' => 'Midville', 'state_id' => 3932],
                ['name' => 'Sardis', 'state_id' => 3932],
                ['name' => 'Gough', 'state_id' => 3932],
                ['name' => 'Keysville', 'state_id' => 3932],
                ['name' => 'Waynesboro', 'state_id' => 3932],
                ['name' => 'Flovilla', 'state_id' => 3932],
                ['name' => 'Jackson', 'state_id' => 3932],
                ['name' => 'Jenkinsburg', 'state_id' => 3932],
                ['name' => 'Dawson', 'state_id' => 3932],
                ['name' => 'Morgan', 'state_id' => 3932],
                ['name' => 'Shellman', 'state_id' => 3932],
                ['name' => 'Kings Bay', 'state_id' => 3932],
                ['name' => 'Kingsland', 'state_id' => 3932],
                ['name' => 'Saint Marys', 'state_id' => 3932],
                ['name' => 'Waverly', 'state_id' => 3932],
                ['name' => 'White Oak', 'state_id' => 3932],
                ['name' => 'Woodbine', 'state_id' => 3932],
                ['name' => 'Metter', 'state_id' => 3932],
                ['name' => 'Pulaski', 'state_id' => 3932],
                ['name' => 'Bowdon', 'state_id' => 3932],
                ['name' => 'Bowdon Junction', 'state_id' => 3932],
                ['name' => 'Carrollton', 'state_id' => 3932],
                ['name' => 'Mount Zion', 'state_id' => 3932],
                ['name' => 'Roopville', 'state_id' => 3932],
                ['name' => 'Temple', 'state_id' => 3932],
                ['name' => 'Villa Rica', 'state_id' => 3932],
                ['name' => 'Whitesburg', 'state_id' => 3932],
                ['name' => 'Graysville', 'state_id' => 3932],
                ['name' => 'Ringgold', 'state_id' => 3932],
                ['name' => 'Fort Oglethorpe', 'state_id' => 3932],
                ['name' => 'Folkston', 'state_id' => 3932],
                ['name' => 'Bloomingdale', 'state_id' => 3932],
                ['name' => 'Pooler', 'state_id' => 3932],
                ['name' => 'Tybee Island', 'state_id' => 3932],
                ['name' => 'Savannah', 'state_id' => 3932],
                ['name' => 'Port Wentworth', 'state_id' => 3932],
                ['name' => 'Cusseta', 'state_id' => 3932],
                ['name' => 'Lyerly', 'state_id' => 3932],
                ['name' => 'Menlo', 'state_id' => 3932],
                ['name' => 'Summerville', 'state_id' => 3932],
                ['name' => 'Trion', 'state_id' => 3932],
                ['name' => 'Ball Ground', 'state_id' => 3932],
                ['name' => 'Canton', 'state_id' => 3932],
                ['name' => 'Holly Springs', 'state_id' => 3932],
                ['name' => 'Lebanon', 'state_id' => 3932],
                ['name' => 'Nelson', 'state_id' => 3932],
                ['name' => 'Waleska', 'state_id' => 3932],
                ['name' => 'Woodstock', 'state_id' => 3932],
                ['name' => 'Athens', 'state_id' => 3932],
                ['name' => 'Winterville', 'state_id' => 3932],
                ['name' => 'Blakely', 'state_id' => 3932],
                ['name' => 'Bluffton', 'state_id' => 3932],
                ['name' => 'Coleman', 'state_id' => 3932],
                ['name' => 'Edison', 'state_id' => 3932],
                ['name' => 'Fort Gaines', 'state_id' => 3932],
                ['name' => 'Georgetown', 'state_id' => 3932],
                ['name' => 'Morris', 'state_id' => 3932],
                ['name' => 'Jonesboro', 'state_id' => 3932],
                ['name' => 'Lovejoy', 'state_id' => 3932],
                ['name' => 'Morrow', 'state_id' => 3932],
                ['name' => 'Rex', 'state_id' => 3932],
                ['name' => 'Riverdale', 'state_id' => 3932],
                ['name' => 'Conley', 'state_id' => 3932],
                ['name' => 'Ellenwood', 'state_id' => 3932],
                ['name' => 'Forest Park', 'state_id' => 3932],
                ['name' => 'Argyle', 'state_id' => 3932],
                ['name' => 'Du Pont', 'state_id' => 3932],
                ['name' => 'Fargo', 'state_id' => 3932],
                ['name' => 'Homerville', 'state_id' => 3932],
                ['name' => 'Marietta', 'state_id' => 3932],
                ['name' => 'Smyrna', 'state_id' => 3932],
                ['name' => 'Acworth', 'state_id' => 3932],
                ['name' => 'Austell', 'state_id' => 3932],
                ['name' => 'Clarkdale', 'state_id' => 3932],
                ['name' => 'Mableton', 'state_id' => 3932],
                ['name' => 'Powder Springs', 'state_id' => 3932],
                ['name' => 'Kennesaw', 'state_id' => 3932],
                ['name' => 'Ambrose', 'state_id' => 3932],
                ['name' => 'Broxton', 'state_id' => 3932],
                ['name' => 'Douglas', 'state_id' => 3932],
                ['name' => 'Nicholls', 'state_id' => 3932],
                ['name' => 'West Green', 'state_id' => 3932],
                ['name' => 'Berlin', 'state_id' => 3932],
                ['name' => 'Doerun', 'state_id' => 3932],
                ['name' => 'Ellenton', 'state_id' => 3932],
                ['name' => 'Funston', 'state_id' => 3932],
                ['name' => 'Hartsfield', 'state_id' => 3932],
                ['name' => 'Moultrie', 'state_id' => 3932],
                ['name' => 'Norman Park', 'state_id' => 3932],
                ['name' => 'Appling', 'state_id' => 3932],
                ['name' => 'Evans', 'state_id' => 3932],
                ['name' => 'Grovetown', 'state_id' => 3932],
                ['name' => 'Harlem', 'state_id' => 3932],
                ['name' => 'Augusta', 'state_id' => 3932],
                ['name' => 'Arlington', 'state_id' => 3932],
                ['name' => 'Adel', 'state_id' => 3932],
                ['name' => 'Cecil', 'state_id' => 3932],
                ['name' => 'Lenox', 'state_id' => 3932],
                ['name' => 'Sparks', 'state_id' => 3932],
                ['name' => 'Grantville', 'state_id' => 3932],
                ['name' => 'Haralson', 'state_id' => 3932],
                ['name' => 'Moreland', 'state_id' => 3932],
                ['name' => 'Newnan', 'state_id' => 3932],
                ['name' => 'Sargent', 'state_id' => 3932],
                ['name' => 'Senoia', 'state_id' => 3932],
                ['name' => 'Sharpsburg', 'state_id' => 3932],
                ['name' => 'Turin', 'state_id' => 3932],
                ['name' => 'Knoxville', 'state_id' => 3932],
                ['name' => 'Musella', 'state_id' => 3932],
                ['name' => 'Roberta', 'state_id' => 3932],
                ['name' => 'Cordele', 'state_id' => 3932],
                ['name' => 'Arabi', 'state_id' => 3932],
                ['name' => 'Rising Fawn', 'state_id' => 3932],
                ['name' => 'Trenton', 'state_id' => 3932],
                ['name' => 'Wildwood', 'state_id' => 3932],
                ['name' => 'Dawsonville', 'state_id' => 3932],
                ['name' => 'Attapulgus', 'state_id' => 3932],
                ['name' => 'Bainbridge', 'state_id' => 3932],
                ['name' => 'Fowlstown', 'state_id' => 3932],
                ['name' => 'Avondale Estates', 'state_id' => 3932],
                ['name' => 'Clarkston', 'state_id' => 3932],
                ['name' => 'Decatur', 'state_id' => 3932],
                ['name' => 'Lithonia', 'state_id' => 3932],
                ['name' => 'Pine Lake', 'state_id' => 3932],
                ['name' => 'Redan', 'state_id' => 3932],
                ['name' => 'Scottdale', 'state_id' => 3932],
                ['name' => 'Stone Mountain', 'state_id' => 3932],
                ['name' => 'Tucker', 'state_id' => 3932],
                ['name' => 'Atlanta', 'state_id' => 3932],
                ['name' => 'Chauncey', 'state_id' => 3932],
                ['name' => 'Chester', 'state_id' => 3932],
                ['name' => 'Eastman', 'state_id' => 3932],
                ['name' => 'Rhine', 'state_id' => 3932],
                ['name' => 'Byromville', 'state_id' => 3932],
                ['name' => 'Lilly', 'state_id' => 3932],
                ['name' => 'Montezuma', 'state_id' => 3932],
                ['name' => 'Pinehurst', 'state_id' => 3932],
                ['name' => 'Unadilla', 'state_id' => 3932],
                ['name' => 'Vienna', 'state_id' => 3932],
                ['name' => 'Putney', 'state_id' => 3932],
                ['name' => 'Lithia Springs', 'state_id' => 3932],
                ['name' => 'Douglasville', 'state_id' => 3932],
                ['name' => 'Winston', 'state_id' => 3932],
                ['name' => 'Cedar Springs', 'state_id' => 3932],
                ['name' => 'Climax', 'state_id' => 3932],
                ['name' => 'Statenville', 'state_id' => 3932],
                ['name' => 'Clyo', 'state_id' => 3932],
                ['name' => 'Eden', 'state_id' => 3932],
                ['name' => 'Guyton', 'state_id' => 3932],
                ['name' => 'Meldrim', 'state_id' => 3932],
                ['name' => 'Rincon', 'state_id' => 3932],
                ['name' => 'Springfield', 'state_id' => 3932],
                ['name' => 'Bowman', 'state_id' => 3932],
                ['name' => 'Dewy Rose', 'state_id' => 3932],
                ['name' => 'Elberton', 'state_id' => 3932],
                ['name' => 'Swainsboro', 'state_id' => 3932],
                ['name' => 'Garfield', 'state_id' => 3932],
                ['name' => 'Norristown', 'state_id' => 3932],
                ['name' => 'Nunez', 'state_id' => 3932],
                ['name' => 'Stillmore', 'state_id' => 3932],
                ['name' => 'Twin City', 'state_id' => 3932],
                ['name' => 'Adrian', 'state_id' => 3932],
                ['name' => 'Bellville', 'state_id' => 3932],
                ['name' => 'Claxton', 'state_id' => 3932],
                ['name' => 'Daisy', 'state_id' => 3932],
                ['name' => 'Hagan', 'state_id' => 3932],
                ['name' => 'Blue Ridge', 'state_id' => 3932],
                ['name' => 'Epworth', 'state_id' => 3932],
                ['name' => 'Mc Caysville', 'state_id' => 3932],
                ['name' => 'Mineral Bluff', 'state_id' => 3932],
                ['name' => 'Morganton', 'state_id' => 3932],
                ['name' => 'Brooks', 'state_id' => 3932],
                ['name' => 'Fayetteville', 'state_id' => 3932],
                ['name' => 'Peachtree City', 'state_id' => 3932],
                ['name' => 'Tyrone', 'state_id' => 3932],
                ['name' => 'Armuchee', 'state_id' => 3932],
                ['name' => 'Cave Spring', 'state_id' => 3932],
                ['name' => 'Coosa', 'state_id' => 3932],
                ['name' => 'Lindale', 'state_id' => 3932],
                ['name' => 'Mount Berry', 'state_id' => 3932],
                ['name' => 'Rome', 'state_id' => 3932],
                ['name' => 'Shannon', 'state_id' => 3932],
                ['name' => 'Silver Creek', 'state_id' => 3932],
                ['name' => 'Cumming', 'state_id' => 3932],
                ['name' => 'Canon', 'state_id' => 3932],
                ['name' => 'Carnesville', 'state_id' => 3932],
                ['name' => 'Lavonia', 'state_id' => 3932],
                ['name' => 'Franklin Springs', 'state_id' => 3932],
                ['name' => 'Royston', 'state_id' => 3932],
                ['name' => 'Alpharetta', 'state_id' => 3932],
                ['name' => 'Roswell', 'state_id' => 3932],
                ['name' => 'Fairburn', 'state_id' => 3932],
                ['name' => 'Palmetto', 'state_id' => 3932],
                ['name' => 'Red Oak', 'state_id' => 3932],
                ['name' => 'Union City', 'state_id' => 3932],
                ['name' => 'Cherry Log', 'state_id' => 3932],
                ['name' => 'Ellijay', 'state_id' => 3932],
                ['name' => 'East Ellijay', 'state_id' => 3932],
                ['name' => 'Gibson', 'state_id' => 3932],
                ['name' => 'Mitchell', 'state_id' => 3932],
                ['name' => 'Brunswick', 'state_id' => 3932],
                ['name' => 'Saint Simons Island', 'state_id' => 3932],
                ['name' => 'Jekyll Island', 'state_id' => 3932],
                ['name' => 'Sea Island', 'state_id' => 3932],
                ['name' => 'Fairmount', 'state_id' => 3932],
                ['name' => 'Calhoun', 'state_id' => 3932],
                ['name' => 'Oakman', 'state_id' => 3932],
                ['name' => 'Plainville', 'state_id' => 3932],
                ['name' => 'Ranger', 'state_id' => 3932],
                ['name' => 'Resaca', 'state_id' => 3932],
                ['name' => 'Sugar Valley', 'state_id' => 3932],
                ['name' => 'Cairo', 'state_id' => 3932],
                ['name' => 'Calvary', 'state_id' => 3932],
                ['name' => 'Whigham', 'state_id' => 3932],
                ['name' => 'Greensboro', 'state_id' => 3932],
                ['name' => 'Siloam', 'state_id' => 3932],
                ['name' => 'Union Point', 'state_id' => 3932],
                ['name' => 'White Plains', 'state_id' => 3932],
                ['name' => 'Norcross', 'state_id' => 3932],
                ['name' => 'Grayson', 'state_id' => 3932],
                ['name' => 'Dacula', 'state_id' => 3932],
                ['name' => 'Suwanee', 'state_id' => 3932],
                ['name' => 'North Metro', 'state_id' => 3932],
                ['name' => 'Snellville', 'state_id' => 3932],
                ['name' => 'Lawrenceville', 'state_id' => 3932],
                ['name' => 'Lilburn', 'state_id' => 3932],
                ['name' => 'Loganville', 'state_id' => 3932],
                ['name' => 'Peachtree Corners', 'state_id' => 3932],
                ['name' => 'Duluth', 'state_id' => 3932],
                ['name' => 'Buford', 'state_id' => 3932],
                ['name' => 'Alto', 'state_id' => 3932],
                ['name' => 'Clarkesville', 'state_id' => 3932],
                ['name' => 'Cornelia', 'state_id' => 3932],
                ['name' => 'Demorest', 'state_id' => 3932],
                ['name' => 'Mount Airy', 'state_id' => 3932],
                ['name' => 'Turnerville', 'state_id' => 3932],
                ['name' => 'Gainesville', 'state_id' => 3932],
                ['name' => 'Chestnut Mountain', 'state_id' => 3932],
                ['name' => 'Clermont', 'state_id' => 3932],
                ['name' => 'Flowery Branch', 'state_id' => 3932],
                ['name' => 'Gillsville', 'state_id' => 3932],
                ['name' => 'Lula', 'state_id' => 3932],
                ['name' => 'Murrayville', 'state_id' => 3932],
                ['name' => 'Oakwood', 'state_id' => 3932],
                ['name' => 'Sparta', 'state_id' => 3932],
                ['name' => 'Bremen', 'state_id' => 3932],
                ['name' => 'Buchanan', 'state_id' => 3932],
                ['name' => 'Felton', 'state_id' => 3932],
                ['name' => 'Tallapoosa', 'state_id' => 3932],
                ['name' => 'Waco', 'state_id' => 3932],
                ['name' => 'Cataula', 'state_id' => 3932],
                ['name' => 'Ellerslie', 'state_id' => 3932],
                ['name' => 'Hamilton', 'state_id' => 3932],
                ['name' => 'Pine Mountain', 'state_id' => 3932],
                ['name' => 'Pine Mountain Valley', 'state_id' => 3932],
                ['name' => 'Shiloh', 'state_id' => 3932],
                ['name' => 'Waverly Hall', 'state_id' => 3932],
                ['name' => 'Bowersville', 'state_id' => 3932],
                ['name' => 'Hartwell', 'state_id' => 3932],
                ['name' => 'Franklin', 'state_id' => 3932],
                ['name' => 'Hampton', 'state_id' => 3932],
                ['name' => 'Locust Grove', 'state_id' => 3932],
                ['name' => 'Mcdonough', 'state_id' => 3932],
                ['name' => 'Stockbridge', 'state_id' => 3932],
                ['name' => 'Bonaire', 'state_id' => 3932],
                ['name' => 'Clinchfield', 'state_id' => 3932],
                ['name' => 'Elko', 'state_id' => 3932],
                ['name' => 'Centerville', 'state_id' => 3932],
                ['name' => 'Kathleen', 'state_id' => 3932],
                ['name' => 'Perry', 'state_id' => 3932],
                ['name' => 'Warner Robins', 'state_id' => 3932],
                ['name' => 'Irwinville', 'state_id' => 3932],
                ['name' => 'Mystic', 'state_id' => 3932],
                ['name' => 'Ocilla', 'state_id' => 3932],
                ['name' => 'Wray', 'state_id' => 3932],
                ['name' => 'Braselton', 'state_id' => 3932],
                ['name' => 'Commerce', 'state_id' => 3932],
                ['name' => 'Hoschton', 'state_id' => 3932],
                ['name' => 'Jefferson', 'state_id' => 3932],
                ['name' => 'Nicholson', 'state_id' => 3932],
                ['name' => 'Pendergrass', 'state_id' => 3932],
                ['name' => 'Talmo', 'state_id' => 3932],
                ['name' => 'Mansfield', 'state_id' => 3932],
                ['name' => 'Hillsboro', 'state_id' => 3932],
                ['name' => 'Monticello', 'state_id' => 3932],
                ['name' => 'Shady Dale', 'state_id' => 3932],
                ['name' => 'Denton', 'state_id' => 3932],
                ['name' => 'Hazlehurst', 'state_id' => 3932],
                ['name' => 'Bartow', 'state_id' => 3932],
                ['name' => 'Louisville', 'state_id' => 3932],
                ['name' => 'Wadley', 'state_id' => 3932],
                ['name' => 'Avera', 'state_id' => 3932],
                ['name' => 'Matthews', 'state_id' => 3932],
                ['name' => 'Stapleton', 'state_id' => 3932],
                ['name' => 'Wrens', 'state_id' => 3932],
                ['name' => 'Millen', 'state_id' => 3932],
                ['name' => 'Perkins', 'state_id' => 3932],
                ['name' => 'Kite', 'state_id' => 3932],
                ['name' => 'Wrightsville', 'state_id' => 3932],
                ['name' => 'Gray', 'state_id' => 3932],
                ['name' => 'Haddock', 'state_id' => 3932],
                ['name' => 'Barnesville', 'state_id' => 3932],
                ['name' => 'Milner', 'state_id' => 3932],
                ['name' => 'Lakeland', 'state_id' => 3932],
                ['name' => 'Stockton', 'state_id' => 3932],
                ['name' => 'Rockledge', 'state_id' => 3932],
                ['name' => 'Cadwell', 'state_id' => 3932],
                ['name' => 'Dexter', 'state_id' => 3932],
                ['name' => 'Dublin', 'state_id' => 3932],
                ['name' => 'Dudley', 'state_id' => 3932],
                ['name' => 'East Dublin', 'state_id' => 3932],
                ['name' => 'Montrose', 'state_id' => 3932],
                ['name' => 'Rentz', 'state_id' => 3932],
                ['name' => 'Leesburg', 'state_id' => 3932],
                ['name' => 'Smithville', 'state_id' => 3932],
                ['name' => 'Allenhurst', 'state_id' => 3932],
                ['name' => 'Fleming', 'state_id' => 3932],
                ['name' => 'Hinesville', 'state_id' => 3932],
                ['name' => 'Fort Stewart', 'state_id' => 3932],
                ['name' => 'Midway', 'state_id' => 3932],
                ['name' => 'Riceboro', 'state_id' => 3932],
                ['name' => 'Walthourville', 'state_id' => 3932],
                ['name' => 'Lincolnton', 'state_id' => 3932],
                ['name' => 'Ludowici', 'state_id' => 3932],
                ['name' => 'Valdosta', 'state_id' => 3932],
                ['name' => 'Hahira', 'state_id' => 3932],
                ['name' => 'Lake Park', 'state_id' => 3932],
                ['name' => 'Naylor', 'state_id' => 3932],
                ['name' => 'Moody Afb', 'state_id' => 3932],
                ['name' => 'Dahlonega', 'state_id' => 3932],
                ['name' => 'Boneville', 'state_id' => 3932],
                ['name' => 'Dearing', 'state_id' => 3932],
                ['name' => 'Thomson', 'state_id' => 3932],
                ['name' => 'Crescent', 'state_id' => 3932],
                ['name' => 'Darien', 'state_id' => 3932],
                ['name' => 'Meridian', 'state_id' => 3932],
                ['name' => 'Sapelo Island', 'state_id' => 3932],
                ['name' => 'Townsend', 'state_id' => 3932],
                ['name' => 'Ideal', 'state_id' => 3932],
                ['name' => 'Marshallville', 'state_id' => 3932],
                ['name' => 'Oglethorpe', 'state_id' => 3932],
                ['name' => 'Carlton', 'state_id' => 3932],
                ['name' => 'Colbert', 'state_id' => 3932],
                ['name' => 'Comer', 'state_id' => 3932],
                ['name' => 'Danielsville', 'state_id' => 3932],
                ['name' => 'Hull', 'state_id' => 3932],
                ['name' => 'Ila', 'state_id' => 3932],
                ['name' => 'Buena Vista', 'state_id' => 3932],
                ['name' => 'Gay', 'state_id' => 3932],
                ['name' => 'Greenville', 'state_id' => 3932],
                ['name' => 'Luthersville', 'state_id' => 3932],
                ['name' => 'Woodbury', 'state_id' => 3932],
                ['name' => 'Manchester', 'state_id' => 3932],
                ['name' => 'Warm Springs', 'state_id' => 3932],
                ['name' => 'Baconton', 'state_id' => 3932],
                ['name' => 'Camilla', 'state_id' => 3932],
                ['name' => 'Cotton', 'state_id' => 3932],
                ['name' => 'Pelham', 'state_id' => 3932],
                ['name' => 'Sale City', 'state_id' => 3932],
                ['name' => 'Bolingbroke', 'state_id' => 3932],
                ['name' => 'Culloden', 'state_id' => 3932],
                ['name' => 'Forsyth', 'state_id' => 3932],
                ['name' => 'Juliette', 'state_id' => 3932],
                ['name' => 'Smarr', 'state_id' => 3932],
                ['name' => 'Ailey', 'state_id' => 3932],
                ['name' => 'Alston', 'state_id' => 3932],
                ['name' => 'Mount Vernon', 'state_id' => 3932],
                ['name' => 'Tarrytown', 'state_id' => 3932],
                ['name' => 'Uvalda', 'state_id' => 3932],
                ['name' => 'Bostwick', 'state_id' => 3932],
                ['name' => 'Buckhead', 'state_id' => 3932],
                ['name' => 'High Shoals', 'state_id' => 3932],
                ['name' => 'Madison', 'state_id' => 3932],
                ['name' => 'Rutledge', 'state_id' => 3932],
                ['name' => 'Chatsworth', 'state_id' => 3932],
                ['name' => 'Cisco', 'state_id' => 3932],
                ['name' => 'Crandall', 'state_id' => 3932],
                ['name' => 'Eton', 'state_id' => 3932],
                ['name' => 'Tennga', 'state_id' => 3932],
                ['name' => 'Fortson', 'state_id' => 3932],
                ['name' => 'Midland', 'state_id' => 3932],
                ['name' => 'Upatoi', 'state_id' => 3932],
                ['name' => 'Columbus', 'state_id' => 3932],
                ['name' => 'Fort Benning', 'state_id' => 3932],
                ['name' => 'Covington', 'state_id' => 3932],
                ['name' => 'Oxford', 'state_id' => 3932],
                ['name' => 'Newborn', 'state_id' => 3932],
                ['name' => 'Porterdale', 'state_id' => 3932],
                ['name' => 'Bishop', 'state_id' => 3932],
                ['name' => 'Bogart', 'state_id' => 3932],
                ['name' => 'Farmington', 'state_id' => 3932],
                ['name' => 'Watkinsville', 'state_id' => 3932],
                ['name' => 'Arnoldsville', 'state_id' => 3932],
                ['name' => 'Crawford', 'state_id' => 3932],
                ['name' => 'Lexington', 'state_id' => 3932],
                ['name' => 'Stephens', 'state_id' => 3932],
                ['name' => 'Maxeys', 'state_id' => 3932],
                ['name' => 'Dallas', 'state_id' => 3932],
                ['name' => 'Hiram', 'state_id' => 3932],
                ['name' => 'Byron', 'state_id' => 3932],
                ['name' => 'Fort Valley', 'state_id' => 3932],
                ['name' => 'Jasper', 'state_id' => 3932],
                ['name' => 'Marble Hill', 'state_id' => 3932],
                ['name' => 'Talking Rock', 'state_id' => 3932],
                ['name' => 'Tate', 'state_id' => 3932],
                ['name' => 'Blackshear', 'state_id' => 3932],
                ['name' => 'Bristol', 'state_id' => 3932],
                ['name' => 'Mershon', 'state_id' => 3932],
                ['name' => 'Offerman', 'state_id' => 3932],
                ['name' => 'Patterson', 'state_id' => 3932],
                ['name' => 'Concord', 'state_id' => 3932],
                ['name' => 'Meansville', 'state_id' => 3932],
                ['name' => 'Molena', 'state_id' => 3932],
                ['name' => 'Williamson', 'state_id' => 3932],
                ['name' => 'Zebulon', 'state_id' => 3932],
                ['name' => 'Aragon', 'state_id' => 3932],
                ['name' => 'Cedartown', 'state_id' => 3932],
                ['name' => 'Esom Hill', 'state_id' => 3932],
                ['name' => 'Rockmart', 'state_id' => 3932],
                ['name' => 'Hawkinsville', 'state_id' => 3932],
                ['name' => 'Eatonton', 'state_id' => 3932],
                ['name' => 'Clayton', 'state_id' => 3932],
                ['name' => 'Dillard', 'state_id' => 3932],
                ['name' => 'Lakemont', 'state_id' => 3932],
                ['name' => 'Mountain City', 'state_id' => 3932],
                ['name' => 'Rabun Gap', 'state_id' => 3932],
                ['name' => 'Tallulah Falls', 'state_id' => 3932],
                ['name' => 'Tiger', 'state_id' => 3932],
                ['name' => 'Wiley', 'state_id' => 3932],
                ['name' => 'Blythe', 'state_id' => 3932],
                ['name' => 'Gracewood', 'state_id' => 3932],
                ['name' => 'Hephzibah', 'state_id' => 3932],
                ['name' => 'Conyers', 'state_id' => 3932],
                ['name' => 'Ellaville', 'state_id' => 3932],
                ['name' => 'Dover', 'state_id' => 3932],
                ['name' => 'Newington', 'state_id' => 3932],
                ['name' => 'Oliver', 'state_id' => 3932],
                ['name' => 'Rocky Ford', 'state_id' => 3932],
                ['name' => 'Sylvania', 'state_id' => 3932],
                ['name' => 'Brinson', 'state_id' => 3932],
                ['name' => 'Iron City', 'state_id' => 3932],
                ['name' => 'Jakin', 'state_id' => 3932],
                ['name' => 'Experiment', 'state_id' => 3932],
                ['name' => 'Griffin', 'state_id' => 3932],
                ['name' => 'Orchard Hill', 'state_id' => 3932],
                ['name' => 'Sunny Side', 'state_id' => 3932],
                ['name' => 'Eastanollee', 'state_id' => 3932],
                ['name' => 'Martin', 'state_id' => 3932],
                ['name' => 'Toccoa', 'state_id' => 3932],
                ['name' => 'Toccoa Falls', 'state_id' => 3932],
                ['name' => 'Louvale', 'state_id' => 3932],
                ['name' => 'Lumpkin', 'state_id' => 3932],
                ['name' => 'Omaha', 'state_id' => 3932],
                ['name' => 'Richland', 'state_id' => 3932],
                ['name' => 'Americus', 'state_id' => 3932],
                ['name' => 'Andersonville', 'state_id' => 3932],
                ['name' => 'Cobb', 'state_id' => 3932],
                ['name' => 'De Soto', 'state_id' => 3932],
                ['name' => 'Leslie', 'state_id' => 3932],
                ['name' => 'Plains', 'state_id' => 3932],
                ['name' => 'Box Springs', 'state_id' => 3932],
                ['name' => 'Geneva', 'state_id' => 3932],
                ['name' => 'Junction City', 'state_id' => 3932],
                ['name' => 'Talbotton', 'state_id' => 3932],
                ['name' => 'Woodland', 'state_id' => 3932],
                ['name' => 'Crawfordville', 'state_id' => 3932],
                ['name' => 'Sharon', 'state_id' => 3932],
                ['name' => 'Cobbtown', 'state_id' => 3932],
                ['name' => 'Collins', 'state_id' => 3932],
                ['name' => 'Glennville', 'state_id' => 3932],
                ['name' => 'Manassas', 'state_id' => 3932],
                ['name' => 'Reidsville', 'state_id' => 3932],
                ['name' => 'Butler', 'state_id' => 3932],
                ['name' => 'Howard', 'state_id' => 3932],
                ['name' => 'Mauk', 'state_id' => 3932],
                ['name' => 'Reynolds', 'state_id' => 3932],
                ['name' => 'Rupert', 'state_id' => 3932],
                ['name' => 'Mc Rae Helena', 'state_id' => 3932],
                ['name' => 'Milan', 'state_id' => 3932],
                ['name' => 'Scotland', 'state_id' => 3932],
                ['name' => 'Jacksonville', 'state_id' => 3932],
                ['name' => 'Lumber City', 'state_id' => 3932],
                ['name' => 'Bronwood', 'state_id' => 3932],
                ['name' => 'Sasser', 'state_id' => 3932],
                ['name' => 'Boston', 'state_id' => 3932],
                ['name' => 'Coolidge', 'state_id' => 3932],
                ['name' => 'Thomasville', 'state_id' => 3932],
                ['name' => 'Meigs', 'state_id' => 3932],
                ['name' => 'Ochlocknee', 'state_id' => 3932],
                ['name' => 'Pavo', 'state_id' => 3932],
                ['name' => 'Brookfield', 'state_id' => 3932],
                ['name' => 'Chula', 'state_id' => 3932],
                ['name' => 'Omega', 'state_id' => 3932],
                ['name' => 'Tifton', 'state_id' => 3932],
                ['name' => 'Ty Ty', 'state_id' => 3932],
                ['name' => 'Lyons', 'state_id' => 3932],
                ['name' => 'Vidalia', 'state_id' => 3932],
                ['name' => 'Hiawassee', 'state_id' => 3932],
                ['name' => 'Young Harris', 'state_id' => 3932],
                ['name' => 'Soperton', 'state_id' => 3932],
                ['name' => 'Hogansville', 'state_id' => 3932],
                ['name' => 'Lagrange', 'state_id' => 3932],
                ['name' => 'West Point', 'state_id' => 3932],
                ['name' => 'Ashburn', 'state_id' => 3932],
                ['name' => 'Rebecca', 'state_id' => 3932],
                ['name' => 'Sycamore', 'state_id' => 3932],
                ['name' => 'Danville', 'state_id' => 3932],
                ['name' => 'Dry Branch', 'state_id' => 3932],
                ['name' => 'Jeffersonville', 'state_id' => 3932],
                ['name' => 'Blairsville', 'state_id' => 3932],
                ['name' => 'Suches', 'state_id' => 3932],
                ['name' => 'The Rock', 'state_id' => 3932],
                ['name' => 'Thomaston', 'state_id' => 3932],
                ['name' => 'Yatesville', 'state_id' => 3932],
                ['name' => 'Chickamauga', 'state_id' => 3932],
                ['name' => 'Flintstone', 'state_id' => 3932],
                ['name' => 'La Fayette', 'state_id' => 3932],
                ['name' => 'Rock Spring', 'state_id' => 3932],
                ['name' => 'Rossville', 'state_id' => 3932],
                ['name' => 'Lookout Mountain', 'state_id' => 3932],
                ['name' => 'Jersey', 'state_id' => 3932],
                ['name' => 'Social Circle', 'state_id' => 3932],
                ['name' => 'Good Hope', 'state_id' => 3932],
                ['name' => 'Monroe', 'state_id' => 3932],
                ['name' => 'Waycross', 'state_id' => 3932],
                ['name' => 'Manor', 'state_id' => 3932],
                ['name' => 'Millwood', 'state_id' => 3932],
                ['name' => 'Waresboro', 'state_id' => 3932],
                ['name' => 'Camak', 'state_id' => 3932],
                ['name' => 'Mesena', 'state_id' => 3932],
                ['name' => 'Norwood', 'state_id' => 3932],
                ['name' => 'Warrenton', 'state_id' => 3932],
                ['name' => 'Jewell', 'state_id' => 3932],
                ['name' => 'Davisboro', 'state_id' => 3932],
                ['name' => 'Harrison', 'state_id' => 3932],
                ['name' => 'Oconee', 'state_id' => 3932],
                ['name' => 'Sandersville', 'state_id' => 3932],
                ['name' => 'Tennille', 'state_id' => 3932],
                ['name' => 'Warthen', 'state_id' => 3932],
                ['name' => 'Jesup', 'state_id' => 3932],
                ['name' => 'Odum', 'state_id' => 3932],
                ['name' => 'Screven', 'state_id' => 3932],
                ['name' => 'Preston', 'state_id' => 3932],
                ['name' => 'Weston', 'state_id' => 3932],
                ['name' => 'Parrott', 'state_id' => 3932],
                ['name' => 'Alamo', 'state_id' => 3932],
                ['name' => 'Glenwood', 'state_id' => 3932],
                ['name' => 'Cleveland', 'state_id' => 3932],
                ['name' => 'Helen', 'state_id' => 3932],
                ['name' => 'Sautee Nacoochee', 'state_id' => 3932],
                ['name' => 'Cohutta', 'state_id' => 3932],
                ['name' => 'Dalton', 'state_id' => 3932],
                ['name' => 'Rocky Face', 'state_id' => 3932],
                ['name' => 'Tunnel Hill', 'state_id' => 3932],
                ['name' => 'Varnell', 'state_id' => 3932],
                ['name' => 'Abbeville', 'state_id' => 3932],
                ['name' => 'Pineview', 'state_id' => 3932],
                ['name' => 'Pitts', 'state_id' => 3932],
                ['name' => 'Rochelle', 'state_id' => 3932],
                ['name' => 'Seville', 'state_id' => 3932],
                ['name' => 'Rayle', 'state_id' => 3932],
                ['name' => 'Tignall', 'state_id' => 3932],
                ['name' => 'Washington', 'state_id' => 3932],
                ['name' => 'Allentown', 'state_id' => 3932],
                ['name' => 'Gordon', 'state_id' => 3932],
                ['name' => 'Irwinton', 'state_id' => 3932],
                ['name' => 'Mc Intyre', 'state_id' => 3932],
                ['name' => 'Toomsboro', 'state_id' => 3932],
                ['name' => 'Oakfield', 'state_id' => 3932],
                ['name' => 'Poulan', 'state_id' => 3932],
                ['name' => 'Sumner', 'state_id' => 3932],
                ['name' => 'Sylvester', 'state_id' => 3932],
                ['name' => 'Warwick', 'state_id' => 3932]
            ]);
        }
    }
}
