<?php

use Illuminate\Database\Seeder;

class state4TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AZ - Arizona.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Alpine', 'state_id' => 3922],
                ['name' => 'Concho', 'state_id' => 3922],
                ['name' => 'Eagar', 'state_id' => 3922],
                ['name' => 'Greer', 'state_id' => 3922],
                ['name' => 'Mcnary', 'state_id' => 3922],
                ['name' => 'Nutrioso', 'state_id' => 3922],
                ['name' => 'Saint Johns', 'state_id' => 3922],
                ['name' => 'Springerville', 'state_id' => 3922],
                ['name' => 'Vernon', 'state_id' => 3922],
                ['name' => 'Petrified Forest Natl Pk', 'state_id' => 3922],
                ['name' => 'Chambers', 'state_id' => 3922],
                ['name' => 'Chinle', 'state_id' => 3922],
                ['name' => 'Fort Defiance', 'state_id' => 3922],
                ['name' => 'Ganado', 'state_id' => 3922],
                ['name' => 'Houck', 'state_id' => 3922],
                ['name' => 'Lukachukai', 'state_id' => 3922],
                ['name' => 'Lupton', 'state_id' => 3922],
                ['name' => 'Saint Michaels', 'state_id' => 3922],
                ['name' => 'Sanders', 'state_id' => 3922],
                ['name' => 'Teec Nos Pos', 'state_id' => 3922],
                ['name' => 'Window Rock', 'state_id' => 3922],
                ['name' => 'Dennehotso', 'state_id' => 3922],
                ['name' => 'Many Farms', 'state_id' => 3922],
                ['name' => 'Nazlini', 'state_id' => 3922],
                ['name' => 'Red Valley', 'state_id' => 3922],
                ['name' => 'Rock Point', 'state_id' => 3922],
                ['name' => 'Round Rock', 'state_id' => 3922],
                ['name' => 'Tsaile', 'state_id' => 3922],
                ['name' => 'Benson', 'state_id' => 3922],
                ['name' => 'Bisbee', 'state_id' => 3922],
                ['name' => 'Bowie', 'state_id' => 3922],
                ['name' => 'Cochise', 'state_id' => 3922],
                ['name' => 'Douglas', 'state_id' => 3922],
                ['name' => 'Dragoon', 'state_id' => 3922],
                ['name' => 'Elfrida', 'state_id' => 3922],
                ['name' => 'Fort Huachuca', 'state_id' => 3922],
                ['name' => 'Hereford', 'state_id' => 3922],
                ['name' => 'Huachuca City', 'state_id' => 3922],
                ['name' => 'Mc Neal', 'state_id' => 3922],
                ['name' => 'Naco', 'state_id' => 3922],
                ['name' => 'Pearce', 'state_id' => 3922],
                ['name' => 'Pirtleville', 'state_id' => 3922],
                ['name' => 'Pomerene', 'state_id' => 3922],
                ['name' => 'Saint David', 'state_id' => 3922],
                ['name' => 'San Simon', 'state_id' => 3922],
                ['name' => 'Sierra Vista', 'state_id' => 3922],
                ['name' => 'Tombstone', 'state_id' => 3922],
                ['name' => 'Willcox', 'state_id' => 3922],
                ['name' => 'Forest Lakes', 'state_id' => 3922],
                ['name' => 'Flagstaff', 'state_id' => 3922],
                ['name' => 'Bellemont', 'state_id' => 3922],
                ['name' => 'Gray Mountain', 'state_id' => 3922],
                ['name' => 'Munds Park', 'state_id' => 3922],
                ['name' => 'Parks', 'state_id' => 3922],
                ['name' => 'Cameron', 'state_id' => 3922],
                ['name' => 'Fredonia', 'state_id' => 3922],
                ['name' => 'Grand Canyon', 'state_id' => 3922],
                ['name' => 'Happy Jack', 'state_id' => 3922],
                ['name' => 'Leupp', 'state_id' => 3922],
                ['name' => 'Marble Canyon', 'state_id' => 3922],
                ['name' => 'Mormon Lake', 'state_id' => 3922],
                ['name' => 'Page', 'state_id' => 3922],
                ['name' => 'Tonalea', 'state_id' => 3922],
                ['name' => 'Tuba City', 'state_id' => 3922],
                ['name' => 'Williams', 'state_id' => 3922],
                ['name' => 'North Rim', 'state_id' => 3922],
                ['name' => 'Kaibeto', 'state_id' => 3922],
                ['name' => 'Sedona', 'state_id' => 3922],
                ['name' => 'Supai', 'state_id' => 3922],
                ['name' => 'Hayden', 'state_id' => 3922],
                ['name' => 'Winkelman', 'state_id' => 3922],
                ['name' => 'Globe', 'state_id' => 3922],
                ['name' => 'Claypool', 'state_id' => 3922],
                ['name' => 'Miami', 'state_id' => 3922],
                ['name' => 'Payson', 'state_id' => 3922],
                ['name' => 'Peridot', 'state_id' => 3922],
                ['name' => 'Pine', 'state_id' => 3922],
                ['name' => 'Roosevelt', 'state_id' => 3922],
                ['name' => 'San Carlos', 'state_id' => 3922],
                ['name' => 'Tonto Basin', 'state_id' => 3922],
                ['name' => 'Young', 'state_id' => 3922],
                ['name' => 'Bylas', 'state_id' => 3922],
                ['name' => 'Central', 'state_id' => 3922],
                ['name' => 'Eden', 'state_id' => 3922],
                ['name' => 'Fort Thomas', 'state_id' => 3922],
                ['name' => 'Pima', 'state_id' => 3922],
                ['name' => 'Safford', 'state_id' => 3922],
                ['name' => 'Solomon', 'state_id' => 3922],
                ['name' => 'Thatcher', 'state_id' => 3922],
                ['name' => 'Clifton', 'state_id' => 3922],
                ['name' => 'Duncan', 'state_id' => 3922],
                ['name' => 'Morenci', 'state_id' => 3922],
                ['name' => 'Blue', 'state_id' => 3922],
                ['name' => 'Bouse', 'state_id' => 3922],
                ['name' => 'Cibola', 'state_id' => 3922],
                ['name' => 'Ehrenberg', 'state_id' => 3922],
                ['name' => 'Parker', 'state_id' => 3922],
                ['name' => 'Quartzsite', 'state_id' => 3922],
                ['name' => 'Salome', 'state_id' => 3922],
                ['name' => 'Wenden', 'state_id' => 3922],
                ['name' => 'Poston', 'state_id' => 3922],
                ['name' => 'Phoenix', 'state_id' => 3922],
                ['name' => 'New River', 'state_id' => 3922],
                ['name' => 'Chandler Heights', 'state_id' => 3922],
                ['name' => 'Queen Creek', 'state_id' => 3922],
                ['name' => 'Tortilla Flat', 'state_id' => 3922],
                ['name' => 'Mesa', 'state_id' => 3922],
                ['name' => 'Chandler', 'state_id' => 3922],
                ['name' => 'Gilbert', 'state_id' => 3922],
                ['name' => 'Higley', 'state_id' => 3922],
                ['name' => 'Scottsdale', 'state_id' => 3922],
                ['name' => 'Paradise Valley', 'state_id' => 3922],
                ['name' => 'Rio Verde', 'state_id' => 3922],
                ['name' => 'Fort Mcdowell', 'state_id' => 3922],
                ['name' => 'Fountain Hills', 'state_id' => 3922],
                ['name' => 'Tempe', 'state_id' => 3922],
                ['name' => 'Glendale', 'state_id' => 3922],
                ['name' => 'Luke Air Force Base', 'state_id' => 3922],
                ['name' => 'Aguila', 'state_id' => 3922],
                ['name' => 'Arlington', 'state_id' => 3922],
                ['name' => 'Avondale', 'state_id' => 3922],
                ['name' => 'Buckeye', 'state_id' => 3922],
                ['name' => 'Cave Creek', 'state_id' => 3922],
                ['name' => 'Cashion', 'state_id' => 3922],
                ['name' => 'El Mirage', 'state_id' => 3922],
                ['name' => 'Gila Bend', 'state_id' => 3922],
                ['name' => 'Goodyear', 'state_id' => 3922],
                ['name' => 'Laveen', 'state_id' => 3922],
                ['name' => 'Litchfield Park', 'state_id' => 3922],
                ['name' => 'Morristown', 'state_id' => 3922],
                ['name' => 'Palo Verde', 'state_id' => 3922],
                ['name' => 'Peoria', 'state_id' => 3922],
                ['name' => 'Sun City', 'state_id' => 3922],
                ['name' => 'Tolleson', 'state_id' => 3922],
                ['name' => 'Tonopah', 'state_id' => 3922],
                ['name' => 'Waddell', 'state_id' => 3922],
                ['name' => 'Wickenburg', 'state_id' => 3922],
                ['name' => 'Wittmann', 'state_id' => 3922],
                ['name' => 'Youngtown', 'state_id' => 3922],
                ['name' => 'Surprise', 'state_id' => 3922],
                ['name' => 'Sun City West', 'state_id' => 3922],
                ['name' => 'Carefree', 'state_id' => 3922],
                ['name' => 'Wikieup', 'state_id' => 3922],
                ['name' => 'Colorado City', 'state_id' => 3922],
                ['name' => 'Kingman', 'state_id' => 3922],
                ['name' => 'Lake Havasu City', 'state_id' => 3922],
                ['name' => 'Hackberry', 'state_id' => 3922],
                ['name' => 'Hualapai', 'state_id' => 3922],
                ['name' => 'Golden Valley', 'state_id' => 3922],
                ['name' => 'Fort Mohave', 'state_id' => 3922],
                ['name' => 'Bullhead City', 'state_id' => 3922],
                ['name' => 'Chloride', 'state_id' => 3922],
                ['name' => 'Littlefield', 'state_id' => 3922],
                ['name' => 'Oatman', 'state_id' => 3922],
                ['name' => 'Peach Springs', 'state_id' => 3922],
                ['name' => 'Topock', 'state_id' => 3922],
                ['name' => 'Valentine', 'state_id' => 3922],
                ['name' => 'Yucca', 'state_id' => 3922],
                ['name' => 'Mohave Valley', 'state_id' => 3922],
                ['name' => 'Dolan Springs', 'state_id' => 3922],
                ['name' => 'Temple Bar Marina', 'state_id' => 3922],
                ['name' => 'Meadview', 'state_id' => 3922],
                ['name' => 'Willow Beach', 'state_id' => 3922],
                ['name' => 'Show Low', 'state_id' => 3922],
                ['name' => 'Cibecue', 'state_id' => 3922],
                ['name' => 'White Mountain Lake', 'state_id' => 3922],
                ['name' => 'Clay Springs', 'state_id' => 3922],
                ['name' => 'Fort Apache', 'state_id' => 3922],
                ['name' => 'Heber', 'state_id' => 3922],
                ['name' => 'Lakeside', 'state_id' => 3922],
                ['name' => 'Overgaard', 'state_id' => 3922],
                ['name' => 'Pinedale', 'state_id' => 3922],
                ['name' => 'Pinetop', 'state_id' => 3922],
                ['name' => 'Snowflake', 'state_id' => 3922],
                ['name' => 'Taylor', 'state_id' => 3922],
                ['name' => 'Whiteriver', 'state_id' => 3922],
                ['name' => 'Woodruff', 'state_id' => 3922],
                ['name' => 'Holbrook', 'state_id' => 3922],
                ['name' => 'Sun Valley', 'state_id' => 3922],
                ['name' => 'Hotevilla', 'state_id' => 3922],
                ['name' => 'Indian Wells', 'state_id' => 3922],
                ['name' => 'Joseph City', 'state_id' => 3922],
                ['name' => 'Kayenta', 'state_id' => 3922],
                ['name' => 'Keams Canyon', 'state_id' => 3922],
                ['name' => 'Kykotsmovi Village', 'state_id' => 3922],
                ['name' => 'Polacca', 'state_id' => 3922],
                ['name' => 'Second Mesa', 'state_id' => 3922],
                ['name' => 'Winslow', 'state_id' => 3922],
                ['name' => 'Shonto', 'state_id' => 3922],
                ['name' => 'Pinon', 'state_id' => 3922],
                ['name' => 'Blue Gap', 'state_id' => 3922],
                ['name' => 'Ajo', 'state_id' => 3922],
                ['name' => 'Lukeville', 'state_id' => 3922],
                ['name' => 'Arivaca', 'state_id' => 3922],
                ['name' => 'Green Valley', 'state_id' => 3922],
                ['name' => 'Mount Lemmon', 'state_id' => 3922],
                ['name' => 'Sahuarita', 'state_id' => 3922],
                ['name' => 'Sasabe', 'state_id' => 3922],
                ['name' => 'Sells', 'state_id' => 3922],
                ['name' => 'Topawa', 'state_id' => 3922],
                ['name' => 'Vail', 'state_id' => 3922],
                ['name' => 'Cortaro', 'state_id' => 3922],
                ['name' => 'Marana', 'state_id' => 3922],
                ['name' => 'Rillito', 'state_id' => 3922],
                ['name' => 'Tucson', 'state_id' => 3922],
                ['name' => 'Catalina', 'state_id' => 3922],
                ['name' => 'Apache Junction', 'state_id' => 3922],
                ['name' => 'Gold Canyon', 'state_id' => 3922],
                ['name' => 'Bapchule', 'state_id' => 3922],
                ['name' => 'Casa Grande', 'state_id' => 3922],
                ['name' => 'Arizona City', 'state_id' => 3922],
                ['name' => 'Coolidge', 'state_id' => 3922],
                ['name' => 'Eloy', 'state_id' => 3922],
                ['name' => 'Florence', 'state_id' => 3922],
                ['name' => 'Kearny', 'state_id' => 3922],
                ['name' => 'Maricopa', 'state_id' => 3922],
                ['name' => 'San Tan Valley', 'state_id' => 3922],
                ['name' => 'Picacho', 'state_id' => 3922],
                ['name' => 'Red Rock', 'state_id' => 3922],
                ['name' => 'Sacaton', 'state_id' => 3922],
                ['name' => 'Stanfield', 'state_id' => 3922],
                ['name' => 'Superior', 'state_id' => 3922],
                ['name' => 'Valley Farms', 'state_id' => 3922],
                ['name' => 'Mammoth', 'state_id' => 3922],
                ['name' => 'Oracle', 'state_id' => 3922],
                ['name' => 'San Manuel', 'state_id' => 3922],
                ['name' => 'Elgin', 'state_id' => 3922],
                ['name' => 'Nogales', 'state_id' => 3922],
                ['name' => 'Patagonia', 'state_id' => 3922],
                ['name' => 'Sonoita', 'state_id' => 3922],
                ['name' => 'Tumacacori', 'state_id' => 3922],
                ['name' => 'Amado', 'state_id' => 3922],
                ['name' => 'Tubac', 'state_id' => 3922],
                ['name' => 'Rio Rico', 'state_id' => 3922],
                ['name' => 'Black Canyon City', 'state_id' => 3922],
                ['name' => 'Congress', 'state_id' => 3922],
                ['name' => 'Yarnell', 'state_id' => 3922],
                ['name' => 'Prescott', 'state_id' => 3922],
                ['name' => 'Prescott Valley', 'state_id' => 3922],
                ['name' => 'Ash Fork', 'state_id' => 3922],
                ['name' => 'Bagdad', 'state_id' => 3922],
                ['name' => 'Camp Verde', 'state_id' => 3922],
                ['name' => 'Chino Valley', 'state_id' => 3922],
                ['name' => 'Clarkdale', 'state_id' => 3922],
                ['name' => 'Cornville', 'state_id' => 3922],
                ['name' => 'Cottonwood', 'state_id' => 3922],
                ['name' => 'Dewey', 'state_id' => 3922],
                ['name' => 'Humboldt', 'state_id' => 3922],
                ['name' => 'Jerome', 'state_id' => 3922],
                ['name' => 'Kirkland', 'state_id' => 3922],
                ['name' => 'Mayer', 'state_id' => 3922],
                ['name' => 'Paulden', 'state_id' => 3922],
                ['name' => 'Rimrock', 'state_id' => 3922],
                ['name' => 'Seligman', 'state_id' => 3922],
                ['name' => 'Skull Valley', 'state_id' => 3922],
                ['name' => 'Lake Montezuma', 'state_id' => 3922],
                ['name' => 'Crown King', 'state_id' => 3922],
                ['name' => 'Dateland', 'state_id' => 3922],
                ['name' => 'Gadsden', 'state_id' => 3922],
                ['name' => 'Roll', 'state_id' => 3922],
                ['name' => 'San Luis', 'state_id' => 3922],
                ['name' => 'Somerton', 'state_id' => 3922],
                ['name' => 'Tacna', 'state_id' => 3922],
                ['name' => 'Wellton', 'state_id' => 3922],
                ['name' => 'Yuma', 'state_id' => 3922]
            ]);
        }
    }
}
