<?php

use Illuminate\Database\Seeder;

class state28TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NC - North Carolina.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Alamance', 'state_id' => 3958],
                ['name' => 'Altamahaw', 'state_id' => 3958],
                ['name' => 'Burlington', 'state_id' => 3958],
                ['name' => 'Elon', 'state_id' => 3958],
                ['name' => 'Graham', 'state_id' => 3958],
                ['name' => 'Haw River', 'state_id' => 3958],
                ['name' => 'Mebane', 'state_id' => 3958],
                ['name' => 'Saxapahaw', 'state_id' => 3958],
                ['name' => 'Snow Camp', 'state_id' => 3958],
                ['name' => 'Swepsonville', 'state_id' => 3958],
                ['name' => 'Hiddenite', 'state_id' => 3958],
                ['name' => 'Stony Point', 'state_id' => 3958],
                ['name' => 'Taylorsville', 'state_id' => 3958],
                ['name' => 'Ennice', 'state_id' => 3958],
                ['name' => 'Glade Valley', 'state_id' => 3958],
                ['name' => 'Piney Creek', 'state_id' => 3958],
                ['name' => 'Roaring Gap', 'state_id' => 3958],
                ['name' => 'Sparta', 'state_id' => 3958],
                ['name' => 'Ansonville', 'state_id' => 3958],
                ['name' => 'Lilesville', 'state_id' => 3958],
                ['name' => 'Mc Farlan', 'state_id' => 3958],
                ['name' => 'Morven', 'state_id' => 3958],
                ['name' => 'Peachland', 'state_id' => 3958],
                ['name' => 'Polkton', 'state_id' => 3958],
                ['name' => 'Wadesboro', 'state_id' => 3958],
                ['name' => 'Creston', 'state_id' => 3958],
                ['name' => 'Crumpler', 'state_id' => 3958],
                ['name' => 'Fleetwood', 'state_id' => 3958],
                ['name' => 'Glendale Springs', 'state_id' => 3958],
                ['name' => 'Grassy Creek', 'state_id' => 3958],
                ['name' => 'Jefferson', 'state_id' => 3958],
                ['name' => 'Lansing', 'state_id' => 3958],
                ['name' => 'Laurel Springs', 'state_id' => 3958],
                ['name' => 'Scottville', 'state_id' => 3958],
                ['name' => 'Todd', 'state_id' => 3958],
                ['name' => 'Warrensville', 'state_id' => 3958],
                ['name' => 'West Jefferson', 'state_id' => 3958],
                ['name' => 'Banner Elk', 'state_id' => 3958],
                ['name' => 'Crossnore', 'state_id' => 3958],
                ['name' => 'Elk Park', 'state_id' => 3958],
                ['name' => 'Linville', 'state_id' => 3958],
                ['name' => 'Minneapolis', 'state_id' => 3958],
                ['name' => 'Montezuma', 'state_id' => 3958],
                ['name' => 'Newland', 'state_id' => 3958],
                ['name' => 'Pineola', 'state_id' => 3958],
                ['name' => 'Plumtree', 'state_id' => 3958],
                ['name' => 'Aurora', 'state_id' => 3958],
                ['name' => 'Bath', 'state_id' => 3958],
                ['name' => 'Belhaven', 'state_id' => 3958],
                ['name' => 'Blounts Creek', 'state_id' => 3958],
                ['name' => 'Chocowinity', 'state_id' => 3958],
                ['name' => 'Edward', 'state_id' => 3958],
                ['name' => 'Pantego', 'state_id' => 3958],
                ['name' => 'Pinetown', 'state_id' => 3958],
                ['name' => 'Washington', 'state_id' => 3958],
                ['name' => 'Aulander', 'state_id' => 3958],
                ['name' => 'Kelford', 'state_id' => 3958],
                ['name' => 'Lewiston Woodville', 'state_id' => 3958],
                ['name' => 'Roxobel', 'state_id' => 3958],
                ['name' => 'Colerain', 'state_id' => 3958],
                ['name' => 'Merry Hill', 'state_id' => 3958],
                ['name' => 'Powellsville', 'state_id' => 3958],
                ['name' => 'Windsor', 'state_id' => 3958],
                ['name' => 'Bladenboro', 'state_id' => 3958],
                ['name' => 'Dublin', 'state_id' => 3958],
                ['name' => 'Elizabethtown', 'state_id' => 3958],
                ['name' => 'Tar Heel', 'state_id' => 3958],
                ['name' => 'White Oak', 'state_id' => 3958],
                ['name' => 'Clarkton', 'state_id' => 3958],
                ['name' => 'Council', 'state_id' => 3958],
                ['name' => 'Kelly', 'state_id' => 3958],
                ['name' => 'Wilmington', 'state_id' => 3958],
                ['name' => 'Ash', 'state_id' => 3958],
                ['name' => 'Bolivia', 'state_id' => 3958],
                ['name' => 'Leland', 'state_id' => 3958],
                ['name' => 'Longwood', 'state_id' => 3958],
                ['name' => 'Shallotte', 'state_id' => 3958],
                ['name' => 'Southport', 'state_id' => 3958],
                ['name' => 'Supply', 'state_id' => 3958],
                ['name' => 'Oak Island', 'state_id' => 3958],
                ['name' => 'Calabash', 'state_id' => 3958],
                ['name' => 'Sunset Beach', 'state_id' => 3958],
                ['name' => 'Ocean Isle Beach', 'state_id' => 3958],
                ['name' => 'Winnabow', 'state_id' => 3958],
                ['name' => 'Alexander', 'state_id' => 3958],
                ['name' => 'Arden', 'state_id' => 3958],
                ['name' => 'Barnardsville', 'state_id' => 3958],
                ['name' => 'Black Mountain', 'state_id' => 3958],
                ['name' => 'Candler', 'state_id' => 3958],
                ['name' => 'Enka', 'state_id' => 3958],
                ['name' => 'Fairview', 'state_id' => 3958],
                ['name' => 'Leicester', 'state_id' => 3958],
                ['name' => 'Montreat', 'state_id' => 3958],
                ['name' => 'Mills River', 'state_id' => 3958],
                ['name' => 'Ridgecrest', 'state_id' => 3958],
                ['name' => 'Skyland', 'state_id' => 3958],
                ['name' => 'Swannanoa', 'state_id' => 3958],
                ['name' => 'Weaverville', 'state_id' => 3958],
                ['name' => 'Asheville', 'state_id' => 3958],
                ['name' => 'Connelly Springs', 'state_id' => 3958],
                ['name' => 'Drexel', 'state_id' => 3958],
                ['name' => 'Glen Alpine', 'state_id' => 3958],
                ['name' => 'Hildebran', 'state_id' => 3958],
                ['name' => 'Jonas Ridge', 'state_id' => 3958],
                ['name' => 'Linville Falls', 'state_id' => 3958],
                ['name' => 'Morganton', 'state_id' => 3958],
                ['name' => 'Icard', 'state_id' => 3958],
                ['name' => 'Rutherford College', 'state_id' => 3958],
                ['name' => 'Valdese', 'state_id' => 3958],
                ['name' => 'Concord', 'state_id' => 3958],
                ['name' => 'Harrisburg', 'state_id' => 3958],
                ['name' => 'Kannapolis', 'state_id' => 3958],
                ['name' => 'Midland', 'state_id' => 3958],
                ['name' => 'Mount Pleasant', 'state_id' => 3958],
                ['name' => 'Collettsville', 'state_id' => 3958],
                ['name' => 'Granite Falls', 'state_id' => 3958],
                ['name' => 'Lenoir', 'state_id' => 3958],
                ['name' => 'Hudson', 'state_id' => 3958],
                ['name' => 'Patterson', 'state_id' => 3958],
                ['name' => 'Rhodhiss', 'state_id' => 3958],
                ['name' => 'Camden', 'state_id' => 3958],
                ['name' => 'Shiloh', 'state_id' => 3958],
                ['name' => 'South Mills', 'state_id' => 3958],
                ['name' => 'Atlantic', 'state_id' => 3958],
                ['name' => 'Atlantic Beach', 'state_id' => 3958],
                ['name' => 'Beaufort', 'state_id' => 3958],
                ['name' => 'Cedar Island', 'state_id' => 3958],
                ['name' => 'Davis', 'state_id' => 3958],
                ['name' => 'Gloucester', 'state_id' => 3958],
                ['name' => 'Harkers Island', 'state_id' => 3958],
                ['name' => 'Marshallberg', 'state_id' => 3958],
                ['name' => 'Morehead City', 'state_id' => 3958],
                ['name' => 'Newport', 'state_id' => 3958],
                ['name' => 'Salter Path', 'state_id' => 3958],
                ['name' => 'Sealevel', 'state_id' => 3958],
                ['name' => 'Smyrna', 'state_id' => 3958],
                ['name' => 'Stacy', 'state_id' => 3958],
                ['name' => 'Stella', 'state_id' => 3958],
                ['name' => 'Williston', 'state_id' => 3958],
                ['name' => 'Emerald Isle', 'state_id' => 3958],
                ['name' => 'Blanch', 'state_id' => 3958],
                ['name' => 'Leasburg', 'state_id' => 3958],
                ['name' => 'Milton', 'state_id' => 3958],
                ['name' => 'Pelham', 'state_id' => 3958],
                ['name' => 'Prospect Hill', 'state_id' => 3958],
                ['name' => 'Providence', 'state_id' => 3958],
                ['name' => 'Yanceyville', 'state_id' => 3958],
                ['name' => 'Hickory', 'state_id' => 3958],
                ['name' => 'Catawba', 'state_id' => 3958],
                ['name' => 'Claremont', 'state_id' => 3958],
                ['name' => 'Conover', 'state_id' => 3958],
                ['name' => 'Maiden', 'state_id' => 3958],
                ['name' => 'Newton', 'state_id' => 3958],
                ['name' => 'Sherrills Ford', 'state_id' => 3958],
                ['name' => 'Terrell', 'state_id' => 3958],
                ['name' => 'Bear Creek', 'state_id' => 3958],
                ['name' => 'Bennett', 'state_id' => 3958],
                ['name' => 'Bonlee', 'state_id' => 3958],
                ['name' => 'Bynum', 'state_id' => 3958],
                ['name' => 'Goldston', 'state_id' => 3958],
                ['name' => 'Gulf', 'state_id' => 3958],
                ['name' => 'Pittsboro', 'state_id' => 3958],
                ['name' => 'Siler City', 'state_id' => 3958],
                ['name' => 'Moncure', 'state_id' => 3958],
                ['name' => 'Topton', 'state_id' => 3958],
                ['name' => 'Andrews', 'state_id' => 3958],
                ['name' => 'Culberson', 'state_id' => 3958],
                ['name' => 'Marble', 'state_id' => 3958],
                ['name' => 'Murphy', 'state_id' => 3958],
                ['name' => 'Edenton', 'state_id' => 3958],
                ['name' => 'Tyner', 'state_id' => 3958],
                ['name' => 'Brasstown', 'state_id' => 3958],
                ['name' => 'Hayesville', 'state_id' => 3958],
                ['name' => 'Warne', 'state_id' => 3958],
                ['name' => 'Boiling Springs', 'state_id' => 3958],
                ['name' => 'Casar', 'state_id' => 3958],
                ['name' => 'Earl', 'state_id' => 3958],
                ['name' => 'Fallston', 'state_id' => 3958],
                ['name' => 'Grover', 'state_id' => 3958],
                ['name' => 'Kings Mountain', 'state_id' => 3958],
                ['name' => 'Lattimore', 'state_id' => 3958],
                ['name' => 'Lawndale', 'state_id' => 3958],
                ['name' => 'Mooresboro', 'state_id' => 3958],
                ['name' => 'Polkville', 'state_id' => 3958],
                ['name' => 'Shelby', 'state_id' => 3958],
                ['name' => 'Waco', 'state_id' => 3958],
                ['name' => 'Bolton', 'state_id' => 3958],
                ['name' => 'Brunswick', 'state_id' => 3958],
                ['name' => 'Cerro Gordo', 'state_id' => 3958],
                ['name' => 'Chadbourn', 'state_id' => 3958],
                ['name' => 'Clarendon', 'state_id' => 3958],
                ['name' => 'Delco', 'state_id' => 3958],
                ['name' => 'Evergreen', 'state_id' => 3958],
                ['name' => 'Fair Bluff', 'state_id' => 3958],
                ['name' => 'Hallsboro', 'state_id' => 3958],
                ['name' => 'Lake Waccamaw', 'state_id' => 3958],
                ['name' => 'Nakina', 'state_id' => 3958],
                ['name' => 'Riegelwood', 'state_id' => 3958],
                ['name' => 'Tabor City', 'state_id' => 3958],
                ['name' => 'Whiteville', 'state_id' => 3958],
                ['name' => 'Bridgeton', 'state_id' => 3958],
                ['name' => 'Cove City', 'state_id' => 3958],
                ['name' => 'Dover', 'state_id' => 3958],
                ['name' => 'Ernul', 'state_id' => 3958],
                ['name' => 'Havelock', 'state_id' => 3958],
                ['name' => 'Cherry Point', 'state_id' => 3958],
                ['name' => 'New Bern', 'state_id' => 3958],
                ['name' => 'Vanceboro', 'state_id' => 3958],
                ['name' => 'Fayetteville', 'state_id' => 3958],
                ['name' => 'Fort Bragg', 'state_id' => 3958],
                ['name' => 'Pope Army Airfield', 'state_id' => 3958],
                ['name' => 'Cumberland', 'state_id' => 3958],
                ['name' => 'Falcon', 'state_id' => 3958],
                ['name' => 'Godwin', 'state_id' => 3958],
                ['name' => 'Hope Mills', 'state_id' => 3958],
                ['name' => 'Linden', 'state_id' => 3958],
                ['name' => 'Spring Lake', 'state_id' => 3958],
                ['name' => 'Stedman', 'state_id' => 3958],
                ['name' => 'Wade', 'state_id' => 3958],
                ['name' => 'Aydlett', 'state_id' => 3958],
                ['name' => 'Barco', 'state_id' => 3958],
                ['name' => 'Coinjock', 'state_id' => 3958],
                ['name' => 'Corolla', 'state_id' => 3958],
                ['name' => 'Currituck', 'state_id' => 3958],
                ['name' => 'Grandy', 'state_id' => 3958],
                ['name' => 'Harbinger', 'state_id' => 3958],
                ['name' => 'Jarvisburg', 'state_id' => 3958],
                ['name' => 'Knotts Island', 'state_id' => 3958],
                ['name' => 'Maple', 'state_id' => 3958],
                ['name' => 'Moyock', 'state_id' => 3958],
                ['name' => 'Point Harbor', 'state_id' => 3958],
                ['name' => 'Poplar Branch', 'state_id' => 3958],
                ['name' => 'Powells Point', 'state_id' => 3958],
                ['name' => 'Shawboro', 'state_id' => 3958],
                ['name' => 'Avon', 'state_id' => 3958],
                ['name' => 'Buxton', 'state_id' => 3958],
                ['name' => 'Frisco', 'state_id' => 3958],
                ['name' => 'Hatteras', 'state_id' => 3958],
                ['name' => 'Kill Devil Hills', 'state_id' => 3958],
                ['name' => 'Kitty Hawk', 'state_id' => 3958],
                ['name' => 'Manns Harbor', 'state_id' => 3958],
                ['name' => 'Manteo', 'state_id' => 3958],
                ['name' => 'Nags Head', 'state_id' => 3958],
                ['name' => 'Rodanthe', 'state_id' => 3958],
                ['name' => 'Salvo', 'state_id' => 3958],
                ['name' => 'Stumpy Point', 'state_id' => 3958],
                ['name' => 'Wanchese', 'state_id' => 3958],
                ['name' => 'Waves', 'state_id' => 3958],
                ['name' => 'Denton', 'state_id' => 3958],
                ['name' => 'Lexington', 'state_id' => 3958],
                ['name' => 'Linwood', 'state_id' => 3958],
                ['name' => 'Southmont', 'state_id' => 3958],
                ['name' => 'Thomasville', 'state_id' => 3958],
                ['name' => 'Wallburg', 'state_id' => 3958],
                ['name' => 'Welcome', 'state_id' => 3958],
                ['name' => 'Advance', 'state_id' => 3958],
                ['name' => 'Cooleemee', 'state_id' => 3958],
                ['name' => 'Mocksville', 'state_id' => 3958],
                ['name' => 'Calypso', 'state_id' => 3958],
                ['name' => 'Faison', 'state_id' => 3958],
                ['name' => 'Kenansville', 'state_id' => 3958],
                ['name' => 'Warsaw', 'state_id' => 3958],
                ['name' => 'Magnolia', 'state_id' => 3958],
                ['name' => 'Rose Hill', 'state_id' => 3958],
                ['name' => 'Teachey', 'state_id' => 3958],
                ['name' => 'Wallace', 'state_id' => 3958],
                ['name' => 'Albertson', 'state_id' => 3958],
                ['name' => 'Beulaville', 'state_id' => 3958],
                ['name' => 'Chinquapin', 'state_id' => 3958],
                ['name' => 'Bahama', 'state_id' => 3958],
                ['name' => 'Rougemont', 'state_id' => 3958],
                ['name' => 'Durham', 'state_id' => 3958],
                ['name' => 'Rocky Mount', 'state_id' => 3958],
                ['name' => 'Battleboro', 'state_id' => 3958],
                ['name' => 'Conetoe', 'state_id' => 3958],
                ['name' => 'Macclesfield', 'state_id' => 3958],
                ['name' => 'Pinetops', 'state_id' => 3958],
                ['name' => 'Speed', 'state_id' => 3958],
                ['name' => 'Tarboro', 'state_id' => 3958],
                ['name' => 'Belews Creek', 'state_id' => 3958],
                ['name' => 'Bethania', 'state_id' => 3958],
                ['name' => 'Clemmons', 'state_id' => 3958],
                ['name' => 'Lewisville', 'state_id' => 3958],
                ['name' => 'Pfafftown', 'state_id' => 3958],
                ['name' => 'Rural Hall', 'state_id' => 3958],
                ['name' => 'Tobaccoville', 'state_id' => 3958],
                ['name' => 'Walkertown', 'state_id' => 3958],
                ['name' => 'Winston-Salem', 'state_id' => 3958],
                ['name' => 'Kernersville', 'state_id' => 3958],
                ['name' => 'Bunn', 'state_id' => 3958],
                ['name' => 'Franklinton', 'state_id' => 3958],
                ['name' => 'Louisburg', 'state_id' => 3958],
                ['name' => 'Youngsville', 'state_id' => 3958],
                ['name' => 'Alexis', 'state_id' => 3958],
                ['name' => 'Belmont', 'state_id' => 3958],
                ['name' => 'Bessemer City', 'state_id' => 3958],
                ['name' => 'Cherryville', 'state_id' => 3958],
                ['name' => 'Cramerton', 'state_id' => 3958],
                ['name' => 'Dallas', 'state_id' => 3958],
                ['name' => 'Davidson', 'state_id' => 3958],
                ['name' => 'Gastonia', 'state_id' => 3958],
                ['name' => 'High Shoals', 'state_id' => 3958],
                ['name' => 'Lowell', 'state_id' => 3958],
                ['name' => 'Mc Adenville', 'state_id' => 3958],
                ['name' => 'Mount Holly', 'state_id' => 3958],
                ['name' => 'Stanley', 'state_id' => 3958],
                ['name' => 'Corapeake', 'state_id' => 3958],
                ['name' => 'Eure', 'state_id' => 3958],
                ['name' => 'Gates', 'state_id' => 3958],
                ['name' => 'Gatesville', 'state_id' => 3958],
                ['name' => 'Hobbsville', 'state_id' => 3958],
                ['name' => 'Roduco', 'state_id' => 3958],
                ['name' => 'Sunbury', 'state_id' => 3958],
                ['name' => 'Fontana Dam', 'state_id' => 3958],
                ['name' => 'Robbinsville', 'state_id' => 3958],
                ['name' => 'Bullock', 'state_id' => 3958],
                ['name' => 'Butner', 'state_id' => 3958],
                ['name' => 'Creedmoor', 'state_id' => 3958],
                ['name' => 'Clayton', 'state_id' => 3958],
                ['name' => 'Oxford', 'state_id' => 3958],
                ['name' => 'Roxboro', 'state_id' => 3958],
                ['name' => 'Stem', 'state_id' => 3958],
                ['name' => 'Stovall', 'state_id' => 3958],
                ['name' => 'Walstonburg', 'state_id' => 3958],
                ['name' => 'Hookerton', 'state_id' => 3958],
                ['name' => 'Maury', 'state_id' => 3958],
                ['name' => 'Snow Hill', 'state_id' => 3958],
                ['name' => 'Browns Summit', 'state_id' => 3958],
                ['name' => 'Climax', 'state_id' => 3958],
                ['name' => 'Colfax', 'state_id' => 3958],
                ['name' => 'Gibsonville', 'state_id' => 3958],
                ['name' => 'High Point', 'state_id' => 3958],
                ['name' => 'Jamestown', 'state_id' => 3958],
                ['name' => 'Julian', 'state_id' => 3958],
                ['name' => 'Mc Leansville', 'state_id' => 3958],
                ['name' => 'Oak Ridge', 'state_id' => 3958],
                ['name' => 'Pleasant Garden', 'state_id' => 3958],
                ['name' => 'Sedalia', 'state_id' => 3958],
                ['name' => 'Stokesdale', 'state_id' => 3958],
                ['name' => 'Summerfield', 'state_id' => 3958],
                ['name' => 'Whitsett', 'state_id' => 3958],
                ['name' => 'Greensboro', 'state_id' => 3958],
                ['name' => 'Enfield', 'state_id' => 3958],
                ['name' => 'Halifax', 'state_id' => 3958],
                ['name' => 'Hobgood', 'state_id' => 3958],
                ['name' => 'Hollister', 'state_id' => 3958],
                ['name' => 'Littleton', 'state_id' => 3958],
                ['name' => 'Roanoke Rapids', 'state_id' => 3958],
                ['name' => 'Scotland Neck', 'state_id' => 3958],
                ['name' => 'Tillery', 'state_id' => 3958],
                ['name' => 'Weldon', 'state_id' => 3958],
                ['name' => 'Angier', 'state_id' => 3958],
                ['name' => 'Buies Creek', 'state_id' => 3958],
                ['name' => 'Coats', 'state_id' => 3958],
                ['name' => 'Kipling', 'state_id' => 3958],
                ['name' => 'Lillington', 'state_id' => 3958],
                ['name' => 'Mamers', 'state_id' => 3958],
                ['name' => 'Bunnlevel', 'state_id' => 3958],
                ['name' => 'Dunn', 'state_id' => 3958],
                ['name' => 'Erwin', 'state_id' => 3958],
                ['name' => 'Olivia', 'state_id' => 3958],
                ['name' => 'Canton', 'state_id' => 3958],
                ['name' => 'Clyde', 'state_id' => 3958],
                ['name' => 'Hazelwood', 'state_id' => 3958],
                ['name' => 'Lake Junaluska', 'state_id' => 3958],
                ['name' => 'Maggie Valley', 'state_id' => 3958],
                ['name' => 'Waynesville', 'state_id' => 3958],
                ['name' => 'Bat Cave', 'state_id' => 3958],
                ['name' => 'Dana', 'state_id' => 3958],
                ['name' => 'East Flat Rock', 'state_id' => 3958],
                ['name' => 'Edneyville', 'state_id' => 3958],
                ['name' => 'Etowah', 'state_id' => 3958],
                ['name' => 'Flat Rock', 'state_id' => 3958],
                ['name' => 'Fletcher', 'state_id' => 3958],
                ['name' => 'Gerton', 'state_id' => 3958],
                ['name' => 'Hendersonville', 'state_id' => 3958],
                ['name' => 'Horse Shoe', 'state_id' => 3958],
                ['name' => 'Mountain Home', 'state_id' => 3958],
                ['name' => 'Naples', 'state_id' => 3958],
                ['name' => 'Tuxedo', 'state_id' => 3958],
                ['name' => 'Zirconia', 'state_id' => 3958],
                ['name' => 'Como', 'state_id' => 3958],
                ['name' => 'Murfreesboro', 'state_id' => 3958],
                ['name' => 'Ahoskie', 'state_id' => 3958],
                ['name' => 'Cofield', 'state_id' => 3958],
                ['name' => 'Harrellsville', 'state_id' => 3958],
                ['name' => 'Winton', 'state_id' => 3958],
                ['name' => 'Raeford', 'state_id' => 3958],
                ['name' => 'Engelhard', 'state_id' => 3958],
                ['name' => 'Fairfield', 'state_id' => 3958],
                ['name' => 'Scranton', 'state_id' => 3958],
                ['name' => 'Swanquarter', 'state_id' => 3958],
                ['name' => 'Ocracoke', 'state_id' => 3958],
                ['name' => 'Barium Springs', 'state_id' => 3958],
                ['name' => 'Mooresville', 'state_id' => 3958],
                ['name' => 'Mount Mourne', 'state_id' => 3958],
                ['name' => 'Troutman', 'state_id' => 3958],
                ['name' => 'Statesville', 'state_id' => 3958],
                ['name' => 'Harmony', 'state_id' => 3958],
                ['name' => 'Olin', 'state_id' => 3958],
                ['name' => 'Turnersburg', 'state_id' => 3958],
                ['name' => 'Union Grove', 'state_id' => 3958],
                ['name' => 'Scotts', 'state_id' => 3958],
                ['name' => 'Balsam', 'state_id' => 3958],
                ['name' => 'Cashiers', 'state_id' => 3958],
                ['name' => 'Cullowhee', 'state_id' => 3958],
                ['name' => 'Dillsboro', 'state_id' => 3958],
                ['name' => 'Glenville', 'state_id' => 3958],
                ['name' => 'Sylva', 'state_id' => 3958],
                ['name' => 'Tuckasegee', 'state_id' => 3958],
                ['name' => 'Webster', 'state_id' => 3958],
                ['name' => 'Whittier', 'state_id' => 3958],
                ['name' => 'Benson', 'state_id' => 3958],
                ['name' => 'Four Oaks', 'state_id' => 3958],
                ['name' => 'Kenly', 'state_id' => 3958],
                ['name' => 'Micro', 'state_id' => 3958],
                ['name' => 'Middlesex', 'state_id' => 3958],
                ['name' => 'Pine Level', 'state_id' => 3958],
                ['name' => 'Princeton', 'state_id' => 3958],
                ['name' => 'Selma', 'state_id' => 3958],
                ['name' => 'Smithfield', 'state_id' => 3958],
                ['name' => 'Wilsons Mills', 'state_id' => 3958],
                ['name' => 'Comfort', 'state_id' => 3958],
                ['name' => 'Maysville', 'state_id' => 3958],
                ['name' => 'Pollocksville', 'state_id' => 3958],
                ['name' => 'Trenton', 'state_id' => 3958],
                ['name' => 'Cumnock', 'state_id' => 3958],
                ['name' => 'Sanford', 'state_id' => 3958],
                ['name' => 'Broadway', 'state_id' => 3958],
                ['name' => 'Lemon Springs', 'state_id' => 3958],
                ['name' => 'Kinston', 'state_id' => 3958],
                ['name' => 'Deep Run', 'state_id' => 3958],
                ['name' => 'La Grange', 'state_id' => 3958],
                ['name' => 'Pink Hill', 'state_id' => 3958],
                ['name' => 'Crouse', 'state_id' => 3958],
                ['name' => 'Denver', 'state_id' => 3958],
                ['name' => 'Iron Station', 'state_id' => 3958],
                ['name' => 'Lincolnton', 'state_id' => 3958],
                ['name' => 'Vale', 'state_id' => 3958],
                ['name' => 'Glenwood', 'state_id' => 3958],
                ['name' => 'Little Switzerland', 'state_id' => 3958],
                ['name' => 'Marion', 'state_id' => 3958],
                ['name' => 'Nebo', 'state_id' => 3958],
                ['name' => 'Old Fort', 'state_id' => 3958],
                ['name' => 'Franklin', 'state_id' => 3958],
                ['name' => 'Highlands', 'state_id' => 3958],
                ['name' => 'Otto', 'state_id' => 3958],
                ['name' => 'Scaly Mountain', 'state_id' => 3958],
                ['name' => 'Hot Springs', 'state_id' => 3958],
                ['name' => 'Marshall', 'state_id' => 3958],
                ['name' => 'Mars Hill', 'state_id' => 3958],
                ['name' => 'Everetts', 'state_id' => 3958],
                ['name' => 'Hamilton', 'state_id' => 3958],
                ['name' => 'Hassell', 'state_id' => 3958],
                ['name' => 'Jamesville', 'state_id' => 3958],
                ['name' => 'Oak City', 'state_id' => 3958],
                ['name' => 'Parmele', 'state_id' => 3958],
                ['name' => 'Robersonville', 'state_id' => 3958],
                ['name' => 'Williamston', 'state_id' => 3958],
                ['name' => 'Cornelius', 'state_id' => 3958],
                ['name' => 'Huntersville', 'state_id' => 3958],
                ['name' => 'Matthews', 'state_id' => 3958],
                ['name' => 'Newell', 'state_id' => 3958],
                ['name' => 'Paw Creek', 'state_id' => 3958],
                ['name' => 'Pineville', 'state_id' => 3958],
                ['name' => 'Charlotte', 'state_id' => 3958],
                ['name' => 'Bakersville', 'state_id' => 3958],
                ['name' => 'Penland', 'state_id' => 3958],
                ['name' => 'Spruce Pine', 'state_id' => 3958],
                ['name' => 'Biscoe', 'state_id' => 3958],
                ['name' => 'Candor', 'state_id' => 3958],
                ['name' => 'Ether', 'state_id' => 3958],
                ['name' => 'Mount Gilead', 'state_id' => 3958],
                ['name' => 'Star', 'state_id' => 3958],
                ['name' => 'Troy', 'state_id' => 3958],
                ['name' => 'Eagle Springs', 'state_id' => 3958],
                ['name' => 'Highfalls', 'state_id' => 3958],
                ['name' => 'Jackson Springs', 'state_id' => 3958],
                ['name' => 'Robbins', 'state_id' => 3958],
                ['name' => 'West End', 'state_id' => 3958],
                ['name' => 'Aberdeen', 'state_id' => 3958],
                ['name' => 'Cameron', 'state_id' => 3958],
                ['name' => 'Carthage', 'state_id' => 3958],
                ['name' => 'Lakeview', 'state_id' => 3958],
                ['name' => 'Pinehurst', 'state_id' => 3958],
                ['name' => 'Pinebluff', 'state_id' => 3958],
                ['name' => 'Southern Pines', 'state_id' => 3958],
                ['name' => 'Vass', 'state_id' => 3958],
                ['name' => 'Bailey', 'state_id' => 3958],
                ['name' => 'Castalia', 'state_id' => 3958],
                ['name' => 'Nashville', 'state_id' => 3958],
                ['name' => 'Red Oak', 'state_id' => 3958],
                ['name' => 'Sharpsburg', 'state_id' => 3958],
                ['name' => 'Spring Hope', 'state_id' => 3958],
                ['name' => 'Whitakers', 'state_id' => 3958],
                ['name' => 'Carolina Beach', 'state_id' => 3958],
                ['name' => 'Castle Hayne', 'state_id' => 3958],
                ['name' => 'Kure Beach', 'state_id' => 3958],
                ['name' => 'Wrightsville Beach', 'state_id' => 3958],
                ['name' => 'Conway', 'state_id' => 3958],
                ['name' => 'Garysburg', 'state_id' => 3958],
                ['name' => 'Gaston', 'state_id' => 3958],
                ['name' => 'Henrico', 'state_id' => 3958],
                ['name' => 'Jackson', 'state_id' => 3958],
                ['name' => 'Margarettsville', 'state_id' => 3958],
                ['name' => 'Pendleton', 'state_id' => 3958],
                ['name' => 'Pleasant Hill', 'state_id' => 3958],
                ['name' => 'Potecasi', 'state_id' => 3958],
                ['name' => 'Rich Square', 'state_id' => 3958],
                ['name' => 'Seaboard', 'state_id' => 3958],
                ['name' => 'Severn', 'state_id' => 3958],
                ['name' => 'Woodland', 'state_id' => 3958],
                ['name' => 'Holly Ridge', 'state_id' => 3958],
                ['name' => 'Sneads Ferry', 'state_id' => 3958],
                ['name' => 'Hubert', 'state_id' => 3958],
                ['name' => 'Jacksonville', 'state_id' => 3958],
                ['name' => 'Camp Lejeune', 'state_id' => 3958],
                ['name' => 'Tarawa Terrace', 'state_id' => 3958],
                ['name' => 'Midway Park', 'state_id' => 3958],
                ['name' => 'Mccutcheon Field', 'state_id' => 3958],
                ['name' => 'Richlands', 'state_id' => 3958],
                ['name' => 'Swansboro', 'state_id' => 3958],
                ['name' => 'Cedar Grove', 'state_id' => 3958],
                ['name' => 'Efland', 'state_id' => 3958],
                ['name' => 'Hillsborough', 'state_id' => 3958],
                ['name' => 'Carrboro', 'state_id' => 3958],
                ['name' => 'Chapel Hill', 'state_id' => 3958],
                ['name' => 'Alliance', 'state_id' => 3958],
                ['name' => 'Arapahoe', 'state_id' => 3958],
                ['name' => 'Bayboro', 'state_id' => 3958],
                ['name' => 'Grantsboro', 'state_id' => 3958],
                ['name' => 'Hobucken', 'state_id' => 3958],
                ['name' => 'Lowland', 'state_id' => 3958],
                ['name' => 'Merritt', 'state_id' => 3958],
                ['name' => 'Oriental', 'state_id' => 3958],
                ['name' => 'Stonewall', 'state_id' => 3958],
                ['name' => 'Vandemere', 'state_id' => 3958],
                ['name' => 'Elizabeth City', 'state_id' => 3958],
                ['name' => 'Atkinson', 'state_id' => 3958],
                ['name' => 'Burgaw', 'state_id' => 3958],
                ['name' => 'Currie', 'state_id' => 3958],
                ['name' => 'Hampstead', 'state_id' => 3958],
                ['name' => 'Maple Hill', 'state_id' => 3958],
                ['name' => 'Rocky Point', 'state_id' => 3958],
                ['name' => 'Willard', 'state_id' => 3958],
                ['name' => 'Belvidere', 'state_id' => 3958],
                ['name' => 'Hertford', 'state_id' => 3958],
                ['name' => 'Winfall', 'state_id' => 3958],
                ['name' => 'Semora', 'state_id' => 3958],
                ['name' => 'Hurdle Mills', 'state_id' => 3958],
                ['name' => 'Timberlake', 'state_id' => 3958],
                ['name' => 'Bellarthur', 'state_id' => 3958],
                ['name' => 'Bethel', 'state_id' => 3958],
                ['name' => 'Falkland', 'state_id' => 3958],
                ['name' => 'Farmville', 'state_id' => 3958],
                ['name' => 'Fountain', 'state_id' => 3958],
                ['name' => 'Greenville', 'state_id' => 3958],
                ['name' => 'Grimesland', 'state_id' => 3958],
                ['name' => 'Simpson', 'state_id' => 3958],
                ['name' => 'Stokes', 'state_id' => 3958],
                ['name' => 'Ayden', 'state_id' => 3958],
                ['name' => 'Grifton', 'state_id' => 3958],
                ['name' => 'Winterville', 'state_id' => 3958],
                ['name' => 'Columbus', 'state_id' => 3958],
                ['name' => 'Lynn', 'state_id' => 3958],
                ['name' => 'Mill Spring', 'state_id' => 3958],
                ['name' => 'Saluda', 'state_id' => 3958],
                ['name' => 'Tryon', 'state_id' => 3958],
                ['name' => 'Asheboro', 'state_id' => 3958],
                ['name' => 'Cedar Falls', 'state_id' => 3958],
                ['name' => 'Franklinville', 'state_id' => 3958],
                ['name' => 'Liberty', 'state_id' => 3958],
                ['name' => 'Ramseur', 'state_id' => 3958],
                ['name' => 'Randleman', 'state_id' => 3958],
                ['name' => 'Seagrove', 'state_id' => 3958],
                ['name' => 'Sophia', 'state_id' => 3958],
                ['name' => 'Staley', 'state_id' => 3958],
                ['name' => 'Trinity', 'state_id' => 3958],
                ['name' => 'Cordova', 'state_id' => 3958],
                ['name' => 'Ellerbe', 'state_id' => 3958],
                ['name' => 'Hamlet', 'state_id' => 3958],
                ['name' => 'Hoffman', 'state_id' => 3958],
                ['name' => 'Marston', 'state_id' => 3958],
                ['name' => 'Norman', 'state_id' => 3958],
                ['name' => 'Rockingham', 'state_id' => 3958],
                ['name' => 'Barnesville', 'state_id' => 3958],
                ['name' => 'Fairmont', 'state_id' => 3958],
                ['name' => 'Lumber Bridge', 'state_id' => 3958],
                ['name' => 'Lumberton', 'state_id' => 3958],
                ['name' => 'Marietta', 'state_id' => 3958],
                ['name' => 'Maxton', 'state_id' => 3958],
                ['name' => 'Orrum', 'state_id' => 3958],
                ['name' => 'Parkton', 'state_id' => 3958],
                ['name' => 'Pembroke', 'state_id' => 3958],
                ['name' => 'Proctorville', 'state_id' => 3958],
                ['name' => 'Red Springs', 'state_id' => 3958],
                ['name' => 'Rex', 'state_id' => 3958],
                ['name' => 'Rowland', 'state_id' => 3958],
                ['name' => 'Saint Pauls', 'state_id' => 3958],
                ['name' => 'Shannon', 'state_id' => 3958],
                ['name' => 'Madison', 'state_id' => 3958],
                ['name' => 'Mayodan', 'state_id' => 3958],
                ['name' => 'Stoneville', 'state_id' => 3958],
                ['name' => 'Eden', 'state_id' => 3958],
                ['name' => 'Reidsville', 'state_id' => 3958],
                ['name' => 'Ruffin', 'state_id' => 3958],
                ['name' => 'Wentworth', 'state_id' => 3958],
                ['name' => 'Cleveland', 'state_id' => 3958],
                ['name' => 'Woodleaf', 'state_id' => 3958],
                ['name' => 'China Grove', 'state_id' => 3958],
                ['name' => 'East Spencer', 'state_id' => 3958],
                ['name' => 'Faith', 'state_id' => 3958],
                ['name' => 'Gold Hill', 'state_id' => 3958],
                ['name' => 'Granite Quarry', 'state_id' => 3958],
                ['name' => 'Landis', 'state_id' => 3958],
                ['name' => 'Mount Ulla', 'state_id' => 3958],
                ['name' => 'Rockwell', 'state_id' => 3958],
                ['name' => 'Salisbury', 'state_id' => 3958],
                ['name' => 'Spencer', 'state_id' => 3958],
                ['name' => 'Bostic', 'state_id' => 3958],
                ['name' => 'Caroleen', 'state_id' => 3958],
                ['name' => 'Cliffside', 'state_id' => 3958],
                ['name' => 'Ellenboro', 'state_id' => 3958],
                ['name' => 'Forest City', 'state_id' => 3958],
                ['name' => 'Harris', 'state_id' => 3958],
                ['name' => 'Henrietta', 'state_id' => 3958],
                ['name' => 'Rutherfordton', 'state_id' => 3958],
                ['name' => 'Spindale', 'state_id' => 3958],
                ['name' => 'Union Mills', 'state_id' => 3958],
                ['name' => 'Chimney Rock', 'state_id' => 3958],
                ['name' => 'Lake Lure', 'state_id' => 3958],
                ['name' => 'Autryville', 'state_id' => 3958],
                ['name' => 'Clinton', 'state_id' => 3958],
                ['name' => 'Newton Grove', 'state_id' => 3958],
                ['name' => 'Roseboro', 'state_id' => 3958],
                ['name' => 'Salemburg', 'state_id' => 3958],
                ['name' => 'Turkey', 'state_id' => 3958],
                ['name' => 'Garland', 'state_id' => 3958],
                ['name' => 'Harrells', 'state_id' => 3958],
                ['name' => 'Ivanhoe', 'state_id' => 3958],
                ['name' => 'Gibson', 'state_id' => 3958],
                ['name' => 'Laurel Hill', 'state_id' => 3958],
                ['name' => 'Laurinburg', 'state_id' => 3958],
                ['name' => 'Wagram', 'state_id' => 3958],
                ['name' => 'Albemarle', 'state_id' => 3958],
                ['name' => 'Badin', 'state_id' => 3958],
                ['name' => 'Locust', 'state_id' => 3958],
                ['name' => 'Misenheimer', 'state_id' => 3958],
                ['name' => 'New London', 'state_id' => 3958],
                ['name' => 'Norwood', 'state_id' => 3958],
                ['name' => 'Oakboro', 'state_id' => 3958],
                ['name' => 'Richfield', 'state_id' => 3958],
                ['name' => 'Stanfield', 'state_id' => 3958],
                ['name' => 'Danbury', 'state_id' => 3958],
                ['name' => 'Germanton', 'state_id' => 3958],
                ['name' => 'King', 'state_id' => 3958],
                ['name' => 'Lawsonville', 'state_id' => 3958],
                ['name' => 'Pine Hall', 'state_id' => 3958],
                ['name' => 'Pinnacle', 'state_id' => 3958],
                ['name' => 'Sandy Ridge', 'state_id' => 3958],
                ['name' => 'Walnut Cove', 'state_id' => 3958],
                ['name' => 'Ararat', 'state_id' => 3958],
                ['name' => 'Dobson', 'state_id' => 3958],
                ['name' => 'Lowgap', 'state_id' => 3958],
                ['name' => 'Mount Airy', 'state_id' => 3958],
                ['name' => 'White Plains', 'state_id' => 3958],
                ['name' => 'Pilot Mountain', 'state_id' => 3958],
                ['name' => 'Siloam', 'state_id' => 3958],
                ['name' => 'Toast', 'state_id' => 3958],
                ['name' => 'Westfield', 'state_id' => 3958],
                ['name' => 'Elkin', 'state_id' => 3958],
                ['name' => 'State Road', 'state_id' => 3958],
                ['name' => 'Almond', 'state_id' => 3958],
                ['name' => 'Bryson City', 'state_id' => 3958],
                ['name' => 'Cherokee', 'state_id' => 3958],
                ['name' => 'Balsam Grove', 'state_id' => 3958],
                ['name' => 'Brevard', 'state_id' => 3958],
                ['name' => 'Cedar Mountain', 'state_id' => 3958],
                ['name' => 'Lake Toxaway', 'state_id' => 3958],
                ['name' => 'Penrose', 'state_id' => 3958],
                ['name' => 'Pisgah Forest', 'state_id' => 3958],
                ['name' => 'Rosman', 'state_id' => 3958],
                ['name' => 'Sapphire', 'state_id' => 3958],
                ['name' => 'Columbia', 'state_id' => 3958],
                ['name' => 'Indian Trail', 'state_id' => 3958],
                ['name' => 'Marshville', 'state_id' => 3958],
                ['name' => 'Mineral Springs', 'state_id' => 3958],
                ['name' => 'Monroe', 'state_id' => 3958],
                ['name' => 'Waxhaw', 'state_id' => 3958],
                ['name' => 'Wingate', 'state_id' => 3958],
                ['name' => 'Henderson', 'state_id' => 3958],
                ['name' => 'Kittrell', 'state_id' => 3958],
                ['name' => 'Manson', 'state_id' => 3958],
                ['name' => 'Middleburg', 'state_id' => 3958],
                ['name' => 'Townsville', 'state_id' => 3958],
                ['name' => 'Apex', 'state_id' => 3958],
                ['name' => 'Cary', 'state_id' => 3958],
                ['name' => 'Fuquay Varina', 'state_id' => 3958],
                ['name' => 'Garner', 'state_id' => 3958],
                ['name' => 'Holly Springs', 'state_id' => 3958],
                ['name' => 'Knightdale', 'state_id' => 3958],
                ['name' => 'Morrisville', 'state_id' => 3958],
                ['name' => 'New Hill', 'state_id' => 3958],
                ['name' => 'Rolesville', 'state_id' => 3958],
                ['name' => 'Wake Forest', 'state_id' => 3958],
                ['name' => 'Wendell', 'state_id' => 3958],
                ['name' => 'Willow Spring', 'state_id' => 3958],
                ['name' => 'Zebulon', 'state_id' => 3958],
                ['name' => 'Raleigh', 'state_id' => 3958],
                ['name' => 'Macon', 'state_id' => 3958],
                ['name' => 'Norlina', 'state_id' => 3958],
                ['name' => 'Ridgeway', 'state_id' => 3958],
                ['name' => 'Vaughan', 'state_id' => 3958],
                ['name' => 'Warrenton', 'state_id' => 3958],
                ['name' => 'Wise', 'state_id' => 3958],
                ['name' => 'Creswell', 'state_id' => 3958],
                ['name' => 'Plymouth', 'state_id' => 3958],
                ['name' => 'Roper', 'state_id' => 3958],
                ['name' => 'Blowing Rock', 'state_id' => 3958],
                ['name' => 'Boone', 'state_id' => 3958],
                ['name' => 'Deep Gap', 'state_id' => 3958],
                ['name' => 'Sugar Grove', 'state_id' => 3958],
                ['name' => 'Valle Crucis', 'state_id' => 3958],
                ['name' => 'Vilas', 'state_id' => 3958],
                ['name' => 'Zionville', 'state_id' => 3958],
                ['name' => 'Goldsboro', 'state_id' => 3958],
                ['name' => 'Fremont', 'state_id' => 3958],
                ['name' => 'Pikeville', 'state_id' => 3958],
                ['name' => 'Dudley', 'state_id' => 3958],
                ['name' => 'Mount Olive', 'state_id' => 3958],
                ['name' => 'Seven Springs', 'state_id' => 3958],
                ['name' => 'Boomer', 'state_id' => 3958],
                ['name' => 'Ferguson', 'state_id' => 3958],
                ['name' => 'Hays', 'state_id' => 3958],
                ['name' => 'Mc Grady', 'state_id' => 3958],
                ['name' => 'Millers Creek', 'state_id' => 3958],
                ['name' => 'Moravian Falls', 'state_id' => 3958],
                ['name' => 'North Wilkesboro', 'state_id' => 3958],
                ['name' => 'Purlear', 'state_id' => 3958],
                ['name' => 'Roaring River', 'state_id' => 3958],
                ['name' => 'Ronda', 'state_id' => 3958],
                ['name' => 'Thurmond', 'state_id' => 3958],
                ['name' => 'Traphill', 'state_id' => 3958],
                ['name' => 'Wilkesboro', 'state_id' => 3958],
                ['name' => 'Black Creek', 'state_id' => 3958],
                ['name' => 'Elm City', 'state_id' => 3958],
                ['name' => 'Lucama', 'state_id' => 3958],
                ['name' => 'Saratoga', 'state_id' => 3958],
                ['name' => 'Sims', 'state_id' => 3958],
                ['name' => 'Stantonsburg', 'state_id' => 3958],
                ['name' => 'Wilson', 'state_id' => 3958],
                ['name' => 'Boonville', 'state_id' => 3958],
                ['name' => 'East Bend', 'state_id' => 3958],
                ['name' => 'Hamptonville', 'state_id' => 3958],
                ['name' => 'Yadkinville', 'state_id' => 3958],
                ['name' => 'Jonesville', 'state_id' => 3958],
                ['name' => 'Burnsville', 'state_id' => 3958],
                ['name' => 'Green Mountain', 'state_id' => 3958],
                ['name' => 'Micaville', 'state_id' => 3958]
            ]);
        }
    }
}
