<?php

use Illuminate\Database\Seeder;

class state31TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NH - New Hampshire.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Barnstead', 'state_id' => 3953],
                ['name' => 'Belmont', 'state_id' => 3953],
                ['name' => 'Center Barnstead', 'state_id' => 3953],
                ['name' => 'Center Harbor', 'state_id' => 3953],
                ['name' => 'Gilmanton', 'state_id' => 3953],
                ['name' => 'Laconia', 'state_id' => 3953],
                ['name' => 'Gilford', 'state_id' => 3953],
                ['name' => 'Lochmere', 'state_id' => 3953],
                ['name' => 'Meredith', 'state_id' => 3953],
                ['name' => 'New Hampton', 'state_id' => 3953],
                ['name' => 'Sanbornton', 'state_id' => 3953],
                ['name' => 'Tilton', 'state_id' => 3953],
                ['name' => 'Winnisquam', 'state_id' => 3953],
                ['name' => 'Alton', 'state_id' => 3953],
                ['name' => 'Alton Bay', 'state_id' => 3953],
                ['name' => 'Gilmanton Iron Works', 'state_id' => 3953],
                ['name' => 'Center Sandwich', 'state_id' => 3953],
                ['name' => 'Moultonborough', 'state_id' => 3953],
                ['name' => 'North Sandwich', 'state_id' => 3953],
                ['name' => 'Bartlett', 'state_id' => 3953],
                ['name' => 'Center Conway', 'state_id' => 3953],
                ['name' => 'Center Ossipee', 'state_id' => 3953],
                ['name' => 'Center Tuftonboro', 'state_id' => 3953],
                ['name' => 'Chocorua', 'state_id' => 3953],
                ['name' => 'Conway', 'state_id' => 3953],
                ['name' => 'East Wakefield', 'state_id' => 3953],
                ['name' => 'Eaton Center', 'state_id' => 3953],
                ['name' => 'Freedom', 'state_id' => 3953],
                ['name' => 'Glen', 'state_id' => 3953],
                ['name' => 'Intervale', 'state_id' => 3953],
                ['name' => 'Jackson', 'state_id' => 3953],
                ['name' => 'Kearsarge', 'state_id' => 3953],
                ['name' => 'Madison', 'state_id' => 3953],
                ['name' => 'Melvin Village', 'state_id' => 3953],
                ['name' => 'Mirror Lake', 'state_id' => 3953],
                ['name' => 'North Conway', 'state_id' => 3953],
                ['name' => 'Lee', 'state_id' => 3953],
                ['name' => 'Ossipee', 'state_id' => 3953],
                ['name' => 'Sanbornville', 'state_id' => 3953],
                ['name' => 'Silver Lake', 'state_id' => 3953],
                ['name' => 'Effingham', 'state_id' => 3953],
                ['name' => 'South Tamworth', 'state_id' => 3953],
                ['name' => 'Tamworth', 'state_id' => 3953],
                ['name' => 'West Ossipee', 'state_id' => 3953],
                ['name' => 'Wolfeboro', 'state_id' => 3953],
                ['name' => 'Wolfeboro Falls', 'state_id' => 3953],
                ['name' => 'Wonalancet', 'state_id' => 3953],
                ['name' => 'Keene', 'state_id' => 3953],
                ['name' => 'Ashuelot', 'state_id' => 3953],
                ['name' => 'Chesterfield', 'state_id' => 3953],
                ['name' => 'Dublin', 'state_id' => 3953],
                ['name' => 'Sullivan', 'state_id' => 3953],
                ['name' => 'Swanzey', 'state_id' => 3953],
                ['name' => 'Fitzwilliam', 'state_id' => 3953],
                ['name' => 'Gilsum', 'state_id' => 3953],
                ['name' => 'Harrisville', 'state_id' => 3953],
                ['name' => 'Hinsdale', 'state_id' => 3953],
                ['name' => 'Jaffrey', 'state_id' => 3953],
                ['name' => 'Marlborough', 'state_id' => 3953],
                ['name' => 'Marlow', 'state_id' => 3953],
                ['name' => 'Nelson', 'state_id' => 3953],
                ['name' => 'Rindge', 'state_id' => 3953],
                ['name' => 'Spofford', 'state_id' => 3953],
                ['name' => 'Stoddard', 'state_id' => 3953],
                ['name' => 'Troy', 'state_id' => 3953],
                ['name' => 'West Chesterfield', 'state_id' => 3953],
                ['name' => 'Westmoreland', 'state_id' => 3953],
                ['name' => 'West Swanzey', 'state_id' => 3953],
                ['name' => 'Winchester', 'state_id' => 3953],
                ['name' => 'Alstead', 'state_id' => 3953],
                ['name' => 'Drewsville', 'state_id' => 3953],
                ['name' => 'Walpole', 'state_id' => 3953],
                ['name' => 'North Walpole', 'state_id' => 3953],
                ['name' => 'Berlin', 'state_id' => 3953],
                ['name' => 'Bretton Woods', 'state_id' => 3953],
                ['name' => 'Colebrook', 'state_id' => 3953],
                ['name' => 'Errol', 'state_id' => 3953],
                ['name' => 'Gorham', 'state_id' => 3953],
                ['name' => 'Groveton', 'state_id' => 3953],
                ['name' => 'Jefferson', 'state_id' => 3953],
                ['name' => 'Lancaster', 'state_id' => 3953],
                ['name' => 'Milan', 'state_id' => 3953],
                ['name' => 'Mount Washington', 'state_id' => 3953],
                ['name' => 'North Stratford', 'state_id' => 3953],
                ['name' => 'Pittsburg', 'state_id' => 3953],
                ['name' => 'Randolph', 'state_id' => 3953],
                ['name' => 'Twin Mountain', 'state_id' => 3953],
                ['name' => 'West Stewartstown', 'state_id' => 3953],
                ['name' => 'Whitefield', 'state_id' => 3953],
                ['name' => 'Waterville Valley', 'state_id' => 3953],
                ['name' => 'Ashland', 'state_id' => 3953],
                ['name' => 'Bristol', 'state_id' => 3953],
                ['name' => 'Campton', 'state_id' => 3953],
                ['name' => 'Glencliff', 'state_id' => 3953],
                ['name' => 'Grafton', 'state_id' => 3953],
                ['name' => 'Hebron', 'state_id' => 3953],
                ['name' => 'Holderness', 'state_id' => 3953],
                ['name' => 'Lincoln', 'state_id' => 3953],
                ['name' => 'Chichester', 'state_id' => 3953],
                ['name' => 'North Woodstock', 'state_id' => 3953],
                ['name' => 'Plymouth', 'state_id' => 3953],
                ['name' => 'Rumney', 'state_id' => 3953],
                ['name' => 'Warren', 'state_id' => 3953],
                ['name' => 'Wentworth', 'state_id' => 3953],
                ['name' => 'Thornton', 'state_id' => 3953],
                ['name' => 'Woodstock', 'state_id' => 3953],
                ['name' => 'Littleton', 'state_id' => 3953],
                ['name' => 'Bethlehem', 'state_id' => 3953],
                ['name' => 'Franconia', 'state_id' => 3953],
                ['name' => 'Lisbon', 'state_id' => 3953],
                ['name' => 'Sugar Hill', 'state_id' => 3953],
                ['name' => 'Bath', 'state_id' => 3953],
                ['name' => 'Canaan', 'state_id' => 3953],
                ['name' => 'Enfield', 'state_id' => 3953],
                ['name' => 'Enfield Center', 'state_id' => 3953],
                ['name' => 'Etna', 'state_id' => 3953],
                ['name' => 'Hanover', 'state_id' => 3953],
                ['name' => 'Lebanon', 'state_id' => 3953],
                ['name' => 'Haverhill', 'state_id' => 3953],
                ['name' => 'Lyme', 'state_id' => 3953],
                ['name' => 'Lyme Center', 'state_id' => 3953],
                ['name' => 'Monroe', 'state_id' => 3953],
                ['name' => 'North Haverhill', 'state_id' => 3953],
                ['name' => 'Orford', 'state_id' => 3953],
                ['name' => 'Piermont', 'state_id' => 3953],
                ['name' => 'Pike', 'state_id' => 3953],
                ['name' => 'West Lebanon', 'state_id' => 3953],
                ['name' => 'Woodsville', 'state_id' => 3953],
                ['name' => 'Amherst', 'state_id' => 3953],
                ['name' => 'Brookline', 'state_id' => 3953],
                ['name' => 'Francestown', 'state_id' => 3953],
                ['name' => 'Goffstown', 'state_id' => 3953],
                ['name' => 'Greenfield', 'state_id' => 3953],
                ['name' => 'Greenville', 'state_id' => 3953],
                ['name' => 'Hollis', 'state_id' => 3953],
                ['name' => 'Hudson', 'state_id' => 3953],
                ['name' => 'Litchfield', 'state_id' => 3953],
                ['name' => 'Merrimack', 'state_id' => 3953],
                ['name' => 'Milford', 'state_id' => 3953],
                ['name' => 'Mont Vernon', 'state_id' => 3953],
                ['name' => 'Nashua', 'state_id' => 3953],
                ['name' => 'New Boston', 'state_id' => 3953],
                ['name' => 'New Ipswich', 'state_id' => 3953],
                ['name' => 'Pelham', 'state_id' => 3953],
                ['name' => 'Lyndeborough', 'state_id' => 3953],
                ['name' => 'Temple', 'state_id' => 3953],
                ['name' => 'Wilton', 'state_id' => 3953],
                ['name' => 'Manchester', 'state_id' => 3953],
                ['name' => 'Bedford', 'state_id' => 3953],
                ['name' => 'Hillsborough', 'state_id' => 3953],
                ['name' => 'Weare', 'state_id' => 3953],
                ['name' => 'Antrim', 'state_id' => 3953],
                ['name' => 'Bennington', 'state_id' => 3953],
                ['name' => 'Hancock', 'state_id' => 3953],
                ['name' => 'Peterborough', 'state_id' => 3953],
                ['name' => 'West Peterborough', 'state_id' => 3953],
                ['name' => 'Dunbarton', 'state_id' => 3953],
                ['name' => 'Hooksett', 'state_id' => 3953],
                ['name' => 'Andover', 'state_id' => 3953],
                ['name' => 'Bradford', 'state_id' => 3953],
                ['name' => 'Canterbury', 'state_id' => 3953],
                ['name' => 'Contoocook', 'state_id' => 3953],
                ['name' => 'Danbury', 'state_id' => 3953],
                ['name' => 'East Andover', 'state_id' => 3953],
                ['name' => 'Elkins', 'state_id' => 3953],
                ['name' => 'Epsom', 'state_id' => 3953],
                ['name' => 'Franklin', 'state_id' => 3953],
                ['name' => 'Henniker', 'state_id' => 3953],
                ['name' => 'Hill', 'state_id' => 3953],
                ['name' => 'Newbury', 'state_id' => 3953],
                ['name' => 'New London', 'state_id' => 3953],
                ['name' => 'North Sutton', 'state_id' => 3953],
                ['name' => 'Pittsfield', 'state_id' => 3953],
                ['name' => 'Salisbury', 'state_id' => 3953],
                ['name' => 'South Newbury', 'state_id' => 3953],
                ['name' => 'South Sutton', 'state_id' => 3953],
                ['name' => 'Suncook', 'state_id' => 3953],
                ['name' => 'Warner', 'state_id' => 3953],
                ['name' => 'Wilmot', 'state_id' => 3953],
                ['name' => 'Concord', 'state_id' => 3953],
                ['name' => 'Bow', 'state_id' => 3953],
                ['name' => 'Loudon', 'state_id' => 3953],
                ['name' => 'Auburn', 'state_id' => 3953],
                ['name' => 'Candia', 'state_id' => 3953],
                ['name' => 'Chester', 'state_id' => 3953],
                ['name' => 'Deerfield', 'state_id' => 3953],
                ['name' => 'Derry', 'state_id' => 3953],
                ['name' => 'East Candia', 'state_id' => 3953],
                ['name' => 'East Derry', 'state_id' => 3953],
                ['name' => 'Epping', 'state_id' => 3953],
                ['name' => 'Fremont', 'state_id' => 3953],
                ['name' => 'Londonderry', 'state_id' => 3953],
                ['name' => 'North Salem', 'state_id' => 3953],
                ['name' => 'Raymond', 'state_id' => 3953],
                ['name' => 'Salem', 'state_id' => 3953],
                ['name' => 'Windham', 'state_id' => 3953],
                ['name' => 'Northwood', 'state_id' => 3953],
                ['name' => 'Nottingham', 'state_id' => 3953],
                ['name' => 'West Nottingham', 'state_id' => 3953],
                ['name' => 'Portsmouth', 'state_id' => 3953],
                ['name' => 'Atkinson', 'state_id' => 3953],
                ['name' => 'Danville', 'state_id' => 3953],
                ['name' => 'East Hampstead', 'state_id' => 3953],
                ['name' => 'East Kingston', 'state_id' => 3953],
                ['name' => 'Exeter', 'state_id' => 3953],
                ['name' => 'Greenland', 'state_id' => 3953],
                ['name' => 'Hampstead', 'state_id' => 3953],
                ['name' => 'Hampton', 'state_id' => 3953],
                ['name' => 'Hampton Falls', 'state_id' => 3953],
                ['name' => 'Kingston', 'state_id' => 3953],
                ['name' => 'New Castle', 'state_id' => 3953],
                ['name' => 'Newfields', 'state_id' => 3953],
                ['name' => 'Newmarket', 'state_id' => 3953],
                ['name' => 'Newton', 'state_id' => 3953],
                ['name' => 'Newton Junction', 'state_id' => 3953],
                ['name' => 'North Hampton', 'state_id' => 3953],
                ['name' => 'Plaistow', 'state_id' => 3953],
                ['name' => 'Rye', 'state_id' => 3953],
                ['name' => 'Rye Beach', 'state_id' => 3953],
                ['name' => 'Sandown', 'state_id' => 3953],
                ['name' => 'Seabrook', 'state_id' => 3953],
                ['name' => 'Stratham', 'state_id' => 3953],
                ['name' => 'Center Strafford', 'state_id' => 3953],
                ['name' => 'Dover', 'state_id' => 3953],
                ['name' => 'Madbury', 'state_id' => 3953],
                ['name' => 'Durham', 'state_id' => 3953],
                ['name' => 'Barrington', 'state_id' => 3953],
                ['name' => 'Farmington', 'state_id' => 3953],
                ['name' => 'Rochester', 'state_id' => 3953],
                ['name' => 'Milton', 'state_id' => 3953],
                ['name' => 'Milton Mills', 'state_id' => 3953],
                ['name' => 'New Durham', 'state_id' => 3953],
                ['name' => 'Rollinsford', 'state_id' => 3953],
                ['name' => 'Somersworth', 'state_id' => 3953],
                ['name' => 'Strafford', 'state_id' => 3953],
                ['name' => 'Union', 'state_id' => 3953],
                ['name' => 'Washington', 'state_id' => 3953],
                ['name' => 'Springfield', 'state_id' => 3953],
                ['name' => 'Acworth', 'state_id' => 3953],
                ['name' => 'Charlestown', 'state_id' => 3953],
                ['name' => 'Lempster', 'state_id' => 3953],
                ['name' => 'South Acworth', 'state_id' => 3953],
                ['name' => 'Claremont', 'state_id' => 3953],
                ['name' => 'Cornish', 'state_id' => 3953],
                ['name' => 'Cornish Flat', 'state_id' => 3953],
                ['name' => 'Georges Mills', 'state_id' => 3953],
                ['name' => 'Goshen', 'state_id' => 3953],
                ['name' => 'Grantham', 'state_id' => 3953],
                ['name' => 'Guild', 'state_id' => 3953],
                ['name' => 'Meriden', 'state_id' => 3953],
                ['name' => 'Newport', 'state_id' => 3953],
                ['name' => 'Plainfield', 'state_id' => 3953],
                ['name' => 'Sunapee', 'state_id' => 3953]
            ]);
        }
    }
}
