<?php

use Illuminate\Database\Seeder;

class state1TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AK - Alaska.
        //If the table 'cities' exists, insert the data to the table.
            DB::table('cities')->insert([
                ['name' => 'Akutan', 'state_id' => 3921],
                ['name' => 'Cold Bay', 'state_id' => 3921],
                ['name' => 'False Pass', 'state_id' => 3921],
                ['name' => 'King Cove', 'state_id' => 3921],
                ['name' => 'Sand Point', 'state_id' => 3921],
                ['name' => 'Adak', 'state_id' => 3921],
                ['name' => 'Atka', 'state_id' => 3921],
                ['name' => 'Saint George Island', 'state_id' => 3921],
                ['name' => 'Nikolski', 'state_id' => 3921],
                ['name' => 'Saint Paul Island', 'state_id' => 3921],
                ['name' => 'Unalaska', 'state_id' => 3921],
                ['name' => 'Dutch Harbor', 'state_id' => 3921],
                ['name' => 'Anchorage', 'state_id' => 3921],
                ['name' => 'Jber', 'state_id' => 3921],
                ['name' => 'Indian', 'state_id' => 3921],
                ['name' => 'Chugiak', 'state_id' => 3921],
                ['name' => 'Eagle River', 'state_id' => 3921],
                ['name' => 'Girdwood', 'state_id' => 3921],
                ['name' => 'Kongiganak', 'state_id' => 3921],
                ['name' => 'Akiachak', 'state_id' => 3921],
                ['name' => 'Akiak', 'state_id' => 3921],
                ['name' => 'Aniak', 'state_id' => 3921],
                ['name' => 'Bethel', 'state_id' => 3921],
                ['name' => 'Chefornak', 'state_id' => 3921],
                ['name' => 'Crooked Creek', 'state_id' => 3921],
                ['name' => 'Eek', 'state_id' => 3921],
                ['name' => 'Goodnews Bay', 'state_id' => 3921],
                ['name' => 'Kalskag', 'state_id' => 3921],
                ['name' => 'Kasigluk', 'state_id' => 3921],
                ['name' => 'Kipnuk', 'state_id' => 3921],
                ['name' => 'Kwethluk', 'state_id' => 3921],
                ['name' => 'Kwigillingok', 'state_id' => 3921],
                ['name' => 'Lower Kalskag', 'state_id' => 3921],
                ['name' => 'Mekoryuk', 'state_id' => 3921],
                ['name' => 'Napakiak', 'state_id' => 3921],
                ['name' => 'Toksook Bay', 'state_id' => 3921],
                ['name' => 'Nunapitchuk', 'state_id' => 3921],
                ['name' => 'Platinum', 'state_id' => 3921],
                ['name' => 'Quinhagak', 'state_id' => 3921],
                ['name' => 'Red Devil', 'state_id' => 3921],
                ['name' => 'Sleetmute', 'state_id' => 3921],
                ['name' => 'Tuluksak', 'state_id' => 3921],
                ['name' => 'Tuntutuliak', 'state_id' => 3921],
                ['name' => 'Tununak', 'state_id' => 3921],
                ['name' => 'Nightmute', 'state_id' => 3921],
                ['name' => 'King Salmon', 'state_id' => 3921],
                ['name' => 'Naknek', 'state_id' => 3921],
                ['name' => 'South Naknek', 'state_id' => 3921],
                ['name' => 'Clear', 'state_id' => 3921],
                ['name' => 'Cantwell', 'state_id' => 3921],
                ['name' => 'Healy', 'state_id' => 3921],
                ['name' => 'Anderson', 'state_id' => 3921],
                ['name' => 'Denali National Park', 'state_id' => 3921],
                ['name' => 'Aleknagik', 'state_id' => 3921],
                ['name' => 'Clarks Point', 'state_id' => 3921],
                ['name' => 'Dillingham', 'state_id' => 3921],
                ['name' => 'Ekwok', 'state_id' => 3921],
                ['name' => 'Manokotak', 'state_id' => 3921],
                ['name' => 'New Stuyahok', 'state_id' => 3921],
                ['name' => 'Togiak', 'state_id' => 3921],
                ['name' => 'Fairbanks', 'state_id' => 3921],
                ['name' => 'Eielson Afb', 'state_id' => 3921],
                ['name' => 'Fort Wainwright', 'state_id' => 3921],
                ['name' => 'North Pole', 'state_id' => 3921],
                ['name' => 'Salcha', 'state_id' => 3921],
                ['name' => 'Two Rivers', 'state_id' => 3921],
                ['name' => 'Ester', 'state_id' => 3921],
                ['name' => 'Haines', 'state_id' => 3921],
                ['name' => 'Juneau', 'state_id' => 3921],
                ['name' => 'Auke Bay', 'state_id' => 3921],
                ['name' => 'Douglas', 'state_id' => 3921],
                ['name' => 'Anchor Point', 'state_id' => 3921],
                ['name' => 'Clam Gulch', 'state_id' => 3921],
                ['name' => 'Cooper Landing', 'state_id' => 3921],
                ['name' => 'Homer', 'state_id' => 3921],
                ['name' => 'Hope', 'state_id' => 3921],
                ['name' => 'Kasilof', 'state_id' => 3921],
                ['name' => 'Kenai', 'state_id' => 3921],
                ['name' => 'Moose Pass', 'state_id' => 3921],
                ['name' => 'Nikiski', 'state_id' => 3921],
                ['name' => 'Ninilchik', 'state_id' => 3921],
                ['name' => 'Seldovia', 'state_id' => 3921],
                ['name' => 'Seward', 'state_id' => 3921],
                ['name' => 'Soldotna', 'state_id' => 3921],
                ['name' => 'Sterling', 'state_id' => 3921],
                ['name' => 'Tyonek', 'state_id' => 3921],
                ['name' => 'Ketchikan', 'state_id' => 3921],
                ['name' => 'Ward Cove', 'state_id' => 3921],
                ['name' => 'Port Lions', 'state_id' => 3921],
                ['name' => 'Karluk', 'state_id' => 3921],
                ['name' => 'Kodiak', 'state_id' => 3921],
                ['name' => 'Larsen Bay', 'state_id' => 3921],
                ['name' => 'Old Harbor', 'state_id' => 3921],
                ['name' => 'Ouzinkie', 'state_id' => 3921],
                ['name' => 'Alakanuk', 'state_id' => 3921],
                ['name' => 'Chevak', 'state_id' => 3921],
                ['name' => 'Emmonak', 'state_id' => 3921],
                ['name' => 'Marshall', 'state_id' => 3921],
                ['name' => 'Hooper Bay', 'state_id' => 3921],
                ['name' => 'Kotlik', 'state_id' => 3921],
                ['name' => 'Mountain Village', 'state_id' => 3921],
                ['name' => 'Pilot Station', 'state_id' => 3921],
                ['name' => 'Russian Mission', 'state_id' => 3921],
                ['name' => 'Saint Marys', 'state_id' => 3921],
                ['name' => 'Scammon Bay', 'state_id' => 3921],
                ['name' => 'Nunam Iqua', 'state_id' => 3921],
                ['name' => 'Chignik Lake', 'state_id' => 3921],
                ['name' => 'Port Heiden', 'state_id' => 3921],
                ['name' => 'Chignik', 'state_id' => 3921],
                ['name' => 'Chignik Lagoon', 'state_id' => 3921],
                ['name' => 'Egegik', 'state_id' => 3921],
                ['name' => 'Iliamna', 'state_id' => 3921],
                ['name' => 'Levelock', 'state_id' => 3921],
                ['name' => 'Nondalton', 'state_id' => 3921],
                ['name' => 'Pedro Bay', 'state_id' => 3921],
                ['name' => 'Perryville', 'state_id' => 3921],
                ['name' => 'Pilot Point', 'state_id' => 3921],
                ['name' => 'Port Alsworth', 'state_id' => 3921],
                ['name' => 'Wasilla', 'state_id' => 3921],
                ['name' => 'Palmer', 'state_id' => 3921],
                ['name' => 'Big Lake', 'state_id' => 3921],
                ['name' => 'Skwentna', 'state_id' => 3921],
                ['name' => 'Sutton', 'state_id' => 3921],
                ['name' => 'Talkeetna', 'state_id' => 3921],
                ['name' => 'Trapper Creek', 'state_id' => 3921],
                ['name' => 'Willow', 'state_id' => 3921],
                ['name' => 'Houston', 'state_id' => 3921],
                ['name' => 'Saint Michael', 'state_id' => 3921],
                ['name' => 'Stebbins', 'state_id' => 3921],
                ['name' => 'Unalakleet', 'state_id' => 3921],
                ['name' => 'Elim', 'state_id' => 3921],
                ['name' => 'Gambell', 'state_id' => 3921],
                ['name' => 'Koyuk', 'state_id' => 3921],
                ['name' => 'Nome', 'state_id' => 3921],
                ['name' => 'Savoonga', 'state_id' => 3921],
                ['name' => 'Shaktoolik', 'state_id' => 3921],
                ['name' => 'Shishmaref', 'state_id' => 3921],
                ['name' => 'Teller', 'state_id' => 3921],
                ['name' => 'Wales', 'state_id' => 3921],
                ['name' => 'White Mountain', 'state_id' => 3921],
                ['name' => 'Brevig Mission', 'state_id' => 3921],
                ['name' => 'Anaktuvuk Pass', 'state_id' => 3921],
                ['name' => 'Barrow', 'state_id' => 3921],
                ['name' => 'Prudhoe Bay', 'state_id' => 3921],
                ['name' => 'Kaktovik', 'state_id' => 3921],
                ['name' => 'Point Lay', 'state_id' => 3921],
                ['name' => 'Point Hope', 'state_id' => 3921],
                ['name' => 'Wainwright', 'state_id' => 3921],
                ['name' => 'Nuiqsut', 'state_id' => 3921],
                ['name' => 'Atqasuk', 'state_id' => 3921],
                ['name' => 'Buckland', 'state_id' => 3921],
                ['name' => 'Deering', 'state_id' => 3921],
                ['name' => 'Kiana', 'state_id' => 3921],
                ['name' => 'Kivalina', 'state_id' => 3921],
                ['name' => 'Kobuk', 'state_id' => 3921],
                ['name' => 'Kotzebue', 'state_id' => 3921],
                ['name' => 'Noatak', 'state_id' => 3921],
                ['name' => 'Noorvik', 'state_id' => 3921],
                ['name' => 'Selawik', 'state_id' => 3921],
                ['name' => 'Shungnak', 'state_id' => 3921],
                ['name' => 'Ambler', 'state_id' => 3921],
                ['name' => 'Meyers Chuck', 'state_id' => 3921],
                ['name' => 'Coffman Cove', 'state_id' => 3921],
                ['name' => 'Thorne Bay', 'state_id' => 3921],
                ['name' => 'Craig', 'state_id' => 3921],
                ['name' => 'Hydaburg', 'state_id' => 3921],
                ['name' => 'Hyder', 'state_id' => 3921],
                ['name' => 'Klawock', 'state_id' => 3921],
                ['name' => 'Metlakatla', 'state_id' => 3921],
                ['name' => 'Point Baker', 'state_id' => 3921],
                ['name' => 'Sitka', 'state_id' => 3921],
                ['name' => 'Yakutat', 'state_id' => 3921],
                ['name' => 'Angoon', 'state_id' => 3921],
                ['name' => 'Elfin Cove', 'state_id' => 3921],
                ['name' => 'Gustavus', 'state_id' => 3921],
                ['name' => 'Hoonah', 'state_id' => 3921],
                ['name' => 'Pelican', 'state_id' => 3921],
                ['name' => 'Skagway', 'state_id' => 3921],
                ['name' => 'Tenakee Springs', 'state_id' => 3921],
                ['name' => 'Fort Greely', 'state_id' => 3921],
                ['name' => 'Chicken', 'state_id' => 3921],
                ['name' => 'Delta Junction', 'state_id' => 3921],
                ['name' => 'Eagle', 'state_id' => 3921],
                ['name' => 'Northway', 'state_id' => 3921],
                ['name' => 'Tanacross', 'state_id' => 3921],
                ['name' => 'Tok', 'state_id' => 3921],
                ['name' => 'Chitina', 'state_id' => 3921],
                ['name' => 'Copper Center', 'state_id' => 3921],
                ['name' => 'Cordova', 'state_id' => 3921],
                ['name' => 'Gakona', 'state_id' => 3921],
                ['name' => 'Glennallen', 'state_id' => 3921],
                ['name' => 'Tatitlek', 'state_id' => 3921],
                ['name' => 'Valdez', 'state_id' => 3921],
                ['name' => 'Whittier', 'state_id' => 3921],
                ['name' => 'Kake', 'state_id' => 3921],
                ['name' => 'Petersburg', 'state_id' => 3921],
                ['name' => 'Port Alexander', 'state_id' => 3921],
                ['name' => 'Wrangell', 'state_id' => 3921],
                ['name' => 'Anvik', 'state_id' => 3921],
                ['name' => 'Grayling', 'state_id' => 3921],
                ['name' => 'Holy Cross', 'state_id' => 3921],
                ['name' => 'Mc Grath', 'state_id' => 3921],
                ['name' => 'Shageluk', 'state_id' => 3921],
                ['name' => 'Takotna', 'state_id' => 3921],
                ['name' => 'Nikolai', 'state_id' => 3921],
                ['name' => 'Allakaket', 'state_id' => 3921],
                ['name' => 'Arctic Village', 'state_id' => 3921],
                ['name' => 'Beaver', 'state_id' => 3921],
                ['name' => 'Bettles Field', 'state_id' => 3921],
                ['name' => 'Central', 'state_id' => 3921],
                ['name' => 'Circle', 'state_id' => 3921],
                ['name' => 'Fort Yukon', 'state_id' => 3921],
                ['name' => 'Galena', 'state_id' => 3921],
                ['name' => 'Hughes', 'state_id' => 3921],
                ['name' => 'Huslia', 'state_id' => 3921],
                ['name' => 'Kaltag', 'state_id' => 3921],
                ['name' => 'Koyukuk', 'state_id' => 3921],
                ['name' => 'Manley Hot Springs', 'state_id' => 3921],
                ['name' => 'Lake Minchumina', 'state_id' => 3921],
                ['name' => 'Minto', 'state_id' => 3921],
                ['name' => 'Nenana', 'state_id' => 3921],
                ['name' => 'Nulato', 'state_id' => 3921],
                ['name' => 'Rampart', 'state_id' => 3921],
                ['name' => 'Ruby', 'state_id' => 3921],
                ['name' => 'Stevens Village', 'state_id' => 3921],
                ['name' => 'Tanana', 'state_id' => 3921],
                ['name' => 'Venetie', 'state_id' => 3921],
                ['name' => 'Chalkyitsik', 'state_id' => 3921]
            ]);
    }
}
