<?php

use Illuminate\Database\Seeder;

class state44TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of TX - Texas.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Frankston', 'state_id' => 3971],
                ['name' => 'Neches', 'state_id' => 3971],
                ['name' => 'Palestine', 'state_id' => 3971],
                ['name' => 'Cayuga', 'state_id' => 3971],
                ['name' => 'Elkhart', 'state_id' => 3971],
                ['name' => 'Montalba', 'state_id' => 3971],
                ['name' => 'Tennessee Colony', 'state_id' => 3971],
                ['name' => 'Andrews', 'state_id' => 3971],
                ['name' => 'Lufkin', 'state_id' => 3971],
                ['name' => 'Diboll', 'state_id' => 3971],
                ['name' => 'Huntington', 'state_id' => 3971],
                ['name' => 'Pollok', 'state_id' => 3971],
                ['name' => 'Zavalla', 'state_id' => 3971],
                ['name' => 'Fulton', 'state_id' => 3971],
                ['name' => 'Rockport', 'state_id' => 3971],
                ['name' => 'Archer City', 'state_id' => 3971],
                ['name' => 'Holliday', 'state_id' => 3971],
                ['name' => 'Megargel', 'state_id' => 3971],
                ['name' => 'Scotland', 'state_id' => 3971],
                ['name' => 'Windthorst', 'state_id' => 3971],
                ['name' => 'Claude', 'state_id' => 3971],
                ['name' => 'Wayside', 'state_id' => 3971],
                ['name' => 'Campbellton', 'state_id' => 3971],
                ['name' => 'Charlotte', 'state_id' => 3971],
                ['name' => 'Christine', 'state_id' => 3971],
                ['name' => 'Jourdanton', 'state_id' => 3971],
                ['name' => 'Leming', 'state_id' => 3971],
                ['name' => 'Lytle', 'state_id' => 3971],
                ['name' => 'Peggy', 'state_id' => 3971],
                ['name' => 'Pleasanton', 'state_id' => 3971],
                ['name' => 'Poteet', 'state_id' => 3971],
                ['name' => 'Bellville', 'state_id' => 3971],
                ['name' => 'Kenney', 'state_id' => 3971],
                ['name' => 'San Felipe', 'state_id' => 3971],
                ['name' => 'Sealy', 'state_id' => 3971],
                ['name' => 'Wallis', 'state_id' => 3971],
                ['name' => 'Bleiblerville', 'state_id' => 3971],
                ['name' => 'Cat Spring', 'state_id' => 3971],
                ['name' => 'Industry', 'state_id' => 3971],
                ['name' => 'New Ulm', 'state_id' => 3971],
                ['name' => 'Enochs', 'state_id' => 3971],
                ['name' => 'Maple', 'state_id' => 3971],
                ['name' => 'Muleshoe', 'state_id' => 3971],
                ['name' => 'Bandera', 'state_id' => 3971],
                ['name' => 'Medina', 'state_id' => 3971],
                ['name' => 'Pipe Creek', 'state_id' => 3971],
                ['name' => 'Tarpley', 'state_id' => 3971],
                ['name' => 'Vanderpool', 'state_id' => 3971],
                ['name' => 'Bastrop', 'state_id' => 3971],
                ['name' => 'Cedar Creek', 'state_id' => 3971],
                ['name' => 'Elgin', 'state_id' => 3971],
                ['name' => 'Mc Dade', 'state_id' => 3971],
                ['name' => 'Paige', 'state_id' => 3971],
                ['name' => 'Red Rock', 'state_id' => 3971],
                ['name' => 'Rosanky', 'state_id' => 3971],
                ['name' => 'Smithville', 'state_id' => 3971],
                ['name' => 'Seymour', 'state_id' => 3971],
                ['name' => 'Beeville', 'state_id' => 3971],
                ['name' => 'Mineral', 'state_id' => 3971],
                ['name' => 'Normanna', 'state_id' => 3971],
                ['name' => 'Pawnee', 'state_id' => 3971],
                ['name' => 'Pettus', 'state_id' => 3971],
                ['name' => 'Tuleta', 'state_id' => 3971],
                ['name' => 'Skidmore', 'state_id' => 3971],
                ['name' => 'Tynan', 'state_id' => 3971],
                ['name' => 'Temple', 'state_id' => 3971],
                ['name' => 'Bartlett', 'state_id' => 3971],
                ['name' => 'Belton', 'state_id' => 3971],
                ['name' => 'Heidenheimer', 'state_id' => 3971],
                ['name' => 'Holland', 'state_id' => 3971],
                ['name' => 'Killeen', 'state_id' => 3971],
                ['name' => 'Fort Hood', 'state_id' => 3971],
                ['name' => 'Harker Heights', 'state_id' => 3971],
                ['name' => 'Little River Academy', 'state_id' => 3971],
                ['name' => 'Nolanville', 'state_id' => 3971],
                ['name' => 'Pendleton', 'state_id' => 3971],
                ['name' => 'Rogers', 'state_id' => 3971],
                ['name' => 'Salado', 'state_id' => 3971],
                ['name' => 'Troy', 'state_id' => 3971],
                ['name' => 'Atascosa', 'state_id' => 3971],
                ['name' => 'Boerne', 'state_id' => 3971],
                ['name' => 'Helotes', 'state_id' => 3971],
                ['name' => 'Macdona', 'state_id' => 3971],
                ['name' => 'Somerset', 'state_id' => 3971],
                ['name' => 'Von Ormy', 'state_id' => 3971],
                ['name' => 'Adkins', 'state_id' => 3971],
                ['name' => 'Converse', 'state_id' => 3971],
                ['name' => 'Elmendorf', 'state_id' => 3971],
                ['name' => 'Universal City', 'state_id' => 3971],
                ['name' => 'Jbsa Randolph', 'state_id' => 3971],
                ['name' => 'Saint Hedwig', 'state_id' => 3971],
                ['name' => 'San Antonio', 'state_id' => 3971],
                ['name' => 'Jbsa Ft Sam Houston', 'state_id' => 3971],
                ['name' => 'Jbsa Lackland', 'state_id' => 3971],
                ['name' => 'Blanco', 'state_id' => 3971],
                ['name' => 'Hye', 'state_id' => 3971],
                ['name' => 'Johnson City', 'state_id' => 3971],
                ['name' => 'Round Mountain', 'state_id' => 3971],
                ['name' => 'Gail', 'state_id' => 3971],
                ['name' => 'Clifton', 'state_id' => 3971],
                ['name' => 'Cranfills Gap', 'state_id' => 3971],
                ['name' => 'Laguna Park', 'state_id' => 3971],
                ['name' => 'Iredell', 'state_id' => 3971],
                ['name' => 'Kopperl', 'state_id' => 3971],
                ['name' => 'Meridian', 'state_id' => 3971],
                ['name' => 'Morgan', 'state_id' => 3971],
                ['name' => 'Valley Mills', 'state_id' => 3971],
                ['name' => 'Walnut Springs', 'state_id' => 3971],
                ['name' => 'Texarkana', 'state_id' => 3971],
                ['name' => 'De Kalb', 'state_id' => 3971],
                ['name' => 'Hooks', 'state_id' => 3971],
                ['name' => 'Maud', 'state_id' => 3971],
                ['name' => 'Nash', 'state_id' => 3971],
                ['name' => 'New Boston', 'state_id' => 3971],
                ['name' => 'Redwater', 'state_id' => 3971],
                ['name' => 'Simms', 'state_id' => 3971],
                ['name' => 'Brazoria', 'state_id' => 3971],
                ['name' => 'Damon', 'state_id' => 3971],
                ['name' => 'Danciger', 'state_id' => 3971],
                ['name' => 'Old Ocean', 'state_id' => 3971],
                ['name' => 'Sweeny', 'state_id' => 3971],
                ['name' => 'West Columbia', 'state_id' => 3971],
                ['name' => 'Alvin', 'state_id' => 3971],
                ['name' => 'Angleton', 'state_id' => 3971],
                ['name' => 'Clute', 'state_id' => 3971],
                ['name' => 'Danbury', 'state_id' => 3971],
                ['name' => 'Freeport', 'state_id' => 3971],
                ['name' => 'Lake Jackson', 'state_id' => 3971],
                ['name' => 'Liverpool', 'state_id' => 3971],
                ['name' => 'Manvel', 'state_id' => 3971],
                ['name' => 'Pearland', 'state_id' => 3971],
                ['name' => 'Rosharon', 'state_id' => 3971],
                ['name' => 'Bryan', 'state_id' => 3971],
                ['name' => 'College Station', 'state_id' => 3971],
                ['name' => 'Kurten', 'state_id' => 3971],
                ['name' => 'Millican', 'state_id' => 3971],
                ['name' => 'Wellborn', 'state_id' => 3971],
                ['name' => 'Alpine', 'state_id' => 3971],
                ['name' => 'Big Bend National Park', 'state_id' => 3971],
                ['name' => 'Marathon', 'state_id' => 3971],
                ['name' => 'Terlingua', 'state_id' => 3971],
                ['name' => 'Quitaque', 'state_id' => 3971],
                ['name' => 'Silverton', 'state_id' => 3971],
                ['name' => 'Encino', 'state_id' => 3971],
                ['name' => 'Falfurrias', 'state_id' => 3971],
                ['name' => 'Blanket', 'state_id' => 3971],
                ['name' => 'Brownwood', 'state_id' => 3971],
                ['name' => 'Early', 'state_id' => 3971],
                ['name' => 'Bangs', 'state_id' => 3971],
                ['name' => 'Brookesmith', 'state_id' => 3971],
                ['name' => 'May', 'state_id' => 3971],
                ['name' => 'Zephyr', 'state_id' => 3971],
                ['name' => 'Caldwell', 'state_id' => 3971],
                ['name' => 'Chriesman', 'state_id' => 3971],
                ['name' => 'Deanville', 'state_id' => 3971],
                ['name' => 'Lyons', 'state_id' => 3971],
                ['name' => 'Snook', 'state_id' => 3971],
                ['name' => 'Somerville', 'state_id' => 3971],
                ['name' => 'Bertram', 'state_id' => 3971],
                ['name' => 'Briggs', 'state_id' => 3971],
                ['name' => 'Burnet', 'state_id' => 3971],
                ['name' => 'Marble Falls', 'state_id' => 3971],
                ['name' => 'Dale', 'state_id' => 3971],
                ['name' => 'Fentress', 'state_id' => 3971],
                ['name' => 'Lockhart', 'state_id' => 3971],
                ['name' => 'Luling', 'state_id' => 3971],
                ['name' => 'Martindale', 'state_id' => 3971],
                ['name' => 'Maxwell', 'state_id' => 3971],
                ['name' => 'Prairie Lea', 'state_id' => 3971],
                ['name' => 'Point Comfort', 'state_id' => 3971],
                ['name' => 'Port Lavaca', 'state_id' => 3971],
                ['name' => 'Port O Connor', 'state_id' => 3971],
                ['name' => 'Seadrift', 'state_id' => 3971],
                ['name' => 'Cross Plains', 'state_id' => 3971],
                ['name' => 'Putnam', 'state_id' => 3971],
                ['name' => 'Baird', 'state_id' => 3971],
                ['name' => 'Clyde', 'state_id' => 3971],
                ['name' => 'Brownsville', 'state_id' => 3971],
                ['name' => 'Combes', 'state_id' => 3971],
                ['name' => 'Harlingen', 'state_id' => 3971],
                ['name' => 'La Feria', 'state_id' => 3971],
                ['name' => 'Los Fresnos', 'state_id' => 3971],
                ['name' => 'Los Indios', 'state_id' => 3971],
                ['name' => 'Lozano', 'state_id' => 3971],
                ['name' => 'Olmito', 'state_id' => 3971],
                ['name' => 'Port Isabel', 'state_id' => 3971],
                ['name' => 'Rio Hondo', 'state_id' => 3971],
                ['name' => 'San Benito', 'state_id' => 3971],
                ['name' => 'Santa Maria', 'state_id' => 3971],
                ['name' => 'Santa Rosa', 'state_id' => 3971],
                ['name' => 'South Padre Island', 'state_id' => 3971],
                ['name' => 'Leesburg', 'state_id' => 3971],
                ['name' => 'Pittsburg', 'state_id' => 3971],
                ['name' => 'Groom', 'state_id' => 3971],
                ['name' => 'Panhandle', 'state_id' => 3971],
                ['name' => 'Skellytown', 'state_id' => 3971],
                ['name' => 'White Deer', 'state_id' => 3971],
                ['name' => 'Atlanta', 'state_id' => 3971],
                ['name' => 'Bivins', 'state_id' => 3971],
                ['name' => 'Bloomburg', 'state_id' => 3971],
                ['name' => 'Douglassville', 'state_id' => 3971],
                ['name' => 'Kildare', 'state_id' => 3971],
                ['name' => 'Linden', 'state_id' => 3971],
                ['name' => 'Mc Leod', 'state_id' => 3971],
                ['name' => 'Marietta', 'state_id' => 3971],
                ['name' => 'Queen City', 'state_id' => 3971],
                ['name' => 'Avinger', 'state_id' => 3971],
                ['name' => 'Hughes Springs', 'state_id' => 3971],
                ['name' => 'Dimmitt', 'state_id' => 3971],
                ['name' => 'Hart', 'state_id' => 3971],
                ['name' => 'Nazareth', 'state_id' => 3971],
                ['name' => 'Summerfield', 'state_id' => 3971],
                ['name' => 'Anahuac', 'state_id' => 3971],
                ['name' => 'Baytown', 'state_id' => 3971],
                ['name' => 'Hankamer', 'state_id' => 3971],
                ['name' => 'Mont Belvieu', 'state_id' => 3971],
                ['name' => 'Wallisville', 'state_id' => 3971],
                ['name' => 'Stowell', 'state_id' => 3971],
                ['name' => 'Winnie', 'state_id' => 3971],
                ['name' => 'Cuney', 'state_id' => 3971],
                ['name' => 'Gallatin', 'state_id' => 3971],
                ['name' => 'Jacksonville', 'state_id' => 3971],
                ['name' => 'Maydelle', 'state_id' => 3971],
                ['name' => 'New Summerfield', 'state_id' => 3971],
                ['name' => 'Reklaw', 'state_id' => 3971],
                ['name' => 'Rusk', 'state_id' => 3971],
                ['name' => 'Alto', 'state_id' => 3971],
                ['name' => 'Wells', 'state_id' => 3971],
                ['name' => 'Childress', 'state_id' => 3971],
                ['name' => 'Tell', 'state_id' => 3971],
                ['name' => 'Bellevue', 'state_id' => 3971],
                ['name' => 'Bluegrove', 'state_id' => 3971],
                ['name' => 'Byers', 'state_id' => 3971],
                ['name' => 'Henrietta', 'state_id' => 3971],
                ['name' => 'Petrolia', 'state_id' => 3971],
                ['name' => 'Bledsoe', 'state_id' => 3971],
                ['name' => 'Morton', 'state_id' => 3971],
                ['name' => 'Whiteface', 'state_id' => 3971],
                ['name' => 'Bronte', 'state_id' => 3971],
                ['name' => 'Robert Lee', 'state_id' => 3971],
                ['name' => 'Silver', 'state_id' => 3971],
                ['name' => 'Tennyson', 'state_id' => 3971],
                ['name' => 'Burkett', 'state_id' => 3971],
                ['name' => 'Coleman', 'state_id' => 3971],
                ['name' => 'Gouldbusk', 'state_id' => 3971],
                ['name' => 'Rockwood', 'state_id' => 3971],
                ['name' => 'Santa Anna', 'state_id' => 3971],
                ['name' => 'Talpa', 'state_id' => 3971],
                ['name' => 'Valera', 'state_id' => 3971],
                ['name' => 'Voss', 'state_id' => 3971],
                ['name' => 'Goldsboro', 'state_id' => 3971],
                ['name' => 'Novice', 'state_id' => 3971],
                ['name' => 'Allen', 'state_id' => 3971],
                ['name' => 'Celina', 'state_id' => 3971],
                ['name' => 'Plano', 'state_id' => 3971],
                ['name' => 'Frisco', 'state_id' => 3971],
                ['name' => 'Mckinney', 'state_id' => 3971],
                ['name' => 'Prosper', 'state_id' => 3971],
                ['name' => 'Weston', 'state_id' => 3971],
                ['name' => 'Copeville', 'state_id' => 3971],
                ['name' => 'Josephine', 'state_id' => 3971],
                ['name' => 'Lavon', 'state_id' => 3971],
                ['name' => 'Nevada', 'state_id' => 3971],
                ['name' => 'Princeton', 'state_id' => 3971],
                ['name' => 'Anna', 'state_id' => 3971],
                ['name' => 'Blue Ridge', 'state_id' => 3971],
                ['name' => 'Farmersville', 'state_id' => 3971],
                ['name' => 'Melissa', 'state_id' => 3971],
                ['name' => 'Westminster', 'state_id' => 3971],
                ['name' => 'Samnorwood', 'state_id' => 3971],
                ['name' => 'Wellington', 'state_id' => 3971],
                ['name' => 'Dodson', 'state_id' => 3971],
                ['name' => 'Quail', 'state_id' => 3971],
                ['name' => 'Altair', 'state_id' => 3971],
                ['name' => 'Eagle Lake', 'state_id' => 3971],
                ['name' => 'Garwood', 'state_id' => 3971],
                ['name' => 'Nada', 'state_id' => 3971],
                ['name' => 'Rock Island', 'state_id' => 3971],
                ['name' => 'Sheridan', 'state_id' => 3971],
                ['name' => 'Columbus', 'state_id' => 3971],
                ['name' => 'Alleyton', 'state_id' => 3971],
                ['name' => 'Glidden', 'state_id' => 3971],
                ['name' => 'Oakland', 'state_id' => 3971],
                ['name' => 'Weimar', 'state_id' => 3971],
                ['name' => 'Spring Branch', 'state_id' => 3971],
                ['name' => 'New Braunfels', 'state_id' => 3971],
                ['name' => 'Canyon Lake', 'state_id' => 3971],
                ['name' => 'Bulverde', 'state_id' => 3971],
                ['name' => 'Fischer', 'state_id' => 3971],
                ['name' => 'Comanche', 'state_id' => 3971],
                ['name' => 'De Leon', 'state_id' => 3971],
                ['name' => 'Energy', 'state_id' => 3971],
                ['name' => 'Gustine', 'state_id' => 3971],
                ['name' => 'Proctor', 'state_id' => 3971],
                ['name' => 'Sidney', 'state_id' => 3971],
                ['name' => 'Eden', 'state_id' => 3971],
                ['name' => 'Lowake', 'state_id' => 3971],
                ['name' => 'Millersview', 'state_id' => 3971],
                ['name' => 'Paint Rock', 'state_id' => 3971],
                ['name' => 'Eola', 'state_id' => 3971],
                ['name' => 'Era', 'state_id' => 3971],
                ['name' => 'Gainesville', 'state_id' => 3971],
                ['name' => 'Lindsay', 'state_id' => 3971],
                ['name' => 'Muenster', 'state_id' => 3971],
                ['name' => 'Myra', 'state_id' => 3971],
                ['name' => 'Rosston', 'state_id' => 3971],
                ['name' => 'Valley View', 'state_id' => 3971],
                ['name' => 'Copperas Cove', 'state_id' => 3971],
                ['name' => 'Evant', 'state_id' => 3971],
                ['name' => 'Flat', 'state_id' => 3971],
                ['name' => 'Gatesville', 'state_id' => 3971],
                ['name' => 'Jonesboro', 'state_id' => 3971],
                ['name' => 'Mound', 'state_id' => 3971],
                ['name' => 'Oglesby', 'state_id' => 3971],
                ['name' => 'Purmela', 'state_id' => 3971],
                ['name' => 'Cee Vee', 'state_id' => 3971],
                ['name' => 'Paducah', 'state_id' => 3971],
                ['name' => 'Crane', 'state_id' => 3971],
                ['name' => 'Ozona', 'state_id' => 3971],
                ['name' => 'Crosbyton', 'state_id' => 3971],
                ['name' => 'Lorenzo', 'state_id' => 3971],
                ['name' => 'Ralls', 'state_id' => 3971],
                ['name' => 'Van Horn', 'state_id' => 3971],
                ['name' => 'Dalhart', 'state_id' => 3971],
                ['name' => 'Kerrick', 'state_id' => 3971],
                ['name' => 'Texline', 'state_id' => 3971],
                ['name' => 'Addison', 'state_id' => 3971],
                ['name' => 'Carrollton', 'state_id' => 3971],
                ['name' => 'Irving', 'state_id' => 3971],
                ['name' => 'Coppell', 'state_id' => 3971],
                ['name' => 'Rowlett', 'state_id' => 3971],
                ['name' => 'Garland', 'state_id' => 3971],
                ['name' => 'Sachse', 'state_id' => 3971],
                ['name' => 'Grand Prairie', 'state_id' => 3971],
                ['name' => 'Richardson', 'state_id' => 3971],
                ['name' => 'Wylie', 'state_id' => 3971],
                ['name' => 'Cedar Hill', 'state_id' => 3971],
                ['name' => 'Desoto', 'state_id' => 3971],
                ['name' => 'Duncanville', 'state_id' => 3971],
                ['name' => 'Lancaster', 'state_id' => 3971],
                ['name' => 'Hutchins', 'state_id' => 3971],
                ['name' => 'Mesquite', 'state_id' => 3971],
                ['name' => 'Seagoville', 'state_id' => 3971],
                ['name' => 'Wilmer', 'state_id' => 3971],
                ['name' => 'Balch Springs', 'state_id' => 3971],
                ['name' => 'Sunnyvale', 'state_id' => 3971],
                ['name' => 'Dallas', 'state_id' => 3971],
                ['name' => 'Lamesa', 'state_id' => 3971],
                ['name' => 'Welch', 'state_id' => 3971],
                ['name' => 'Ackerly', 'state_id' => 3971],
                ['name' => 'Dawn', 'state_id' => 3971],
                ['name' => 'Hereford', 'state_id' => 3971],
                ['name' => 'Ben Franklin', 'state_id' => 3971],
                ['name' => 'Cooper', 'state_id' => 3971],
                ['name' => 'Enloe', 'state_id' => 3971],
                ['name' => 'Klondike', 'state_id' => 3971],
                ['name' => 'Lake Creek', 'state_id' => 3971],
                ['name' => 'Pecan Gap', 'state_id' => 3971],
                ['name' => 'Flower Mound', 'state_id' => 3971],
                ['name' => 'Lewisville', 'state_id' => 3971],
                ['name' => 'The Colony', 'state_id' => 3971],
                ['name' => 'Lake Dallas', 'state_id' => 3971],
                ['name' => 'Little Elm', 'state_id' => 3971],
                ['name' => 'Denton', 'state_id' => 3971],
                ['name' => 'Argyle', 'state_id' => 3971],
                ['name' => 'Aubrey', 'state_id' => 3971],
                ['name' => 'Justin', 'state_id' => 3971],
                ['name' => 'Krum', 'state_id' => 3971],
                ['name' => 'Pilot Point', 'state_id' => 3971],
                ['name' => 'Ponder', 'state_id' => 3971],
                ['name' => 'Roanoke', 'state_id' => 3971],
                ['name' => 'Sanger', 'state_id' => 3971],
                ['name' => 'Cuero', 'state_id' => 3971],
                ['name' => 'Hochheim', 'state_id' => 3971],
                ['name' => 'Meyersville', 'state_id' => 3971],
                ['name' => 'Thomaston', 'state_id' => 3971],
                ['name' => 'Westhoff', 'state_id' => 3971],
                ['name' => 'Nordheim', 'state_id' => 3971],
                ['name' => 'Yorktown', 'state_id' => 3971],
                ['name' => 'Afton', 'state_id' => 3971],
                ['name' => 'Dickens', 'state_id' => 3971],
                ['name' => 'Mcadoo', 'state_id' => 3971],
                ['name' => 'Spur', 'state_id' => 3971],
                ['name' => 'Asherton', 'state_id' => 3971],
                ['name' => 'Big Wells', 'state_id' => 3971],
                ['name' => 'Carrizo Springs', 'state_id' => 3971],
                ['name' => 'Catarina', 'state_id' => 3971],
                ['name' => 'Clarendon', 'state_id' => 3971],
                ['name' => 'Hedley', 'state_id' => 3971],
                ['name' => 'Lelia Lake', 'state_id' => 3971],
                ['name' => 'Benavides', 'state_id' => 3971],
                ['name' => 'Concepcion', 'state_id' => 3971],
                ['name' => 'Freer', 'state_id' => 3971],
                ['name' => 'Realitos', 'state_id' => 3971],
                ['name' => 'San Diego', 'state_id' => 3971],
                ['name' => 'Carbon', 'state_id' => 3971],
                ['name' => 'Cisco', 'state_id' => 3971],
                ['name' => 'Desdemona', 'state_id' => 3971],
                ['name' => 'Eastland', 'state_id' => 3971],
                ['name' => 'Gorman', 'state_id' => 3971],
                ['name' => 'Olden', 'state_id' => 3971],
                ['name' => 'Ranger', 'state_id' => 3971],
                ['name' => 'Rising Star', 'state_id' => 3971],
                ['name' => 'Goldsmith', 'state_id' => 3971],
                ['name' => 'Gardendale', 'state_id' => 3971],
                ['name' => 'Notrees', 'state_id' => 3971],
                ['name' => 'Odessa', 'state_id' => 3971],
                ['name' => 'Penwell', 'state_id' => 3971],
                ['name' => 'Telegraph', 'state_id' => 3971],
                ['name' => 'Barksdale', 'state_id' => 3971],
                ['name' => 'Rocksprings', 'state_id' => 3971],
                ['name' => 'Bardwell', 'state_id' => 3971],
                ['name' => 'Ennis', 'state_id' => 3971],
                ['name' => 'Ferris', 'state_id' => 3971],
                ['name' => 'Palmer', 'state_id' => 3971],
                ['name' => 'Red Oak', 'state_id' => 3971],
                ['name' => 'Rice', 'state_id' => 3971],
                ['name' => 'Waxahachie', 'state_id' => 3971],
                ['name' => 'Forreston', 'state_id' => 3971],
                ['name' => 'Maypearl', 'state_id' => 3971],
                ['name' => 'Midlothian', 'state_id' => 3971],
                ['name' => 'Avalon', 'state_id' => 3971],
                ['name' => 'Italy', 'state_id' => 3971],
                ['name' => 'Milford', 'state_id' => 3971],
                ['name' => 'Anthony', 'state_id' => 3971],
                ['name' => 'Canutillo', 'state_id' => 3971],
                ['name' => 'Clint', 'state_id' => 3971],
                ['name' => 'Fabens', 'state_id' => 3971],
                ['name' => 'San Elizario', 'state_id' => 3971],
                ['name' => 'Tornillo', 'state_id' => 3971],
                ['name' => 'El Paso', 'state_id' => 3971],
                ['name' => 'Fort Bliss', 'state_id' => 3971],
                ['name' => 'Stephenville', 'state_id' => 3971],
                ['name' => 'Bluff Dale', 'state_id' => 3971],
                ['name' => 'Dublin', 'state_id' => 3971],
                ['name' => 'Lingleville', 'state_id' => 3971],
                ['name' => 'Morgan Mill', 'state_id' => 3971],
                ['name' => 'Rosebud', 'state_id' => 3971],
                ['name' => 'Chilton', 'state_id' => 3971],
                ['name' => 'Lott', 'state_id' => 3971],
                ['name' => 'Marlin', 'state_id' => 3971],
                ['name' => 'Reagan', 'state_id' => 3971],
                ['name' => 'Satin', 'state_id' => 3971],
                ['name' => 'Bailey', 'state_id' => 3971],
                ['name' => 'Bonham', 'state_id' => 3971],
                ['name' => 'Dodd City', 'state_id' => 3971],
                ['name' => 'Ector', 'state_id' => 3971],
                ['name' => 'Gober', 'state_id' => 3971],
                ['name' => 'Honey Grove', 'state_id' => 3971],
                ['name' => 'Ivanhoe', 'state_id' => 3971],
                ['name' => 'Ladonia', 'state_id' => 3971],
                ['name' => 'Leonard', 'state_id' => 3971],
                ['name' => 'Randolph', 'state_id' => 3971],
                ['name' => 'Ravenna', 'state_id' => 3971],
                ['name' => 'Savoy', 'state_id' => 3971],
                ['name' => 'Telephone', 'state_id' => 3971],
                ['name' => 'Trenton', 'state_id' => 3971],
                ['name' => 'Windom', 'state_id' => 3971],
                ['name' => 'Carmine', 'state_id' => 3971],
                ['name' => 'Ellinger', 'state_id' => 3971],
                ['name' => 'Fayetteville', 'state_id' => 3971],
                ['name' => 'Flatonia', 'state_id' => 3971],
                ['name' => 'La Grange', 'state_id' => 3971],
                ['name' => 'Ledbetter', 'state_id' => 3971],
                ['name' => 'Muldoon', 'state_id' => 3971],
                ['name' => 'Plum', 'state_id' => 3971],
                ['name' => 'Round Top', 'state_id' => 3971],
                ['name' => 'Schulenburg', 'state_id' => 3971],
                ['name' => 'Warda', 'state_id' => 3971],
                ['name' => 'West Point', 'state_id' => 3971],
                ['name' => 'Mc Caulley', 'state_id' => 3971],
                ['name' => 'Roby', 'state_id' => 3971],
                ['name' => 'Rotan', 'state_id' => 3971],
                ['name' => 'Sylvester', 'state_id' => 3971],
                ['name' => 'Aiken', 'state_id' => 3971],
                ['name' => 'Dougherty', 'state_id' => 3971],
                ['name' => 'Floydada', 'state_id' => 3971],
                ['name' => 'Lockney', 'state_id' => 3971],
                ['name' => 'South Plains', 'state_id' => 3971],
                ['name' => 'Crowell', 'state_id' => 3971],
                ['name' => 'Richmond', 'state_id' => 3971],
                ['name' => 'Beasley', 'state_id' => 3971],
                ['name' => 'Fulshear', 'state_id' => 3971],
                ['name' => 'Guy', 'state_id' => 3971],
                ['name' => 'Kendleton', 'state_id' => 3971],
                ['name' => 'Missouri City', 'state_id' => 3971],
                ['name' => 'Needville', 'state_id' => 3971],
                ['name' => 'Orchard', 'state_id' => 3971],
                ['name' => 'Rosenberg', 'state_id' => 3971],
                ['name' => 'Simonton', 'state_id' => 3971],
                ['name' => 'Stafford', 'state_id' => 3971],
                ['name' => 'Sugar Land', 'state_id' => 3971],
                ['name' => 'Thompsons', 'state_id' => 3971],
                ['name' => 'Fresno', 'state_id' => 3971],
                ['name' => 'Mount Vernon', 'state_id' => 3971],
                ['name' => 'Scroggins', 'state_id' => 3971],
                ['name' => 'Talco', 'state_id' => 3971],
                ['name' => 'Donie', 'state_id' => 3971],
                ['name' => 'Fairfield', 'state_id' => 3971],
                ['name' => 'Kirvin', 'state_id' => 3971],
                ['name' => 'Streetman', 'state_id' => 3971],
                ['name' => 'Teague', 'state_id' => 3971],
                ['name' => 'Wortham', 'state_id' => 3971],
                ['name' => 'Bigfoot', 'state_id' => 3971],
                ['name' => 'Dilley', 'state_id' => 3971],
                ['name' => 'Moore', 'state_id' => 3971],
                ['name' => 'Pearsall', 'state_id' => 3971],
                ['name' => 'Loop', 'state_id' => 3971],
                ['name' => 'Seagraves', 'state_id' => 3971],
                ['name' => 'Seminole', 'state_id' => 3971],
                ['name' => 'Santa Fe', 'state_id' => 3971],
                ['name' => 'Bacliff', 'state_id' => 3971],
                ['name' => 'Dickinson', 'state_id' => 3971],
                ['name' => 'Friendswood', 'state_id' => 3971],
                ['name' => 'Galveston', 'state_id' => 3971],
                ['name' => 'Hitchcock', 'state_id' => 3971],
                ['name' => 'Kemah', 'state_id' => 3971],
                ['name' => 'La Marque', 'state_id' => 3971],
                ['name' => 'League City', 'state_id' => 3971],
                ['name' => 'Texas City', 'state_id' => 3971],
                ['name' => 'Gilchrist', 'state_id' => 3971],
                ['name' => 'High Island', 'state_id' => 3971],
                ['name' => 'Port Bolivar', 'state_id' => 3971],
                ['name' => 'Justiceburg', 'state_id' => 3971],
                ['name' => 'Post', 'state_id' => 3971],
                ['name' => 'Doss', 'state_id' => 3971],
                ['name' => 'Fredericksburg', 'state_id' => 3971],
                ['name' => 'Harper', 'state_id' => 3971],
                ['name' => 'Stonewall', 'state_id' => 3971],
                ['name' => 'Willow City', 'state_id' => 3971],
                ['name' => 'Garden City', 'state_id' => 3971],
                ['name' => 'Fannin', 'state_id' => 3971],
                ['name' => 'Goliad', 'state_id' => 3971],
                ['name' => 'Weesatche', 'state_id' => 3971],
                ['name' => 'Berclair', 'state_id' => 3971],
                ['name' => 'Leesville', 'state_id' => 3971],
                ['name' => 'Nixon', 'state_id' => 3971],
                ['name' => 'Smiley', 'state_id' => 3971],
                ['name' => 'Belmont', 'state_id' => 3971],
                ['name' => 'Cost', 'state_id' => 3971],
                ['name' => 'Gonzales', 'state_id' => 3971],
                ['name' => 'Harwood', 'state_id' => 3971],
                ['name' => 'Ottine', 'state_id' => 3971],
                ['name' => 'Wrightsboro', 'state_id' => 3971],
                ['name' => 'Waelder', 'state_id' => 3971],
                ['name' => 'Alanreed', 'state_id' => 3971],
                ['name' => 'Lefors', 'state_id' => 3971],
                ['name' => 'Mclean', 'state_id' => 3971],
                ['name' => 'Pampa', 'state_id' => 3971],
                ['name' => 'Denison', 'state_id' => 3971],
                ['name' => 'Gunter', 'state_id' => 3971],
                ['name' => 'Pottsboro', 'state_id' => 3971],
                ['name' => 'Sherman', 'state_id' => 3971],
                ['name' => 'Bells', 'state_id' => 3971],
                ['name' => 'Howe', 'state_id' => 3971],
                ['name' => 'Tom Bean', 'state_id' => 3971],
                ['name' => 'Whitewright', 'state_id' => 3971],
                ['name' => 'Van Alstyne', 'state_id' => 3971],
                ['name' => 'Collinsville', 'state_id' => 3971],
                ['name' => 'Gordonville', 'state_id' => 3971],
                ['name' => 'Sadler', 'state_id' => 3971],
                ['name' => 'Southmayd', 'state_id' => 3971],
                ['name' => 'Tioga', 'state_id' => 3971],
                ['name' => 'Whitesboro', 'state_id' => 3971],
                ['name' => 'Longview', 'state_id' => 3971],
                ['name' => 'Easton', 'state_id' => 3971],
                ['name' => 'Gladewater', 'state_id' => 3971],
                ['name' => 'Judson', 'state_id' => 3971],
                ['name' => 'Kilgore', 'state_id' => 3971],
                ['name' => 'White Oak', 'state_id' => 3971],
                ['name' => 'Plantersville', 'state_id' => 3971],
                ['name' => 'Anderson', 'state_id' => 3971],
                ['name' => 'Bedias', 'state_id' => 3971],
                ['name' => 'Iola', 'state_id' => 3971],
                ['name' => 'Navasota', 'state_id' => 3971],
                ['name' => 'Richards', 'state_id' => 3971],
                ['name' => 'Roans Prairie', 'state_id' => 3971],
                ['name' => 'Shiro', 'state_id' => 3971],
                ['name' => 'Cibolo', 'state_id' => 3971],
                ['name' => 'Geronimo', 'state_id' => 3971],
                ['name' => 'Mc Queeney', 'state_id' => 3971],
                ['name' => 'Marion', 'state_id' => 3971],
                ['name' => 'Schertz', 'state_id' => 3971],
                ['name' => 'Seguin', 'state_id' => 3971],
                ['name' => 'Kingsbury', 'state_id' => 3971],
                ['name' => 'Staples', 'state_id' => 3971],
                ['name' => 'Cotton Center', 'state_id' => 3971],
                ['name' => 'Edmonson', 'state_id' => 3971],
                ['name' => 'Hale Center', 'state_id' => 3971],
                ['name' => 'Plainview', 'state_id' => 3971],
                ['name' => 'Petersburg', 'state_id' => 3971],
                ['name' => 'Abernathy', 'state_id' => 3971],
                ['name' => 'Estelline', 'state_id' => 3971],
                ['name' => 'Lakeview', 'state_id' => 3971],
                ['name' => 'Memphis', 'state_id' => 3971],
                ['name' => 'Turkey', 'state_id' => 3971],
                ['name' => 'Carlton', 'state_id' => 3971],
                ['name' => 'Hico', 'state_id' => 3971],
                ['name' => 'Hamilton', 'state_id' => 3971],
                ['name' => 'Pottsville', 'state_id' => 3971],
                ['name' => 'Gruver', 'state_id' => 3971],
                ['name' => 'Morse', 'state_id' => 3971],
                ['name' => 'Spearman', 'state_id' => 3971],
                ['name' => 'Chillicothe', 'state_id' => 3971],
                ['name' => 'Quanah', 'state_id' => 3971],
                ['name' => 'Thicket', 'state_id' => 3971],
                ['name' => 'Votaw', 'state_id' => 3971],
                ['name' => 'Batson', 'state_id' => 3971],
                ['name' => 'Saratoga', 'state_id' => 3971],
                ['name' => 'Kountze', 'state_id' => 3971],
                ['name' => 'Silsbee', 'state_id' => 3971],
                ['name' => 'Lumberton', 'state_id' => 3971],
                ['name' => 'Sour Lake', 'state_id' => 3971],
                ['name' => 'Village Mills', 'state_id' => 3971],
                ['name' => 'Houston', 'state_id' => 3971],
                ['name' => 'North Houston', 'state_id' => 3971],
                ['name' => 'Kingwood', 'state_id' => 3971],
                ['name' => 'Huffman', 'state_id' => 3971],
                ['name' => 'Hufsmith', 'state_id' => 3971],
                ['name' => 'Humble', 'state_id' => 3971],
                ['name' => 'Spring', 'state_id' => 3971],
                ['name' => 'Tomball', 'state_id' => 3971],
                ['name' => 'Bellaire', 'state_id' => 3971],
                ['name' => 'Cypress', 'state_id' => 3971],
                ['name' => 'Alief', 'state_id' => 3971],
                ['name' => 'Barker', 'state_id' => 3971],
                ['name' => 'Hockley', 'state_id' => 3971],
                ['name' => 'Katy', 'state_id' => 3971],
                ['name' => 'Pasadena', 'state_id' => 3971],
                ['name' => 'Channelview', 'state_id' => 3971],
                ['name' => 'Crosby', 'state_id' => 3971],
                ['name' => 'Deer Park', 'state_id' => 3971],
                ['name' => 'Galena Park', 'state_id' => 3971],
                ['name' => 'Highlands', 'state_id' => 3971],
                ['name' => 'La Porte', 'state_id' => 3971],
                ['name' => 'Seabrook', 'state_id' => 3971],
                ['name' => 'South Houston', 'state_id' => 3971],
                ['name' => 'Webster', 'state_id' => 3971],
                ['name' => 'Elysian Fields', 'state_id' => 3971],
                ['name' => 'Hallsville', 'state_id' => 3971],
                ['name' => 'Harleton', 'state_id' => 3971],
                ['name' => 'Jonesville', 'state_id' => 3971],
                ['name' => 'Karnack', 'state_id' => 3971],
                ['name' => 'Marshall', 'state_id' => 3971],
                ['name' => 'Scottsville', 'state_id' => 3971],
                ['name' => 'Waskom', 'state_id' => 3971],
                ['name' => 'Woodlawn', 'state_id' => 3971],
                ['name' => 'Channing', 'state_id' => 3971],
                ['name' => 'Hartley', 'state_id' => 3971],
                ['name' => 'Weinert', 'state_id' => 3971],
                ['name' => 'Haskell', 'state_id' => 3971],
                ['name' => 'O Brien', 'state_id' => 3971],
                ['name' => 'Rochester', 'state_id' => 3971],
                ['name' => 'Rule', 'state_id' => 3971],
                ['name' => 'Buda', 'state_id' => 3971],
                ['name' => 'Driftwood', 'state_id' => 3971],
                ['name' => 'Dripping Springs', 'state_id' => 3971],
                ['name' => 'Kyle', 'state_id' => 3971],
                ['name' => 'San Marcos', 'state_id' => 3971],
                ['name' => 'Wimberley', 'state_id' => 3971],
                ['name' => 'Canadian', 'state_id' => 3971],
                ['name' => 'Eustace', 'state_id' => 3971],
                ['name' => 'Kemp', 'state_id' => 3971],
                ['name' => 'Malakoff', 'state_id' => 3971],
                ['name' => 'Trinidad', 'state_id' => 3971],
                ['name' => 'Athens', 'state_id' => 3971],
                ['name' => 'Brownsboro', 'state_id' => 3971],
                ['name' => 'Chandler', 'state_id' => 3971],
                ['name' => 'Larue', 'state_id' => 3971],
                ['name' => 'Murchison', 'state_id' => 3971],
                ['name' => 'Poynor', 'state_id' => 3971],
                ['name' => 'Mcallen', 'state_id' => 3971],
                ['name' => 'Alamo', 'state_id' => 3971],
                ['name' => 'Donna', 'state_id' => 3971],
                ['name' => 'Edcouch', 'state_id' => 3971],
                ['name' => 'Edinburg', 'state_id' => 3971],
                ['name' => 'Elsa', 'state_id' => 3971],
                ['name' => 'Hargill', 'state_id' => 3971],
                ['name' => 'Hidalgo', 'state_id' => 3971],
                ['name' => 'La Blanca', 'state_id' => 3971],
                ['name' => 'La Joya', 'state_id' => 3971],
                ['name' => 'La Villa', 'state_id' => 3971],
                ['name' => 'Linn', 'state_id' => 3971],
                ['name' => 'Los Ebanos', 'state_id' => 3971],
                ['name' => 'Mercedes', 'state_id' => 3971],
                ['name' => 'Mission', 'state_id' => 3971],
                ['name' => 'Penitas', 'state_id' => 3971],
                ['name' => 'Pharr', 'state_id' => 3971],
                ['name' => 'Progreso', 'state_id' => 3971],
                ['name' => 'San Juan', 'state_id' => 3971],
                ['name' => 'Sullivan City', 'state_id' => 3971],
                ['name' => 'Weslaco', 'state_id' => 3971],
                ['name' => 'Itasca', 'state_id' => 3971],
                ['name' => 'Abbott', 'state_id' => 3971],
                ['name' => 'Aquilla', 'state_id' => 3971],
                ['name' => 'Blum', 'state_id' => 3971],
                ['name' => 'Brandon', 'state_id' => 3971],
                ['name' => 'Bynum', 'state_id' => 3971],
                ['name' => 'Covington', 'state_id' => 3971],
                ['name' => 'Hillsboro', 'state_id' => 3971],
                ['name' => 'Hubbard', 'state_id' => 3971],
                ['name' => 'Irene', 'state_id' => 3971],
                ['name' => 'Malone', 'state_id' => 3971],
                ['name' => 'Mertens', 'state_id' => 3971],
                ['name' => 'Mount Calm', 'state_id' => 3971],
                ['name' => 'Penelope', 'state_id' => 3971],
                ['name' => 'Whitney', 'state_id' => 3971],
                ['name' => 'Anton', 'state_id' => 3971],
                ['name' => 'Levelland', 'state_id' => 3971],
                ['name' => 'Pep', 'state_id' => 3971],
                ['name' => 'Ropesville', 'state_id' => 3971],
                ['name' => 'Smyer', 'state_id' => 3971],
                ['name' => 'Sundown', 'state_id' => 3971],
                ['name' => 'Whitharral', 'state_id' => 3971],
                ['name' => 'Cresson', 'state_id' => 3971],
                ['name' => 'Granbury', 'state_id' => 3971],
                ['name' => 'Lipan', 'state_id' => 3971],
                ['name' => 'Paluxy', 'state_id' => 3971],
                ['name' => 'Tolar', 'state_id' => 3971],
                ['name' => 'Brashear', 'state_id' => 3971],
                ['name' => 'Como', 'state_id' => 3971],
                ['name' => 'Cumby', 'state_id' => 3971],
                ['name' => 'Dike', 'state_id' => 3971],
                ['name' => 'Pickton', 'state_id' => 3971],
                ['name' => 'Saltillo', 'state_id' => 3971],
                ['name' => 'Sulphur Bluff', 'state_id' => 3971],
                ['name' => 'Sulphur Springs', 'state_id' => 3971],
                ['name' => 'Crockett', 'state_id' => 3971],
                ['name' => 'Grapeland', 'state_id' => 3971],
                ['name' => 'Kennard', 'state_id' => 3971],
                ['name' => 'Latexo', 'state_id' => 3971],
                ['name' => 'Lovelady', 'state_id' => 3971],
                ['name' => 'Ratcliff', 'state_id' => 3971],
                ['name' => 'Coahoma', 'state_id' => 3971],
                ['name' => 'Big Spring', 'state_id' => 3971],
                ['name' => 'Forsan', 'state_id' => 3971],
                ['name' => 'Knott', 'state_id' => 3971],
                ['name' => 'Dell City', 'state_id' => 3971],
                ['name' => 'Fort Hancock', 'state_id' => 3971],
                ['name' => 'Salt Flat', 'state_id' => 3971],
                ['name' => 'Sierra Blanca', 'state_id' => 3971],
                ['name' => 'Caddo Mills', 'state_id' => 3971],
                ['name' => 'Greenville', 'state_id' => 3971],
                ['name' => 'Campbell', 'state_id' => 3971],
                ['name' => 'Celeste', 'state_id' => 3971],
                ['name' => 'Commerce', 'state_id' => 3971],
                ['name' => 'Lone Oak', 'state_id' => 3971],
                ['name' => 'Merit', 'state_id' => 3971],
                ['name' => 'Quinlan', 'state_id' => 3971],
                ['name' => 'Wolfe City', 'state_id' => 3971],
                ['name' => 'Borger', 'state_id' => 3971],
                ['name' => 'Fritch', 'state_id' => 3971],
                ['name' => 'Sanford', 'state_id' => 3971],
                ['name' => 'Stinnett', 'state_id' => 3971],
                ['name' => 'Barnhart', 'state_id' => 3971],
                ['name' => 'Mertzon', 'state_id' => 3971],
                ['name' => 'Bryson', 'state_id' => 3971],
                ['name' => 'Jacksboro', 'state_id' => 3971],
                ['name' => 'Jermyn', 'state_id' => 3971],
                ['name' => 'Perrin', 'state_id' => 3971],
                ['name' => 'Edna', 'state_id' => 3971],
                ['name' => 'Francitas', 'state_id' => 3971],
                ['name' => 'Ganado', 'state_id' => 3971],
                ['name' => 'La Salle', 'state_id' => 3971],
                ['name' => 'La Ward', 'state_id' => 3971],
                ['name' => 'Lolita', 'state_id' => 3971],
                ['name' => 'Vanderbilt', 'state_id' => 3971],
                ['name' => 'Jasper', 'state_id' => 3971],
                ['name' => 'Kirbyville', 'state_id' => 3971],
                ['name' => 'Buna', 'state_id' => 3971],
                ['name' => 'Evadale', 'state_id' => 3971],
                ['name' => 'Fort Davis', 'state_id' => 3971],
                ['name' => 'Valentine', 'state_id' => 3971],
                ['name' => 'China', 'state_id' => 3971],
                ['name' => 'Groves', 'state_id' => 3971],
                ['name' => 'Hamshire', 'state_id' => 3971],
                ['name' => 'Nederland', 'state_id' => 3971],
                ['name' => 'Nome', 'state_id' => 3971],
                ['name' => 'Port Arthur', 'state_id' => 3971],
                ['name' => 'Port Neches', 'state_id' => 3971],
                ['name' => 'Sabine Pass', 'state_id' => 3971],
                ['name' => 'Beaumont', 'state_id' => 3971],
                ['name' => 'Guerra', 'state_id' => 3971],
                ['name' => 'Hebbronville', 'state_id' => 3971],
                ['name' => 'Alice', 'state_id' => 3971],
                ['name' => 'Ben Bolt', 'state_id' => 3971],
                ['name' => 'Orange Grove', 'state_id' => 3971],
                ['name' => 'Premont', 'state_id' => 3971],
                ['name' => 'Sandia', 'state_id' => 3971],
                ['name' => 'Alvarado', 'state_id' => 3971],
                ['name' => 'Burleson', 'state_id' => 3971],
                ['name' => 'Cleburne', 'state_id' => 3971],
                ['name' => 'Godley', 'state_id' => 3971],
                ['name' => 'Grandview', 'state_id' => 3971],
                ['name' => 'Joshua', 'state_id' => 3971],
                ['name' => 'Keene', 'state_id' => 3971],
                ['name' => 'Lillian', 'state_id' => 3971],
                ['name' => 'Venus', 'state_id' => 3971],
                ['name' => 'Rio Vista', 'state_id' => 3971],
                ['name' => 'Anson', 'state_id' => 3971],
                ['name' => 'Avoca', 'state_id' => 3971],
                ['name' => 'Hamlin', 'state_id' => 3971],
                ['name' => 'Hawley', 'state_id' => 3971],
                ['name' => 'Lueders', 'state_id' => 3971],
                ['name' => 'Stamford', 'state_id' => 3971],
                ['name' => 'Ecleto', 'state_id' => 3971],
                ['name' => 'Falls City', 'state_id' => 3971],
                ['name' => 'Gillett', 'state_id' => 3971],
                ['name' => 'Hobson', 'state_id' => 3971],
                ['name' => 'Karnes City', 'state_id' => 3971],
                ['name' => 'Kenedy', 'state_id' => 3971],
                ['name' => 'Panna Maria', 'state_id' => 3971],
                ['name' => 'Runge', 'state_id' => 3971],
                ['name' => 'Crandall', 'state_id' => 3971],
                ['name' => 'Elmo', 'state_id' => 3971],
                ['name' => 'Forney', 'state_id' => 3971],
                ['name' => 'Kaufman', 'state_id' => 3971],
                ['name' => 'Mabank', 'state_id' => 3971],
                ['name' => 'Rosser', 'state_id' => 3971],
                ['name' => 'Scurry', 'state_id' => 3971],
                ['name' => 'Terrell', 'state_id' => 3971],
                ['name' => 'Bergheim', 'state_id' => 3971],
                ['name' => 'Comfort', 'state_id' => 3971],
                ['name' => 'Kendalia', 'state_id' => 3971],
                ['name' => 'Waring', 'state_id' => 3971],
                ['name' => 'Armstrong', 'state_id' => 3971],
                ['name' => 'Sarita', 'state_id' => 3971],
                ['name' => 'Girard', 'state_id' => 3971],
                ['name' => 'Jayton', 'state_id' => 3971],
                ['name' => 'Center Point', 'state_id' => 3971],
                ['name' => 'Hunt', 'state_id' => 3971],
                ['name' => 'Ingram', 'state_id' => 3971],
                ['name' => 'Kerrville', 'state_id' => 3971],
                ['name' => 'Mountain Home', 'state_id' => 3971],
                ['name' => 'Junction', 'state_id' => 3971],
                ['name' => 'London', 'state_id' => 3971],
                ['name' => 'Roosevelt', 'state_id' => 3971],
                ['name' => 'Guthrie', 'state_id' => 3971],
                ['name' => 'Brackettville', 'state_id' => 3971],
                ['name' => 'Kingsville', 'state_id' => 3971],
                ['name' => 'Riviera', 'state_id' => 3971],
                ['name' => 'Goree', 'state_id' => 3971],
                ['name' => 'Munday', 'state_id' => 3971],
                ['name' => 'Benjamin', 'state_id' => 3971],
                ['name' => 'Knox City', 'state_id' => 3971],
                ['name' => 'Arthur City', 'state_id' => 3971],
                ['name' => 'Blossom', 'state_id' => 3971],
                ['name' => 'Brookston', 'state_id' => 3971],
                ['name' => 'Chicota', 'state_id' => 3971],
                ['name' => 'Cunningham', 'state_id' => 3971],
                ['name' => 'Deport', 'state_id' => 3971],
                ['name' => 'Paris', 'state_id' => 3971],
                ['name' => 'Pattonville', 'state_id' => 3971],
                ['name' => 'Petty', 'state_id' => 3971],
                ['name' => 'Powderly', 'state_id' => 3971],
                ['name' => 'Roxton', 'state_id' => 3971],
                ['name' => 'Sumner', 'state_id' => 3971],
                ['name' => 'Earth', 'state_id' => 3971],
                ['name' => 'Olton', 'state_id' => 3971],
                ['name' => 'Springlake', 'state_id' => 3971],
                ['name' => 'Amherst', 'state_id' => 3971],
                ['name' => 'Fieldton', 'state_id' => 3971],
                ['name' => 'Littlefield', 'state_id' => 3971],
                ['name' => 'Spade', 'state_id' => 3971],
                ['name' => 'Sudan', 'state_id' => 3971],
                ['name' => 'Kempner', 'state_id' => 3971],
                ['name' => 'Lampasas', 'state_id' => 3971],
                ['name' => 'Bend', 'state_id' => 3971],
                ['name' => 'Lometa', 'state_id' => 3971],
                ['name' => 'Artesia Wells', 'state_id' => 3971],
                ['name' => 'Cotulla', 'state_id' => 3971],
                ['name' => 'Encinal', 'state_id' => 3971],
                ['name' => 'Fowlerton', 'state_id' => 3971],
                ['name' => 'Hallettsville', 'state_id' => 3971],
                ['name' => 'Moulton', 'state_id' => 3971],
                ['name' => 'Shiner', 'state_id' => 3971],
                ['name' => 'Sublime', 'state_id' => 3971],
                ['name' => 'Sweet Home', 'state_id' => 3971],
                ['name' => 'Yoakum', 'state_id' => 3971],
                ['name' => 'Dime Box', 'state_id' => 3971],
                ['name' => 'Giddings', 'state_id' => 3971],
                ['name' => 'Lexington', 'state_id' => 3971],
                ['name' => 'Lincoln', 'state_id' => 3971],
                ['name' => 'Buffalo', 'state_id' => 3971],
                ['name' => 'Centerville', 'state_id' => 3971],
                ['name' => 'Jewett', 'state_id' => 3971],
                ['name' => 'Leona', 'state_id' => 3971],
                ['name' => 'Oakwood', 'state_id' => 3971],
                ['name' => 'Concord', 'state_id' => 3971],
                ['name' => 'Flynn', 'state_id' => 3971],
                ['name' => 'Marquez', 'state_id' => 3971],
                ['name' => 'Normangee', 'state_id' => 3971],
                ['name' => 'Cleveland', 'state_id' => 3971],
                ['name' => 'Romayor', 'state_id' => 3971],
                ['name' => 'Rye', 'state_id' => 3971],
                ['name' => 'Daisetta', 'state_id' => 3971],
                ['name' => 'Dayton', 'state_id' => 3971],
                ['name' => 'Devers', 'state_id' => 3971],
                ['name' => 'Hardin', 'state_id' => 3971],
                ['name' => 'Hull', 'state_id' => 3971],
                ['name' => 'Liberty', 'state_id' => 3971],
                ['name' => 'Raywood', 'state_id' => 3971],
                ['name' => 'Coolidge', 'state_id' => 3971],
                ['name' => 'Groesbeck', 'state_id' => 3971],
                ['name' => 'Kosse', 'state_id' => 3971],
                ['name' => 'Mexia', 'state_id' => 3971],
                ['name' => 'Prairie Hill', 'state_id' => 3971],
                ['name' => 'Tehuacana', 'state_id' => 3971],
                ['name' => 'Thornton', 'state_id' => 3971],
                ['name' => 'Booker', 'state_id' => 3971],
                ['name' => 'Darrouzett', 'state_id' => 3971],
                ['name' => 'Follett', 'state_id' => 3971],
                ['name' => 'Higgins', 'state_id' => 3971],
                ['name' => 'Lipscomb', 'state_id' => 3971],
                ['name' => 'George West', 'state_id' => 3971],
                ['name' => 'Oakville', 'state_id' => 3971],
                ['name' => 'Three Rivers', 'state_id' => 3971],
                ['name' => 'Whitsett', 'state_id' => 3971],
                ['name' => 'Dinero', 'state_id' => 3971],
                ['name' => 'Castell', 'state_id' => 3971],
                ['name' => 'Valley Spring', 'state_id' => 3971],
                ['name' => 'Bluffton', 'state_id' => 3971],
                ['name' => 'Buchanan Dam', 'state_id' => 3971],
                ['name' => 'Kingsland', 'state_id' => 3971],
                ['name' => 'Llano', 'state_id' => 3971],
                ['name' => 'Horseshoe Bay', 'state_id' => 3971],
                ['name' => 'Tow', 'state_id' => 3971],
                ['name' => 'Mentone', 'state_id' => 3971],
                ['name' => 'Idalou', 'state_id' => 3971],
                ['name' => 'New Deal', 'state_id' => 3971],
                ['name' => 'Shallowater', 'state_id' => 3971],
                ['name' => 'Slaton', 'state_id' => 3971],
                ['name' => 'Ransom Canyon', 'state_id' => 3971],
                ['name' => 'Wolfforth', 'state_id' => 3971],
                ['name' => 'Lubbock', 'state_id' => 3971],
                ['name' => 'Odonnell', 'state_id' => 3971],
                ['name' => 'Tahoka', 'state_id' => 3971],
                ['name' => 'Wilson', 'state_id' => 3971],
                ['name' => 'New Home', 'state_id' => 3971],
                ['name' => 'Brady', 'state_id' => 3971],
                ['name' => 'Doole', 'state_id' => 3971],
                ['name' => 'Lohn', 'state_id' => 3971],
                ['name' => 'Melvin', 'state_id' => 3971],
                ['name' => 'Rochelle', 'state_id' => 3971],
                ['name' => 'Voca', 'state_id' => 3971],
                ['name' => 'Eddy', 'state_id' => 3971],
                ['name' => 'Moody', 'state_id' => 3971],
                ['name' => 'Axtell', 'state_id' => 3971],
                ['name' => 'Bruceville', 'state_id' => 3971],
                ['name' => 'China Spring', 'state_id' => 3971],
                ['name' => 'Crawford', 'state_id' => 3971],
                ['name' => 'Elm Mott', 'state_id' => 3971],
                ['name' => 'Hewitt', 'state_id' => 3971],
                ['name' => 'Leroy', 'state_id' => 3971],
                ['name' => 'Lorena', 'state_id' => 3971],
                ['name' => 'Mc Gregor', 'state_id' => 3971],
                ['name' => 'Mart', 'state_id' => 3971],
                ['name' => 'Riesel', 'state_id' => 3971],
                ['name' => 'Ross', 'state_id' => 3971],
                ['name' => 'West', 'state_id' => 3971],
                ['name' => 'Waco', 'state_id' => 3971],
                ['name' => 'Woodway', 'state_id' => 3971],
                ['name' => 'Calliham', 'state_id' => 3971],
                ['name' => 'Tilden', 'state_id' => 3971],
                ['name' => 'Midway', 'state_id' => 3971],
                ['name' => 'Madisonville', 'state_id' => 3971],
                ['name' => 'North Zulch', 'state_id' => 3971],
                ['name' => 'Lodi', 'state_id' => 3971],
                ['name' => 'Jefferson', 'state_id' => 3971],
                ['name' => 'Lenorah', 'state_id' => 3971],
                ['name' => 'Stanton', 'state_id' => 3971],
                ['name' => 'Tarzan', 'state_id' => 3971],
                ['name' => 'Art', 'state_id' => 3971],
                ['name' => 'Fredonia', 'state_id' => 3971],
                ['name' => 'Mason', 'state_id' => 3971],
                ['name' => 'Pontotoc', 'state_id' => 3971],
                ['name' => 'Bay City', 'state_id' => 3971],
                ['name' => 'Cedar Lane', 'state_id' => 3971],
                ['name' => 'Blessing', 'state_id' => 3971],
                ['name' => 'Collegeport', 'state_id' => 3971],
                ['name' => 'Elmaton', 'state_id' => 3971],
                ['name' => 'Markham', 'state_id' => 3971],
                ['name' => 'Matagorda', 'state_id' => 3971],
                ['name' => 'Midfield', 'state_id' => 3971],
                ['name' => 'Palacios', 'state_id' => 3971],
                ['name' => 'Pledger', 'state_id' => 3971],
                ['name' => 'Van Vleck', 'state_id' => 3971],
                ['name' => 'Wadsworth', 'state_id' => 3971],
                ['name' => 'Eagle Pass', 'state_id' => 3971],
                ['name' => 'El Indio', 'state_id' => 3971],
                ['name' => 'Quemado', 'state_id' => 3971],
                ['name' => 'Castroville', 'state_id' => 3971],
                ['name' => 'Devine', 'state_id' => 3971],
                ['name' => 'La Coste', 'state_id' => 3971],
                ['name' => 'Mico', 'state_id' => 3971],
                ['name' => 'Natalia', 'state_id' => 3971],
                ['name' => 'Rio Medina', 'state_id' => 3971],
                ['name' => 'D Hanis', 'state_id' => 3971],
                ['name' => 'Hondo', 'state_id' => 3971],
                ['name' => 'Yancey', 'state_id' => 3971],
                ['name' => 'Fort Mc Kavett', 'state_id' => 3971],
                ['name' => 'Hext', 'state_id' => 3971],
                ['name' => 'Menard', 'state_id' => 3971],
                ['name' => 'Midland', 'state_id' => 3971],
                ['name' => 'Buckholts', 'state_id' => 3971],
                ['name' => 'Burlington', 'state_id' => 3971],
                ['name' => 'Cameron', 'state_id' => 3971],
                ['name' => 'Davilla', 'state_id' => 3971],
                ['name' => 'Milano', 'state_id' => 3971],
                ['name' => 'Rockdale', 'state_id' => 3971],
                ['name' => 'Thorndale', 'state_id' => 3971],
                ['name' => 'Gause', 'state_id' => 3971],
                ['name' => 'Goldthwaite', 'state_id' => 3971],
                ['name' => 'Mullin', 'state_id' => 3971],
                ['name' => 'Priddy', 'state_id' => 3971],
                ['name' => 'Star', 'state_id' => 3971],
                ['name' => 'Colorado City', 'state_id' => 3971],
                ['name' => 'Loraine', 'state_id' => 3971],
                ['name' => 'Westbrook', 'state_id' => 3971],
                ['name' => 'Bowie', 'state_id' => 3971],
                ['name' => 'Forestburg', 'state_id' => 3971],
                ['name' => 'Montague', 'state_id' => 3971],
                ['name' => 'Nocona', 'state_id' => 3971],
                ['name' => 'Ringgold', 'state_id' => 3971],
                ['name' => 'Saint Jo', 'state_id' => 3971],
                ['name' => 'Sunset', 'state_id' => 3971],
                ['name' => 'Conroe', 'state_id' => 3971],
                ['name' => 'Montgomery', 'state_id' => 3971],
                ['name' => 'Willis', 'state_id' => 3971],
                ['name' => 'Dobbin', 'state_id' => 3971],
                ['name' => 'Magnolia', 'state_id' => 3971],
                ['name' => 'New Caney', 'state_id' => 3971],
                ['name' => 'Pinehurst', 'state_id' => 3971],
                ['name' => 'Porter', 'state_id' => 3971],
                ['name' => 'Splendora', 'state_id' => 3971],
                ['name' => 'Cactus', 'state_id' => 3971],
                ['name' => 'Dumas', 'state_id' => 3971],
                ['name' => 'Masterson', 'state_id' => 3971],
                ['name' => 'Sunray', 'state_id' => 3971],
                ['name' => 'Naples', 'state_id' => 3971],
                ['name' => 'Omaha', 'state_id' => 3971],
                ['name' => 'Cason', 'state_id' => 3971],
                ['name' => 'Daingerfield', 'state_id' => 3971],
                ['name' => 'Lone Star', 'state_id' => 3971],
                ['name' => 'Flomot', 'state_id' => 3971],
                ['name' => 'Matador', 'state_id' => 3971],
                ['name' => 'Roaring Springs', 'state_id' => 3971],
                ['name' => 'Cushing', 'state_id' => 3971],
                ['name' => 'Sacul', 'state_id' => 3971],
                ['name' => 'Chireno', 'state_id' => 3971],
                ['name' => 'Douglass', 'state_id' => 3971],
                ['name' => 'Etoile', 'state_id' => 3971],
                ['name' => 'Garrison', 'state_id' => 3971],
                ['name' => 'Martinsville', 'state_id' => 3971],
                ['name' => 'Nacogdoches', 'state_id' => 3971],
                ['name' => 'Woden', 'state_id' => 3971],
                ['name' => 'Barry', 'state_id' => 3971],
                ['name' => 'Chatfield', 'state_id' => 3971],
                ['name' => 'Corsicana', 'state_id' => 3971],
                ['name' => 'Kerens', 'state_id' => 3971],
                ['name' => 'Powell', 'state_id' => 3971],
                ['name' => 'Blooming Grove', 'state_id' => 3971],
                ['name' => 'Dawson', 'state_id' => 3971],
                ['name' => 'Frost', 'state_id' => 3971],
                ['name' => 'Purdon', 'state_id' => 3971],
                ['name' => 'Richland', 'state_id' => 3971],
                ['name' => 'Bon Wier', 'state_id' => 3971],
                ['name' => 'Burkeville', 'state_id' => 3971],
                ['name' => 'Call', 'state_id' => 3971],
                ['name' => 'Newton', 'state_id' => 3971],
                ['name' => 'Wiergate', 'state_id' => 3971],
                ['name' => 'Deweyville', 'state_id' => 3971],
                ['name' => 'Blackwell', 'state_id' => 3971],
                ['name' => 'Maryneal', 'state_id' => 3971],
                ['name' => 'Nolan', 'state_id' => 3971],
                ['name' => 'Roscoe', 'state_id' => 3971],
                ['name' => 'Sweetwater', 'state_id' => 3971],
                ['name' => 'Agua Dulce', 'state_id' => 3971],
                ['name' => 'Banquete', 'state_id' => 3971],
                ['name' => 'Bishop', 'state_id' => 3971],
                ['name' => 'Chapman Ranch', 'state_id' => 3971],
                ['name' => 'Driscoll', 'state_id' => 3971],
                ['name' => 'Port Aransas', 'state_id' => 3971],
                ['name' => 'Robstown', 'state_id' => 3971],
                ['name' => 'Corpus Christi', 'state_id' => 3971],
                ['name' => 'Farnsworth', 'state_id' => 3971],
                ['name' => 'Perryton', 'state_id' => 3971],
                ['name' => 'Waka', 'state_id' => 3971],
                ['name' => 'Adrian', 'state_id' => 3971],
                ['name' => 'Boys Ranch', 'state_id' => 3971],
                ['name' => 'Vega', 'state_id' => 3971],
                ['name' => 'Wildorado', 'state_id' => 3971],
                ['name' => 'Bridge City', 'state_id' => 3971],
                ['name' => 'Mauriceville', 'state_id' => 3971],
                ['name' => 'Orange', 'state_id' => 3971],
                ['name' => 'Orangefield', 'state_id' => 3971],
                ['name' => 'Vidor', 'state_id' => 3971],
                ['name' => 'Mineral Wells', 'state_id' => 3971],
                ['name' => 'Graford', 'state_id' => 3971],
                ['name' => 'Gordon', 'state_id' => 3971],
                ['name' => 'Mingus', 'state_id' => 3971],
                ['name' => 'Santo', 'state_id' => 3971],
                ['name' => 'Strawn', 'state_id' => 3971],
                ['name' => 'Palo Pinto', 'state_id' => 3971],
                ['name' => 'Beckville', 'state_id' => 3971],
                ['name' => 'Carthage', 'state_id' => 3971],
                ['name' => 'Clayton', 'state_id' => 3971],
                ['name' => 'De Berry', 'state_id' => 3971],
                ['name' => 'Gary', 'state_id' => 3971],
                ['name' => 'Long Branch', 'state_id' => 3971],
                ['name' => 'Panola', 'state_id' => 3971],
                ['name' => 'Aledo', 'state_id' => 3971],
                ['name' => 'Millsap', 'state_id' => 3971],
                ['name' => 'Springtown', 'state_id' => 3971],
                ['name' => 'Weatherford', 'state_id' => 3971],
                ['name' => 'Azle', 'state_id' => 3971],
                ['name' => 'Dennis', 'state_id' => 3971],
                ['name' => 'Peaster', 'state_id' => 3971],
                ['name' => 'Poolville', 'state_id' => 3971],
                ['name' => 'Whitt', 'state_id' => 3971],
                ['name' => 'Bovina', 'state_id' => 3971],
                ['name' => 'Friona', 'state_id' => 3971],
                ['name' => 'Lazbuddie', 'state_id' => 3971],
                ['name' => 'Farwell', 'state_id' => 3971],
                ['name' => 'Coyanosa', 'state_id' => 3971],
                ['name' => 'Fort Stockton', 'state_id' => 3971],
                ['name' => 'Girvin', 'state_id' => 3971],
                ['name' => 'Imperial', 'state_id' => 3971],
                ['name' => 'Iraan', 'state_id' => 3971],
                ['name' => 'Sheffield', 'state_id' => 3971],
                ['name' => 'Camden', 'state_id' => 3971],
                ['name' => 'Corrigan', 'state_id' => 3971],
                ['name' => 'Moscow', 'state_id' => 3971],
                ['name' => 'Ace', 'state_id' => 3971],
                ['name' => 'Dallardsville', 'state_id' => 3971],
                ['name' => 'Goodrich', 'state_id' => 3971],
                ['name' => 'Leggett', 'state_id' => 3971],
                ['name' => 'Livingston', 'state_id' => 3971],
                ['name' => 'Onalaska', 'state_id' => 3971],
                ['name' => 'Bushland', 'state_id' => 3971],
                ['name' => 'Amarillo', 'state_id' => 3971],
                ['name' => 'Marfa', 'state_id' => 3971],
                ['name' => 'Presidio', 'state_id' => 3971],
                ['name' => 'Redford', 'state_id' => 3971],
                ['name' => 'Alba', 'state_id' => 3971],
                ['name' => 'Emory', 'state_id' => 3971],
                ['name' => 'Point', 'state_id' => 3971],
                ['name' => 'Canyon', 'state_id' => 3971],
                ['name' => 'Umbarger', 'state_id' => 3971],
                ['name' => 'Big Lake', 'state_id' => 3971],
                ['name' => 'Camp Wood', 'state_id' => 3971],
                ['name' => 'Leakey', 'state_id' => 3971],
                ['name' => 'Rio Frio', 'state_id' => 3971],
                ['name' => 'Bagwell', 'state_id' => 3971],
                ['name' => 'Bogata', 'state_id' => 3971],
                ['name' => 'Clarksville', 'state_id' => 3971],
                ['name' => 'Detroit', 'state_id' => 3971],
                ['name' => 'Annona', 'state_id' => 3971],
                ['name' => 'Avery', 'state_id' => 3971],
                ['name' => 'Balmorhea', 'state_id' => 3971],
                ['name' => 'Orla', 'state_id' => 3971],
                ['name' => 'Pecos', 'state_id' => 3971],
                ['name' => 'Saragosa', 'state_id' => 3971],
                ['name' => 'Toyah', 'state_id' => 3971],
                ['name' => 'Toyahvale', 'state_id' => 3971],
                ['name' => 'Austwell', 'state_id' => 3971],
                ['name' => 'Tivoli', 'state_id' => 3971],
                ['name' => 'Bayside', 'state_id' => 3971],
                ['name' => 'Refugio', 'state_id' => 3971],
                ['name' => 'Woodsboro', 'state_id' => 3971],
                ['name' => 'Miami', 'state_id' => 3971],
                ['name' => 'Bremond', 'state_id' => 3971],
                ['name' => 'Calvert', 'state_id' => 3971],
                ['name' => 'Franklin', 'state_id' => 3971],
                ['name' => 'Hearne', 'state_id' => 3971],
                ['name' => 'Mumford', 'state_id' => 3971],
                ['name' => 'New Baden', 'state_id' => 3971],
                ['name' => 'Wheelock', 'state_id' => 3971],
                ['name' => 'Rockwall', 'state_id' => 3971],
                ['name' => 'Fate', 'state_id' => 3971],
                ['name' => 'Royse City', 'state_id' => 3971],
                ['name' => 'Ballinger', 'state_id' => 3971],
                ['name' => 'Miles', 'state_id' => 3971],
                ['name' => 'Norton', 'state_id' => 3971],
                ['name' => 'Rowena', 'state_id' => 3971],
                ['name' => 'Wingate', 'state_id' => 3971],
                ['name' => 'Winters', 'state_id' => 3971],
                ['name' => 'Henderson', 'state_id' => 3971],
                ['name' => 'Joinerville', 'state_id' => 3971],
                ['name' => 'Laird Hill', 'state_id' => 3971],
                ['name' => 'Laneville', 'state_id' => 3971],
                ['name' => 'Minden', 'state_id' => 3971],
                ['name' => 'Mount Enterprise', 'state_id' => 3971],
                ['name' => 'New London', 'state_id' => 3971],
                ['name' => 'Overton', 'state_id' => 3971],
                ['name' => 'Price', 'state_id' => 3971],
                ['name' => 'Selman City', 'state_id' => 3971],
                ['name' => 'Tatum', 'state_id' => 3971],
                ['name' => 'Bronson', 'state_id' => 3971],
                ['name' => 'Brookeland', 'state_id' => 3971],
                ['name' => 'Hemphill', 'state_id' => 3971],
                ['name' => 'Milam', 'state_id' => 3971],
                ['name' => 'Pineland', 'state_id' => 3971],
                ['name' => 'Broaddus', 'state_id' => 3971],
                ['name' => 'San Augustine', 'state_id' => 3971],
                ['name' => 'Coldspring', 'state_id' => 3971],
                ['name' => 'Oakhurst', 'state_id' => 3971],
                ['name' => 'Pointblank', 'state_id' => 3971],
                ['name' => 'Shepherd', 'state_id' => 3971],
                ['name' => 'Aransas Pass', 'state_id' => 3971],
                ['name' => 'Edroy', 'state_id' => 3971],
                ['name' => 'Gregory', 'state_id' => 3971],
                ['name' => 'Ingleside', 'state_id' => 3971],
                ['name' => 'Mathis', 'state_id' => 3971],
                ['name' => 'Odem', 'state_id' => 3971],
                ['name' => 'Portland', 'state_id' => 3971],
                ['name' => 'Sinton', 'state_id' => 3971],
                ['name' => 'Taft', 'state_id' => 3971],
                ['name' => 'Cherokee', 'state_id' => 3971],
                ['name' => 'Richland Springs', 'state_id' => 3971],
                ['name' => 'San Saba', 'state_id' => 3971],
                ['name' => 'Eldorado', 'state_id' => 3971],
                ['name' => 'Dunn', 'state_id' => 3971],
                ['name' => 'Fluvanna', 'state_id' => 3971],
                ['name' => 'Hermleigh', 'state_id' => 3971],
                ['name' => 'Ira', 'state_id' => 3971],
                ['name' => 'Snyder', 'state_id' => 3971],
                ['name' => 'Albany', 'state_id' => 3971],
                ['name' => 'Moran', 'state_id' => 3971],
                ['name' => 'Center', 'state_id' => 3971],
                ['name' => 'Joaquin', 'state_id' => 3971],
                ['name' => 'Shelbyville', 'state_id' => 3971],
                ['name' => 'Tenaha', 'state_id' => 3971],
                ['name' => 'Timpson', 'state_id' => 3971],
                ['name' => 'Texhoma', 'state_id' => 3971],
                ['name' => 'Stratford', 'state_id' => 3971],
                ['name' => 'Tyler', 'state_id' => 3971],
                ['name' => 'Arp', 'state_id' => 3971],
                ['name' => 'Bullard', 'state_id' => 3971],
                ['name' => 'Flint', 'state_id' => 3971],
                ['name' => 'Lindale', 'state_id' => 3971],
                ['name' => 'Troup', 'state_id' => 3971],
                ['name' => 'Whitehouse', 'state_id' => 3971],
                ['name' => 'Winona', 'state_id' => 3971],
                ['name' => 'Glen Rose', 'state_id' => 3971],
                ['name' => 'Nemo', 'state_id' => 3971],
                ['name' => 'Rainbow', 'state_id' => 3971],
                ['name' => 'Delmita', 'state_id' => 3971],
                ['name' => 'Falcon Heights', 'state_id' => 3971],
                ['name' => 'Garciasville', 'state_id' => 3971],
                ['name' => 'Grulla', 'state_id' => 3971],
                ['name' => 'Rio Grande City', 'state_id' => 3971],
                ['name' => 'Roma', 'state_id' => 3971],
                ['name' => 'Salineno', 'state_id' => 3971],
                ['name' => 'San Isidro', 'state_id' => 3971],
                ['name' => 'Santa Elena', 'state_id' => 3971],
                ['name' => 'Breckenridge', 'state_id' => 3971],
                ['name' => 'Caddo', 'state_id' => 3971],
                ['name' => 'Sterling City', 'state_id' => 3971],
                ['name' => 'Aspermont', 'state_id' => 3971],
                ['name' => 'Old Glory', 'state_id' => 3971],
                ['name' => 'Sonora', 'state_id' => 3971],
                ['name' => 'Happy', 'state_id' => 3971],
                ['name' => 'Kress', 'state_id' => 3971],
                ['name' => 'Tulia', 'state_id' => 3971],
                ['name' => 'Arlington', 'state_id' => 3971],
                ['name' => 'Bedford', 'state_id' => 3971],
                ['name' => 'Colleyville', 'state_id' => 3971],
                ['name' => 'Crowley', 'state_id' => 3971],
                ['name' => 'Euless', 'state_id' => 3971],
                ['name' => 'Grapevine', 'state_id' => 3971],
                ['name' => 'Haslet', 'state_id' => 3971],
                ['name' => 'Hurst', 'state_id' => 3971],
                ['name' => 'Kennedale', 'state_id' => 3971],
                ['name' => 'Mansfield', 'state_id' => 3971],
                ['name' => 'Southlake', 'state_id' => 3971],
                ['name' => 'Fort Worth', 'state_id' => 3971],
                ['name' => 'Haltom City', 'state_id' => 3971],
                ['name' => 'Naval Air Station Jrb', 'state_id' => 3971],
                ['name' => 'North Richland Hills', 'state_id' => 3971],
                ['name' => 'Keller', 'state_id' => 3971],
                ['name' => 'Buffalo Gap', 'state_id' => 3971],
                ['name' => 'Lawn', 'state_id' => 3971],
                ['name' => 'Merkel', 'state_id' => 3971],
                ['name' => 'Ovalo', 'state_id' => 3971],
                ['name' => 'Trent', 'state_id' => 3971],
                ['name' => 'Tuscola', 'state_id' => 3971],
                ['name' => 'Tye', 'state_id' => 3971],
                ['name' => 'Abilene', 'state_id' => 3971],
                ['name' => 'Dyess Afb', 'state_id' => 3971],
                ['name' => 'Dryden', 'state_id' => 3971],
                ['name' => 'Sanderson', 'state_id' => 3971],
                ['name' => 'Brownfield', 'state_id' => 3971],
                ['name' => 'Meadow', 'state_id' => 3971],
                ['name' => 'Wellman', 'state_id' => 3971],
                ['name' => 'Throckmorton', 'state_id' => 3971],
                ['name' => 'Woodson', 'state_id' => 3971],
                ['name' => 'Mount Pleasant', 'state_id' => 3971],
                ['name' => 'Winfield', 'state_id' => 3971],
                ['name' => 'Cookville', 'state_id' => 3971],
                ['name' => 'Veribest', 'state_id' => 3971],
                ['name' => 'San Angelo', 'state_id' => 3971],
                ['name' => 'Goodfellow Afb', 'state_id' => 3971],
                ['name' => 'Carlsbad', 'state_id' => 3971],
                ['name' => 'Christoval', 'state_id' => 3971],
                ['name' => 'Knickerbocker', 'state_id' => 3971],
                ['name' => 'Mereta', 'state_id' => 3971],
                ['name' => 'Vancourt', 'state_id' => 3971],
                ['name' => 'Wall', 'state_id' => 3971],
                ['name' => 'Water Valley', 'state_id' => 3971],
                ['name' => 'Austin', 'state_id' => 3971],
                ['name' => 'Del Valle', 'state_id' => 3971],
                ['name' => 'Leander', 'state_id' => 3971],
                ['name' => 'Mc Neil', 'state_id' => 3971],
                ['name' => 'Manchaca', 'state_id' => 3971],
                ['name' => 'Manor', 'state_id' => 3971],
                ['name' => 'Pflugerville', 'state_id' => 3971],
                ['name' => 'Spicewood', 'state_id' => 3971],
                ['name' => 'Centralia', 'state_id' => 3971],
                ['name' => 'Groveton', 'state_id' => 3971],
                ['name' => 'Pennington', 'state_id' => 3971],
                ['name' => 'Trinity', 'state_id' => 3971],
                ['name' => 'Woodlake', 'state_id' => 3971],
                ['name' => 'Apple Springs', 'state_id' => 3971],
                ['name' => 'Chester', 'state_id' => 3971],
                ['name' => 'Colmesneil', 'state_id' => 3971],
                ['name' => 'Doucette', 'state_id' => 3971],
                ['name' => 'Woodville', 'state_id' => 3971],
                ['name' => 'Fred', 'state_id' => 3971],
                ['name' => 'Hillister', 'state_id' => 3971],
                ['name' => 'Spurger', 'state_id' => 3971],
                ['name' => 'Warren', 'state_id' => 3971],
                ['name' => 'Diana', 'state_id' => 3971],
                ['name' => 'Gilmer', 'state_id' => 3971],
                ['name' => 'Ore City', 'state_id' => 3971],
                ['name' => 'Big Sandy', 'state_id' => 3971],
                ['name' => 'Mc Camey', 'state_id' => 3971],
                ['name' => 'Midkiff', 'state_id' => 3971],
                ['name' => 'Rankin', 'state_id' => 3971],
                ['name' => 'Uvalde', 'state_id' => 3971],
                ['name' => 'Concan', 'state_id' => 3971],
                ['name' => 'Knippa', 'state_id' => 3971],
                ['name' => 'Sabinal', 'state_id' => 3971],
                ['name' => 'Utopia', 'state_id' => 3971],
                ['name' => 'Comstock', 'state_id' => 3971],
                ['name' => 'Del Rio', 'state_id' => 3971],
                ['name' => 'Laughlin Afb', 'state_id' => 3971],
                ['name' => 'Langtry', 'state_id' => 3971],
                ['name' => 'Canton', 'state_id' => 3971],
                ['name' => 'Edgewood', 'state_id' => 3971],
                ['name' => 'Fruitvale', 'state_id' => 3971],
                ['name' => 'Grand Saline', 'state_id' => 3971],
                ['name' => 'Wills Point', 'state_id' => 3971],
                ['name' => 'Ben Wheeler', 'state_id' => 3971],
                ['name' => 'Van', 'state_id' => 3971],
                ['name' => 'Victoria', 'state_id' => 3971],
                ['name' => 'Bloomington', 'state_id' => 3971],
                ['name' => 'Inez', 'state_id' => 3971],
                ['name' => 'Mcfaddin', 'state_id' => 3971],
                ['name' => 'Nursery', 'state_id' => 3971],
                ['name' => 'Placedo', 'state_id' => 3971],
                ['name' => 'Telferner', 'state_id' => 3971],
                ['name' => 'Huntsville', 'state_id' => 3971],
                ['name' => 'Dodge', 'state_id' => 3971],
                ['name' => 'New Waverly', 'state_id' => 3971],
                ['name' => 'Riverside', 'state_id' => 3971],
                ['name' => 'Brookshire', 'state_id' => 3971],
                ['name' => 'Hempstead', 'state_id' => 3971],
                ['name' => 'Prairie View', 'state_id' => 3971],
                ['name' => 'Pattison', 'state_id' => 3971],
                ['name' => 'Waller', 'state_id' => 3971],
                ['name' => 'Barstow', 'state_id' => 3971],
                ['name' => 'Grandfalls', 'state_id' => 3971],
                ['name' => 'Monahans', 'state_id' => 3971],
                ['name' => 'Pyote', 'state_id' => 3971],
                ['name' => 'Wickett', 'state_id' => 3971],
                ['name' => 'Chappell Hill', 'state_id' => 3971],
                ['name' => 'Brenham', 'state_id' => 3971],
                ['name' => 'Burton', 'state_id' => 3971],
                ['name' => 'Washington', 'state_id' => 3971],
                ['name' => 'Laredo', 'state_id' => 3971],
                ['name' => 'Bruni', 'state_id' => 3971],
                ['name' => 'Mirando City', 'state_id' => 3971],
                ['name' => 'Oilton', 'state_id' => 3971],
                ['name' => 'Boling', 'state_id' => 3971],
                ['name' => 'Danevang', 'state_id' => 3971],
                ['name' => 'East Bernard', 'state_id' => 3971],
                ['name' => 'Egypt', 'state_id' => 3971],
                ['name' => 'El Campo', 'state_id' => 3971],
                ['name' => 'Glen Flora', 'state_id' => 3971],
                ['name' => 'Hungerford', 'state_id' => 3971],
                ['name' => 'Lane City', 'state_id' => 3971],
                ['name' => 'Lissie', 'state_id' => 3971],
                ['name' => 'Louise', 'state_id' => 3971],
                ['name' => 'Pierce', 'state_id' => 3971],
                ['name' => 'Wharton', 'state_id' => 3971],
                ['name' => 'Allison', 'state_id' => 3971],
                ['name' => 'Briscoe', 'state_id' => 3971],
                ['name' => 'Mobeetie', 'state_id' => 3971],
                ['name' => 'Shamrock', 'state_id' => 3971],
                ['name' => 'Wheeler', 'state_id' => 3971],
                ['name' => 'Wichita Falls', 'state_id' => 3971],
                ['name' => 'Sheppard Afb', 'state_id' => 3971],
                ['name' => 'Burkburnett', 'state_id' => 3971],
                ['name' => 'Electra', 'state_id' => 3971],
                ['name' => 'Iowa Park', 'state_id' => 3971],
                ['name' => 'Kamay', 'state_id' => 3971],
                ['name' => 'Harrold', 'state_id' => 3971],
                ['name' => 'Oklaunion', 'state_id' => 3971],
                ['name' => 'Vernon', 'state_id' => 3971],
                ['name' => 'Odell', 'state_id' => 3971],
                ['name' => 'Lasara', 'state_id' => 3971],
                ['name' => 'Lyford', 'state_id' => 3971],
                ['name' => 'Raymondville', 'state_id' => 3971],
                ['name' => 'San Perlita', 'state_id' => 3971],
                ['name' => 'Sebastian', 'state_id' => 3971],
                ['name' => 'Port Mansfield', 'state_id' => 3971],
                ['name' => 'Florence', 'state_id' => 3971],
                ['name' => 'Granger', 'state_id' => 3971],
                ['name' => 'Jarrell', 'state_id' => 3971],
                ['name' => 'Schwertner', 'state_id' => 3971],
                ['name' => 'Taylor', 'state_id' => 3971],
                ['name' => 'Thrall', 'state_id' => 3971],
                ['name' => 'Cedar Park', 'state_id' => 3971],
                ['name' => 'Coupland', 'state_id' => 3971],
                ['name' => 'Georgetown', 'state_id' => 3971],
                ['name' => 'Hutto', 'state_id' => 3971],
                ['name' => 'Liberty Hill', 'state_id' => 3971],
                ['name' => 'Round Rock', 'state_id' => 3971],
                ['name' => 'Walburg', 'state_id' => 3971],
                ['name' => 'Weir', 'state_id' => 3971],
                ['name' => 'Floresville', 'state_id' => 3971],
                ['name' => 'La Vernia', 'state_id' => 3971],
                ['name' => 'Pandora', 'state_id' => 3971],
                ['name' => 'Poth', 'state_id' => 3971],
                ['name' => 'Stockdale', 'state_id' => 3971],
                ['name' => 'Sutherland Springs', 'state_id' => 3971],
                ['name' => 'Kermit', 'state_id' => 3971],
                ['name' => 'Wink', 'state_id' => 3971],
                ['name' => 'Boyd', 'state_id' => 3971],
                ['name' => 'Newark', 'state_id' => 3971],
                ['name' => 'Paradise', 'state_id' => 3971],
                ['name' => 'Rhome', 'state_id' => 3971],
                ['name' => 'Alvord', 'state_id' => 3971],
                ['name' => 'Decatur', 'state_id' => 3971],
                ['name' => 'Greenwood', 'state_id' => 3971],
                ['name' => 'Slidell', 'state_id' => 3971],
                ['name' => 'Bridgeport', 'state_id' => 3971],
                ['name' => 'Chico', 'state_id' => 3971],
                ['name' => 'Golden', 'state_id' => 3971],
                ['name' => 'Winnsboro', 'state_id' => 3971],
                ['name' => 'Yantis', 'state_id' => 3971],
                ['name' => 'Hawkins', 'state_id' => 3971],
                ['name' => 'Mineola', 'state_id' => 3971],
                ['name' => 'Quitman', 'state_id' => 3971],
                ['name' => 'Denver City', 'state_id' => 3971],
                ['name' => 'Plains', 'state_id' => 3971],
                ['name' => 'Tokio', 'state_id' => 3971],
                ['name' => 'Newcastle', 'state_id' => 3971],
                ['name' => 'Olney', 'state_id' => 3971],
                ['name' => 'Graham', 'state_id' => 3971],
                ['name' => 'Loving', 'state_id' => 3971],
                ['name' => 'South Bend', 'state_id' => 3971],
                ['name' => 'San Ygnacio', 'state_id' => 3971],
                ['name' => 'Zapata', 'state_id' => 3971],
                ['name' => 'Lopeno', 'state_id' => 3971],
                ['name' => 'Batesville', 'state_id' => 3971],
                ['name' => 'Crystal City', 'state_id' => 3971],
                ['name' => 'La Pryor', 'state_id' => 3971]
            ]);
        }
    }
}
