<?php

use Illuminate\Database\Seeder;

class state29TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ND - North Dakota.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Hettinger', 'state_id' => 3959],
                ['name' => 'Reeder', 'state_id' => 3959],
                ['name' => 'Fingal', 'state_id' => 3959],
                ['name' => 'Kathryn', 'state_id' => 3959],
                ['name' => 'Nome', 'state_id' => 3959],
                ['name' => 'Oriska', 'state_id' => 3959],
                ['name' => 'Pillsbury', 'state_id' => 3959],
                ['name' => 'Valley City', 'state_id' => 3959],
                ['name' => 'Dazey', 'state_id' => 3959],
                ['name' => 'Litchville', 'state_id' => 3959],
                ['name' => 'Rogers', 'state_id' => 3959],
                ['name' => 'Sanborn', 'state_id' => 3959],
                ['name' => 'Wimbledon', 'state_id' => 3959],
                ['name' => 'Esmond', 'state_id' => 3959],
                ['name' => 'Fort Totten', 'state_id' => 3959],
                ['name' => 'Knox', 'state_id' => 3959],
                ['name' => 'Leeds', 'state_id' => 3959],
                ['name' => 'Maddock', 'state_id' => 3959],
                ['name' => 'Minnewaukan', 'state_id' => 3959],
                ['name' => 'Oberon', 'state_id' => 3959],
                ['name' => 'Saint Michael', 'state_id' => 3959],
                ['name' => 'Tokio', 'state_id' => 3959],
                ['name' => 'Warwick', 'state_id' => 3959],
                ['name' => 'York', 'state_id' => 3959],
                ['name' => 'Fairfield', 'state_id' => 3959],
                ['name' => 'Medora', 'state_id' => 3959],
                ['name' => 'Bottineau', 'state_id' => 3959],
                ['name' => 'Willow City', 'state_id' => 3959],
                ['name' => 'Antler', 'state_id' => 3959],
                ['name' => 'Kramer', 'state_id' => 3959],
                ['name' => 'Lansford', 'state_id' => 3959],
                ['name' => 'Maxbass', 'state_id' => 3959],
                ['name' => 'Newburg', 'state_id' => 3959],
                ['name' => 'Souris', 'state_id' => 3959],
                ['name' => 'Westhope', 'state_id' => 3959],
                ['name' => 'Bowman', 'state_id' => 3959],
                ['name' => 'Rhame', 'state_id' => 3959],
                ['name' => 'Scranton', 'state_id' => 3959],
                ['name' => 'Bowbells', 'state_id' => 3959],
                ['name' => 'Columbus', 'state_id' => 3959],
                ['name' => 'Flaxton', 'state_id' => 3959],
                ['name' => 'Lignite', 'state_id' => 3959],
                ['name' => 'Portal', 'state_id' => 3959],
                ['name' => 'Powers Lake', 'state_id' => 3959],
                ['name' => 'Regan', 'state_id' => 3959],
                ['name' => 'Wing', 'state_id' => 3959],
                ['name' => 'Bismarck', 'state_id' => 3959],
                ['name' => 'Baldwin', 'state_id' => 3959],
                ['name' => 'Driscoll', 'state_id' => 3959],
                ['name' => 'Menoken', 'state_id' => 3959],
                ['name' => 'Moffit', 'state_id' => 3959],
                ['name' => 'Sterling', 'state_id' => 3959],
                ['name' => 'Absaraka', 'state_id' => 3959],
                ['name' => 'Amenia', 'state_id' => 3959],
                ['name' => 'Argusville', 'state_id' => 3959],
                ['name' => 'Arthur', 'state_id' => 3959],
                ['name' => 'Ayr', 'state_id' => 3959],
                ['name' => 'Buffalo', 'state_id' => 3959],
                ['name' => 'Casselton', 'state_id' => 3959],
                ['name' => 'Davenport', 'state_id' => 3959],
                ['name' => 'Erie', 'state_id' => 3959],
                ['name' => 'Gardner', 'state_id' => 3959],
                ['name' => 'Grandin', 'state_id' => 3959],
                ['name' => 'Harwood', 'state_id' => 3959],
                ['name' => 'Horace', 'state_id' => 3959],
                ['name' => 'Hunter', 'state_id' => 3959],
                ['name' => 'Kindred', 'state_id' => 3959],
                ['name' => 'Leonard', 'state_id' => 3959],
                ['name' => 'Mapleton', 'state_id' => 3959],
                ['name' => 'Page', 'state_id' => 3959],
                ['name' => 'Tower City', 'state_id' => 3959],
                ['name' => 'West Fargo', 'state_id' => 3959],
                ['name' => 'Wheatland', 'state_id' => 3959],
                ['name' => 'Fargo', 'state_id' => 3959],
                ['name' => 'Hannah', 'state_id' => 3959],
                ['name' => 'Langdon', 'state_id' => 3959],
                ['name' => 'Maida', 'state_id' => 3959],
                ['name' => 'Milton', 'state_id' => 3959],
                ['name' => 'Osnabrock', 'state_id' => 3959],
                ['name' => 'Wales', 'state_id' => 3959],
                ['name' => 'Alsen', 'state_id' => 3959],
                ['name' => 'Calvin', 'state_id' => 3959],
                ['name' => 'Munich', 'state_id' => 3959],
                ['name' => 'Nekoma', 'state_id' => 3959],
                ['name' => 'Sarles', 'state_id' => 3959],
                ['name' => 'Ellendale', 'state_id' => 3959],
                ['name' => 'Forbes', 'state_id' => 3959],
                ['name' => 'Fullerton', 'state_id' => 3959],
                ['name' => 'Oakes', 'state_id' => 3959],
                ['name' => 'Crosby', 'state_id' => 3959],
                ['name' => 'Noonan', 'state_id' => 3959],
                ['name' => 'Ambrose', 'state_id' => 3959],
                ['name' => 'Fortuna', 'state_id' => 3959],
                ['name' => 'Dodge', 'state_id' => 3959],
                ['name' => 'Dunn Center', 'state_id' => 3959],
                ['name' => 'Halliday', 'state_id' => 3959],
                ['name' => 'Killdeer', 'state_id' => 3959],
                ['name' => 'Manning', 'state_id' => 3959],
                ['name' => 'Marshall', 'state_id' => 3959],
                ['name' => 'New Rockford', 'state_id' => 3959],
                ['name' => 'Sheyenne', 'state_id' => 3959],
                ['name' => 'Braddock', 'state_id' => 3959],
                ['name' => 'Hague', 'state_id' => 3959],
                ['name' => 'Hazelton', 'state_id' => 3959],
                ['name' => 'Kintyre', 'state_id' => 3959],
                ['name' => 'Linton', 'state_id' => 3959],
                ['name' => 'Strasburg', 'state_id' => 3959],
                ['name' => 'Carrington', 'state_id' => 3959],
                ['name' => 'Glenfield', 'state_id' => 3959],
                ['name' => 'Grace City', 'state_id' => 3959],
                ['name' => 'Mchenry', 'state_id' => 3959],
                ['name' => 'Beach', 'state_id' => 3959],
                ['name' => 'Golva', 'state_id' => 3959],
                ['name' => 'Sentinel Butte', 'state_id' => 3959],
                ['name' => 'Grand Forks', 'state_id' => 3959],
                ['name' => 'Grand Forks Afb', 'state_id' => 3959],
                ['name' => 'Arvilla', 'state_id' => 3959],
                ['name' => 'Emerado', 'state_id' => 3959],
                ['name' => 'Gilby', 'state_id' => 3959],
                ['name' => 'Inkster', 'state_id' => 3959],
                ['name' => 'Larimore', 'state_id' => 3959],
                ['name' => 'Manvel', 'state_id' => 3959],
                ['name' => 'Mekinock', 'state_id' => 3959],
                ['name' => 'Niagara', 'state_id' => 3959],
                ['name' => 'Northwood', 'state_id' => 3959],
                ['name' => 'Reynolds', 'state_id' => 3959],
                ['name' => 'Thompson', 'state_id' => 3959],
                ['name' => 'Carson', 'state_id' => 3959],
                ['name' => 'Elgin', 'state_id' => 3959],
                ['name' => 'New Leipzig', 'state_id' => 3959],
                ['name' => 'Raleigh', 'state_id' => 3959],
                ['name' => 'Shields', 'state_id' => 3959],
                ['name' => 'Binford', 'state_id' => 3959],
                ['name' => 'Cooperstown', 'state_id' => 3959],
                ['name' => 'Hannaford', 'state_id' => 3959],
                ['name' => 'Jessie', 'state_id' => 3959],
                ['name' => 'Sutton', 'state_id' => 3959],
                ['name' => 'Mott', 'state_id' => 3959],
                ['name' => 'New England', 'state_id' => 3959],
                ['name' => 'Regent', 'state_id' => 3959],
                ['name' => 'Dawson', 'state_id' => 3959],
                ['name' => 'Pettibone', 'state_id' => 3959],
                ['name' => 'Robinson', 'state_id' => 3959],
                ['name' => 'Steele', 'state_id' => 3959],
                ['name' => 'Tappen', 'state_id' => 3959],
                ['name' => 'Tuttle', 'state_id' => 3959],
                ['name' => 'Berlin', 'state_id' => 3959],
                ['name' => 'Dickey', 'state_id' => 3959],
                ['name' => 'Edgeley', 'state_id' => 3959],
                ['name' => 'Jud', 'state_id' => 3959],
                ['name' => 'Kulm', 'state_id' => 3959],
                ['name' => 'Lamoure', 'state_id' => 3959],
                ['name' => 'Marion', 'state_id' => 3959],
                ['name' => 'Verona', 'state_id' => 3959],
                ['name' => 'Fredonia', 'state_id' => 3959],
                ['name' => 'Gackle', 'state_id' => 3959],
                ['name' => 'Napoleon', 'state_id' => 3959],
                ['name' => 'Anamoose', 'state_id' => 3959],
                ['name' => 'Balfour', 'state_id' => 3959],
                ['name' => 'Bantry', 'state_id' => 3959],
                ['name' => 'Deering', 'state_id' => 3959],
                ['name' => 'Drake', 'state_id' => 3959],
                ['name' => 'Granville', 'state_id' => 3959],
                ['name' => 'Karlsruhe', 'state_id' => 3959],
                ['name' => 'Norwich', 'state_id' => 3959],
                ['name' => 'Towner', 'state_id' => 3959],
                ['name' => 'Upham', 'state_id' => 3959],
                ['name' => 'Velva', 'state_id' => 3959],
                ['name' => 'Voltaire', 'state_id' => 3959],
                ['name' => 'Ashley', 'state_id' => 3959],
                ['name' => 'Lehr', 'state_id' => 3959],
                ['name' => 'Wishek', 'state_id' => 3959],
                ['name' => 'Zeeland', 'state_id' => 3959],
                ['name' => 'Grassy Butte', 'state_id' => 3959],
                ['name' => 'Mandaree', 'state_id' => 3959],
                ['name' => 'Alexander', 'state_id' => 3959],
                ['name' => 'Arnegard', 'state_id' => 3959],
                ['name' => 'Cartwright', 'state_id' => 3959],
                ['name' => 'Keene', 'state_id' => 3959],
                ['name' => 'Watford City', 'state_id' => 3959],
                ['name' => 'Coleharbor', 'state_id' => 3959],
                ['name' => 'Garrison', 'state_id' => 3959],
                ['name' => 'Mercer', 'state_id' => 3959],
                ['name' => 'Riverdale', 'state_id' => 3959],
                ['name' => 'Turtle Lake', 'state_id' => 3959],
                ['name' => 'Underwood', 'state_id' => 3959],
                ['name' => 'Washburn', 'state_id' => 3959],
                ['name' => 'Wilton', 'state_id' => 3959],
                ['name' => 'Benedict', 'state_id' => 3959],
                ['name' => 'Butte', 'state_id' => 3959],
                ['name' => 'Max', 'state_id' => 3959],
                ['name' => 'Roseglen', 'state_id' => 3959],
                ['name' => 'Ruso', 'state_id' => 3959],
                ['name' => 'Beulah', 'state_id' => 3959],
                ['name' => 'Golden Valley', 'state_id' => 3959],
                ['name' => 'Hazen', 'state_id' => 3959],
                ['name' => 'Stanton', 'state_id' => 3959],
                ['name' => 'Zap', 'state_id' => 3959],
                ['name' => 'Almont', 'state_id' => 3959],
                ['name' => 'Flasher', 'state_id' => 3959],
                ['name' => 'Mandan', 'state_id' => 3959],
                ['name' => 'New Salem', 'state_id' => 3959],
                ['name' => 'Saint Anthony', 'state_id' => 3959],
                ['name' => 'Glen Ullin', 'state_id' => 3959],
                ['name' => 'Hebron', 'state_id' => 3959],
                ['name' => 'New Town', 'state_id' => 3959],
                ['name' => 'Palermo', 'state_id' => 3959],
                ['name' => 'Parshall', 'state_id' => 3959],
                ['name' => 'Plaza', 'state_id' => 3959],
                ['name' => 'Ross', 'state_id' => 3959],
                ['name' => 'Stanley', 'state_id' => 3959],
                ['name' => 'White Earth', 'state_id' => 3959],
                ['name' => 'Aneta', 'state_id' => 3959],
                ['name' => 'Dahlen', 'state_id' => 3959],
                ['name' => 'Mcville', 'state_id' => 3959],
                ['name' => 'Michigan', 'state_id' => 3959],
                ['name' => 'Petersburg', 'state_id' => 3959],
                ['name' => 'Lakota', 'state_id' => 3959],
                ['name' => 'Pekin', 'state_id' => 3959],
                ['name' => 'Tolna', 'state_id' => 3959],
                ['name' => 'Center', 'state_id' => 3959],
                ['name' => 'Bathgate', 'state_id' => 3959],
                ['name' => 'Cavalier', 'state_id' => 3959],
                ['name' => 'Crystal', 'state_id' => 3959],
                ['name' => 'Drayton', 'state_id' => 3959],
                ['name' => 'Glasston', 'state_id' => 3959],
                ['name' => 'Hamilton', 'state_id' => 3959],
                ['name' => 'Hensel', 'state_id' => 3959],
                ['name' => 'Mountain', 'state_id' => 3959],
                ['name' => 'Neche', 'state_id' => 3959],
                ['name' => 'Pembina', 'state_id' => 3959],
                ['name' => 'Saint Thomas', 'state_id' => 3959],
                ['name' => 'Walhalla', 'state_id' => 3959],
                ['name' => 'Balta', 'state_id' => 3959],
                ['name' => 'Rugby', 'state_id' => 3959],
                ['name' => 'Wolford', 'state_id' => 3959],
                ['name' => 'Devils Lake', 'state_id' => 3959],
                ['name' => 'Brocket', 'state_id' => 3959],
                ['name' => 'Churchs Ferry', 'state_id' => 3959],
                ['name' => 'Crary', 'state_id' => 3959],
                ['name' => 'Edmore', 'state_id' => 3959],
                ['name' => 'Hampden', 'state_id' => 3959],
                ['name' => 'Lawton', 'state_id' => 3959],
                ['name' => 'Penn', 'state_id' => 3959],
                ['name' => 'Starkweather', 'state_id' => 3959],
                ['name' => 'Webster', 'state_id' => 3959],
                ['name' => 'Enderlin', 'state_id' => 3959],
                ['name' => 'Fort Ransom', 'state_id' => 3959],
                ['name' => 'Lisbon', 'state_id' => 3959],
                ['name' => 'Mcleod', 'state_id' => 3959],
                ['name' => 'Sheldon', 'state_id' => 3959],
                ['name' => 'Glenburn', 'state_id' => 3959],
                ['name' => 'Mohall', 'state_id' => 3959],
                ['name' => 'Sherwood', 'state_id' => 3959],
                ['name' => 'Tolley', 'state_id' => 3959],
                ['name' => 'Abercrombie', 'state_id' => 3959],
                ['name' => 'Barney', 'state_id' => 3959],
                ['name' => 'Christine', 'state_id' => 3959],
                ['name' => 'Colfax', 'state_id' => 3959],
                ['name' => 'Fairmount', 'state_id' => 3959],
                ['name' => 'Hankinson', 'state_id' => 3959],
                ['name' => 'Lidgerwood', 'state_id' => 3959],
                ['name' => 'Mantador', 'state_id' => 3959],
                ['name' => 'Mooreton', 'state_id' => 3959],
                ['name' => 'Wahpeton', 'state_id' => 3959],
                ['name' => 'Walcott', 'state_id' => 3959],
                ['name' => 'Wyndmere', 'state_id' => 3959],
                ['name' => 'Agate', 'state_id' => 3959],
                ['name' => 'Belcourt', 'state_id' => 3959],
                ['name' => 'Dunseith', 'state_id' => 3959],
                ['name' => 'Mylo', 'state_id' => 3959],
                ['name' => 'Rolette', 'state_id' => 3959],
                ['name' => 'Rolla', 'state_id' => 3959],
                ['name' => 'Saint John', 'state_id' => 3959],
                ['name' => 'Cayuga', 'state_id' => 3959],
                ['name' => 'Cogswell', 'state_id' => 3959],
                ['name' => 'Forman', 'state_id' => 3959],
                ['name' => 'Gwinner', 'state_id' => 3959],
                ['name' => 'Havana', 'state_id' => 3959],
                ['name' => 'Milnor', 'state_id' => 3959],
                ['name' => 'Rutland', 'state_id' => 3959],
                ['name' => 'Stirum', 'state_id' => 3959],
                ['name' => 'Denhoff', 'state_id' => 3959],
                ['name' => 'Goodrich', 'state_id' => 3959],
                ['name' => 'Mcclusky', 'state_id' => 3959],
                ['name' => 'Martin', 'state_id' => 3959],
                ['name' => 'Cannon Ball', 'state_id' => 3959],
                ['name' => 'Fort Yates', 'state_id' => 3959],
                ['name' => 'Selfridge', 'state_id' => 3959],
                ['name' => 'Solen', 'state_id' => 3959],
                ['name' => 'Amidon', 'state_id' => 3959],
                ['name' => 'Marmarth', 'state_id' => 3959],
                ['name' => 'Dickinson', 'state_id' => 3959],
                ['name' => 'Belfield', 'state_id' => 3959],
                ['name' => 'Gladstone', 'state_id' => 3959],
                ['name' => 'Lefor', 'state_id' => 3959],
                ['name' => 'Richardton', 'state_id' => 3959],
                ['name' => 'South Heart', 'state_id' => 3959],
                ['name' => 'Taylor', 'state_id' => 3959],
                ['name' => 'Hope', 'state_id' => 3959],
                ['name' => 'Luverne', 'state_id' => 3959],
                ['name' => 'Finley', 'state_id' => 3959],
                ['name' => 'Sharon', 'state_id' => 3959],
                ['name' => 'Jamestown', 'state_id' => 3959],
                ['name' => 'Buchanan', 'state_id' => 3959],
                ['name' => 'Cleveland', 'state_id' => 3959],
                ['name' => 'Courtenay', 'state_id' => 3959],
                ['name' => 'Kensal', 'state_id' => 3959],
                ['name' => 'Medina', 'state_id' => 3959],
                ['name' => 'Montpelier', 'state_id' => 3959],
                ['name' => 'Pingree', 'state_id' => 3959],
                ['name' => 'Spiritwood', 'state_id' => 3959],
                ['name' => 'Streeter', 'state_id' => 3959],
                ['name' => 'Woodworth', 'state_id' => 3959],
                ['name' => 'Ypsilanti', 'state_id' => 3959],
                ['name' => 'Bisbee', 'state_id' => 3959],
                ['name' => 'Cando', 'state_id' => 3959],
                ['name' => 'Egeland', 'state_id' => 3959],
                ['name' => 'Hansboro', 'state_id' => 3959],
                ['name' => 'Perth', 'state_id' => 3959],
                ['name' => 'Rocklake', 'state_id' => 3959],
                ['name' => 'Blanchard', 'state_id' => 3959],
                ['name' => 'Clifford', 'state_id' => 3959],
                ['name' => 'Galesburg', 'state_id' => 3959],
                ['name' => 'Hillsboro', 'state_id' => 3959],
                ['name' => 'Buxton', 'state_id' => 3959],
                ['name' => 'Caledonia', 'state_id' => 3959],
                ['name' => 'Cummings', 'state_id' => 3959],
                ['name' => 'Hatton', 'state_id' => 3959],
                ['name' => 'Mayville', 'state_id' => 3959],
                ['name' => 'Portland', 'state_id' => 3959],
                ['name' => 'Adams', 'state_id' => 3959],
                ['name' => 'Edinburg', 'state_id' => 3959],
                ['name' => 'Fairdale', 'state_id' => 3959],
                ['name' => 'Fordville', 'state_id' => 3959],
                ['name' => 'Forest River', 'state_id' => 3959],
                ['name' => 'Grafton', 'state_id' => 3959],
                ['name' => 'Hoople', 'state_id' => 3959],
                ['name' => 'Lankin', 'state_id' => 3959],
                ['name' => 'Minto', 'state_id' => 3959],
                ['name' => 'Park River', 'state_id' => 3959],
                ['name' => 'Pisek', 'state_id' => 3959],
                ['name' => 'Minot', 'state_id' => 3959],
                ['name' => 'Minot Afb', 'state_id' => 3959],
                ['name' => 'Berthold', 'state_id' => 3959],
                ['name' => 'Burlington', 'state_id' => 3959],
                ['name' => 'Carpio', 'state_id' => 3959],
                ['name' => 'Des Lacs', 'state_id' => 3959],
                ['name' => 'Donnybrook', 'state_id' => 3959],
                ['name' => 'Douglas', 'state_id' => 3959],
                ['name' => 'Kenmare', 'state_id' => 3959],
                ['name' => 'Makoti', 'state_id' => 3959],
                ['name' => 'Ryder', 'state_id' => 3959],
                ['name' => 'Sawyer', 'state_id' => 3959],
                ['name' => 'Surrey', 'state_id' => 3959],
                ['name' => 'Harvey', 'state_id' => 3959],
                ['name' => 'Bowdon', 'state_id' => 3959],
                ['name' => 'Cathay', 'state_id' => 3959],
                ['name' => 'Chaseley', 'state_id' => 3959],
                ['name' => 'Fessenden', 'state_id' => 3959],
                ['name' => 'Hurdsfield', 'state_id' => 3959],
                ['name' => 'Sykeston', 'state_id' => 3959],
                ['name' => 'Mcgregor', 'state_id' => 3959],
                ['name' => 'Wildrose', 'state_id' => 3959],
                ['name' => 'Williston', 'state_id' => 3959],
                ['name' => 'Alamo', 'state_id' => 3959],
                ['name' => 'Epping', 'state_id' => 3959],
                ['name' => 'Grenora', 'state_id' => 3959],
                ['name' => 'Ray', 'state_id' => 3959],
                ['name' => 'Tioga', 'state_id' => 3959],
                ['name' => 'Trenton', 'state_id' => 3959],
                ['name' => 'Zahl', 'state_id' => 3959]
            ]);
        }
    }
}
