<?php

use Illuminate\Database\Seeder;

class state7TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AR - Arkansas.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Botsford', 'state_id' => 3928],
                ['name' => 'Hawleyville', 'state_id' => 3928],
                ['name' => 'Monroe', 'state_id' => 3928],
                ['name' => 'Newtown', 'state_id' => 3928],
                ['name' => 'Sandy Hook', 'state_id' => 3928],
                ['name' => 'Shelton', 'state_id' => 3928],
                ['name' => 'Stevenson', 'state_id' => 3928],
                ['name' => 'Bridgeport', 'state_id' => 3928],
                ['name' => 'Trumbull', 'state_id' => 3928],
                ['name' => 'Easton', 'state_id' => 3928],
                ['name' => 'Stratford', 'state_id' => 3928],
                ['name' => 'Sherman', 'state_id' => 3928],
                ['name' => 'Bethel', 'state_id' => 3928],
                ['name' => 'Brookfield', 'state_id' => 3928],
                ['name' => 'Cos Cob', 'state_id' => 3928],
                ['name' => 'Danbury', 'state_id' => 3928],
                ['name' => 'New Fairfield', 'state_id' => 3928],
                ['name' => 'Darien', 'state_id' => 3928],
                ['name' => 'Fairfield', 'state_id' => 3928],
                ['name' => 'Georgetown', 'state_id' => 3928],
                ['name' => 'Greenwich', 'state_id' => 3928],
                ['name' => 'Greens Farms', 'state_id' => 3928],
                ['name' => 'New Canaan', 'state_id' => 3928],
                ['name' => 'Norwalk', 'state_id' => 3928],
                ['name' => 'Old Greenwich', 'state_id' => 3928],
                ['name' => 'Redding Center', 'state_id' => 3928],
                ['name' => 'Redding Ridge', 'state_id' => 3928],
                ['name' => 'Ridgefield', 'state_id' => 3928],
                ['name' => 'Riverside', 'state_id' => 3928],
                ['name' => 'Westport', 'state_id' => 3928],
                ['name' => 'Weston', 'state_id' => 3928],
                ['name' => 'Southport', 'state_id' => 3928],
                ['name' => 'Redding', 'state_id' => 3928],
                ['name' => 'Wilton', 'state_id' => 3928],
                ['name' => 'Stamford', 'state_id' => 3928],
                ['name' => 'Avon', 'state_id' => 3928],
                ['name' => 'Bloomfield', 'state_id' => 3928],
                ['name' => 'Windsor', 'state_id' => 3928],
                ['name' => 'Bristol', 'state_id' => 3928],
                ['name' => 'Burlington', 'state_id' => 3928],
                ['name' => 'Broad Brook', 'state_id' => 3928],
                ['name' => 'Canton', 'state_id' => 3928],
                ['name' => 'Canton Center', 'state_id' => 3928],
                ['name' => 'Collinsville', 'state_id' => 3928],
                ['name' => 'East Berlin', 'state_id' => 3928],
                ['name' => 'East Glastonbury', 'state_id' => 3928],
                ['name' => 'East Granby', 'state_id' => 3928],
                ['name' => 'East Hartland', 'state_id' => 3928],
                ['name' => 'East Windsor Hill', 'state_id' => 3928],
                ['name' => 'Farmington', 'state_id' => 3928],
                ['name' => 'Glastonbury', 'state_id' => 3928],
                ['name' => 'Granby', 'state_id' => 3928],
                ['name' => 'Berlin', 'state_id' => 3928],
                ['name' => 'Manchester', 'state_id' => 3928],
                ['name' => 'New Britain', 'state_id' => 3928],
                ['name' => 'North Canton', 'state_id' => 3928],
                ['name' => 'North Granby', 'state_id' => 3928],
                ['name' => 'Plainville', 'state_id' => 3928],
                ['name' => 'Poquonock', 'state_id' => 3928],
                ['name' => 'Rocky Hill', 'state_id' => 3928],
                ['name' => 'Simsbury', 'state_id' => 3928],
                ['name' => 'South Glastonbury', 'state_id' => 3928],
                ['name' => 'South Windsor', 'state_id' => 3928],
                ['name' => 'Suffield', 'state_id' => 3928],
                ['name' => 'Tariffville', 'state_id' => 3928],
                ['name' => 'Enfield', 'state_id' => 3928],
                ['name' => 'Unionville', 'state_id' => 3928],
                ['name' => 'East Windsor', 'state_id' => 3928],
                ['name' => 'Weatogue', 'state_id' => 3928],
                ['name' => 'West Granby', 'state_id' => 3928],
                ['name' => 'West Hartland', 'state_id' => 3928],
                ['name' => 'West Simsbury', 'state_id' => 3928],
                ['name' => 'West Suffield', 'state_id' => 3928],
                ['name' => 'Windsor Locks', 'state_id' => 3928],
                ['name' => 'Hartford', 'state_id' => 3928],
                ['name' => 'West Hartford', 'state_id' => 3928],
                ['name' => 'East Hartford', 'state_id' => 3928],
                ['name' => 'Wethersfield', 'state_id' => 3928],
                ['name' => 'Newington', 'state_id' => 3928],
                ['name' => 'Marion', 'state_id' => 3928],
                ['name' => 'Marlborough', 'state_id' => 3928],
                ['name' => 'Milldale', 'state_id' => 3928],
                ['name' => 'Plantsville', 'state_id' => 3928],
                ['name' => 'Southington', 'state_id' => 3928],
                ['name' => 'Canaan', 'state_id' => 3928],
                ['name' => 'Colebrook', 'state_id' => 3928],
                ['name' => 'East Canaan', 'state_id' => 3928],
                ['name' => 'Falls Village', 'state_id' => 3928],
                ['name' => 'Lakeville', 'state_id' => 3928],
                ['name' => 'New Hartford', 'state_id' => 3928],
                ['name' => 'Norfolk', 'state_id' => 3928],
                ['name' => 'Pine Meadow', 'state_id' => 3928],
                ['name' => 'Barkhamsted', 'state_id' => 3928],
                ['name' => 'Riverton', 'state_id' => 3928],
                ['name' => 'Salisbury', 'state_id' => 3928],
                ['name' => 'Sharon', 'state_id' => 3928],
                ['name' => 'Taconic', 'state_id' => 3928],
                ['name' => 'Winchester Center', 'state_id' => 3928],
                ['name' => 'Winsted', 'state_id' => 3928],
                ['name' => 'Bantam', 'state_id' => 3928],
                ['name' => 'Bethlehem', 'state_id' => 3928],
                ['name' => 'Bridgewater', 'state_id' => 3928],
                ['name' => 'Cornwall', 'state_id' => 3928],
                ['name' => 'Cornwall Bridge', 'state_id' => 3928],
                ['name' => 'Gaylordsville', 'state_id' => 3928],
                ['name' => 'Goshen', 'state_id' => 3928],
                ['name' => 'Kent', 'state_id' => 3928],
                ['name' => 'Lakeside', 'state_id' => 3928],
                ['name' => 'Litchfield', 'state_id' => 3928],
                ['name' => 'Morris', 'state_id' => 3928],
                ['name' => 'New Milford', 'state_id' => 3928],
                ['name' => 'New Preston Marble Dale', 'state_id' => 3928],
                ['name' => 'Northfield', 'state_id' => 3928],
                ['name' => 'Oakville', 'state_id' => 3928],
                ['name' => 'Pequabuck', 'state_id' => 3928],
                ['name' => 'Plymouth', 'state_id' => 3928],
                ['name' => 'Roxbury', 'state_id' => 3928],
                ['name' => 'South Kent', 'state_id' => 3928],
                ['name' => 'Terryville', 'state_id' => 3928],
                ['name' => 'Thomaston', 'state_id' => 3928],
                ['name' => 'Torrington', 'state_id' => 3928],
                ['name' => 'Harwinton', 'state_id' => 3928],
                ['name' => 'Washington', 'state_id' => 3928],
                ['name' => 'Washington Depot', 'state_id' => 3928],
                ['name' => 'Watertown', 'state_id' => 3928],
                ['name' => 'West Cornwall', 'state_id' => 3928],
                ['name' => 'Woodbury', 'state_id' => 3928],
                ['name' => 'Centerbrook', 'state_id' => 3928],
                ['name' => 'Chester', 'state_id' => 3928],
                ['name' => 'Clinton', 'state_id' => 3928],
                ['name' => 'Cobalt', 'state_id' => 3928],
                ['name' => 'Cromwell', 'state_id' => 3928],
                ['name' => 'Deep River', 'state_id' => 3928],
                ['name' => 'Killingworth', 'state_id' => 3928],
                ['name' => 'Durham', 'state_id' => 3928],
                ['name' => 'East Haddam', 'state_id' => 3928],
                ['name' => 'East Hampton', 'state_id' => 3928],
                ['name' => 'Essex', 'state_id' => 3928],
                ['name' => 'Haddam', 'state_id' => 3928],
                ['name' => 'Higganum', 'state_id' => 3928],
                ['name' => 'Ivoryton', 'state_id' => 3928],
                ['name' => 'Middlefield', 'state_id' => 3928],
                ['name' => 'Middle Haddam', 'state_id' => 3928],
                ['name' => 'Middletown', 'state_id' => 3928],
                ['name' => 'Moodus', 'state_id' => 3928],
                ['name' => 'Old Saybrook', 'state_id' => 3928],
                ['name' => 'Portland', 'state_id' => 3928],
                ['name' => 'Rockfall', 'state_id' => 3928],
                ['name' => 'Westbrook', 'state_id' => 3928],
                ['name' => 'Ansonia', 'state_id' => 3928],
                ['name' => 'Beacon Falls', 'state_id' => 3928],
                ['name' => 'Branford', 'state_id' => 3928],
                ['name' => 'Cheshire', 'state_id' => 3928],
                ['name' => 'Derby', 'state_id' => 3928],
                ['name' => 'Guilford', 'state_id' => 3928],
                ['name' => 'Madison', 'state_id' => 3928],
                ['name' => 'Meriden', 'state_id' => 3928],
                ['name' => 'Milford', 'state_id' => 3928],
                ['name' => 'North Branford', 'state_id' => 3928],
                ['name' => 'Northford', 'state_id' => 3928],
                ['name' => 'North Haven', 'state_id' => 3928],
                ['name' => 'Orange', 'state_id' => 3928],
                ['name' => 'Oxford', 'state_id' => 3928],
                ['name' => 'Seymour', 'state_id' => 3928],
                ['name' => 'South Britain', 'state_id' => 3928],
                ['name' => 'Southbury', 'state_id' => 3928],
                ['name' => 'Wallingford', 'state_id' => 3928],
                ['name' => 'New Haven', 'state_id' => 3928],
                ['name' => 'Hamden', 'state_id' => 3928],
                ['name' => 'West Haven', 'state_id' => 3928],
                ['name' => 'Bethany', 'state_id' => 3928],
                ['name' => 'Waterbury', 'state_id' => 3928],
                ['name' => 'Prospect', 'state_id' => 3928],
                ['name' => 'Wolcott', 'state_id' => 3928],
                ['name' => 'Middlebury', 'state_id' => 3928],
                ['name' => 'Naugatuck', 'state_id' => 3928],
                ['name' => 'Lebanon', 'state_id' => 3928],
                ['name' => 'North Franklin', 'state_id' => 3928],
                ['name' => 'New London', 'state_id' => 3928],
                ['name' => 'Baltic', 'state_id' => 3928],
                ['name' => 'East Lyme', 'state_id' => 3928],
                ['name' => 'Bozrah', 'state_id' => 3928],
                ['name' => 'Gales Ferry', 'state_id' => 3928],
                ['name' => 'Gilman', 'state_id' => 3928],
                ['name' => 'Mashantucket', 'state_id' => 3928],
                ['name' => 'Ledyard', 'state_id' => 3928],
                ['name' => 'Groton', 'state_id' => 3928],
                ['name' => 'Hanover', 'state_id' => 3928],
                ['name' => 'Jewett City', 'state_id' => 3928],
                ['name' => 'Montville', 'state_id' => 3928],
                ['name' => 'Mystic', 'state_id' => 3928],
                ['name' => 'Niantic', 'state_id' => 3928],
                ['name' => 'North Stonington', 'state_id' => 3928],
                ['name' => 'Norwich', 'state_id' => 3928],
                ['name' => 'Preston', 'state_id' => 3928],
                ['name' => 'Oakdale', 'state_id' => 3928],
                ['name' => 'Old Lyme', 'state_id' => 3928],
                ['name' => 'Old Mystic', 'state_id' => 3928],
                ['name' => 'Quaker Hill', 'state_id' => 3928],
                ['name' => 'South Lyme', 'state_id' => 3928],
                ['name' => 'Stonington', 'state_id' => 3928],
                ['name' => 'Pawcatuck', 'state_id' => 3928],
                ['name' => 'Taftville', 'state_id' => 3928],
                ['name' => 'Uncasville', 'state_id' => 3928],
                ['name' => 'Versailles', 'state_id' => 3928],
                ['name' => 'Voluntown', 'state_id' => 3928],
                ['name' => 'Waterford', 'state_id' => 3928],
                ['name' => 'West Mystic', 'state_id' => 3928],
                ['name' => 'Yantic', 'state_id' => 3928],
                ['name' => 'Colchester', 'state_id' => 3928],
                ['name' => 'Salem', 'state_id' => 3928],
                ['name' => 'Hadlyme', 'state_id' => 3928],
                ['name' => 'North Westchester', 'state_id' => 3928],
                ['name' => 'Ellington', 'state_id' => 3928],
                ['name' => 'Bolton', 'state_id' => 3928],
                ['name' => 'Vernon Rockville', 'state_id' => 3928],
                ['name' => 'Somers', 'state_id' => 3928],
                ['name' => 'Somersville', 'state_id' => 3928],
                ['name' => 'Stafford', 'state_id' => 3928],
                ['name' => 'Stafford Springs', 'state_id' => 3928],
                ['name' => 'Staffordville', 'state_id' => 3928],
                ['name' => 'Tolland', 'state_id' => 3928],
                ['name' => 'Amston', 'state_id' => 3928],
                ['name' => 'Andover', 'state_id' => 3928],
                ['name' => 'Columbia', 'state_id' => 3928],
                ['name' => 'Coventry', 'state_id' => 3928],
                ['name' => 'Hebron', 'state_id' => 3928],
                ['name' => 'Mansfield Center', 'state_id' => 3928],
                ['name' => 'Mansfield Depot', 'state_id' => 3928],
                ['name' => 'South Willington', 'state_id' => 3928],
                ['name' => 'Storrs Mansfield', 'state_id' => 3928],
                ['name' => 'Willington', 'state_id' => 3928],
                ['name' => 'Willimantic', 'state_id' => 3928],
                ['name' => 'Abington', 'state_id' => 3928],
                ['name' => 'Ballouville', 'state_id' => 3928],
                ['name' => 'Brooklyn', 'state_id' => 3928],
                ['name' => 'Chaplin', 'state_id' => 3928],
                ['name' => 'Danielson', 'state_id' => 3928],
                ['name' => 'Dayville', 'state_id' => 3928],
                ['name' => 'Eastford', 'state_id' => 3928],
                ['name' => 'East Killingly', 'state_id' => 3928],
                ['name' => 'East Woodstock', 'state_id' => 3928],
                ['name' => 'Fabyan', 'state_id' => 3928],
                ['name' => 'Grosvenor Dale', 'state_id' => 3928],
                ['name' => 'Hampton', 'state_id' => 3928],
                ['name' => 'North Grosvenordale', 'state_id' => 3928],
                ['name' => 'North Windham', 'state_id' => 3928],
                ['name' => 'Pomfret', 'state_id' => 3928],
                ['name' => 'Pomfret Center', 'state_id' => 3928],
                ['name' => 'Putnam', 'state_id' => 3928],
                ['name' => 'Quinebaug', 'state_id' => 3928],
                ['name' => 'Rogers', 'state_id' => 3928],
                ['name' => 'Scotland', 'state_id' => 3928],
                ['name' => 'South Windham', 'state_id' => 3928],
                ['name' => 'South Woodstock', 'state_id' => 3928],
                ['name' => 'Thompson', 'state_id' => 3928],
                ['name' => 'Ashford', 'state_id' => 3928],
                ['name' => 'Windham', 'state_id' => 3928],
                ['name' => 'Woodstock', 'state_id' => 3928],
                ['name' => 'Woodstock Valley', 'state_id' => 3928],
                ['name' => 'Canterbury', 'state_id' => 3928],
                ['name' => 'Central Village', 'state_id' => 3928],
                ['name' => 'Moosup', 'state_id' => 3928],
                ['name' => 'Oneco', 'state_id' => 3928],
                ['name' => 'Plainfield', 'state_id' => 3928],
                ['name' => 'Sterling', 'state_id' => 3928],
                ['name' => 'Wauregan', 'state_id' => 3928]
            ]);
        }
    }
}
