<?php

use Illuminate\Database\Seeder;

class state13TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IA - Iowa.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Adair', 'state_id' => 3937],
                ['name' => 'Bridgewater', 'state_id' => 3937],
                ['name' => 'Fontanelle', 'state_id' => 3937],
                ['name' => 'Greenfield', 'state_id' => 3937],
                ['name' => 'Orient', 'state_id' => 3937],
                ['name' => 'Carbon', 'state_id' => 3937],
                ['name' => 'Corning', 'state_id' => 3937],
                ['name' => 'Nodaway', 'state_id' => 3937],
                ['name' => 'Prescott', 'state_id' => 3937],
                ['name' => 'Dorchester', 'state_id' => 3937],
                ['name' => 'Harpers Ferry', 'state_id' => 3937],
                ['name' => 'Lansing', 'state_id' => 3937],
                ['name' => 'New Albin', 'state_id' => 3937],
                ['name' => 'Postville', 'state_id' => 3937],
                ['name' => 'Waterville', 'state_id' => 3937],
                ['name' => 'Waukon', 'state_id' => 3937],
                ['name' => 'Centerville', 'state_id' => 3937],
                ['name' => 'Cincinnati', 'state_id' => 3937],
                ['name' => 'Exline', 'state_id' => 3937],
                ['name' => 'Moravia', 'state_id' => 3937],
                ['name' => 'Moulton', 'state_id' => 3937],
                ['name' => 'Mystic', 'state_id' => 3937],
                ['name' => 'Plano', 'state_id' => 3937],
                ['name' => 'Udell', 'state_id' => 3937],
                ['name' => 'Unionville', 'state_id' => 3937],
                ['name' => 'Audubon', 'state_id' => 3937],
                ['name' => 'Brayton', 'state_id' => 3937],
                ['name' => 'Exira', 'state_id' => 3937],
                ['name' => 'Gray', 'state_id' => 3937],
                ['name' => 'Hamlin', 'state_id' => 3937],
                ['name' => 'Kimballton', 'state_id' => 3937],
                ['name' => 'Atkins', 'state_id' => 3937],
                ['name' => 'Belle Plaine', 'state_id' => 3937],
                ['name' => 'Blairstown', 'state_id' => 3937],
                ['name' => 'Garrison', 'state_id' => 3937],
                ['name' => 'Keystone', 'state_id' => 3937],
                ['name' => 'Luzerne', 'state_id' => 3937],
                ['name' => 'Mount Auburn', 'state_id' => 3937],
                ['name' => 'Newhall', 'state_id' => 3937],
                ['name' => 'Norway', 'state_id' => 3937],
                ['name' => 'Shellsburg', 'state_id' => 3937],
                ['name' => 'Urbana', 'state_id' => 3937],
                ['name' => 'Van Horne', 'state_id' => 3937],
                ['name' => 'Vinton', 'state_id' => 3937],
                ['name' => 'Walford', 'state_id' => 3937],
                ['name' => 'Watkins', 'state_id' => 3937],
                ['name' => 'Cedar Falls', 'state_id' => 3937],
                ['name' => 'Dewar', 'state_id' => 3937],
                ['name' => 'Dunkerton', 'state_id' => 3937],
                ['name' => 'Gilbertville', 'state_id' => 3937],
                ['name' => 'Hudson', 'state_id' => 3937],
                ['name' => 'La Porte City', 'state_id' => 3937],
                ['name' => 'Raymond', 'state_id' => 3937],
                ['name' => 'Waterloo', 'state_id' => 3937],
                ['name' => 'Evansdale', 'state_id' => 3937],
                ['name' => 'Beaver', 'state_id' => 3937],
                ['name' => 'Boone', 'state_id' => 3937],
                ['name' => 'Boxholm', 'state_id' => 3937],
                ['name' => 'Luther', 'state_id' => 3937],
                ['name' => 'Madrid', 'state_id' => 3937],
                ['name' => 'Ogden', 'state_id' => 3937],
                ['name' => 'Pilot Mound', 'state_id' => 3937],
                ['name' => 'Denver', 'state_id' => 3937],
                ['name' => 'Frederika', 'state_id' => 3937],
                ['name' => 'Janesville', 'state_id' => 3937],
                ['name' => 'Plainfield', 'state_id' => 3937],
                ['name' => 'Readlyn', 'state_id' => 3937],
                ['name' => 'Sumner', 'state_id' => 3937],
                ['name' => 'Tripoli', 'state_id' => 3937],
                ['name' => 'Waverly', 'state_id' => 3937],
                ['name' => 'Aurora', 'state_id' => 3937],
                ['name' => 'Fairbank', 'state_id' => 3937],
                ['name' => 'Hazleton', 'state_id' => 3937],
                ['name' => 'Independence', 'state_id' => 3937],
                ['name' => 'Jesup', 'state_id' => 3937],
                ['name' => 'Lamont', 'state_id' => 3937],
                ['name' => 'Stanley', 'state_id' => 3937],
                ['name' => 'Winthrop', 'state_id' => 3937],
                ['name' => 'Brandon', 'state_id' => 3937],
                ['name' => 'Quasqueton', 'state_id' => 3937],
                ['name' => 'Rowley', 'state_id' => 3937],
                ['name' => 'Albert City', 'state_id' => 3937],
                ['name' => 'Marathon', 'state_id' => 3937],
                ['name' => 'Newell', 'state_id' => 3937],
                ['name' => 'Rembrandt', 'state_id' => 3937],
                ['name' => 'Sioux Rapids', 'state_id' => 3937],
                ['name' => 'Storm Lake', 'state_id' => 3937],
                ['name' => 'Truesdale', 'state_id' => 3937],
                ['name' => 'Alta', 'state_id' => 3937],
                ['name' => 'Linn Grove', 'state_id' => 3937],
                ['name' => 'Allison', 'state_id' => 3937],
                ['name' => 'Aplington', 'state_id' => 3937],
                ['name' => 'Aredale', 'state_id' => 3937],
                ['name' => 'Austinville', 'state_id' => 3937],
                ['name' => 'Bristow', 'state_id' => 3937],
                ['name' => 'Clarksville', 'state_id' => 3937],
                ['name' => 'Dumont', 'state_id' => 3937],
                ['name' => 'Greene', 'state_id' => 3937],
                ['name' => 'Kesley', 'state_id' => 3937],
                ['name' => 'New Hartford', 'state_id' => 3937],
                ['name' => 'Parkersburg', 'state_id' => 3937],
                ['name' => 'Shell Rock', 'state_id' => 3937],
                ['name' => 'Farnhamville', 'state_id' => 3937],
                ['name' => 'Jolley', 'state_id' => 3937],
                ['name' => 'Knierim', 'state_id' => 3937],
                ['name' => 'Lytton', 'state_id' => 3937],
                ['name' => 'Manson', 'state_id' => 3937],
                ['name' => 'Pomeroy', 'state_id' => 3937],
                ['name' => 'Rockwell City', 'state_id' => 3937],
                ['name' => 'Somers', 'state_id' => 3937],
                ['name' => 'Lake City', 'state_id' => 3937],
                ['name' => 'Lohrville', 'state_id' => 3937],
                ['name' => 'Coon Rapids', 'state_id' => 3937],
                ['name' => 'Carroll', 'state_id' => 3937],
                ['name' => 'Arcadia', 'state_id' => 3937],
                ['name' => 'Breda', 'state_id' => 3937],
                ['name' => 'Dedham', 'state_id' => 3937],
                ['name' => 'Glidden', 'state_id' => 3937],
                ['name' => 'Halbur', 'state_id' => 3937],
                ['name' => 'Lanesboro', 'state_id' => 3937],
                ['name' => 'Lidderdale', 'state_id' => 3937],
                ['name' => 'Manning', 'state_id' => 3937],
                ['name' => 'Ralston', 'state_id' => 3937],
                ['name' => 'Templeton', 'state_id' => 3937],
                ['name' => 'Anita', 'state_id' => 3937],
                ['name' => 'Atlantic', 'state_id' => 3937],
                ['name' => 'Wiota', 'state_id' => 3937],
                ['name' => 'Cumberland', 'state_id' => 3937],
                ['name' => 'Massena', 'state_id' => 3937],
                ['name' => 'Griswold', 'state_id' => 3937],
                ['name' => 'Lewis', 'state_id' => 3937],
                ['name' => 'Marne', 'state_id' => 3937],
                ['name' => 'Clarence', 'state_id' => 3937],
                ['name' => 'Lowden', 'state_id' => 3937],
                ['name' => 'Mechanicsville', 'state_id' => 3937],
                ['name' => 'Stanwood', 'state_id' => 3937],
                ['name' => 'West Branch', 'state_id' => 3937],
                ['name' => 'Bennett', 'state_id' => 3937],
                ['name' => 'Durant', 'state_id' => 3937],
                ['name' => 'Tipton', 'state_id' => 3937],
                ['name' => 'Mason City', 'state_id' => 3937],
                ['name' => 'Clear Lake', 'state_id' => 3937],
                ['name' => 'Dougherty', 'state_id' => 3937],
                ['name' => 'Meservey', 'state_id' => 3937],
                ['name' => 'Plymouth', 'state_id' => 3937],
                ['name' => 'Rock Falls', 'state_id' => 3937],
                ['name' => 'Rockwell', 'state_id' => 3937],
                ['name' => 'Swaledale', 'state_id' => 3937],
                ['name' => 'Thornton', 'state_id' => 3937],
                ['name' => 'Ventura', 'state_id' => 3937],
                ['name' => 'Aurelia', 'state_id' => 3937],
                ['name' => 'Cherokee', 'state_id' => 3937],
                ['name' => 'Cleghorn', 'state_id' => 3937],
                ['name' => 'Larrabee', 'state_id' => 3937],
                ['name' => 'Marcus', 'state_id' => 3937],
                ['name' => 'Meriden', 'state_id' => 3937],
                ['name' => 'Quimby', 'state_id' => 3937],
                ['name' => 'Washta', 'state_id' => 3937],
                ['name' => 'Alta Vista', 'state_id' => 3937],
                ['name' => 'Fredericksburg', 'state_id' => 3937],
                ['name' => 'Ionia', 'state_id' => 3937],
                ['name' => 'Nashua', 'state_id' => 3937],
                ['name' => 'New Hampton', 'state_id' => 3937],
                ['name' => 'North Washington', 'state_id' => 3937],
                ['name' => 'Lawler', 'state_id' => 3937],
                ['name' => 'Murray', 'state_id' => 3937],
                ['name' => 'Osceola', 'state_id' => 3937],
                ['name' => 'Woodburn', 'state_id' => 3937],
                ['name' => 'Peterson', 'state_id' => 3937],
                ['name' => 'Spencer', 'state_id' => 3937],
                ['name' => 'Dickens', 'state_id' => 3937],
                ['name' => 'Everly', 'state_id' => 3937],
                ['name' => 'Fostoria', 'state_id' => 3937],
                ['name' => 'Gillett Grove', 'state_id' => 3937],
                ['name' => 'Greenville', 'state_id' => 3937],
                ['name' => 'Royal', 'state_id' => 3937],
                ['name' => 'Webb', 'state_id' => 3937],
                ['name' => 'Edgewood', 'state_id' => 3937],
                ['name' => 'Elkader', 'state_id' => 3937],
                ['name' => 'Elkport', 'state_id' => 3937],
                ['name' => 'Farmersburg', 'state_id' => 3937],
                ['name' => 'Garber', 'state_id' => 3937],
                ['name' => 'Garnavillo', 'state_id' => 3937],
                ['name' => 'Guttenberg', 'state_id' => 3937],
                ['name' => 'North Buena Vista', 'state_id' => 3937],
                ['name' => 'Saint Olaf', 'state_id' => 3937],
                ['name' => 'Strawberry Point', 'state_id' => 3937],
                ['name' => 'Volga', 'state_id' => 3937],
                ['name' => 'Luana', 'state_id' => 3937],
                ['name' => 'Mc Gregor', 'state_id' => 3937],
                ['name' => 'Marquette', 'state_id' => 3937],
                ['name' => 'Monona', 'state_id' => 3937],
                ['name' => 'Delmar', 'state_id' => 3937],
                ['name' => 'Lost Nation', 'state_id' => 3937],
                ['name' => 'Andover', 'state_id' => 3937],
                ['name' => 'Bryant', 'state_id' => 3937],
                ['name' => 'Calamus', 'state_id' => 3937],
                ['name' => 'Camanche', 'state_id' => 3937],
                ['name' => 'Charlotte', 'state_id' => 3937],
                ['name' => 'Clinton', 'state_id' => 3937],
                ['name' => 'De Witt', 'state_id' => 3937],
                ['name' => 'Goose Lake', 'state_id' => 3937],
                ['name' => 'Grand Mound', 'state_id' => 3937],
                ['name' => 'Low Moor', 'state_id' => 3937],
                ['name' => 'Teeds Grove', 'state_id' => 3937],
                ['name' => 'Welton', 'state_id' => 3937],
                ['name' => 'Wheatland', 'state_id' => 3937],
                ['name' => 'Aspinwall', 'state_id' => 3937],
                ['name' => 'Charter Oak', 'state_id' => 3937],
                ['name' => 'Deloit', 'state_id' => 3937],
                ['name' => 'Denison', 'state_id' => 3937],
                ['name' => 'Kiron', 'state_id' => 3937],
                ['name' => 'Manilla', 'state_id' => 3937],
                ['name' => 'Ricketts', 'state_id' => 3937],
                ['name' => 'Schleswig', 'state_id' => 3937],
                ['name' => 'Vail', 'state_id' => 3937],
                ['name' => 'Westside', 'state_id' => 3937],
                ['name' => 'Arion', 'state_id' => 3937],
                ['name' => 'Dow City', 'state_id' => 3937],
                ['name' => 'Adel', 'state_id' => 3937],
                ['name' => 'Booneville', 'state_id' => 3937],
                ['name' => 'Bouton', 'state_id' => 3937],
                ['name' => 'Dallas Center', 'state_id' => 3937],
                ['name' => 'Dawson', 'state_id' => 3937],
                ['name' => 'De Soto', 'state_id' => 3937],
                ['name' => 'Dexter', 'state_id' => 3937],
                ['name' => 'Granger', 'state_id' => 3937],
                ['name' => 'Linden', 'state_id' => 3937],
                ['name' => 'Minburn', 'state_id' => 3937],
                ['name' => 'Perry', 'state_id' => 3937],
                ['name' => 'Redfield', 'state_id' => 3937],
                ['name' => 'Van Meter', 'state_id' => 3937],
                ['name' => 'Waukee', 'state_id' => 3937],
                ['name' => 'Woodward', 'state_id' => 3937],
                ['name' => 'Bloomfield', 'state_id' => 3937],
                ['name' => 'Drakesville', 'state_id' => 3937],
                ['name' => 'Floris', 'state_id' => 3937],
                ['name' => 'Pulaski', 'state_id' => 3937],
                ['name' => 'Davis City', 'state_id' => 3937],
                ['name' => 'Decatur', 'state_id' => 3937],
                ['name' => 'Garden Grove', 'state_id' => 3937],
                ['name' => 'Grand River', 'state_id' => 3937],
                ['name' => 'Lamoni', 'state_id' => 3937],
                ['name' => 'Leon', 'state_id' => 3937],
                ['name' => 'Van Wert', 'state_id' => 3937],
                ['name' => 'Weldon', 'state_id' => 3937],
                ['name' => 'Masonville', 'state_id' => 3937],
                ['name' => 'Colesburg', 'state_id' => 3937],
                ['name' => 'Delaware', 'state_id' => 3937],
                ['name' => 'Dundee', 'state_id' => 3937],
                ['name' => 'Earlville', 'state_id' => 3937],
                ['name' => 'Greeley', 'state_id' => 3937],
                ['name' => 'Manchester', 'state_id' => 3937],
                ['name' => 'Delhi', 'state_id' => 3937],
                ['name' => 'Hopkinton', 'state_id' => 3937],
                ['name' => 'Ryan', 'state_id' => 3937],
                ['name' => 'Burlington', 'state_id' => 3937],
                ['name' => 'Danville', 'state_id' => 3937],
                ['name' => 'Mediapolis', 'state_id' => 3937],
                ['name' => 'Middletown', 'state_id' => 3937],
                ['name' => 'Sperry', 'state_id' => 3937],
                ['name' => 'West Burlington', 'state_id' => 3937],
                ['name' => 'Yarmouth', 'state_id' => 3937],
                ['name' => 'Arnolds Park', 'state_id' => 3937],
                ['name' => 'Lake Park', 'state_id' => 3937],
                ['name' => 'Milford', 'state_id' => 3937],
                ['name' => 'Okoboji', 'state_id' => 3937],
                ['name' => 'Spirit Lake', 'state_id' => 3937],
                ['name' => 'Superior', 'state_id' => 3937],
                ['name' => 'Terril', 'state_id' => 3937],
                ['name' => 'Dubuque', 'state_id' => 3937],
                ['name' => 'Bernard', 'state_id' => 3937],
                ['name' => 'Cascade', 'state_id' => 3937],
                ['name' => 'Durango', 'state_id' => 3937],
                ['name' => 'Dyersville', 'state_id' => 3937],
                ['name' => 'Epworth', 'state_id' => 3937],
                ['name' => 'Farley', 'state_id' => 3937],
                ['name' => 'Holy Cross', 'state_id' => 3937],
                ['name' => 'Luxemburg', 'state_id' => 3937],
                ['name' => 'New Vienna', 'state_id' => 3937],
                ['name' => 'Peosta', 'state_id' => 3937],
                ['name' => 'Sherrill', 'state_id' => 3937],
                ['name' => 'Worthington', 'state_id' => 3937],
                ['name' => 'Zwingle', 'state_id' => 3937],
                ['name' => 'Armstrong', 'state_id' => 3937],
                ['name' => 'Dolliver', 'state_id' => 3937],
                ['name' => 'Ringsted', 'state_id' => 3937],
                ['name' => 'Estherville', 'state_id' => 3937],
                ['name' => 'Wallingford', 'state_id' => 3937],
                ['name' => 'Arlington', 'state_id' => 3937],
                ['name' => 'Maynard', 'state_id' => 3937],
                ['name' => 'Oelwein', 'state_id' => 3937],
                ['name' => 'Oran', 'state_id' => 3937],
                ['name' => 'Westgate', 'state_id' => 3937],
                ['name' => 'Clermont', 'state_id' => 3937],
                ['name' => 'Elgin', 'state_id' => 3937],
                ['name' => 'Fayette', 'state_id' => 3937],
                ['name' => 'Hawkeye', 'state_id' => 3937],
                ['name' => 'Randalia', 'state_id' => 3937],
                ['name' => 'Saint Lucas', 'state_id' => 3937],
                ['name' => 'Wadena', 'state_id' => 3937],
                ['name' => 'Waucoma', 'state_id' => 3937],
                ['name' => 'West Union', 'state_id' => 3937],
                ['name' => 'Floyd', 'state_id' => 3937],
                ['name' => 'Nora Springs', 'state_id' => 3937],
                ['name' => 'Rockford', 'state_id' => 3937],
                ['name' => 'Rudd', 'state_id' => 3937],
                ['name' => 'Charles City', 'state_id' => 3937],
                ['name' => 'Colwell', 'state_id' => 3937],
                ['name' => 'Marble Rock', 'state_id' => 3937],
                ['name' => 'Bradford', 'state_id' => 3937],
                ['name' => 'Popejoy', 'state_id' => 3937],
                ['name' => 'Alexander', 'state_id' => 3937],
                ['name' => 'Chapin', 'state_id' => 3937],
                ['name' => 'Coulter', 'state_id' => 3937],
                ['name' => 'Hampton', 'state_id' => 3937],
                ['name' => 'Latimer', 'state_id' => 3937],
                ['name' => 'Sheffield', 'state_id' => 3937],
                ['name' => 'Geneva', 'state_id' => 3937],
                ['name' => 'Farragut', 'state_id' => 3937],
                ['name' => 'Hamburg', 'state_id' => 3937],
                ['name' => 'Imogene', 'state_id' => 3937],
                ['name' => 'Percival', 'state_id' => 3937],
                ['name' => 'Randolph', 'state_id' => 3937],
                ['name' => 'Riverton', 'state_id' => 3937],
                ['name' => 'Sidney', 'state_id' => 3937],
                ['name' => 'Tabor', 'state_id' => 3937],
                ['name' => 'Thurman', 'state_id' => 3937],
                ['name' => 'Churdan', 'state_id' => 3937],
                ['name' => 'Cooper', 'state_id' => 3937],
                ['name' => 'Dana', 'state_id' => 3937],
                ['name' => 'Grand Junction', 'state_id' => 3937],
                ['name' => 'Jefferson', 'state_id' => 3937],
                ['name' => 'Paton', 'state_id' => 3937],
                ['name' => 'Rippey', 'state_id' => 3937],
                ['name' => 'Scranton', 'state_id' => 3937],
                ['name' => 'Beaman', 'state_id' => 3937],
                ['name' => 'Conrad', 'state_id' => 3937],
                ['name' => 'Dike', 'state_id' => 3937],
                ['name' => 'Grundy Center', 'state_id' => 3937],
                ['name' => 'Holland', 'state_id' => 3937],
                ['name' => 'Morrison', 'state_id' => 3937],
                ['name' => 'Reinbeck', 'state_id' => 3937],
                ['name' => 'Stout', 'state_id' => 3937],
                ['name' => 'Wellsburg', 'state_id' => 3937],
                ['name' => 'Bagley', 'state_id' => 3937],
                ['name' => 'Bayard', 'state_id' => 3937],
                ['name' => 'Casey', 'state_id' => 3937],
                ['name' => 'Guthrie Center', 'state_id' => 3937],
                ['name' => 'Jamaica', 'state_id' => 3937],
                ['name' => 'Menlo', 'state_id' => 3937],
                ['name' => 'Panora', 'state_id' => 3937],
                ['name' => 'Stuart', 'state_id' => 3937],
                ['name' => 'Yale', 'state_id' => 3937],
                ['name' => 'Blairsburg', 'state_id' => 3937],
                ['name' => 'Ellsworth', 'state_id' => 3937],
                ['name' => 'Jewell', 'state_id' => 3937],
                ['name' => 'Kamrar', 'state_id' => 3937],
                ['name' => 'Randall', 'state_id' => 3937],
                ['name' => 'Stanhope', 'state_id' => 3937],
                ['name' => 'Stratford', 'state_id' => 3937],
                ['name' => 'Williams', 'state_id' => 3937],
                ['name' => 'Webster City', 'state_id' => 3937],
                ['name' => 'Britt', 'state_id' => 3937],
                ['name' => 'Corwith', 'state_id' => 3937],
                ['name' => 'Crystal Lake', 'state_id' => 3937],
                ['name' => 'Garner', 'state_id' => 3937],
                ['name' => 'Goodell', 'state_id' => 3937],
                ['name' => 'Kanawha', 'state_id' => 3937],
                ['name' => 'Klemme', 'state_id' => 3937],
                ['name' => 'Woden', 'state_id' => 3937],
                ['name' => 'Alden', 'state_id' => 3937],
                ['name' => 'Buckeye', 'state_id' => 3937],
                ['name' => 'Garden City', 'state_id' => 3937],
                ['name' => 'Hubbard', 'state_id' => 3937],
                ['name' => 'Iowa Falls', 'state_id' => 3937],
                ['name' => 'New Providence', 'state_id' => 3937],
                ['name' => 'Radcliffe', 'state_id' => 3937],
                ['name' => 'Union', 'state_id' => 3937],
                ['name' => 'Gifford', 'state_id' => 3937],
                ['name' => 'Whitten', 'state_id' => 3937],
                ['name' => 'Ackley', 'state_id' => 3937],
                ['name' => 'Eldora', 'state_id' => 3937],
                ['name' => 'Steamboat Rock', 'state_id' => 3937],
                ['name' => 'Dunlap', 'state_id' => 3937],
                ['name' => 'Little Sioux', 'state_id' => 3937],
                ['name' => 'Logan', 'state_id' => 3937],
                ['name' => 'Magnolia', 'state_id' => 3937],
                ['name' => 'Missouri Valley', 'state_id' => 3937],
                ['name' => 'Modale', 'state_id' => 3937],
                ['name' => 'Mondamin', 'state_id' => 3937],
                ['name' => 'Persia', 'state_id' => 3937],
                ['name' => 'Pisgah', 'state_id' => 3937],
                ['name' => 'Woodbine', 'state_id' => 3937],
                ['name' => 'Hillsboro', 'state_id' => 3937],
                ['name' => 'Mount Pleasant', 'state_id' => 3937],
                ['name' => 'Rome', 'state_id' => 3937],
                ['name' => 'Mount Union', 'state_id' => 3937],
                ['name' => 'New London', 'state_id' => 3937],
                ['name' => 'Olds', 'state_id' => 3937],
                ['name' => 'Salem', 'state_id' => 3937],
                ['name' => 'Swedesburg', 'state_id' => 3937],
                ['name' => 'Wayland', 'state_id' => 3937],
                ['name' => 'Winfield', 'state_id' => 3937],
                ['name' => 'Riceville', 'state_id' => 3937],
                ['name' => 'Elma', 'state_id' => 3937],
                ['name' => 'Chester', 'state_id' => 3937],
                ['name' => 'Cresco', 'state_id' => 3937],
                ['name' => 'Lime Springs', 'state_id' => 3937],
                ['name' => 'Protivin', 'state_id' => 3937],
                ['name' => 'Bode', 'state_id' => 3937],
                ['name' => 'Bradgate', 'state_id' => 3937],
                ['name' => 'Dakota City', 'state_id' => 3937],
                ['name' => 'Gilmore City', 'state_id' => 3937],
                ['name' => 'Hardy', 'state_id' => 3937],
                ['name' => 'Humboldt', 'state_id' => 3937],
                ['name' => 'Livermore', 'state_id' => 3937],
                ['name' => 'Ottosen', 'state_id' => 3937],
                ['name' => 'Renwick', 'state_id' => 3937],
                ['name' => 'Rutland', 'state_id' => 3937],
                ['name' => 'Thor', 'state_id' => 3937],
                ['name' => 'Battle Creek', 'state_id' => 3937],
                ['name' => 'Galva', 'state_id' => 3937],
                ['name' => 'Holstein', 'state_id' => 3937],
                ['name' => 'Arthur', 'state_id' => 3937],
                ['name' => 'Ida Grove', 'state_id' => 3937],
                ['name' => 'Amana', 'state_id' => 3937],
                ['name' => 'Conroy', 'state_id' => 3937],
                ['name' => 'Homestead', 'state_id' => 3937],
                ['name' => 'Ladora', 'state_id' => 3937],
                ['name' => 'Marengo', 'state_id' => 3937],
                ['name' => 'Middle Amana', 'state_id' => 3937],
                ['name' => 'Millersburg', 'state_id' => 3937],
                ['name' => 'North English', 'state_id' => 3937],
                ['name' => 'Parnell', 'state_id' => 3937],
                ['name' => 'South Amana', 'state_id' => 3937],
                ['name' => 'Victor', 'state_id' => 3937],
                ['name' => 'Williamsburg', 'state_id' => 3937],
                ['name' => 'Andrew', 'state_id' => 3937],
                ['name' => 'Bellevue', 'state_id' => 3937],
                ['name' => 'La Motte', 'state_id' => 3937],
                ['name' => 'Maquoketa', 'state_id' => 3937],
                ['name' => 'Miles', 'state_id' => 3937],
                ['name' => 'Preston', 'state_id' => 3937],
                ['name' => 'Sabula', 'state_id' => 3937],
                ['name' => 'Saint Donatus', 'state_id' => 3937],
                ['name' => 'Spragueville', 'state_id' => 3937],
                ['name' => 'Springbrook', 'state_id' => 3937],
                ['name' => 'Baldwin', 'state_id' => 3937],
                ['name' => 'Monmouth', 'state_id' => 3937],
                ['name' => 'Baxter', 'state_id' => 3937],
                ['name' => 'Colfax', 'state_id' => 3937],
                ['name' => 'Ira', 'state_id' => 3937],
                ['name' => 'Kellogg', 'state_id' => 3937],
                ['name' => 'Killduff', 'state_id' => 3937],
                ['name' => 'Lynnville', 'state_id' => 3937],
                ['name' => 'Mingo', 'state_id' => 3937],
                ['name' => 'Monroe', 'state_id' => 3937],
                ['name' => 'Newton', 'state_id' => 3937],
                ['name' => 'Prairie City', 'state_id' => 3937],
                ['name' => 'Reasnor', 'state_id' => 3937],
                ['name' => 'Sully', 'state_id' => 3937],
                ['name' => 'Batavia', 'state_id' => 3937],
                ['name' => 'Fairfield', 'state_id' => 3937],
                ['name' => 'Libertyville', 'state_id' => 3937],
                ['name' => 'Packwood', 'state_id' => 3937],
                ['name' => 'Lockridge', 'state_id' => 3937],
                ['name' => 'Hills', 'state_id' => 3937],
                ['name' => 'Iowa City', 'state_id' => 3937],
                ['name' => 'Coralville', 'state_id' => 3937],
                ['name' => 'North Liberty', 'state_id' => 3937],
                ['name' => 'Oxford', 'state_id' => 3937],
                ['name' => 'Solon', 'state_id' => 3937],
                ['name' => 'Swisher', 'state_id' => 3937],
                ['name' => 'Tiffin', 'state_id' => 3937],
                ['name' => 'Lone Tree', 'state_id' => 3937],
                ['name' => 'Anamosa', 'state_id' => 3937],
                ['name' => 'Center Junction', 'state_id' => 3937],
                ['name' => 'Langworthy', 'state_id' => 3937],
                ['name' => 'Martelle', 'state_id' => 3937],
                ['name' => 'Monticello', 'state_id' => 3937],
                ['name' => 'Morley', 'state_id' => 3937],
                ['name' => 'Olin', 'state_id' => 3937],
                ['name' => 'Onslow', 'state_id' => 3937],
                ['name' => 'Oxford Junction', 'state_id' => 3937],
                ['name' => 'Wyoming', 'state_id' => 3937],
                ['name' => 'Gibson', 'state_id' => 3937],
                ['name' => 'Keswick', 'state_id' => 3937],
                ['name' => 'Thornburg', 'state_id' => 3937],
                ['name' => 'What Cheer', 'state_id' => 3937],
                ['name' => 'Harper', 'state_id' => 3937],
                ['name' => 'Keota', 'state_id' => 3937],
                ['name' => 'South English', 'state_id' => 3937],
                ['name' => 'Webster', 'state_id' => 3937],
                ['name' => 'Delta', 'state_id' => 3937],
                ['name' => 'Hayesville', 'state_id' => 3937],
                ['name' => 'Hedrick', 'state_id' => 3937],
                ['name' => 'Martinsburg', 'state_id' => 3937],
                ['name' => 'Ollie', 'state_id' => 3937],
                ['name' => 'Richland', 'state_id' => 3937],
                ['name' => 'Sigourney', 'state_id' => 3937],
                ['name' => 'Lakota', 'state_id' => 3937],
                ['name' => 'Titonka', 'state_id' => 3937],
                ['name' => 'Wesley', 'state_id' => 3937],
                ['name' => 'Algona', 'state_id' => 3937],
                ['name' => 'Bancroft', 'state_id' => 3937],
                ['name' => 'Burt', 'state_id' => 3937],
                ['name' => 'Fenton', 'state_id' => 3937],
                ['name' => 'Ledyard', 'state_id' => 3937],
                ['name' => 'Lone Rock', 'state_id' => 3937],
                ['name' => 'Lu Verne', 'state_id' => 3937],
                ['name' => 'Swea City', 'state_id' => 3937],
                ['name' => 'Whittemore', 'state_id' => 3937],
                ['name' => 'Argyle', 'state_id' => 3937],
                ['name' => 'Denmark', 'state_id' => 3937],
                ['name' => 'Donnellson', 'state_id' => 3937],
                ['name' => 'Fort Madison', 'state_id' => 3937],
                ['name' => 'Houghton', 'state_id' => 3937],
                ['name' => 'Keokuk', 'state_id' => 3937],
                ['name' => 'Montrose', 'state_id' => 3937],
                ['name' => 'Pilot Grove', 'state_id' => 3937],
                ['name' => 'West Point', 'state_id' => 3937],
                ['name' => 'Saint Paul', 'state_id' => 3937],
                ['name' => 'Wever', 'state_id' => 3937],
                ['name' => 'Alburnett', 'state_id' => 3937],
                ['name' => 'Center Point', 'state_id' => 3937],
                ['name' => 'Central City', 'state_id' => 3937],
                ['name' => 'Coggon', 'state_id' => 3937],
                ['name' => 'Prairieburg', 'state_id' => 3937],
                ['name' => 'Ely', 'state_id' => 3937],
                ['name' => 'Fairfax', 'state_id' => 3937],
                ['name' => 'Hiawatha', 'state_id' => 3937],
                ['name' => 'Lisbon', 'state_id' => 3937],
                ['name' => 'Marion', 'state_id' => 3937],
                ['name' => 'Mount Vernon', 'state_id' => 3937],
                ['name' => 'Palo', 'state_id' => 3937],
                ['name' => 'Robins', 'state_id' => 3937],
                ['name' => 'Springville', 'state_id' => 3937],
                ['name' => 'Toddville', 'state_id' => 3937],
                ['name' => 'Troy Mills', 'state_id' => 3937],
                ['name' => 'Walker', 'state_id' => 3937],
                ['name' => 'Cedar Rapids', 'state_id' => 3937],
                ['name' => 'Morning Sun', 'state_id' => 3937],
                ['name' => 'Oakville', 'state_id' => 3937],
                ['name' => 'Wapello', 'state_id' => 3937],
                ['name' => 'Columbus City', 'state_id' => 3937],
                ['name' => 'Columbus Junction', 'state_id' => 3937],
                ['name' => 'Grandview', 'state_id' => 3937],
                ['name' => 'Letts', 'state_id' => 3937],
                ['name' => 'Chariton', 'state_id' => 3937],
                ['name' => 'Derby', 'state_id' => 3937],
                ['name' => 'Lucas', 'state_id' => 3937],
                ['name' => 'Russell', 'state_id' => 3937],
                ['name' => 'Williamson', 'state_id' => 3937],
                ['name' => 'Alvord', 'state_id' => 3937],
                ['name' => 'Doon', 'state_id' => 3937],
                ['name' => 'George', 'state_id' => 3937],
                ['name' => 'Inwood', 'state_id' => 3937],
                ['name' => 'Larchwood', 'state_id' => 3937],
                ['name' => 'Lester', 'state_id' => 3937],
                ['name' => 'Little Rock', 'state_id' => 3937],
                ['name' => 'Rock Rapids', 'state_id' => 3937],
                ['name' => 'Bevington', 'state_id' => 3937],
                ['name' => 'Earlham', 'state_id' => 3937],
                ['name' => 'Macksburg', 'state_id' => 3937],
                ['name' => 'Patterson', 'state_id' => 3937],
                ['name' => 'Peru', 'state_id' => 3937],
                ['name' => 'Saint Charles', 'state_id' => 3937],
                ['name' => 'Truro', 'state_id' => 3937],
                ['name' => 'Winterset', 'state_id' => 3937],
                ['name' => 'Barnes City', 'state_id' => 3937],
                ['name' => 'Leighton', 'state_id' => 3937],
                ['name' => 'New Sharon', 'state_id' => 3937],
                ['name' => 'Beacon', 'state_id' => 3937],
                ['name' => 'Cedar', 'state_id' => 3937],
                ['name' => 'Fremont', 'state_id' => 3937],
                ['name' => 'Oskaloosa', 'state_id' => 3937],
                ['name' => 'Rose Hill', 'state_id' => 3937],
                ['name' => 'University Park', 'state_id' => 3937],
                ['name' => 'Bussey', 'state_id' => 3937],
                ['name' => 'Columbia', 'state_id' => 3937],
                ['name' => 'Melcher Dallas', 'state_id' => 3937],
                ['name' => 'Hamilton', 'state_id' => 3937],
                ['name' => 'Harvey', 'state_id' => 3937],
                ['name' => 'Knoxville', 'state_id' => 3937],
                ['name' => 'Otley', 'state_id' => 3937],
                ['name' => 'Pella', 'state_id' => 3937],
                ['name' => 'Pleasantville', 'state_id' => 3937],
                ['name' => 'Swan', 'state_id' => 3937],
                ['name' => 'Tracy', 'state_id' => 3937],
                ['name' => 'Albion', 'state_id' => 3937],
                ['name' => 'Clemons', 'state_id' => 3937],
                ['name' => 'Ferguson', 'state_id' => 3937],
                ['name' => 'Gilman', 'state_id' => 3937],
                ['name' => 'Haverhill', 'state_id' => 3937],
                ['name' => 'Laurel', 'state_id' => 3937],
                ['name' => 'Le Grand', 'state_id' => 3937],
                ['name' => 'Liscomb', 'state_id' => 3937],
                ['name' => 'Marshalltown', 'state_id' => 3937],
                ['name' => 'Melbourne', 'state_id' => 3937],
                ['name' => 'Rhodes', 'state_id' => 3937],
                ['name' => 'Saint Anthony', 'state_id' => 3937],
                ['name' => 'State Center', 'state_id' => 3937],
                ['name' => 'Emerson', 'state_id' => 3937],
                ['name' => 'Glenwood', 'state_id' => 3937],
                ['name' => 'Hastings', 'state_id' => 3937],
                ['name' => 'Henderson', 'state_id' => 3937],
                ['name' => 'Malvern', 'state_id' => 3937],
                ['name' => 'Mineola', 'state_id' => 3937],
                ['name' => 'Pacific Junction', 'state_id' => 3937],
                ['name' => 'Silver City', 'state_id' => 3937],
                ['name' => 'Carpenter', 'state_id' => 3937],
                ['name' => 'Little Cedar', 'state_id' => 3937],
                ['name' => 'Mc Intire', 'state_id' => 3937],
                ['name' => 'Orchard', 'state_id' => 3937],
                ['name' => 'Osage', 'state_id' => 3937],
                ['name' => 'Saint Ansgar', 'state_id' => 3937],
                ['name' => 'Stacyville', 'state_id' => 3937],
                ['name' => 'Toeterville', 'state_id' => 3937],
                ['name' => 'Castana', 'state_id' => 3937],
                ['name' => 'Mapleton', 'state_id' => 3937],
                ['name' => 'Onawa', 'state_id' => 3937],
                ['name' => 'Rodney', 'state_id' => 3937],
                ['name' => 'Ute', 'state_id' => 3937],
                ['name' => 'Whiting', 'state_id' => 3937],
                ['name' => 'Blencoe', 'state_id' => 3937],
                ['name' => 'Moorhead', 'state_id' => 3937],
                ['name' => 'Soldier', 'state_id' => 3937],
                ['name' => 'Lovilia', 'state_id' => 3937],
                ['name' => 'Albia', 'state_id' => 3937],
                ['name' => 'Melrose', 'state_id' => 3937],
                ['name' => 'Grant', 'state_id' => 3937],
                ['name' => 'Villisca', 'state_id' => 3937],
                ['name' => 'Elliott', 'state_id' => 3937],
                ['name' => 'Red Oak', 'state_id' => 3937],
                ['name' => 'Stanton', 'state_id' => 3937],
                ['name' => 'Atalissa', 'state_id' => 3937],
                ['name' => 'Conesville', 'state_id' => 3937],
                ['name' => 'Fruitland', 'state_id' => 3937],
                ['name' => 'Montpelier', 'state_id' => 3937],
                ['name' => 'Moscow', 'state_id' => 3937],
                ['name' => 'Muscatine', 'state_id' => 3937],
                ['name' => 'Nichols', 'state_id' => 3937],
                ['name' => 'Stockton', 'state_id' => 3937],
                ['name' => 'West Liberty', 'state_id' => 3937],
                ['name' => 'Wilton', 'state_id' => 3937],
                ['name' => 'Calumet', 'state_id' => 3937],
                ['name' => 'Paullina', 'state_id' => 3937],
                ['name' => 'Sutherland', 'state_id' => 3937],
                ['name' => 'Sheldon', 'state_id' => 3937],
                ['name' => 'Archer', 'state_id' => 3937],
                ['name' => 'Primghar', 'state_id' => 3937],
                ['name' => 'Sanborn', 'state_id' => 3937],
                ['name' => 'Hartley', 'state_id' => 3937],
                ['name' => 'Ashton', 'state_id' => 3937],
                ['name' => 'Sibley', 'state_id' => 3937],
                ['name' => 'Harris', 'state_id' => 3937],
                ['name' => 'Melvin', 'state_id' => 3937],
                ['name' => 'Ocheyedan', 'state_id' => 3937],
                ['name' => 'Shenandoah', 'state_id' => 3937],
                ['name' => 'Blanchard', 'state_id' => 3937],
                ['name' => 'Braddyville', 'state_id' => 3937],
                ['name' => 'Clarinda', 'state_id' => 3937],
                ['name' => 'Coin', 'state_id' => 3937],
                ['name' => 'College Springs', 'state_id' => 3937],
                ['name' => 'Essex', 'state_id' => 3937],
                ['name' => 'Northboro', 'state_id' => 3937],
                ['name' => 'Shambaugh', 'state_id' => 3937],
                ['name' => 'Yorktown', 'state_id' => 3937],
                ['name' => 'Ayrshire', 'state_id' => 3937],
                ['name' => 'Curlew', 'state_id' => 3937],
                ['name' => 'Cylinder', 'state_id' => 3937],
                ['name' => 'Emmetsburg', 'state_id' => 3937],
                ['name' => 'Mallard', 'state_id' => 3937],
                ['name' => 'West Bend', 'state_id' => 3937],
                ['name' => 'Graettinger', 'state_id' => 3937],
                ['name' => 'Ruthven', 'state_id' => 3937],
                ['name' => 'Akron', 'state_id' => 3937],
                ['name' => 'Brunsville', 'state_id' => 3937],
                ['name' => 'Hinton', 'state_id' => 3937],
                ['name' => 'Kingsley', 'state_id' => 3937],
                ['name' => 'Le Mars', 'state_id' => 3937],
                ['name' => 'Merrill', 'state_id' => 3937],
                ['name' => 'Oyens', 'state_id' => 3937],
                ['name' => 'Remsen', 'state_id' => 3937],
                ['name' => 'Westfield', 'state_id' => 3937],
                ['name' => 'Fonda', 'state_id' => 3937],
                ['name' => 'Havelock', 'state_id' => 3937],
                ['name' => 'Laurens', 'state_id' => 3937],
                ['name' => 'Palmer', 'state_id' => 3937],
                ['name' => 'Plover', 'state_id' => 3937],
                ['name' => 'Pocahontas', 'state_id' => 3937],
                ['name' => 'Rolfe', 'state_id' => 3937],
                ['name' => 'Varina', 'state_id' => 3937],
                ['name' => 'Alleman', 'state_id' => 3937],
                ['name' => 'Altoona', 'state_id' => 3937],
                ['name' => 'Ankeny', 'state_id' => 3937],
                ['name' => 'Berwick', 'state_id' => 3937],
                ['name' => 'Bondurant', 'state_id' => 3937],
                ['name' => 'Elkhart', 'state_id' => 3937],
                ['name' => 'Grimes', 'state_id' => 3937],
                ['name' => 'Johnston', 'state_id' => 3937],
                ['name' => 'Mitchellville', 'state_id' => 3937],
                ['name' => 'Polk City', 'state_id' => 3937],
                ['name' => 'Runnells', 'state_id' => 3937],
                ['name' => 'Sheldahl', 'state_id' => 3937],
                ['name' => 'West Des Moines', 'state_id' => 3937],
                ['name' => 'Des Moines', 'state_id' => 3937],
                ['name' => 'Urbandale', 'state_id' => 3937],
                ['name' => 'Windsor Heights', 'state_id' => 3937],
                ['name' => 'Clive', 'state_id' => 3937],
                ['name' => 'Pleasant Hill', 'state_id' => 3937],
                ['name' => 'Council Bluffs', 'state_id' => 3937],
                ['name' => 'Carter Lake', 'state_id' => 3937],
                ['name' => 'Avoca', 'state_id' => 3937],
                ['name' => 'Carson', 'state_id' => 3937],
                ['name' => 'Crescent', 'state_id' => 3937],
                ['name' => 'Hancock', 'state_id' => 3937],
                ['name' => 'Honey Creek', 'state_id' => 3937],
                ['name' => 'Mc Clelland', 'state_id' => 3937],
                ['name' => 'Macedonia', 'state_id' => 3937],
                ['name' => 'Minden', 'state_id' => 3937],
                ['name' => 'Neola', 'state_id' => 3937],
                ['name' => 'Oakland', 'state_id' => 3937],
                ['name' => 'Shelby', 'state_id' => 3937],
                ['name' => 'Treynor', 'state_id' => 3937],
                ['name' => 'Underwood', 'state_id' => 3937],
                ['name' => 'Walnut', 'state_id' => 3937],
                ['name' => 'Harlan', 'state_id' => 3937],
                ['name' => 'Grinnell', 'state_id' => 3937],
                ['name' => 'Malcom', 'state_id' => 3937],
                ['name' => 'Montezuma', 'state_id' => 3937],
                ['name' => 'Searsboro', 'state_id' => 3937],
                ['name' => 'Brooklyn', 'state_id' => 3937],
                ['name' => 'Guernsey', 'state_id' => 3937],
                ['name' => 'Deep River', 'state_id' => 3937],
                ['name' => 'Hartwick', 'state_id' => 3937],
                ['name' => 'Ellston', 'state_id' => 3937],
                ['name' => 'Kellerton', 'state_id' => 3937],
                ['name' => 'Benton', 'state_id' => 3937],
                ['name' => 'Diagonal', 'state_id' => 3937],
                ['name' => 'Mount Ayr', 'state_id' => 3937],
                ['name' => 'Redding', 'state_id' => 3937],
                ['name' => 'Tingley', 'state_id' => 3937],
                ['name' => 'Early', 'state_id' => 3937],
                ['name' => 'Nemaha', 'state_id' => 3937],
                ['name' => 'Sac City', 'state_id' => 3937],
                ['name' => 'Schaller', 'state_id' => 3937],
                ['name' => 'Auburn', 'state_id' => 3937],
                ['name' => 'Lake View', 'state_id' => 3937],
                ['name' => 'Odebolt', 'state_id' => 3937],
                ['name' => 'Wall Lake', 'state_id' => 3937],
                ['name' => 'Bettendorf', 'state_id' => 3937],
                ['name' => 'Blue Grass', 'state_id' => 3937],
                ['name' => 'Buffalo', 'state_id' => 3937],
                ['name' => 'Dixon', 'state_id' => 3937],
                ['name' => 'Donahue', 'state_id' => 3937],
                ['name' => 'Eldridge', 'state_id' => 3937],
                ['name' => 'Le Claire', 'state_id' => 3937],
                ['name' => 'Long Grove', 'state_id' => 3937],
                ['name' => 'Mc Causland', 'state_id' => 3937],
                ['name' => 'New Liberty', 'state_id' => 3937],
                ['name' => 'Pleasant Valley', 'state_id' => 3937],
                ['name' => 'Princeton', 'state_id' => 3937],
                ['name' => 'Walcott', 'state_id' => 3937],
                ['name' => 'Davenport', 'state_id' => 3937],
                ['name' => 'Irwin', 'state_id' => 3937],
                ['name' => 'Kirkman', 'state_id' => 3937],
                ['name' => 'Defiance', 'state_id' => 3937],
                ['name' => 'Earling', 'state_id' => 3937],
                ['name' => 'Elk Horn', 'state_id' => 3937],
                ['name' => 'Panama', 'state_id' => 3937],
                ['name' => 'Portsmouth', 'state_id' => 3937],
                ['name' => 'Westphalia', 'state_id' => 3937],
                ['name' => 'Alton', 'state_id' => 3937],
                ['name' => 'Chatsworth', 'state_id' => 3937],
                ['name' => 'Granville', 'state_id' => 3937],
                ['name' => 'Hawarden', 'state_id' => 3937],
                ['name' => 'Ireton', 'state_id' => 3937],
                ['name' => 'Maurice', 'state_id' => 3937],
                ['name' => 'Orange City', 'state_id' => 3937],
                ['name' => 'Boyden', 'state_id' => 3937],
                ['name' => 'Hospers', 'state_id' => 3937],
                ['name' => 'Hull', 'state_id' => 3937],
                ['name' => 'Matlock', 'state_id' => 3937],
                ['name' => 'Rock Valley', 'state_id' => 3937],
                ['name' => 'Sioux Center', 'state_id' => 3937],
                ['name' => 'Ames', 'state_id' => 3937],
                ['name' => 'Cambridge', 'state_id' => 3937],
                ['name' => 'Collins', 'state_id' => 3937],
                ['name' => 'Colo', 'state_id' => 3937],
                ['name' => 'Gilbert', 'state_id' => 3937],
                ['name' => 'Huxley', 'state_id' => 3937],
                ['name' => 'Kelley', 'state_id' => 3937],
                ['name' => 'Mc Callsburg', 'state_id' => 3937],
                ['name' => 'Maxwell', 'state_id' => 3937],
                ['name' => 'Nevada', 'state_id' => 3937],
                ['name' => 'Roland', 'state_id' => 3937],
                ['name' => 'Slater', 'state_id' => 3937],
                ['name' => 'Story City', 'state_id' => 3937],
                ['name' => 'Zearing', 'state_id' => 3937],
                ['name' => 'Montour', 'state_id' => 3937],
                ['name' => 'Buckingham', 'state_id' => 3937],
                ['name' => 'Garwin', 'state_id' => 3937],
                ['name' => 'Gladbrook', 'state_id' => 3937],
                ['name' => 'Lincoln', 'state_id' => 3937],
                ['name' => 'Traer', 'state_id' => 3937],
                ['name' => 'Chelsea', 'state_id' => 3937],
                ['name' => 'Clutier', 'state_id' => 3937],
                ['name' => 'Dysart', 'state_id' => 3937],
                ['name' => 'Elberon', 'state_id' => 3937],
                ['name' => 'Tama', 'state_id' => 3937],
                ['name' => 'Toledo', 'state_id' => 3937],
                ['name' => 'Vining', 'state_id' => 3937],
                ['name' => 'Bedford', 'state_id' => 3937],
                ['name' => 'Blockton', 'state_id' => 3937],
                ['name' => 'Clearfield', 'state_id' => 3937],
                ['name' => 'Gravity', 'state_id' => 3937],
                ['name' => 'Lenox', 'state_id' => 3937],
                ['name' => 'Sharpsburg', 'state_id' => 3937],
                ['name' => 'New Market', 'state_id' => 3937],
                ['name' => 'Lorimor', 'state_id' => 3937],
                ['name' => 'Thayer', 'state_id' => 3937],
                ['name' => 'Creston', 'state_id' => 3937],
                ['name' => 'Afton', 'state_id' => 3937],
                ['name' => 'Arispe', 'state_id' => 3937],
                ['name' => 'Cromwell', 'state_id' => 3937],
                ['name' => 'Shannon City', 'state_id' => 3937],
                ['name' => 'Birmingham', 'state_id' => 3937],
                ['name' => 'Cantril', 'state_id' => 3937],
                ['name' => 'Douds', 'state_id' => 3937],
                ['name' => 'Keosauqua', 'state_id' => 3937],
                ['name' => 'Milton', 'state_id' => 3937],
                ['name' => 'Mount Sterling', 'state_id' => 3937],
                ['name' => 'Selma', 'state_id' => 3937],
                ['name' => 'Bonaparte', 'state_id' => 3937],
                ['name' => 'Farmington', 'state_id' => 3937],
                ['name' => 'Stockport', 'state_id' => 3937],
                ['name' => 'Ottumwa', 'state_id' => 3937],
                ['name' => 'Agency', 'state_id' => 3937],
                ['name' => 'Blakesburg', 'state_id' => 3937],
                ['name' => 'Chillicothe', 'state_id' => 3937],
                ['name' => 'Eddyville', 'state_id' => 3937],
                ['name' => 'Eldon', 'state_id' => 3937],
                ['name' => 'Kirkville', 'state_id' => 3937],
                ['name' => 'Ackworth', 'state_id' => 3937],
                ['name' => 'Carlisle', 'state_id' => 3937],
                ['name' => 'Cumming', 'state_id' => 3937],
                ['name' => 'Hartford', 'state_id' => 3937],
                ['name' => 'Indianola', 'state_id' => 3937],
                ['name' => 'Lacona', 'state_id' => 3937],
                ['name' => 'Liberty Center', 'state_id' => 3937],
                ['name' => 'Martensdale', 'state_id' => 3937],
                ['name' => 'Milo', 'state_id' => 3937],
                ['name' => 'New Virginia', 'state_id' => 3937],
                ['name' => 'Norwalk', 'state_id' => 3937],
                ['name' => 'Prole', 'state_id' => 3937],
                ['name' => 'Saint Marys', 'state_id' => 3937],
                ['name' => 'Ainsworth', 'state_id' => 3937],
                ['name' => 'Kalona', 'state_id' => 3937],
                ['name' => 'Riverside', 'state_id' => 3937],
                ['name' => 'Washington', 'state_id' => 3937],
                ['name' => 'Wellman', 'state_id' => 3937],
                ['name' => 'West Chester', 'state_id' => 3937],
                ['name' => 'Brighton', 'state_id' => 3937],
                ['name' => 'Crawfordsville', 'state_id' => 3937],
                ['name' => 'Allerton', 'state_id' => 3937],
                ['name' => 'Clio', 'state_id' => 3937],
                ['name' => 'Corydon', 'state_id' => 3937],
                ['name' => 'Humeston', 'state_id' => 3937],
                ['name' => 'Lineville', 'state_id' => 3937],
                ['name' => 'Millerton', 'state_id' => 3937],
                ['name' => 'Promise City', 'state_id' => 3937],
                ['name' => 'Seymour', 'state_id' => 3937],
                ['name' => 'Fort Dodge', 'state_id' => 3937],
                ['name' => 'Badger', 'state_id' => 3937],
                ['name' => 'Barnum', 'state_id' => 3937],
                ['name' => 'Burnside', 'state_id' => 3937],
                ['name' => 'Callender', 'state_id' => 3937],
                ['name' => 'Clare', 'state_id' => 3937],
                ['name' => 'Dayton', 'state_id' => 3937],
                ['name' => 'Duncombe', 'state_id' => 3937],
                ['name' => 'Gowrie', 'state_id' => 3937],
                ['name' => 'Harcourt', 'state_id' => 3937],
                ['name' => 'Lehigh', 'state_id' => 3937],
                ['name' => 'Moorland', 'state_id' => 3937],
                ['name' => 'Otho', 'state_id' => 3937],
                ['name' => 'Vincent', 'state_id' => 3937],
                ['name' => 'Buffalo Center', 'state_id' => 3937],
                ['name' => 'Forest City', 'state_id' => 3937],
                ['name' => 'Lake Mills', 'state_id' => 3937],
                ['name' => 'Leland', 'state_id' => 3937],
                ['name' => 'Rake', 'state_id' => 3937],
                ['name' => 'Scarville', 'state_id' => 3937],
                ['name' => 'Thompson', 'state_id' => 3937],
                ['name' => 'Decorah', 'state_id' => 3937],
                ['name' => 'Calmar', 'state_id' => 3937],
                ['name' => 'Castalia', 'state_id' => 3937],
                ['name' => 'Fort Atkinson', 'state_id' => 3937],
                ['name' => 'Highlandville', 'state_id' => 3937],
                ['name' => 'Ossian', 'state_id' => 3937],
                ['name' => 'Ridgeway', 'state_id' => 3937],
                ['name' => 'Spillville', 'state_id' => 3937],
                ['name' => 'Anthon', 'state_id' => 3937],
                ['name' => 'Bronson', 'state_id' => 3937],
                ['name' => 'Climbing Hill', 'state_id' => 3937],
                ['name' => 'Correctionville', 'state_id' => 3937],
                ['name' => 'Cushing', 'state_id' => 3937],
                ['name' => 'Danbury', 'state_id' => 3937],
                ['name' => 'Hornick', 'state_id' => 3937],
                ['name' => 'Lawton', 'state_id' => 3937],
                ['name' => 'Moville', 'state_id' => 3937],
                ['name' => 'Oto', 'state_id' => 3937],
                ['name' => 'Pierson', 'state_id' => 3937],
                ['name' => 'Salix', 'state_id' => 3937],
                ['name' => 'Sergeant Bluff', 'state_id' => 3937],
                ['name' => 'Sloan', 'state_id' => 3937],
                ['name' => 'Smithland', 'state_id' => 3937],
                ['name' => 'Sioux City', 'state_id' => 3937],
                ['name' => 'Fertile', 'state_id' => 3937],
                ['name' => 'Grafton', 'state_id' => 3937],
                ['name' => 'Hanlontown', 'state_id' => 3937],
                ['name' => 'Joice', 'state_id' => 3937],
                ['name' => 'Kensett', 'state_id' => 3937],
                ['name' => 'Manly', 'state_id' => 3937],
                ['name' => 'Northwood', 'state_id' => 3937],
                ['name' => 'Dows', 'state_id' => 3937],
                ['name' => 'Galt', 'state_id' => 3937],
                ['name' => 'Belmond', 'state_id' => 3937],
                ['name' => 'Rowan', 'state_id' => 3937],
                ['name' => 'Clarion', 'state_id' => 3937],
                ['name' => 'Eagle Grove', 'state_id' => 3937],
                ['name' => 'Goldfield', 'state_id' => 3937],
                ['name' => 'Woolstock', 'state_id' => 3937]
            ]);
        }
    }
}
