<?php

use Illuminate\Database\Seeder;

class state5TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of CA - California.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Alameda', 'state_id' => 3925],
                ['name' => 'Fremont', 'state_id' => 3925],
                ['name' => 'Hayward', 'state_id' => 3925],
                ['name' => 'Castro Valley', 'state_id' => 3925],
                ['name' => 'Livermore', 'state_id' => 3925],
                ['name' => 'Newark', 'state_id' => 3925],
                ['name' => 'Pleasanton', 'state_id' => 3925],
                ['name' => 'Dublin', 'state_id' => 3925],
                ['name' => 'San Leandro', 'state_id' => 3925],
                ['name' => 'San Lorenzo', 'state_id' => 3925],
                ['name' => 'Sunol', 'state_id' => 3925],
                ['name' => 'Union City', 'state_id' => 3925],
                ['name' => 'Oakland', 'state_id' => 3925],
                ['name' => 'Emeryville', 'state_id' => 3925],
                ['name' => 'Piedmont', 'state_id' => 3925],
                ['name' => 'Berkeley', 'state_id' => 3925],
                ['name' => 'Albany', 'state_id' => 3925],
                ['name' => 'Kirkwood', 'state_id' => 3925],
                ['name' => 'Markleeville', 'state_id' => 3925],
                ['name' => 'Amador City', 'state_id' => 3925],
                ['name' => 'Fiddletown', 'state_id' => 3925],
                ['name' => 'Ione', 'state_id' => 3925],
                ['name' => 'Jackson', 'state_id' => 3925],
                ['name' => 'Kit Carson', 'state_id' => 3925],
                ['name' => 'Martell', 'state_id' => 3925],
                ['name' => 'Pine Grove', 'state_id' => 3925],
                ['name' => 'Pioneer', 'state_id' => 3925],
                ['name' => 'Plymouth', 'state_id' => 3925],
                ['name' => 'River Pines', 'state_id' => 3925],
                ['name' => 'Sutter Creek', 'state_id' => 3925],
                ['name' => 'Volcano', 'state_id' => 3925],
                ['name' => 'Drytown', 'state_id' => 3925],
                ['name' => 'Bangor', 'state_id' => 3925],
                ['name' => 'Berry Creek', 'state_id' => 3925],
                ['name' => 'Biggs', 'state_id' => 3925],
                ['name' => 'Chico', 'state_id' => 3925],
                ['name' => 'Clipper Mills', 'state_id' => 3925],
                ['name' => 'Durham', 'state_id' => 3925],
                ['name' => 'Feather Falls', 'state_id' => 3925],
                ['name' => 'Forbestown', 'state_id' => 3925],
                ['name' => 'Forest Ranch', 'state_id' => 3925],
                ['name' => 'Gridley', 'state_id' => 3925],
                ['name' => 'Magalia', 'state_id' => 3925],
                ['name' => 'Nelson', 'state_id' => 3925],
                ['name' => 'Oroville', 'state_id' => 3925],
                ['name' => 'Paradise', 'state_id' => 3925],
                ['name' => 'Palermo', 'state_id' => 3925],
                ['name' => 'Richvale', 'state_id' => 3925],
                ['name' => 'Stirling City', 'state_id' => 3925],
                ['name' => 'Altaville', 'state_id' => 3925],
                ['name' => 'Angels Camp', 'state_id' => 3925],
                ['name' => 'Arnold', 'state_id' => 3925],
                ['name' => 'Avery', 'state_id' => 3925],
                ['name' => 'Burson', 'state_id' => 3925],
                ['name' => 'Campo Seco', 'state_id' => 3925],
                ['name' => 'Copperopolis', 'state_id' => 3925],
                ['name' => 'Douglas Flat', 'state_id' => 3925],
                ['name' => 'Glencoe', 'state_id' => 3925],
                ['name' => 'Hathaway Pines', 'state_id' => 3925],
                ['name' => 'Mokelumne Hill', 'state_id' => 3925],
                ['name' => 'Mountain Ranch', 'state_id' => 3925],
                ['name' => 'Murphys', 'state_id' => 3925],
                ['name' => 'Rail Road Flat', 'state_id' => 3925],
                ['name' => 'San Andreas', 'state_id' => 3925],
                ['name' => 'Vallecito', 'state_id' => 3925],
                ['name' => 'Valley Springs', 'state_id' => 3925],
                ['name' => 'Wallace', 'state_id' => 3925],
                ['name' => 'West Point', 'state_id' => 3925],
                ['name' => 'Wilseyville', 'state_id' => 3925],
                ['name' => 'Arbuckle', 'state_id' => 3925],
                ['name' => 'Colusa', 'state_id' => 3925],
                ['name' => 'Grimes', 'state_id' => 3925],
                ['name' => 'Maxwell', 'state_id' => 3925],
                ['name' => 'Princeton', 'state_id' => 3925],
                ['name' => 'Stonyford', 'state_id' => 3925],
                ['name' => 'Williams', 'state_id' => 3925],
                ['name' => 'Discovery Bay', 'state_id' => 3925],
                ['name' => 'Danville', 'state_id' => 3925],
                ['name' => 'Alamo', 'state_id' => 3925],
                ['name' => 'Antioch', 'state_id' => 3925],
                ['name' => 'Bethel Island', 'state_id' => 3925],
                ['name' => 'Brentwood', 'state_id' => 3925],
                ['name' => 'Byron', 'state_id' => 3925],
                ['name' => 'Canyon', 'state_id' => 3925],
                ['name' => 'Clayton', 'state_id' => 3925],
                ['name' => 'Concord', 'state_id' => 3925],
                ['name' => 'Pleasant Hill', 'state_id' => 3925],
                ['name' => 'Crockett', 'state_id' => 3925],
                ['name' => 'Diablo', 'state_id' => 3925],
                ['name' => 'El Cerrito', 'state_id' => 3925],
                ['name' => 'Hercules', 'state_id' => 3925],
                ['name' => 'Knightsen', 'state_id' => 3925],
                ['name' => 'Lafayette', 'state_id' => 3925],
                ['name' => 'Martinez', 'state_id' => 3925],
                ['name' => 'Moraga', 'state_id' => 3925],
                ['name' => 'Oakley', 'state_id' => 3925],
                ['name' => 'Orinda', 'state_id' => 3925],
                ['name' => 'Pinole', 'state_id' => 3925],
                ['name' => 'Pittsburg', 'state_id' => 3925],
                ['name' => 'Port Costa', 'state_id' => 3925],
                ['name' => 'Rodeo', 'state_id' => 3925],
                ['name' => 'San Ramon', 'state_id' => 3925],
                ['name' => 'Walnut Creek', 'state_id' => 3925],
                ['name' => 'Richmond', 'state_id' => 3925],
                ['name' => 'El Sobrante', 'state_id' => 3925],
                ['name' => 'San Pablo', 'state_id' => 3925],
                ['name' => 'Crescent City', 'state_id' => 3925],
                ['name' => 'Fort Dick', 'state_id' => 3925],
                ['name' => 'Gasquet', 'state_id' => 3925],
                ['name' => 'Klamath', 'state_id' => 3925],
                ['name' => 'Smith River', 'state_id' => 3925],
                ['name' => 'Coloma', 'state_id' => 3925],
                ['name' => 'Cool', 'state_id' => 3925],
                ['name' => 'Diamond Springs', 'state_id' => 3925],
                ['name' => 'El Dorado', 'state_id' => 3925],
                ['name' => 'Garden Valley', 'state_id' => 3925],
                ['name' => 'Georgetown', 'state_id' => 3925],
                ['name' => 'Greenwood', 'state_id' => 3925],
                ['name' => 'Grizzly Flats', 'state_id' => 3925],
                ['name' => 'Lotus', 'state_id' => 3925],
                ['name' => 'Mount Aukum', 'state_id' => 3925],
                ['name' => 'Pilot Hill', 'state_id' => 3925],
                ['name' => 'Placerville', 'state_id' => 3925],
                ['name' => 'Rescue', 'state_id' => 3925],
                ['name' => 'Shingle Springs', 'state_id' => 3925],
                ['name' => 'Somerset', 'state_id' => 3925],
                ['name' => 'Camino', 'state_id' => 3925],
                ['name' => 'Kyburz', 'state_id' => 3925],
                ['name' => 'Echo Lake', 'state_id' => 3925],
                ['name' => 'Pollock Pines', 'state_id' => 3925],
                ['name' => 'Twin Bridges', 'state_id' => 3925],
                ['name' => 'El Dorado Hills', 'state_id' => 3925],
                ['name' => 'Tahoma', 'state_id' => 3925],
                ['name' => 'South Lake Tahoe', 'state_id' => 3925],
                ['name' => 'Coalinga', 'state_id' => 3925],
                ['name' => 'Huron', 'state_id' => 3925],
                ['name' => 'Laton', 'state_id' => 3925],
                ['name' => 'Auberry', 'state_id' => 3925],
                ['name' => 'Big Creek', 'state_id' => 3925],
                ['name' => 'Biola', 'state_id' => 3925],
                ['name' => 'Burrel', 'state_id' => 3925],
                ['name' => 'Cantua Creek', 'state_id' => 3925],
                ['name' => 'Caruthers', 'state_id' => 3925],
                ['name' => 'Clovis', 'state_id' => 3925],
                ['name' => 'Del Rey', 'state_id' => 3925],
                ['name' => 'Dunlap', 'state_id' => 3925],
                ['name' => 'Firebaugh', 'state_id' => 3925],
                ['name' => 'Five Points', 'state_id' => 3925],
                ['name' => 'Fowler', 'state_id' => 3925],
                ['name' => 'Friant', 'state_id' => 3925],
                ['name' => 'Helm', 'state_id' => 3925],
                ['name' => 'Hume', 'state_id' => 3925],
                ['name' => 'Kerman', 'state_id' => 3925],
                ['name' => 'Kingsburg', 'state_id' => 3925],
                ['name' => 'Lakeshore', 'state_id' => 3925],
                ['name' => 'Mendota', 'state_id' => 3925],
                ['name' => 'Miramonte', 'state_id' => 3925],
                ['name' => 'Mono Hot Springs', 'state_id' => 3925],
                ['name' => 'Orange Cove', 'state_id' => 3925],
                ['name' => 'Parlier', 'state_id' => 3925],
                ['name' => 'Piedra', 'state_id' => 3925],
                ['name' => 'Fresno', 'state_id' => 3925],
                ['name' => 'Prather', 'state_id' => 3925],
                ['name' => 'Raisin City', 'state_id' => 3925],
                ['name' => 'Reedley', 'state_id' => 3925],
                ['name' => 'Riverdale', 'state_id' => 3925],
                ['name' => 'Sanger', 'state_id' => 3925],
                ['name' => 'San Joaquin', 'state_id' => 3925],
                ['name' => 'Selma', 'state_id' => 3925],
                ['name' => 'Shaver Lake', 'state_id' => 3925],
                ['name' => 'Tollhouse', 'state_id' => 3925],
                ['name' => 'Tranquillity', 'state_id' => 3925],
                ['name' => 'Squaw Valley', 'state_id' => 3925],
                ['name' => 'Artois', 'state_id' => 3925],
                ['name' => 'Butte City', 'state_id' => 3925],
                ['name' => 'Elk Creek', 'state_id' => 3925],
                ['name' => 'Glenn', 'state_id' => 3925],
                ['name' => 'Hamilton City', 'state_id' => 3925],
                ['name' => 'Orland', 'state_id' => 3925],
                ['name' => 'Willows', 'state_id' => 3925],
                ['name' => 'Eureka', 'state_id' => 3925],
                ['name' => 'Alderpoint', 'state_id' => 3925],
                ['name' => 'Blocksburg', 'state_id' => 3925],
                ['name' => 'Arcata', 'state_id' => 3925],
                ['name' => 'Mckinleyville', 'state_id' => 3925],
                ['name' => 'Bayside', 'state_id' => 3925],
                ['name' => 'Blue Lake', 'state_id' => 3925],
                ['name' => 'Bridgeville', 'state_id' => 3925],
                ['name' => 'Carlotta', 'state_id' => 3925],
                ['name' => 'Cutten', 'state_id' => 3925],
                ['name' => 'Ferndale', 'state_id' => 3925],
                ['name' => 'Fields Landing', 'state_id' => 3925],
                ['name' => 'Fortuna', 'state_id' => 3925],
                ['name' => 'Garberville', 'state_id' => 3925],
                ['name' => 'Honeydew', 'state_id' => 3925],
                ['name' => 'Hoopa', 'state_id' => 3925],
                ['name' => 'Hydesville', 'state_id' => 3925],
                ['name' => 'Kneeland', 'state_id' => 3925],
                ['name' => 'Korbel', 'state_id' => 3925],
                ['name' => 'Loleta', 'state_id' => 3925],
                ['name' => 'Miranda', 'state_id' => 3925],
                ['name' => 'Myers Flat', 'state_id' => 3925],
                ['name' => 'Orick', 'state_id' => 3925],
                ['name' => 'Orleans', 'state_id' => 3925],
                ['name' => 'Petrolia', 'state_id' => 3925],
                ['name' => 'Phillipsville', 'state_id' => 3925],
                ['name' => 'Redway', 'state_id' => 3925],
                ['name' => 'Rio Dell', 'state_id' => 3925],
                ['name' => 'Samoa', 'state_id' => 3925],
                ['name' => 'Scotia', 'state_id' => 3925],
                ['name' => 'Redcrest', 'state_id' => 3925],
                ['name' => 'Trinidad', 'state_id' => 3925],
                ['name' => 'Weott', 'state_id' => 3925],
                ['name' => 'Willow Creek', 'state_id' => 3925],
                ['name' => 'Whitethorn', 'state_id' => 3925],
                ['name' => 'Bard', 'state_id' => 3925],
                ['name' => 'Brawley', 'state_id' => 3925],
                ['name' => 'Calexico', 'state_id' => 3925],
                ['name' => 'Calipatria', 'state_id' => 3925],
                ['name' => 'El Centro', 'state_id' => 3925],
                ['name' => 'Heber', 'state_id' => 3925],
                ['name' => 'Holtville', 'state_id' => 3925],
                ['name' => 'Imperial', 'state_id' => 3925],
                ['name' => 'Niland', 'state_id' => 3925],
                ['name' => 'Ocotillo', 'state_id' => 3925],
                ['name' => 'Palo Verde', 'state_id' => 3925],
                ['name' => 'Seeley', 'state_id' => 3925],
                ['name' => 'Salton City', 'state_id' => 3925],
                ['name' => 'Westmorland', 'state_id' => 3925],
                ['name' => 'Winterhaven', 'state_id' => 3925],
                ['name' => 'Fontana', 'state_id' => 3925],
                ['name' => 'Death Valley', 'state_id' => 3925],
                ['name' => 'Shoshone', 'state_id' => 3925],
                ['name' => 'Tecopa', 'state_id' => 3925],
                ['name' => 'Big Pine', 'state_id' => 3925],
                ['name' => 'Bishop', 'state_id' => 3925],
                ['name' => 'Darwin', 'state_id' => 3925],
                ['name' => 'Independence', 'state_id' => 3925],
                ['name' => 'Keeler', 'state_id' => 3925],
                ['name' => 'Little Lake', 'state_id' => 3925],
                ['name' => 'Lone Pine', 'state_id' => 3925],
                ['name' => 'Olancha', 'state_id' => 3925],
                ['name' => 'Arvin', 'state_id' => 3925],
                ['name' => 'Bodfish', 'state_id' => 3925],
                ['name' => 'Buttonwillow', 'state_id' => 3925],
                ['name' => 'Delano', 'state_id' => 3925],
                ['name' => 'Edison', 'state_id' => 3925],
                ['name' => 'Pine Mountain Club', 'state_id' => 3925],
                ['name' => 'Fellows', 'state_id' => 3925],
                ['name' => 'Frazier Park', 'state_id' => 3925],
                ['name' => 'Glennville', 'state_id' => 3925],
                ['name' => 'Kernville', 'state_id' => 3925],
                ['name' => 'Lake Isabella', 'state_id' => 3925],
                ['name' => 'Lamont', 'state_id' => 3925],
                ['name' => 'Lebec', 'state_id' => 3925],
                ['name' => 'Lost Hills', 'state_id' => 3925],
                ['name' => 'Mc Farland', 'state_id' => 3925],
                ['name' => 'Mc Kittrick', 'state_id' => 3925],
                ['name' => 'Maricopa', 'state_id' => 3925],
                ['name' => 'Onyx', 'state_id' => 3925],
                ['name' => 'Shafter', 'state_id' => 3925],
                ['name' => 'Taft', 'state_id' => 3925],
                ['name' => 'Tupman', 'state_id' => 3925],
                ['name' => 'Wasco', 'state_id' => 3925],
                ['name' => 'Weldon', 'state_id' => 3925],
                ['name' => 'Wofford Heights', 'state_id' => 3925],
                ['name' => 'Woody', 'state_id' => 3925],
                ['name' => 'Bakersfield', 'state_id' => 3925],
                ['name' => 'Mojave', 'state_id' => 3925],
                ['name' => 'California City', 'state_id' => 3925],
                ['name' => 'Boron', 'state_id' => 3925],
                ['name' => 'Caliente', 'state_id' => 3925],
                ['name' => 'Cantil', 'state_id' => 3925],
                ['name' => 'Edwards', 'state_id' => 3925],
                ['name' => 'Inyokern', 'state_id' => 3925],
                ['name' => 'Johannesburg', 'state_id' => 3925],
                ['name' => 'Keene', 'state_id' => 3925],
                ['name' => 'Randsburg', 'state_id' => 3925],
                ['name' => 'Ridgecrest', 'state_id' => 3925],
                ['name' => 'Rosamond', 'state_id' => 3925],
                ['name' => 'Tehachapi', 'state_id' => 3925],
                ['name' => 'Armona', 'state_id' => 3925],
                ['name' => 'Avenal', 'state_id' => 3925],
                ['name' => 'Corcoran', 'state_id' => 3925],
                ['name' => 'Hanford', 'state_id' => 3925],
                ['name' => 'Kettleman City', 'state_id' => 3925],
                ['name' => 'Lemoore', 'state_id' => 3925],
                ['name' => 'Stratford', 'state_id' => 3925],
                ['name' => 'Clearlake', 'state_id' => 3925],
                ['name' => 'Clearlake Oaks', 'state_id' => 3925],
                ['name' => 'Clearlake Park', 'state_id' => 3925],
                ['name' => 'Cobb', 'state_id' => 3925],
                ['name' => 'Finley', 'state_id' => 3925],
                ['name' => 'Glenhaven', 'state_id' => 3925],
                ['name' => 'Kelseyville', 'state_id' => 3925],
                ['name' => 'Lakeport', 'state_id' => 3925],
                ['name' => 'Lower Lake', 'state_id' => 3925],
                ['name' => 'Lucerne', 'state_id' => 3925],
                ['name' => 'Middletown', 'state_id' => 3925],
                ['name' => 'Nice', 'state_id' => 3925],
                ['name' => 'Hidden Valley Lake', 'state_id' => 3925],
                ['name' => 'Upper Lake', 'state_id' => 3925],
                ['name' => 'Witter Springs', 'state_id' => 3925],
                ['name' => 'Bieber', 'state_id' => 3925],
                ['name' => 'Nubieber', 'state_id' => 3925],
                ['name' => 'Doyle', 'state_id' => 3925],
                ['name' => 'Herlong', 'state_id' => 3925],
                ['name' => 'Janesville', 'state_id' => 3925],
                ['name' => 'Litchfield', 'state_id' => 3925],
                ['name' => 'Madeline', 'state_id' => 3925],
                ['name' => 'Milford', 'state_id' => 3925],
                ['name' => 'Ravendale', 'state_id' => 3925],
                ['name' => 'Susanville', 'state_id' => 3925],
                ['name' => 'Standish', 'state_id' => 3925],
                ['name' => 'Termo', 'state_id' => 3925],
                ['name' => 'Wendel', 'state_id' => 3925],
                ['name' => 'Westwood', 'state_id' => 3925],
                ['name' => 'Los Angeles', 'state_id' => 3925],
                ['name' => 'West Hollywood', 'state_id' => 3925],
                ['name' => 'Dodgertown', 'state_id' => 3925],
                ['name' => 'Playa Vista', 'state_id' => 3925],
                ['name' => 'Bell Gardens', 'state_id' => 3925],
                ['name' => 'Bell', 'state_id' => 3925],
                ['name' => 'Beverly Hills', 'state_id' => 3925],
                ['name' => 'Compton', 'state_id' => 3925],
                ['name' => 'Culver City', 'state_id' => 3925],
                ['name' => 'Downey', 'state_id' => 3925],
                ['name' => 'El Segundo', 'state_id' => 3925],
                ['name' => 'Gardena', 'state_id' => 3925],
                ['name' => 'Hawthorne', 'state_id' => 3925],
                ['name' => 'Hermosa Beach', 'state_id' => 3925],
                ['name' => 'Huntington Park', 'state_id' => 3925],
                ['name' => 'Lawndale', 'state_id' => 3925],
                ['name' => 'Lynwood', 'state_id' => 3925],
                ['name' => 'Malibu', 'state_id' => 3925],
                ['name' => 'Manhattan Beach', 'state_id' => 3925],
                ['name' => 'Maywood', 'state_id' => 3925],
                ['name' => 'Pacific Palisades', 'state_id' => 3925],
                ['name' => 'Palos Verdes Peninsula', 'state_id' => 3925],
                ['name' => 'Rancho Palos Verdes', 'state_id' => 3925],
                ['name' => 'Redondo Beach', 'state_id' => 3925],
                ['name' => 'South Gate', 'state_id' => 3925],
                ['name' => 'Topanga', 'state_id' => 3925],
                ['name' => 'Venice', 'state_id' => 3925],
                ['name' => 'Marina Del Rey', 'state_id' => 3925],
                ['name' => 'Playa Del Rey', 'state_id' => 3925],
                ['name' => 'Inglewood', 'state_id' => 3925],
                ['name' => 'Santa Monica', 'state_id' => 3925],
                ['name' => 'Torrance', 'state_id' => 3925],
                ['name' => 'Whittier', 'state_id' => 3925],
                ['name' => 'La Mirada', 'state_id' => 3925],
                ['name' => 'Montebello', 'state_id' => 3925],
                ['name' => 'Norwalk', 'state_id' => 3925],
                ['name' => 'Pico Rivera', 'state_id' => 3925],
                ['name' => 'Santa Fe Springs', 'state_id' => 3925],
                ['name' => 'Artesia', 'state_id' => 3925],
                ['name' => 'Cerritos', 'state_id' => 3925],
                ['name' => 'Avalon', 'state_id' => 3925],
                ['name' => 'Bellflower', 'state_id' => 3925],
                ['name' => 'Harbor City', 'state_id' => 3925],
                ['name' => 'Lakewood', 'state_id' => 3925],
                ['name' => 'Hawaiian Gardens', 'state_id' => 3925],
                ['name' => 'Lomita', 'state_id' => 3925],
                ['name' => 'Paramount', 'state_id' => 3925],
                ['name' => 'San Pedro', 'state_id' => 3925],
                ['name' => 'Wilmington', 'state_id' => 3925],
                ['name' => 'Carson', 'state_id' => 3925],
                ['name' => 'Signal Hill', 'state_id' => 3925],
                ['name' => 'Long Beach', 'state_id' => 3925],
                ['name' => 'Altadena', 'state_id' => 3925],
                ['name' => 'Arcadia', 'state_id' => 3925],
                ['name' => 'Duarte', 'state_id' => 3925],
                ['name' => 'La Canada Flintridge', 'state_id' => 3925],
                ['name' => 'Monrovia', 'state_id' => 3925],
                ['name' => 'Montrose', 'state_id' => 3925],
                ['name' => 'Mount Wilson', 'state_id' => 3925],
                ['name' => 'Sierra Madre', 'state_id' => 3925],
                ['name' => 'South Pasadena', 'state_id' => 3925],
                ['name' => 'Sunland', 'state_id' => 3925],
                ['name' => 'Tujunga', 'state_id' => 3925],
                ['name' => 'Verdugo City', 'state_id' => 3925],
                ['name' => 'Pasadena', 'state_id' => 3925],
                ['name' => 'San Marino', 'state_id' => 3925],
                ['name' => 'Glendale', 'state_id' => 3925],
                ['name' => 'La Crescenta', 'state_id' => 3925],
                ['name' => 'Agoura Hills', 'state_id' => 3925],
                ['name' => 'Calabasas', 'state_id' => 3925],
                ['name' => 'Canoga Park', 'state_id' => 3925],
                ['name' => 'Winnetka', 'state_id' => 3925],
                ['name' => 'West Hills', 'state_id' => 3925],
                ['name' => 'Castaic', 'state_id' => 3925],
                ['name' => 'Chatsworth', 'state_id' => 3925],
                ['name' => 'Encino', 'state_id' => 3925],
                ['name' => 'Newhall', 'state_id' => 3925],
                ['name' => 'Northridge', 'state_id' => 3925],
                ['name' => 'Porter Ranch', 'state_id' => 3925],
                ['name' => 'Pacoima', 'state_id' => 3925],
                ['name' => 'Reseda', 'state_id' => 3925],
                ['name' => 'San Fernando', 'state_id' => 3925],
                ['name' => 'Sylmar', 'state_id' => 3925],
                ['name' => 'North Hills', 'state_id' => 3925],
                ['name' => 'Granada Hills', 'state_id' => 3925],
                ['name' => 'Mission Hills', 'state_id' => 3925],
                ['name' => 'Santa Clarita', 'state_id' => 3925],
                ['name' => 'Canyon Country', 'state_id' => 3925],
                ['name' => 'Sun Valley', 'state_id' => 3925],
                ['name' => 'Valencia', 'state_id' => 3925],
                ['name' => 'Tarzana', 'state_id' => 3925],
                ['name' => 'Woodland Hills', 'state_id' => 3925],
                ['name' => 'Stevenson Ranch', 'state_id' => 3925],
                ['name' => 'Van Nuys', 'state_id' => 3925],
                ['name' => 'Panorama City', 'state_id' => 3925],
                ['name' => 'Sherman Oaks', 'state_id' => 3925],
                ['name' => 'Burbank', 'state_id' => 3925],
                ['name' => 'North Hollywood', 'state_id' => 3925],
                ['name' => 'Studio City', 'state_id' => 3925],
                ['name' => 'Valley Village', 'state_id' => 3925],
                ['name' => 'Universal City', 'state_id' => 3925],
                ['name' => 'Toluca Lake', 'state_id' => 3925],
                ['name' => 'Azusa', 'state_id' => 3925],
                ['name' => 'Baldwin Park', 'state_id' => 3925],
                ['name' => 'Claremont', 'state_id' => 3925],
                ['name' => 'City Of Industry', 'state_id' => 3925],
                ['name' => 'Covina', 'state_id' => 3925],
                ['name' => 'El Monte', 'state_id' => 3925],
                ['name' => 'South El Monte', 'state_id' => 3925],
                ['name' => 'Glendora', 'state_id' => 3925],
                ['name' => 'La Puente', 'state_id' => 3925],
                ['name' => 'Hacienda Heights', 'state_id' => 3925],
                ['name' => 'Rowland Heights', 'state_id' => 3925],
                ['name' => 'La Verne', 'state_id' => 3925],
                ['name' => 'Monterey Park', 'state_id' => 3925],
                ['name' => 'Mt Baldy', 'state_id' => 3925],
                ['name' => 'Diamond Bar', 'state_id' => 3925],
                ['name' => 'Pomona', 'state_id' => 3925],
                ['name' => 'Rosemead', 'state_id' => 3925],
                ['name' => 'San Dimas', 'state_id' => 3925],
                ['name' => 'San Gabriel', 'state_id' => 3925],
                ['name' => 'Temple City', 'state_id' => 3925],
                ['name' => 'Walnut', 'state_id' => 3925],
                ['name' => 'West Covina', 'state_id' => 3925],
                ['name' => 'Alhambra', 'state_id' => 3925],
                ['name' => 'Acton', 'state_id' => 3925],
                ['name' => 'Lake Hughes', 'state_id' => 3925],
                ['name' => 'Lancaster', 'state_id' => 3925],
                ['name' => 'Littlerock', 'state_id' => 3925],
                ['name' => 'Llano', 'state_id' => 3925],
                ['name' => 'Palmdale', 'state_id' => 3925],
                ['name' => 'Pearblossom', 'state_id' => 3925],
                ['name' => 'Valyermo', 'state_id' => 3925],
                ['name' => 'Ahwahnee', 'state_id' => 3925],
                ['name' => 'Bass Lake', 'state_id' => 3925],
                ['name' => 'Chowchilla', 'state_id' => 3925],
                ['name' => 'Coarsegold', 'state_id' => 3925],
                ['name' => 'Madera', 'state_id' => 3925],
                ['name' => 'North Fork', 'state_id' => 3925],
                ['name' => 'Oakhurst', 'state_id' => 3925],
                ['name' => 'O Neals', 'state_id' => 3925],
                ['name' => 'Raymond', 'state_id' => 3925],
                ['name' => 'Wishon', 'state_id' => 3925],
                ['name' => 'San Rafael', 'state_id' => 3925],
                ['name' => 'Greenbrae', 'state_id' => 3925],
                ['name' => 'Kentfield', 'state_id' => 3925],
                ['name' => 'Belvedere Tiburon', 'state_id' => 3925],
                ['name' => 'Bolinas', 'state_id' => 3925],
                ['name' => 'Corte Madera', 'state_id' => 3925],
                ['name' => 'Dillon Beach', 'state_id' => 3925],
                ['name' => 'Fairfax', 'state_id' => 3925],
                ['name' => 'Forest Knolls', 'state_id' => 3925],
                ['name' => 'Inverness', 'state_id' => 3925],
                ['name' => 'Lagunitas', 'state_id' => 3925],
                ['name' => 'Larkspur', 'state_id' => 3925],
                ['name' => 'Marshall', 'state_id' => 3925],
                ['name' => 'Mill Valley', 'state_id' => 3925],
                ['name' => 'Novato', 'state_id' => 3925],
                ['name' => 'Nicasio', 'state_id' => 3925],
                ['name' => 'Olema', 'state_id' => 3925],
                ['name' => 'Point Reyes Station', 'state_id' => 3925],
                ['name' => 'Ross', 'state_id' => 3925],
                ['name' => 'San Anselmo', 'state_id' => 3925],
                ['name' => 'San Geronimo', 'state_id' => 3925],
                ['name' => 'San Quentin', 'state_id' => 3925],
                ['name' => 'Sausalito', 'state_id' => 3925],
                ['name' => 'Stinson Beach', 'state_id' => 3925],
                ['name' => 'Tomales', 'state_id' => 3925],
                ['name' => 'Woodacre', 'state_id' => 3925],
                ['name' => 'Fish Camp', 'state_id' => 3925],
                ['name' => 'Catheys Valley', 'state_id' => 3925],
                ['name' => 'Coulterville', 'state_id' => 3925],
                ['name' => 'El Portal', 'state_id' => 3925],
                ['name' => 'Hornitos', 'state_id' => 3925],
                ['name' => 'Mariposa', 'state_id' => 3925],
                ['name' => 'Midpines', 'state_id' => 3925],
                ['name' => 'Yosemite National Park', 'state_id' => 3925],
                ['name' => 'Albion', 'state_id' => 3925],
                ['name' => 'Boonville', 'state_id' => 3925],
                ['name' => 'Branscomb', 'state_id' => 3925],
                ['name' => 'Calpella', 'state_id' => 3925],
                ['name' => 'Caspar', 'state_id' => 3925],
                ['name' => 'Comptche', 'state_id' => 3925],
                ['name' => 'Covelo', 'state_id' => 3925],
                ['name' => 'Dos Rios', 'state_id' => 3925],
                ['name' => 'Elk', 'state_id' => 3925],
                ['name' => 'Fort Bragg', 'state_id' => 3925],
                ['name' => 'Gualala', 'state_id' => 3925],
                ['name' => 'Hopland', 'state_id' => 3925],
                ['name' => 'Laytonville', 'state_id' => 3925],
                ['name' => 'Little River', 'state_id' => 3925],
                ['name' => 'Manchester', 'state_id' => 3925],
                ['name' => 'Mendocino', 'state_id' => 3925],
                ['name' => 'Navarro', 'state_id' => 3925],
                ['name' => 'Philo', 'state_id' => 3925],
                ['name' => 'Point Arena', 'state_id' => 3925],
                ['name' => 'Potter Valley', 'state_id' => 3925],
                ['name' => 'Redwood Valley', 'state_id' => 3925],
                ['name' => 'Talmage', 'state_id' => 3925],
                ['name' => 'Ukiah', 'state_id' => 3925],
                ['name' => 'Westport', 'state_id' => 3925],
                ['name' => 'Willits', 'state_id' => 3925],
                ['name' => 'Yorkville', 'state_id' => 3925],
                ['name' => 'Leggett', 'state_id' => 3925],
                ['name' => 'Piercy', 'state_id' => 3925],
                ['name' => 'Dos Palos', 'state_id' => 3925],
                ['name' => 'Los Banos', 'state_id' => 3925],
                ['name' => 'Santa Rita Park', 'state_id' => 3925],
                ['name' => 'South Dos Palos', 'state_id' => 3925],
                ['name' => 'Atwater', 'state_id' => 3925],
                ['name' => 'Ballico', 'state_id' => 3925],
                ['name' => 'Cressey', 'state_id' => 3925],
                ['name' => 'Delhi', 'state_id' => 3925],
                ['name' => 'El Nido', 'state_id' => 3925],
                ['name' => 'Gustine', 'state_id' => 3925],
                ['name' => 'Hilmar', 'state_id' => 3925],
                ['name' => 'Le Grand', 'state_id' => 3925],
                ['name' => 'Livingston', 'state_id' => 3925],
                ['name' => 'Merced', 'state_id' => 3925],
                ['name' => 'Planada', 'state_id' => 3925],
                ['name' => 'Snelling', 'state_id' => 3925],
                ['name' => 'Stevinson', 'state_id' => 3925],
                ['name' => 'Winton', 'state_id' => 3925],
                ['name' => 'Adin', 'state_id' => 3925],
                ['name' => 'Canby', 'state_id' => 3925],
                ['name' => 'Lookout', 'state_id' => 3925],
                ['name' => 'Alturas', 'state_id' => 3925],
                ['name' => 'Cedarville', 'state_id' => 3925],
                ['name' => 'Davis Creek', 'state_id' => 3925],
                ['name' => 'Eagleville', 'state_id' => 3925],
                ['name' => 'Fort Bidwell', 'state_id' => 3925],
                ['name' => 'Lake City', 'state_id' => 3925],
                ['name' => 'Likely', 'state_id' => 3925],
                ['name' => 'Benton', 'state_id' => 3925],
                ['name' => 'Bridgeport', 'state_id' => 3925],
                ['name' => 'June Lake', 'state_id' => 3925],
                ['name' => 'Lee Vining', 'state_id' => 3925],
                ['name' => 'Mammoth Lakes', 'state_id' => 3925],
                ['name' => 'Coleville', 'state_id' => 3925],
                ['name' => 'Topaz', 'state_id' => 3925],
                ['name' => 'Bradley', 'state_id' => 3925],
                ['name' => 'San Ardo', 'state_id' => 3925],
                ['name' => 'Salinas', 'state_id' => 3925],
                ['name' => 'Big Sur', 'state_id' => 3925],
                ['name' => 'Carmel By The Sea', 'state_id' => 3925],
                ['name' => 'Carmel', 'state_id' => 3925],
                ['name' => 'Carmel Valley', 'state_id' => 3925],
                ['name' => 'Chualar', 'state_id' => 3925],
                ['name' => 'Gonzales', 'state_id' => 3925],
                ['name' => 'Greenfield', 'state_id' => 3925],
                ['name' => 'Jolon', 'state_id' => 3925],
                ['name' => 'King City', 'state_id' => 3925],
                ['name' => 'Lockwood', 'state_id' => 3925],
                ['name' => 'Marina', 'state_id' => 3925],
                ['name' => 'Monterey', 'state_id' => 3925],
                ['name' => 'Pacific Grove', 'state_id' => 3925],
                ['name' => 'Pebble Beach', 'state_id' => 3925],
                ['name' => 'San Lucas', 'state_id' => 3925],
                ['name' => 'Seaside', 'state_id' => 3925],
                ['name' => 'Soledad', 'state_id' => 3925],
                ['name' => 'Spreckels', 'state_id' => 3925],
                ['name' => 'Aromas', 'state_id' => 3925],
                ['name' => 'Castroville', 'state_id' => 3925],
                ['name' => 'Moss Landing', 'state_id' => 3925],
                ['name' => 'American Canyon', 'state_id' => 3925],
                ['name' => 'Angwin', 'state_id' => 3925],
                ['name' => 'Calistoga', 'state_id' => 3925],
                ['name' => 'Napa', 'state_id' => 3925],
                ['name' => 'Oakville', 'state_id' => 3925],
                ['name' => 'Pope Valley', 'state_id' => 3925],
                ['name' => 'Rutherford', 'state_id' => 3925],
                ['name' => 'Saint Helena', 'state_id' => 3925],
                ['name' => 'Deer Park', 'state_id' => 3925],
                ['name' => 'Yountville', 'state_id' => 3925],
                ['name' => 'Chicago Park', 'state_id' => 3925],
                ['name' => 'Norden', 'state_id' => 3925],
                ['name' => 'Soda Springs', 'state_id' => 3925],
                ['name' => 'Cedar Ridge', 'state_id' => 3925],
                ['name' => 'Grass Valley', 'state_id' => 3925],
                ['name' => 'Penn Valley', 'state_id' => 3925],
                ['name' => 'Nevada City', 'state_id' => 3925],
                ['name' => 'North San Juan', 'state_id' => 3925],
                ['name' => 'Rough And Ready', 'state_id' => 3925],
                ['name' => 'Smartsville', 'state_id' => 3925],
                ['name' => 'Washington', 'state_id' => 3925],
                ['name' => 'Floriston', 'state_id' => 3925],
                ['name' => 'Truckee', 'state_id' => 3925],
                ['name' => 'Buena Park', 'state_id' => 3925],
                ['name' => 'La Palma', 'state_id' => 3925],
                ['name' => 'Cypress', 'state_id' => 3925],
                ['name' => 'La Habra', 'state_id' => 3925],
                ['name' => 'Stanton', 'state_id' => 3925],
                ['name' => 'Los Alamitos', 'state_id' => 3925],
                ['name' => 'Seal Beach', 'state_id' => 3925],
                ['name' => 'Sunset Beach', 'state_id' => 3925],
                ['name' => 'Surfside', 'state_id' => 3925],
                ['name' => 'Irvine', 'state_id' => 3925],
                ['name' => 'Huntington Beach', 'state_id' => 3925],
                ['name' => 'Laguna Niguel', 'state_id' => 3925],
                ['name' => 'El Toro', 'state_id' => 3925],
                ['name' => 'Foothill Ranch', 'state_id' => 3925],
                ['name' => 'Capistrano Beach', 'state_id' => 3925],
                ['name' => 'Corona Del Mar', 'state_id' => 3925],
                ['name' => 'Costa Mesa', 'state_id' => 3925],
                ['name' => 'Dana Point', 'state_id' => 3925],
                ['name' => 'Lake Forest', 'state_id' => 3925],
                ['name' => 'Laguna Woods', 'state_id' => 3925],
                ['name' => 'East Irvine', 'state_id' => 3925],
                ['name' => 'Laguna Beach', 'state_id' => 3925],
                ['name' => 'Laguna Hills', 'state_id' => 3925],
                ['name' => 'Midway City', 'state_id' => 3925],
                ['name' => 'Aliso Viejo', 'state_id' => 3925],
                ['name' => 'Newport Coast', 'state_id' => 3925],
                ['name' => 'Newport Beach', 'state_id' => 3925],
                ['name' => 'San Clemente', 'state_id' => 3925],
                ['name' => 'San Juan Capistrano', 'state_id' => 3925],
                ['name' => 'Silverado', 'state_id' => 3925],
                ['name' => 'Trabuco Canyon', 'state_id' => 3925],
                ['name' => 'Westminster', 'state_id' => 3925],
                ['name' => 'Rancho Santa Margarita', 'state_id' => 3925],
                ['name' => 'Mission Viejo', 'state_id' => 3925],
                ['name' => 'Ladera Ranch', 'state_id' => 3925],
                ['name' => 'Santa Ana', 'state_id' => 3925],
                ['name' => 'Fountain Valley', 'state_id' => 3925],
                ['name' => 'Tustin', 'state_id' => 3925],
                ['name' => 'Anaheim', 'state_id' => 3925],
                ['name' => 'Atwood', 'state_id' => 3925],
                ['name' => 'Brea', 'state_id' => 3925],
                ['name' => 'Fullerton', 'state_id' => 3925],
                ['name' => 'Garden Grove', 'state_id' => 3925],
                ['name' => 'Orange', 'state_id' => 3925],
                ['name' => 'Villa Park', 'state_id' => 3925],
                ['name' => 'Placentia', 'state_id' => 3925],
                ['name' => 'Yorba Linda', 'state_id' => 3925],
                ['name' => 'Auburn', 'state_id' => 3925],
                ['name' => 'Foresthill', 'state_id' => 3925],
                ['name' => 'Lincoln', 'state_id' => 3925],
                ['name' => 'Loomis', 'state_id' => 3925],
                ['name' => 'Newcastle', 'state_id' => 3925],
                ['name' => 'Roseville', 'state_id' => 3925],
                ['name' => 'Penryn', 'state_id' => 3925],
                ['name' => 'Rocklin', 'state_id' => 3925],
                ['name' => 'Sheridan', 'state_id' => 3925],
                ['name' => 'Alta', 'state_id' => 3925],
                ['name' => 'Applegate', 'state_id' => 3925],
                ['name' => 'Colfax', 'state_id' => 3925],
                ['name' => 'Dutch Flat', 'state_id' => 3925],
                ['name' => 'Emigrant Gap', 'state_id' => 3925],
                ['name' => 'Gold Run', 'state_id' => 3925],
                ['name' => 'Meadow Vista', 'state_id' => 3925],
                ['name' => 'Weimar', 'state_id' => 3925],
                ['name' => 'Granite Bay', 'state_id' => 3925],
                ['name' => 'Carnelian Bay', 'state_id' => 3925],
                ['name' => 'Homewood', 'state_id' => 3925],
                ['name' => 'Kings Beach', 'state_id' => 3925],
                ['name' => 'Tahoe City', 'state_id' => 3925],
                ['name' => 'Olympic Valley', 'state_id' => 3925],
                ['name' => 'Tahoe Vista', 'state_id' => 3925],
                ['name' => 'Belden', 'state_id' => 3925],
                ['name' => 'Canyon Dam', 'state_id' => 3925],
                ['name' => 'Crescent Mills', 'state_id' => 3925],
                ['name' => 'Greenville', 'state_id' => 3925],
                ['name' => 'Meadow Valley', 'state_id' => 3925],
                ['name' => 'Quincy', 'state_id' => 3925],
                ['name' => 'Storrie', 'state_id' => 3925],
                ['name' => 'Taylorsville', 'state_id' => 3925],
                ['name' => 'Twain', 'state_id' => 3925],
                ['name' => 'Chester', 'state_id' => 3925],
                ['name' => 'Blairsden Graeagle', 'state_id' => 3925],
                ['name' => 'Chilcoot', 'state_id' => 3925],
                ['name' => 'Clio', 'state_id' => 3925],
                ['name' => 'Portola', 'state_id' => 3925],
                ['name' => 'Beckwourth', 'state_id' => 3925],
                ['name' => 'Vinton', 'state_id' => 3925],
                ['name' => 'Mira Loma', 'state_id' => 3925],
                ['name' => 'Indio', 'state_id' => 3925],
                ['name' => 'Indian Wells', 'state_id' => 3925],
                ['name' => 'Palm Desert', 'state_id' => 3925],
                ['name' => 'Banning', 'state_id' => 3925],
                ['name' => 'Beaumont', 'state_id' => 3925],
                ['name' => 'Blythe', 'state_id' => 3925],
                ['name' => 'Cabazon', 'state_id' => 3925],
                ['name' => 'Cathedral City', 'state_id' => 3925],
                ['name' => 'Coachella', 'state_id' => 3925],
                ['name' => 'Desert Center', 'state_id' => 3925],
                ['name' => 'Desert Hot Springs', 'state_id' => 3925],
                ['name' => 'La Quinta', 'state_id' => 3925],
                ['name' => 'Mecca', 'state_id' => 3925],
                ['name' => 'North Palm Springs', 'state_id' => 3925],
                ['name' => 'Palm Springs', 'state_id' => 3925],
                ['name' => 'Rancho Mirage', 'state_id' => 3925],
                ['name' => 'Thermal', 'state_id' => 3925],
                ['name' => 'Thousand Palms', 'state_id' => 3925],
                ['name' => 'Whitewater', 'state_id' => 3925],
                ['name' => 'Calimesa', 'state_id' => 3925],
                ['name' => 'Riverside', 'state_id' => 3925],
                ['name' => 'March Air Reserve Base', 'state_id' => 3925],
                ['name' => 'Lake Elsinore', 'state_id' => 3925],
                ['name' => 'Aguanga', 'state_id' => 3925],
                ['name' => 'Anza', 'state_id' => 3925],
                ['name' => 'Hemet', 'state_id' => 3925],
                ['name' => 'Homeland', 'state_id' => 3925],
                ['name' => 'Idyllwild', 'state_id' => 3925],
                ['name' => 'Moreno Valley', 'state_id' => 3925],
                ['name' => 'Mountain Center', 'state_id' => 3925],
                ['name' => 'Murrieta', 'state_id' => 3925],
                ['name' => 'Nuevo', 'state_id' => 3925],
                ['name' => 'Perris', 'state_id' => 3925],
                ['name' => 'San Jacinto', 'state_id' => 3925],
                ['name' => 'Menifee', 'state_id' => 3925],
                ['name' => 'Sun City', 'state_id' => 3925],
                ['name' => 'Quail Valley', 'state_id' => 3925],
                ['name' => 'Temecula', 'state_id' => 3925],
                ['name' => 'Wildomar', 'state_id' => 3925],
                ['name' => 'Winchester', 'state_id' => 3925],
                ['name' => 'Norco', 'state_id' => 3925],
                ['name' => 'Corona', 'state_id' => 3925],
                ['name' => 'Sacramento', 'state_id' => 3925],
                ['name' => 'Carmichael', 'state_id' => 3925],
                ['name' => 'Citrus Heights', 'state_id' => 3925],
                ['name' => 'Courtland', 'state_id' => 3925],
                ['name' => 'Elk Grove', 'state_id' => 3925],
                ['name' => 'Elverta', 'state_id' => 3925],
                ['name' => 'Fair Oaks', 'state_id' => 3925],
                ['name' => 'Folsom', 'state_id' => 3925],
                ['name' => 'Galt', 'state_id' => 3925],
                ['name' => 'Herald', 'state_id' => 3925],
                ['name' => 'Hood', 'state_id' => 3925],
                ['name' => 'Isleton', 'state_id' => 3925],
                ['name' => 'Mcclellan', 'state_id' => 3925],
                ['name' => 'Mather', 'state_id' => 3925],
                ['name' => 'North Highlands', 'state_id' => 3925],
                ['name' => 'Orangevale', 'state_id' => 3925],
                ['name' => 'Rancho Cordova', 'state_id' => 3925],
                ['name' => 'Represa', 'state_id' => 3925],
                ['name' => 'Rio Linda', 'state_id' => 3925],
                ['name' => 'Ryde', 'state_id' => 3925],
                ['name' => 'Sloughhouse', 'state_id' => 3925],
                ['name' => 'Walnut Grove', 'state_id' => 3925],
                ['name' => 'Wilton', 'state_id' => 3925],
                ['name' => 'Antelope', 'state_id' => 3925],
                ['name' => 'Hollister', 'state_id' => 3925],
                ['name' => 'Paicines', 'state_id' => 3925],
                ['name' => 'San Juan Bautista', 'state_id' => 3925],
                ['name' => 'Tres Pinos', 'state_id' => 3925],
                ['name' => 'Rancho Cucamonga', 'state_id' => 3925],
                ['name' => 'Chino', 'state_id' => 3925],
                ['name' => 'Chino Hills', 'state_id' => 3925],
                ['name' => 'Guasti', 'state_id' => 3925],
                ['name' => 'Ontario', 'state_id' => 3925],
                ['name' => 'Montclair', 'state_id' => 3925],
                ['name' => 'Upland', 'state_id' => 3925],
                ['name' => 'Earp', 'state_id' => 3925],
                ['name' => 'Joshua Tree', 'state_id' => 3925],
                ['name' => 'Morongo Valley', 'state_id' => 3925],
                ['name' => 'Parker Dam', 'state_id' => 3925],
                ['name' => 'Pioneertown', 'state_id' => 3925],
                ['name' => 'Twentynine Palms', 'state_id' => 3925],
                ['name' => 'Vidal', 'state_id' => 3925],
                ['name' => 'Yucca Valley', 'state_id' => 3925],
                ['name' => 'Landers', 'state_id' => 3925],
                ['name' => 'Adelanto', 'state_id' => 3925],
                ['name' => 'Amboy', 'state_id' => 3925],
                ['name' => 'Angelus Oaks', 'state_id' => 3925],
                ['name' => 'Apple Valley', 'state_id' => 3925],
                ['name' => 'Baker', 'state_id' => 3925],
                ['name' => 'Fort Irwin', 'state_id' => 3925],
                ['name' => 'Barstow', 'state_id' => 3925],
                ['name' => 'Grand Terrace', 'state_id' => 3925],
                ['name' => 'Big Bear City', 'state_id' => 3925],
                ['name' => 'Big Bear Lake', 'state_id' => 3925],
                ['name' => 'Bloomington', 'state_id' => 3925],
                ['name' => 'Blue Jay', 'state_id' => 3925],
                ['name' => 'Bryn Mawr', 'state_id' => 3925],
                ['name' => 'Cedar Glen', 'state_id' => 3925],
                ['name' => 'Cedarpines Park', 'state_id' => 3925],
                ['name' => 'Cima', 'state_id' => 3925],
                ['name' => 'Colton', 'state_id' => 3925],
                ['name' => 'Crestline', 'state_id' => 3925],
                ['name' => 'Daggett', 'state_id' => 3925],
                ['name' => 'Phelan', 'state_id' => 3925],
                ['name' => 'Essex', 'state_id' => 3925],
                ['name' => 'Fawnskin', 'state_id' => 3925],
                ['name' => 'Ludlow', 'state_id' => 3925],
                ['name' => 'Forest Falls', 'state_id' => 3925],
                ['name' => 'Hesperia', 'state_id' => 3925],
                ['name' => 'Green Valley Lake', 'state_id' => 3925],
                ['name' => 'Helendale', 'state_id' => 3925],
                ['name' => 'Highland', 'state_id' => 3925],
                ['name' => 'Hinkley', 'state_id' => 3925],
                ['name' => 'Loma Linda', 'state_id' => 3925],
                ['name' => 'Lake Arrowhead', 'state_id' => 3925],
                ['name' => 'Lucerne Valley', 'state_id' => 3925],
                ['name' => 'Lytle Creek', 'state_id' => 3925],
                ['name' => 'Mentone', 'state_id' => 3925],
                ['name' => 'Needles', 'state_id' => 3925],
                ['name' => 'Nipton', 'state_id' => 3925],
                ['name' => 'Newberry Springs', 'state_id' => 3925],
                ['name' => 'Mountain Pass', 'state_id' => 3925],
                ['name' => 'Oro Grande', 'state_id' => 3925],
                ['name' => 'Patton', 'state_id' => 3925],
                ['name' => 'Pinon Hills', 'state_id' => 3925],
                ['name' => 'Redlands', 'state_id' => 3925],
                ['name' => 'Rialto', 'state_id' => 3925],
                ['name' => 'Rimforest', 'state_id' => 3925],
                ['name' => 'Running Springs', 'state_id' => 3925],
                ['name' => 'Skyforest', 'state_id' => 3925],
                ['name' => 'Sugarloaf', 'state_id' => 3925],
                ['name' => 'Twin Peaks', 'state_id' => 3925],
                ['name' => 'Victorville', 'state_id' => 3925],
                ['name' => 'Wrightwood', 'state_id' => 3925],
                ['name' => 'Yermo', 'state_id' => 3925],
                ['name' => 'Yucaipa', 'state_id' => 3925],
                ['name' => 'San Bernardino', 'state_id' => 3925],
                ['name' => 'Red Mountain', 'state_id' => 3925],
                ['name' => 'Trona', 'state_id' => 3925],
                ['name' => 'Alpine', 'state_id' => 3925],
                ['name' => 'Bonita', 'state_id' => 3925],
                ['name' => 'Boulevard', 'state_id' => 3925],
                ['name' => 'Campo', 'state_id' => 3925],
                ['name' => 'Chula Vista', 'state_id' => 3925],
                ['name' => 'Descanso', 'state_id' => 3925],
                ['name' => 'Dulzura', 'state_id' => 3925],
                ['name' => 'Guatay', 'state_id' => 3925],
                ['name' => 'Imperial Beach', 'state_id' => 3925],
                ['name' => 'Jacumba', 'state_id' => 3925],
                ['name' => 'Jamul', 'state_id' => 3925],
                ['name' => 'La Mesa', 'state_id' => 3925],
                ['name' => 'Lemon Grove', 'state_id' => 3925],
                ['name' => 'Mount Laguna', 'state_id' => 3925],
                ['name' => 'National City', 'state_id' => 3925],
                ['name' => 'Pine Valley', 'state_id' => 3925],
                ['name' => 'Potrero', 'state_id' => 3925],
                ['name' => 'Spring Valley', 'state_id' => 3925],
                ['name' => 'Tecate', 'state_id' => 3925],
                ['name' => 'Bonsall', 'state_id' => 3925],
                ['name' => 'Borrego Springs', 'state_id' => 3925],
                ['name' => 'Cardiff By The Sea', 'state_id' => 3925],
                ['name' => 'Carlsbad', 'state_id' => 3925],
                ['name' => 'Del Mar', 'state_id' => 3925],
                ['name' => 'El Cajon', 'state_id' => 3925],
                ['name' => 'Encinitas', 'state_id' => 3925],
                ['name' => 'Escondido', 'state_id' => 3925],
                ['name' => 'Fallbrook', 'state_id' => 3925],
                ['name' => 'Julian', 'state_id' => 3925],
                ['name' => 'La Jolla', 'state_id' => 3925],
                ['name' => 'Lakeside', 'state_id' => 3925],
                ['name' => 'Oceanside', 'state_id' => 3925],
                ['name' => 'Camp Pendleton', 'state_id' => 3925],
                ['name' => 'Pala', 'state_id' => 3925],
                ['name' => 'Palomar Mountain', 'state_id' => 3925],
                ['name' => 'Pauma Valley', 'state_id' => 3925],
                ['name' => 'Poway', 'state_id' => 3925],
                ['name' => 'Ramona', 'state_id' => 3925],
                ['name' => 'Ranchita', 'state_id' => 3925],
                ['name' => 'Rancho Santa Fe', 'state_id' => 3925],
                ['name' => 'San Luis Rey', 'state_id' => 3925],
                ['name' => 'San Marcos', 'state_id' => 3925],
                ['name' => 'Santa Ysabel', 'state_id' => 3925],
                ['name' => 'Santee', 'state_id' => 3925],
                ['name' => 'Solana Beach', 'state_id' => 3925],
                ['name' => 'Vista', 'state_id' => 3925],
                ['name' => 'Valley Center', 'state_id' => 3925],
                ['name' => 'Warner Springs', 'state_id' => 3925],
                ['name' => 'San Diego', 'state_id' => 3925],
                ['name' => 'Coronado', 'state_id' => 3925],
                ['name' => 'San Ysidro', 'state_id' => 3925],
                ['name' => 'San Francisco', 'state_id' => 3925],
                ['name' => 'Stockton', 'state_id' => 3925],
                ['name' => 'Acampo', 'state_id' => 3925],
                ['name' => 'Clements', 'state_id' => 3925],
                ['name' => 'Farmington', 'state_id' => 3925],
                ['name' => 'French Camp', 'state_id' => 3925],
                ['name' => 'Holt', 'state_id' => 3925],
                ['name' => 'Linden', 'state_id' => 3925],
                ['name' => 'Lockeford', 'state_id' => 3925],
                ['name' => 'Lodi', 'state_id' => 3925],
                ['name' => 'Victor', 'state_id' => 3925],
                ['name' => 'Woodbridge', 'state_id' => 3925],
                ['name' => 'Tracy', 'state_id' => 3925],
                ['name' => 'Escalon', 'state_id' => 3925],
                ['name' => 'Lathrop', 'state_id' => 3925],
                ['name' => 'Manteca', 'state_id' => 3925],
                ['name' => 'Ripon', 'state_id' => 3925],
                ['name' => 'Vernalis', 'state_id' => 3925],
                ['name' => 'Thornton', 'state_id' => 3925],
                ['name' => 'San Luis Obispo', 'state_id' => 3925],
                ['name' => 'Los Osos', 'state_id' => 3925],
                ['name' => 'Arroyo Grande', 'state_id' => 3925],
                ['name' => 'Atascadero', 'state_id' => 3925],
                ['name' => 'Avila Beach', 'state_id' => 3925],
                ['name' => 'Cambria', 'state_id' => 3925],
                ['name' => 'Cayucos', 'state_id' => 3925],
                ['name' => 'Creston', 'state_id' => 3925],
                ['name' => 'Grover Beach', 'state_id' => 3925],
                ['name' => 'Harmony', 'state_id' => 3925],
                ['name' => 'Morro Bay', 'state_id' => 3925],
                ['name' => 'Nipomo', 'state_id' => 3925],
                ['name' => 'Oceano', 'state_id' => 3925],
                ['name' => 'Paso Robles', 'state_id' => 3925],
                ['name' => 'Pismo Beach', 'state_id' => 3925],
                ['name' => 'San Miguel', 'state_id' => 3925],
                ['name' => 'San Simeon', 'state_id' => 3925],
                ['name' => 'Santa Margarita', 'state_id' => 3925],
                ['name' => 'Shandon', 'state_id' => 3925],
                ['name' => 'Templeton', 'state_id' => 3925],
                ['name' => 'Belmont', 'state_id' => 3925],
                ['name' => 'Brisbane', 'state_id' => 3925],
                ['name' => 'Burlingame', 'state_id' => 3925],
                ['name' => 'Daly City', 'state_id' => 3925],
                ['name' => 'El Granada', 'state_id' => 3925],
                ['name' => 'Half Moon Bay', 'state_id' => 3925],
                ['name' => 'La Honda', 'state_id' => 3925],
                ['name' => 'Loma Mar', 'state_id' => 3925],
                ['name' => 'Menlo Park', 'state_id' => 3925],
                ['name' => 'Atherton', 'state_id' => 3925],
                ['name' => 'Portola Valley', 'state_id' => 3925],
                ['name' => 'Millbrae', 'state_id' => 3925],
                ['name' => 'Montara', 'state_id' => 3925],
                ['name' => 'Moss Beach', 'state_id' => 3925],
                ['name' => 'Pacifica', 'state_id' => 3925],
                ['name' => 'Pescadero', 'state_id' => 3925],
                ['name' => 'Redwood City', 'state_id' => 3925],
                ['name' => 'San Bruno', 'state_id' => 3925],
                ['name' => 'San Carlos', 'state_id' => 3925],
                ['name' => 'San Gregorio', 'state_id' => 3925],
                ['name' => 'South San Francisco', 'state_id' => 3925],
                ['name' => 'Palo Alto', 'state_id' => 3925],
                ['name' => 'San Mateo', 'state_id' => 3925],
                ['name' => 'Carpinteria', 'state_id' => 3925],
                ['name' => 'Summerland', 'state_id' => 3925],
                ['name' => 'Santa Barbara', 'state_id' => 3925],
                ['name' => 'Goleta', 'state_id' => 3925],
                ['name' => 'New Cuyama', 'state_id' => 3925],
                ['name' => 'Buellton', 'state_id' => 3925],
                ['name' => 'Casmalia', 'state_id' => 3925],
                ['name' => 'Guadalupe', 'state_id' => 3925],
                ['name' => 'Lompoc', 'state_id' => 3925],
                ['name' => 'Los Alamos', 'state_id' => 3925],
                ['name' => 'Los Olivos', 'state_id' => 3925],
                ['name' => 'Santa Maria', 'state_id' => 3925],
                ['name' => 'Santa Ynez', 'state_id' => 3925],
                ['name' => 'Solvang', 'state_id' => 3925],
                ['name' => 'Los Altos', 'state_id' => 3925],
                ['name' => 'Mountain View', 'state_id' => 3925],
                ['name' => 'Sunnyvale', 'state_id' => 3925],
                ['name' => 'Stanford', 'state_id' => 3925],
                ['name' => 'Alviso', 'state_id' => 3925],
                ['name' => 'Campbell', 'state_id' => 3925],
                ['name' => 'Coyote', 'state_id' => 3925],
                ['name' => 'Cupertino', 'state_id' => 3925],
                ['name' => 'Gilroy', 'state_id' => 3925],
                ['name' => 'Holy City', 'state_id' => 3925],
                ['name' => 'Los Gatos', 'state_id' => 3925],
                ['name' => 'Milpitas', 'state_id' => 3925],
                ['name' => 'Morgan Hill', 'state_id' => 3925],
                ['name' => 'New Almaden', 'state_id' => 3925],
                ['name' => 'Redwood Estates', 'state_id' => 3925],
                ['name' => 'San Martin', 'state_id' => 3925],
                ['name' => 'Santa Clara', 'state_id' => 3925],
                ['name' => 'Saratoga', 'state_id' => 3925],
                ['name' => 'San Jose', 'state_id' => 3925],
                ['name' => 'Mount Hamilton', 'state_id' => 3925],
                ['name' => 'Aptos', 'state_id' => 3925],
                ['name' => 'Ben Lomond', 'state_id' => 3925],
                ['name' => 'Boulder Creek', 'state_id' => 3925],
                ['name' => 'Brookdale', 'state_id' => 3925],
                ['name' => 'Capitola', 'state_id' => 3925],
                ['name' => 'Davenport', 'state_id' => 3925],
                ['name' => 'Felton', 'state_id' => 3925],
                ['name' => 'Freedom', 'state_id' => 3925],
                ['name' => 'Mount Hermon', 'state_id' => 3925],
                ['name' => 'Santa Cruz', 'state_id' => 3925],
                ['name' => 'Scotts Valley', 'state_id' => 3925],
                ['name' => 'Soquel', 'state_id' => 3925],
                ['name' => 'Watsonville', 'state_id' => 3925],
                ['name' => 'Redding', 'state_id' => 3925],
                ['name' => 'Anderson', 'state_id' => 3925],
                ['name' => 'Bella Vista', 'state_id' => 3925],
                ['name' => 'Big Bend', 'state_id' => 3925],
                ['name' => 'Burney', 'state_id' => 3925],
                ['name' => 'Cassel', 'state_id' => 3925],
                ['name' => 'Castella', 'state_id' => 3925],
                ['name' => 'Shasta Lake', 'state_id' => 3925],
                ['name' => 'Cottonwood', 'state_id' => 3925],
                ['name' => 'Fall River Mills', 'state_id' => 3925],
                ['name' => 'French Gulch', 'state_id' => 3925],
                ['name' => 'Hat Creek', 'state_id' => 3925],
                ['name' => 'Igo', 'state_id' => 3925],
                ['name' => 'Lakehead', 'state_id' => 3925],
                ['name' => 'Mcarthur', 'state_id' => 3925],
                ['name' => 'Millville', 'state_id' => 3925],
                ['name' => 'Montgomery Creek', 'state_id' => 3925],
                ['name' => 'Oak Run', 'state_id' => 3925],
                ['name' => 'Obrien', 'state_id' => 3925],
                ['name' => 'Old Station', 'state_id' => 3925],
                ['name' => 'Palo Cedro', 'state_id' => 3925],
                ['name' => 'Platina', 'state_id' => 3925],
                ['name' => 'Round Mountain', 'state_id' => 3925],
                ['name' => 'Shasta', 'state_id' => 3925],
                ['name' => 'Shingletown', 'state_id' => 3925],
                ['name' => 'Whiskeytown', 'state_id' => 3925],
                ['name' => 'Whitmore', 'state_id' => 3925],
                ['name' => 'Alleghany', 'state_id' => 3925],
                ['name' => 'Downieville', 'state_id' => 3925],
                ['name' => 'Goodyears Bar', 'state_id' => 3925],
                ['name' => 'Loyalton', 'state_id' => 3925],
                ['name' => 'Calpine', 'state_id' => 3925],
                ['name' => 'Sierra City', 'state_id' => 3925],
                ['name' => 'Sierraville', 'state_id' => 3925],
                ['name' => 'Somes Bar', 'state_id' => 3925],
                ['name' => 'Callahan', 'state_id' => 3925],
                ['name' => 'Dorris', 'state_id' => 3925],
                ['name' => 'Dunsmuir', 'state_id' => 3925],
                ['name' => 'Etna', 'state_id' => 3925],
                ['name' => 'Forks Of Salmon', 'state_id' => 3925],
                ['name' => 'Fort Jones', 'state_id' => 3925],
                ['name' => 'Gazelle', 'state_id' => 3925],
                ['name' => 'Greenview', 'state_id' => 3925],
                ['name' => 'Grenada', 'state_id' => 3925],
                ['name' => 'Happy Camp', 'state_id' => 3925],
                ['name' => 'Hornbrook', 'state_id' => 3925],
                ['name' => 'Klamath River', 'state_id' => 3925],
                ['name' => 'Mccloud', 'state_id' => 3925],
                ['name' => 'Macdoel', 'state_id' => 3925],
                ['name' => 'Montague', 'state_id' => 3925],
                ['name' => 'Mount Shasta', 'state_id' => 3925],
                ['name' => 'Scott Bar', 'state_id' => 3925],
                ['name' => 'Seiad Valley', 'state_id' => 3925],
                ['name' => 'Weed', 'state_id' => 3925],
                ['name' => 'Yreka', 'state_id' => 3925],
                ['name' => 'Tulelake', 'state_id' => 3925],
                ['name' => 'Benicia', 'state_id' => 3925],
                ['name' => 'Birds Landing', 'state_id' => 3925],
                ['name' => 'Fairfield', 'state_id' => 3925],
                ['name' => 'Travis Afb', 'state_id' => 3925],
                ['name' => 'Rio Vista', 'state_id' => 3925],
                ['name' => 'Suisun City', 'state_id' => 3925],
                ['name' => 'Vallejo', 'state_id' => 3925],
                ['name' => 'Dixon', 'state_id' => 3925],
                ['name' => 'Elmira', 'state_id' => 3925],
                ['name' => 'Vacaville', 'state_id' => 3925],
                ['name' => 'Bodega', 'state_id' => 3925],
                ['name' => 'Bodega Bay', 'state_id' => 3925],
                ['name' => 'Rohnert Park', 'state_id' => 3925],
                ['name' => 'Cotati', 'state_id' => 3925],
                ['name' => 'Penngrove', 'state_id' => 3925],
                ['name' => 'Petaluma', 'state_id' => 3925],
                ['name' => 'Valley Ford', 'state_id' => 3925],
                ['name' => 'Santa Rosa', 'state_id' => 3925],
                ['name' => 'Annapolis', 'state_id' => 3925],
                ['name' => 'Boyes Hot Springs', 'state_id' => 3925],
                ['name' => 'Camp Meeker', 'state_id' => 3925],
                ['name' => 'Cazadero', 'state_id' => 3925],
                ['name' => 'Cloverdale', 'state_id' => 3925],
                ['name' => 'Duncans Mills', 'state_id' => 3925],
                ['name' => 'Eldridge', 'state_id' => 3925],
                ['name' => 'El Verano', 'state_id' => 3925],
                ['name' => 'Forestville', 'state_id' => 3925],
                ['name' => 'Fulton', 'state_id' => 3925],
                ['name' => 'Geyserville', 'state_id' => 3925],
                ['name' => 'Glen Ellen', 'state_id' => 3925],
                ['name' => 'Graton', 'state_id' => 3925],
                ['name' => 'Guerneville', 'state_id' => 3925],
                ['name' => 'Healdsburg', 'state_id' => 3925],
                ['name' => 'Jenner', 'state_id' => 3925],
                ['name' => 'Kenwood', 'state_id' => 3925],
                ['name' => 'Monte Rio', 'state_id' => 3925],
                ['name' => 'Occidental', 'state_id' => 3925],
                ['name' => 'Rio Nido', 'state_id' => 3925],
                ['name' => 'Sebastopol', 'state_id' => 3925],
                ['name' => 'Sonoma', 'state_id' => 3925],
                ['name' => 'Stewarts Point', 'state_id' => 3925],
                ['name' => 'Villa Grande', 'state_id' => 3925],
                ['name' => 'Vineburg', 'state_id' => 3925],
                ['name' => 'Windsor', 'state_id' => 3925],
                ['name' => 'The Sea Ranch', 'state_id' => 3925],
                ['name' => 'Ceres', 'state_id' => 3925],
                ['name' => 'Crows Landing', 'state_id' => 3925],
                ['name' => 'Denair', 'state_id' => 3925],
                ['name' => 'Empire', 'state_id' => 3925],
                ['name' => 'Hickman', 'state_id' => 3925],
                ['name' => 'Hughson', 'state_id' => 3925],
                ['name' => 'Keyes', 'state_id' => 3925],
                ['name' => 'La Grange', 'state_id' => 3925],
                ['name' => 'Modesto', 'state_id' => 3925],
                ['name' => 'Newman', 'state_id' => 3925],
                ['name' => 'Oakdale', 'state_id' => 3925],
                ['name' => 'Patterson', 'state_id' => 3925],
                ['name' => 'Riverbank', 'state_id' => 3925],
                ['name' => 'Salida', 'state_id' => 3925],
                ['name' => 'Turlock', 'state_id' => 3925],
                ['name' => 'Waterford', 'state_id' => 3925],
                ['name' => 'Westley', 'state_id' => 3925],
                ['name' => 'Nicolaus', 'state_id' => 3925],
                ['name' => 'Pleasant Grove', 'state_id' => 3925],
                ['name' => 'Rio Oso', 'state_id' => 3925],
                ['name' => 'Robbins', 'state_id' => 3925],
                ['name' => 'Live Oak', 'state_id' => 3925],
                ['name' => 'Meridian', 'state_id' => 3925],
                ['name' => 'Sutter', 'state_id' => 3925],
                ['name' => 'Yuba City', 'state_id' => 3925],
                ['name' => 'Corning', 'state_id' => 3925],
                ['name' => 'Flournoy', 'state_id' => 3925],
                ['name' => 'Gerber', 'state_id' => 3925],
                ['name' => 'Los Molinos', 'state_id' => 3925],
                ['name' => 'Manton', 'state_id' => 3925],
                ['name' => 'Mill Creek', 'state_id' => 3925],
                ['name' => 'Mineral', 'state_id' => 3925],
                ['name' => 'Paskenta', 'state_id' => 3925],
                ['name' => 'Paynes Creek', 'state_id' => 3925],
                ['name' => 'Proberta', 'state_id' => 3925],
                ['name' => 'Red Bluff', 'state_id' => 3925],
                ['name' => 'Tehama', 'state_id' => 3925],
                ['name' => 'Vina', 'state_id' => 3925],
                ['name' => 'Burnt Ranch', 'state_id' => 3925],
                ['name' => 'Mad River', 'state_id' => 3925],
                ['name' => 'Salyer', 'state_id' => 3925],
                ['name' => 'Zenia', 'state_id' => 3925],
                ['name' => 'Big Bar', 'state_id' => 3925],
                ['name' => 'Douglas City', 'state_id' => 3925],
                ['name' => 'Hayfork', 'state_id' => 3925],
                ['name' => 'Hyampom', 'state_id' => 3925],
                ['name' => 'Junction City', 'state_id' => 3925],
                ['name' => 'Lewiston', 'state_id' => 3925],
                ['name' => 'Trinity Center', 'state_id' => 3925],
                ['name' => 'Weaverville', 'state_id' => 3925],
                ['name' => 'Alpaugh', 'state_id' => 3925],
                ['name' => 'California Hot Springs', 'state_id' => 3925],
                ['name' => 'Camp Nelson', 'state_id' => 3925],
                ['name' => 'Ducor', 'state_id' => 3925],
                ['name' => 'Earlimart', 'state_id' => 3925],
                ['name' => 'Exeter', 'state_id' => 3925],
                ['name' => 'Farmersville', 'state_id' => 3925],
                ['name' => 'Goshen', 'state_id' => 3925],
                ['name' => 'Ivanhoe', 'state_id' => 3925],
                ['name' => 'Kaweah', 'state_id' => 3925],
                ['name' => 'Lemon Cove', 'state_id' => 3925],
                ['name' => 'Lindsay', 'state_id' => 3925],
                ['name' => 'Pixley', 'state_id' => 3925],
                ['name' => 'Porterville', 'state_id' => 3925],
                ['name' => 'Posey', 'state_id' => 3925],
                ['name' => 'Richgrove', 'state_id' => 3925],
                ['name' => 'Sequoia National Park', 'state_id' => 3925],
                ['name' => 'Springville', 'state_id' => 3925],
                ['name' => 'Strathmore', 'state_id' => 3925],
                ['name' => 'Terra Bella', 'state_id' => 3925],
                ['name' => 'Three Rivers', 'state_id' => 3925],
                ['name' => 'Tipton', 'state_id' => 3925],
                ['name' => 'Tulare', 'state_id' => 3925],
                ['name' => 'Visalia', 'state_id' => 3925],
                ['name' => 'Waukena', 'state_id' => 3925],
                ['name' => 'Woodlake', 'state_id' => 3925],
                ['name' => 'Badger', 'state_id' => 3925],
                ['name' => 'Cutler', 'state_id' => 3925],
                ['name' => 'Dinuba', 'state_id' => 3925],
                ['name' => 'Kings Canyon National Pk', 'state_id' => 3925],
                ['name' => 'Orosi', 'state_id' => 3925],
                ['name' => 'Sultana', 'state_id' => 3925],
                ['name' => 'Yettem', 'state_id' => 3925],
                ['name' => 'Traver', 'state_id' => 3925],
                ['name' => 'Big Oak Flat', 'state_id' => 3925],
                ['name' => 'Chinese Camp', 'state_id' => 3925],
                ['name' => 'Columbia', 'state_id' => 3925],
                ['name' => 'Groveland', 'state_id' => 3925],
                ['name' => 'Jamestown', 'state_id' => 3925],
                ['name' => 'Long Barn', 'state_id' => 3925],
                ['name' => 'Mi Wuk Village', 'state_id' => 3925],
                ['name' => 'Moccasin', 'state_id' => 3925],
                ['name' => 'Pinecrest', 'state_id' => 3925],
                ['name' => 'Sonora', 'state_id' => 3925],
                ['name' => 'Soulsbyville', 'state_id' => 3925],
                ['name' => 'Standard', 'state_id' => 3925],
                ['name' => 'Strawberry', 'state_id' => 3925],
                ['name' => 'Tuolumne', 'state_id' => 3925],
                ['name' => 'Twain Harte', 'state_id' => 3925],
                ['name' => 'Newbury Park', 'state_id' => 3925],
                ['name' => 'Thousand Oaks', 'state_id' => 3925],
                ['name' => 'Westlake Village', 'state_id' => 3925],
                ['name' => 'Oak Park', 'state_id' => 3925],
                ['name' => 'Ventura', 'state_id' => 3925],
                ['name' => 'Camarillo', 'state_id' => 3925],
                ['name' => 'Fillmore', 'state_id' => 3925],
                ['name' => 'Moorpark', 'state_id' => 3925],
                ['name' => 'Oak View', 'state_id' => 3925],
                ['name' => 'Ojai', 'state_id' => 3925],
                ['name' => 'Oxnard', 'state_id' => 3925],
                ['name' => 'Piru', 'state_id' => 3925],
                ['name' => 'Port Hueneme', 'state_id' => 3925],
                ['name' => 'Point Mugu Nawc', 'state_id' => 3925],
                ['name' => 'Port Hueneme Cbc Base', 'state_id' => 3925],
                ['name' => 'Santa Paula', 'state_id' => 3925],
                ['name' => 'Simi Valley', 'state_id' => 3925],
                ['name' => 'Brandeis', 'state_id' => 3925],
                ['name' => 'Somis', 'state_id' => 3925],
                ['name' => 'West Sacramento', 'state_id' => 3925],
                ['name' => 'Brooks', 'state_id' => 3925],
                ['name' => 'Capay', 'state_id' => 3925],
                ['name' => 'Clarksburg', 'state_id' => 3925],
                ['name' => 'Davis', 'state_id' => 3925],
                ['name' => 'Esparto', 'state_id' => 3925],
                ['name' => 'Guinda', 'state_id' => 3925],
                ['name' => 'Knights Landing', 'state_id' => 3925],
                ['name' => 'Madison', 'state_id' => 3925],
                ['name' => 'Rumsey', 'state_id' => 3925],
                ['name' => 'Winters', 'state_id' => 3925],
                ['name' => 'Woodland', 'state_id' => 3925],
                ['name' => 'Yolo', 'state_id' => 3925],
                ['name' => 'Zamora', 'state_id' => 3925],
                ['name' => 'Dunnigan', 'state_id' => 3925],
                ['name' => 'Wheatland', 'state_id' => 3925],
                ['name' => 'Marysville', 'state_id' => 3925],
                ['name' => 'Beale Afb', 'state_id' => 3925],
                ['name' => 'Browns Valley', 'state_id' => 3925],
                ['name' => 'Brownsville', 'state_id' => 3925],
                ['name' => 'Camptonville', 'state_id' => 3925],
                ['name' => 'Challenge', 'state_id' => 3925],
                ['name' => 'Dobbins', 'state_id' => 3925],
                ['name' => 'Olivehurst', 'state_id' => 3925],
                ['name' => 'Oregon House', 'state_id' => 3925],
                ['name' => 'Rackerby', 'state_id' => 3925],
                ['name' => 'Strawberry Valley', 'state_id' => 3925]
            ]);
        }
    }
}
