<?php

use Illuminate\Database\Seeder;

class state41TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of SC - South Carolina.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Abbeville', 'state_id' => 3967],
                ['name' => 'Calhoun Falls', 'state_id' => 3967],
                ['name' => 'Donalds', 'state_id' => 3967],
                ['name' => 'Due West', 'state_id' => 3967],
                ['name' => 'Lowndesville', 'state_id' => 3967],
                ['name' => 'Salley', 'state_id' => 3967],
                ['name' => 'Wagener', 'state_id' => 3967],
                ['name' => 'Aiken', 'state_id' => 3967],
                ['name' => 'New Ellenton', 'state_id' => 3967],
                ['name' => 'Bath', 'state_id' => 3967],
                ['name' => 'Clearwater', 'state_id' => 3967],
                ['name' => 'Gloverville', 'state_id' => 3967],
                ['name' => 'Graniteville', 'state_id' => 3967],
                ['name' => 'Jackson', 'state_id' => 3967],
                ['name' => 'Langley', 'state_id' => 3967],
                ['name' => 'Montmorenci', 'state_id' => 3967],
                ['name' => 'North Augusta', 'state_id' => 3967],
                ['name' => 'Beech Island', 'state_id' => 3967],
                ['name' => 'Vaucluse', 'state_id' => 3967],
                ['name' => 'Warrenville', 'state_id' => 3967],
                ['name' => 'Windsor', 'state_id' => 3967],
                ['name' => 'Allendale', 'state_id' => 3967],
                ['name' => 'Fairfax', 'state_id' => 3967],
                ['name' => 'Martin', 'state_id' => 3967],
                ['name' => 'Sycamore', 'state_id' => 3967],
                ['name' => 'Ulmer', 'state_id' => 3967],
                ['name' => 'Anderson', 'state_id' => 3967],
                ['name' => 'Belton', 'state_id' => 3967],
                ['name' => 'Honea Path', 'state_id' => 3967],
                ['name' => 'Iva', 'state_id' => 3967],
                ['name' => 'La France', 'state_id' => 3967],
                ['name' => 'Pelzer', 'state_id' => 3967],
                ['name' => 'Pendleton', 'state_id' => 3967],
                ['name' => 'Sandy Springs', 'state_id' => 3967],
                ['name' => 'Starr', 'state_id' => 3967],
                ['name' => 'Townville', 'state_id' => 3967],
                ['name' => 'Williamston', 'state_id' => 3967],
                ['name' => 'Bamberg', 'state_id' => 3967],
                ['name' => 'Denmark', 'state_id' => 3967],
                ['name' => 'Ehrhardt', 'state_id' => 3967],
                ['name' => 'Olar', 'state_id' => 3967],
                ['name' => 'Barnwell', 'state_id' => 3967],
                ['name' => 'Hilda', 'state_id' => 3967],
                ['name' => 'Blackville', 'state_id' => 3967],
                ['name' => 'Elko', 'state_id' => 3967],
                ['name' => 'Williston', 'state_id' => 3967],
                ['name' => 'Beaufort', 'state_id' => 3967],
                ['name' => 'Parris Island', 'state_id' => 3967],
                ['name' => 'Bluffton', 'state_id' => 3967],
                ['name' => 'Dale', 'state_id' => 3967],
                ['name' => 'Daufuskie Island', 'state_id' => 3967],
                ['name' => 'Saint Helena Island', 'state_id' => 3967],
                ['name' => 'Hilton Head Island', 'state_id' => 3967],
                ['name' => 'Lobeco', 'state_id' => 3967],
                ['name' => 'Port Royal', 'state_id' => 3967],
                ['name' => 'Seabrook', 'state_id' => 3967],
                ['name' => 'Sheldon', 'state_id' => 3967],
                ['name' => 'Hanahan', 'state_id' => 3967],
                ['name' => 'Bonneau', 'state_id' => 3967],
                ['name' => 'Cordesville', 'state_id' => 3967],
                ['name' => 'Cross', 'state_id' => 3967],
                ['name' => 'Goose Creek', 'state_id' => 3967],
                ['name' => 'Huger', 'state_id' => 3967],
                ['name' => 'Jamestown', 'state_id' => 3967],
                ['name' => 'Ladson', 'state_id' => 3967],
                ['name' => 'Moncks Corner', 'state_id' => 3967],
                ['name' => 'Pineville', 'state_id' => 3967],
                ['name' => 'Pinopolis', 'state_id' => 3967],
                ['name' => 'Russellville', 'state_id' => 3967],
                ['name' => 'Saint Stephen', 'state_id' => 3967],
                ['name' => 'Summerville', 'state_id' => 3967],
                ['name' => 'Charleston', 'state_id' => 3967],
                ['name' => 'Cameron', 'state_id' => 3967],
                ['name' => 'Saint Matthews', 'state_id' => 3967],
                ['name' => 'Charleston Afb', 'state_id' => 3967],
                ['name' => 'North Charleston', 'state_id' => 3967],
                ['name' => 'Adams Run', 'state_id' => 3967],
                ['name' => 'Awendaw', 'state_id' => 3967],
                ['name' => 'Folly Beach', 'state_id' => 3967],
                ['name' => 'Hollywood', 'state_id' => 3967],
                ['name' => 'Isle Of Palms', 'state_id' => 3967],
                ['name' => 'Johns Island', 'state_id' => 3967],
                ['name' => 'Mc Clellanville', 'state_id' => 3967],
                ['name' => 'Mount Pleasant', 'state_id' => 3967],
                ['name' => 'Ravenel', 'state_id' => 3967],
                ['name' => 'Sullivans Island', 'state_id' => 3967],
                ['name' => 'Wadmalaw Island', 'state_id' => 3967],
                ['name' => 'Gaffney', 'state_id' => 3967],
                ['name' => 'Blacksburg', 'state_id' => 3967],
                ['name' => 'Blackstock', 'state_id' => 3967],
                ['name' => 'Great Falls', 'state_id' => 3967],
                ['name' => 'Chester', 'state_id' => 3967],
                ['name' => 'Edgemoor', 'state_id' => 3967],
                ['name' => 'Fort Lawn', 'state_id' => 3967],
                ['name' => 'Lando', 'state_id' => 3967],
                ['name' => 'Richburg', 'state_id' => 3967],
                ['name' => 'Mc Bee', 'state_id' => 3967],
                ['name' => 'Cheraw', 'state_id' => 3967],
                ['name' => 'Patrick', 'state_id' => 3967],
                ['name' => 'Chesterfield', 'state_id' => 3967],
                ['name' => 'Jefferson', 'state_id' => 3967],
                ['name' => 'Mount Croghan', 'state_id' => 3967],
                ['name' => 'Pageland', 'state_id' => 3967],
                ['name' => 'Ruby', 'state_id' => 3967],
                ['name' => 'Alcolu', 'state_id' => 3967],
                ['name' => 'Davis Station', 'state_id' => 3967],
                ['name' => 'Gable', 'state_id' => 3967],
                ['name' => 'Manning', 'state_id' => 3967],
                ['name' => 'New Zion', 'state_id' => 3967],
                ['name' => 'Sardinia', 'state_id' => 3967],
                ['name' => 'Summerton', 'state_id' => 3967],
                ['name' => 'Turbeville', 'state_id' => 3967],
                ['name' => 'Lodge', 'state_id' => 3967],
                ['name' => 'Canadys', 'state_id' => 3967],
                ['name' => 'Cottageville', 'state_id' => 3967],
                ['name' => 'Edisto Island', 'state_id' => 3967],
                ['name' => 'Green Pond', 'state_id' => 3967],
                ['name' => 'Jacksonboro', 'state_id' => 3967],
                ['name' => 'Round O', 'state_id' => 3967],
                ['name' => 'Ruffin', 'state_id' => 3967],
                ['name' => 'Smoaks', 'state_id' => 3967],
                ['name' => 'Walterboro', 'state_id' => 3967],
                ['name' => 'Williams', 'state_id' => 3967],
                ['name' => 'Islandton', 'state_id' => 3967],
                ['name' => 'Lamar', 'state_id' => 3967],
                ['name' => 'Lydia', 'state_id' => 3967],
                ['name' => 'Darlington', 'state_id' => 3967],
                ['name' => 'Hartsville', 'state_id' => 3967],
                ['name' => 'Society Hill', 'state_id' => 3967],
                ['name' => 'Dillon', 'state_id' => 3967],
                ['name' => 'Fork', 'state_id' => 3967],
                ['name' => 'Hamer', 'state_id' => 3967],
                ['name' => 'Lake View', 'state_id' => 3967],
                ['name' => 'Latta', 'state_id' => 3967],
                ['name' => 'Little Rock', 'state_id' => 3967],
                ['name' => 'Dorchester', 'state_id' => 3967],
                ['name' => 'Grover', 'state_id' => 3967],
                ['name' => 'Harleyville', 'state_id' => 3967],
                ['name' => 'Reevesville', 'state_id' => 3967],
                ['name' => 'Ridgeville', 'state_id' => 3967],
                ['name' => 'Saint George', 'state_id' => 3967],
                ['name' => 'Edgefield', 'state_id' => 3967],
                ['name' => 'Johnston', 'state_id' => 3967],
                ['name' => 'Trenton', 'state_id' => 3967],
                ['name' => 'Blair', 'state_id' => 3967],
                ['name' => 'Jenkinsville', 'state_id' => 3967],
                ['name' => 'Ridgeway', 'state_id' => 3967],
                ['name' => 'Rion', 'state_id' => 3967],
                ['name' => 'Winnsboro', 'state_id' => 3967],
                ['name' => 'Olanta', 'state_id' => 3967],
                ['name' => 'Timmonsville', 'state_id' => 3967],
                ['name' => 'Florence', 'state_id' => 3967],
                ['name' => 'Coward', 'state_id' => 3967],
                ['name' => 'Effingham', 'state_id' => 3967],
                ['name' => 'Johnsonville', 'state_id' => 3967],
                ['name' => 'Lake City', 'state_id' => 3967],
                ['name' => 'Pamplico', 'state_id' => 3967],
                ['name' => 'Scranton', 'state_id' => 3967],
                ['name' => 'Georgetown', 'state_id' => 3967],
                ['name' => 'Andrews', 'state_id' => 3967],
                ['name' => 'Murrells Inlet', 'state_id' => 3967],
                ['name' => 'Pawleys Island', 'state_id' => 3967],
                ['name' => 'Greenville', 'state_id' => 3967],
                ['name' => 'Cleveland', 'state_id' => 3967],
                ['name' => 'Conestee', 'state_id' => 3967],
                ['name' => 'Fountain Inn', 'state_id' => 3967],
                ['name' => 'Greer', 'state_id' => 3967],
                ['name' => 'Marietta', 'state_id' => 3967],
                ['name' => 'Mauldin', 'state_id' => 3967],
                ['name' => 'Piedmont', 'state_id' => 3967],
                ['name' => 'Simpsonville', 'state_id' => 3967],
                ['name' => 'Slater', 'state_id' => 3967],
                ['name' => 'Taylors', 'state_id' => 3967],
                ['name' => 'Tigerville', 'state_id' => 3967],
                ['name' => 'Travelers Rest', 'state_id' => 3967],
                ['name' => 'Greenwood', 'state_id' => 3967],
                ['name' => 'Hodges', 'state_id' => 3967],
                ['name' => 'Ninety Six', 'state_id' => 3967],
                ['name' => 'Ware Shoals', 'state_id' => 3967],
                ['name' => 'Bradley', 'state_id' => 3967],
                ['name' => 'Troy', 'state_id' => 3967],
                ['name' => 'Brunson', 'state_id' => 3967],
                ['name' => 'Crocketville', 'state_id' => 3967],
                ['name' => 'Early Branch', 'state_id' => 3967],
                ['name' => 'Estill', 'state_id' => 3967],
                ['name' => 'Furman', 'state_id' => 3967],
                ['name' => 'Garnett', 'state_id' => 3967],
                ['name' => 'Gifford', 'state_id' => 3967],
                ['name' => 'Hampton', 'state_id' => 3967],
                ['name' => 'Luray', 'state_id' => 3967],
                ['name' => 'Miley', 'state_id' => 3967],
                ['name' => 'Scotia', 'state_id' => 3967],
                ['name' => 'Varnville', 'state_id' => 3967],
                ['name' => 'Yemassee', 'state_id' => 3967],
                ['name' => 'Aynor', 'state_id' => 3967],
                ['name' => 'Conway', 'state_id' => 3967],
                ['name' => 'Galivants Ferry', 'state_id' => 3967],
                ['name' => 'Green Sea', 'state_id' => 3967],
                ['name' => 'Little River', 'state_id' => 3967],
                ['name' => 'Longs', 'state_id' => 3967],
                ['name' => 'Loris', 'state_id' => 3967],
                ['name' => 'Myrtle Beach', 'state_id' => 3967],
                ['name' => 'Nichols', 'state_id' => 3967],
                ['name' => 'North Myrtle Beach', 'state_id' => 3967],
                ['name' => 'Okatie', 'state_id' => 3967],
                ['name' => 'Coosawhatchie', 'state_id' => 3967],
                ['name' => 'Hardeeville', 'state_id' => 3967],
                ['name' => 'Pineland', 'state_id' => 3967],
                ['name' => 'Ridgeland', 'state_id' => 3967],
                ['name' => 'Tillman', 'state_id' => 3967],
                ['name' => 'Bethune', 'state_id' => 3967],
                ['name' => 'Camden', 'state_id' => 3967],
                ['name' => 'Cassatt', 'state_id' => 3967],
                ['name' => 'Elgin', 'state_id' => 3967],
                ['name' => 'Liberty Hill', 'state_id' => 3967],
                ['name' => 'Lugoff', 'state_id' => 3967],
                ['name' => 'Westville', 'state_id' => 3967],
                ['name' => 'Heath Springs', 'state_id' => 3967],
                ['name' => 'Kershaw', 'state_id' => 3967],
                ['name' => 'Fort Mill', 'state_id' => 3967],
                ['name' => 'Lancaster', 'state_id' => 3967],
                ['name' => 'Van Wyck', 'state_id' => 3967],
                ['name' => 'Clinton', 'state_id' => 3967],
                ['name' => 'Cross Hill', 'state_id' => 3967],
                ['name' => 'Joanna', 'state_id' => 3967],
                ['name' => 'Laurens', 'state_id' => 3967],
                ['name' => 'Mountville', 'state_id' => 3967],
                ['name' => 'Waterloo', 'state_id' => 3967],
                ['name' => 'Gray Court', 'state_id' => 3967],
                ['name' => 'Bishopville', 'state_id' => 3967],
                ['name' => 'Elliott', 'state_id' => 3967],
                ['name' => 'Lynchburg', 'state_id' => 3967],
                ['name' => 'Batesburg', 'state_id' => 3967],
                ['name' => 'Cayce', 'state_id' => 3967],
                ['name' => 'Chapin', 'state_id' => 3967],
                ['name' => 'Gaston', 'state_id' => 3967],
                ['name' => 'Gilbert', 'state_id' => 3967],
                ['name' => 'Leesville', 'state_id' => 3967],
                ['name' => 'Lexington', 'state_id' => 3967],
                ['name' => 'Pelion', 'state_id' => 3967],
                ['name' => 'Swansea', 'state_id' => 3967],
                ['name' => 'West Columbia', 'state_id' => 3967],
                ['name' => 'Columbia', 'state_id' => 3967],
                ['name' => 'Clarks Hill', 'state_id' => 3967],
                ['name' => 'Mc Cormick', 'state_id' => 3967],
                ['name' => 'Modoc', 'state_id' => 3967],
                ['name' => 'Mount Carmel', 'state_id' => 3967],
                ['name' => 'Parksville', 'state_id' => 3967],
                ['name' => 'Plum Branch', 'state_id' => 3967],
                ['name' => 'Centenary', 'state_id' => 3967],
                ['name' => 'Gresham', 'state_id' => 3967],
                ['name' => 'Marion', 'state_id' => 3967],
                ['name' => 'Mullins', 'state_id' => 3967],
                ['name' => 'Rains', 'state_id' => 3967],
                ['name' => 'Sellers', 'state_id' => 3967],
                ['name' => 'Bennettsville', 'state_id' => 3967],
                ['name' => 'Blenheim', 'state_id' => 3967],
                ['name' => 'Clio', 'state_id' => 3967],
                ['name' => 'Mc Coll', 'state_id' => 3967],
                ['name' => 'Tatum', 'state_id' => 3967],
                ['name' => 'Wallace', 'state_id' => 3967],
                ['name' => 'Chappells', 'state_id' => 3967],
                ['name' => 'Little Mountain', 'state_id' => 3967],
                ['name' => 'Newberry', 'state_id' => 3967],
                ['name' => 'Peak', 'state_id' => 3967],
                ['name' => 'Pomaria', 'state_id' => 3967],
                ['name' => 'Prosperity', 'state_id' => 3967],
                ['name' => 'Silverstreet', 'state_id' => 3967],
                ['name' => 'Whitmire', 'state_id' => 3967],
                ['name' => 'Kinards', 'state_id' => 3967],
                ['name' => 'Fair Play', 'state_id' => 3967],
                ['name' => 'Long Creek', 'state_id' => 3967],
                ['name' => 'Mountain Rest', 'state_id' => 3967],
                ['name' => 'Newry', 'state_id' => 3967],
                ['name' => 'Seneca', 'state_id' => 3967],
                ['name' => 'Richland', 'state_id' => 3967],
                ['name' => 'Salem', 'state_id' => 3967],
                ['name' => 'Tamassee', 'state_id' => 3967],
                ['name' => 'Walhalla', 'state_id' => 3967],
                ['name' => 'Westminster', 'state_id' => 3967],
                ['name' => 'West Union', 'state_id' => 3967],
                ['name' => 'Bowman', 'state_id' => 3967],
                ['name' => 'Cope', 'state_id' => 3967],
                ['name' => 'Cordova', 'state_id' => 3967],
                ['name' => 'Elloree', 'state_id' => 3967],
                ['name' => 'Eutawville', 'state_id' => 3967],
                ['name' => 'Holly Hill', 'state_id' => 3967],
                ['name' => 'Neeses', 'state_id' => 3967],
                ['name' => 'North', 'state_id' => 3967],
                ['name' => 'Norway', 'state_id' => 3967],
                ['name' => 'Orangeburg', 'state_id' => 3967],
                ['name' => 'Rowesville', 'state_id' => 3967],
                ['name' => 'Santee', 'state_id' => 3967],
                ['name' => 'Springfield', 'state_id' => 3967],
                ['name' => 'Vance', 'state_id' => 3967],
                ['name' => 'Branchville', 'state_id' => 3967],
                ['name' => 'Central', 'state_id' => 3967],
                ['name' => 'Clemson', 'state_id' => 3967],
                ['name' => 'Easley', 'state_id' => 3967],
                ['name' => 'Liberty', 'state_id' => 3967],
                ['name' => 'Norris', 'state_id' => 3967],
                ['name' => 'Pickens', 'state_id' => 3967],
                ['name' => 'Six Mile', 'state_id' => 3967],
                ['name' => 'Sunset', 'state_id' => 3967],
                ['name' => 'Ballentine', 'state_id' => 3967],
                ['name' => 'Blythewood', 'state_id' => 3967],
                ['name' => 'Eastover', 'state_id' => 3967],
                ['name' => 'Gadsden', 'state_id' => 3967],
                ['name' => 'Hopkins', 'state_id' => 3967],
                ['name' => 'Irmo', 'state_id' => 3967],
                ['name' => 'State Park', 'state_id' => 3967],
                ['name' => 'White Rock', 'state_id' => 3967],
                ['name' => 'Monetta', 'state_id' => 3967],
                ['name' => 'Ridge Spring', 'state_id' => 3967],
                ['name' => 'Saluda', 'state_id' => 3967],
                ['name' => 'Ward', 'state_id' => 3967],
                ['name' => 'Spartanburg', 'state_id' => 3967],
                ['name' => 'Boiling Springs', 'state_id' => 3967],
                ['name' => 'Arcadia', 'state_id' => 3967],
                ['name' => 'Campobello', 'state_id' => 3967],
                ['name' => 'Chesnee', 'state_id' => 3967],
                ['name' => 'Clifton', 'state_id' => 3967],
                ['name' => 'Converse', 'state_id' => 3967],
                ['name' => 'Cowpens', 'state_id' => 3967],
                ['name' => 'Cross Anchor', 'state_id' => 3967],
                ['name' => 'Drayton', 'state_id' => 3967],
                ['name' => 'Duncan', 'state_id' => 3967],
                ['name' => 'Enoree', 'state_id' => 3967],
                ['name' => 'Fairforest', 'state_id' => 3967],
                ['name' => 'Fingerville', 'state_id' => 3967],
                ['name' => 'Glendale', 'state_id' => 3967],
                ['name' => 'Gramling', 'state_id' => 3967],
                ['name' => 'Inman', 'state_id' => 3967],
                ['name' => 'Landrum', 'state_id' => 3967],
                ['name' => 'Lyman', 'state_id' => 3967],
                ['name' => 'Mayo', 'state_id' => 3967],
                ['name' => 'Moore', 'state_id' => 3967],
                ['name' => 'Pacolet', 'state_id' => 3967],
                ['name' => 'Pacolet Mills', 'state_id' => 3967],
                ['name' => 'Pauline', 'state_id' => 3967],
                ['name' => 'Reidville', 'state_id' => 3967],
                ['name' => 'Roebuck', 'state_id' => 3967],
                ['name' => 'Startex', 'state_id' => 3967],
                ['name' => 'Una', 'state_id' => 3967],
                ['name' => 'Wellford', 'state_id' => 3967],
                ['name' => 'White Stone', 'state_id' => 3967],
                ['name' => 'Woodruff', 'state_id' => 3967],
                ['name' => 'Dalzell', 'state_id' => 3967],
                ['name' => 'Horatio', 'state_id' => 3967],
                ['name' => 'Mayesville', 'state_id' => 3967],
                ['name' => 'Pinewood', 'state_id' => 3967],
                ['name' => 'Rembert', 'state_id' => 3967],
                ['name' => 'Sumter', 'state_id' => 3967],
                ['name' => 'Shaw Afb', 'state_id' => 3967],
                ['name' => 'Wedgefield', 'state_id' => 3967],
                ['name' => 'Carlisle', 'state_id' => 3967],
                ['name' => 'Buffalo', 'state_id' => 3967],
                ['name' => 'Jonesville', 'state_id' => 3967],
                ['name' => 'Lockhart', 'state_id' => 3967],
                ['name' => 'Union', 'state_id' => 3967],
                ['name' => 'Greeleyville', 'state_id' => 3967],
                ['name' => 'Cades', 'state_id' => 3967],
                ['name' => 'Hemingway', 'state_id' => 3967],
                ['name' => 'Kingstree', 'state_id' => 3967],
                ['name' => 'Lane', 'state_id' => 3967],
                ['name' => 'Nesmith', 'state_id' => 3967],
                ['name' => 'Salters', 'state_id' => 3967],
                ['name' => 'Bowling Green', 'state_id' => 3967],
                ['name' => 'Catawba', 'state_id' => 3967],
                ['name' => 'Clover', 'state_id' => 3967],
                ['name' => 'Hickory Grove', 'state_id' => 3967],
                ['name' => 'Mc Connells', 'state_id' => 3967],
                ['name' => 'Rock Hill', 'state_id' => 3967],
                ['name' => 'Sharon', 'state_id' => 3967],
                ['name' => 'Smyrna', 'state_id' => 3967],
                ['name' => 'York', 'state_id' => 3967]
            ]);
        }
    }
}
