<?php

use Illuminate\Database\Seeder;

class state15TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IL - Illinois.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Quincy', 'state_id' => 3935],
                ['name' => 'Camp Point', 'state_id' => 3935],
                ['name' => 'Clayton', 'state_id' => 3935],
                ['name' => 'Coatsburg', 'state_id' => 3935],
                ['name' => 'Fowler', 'state_id' => 3935],
                ['name' => 'Golden', 'state_id' => 3935],
                ['name' => 'La Prairie', 'state_id' => 3935],
                ['name' => 'Liberty', 'state_id' => 3935],
                ['name' => 'Lima', 'state_id' => 3935],
                ['name' => 'Loraine', 'state_id' => 3935],
                ['name' => 'Mendon', 'state_id' => 3935],
                ['name' => 'Paloma', 'state_id' => 3935],
                ['name' => 'Payson', 'state_id' => 3935],
                ['name' => 'Plainville', 'state_id' => 3935],
                ['name' => 'Ursa', 'state_id' => 3935],
                ['name' => 'Cairo', 'state_id' => 3935],
                ['name' => 'Mc Clure', 'state_id' => 3935],
                ['name' => 'Miller City', 'state_id' => 3935],
                ['name' => 'Olive Branch', 'state_id' => 3935],
                ['name' => 'Tamms', 'state_id' => 3935],
                ['name' => 'Thebes', 'state_id' => 3935],
                ['name' => 'Unity', 'state_id' => 3935],
                ['name' => 'Donnellson', 'state_id' => 3935],
                ['name' => 'Sorento', 'state_id' => 3935],
                ['name' => 'Greenville', 'state_id' => 3935],
                ['name' => 'Mulberry Grove', 'state_id' => 3935],
                ['name' => 'Pierron', 'state_id' => 3935],
                ['name' => 'Pocahontas', 'state_id' => 3935],
                ['name' => 'Smithboro', 'state_id' => 3935],
                ['name' => 'Belvidere', 'state_id' => 3935],
                ['name' => 'Caledonia', 'state_id' => 3935],
                ['name' => 'Capron', 'state_id' => 3935],
                ['name' => 'Garden Prairie', 'state_id' => 3935],
                ['name' => 'Poplar Grove', 'state_id' => 3935],
                ['name' => 'Mount Sterling', 'state_id' => 3935],
                ['name' => 'Timewell', 'state_id' => 3935],
                ['name' => 'Versailles', 'state_id' => 3935],
                ['name' => 'Arlington', 'state_id' => 3935],
                ['name' => 'Buda', 'state_id' => 3935],
                ['name' => 'Bureau', 'state_id' => 3935],
                ['name' => 'Cherry', 'state_id' => 3935],
                ['name' => 'Dalzell', 'state_id' => 3935],
                ['name' => 'Depue', 'state_id' => 3935],
                ['name' => 'Dover', 'state_id' => 3935],
                ['name' => 'Kasbeer', 'state_id' => 3935],
                ['name' => 'Ladd', 'state_id' => 3935],
                ['name' => 'La Moille', 'state_id' => 3935],
                ['name' => 'Malden', 'state_id' => 3935],
                ['name' => 'Manlius', 'state_id' => 3935],
                ['name' => 'Mineral', 'state_id' => 3935],
                ['name' => 'Neponset', 'state_id' => 3935],
                ['name' => 'New Bedford', 'state_id' => 3935],
                ['name' => 'Ohio', 'state_id' => 3935],
                ['name' => 'Princeton', 'state_id' => 3935],
                ['name' => 'Seatonville', 'state_id' => 3935],
                ['name' => 'Sheffield', 'state_id' => 3935],
                ['name' => 'Spring Valley', 'state_id' => 3935],
                ['name' => 'Tiskilwa', 'state_id' => 3935],
                ['name' => 'Van Orin', 'state_id' => 3935],
                ['name' => 'Walnut', 'state_id' => 3935],
                ['name' => 'Wyanet', 'state_id' => 3935],
                ['name' => 'Batchtown', 'state_id' => 3935],
                ['name' => 'Brussels', 'state_id' => 3935],
                ['name' => 'Golden Eagle', 'state_id' => 3935],
                ['name' => 'Hamburg', 'state_id' => 3935],
                ['name' => 'Hardin', 'state_id' => 3935],
                ['name' => 'Kampsville', 'state_id' => 3935],
                ['name' => 'Michael', 'state_id' => 3935],
                ['name' => 'Mozier', 'state_id' => 3935],
                ['name' => 'Chadwick', 'state_id' => 3935],
                ['name' => 'Lanark', 'state_id' => 3935],
                ['name' => 'Milledgeville', 'state_id' => 3935],
                ['name' => 'Mount Carroll', 'state_id' => 3935],
                ['name' => 'Savanna', 'state_id' => 3935],
                ['name' => 'Shannon', 'state_id' => 3935],
                ['name' => 'Thomson', 'state_id' => 3935],
                ['name' => 'Arenzville', 'state_id' => 3935],
                ['name' => 'Ashland', 'state_id' => 3935],
                ['name' => 'Beardstown', 'state_id' => 3935],
                ['name' => 'Bluff Springs', 'state_id' => 3935],
                ['name' => 'Chandlerville', 'state_id' => 3935],
                ['name' => 'Virginia', 'state_id' => 3935],
                ['name' => 'Ludlow', 'state_id' => 3935],
                ['name' => 'Urbana', 'state_id' => 3935],
                ['name' => 'Bondville', 'state_id' => 3935],
                ['name' => 'Broadlands', 'state_id' => 3935],
                ['name' => 'Champaign', 'state_id' => 3935],
                ['name' => 'Dewey', 'state_id' => 3935],
                ['name' => 'Fisher', 'state_id' => 3935],
                ['name' => 'Foosland', 'state_id' => 3935],
                ['name' => 'Gifford', 'state_id' => 3935],
                ['name' => 'Homer', 'state_id' => 3935],
                ['name' => 'Ivesdale', 'state_id' => 3935],
                ['name' => 'Longview', 'state_id' => 3935],
                ['name' => 'Mahomet', 'state_id' => 3935],
                ['name' => 'Ogden', 'state_id' => 3935],
                ['name' => 'Penfield', 'state_id' => 3935],
                ['name' => 'Pesotum', 'state_id' => 3935],
                ['name' => 'Philo', 'state_id' => 3935],
                ['name' => 'Rantoul', 'state_id' => 3935],
                ['name' => 'Royal', 'state_id' => 3935],
                ['name' => 'Sadorus', 'state_id' => 3935],
                ['name' => 'Saint Joseph', 'state_id' => 3935],
                ['name' => 'Savoy', 'state_id' => 3935],
                ['name' => 'Seymour', 'state_id' => 3935],
                ['name' => 'Sidney', 'state_id' => 3935],
                ['name' => 'Thomasboro', 'state_id' => 3935],
                ['name' => 'Tolono', 'state_id' => 3935],
                ['name' => 'Rosamond', 'state_id' => 3935],
                ['name' => 'Assumption', 'state_id' => 3935],
                ['name' => 'Bulpitt', 'state_id' => 3935],
                ['name' => 'Edinburg', 'state_id' => 3935],
                ['name' => 'Kincaid', 'state_id' => 3935],
                ['name' => 'Morrisonville', 'state_id' => 3935],
                ['name' => 'Mount Auburn', 'state_id' => 3935],
                ['name' => 'Owaneco', 'state_id' => 3935],
                ['name' => 'Palmer', 'state_id' => 3935],
                ['name' => 'Pana', 'state_id' => 3935],
                ['name' => 'Stonington', 'state_id' => 3935],
                ['name' => 'Taylorville', 'state_id' => 3935],
                ['name' => 'Tovey', 'state_id' => 3935],
                ['name' => 'Casey', 'state_id' => 3935],
                ['name' => 'Dennison', 'state_id' => 3935],
                ['name' => 'Marshall', 'state_id' => 3935],
                ['name' => 'Martinsville', 'state_id' => 3935],
                ['name' => 'Westfield', 'state_id' => 3935],
                ['name' => 'West Union', 'state_id' => 3935],
                ['name' => 'Ingraham', 'state_id' => 3935],
                ['name' => 'Clay City', 'state_id' => 3935],
                ['name' => 'Flora', 'state_id' => 3935],
                ['name' => 'Louisville', 'state_id' => 3935],
                ['name' => 'Sailor Springs', 'state_id' => 3935],
                ['name' => 'Xenia', 'state_id' => 3935],
                ['name' => 'Albers', 'state_id' => 3935],
                ['name' => 'Aviston', 'state_id' => 3935],
                ['name' => 'Bartelso', 'state_id' => 3935],
                ['name' => 'Beckemeyer', 'state_id' => 3935],
                ['name' => 'Breese', 'state_id' => 3935],
                ['name' => 'Carlyle', 'state_id' => 3935],
                ['name' => 'Germantown', 'state_id' => 3935],
                ['name' => 'Hoffman', 'state_id' => 3935],
                ['name' => 'Huey', 'state_id' => 3935],
                ['name' => 'Keyesport', 'state_id' => 3935],
                ['name' => 'New Baden', 'state_id' => 3935],
                ['name' => 'New Memphis', 'state_id' => 3935],
                ['name' => 'Trenton', 'state_id' => 3935],
                ['name' => 'Ashmore', 'state_id' => 3935],
                ['name' => 'Charleston', 'state_id' => 3935],
                ['name' => 'Humboldt', 'state_id' => 3935],
                ['name' => 'Mattoon', 'state_id' => 3935],
                ['name' => 'Oakland', 'state_id' => 3935],
                ['name' => 'Lerna', 'state_id' => 3935],
                ['name' => 'Trilla', 'state_id' => 3935],
                ['name' => 'Arlington Heights', 'state_id' => 3935],
                ['name' => 'Elk Grove Village', 'state_id' => 3935],
                ['name' => 'Rolling Meadows', 'state_id' => 3935],
                ['name' => 'Des Plaines', 'state_id' => 3935],
                ['name' => 'Glencoe', 'state_id' => 3935],
                ['name' => 'Glenview', 'state_id' => 3935],
                ['name' => 'Golf', 'state_id' => 3935],
                ['name' => 'Palatine', 'state_id' => 3935],
                ['name' => 'Kenilworth', 'state_id' => 3935],
                ['name' => 'Morton Grove', 'state_id' => 3935],
                ['name' => 'Mount Prospect', 'state_id' => 3935],
                ['name' => 'Northbrook', 'state_id' => 3935],
                ['name' => 'Park Ridge', 'state_id' => 3935],
                ['name' => 'Prospect Heights', 'state_id' => 3935],
                ['name' => 'Skokie', 'state_id' => 3935],
                ['name' => 'Techny', 'state_id' => 3935],
                ['name' => 'Wheeling', 'state_id' => 3935],
                ['name' => 'Wilmette', 'state_id' => 3935],
                ['name' => 'Winnetka', 'state_id' => 3935],
                ['name' => 'Bartlett', 'state_id' => 3935],
                ['name' => 'Bellwood', 'state_id' => 3935],
                ['name' => 'Streamwood', 'state_id' => 3935],
                ['name' => 'Forest Park', 'state_id' => 3935],
                ['name' => 'Franklin Park', 'state_id' => 3935],
                ['name' => 'Hines', 'state_id' => 3935],
                ['name' => 'Maywood', 'state_id' => 3935],
                ['name' => 'Westchester', 'state_id' => 3935],
                ['name' => 'Broadview', 'state_id' => 3935],
                ['name' => 'Schaumburg', 'state_id' => 3935],
                ['name' => 'Melrose Park', 'state_id' => 3935],
                ['name' => 'Hillside', 'state_id' => 3935],
                ['name' => 'Berkeley', 'state_id' => 3935],
                ['name' => 'Stone Park', 'state_id' => 3935],
                ['name' => 'Hoffman Estates', 'state_id' => 3935],
                ['name' => 'River Grove', 'state_id' => 3935],
                ['name' => 'Schiller Park', 'state_id' => 3935],
                ['name' => 'Evanston', 'state_id' => 3935],
                ['name' => 'Oak Park', 'state_id' => 3935],
                ['name' => 'River Forest', 'state_id' => 3935],
                ['name' => 'Berwyn', 'state_id' => 3935],
                ['name' => 'Blue Island', 'state_id' => 3935],
                ['name' => 'Calumet City', 'state_id' => 3935],
                ['name' => 'Chicago Heights', 'state_id' => 3935],
                ['name' => 'Chicago Ridge', 'state_id' => 3935],
                ['name' => 'Crestwood', 'state_id' => 3935],
                ['name' => 'Dolton', 'state_id' => 3935],
                ['name' => 'Flossmoor', 'state_id' => 3935],
                ['name' => 'Glenwood', 'state_id' => 3935],
                ['name' => 'Harvey', 'state_id' => 3935],
                ['name' => 'Hazel Crest', 'state_id' => 3935],
                ['name' => 'Homewood', 'state_id' => 3935],
                ['name' => 'Lansing', 'state_id' => 3935],
                ['name' => 'Matteson', 'state_id' => 3935],
                ['name' => 'Midlothian', 'state_id' => 3935],
                ['name' => 'Oak Forest', 'state_id' => 3935],
                ['name' => 'Oak Lawn', 'state_id' => 3935],
                ['name' => 'Bridgeview', 'state_id' => 3935],
                ['name' => 'Hometown', 'state_id' => 3935],
                ['name' => 'Hickory Hills', 'state_id' => 3935],
                ['name' => 'Justice', 'state_id' => 3935],
                ['name' => 'Burbank', 'state_id' => 3935],
                ['name' => 'Olympia Fields', 'state_id' => 3935],
                ['name' => 'Orland Park', 'state_id' => 3935],
                ['name' => 'Palos Heights', 'state_id' => 3935],
                ['name' => 'Palos Park', 'state_id' => 3935],
                ['name' => 'Palos Hills', 'state_id' => 3935],
                ['name' => 'Park Forest', 'state_id' => 3935],
                ['name' => 'Posen', 'state_id' => 3935],
                ['name' => 'Richton Park', 'state_id' => 3935],
                ['name' => 'Robbins', 'state_id' => 3935],
                ['name' => 'South Holland', 'state_id' => 3935],
                ['name' => 'Steger', 'state_id' => 3935],
                ['name' => 'Thornton', 'state_id' => 3935],
                ['name' => 'Tinley Park', 'state_id' => 3935],
                ['name' => 'Country Club Hills', 'state_id' => 3935],
                ['name' => 'Willow Springs', 'state_id' => 3935],
                ['name' => 'Worth', 'state_id' => 3935],
                ['name' => 'Bedford Park', 'state_id' => 3935],
                ['name' => 'Summit Argo', 'state_id' => 3935],
                ['name' => 'Brookfield', 'state_id' => 3935],
                ['name' => 'La Grange', 'state_id' => 3935],
                ['name' => 'La Grange Park', 'state_id' => 3935],
                ['name' => 'Lyons', 'state_id' => 3935],
                ['name' => 'Riverside', 'state_id' => 3935],
                ['name' => 'Western Springs', 'state_id' => 3935],
                ['name' => 'Chicago', 'state_id' => 3935],
                ['name' => 'Harwood Heights', 'state_id' => 3935],
                ['name' => 'Elmwood Park', 'state_id' => 3935],
                ['name' => 'Lincolnwood', 'state_id' => 3935],
                ['name' => 'Niles', 'state_id' => 3935],
                ['name' => 'Alsip', 'state_id' => 3935],
                ['name' => 'Cicero', 'state_id' => 3935],
                ['name' => 'Evergreen Park', 'state_id' => 3935],
                ['name' => 'Riverdale', 'state_id' => 3935],
                ['name' => 'Annapolis', 'state_id' => 3935],
                ['name' => 'Flat Rock', 'state_id' => 3935],
                ['name' => 'Hutsonville', 'state_id' => 3935],
                ['name' => 'Oblong', 'state_id' => 3935],
                ['name' => 'Palestine', 'state_id' => 3935],
                ['name' => 'Robinson', 'state_id' => 3935],
                ['name' => 'Stoy', 'state_id' => 3935],
                ['name' => 'West York', 'state_id' => 3935],
                ['name' => 'Greenup', 'state_id' => 3935],
                ['name' => 'Janesville', 'state_id' => 3935],
                ['name' => 'Jewett', 'state_id' => 3935],
                ['name' => 'Neoga', 'state_id' => 3935],
                ['name' => 'Toledo', 'state_id' => 3935],
                ['name' => 'Clare', 'state_id' => 3935],
                ['name' => 'Cortland', 'state_id' => 3935],
                ['name' => 'Dekalb', 'state_id' => 3935],
                ['name' => 'Esmond', 'state_id' => 3935],
                ['name' => 'Genoa', 'state_id' => 3935],
                ['name' => 'Kingston', 'state_id' => 3935],
                ['name' => 'Kirkland', 'state_id' => 3935],
                ['name' => 'Malta', 'state_id' => 3935],
                ['name' => 'Sycamore', 'state_id' => 3935],
                ['name' => 'Hinckley', 'state_id' => 3935],
                ['name' => 'Sandwich', 'state_id' => 3935],
                ['name' => 'Shabbona', 'state_id' => 3935],
                ['name' => 'Somonauk', 'state_id' => 3935],
                ['name' => 'Waterman', 'state_id' => 3935],
                ['name' => 'Clinton', 'state_id' => 3935],
                ['name' => 'Dewitt', 'state_id' => 3935],
                ['name' => 'Kenney', 'state_id' => 3935],
                ['name' => 'Lane', 'state_id' => 3935],
                ['name' => 'Wapella', 'state_id' => 3935],
                ['name' => 'Waynesville', 'state_id' => 3935],
                ['name' => 'Farmer City', 'state_id' => 3935],
                ['name' => 'Weldon', 'state_id' => 3935],
                ['name' => 'Arcola', 'state_id' => 3935],
                ['name' => 'Arthur', 'state_id' => 3935],
                ['name' => 'Atwood', 'state_id' => 3935],
                ['name' => 'Camargo', 'state_id' => 3935],
                ['name' => 'Hindsboro', 'state_id' => 3935],
                ['name' => 'Murdock', 'state_id' => 3935],
                ['name' => 'Newman', 'state_id' => 3935],
                ['name' => 'Tuscola', 'state_id' => 3935],
                ['name' => 'Villa Grove', 'state_id' => 3935],
                ['name' => 'Addison', 'state_id' => 3935],
                ['name' => 'Bensenville', 'state_id' => 3935],
                ['name' => 'Bloomingdale', 'state_id' => 3935],
                ['name' => 'Carol Stream', 'state_id' => 3935],
                ['name' => 'Elmhurst', 'state_id' => 3935],
                ['name' => 'Hanover Park', 'state_id' => 3935],
                ['name' => 'Glen Ellyn', 'state_id' => 3935],
                ['name' => 'Glendale Heights', 'state_id' => 3935],
                ['name' => 'Itasca', 'state_id' => 3935],
                ['name' => 'Lombard', 'state_id' => 3935],
                ['name' => 'Medinah', 'state_id' => 3935],
                ['name' => 'Roselle', 'state_id' => 3935],
                ['name' => 'Villa Park', 'state_id' => 3935],
                ['name' => 'Wayne', 'state_id' => 3935],
                ['name' => 'West Chicago', 'state_id' => 3935],
                ['name' => 'Wheaton', 'state_id' => 3935],
                ['name' => 'Winfield', 'state_id' => 3935],
                ['name' => 'Wood Dale', 'state_id' => 3935],
                ['name' => 'Lemont', 'state_id' => 3935],
                ['name' => 'Aurora', 'state_id' => 3935],
                ['name' => 'Clarendon Hills', 'state_id' => 3935],
                ['name' => 'Downers Grove', 'state_id' => 3935],
                ['name' => 'Woodridge', 'state_id' => 3935],
                ['name' => 'Eola', 'state_id' => 3935],
                ['name' => 'Hinsdale', 'state_id' => 3935],
                ['name' => 'Oak Brook', 'state_id' => 3935],
                ['name' => 'Willowbrook', 'state_id' => 3935],
                ['name' => 'Lisle', 'state_id' => 3935],
                ['name' => 'Naperville', 'state_id' => 3935],
                ['name' => 'Warrenville', 'state_id' => 3935],
                ['name' => 'Westmont', 'state_id' => 3935],
                ['name' => 'Darien', 'state_id' => 3935],
                ['name' => 'Fox Valley', 'state_id' => 3935],
                ['name' => 'Brocton', 'state_id' => 3935],
                ['name' => 'Chrisman', 'state_id' => 3935],
                ['name' => 'Hume', 'state_id' => 3935],
                ['name' => 'Kansas', 'state_id' => 3935],
                ['name' => 'Metcalf', 'state_id' => 3935],
                ['name' => 'Paris', 'state_id' => 3935],
                ['name' => 'Redmon', 'state_id' => 3935],
                ['name' => 'Vermilion', 'state_id' => 3935],
                ['name' => 'West Salem', 'state_id' => 3935],
                ['name' => 'Albion', 'state_id' => 3935],
                ['name' => 'Bone Gap', 'state_id' => 3935],
                ['name' => 'Browns', 'state_id' => 3935],
                ['name' => 'Ellery', 'state_id' => 3935],
                ['name' => 'Effingham', 'state_id' => 3935],
                ['name' => 'Altamont', 'state_id' => 3935],
                ['name' => 'Beecher City', 'state_id' => 3935],
                ['name' => 'Dieterich', 'state_id' => 3935],
                ['name' => 'Edgewood', 'state_id' => 3935],
                ['name' => 'Mason', 'state_id' => 3935],
                ['name' => 'Montrose', 'state_id' => 3935],
                ['name' => 'Shumway', 'state_id' => 3935],
                ['name' => 'Teutopolis', 'state_id' => 3935],
                ['name' => 'Watson', 'state_id' => 3935],
                ['name' => 'Bingham', 'state_id' => 3935],
                ['name' => 'Ramsey', 'state_id' => 3935],
                ['name' => 'Hagarstown', 'state_id' => 3935],
                ['name' => 'Brownstown', 'state_id' => 3935],
                ['name' => 'Saint Elmo', 'state_id' => 3935],
                ['name' => 'Vandalia', 'state_id' => 3935],
                ['name' => 'Farina', 'state_id' => 3935],
                ['name' => 'Saint Peter', 'state_id' => 3935],
                ['name' => 'Shobonier', 'state_id' => 3935],
                ['name' => 'Cabery', 'state_id' => 3935],
                ['name' => 'Elliott', 'state_id' => 3935],
                ['name' => 'Gibson City', 'state_id' => 3935],
                ['name' => 'Kempton', 'state_id' => 3935],
                ['name' => 'Melvin', 'state_id' => 3935],
                ['name' => 'Paxton', 'state_id' => 3935],
                ['name' => 'Piper City', 'state_id' => 3935],
                ['name' => 'Roberts', 'state_id' => 3935],
                ['name' => 'Sibley', 'state_id' => 3935],
                ['name' => 'Benton', 'state_id' => 3935],
                ['name' => 'Buckner', 'state_id' => 3935],
                ['name' => 'Christopher', 'state_id' => 3935],
                ['name' => 'Coello', 'state_id' => 3935],
                ['name' => 'Ewing', 'state_id' => 3935],
                ['name' => 'Frankfort Heights', 'state_id' => 3935],
                ['name' => 'Logan', 'state_id' => 3935],
                ['name' => 'Mulkeytown', 'state_id' => 3935],
                ['name' => 'Orient', 'state_id' => 3935],
                ['name' => 'Sesser', 'state_id' => 3935],
                ['name' => 'Thompsonville', 'state_id' => 3935],
                ['name' => 'Valier', 'state_id' => 3935],
                ['name' => 'West Frankfort', 'state_id' => 3935],
                ['name' => 'Whittington', 'state_id' => 3935],
                ['name' => 'Royalton', 'state_id' => 3935],
                ['name' => 'Zeigler', 'state_id' => 3935],
                ['name' => 'Avon', 'state_id' => 3935],
                ['name' => 'Cuba', 'state_id' => 3935],
                ['name' => 'Ellisville', 'state_id' => 3935],
                ['name' => 'Fairview', 'state_id' => 3935],
                ['name' => 'Fiatt', 'state_id' => 3935],
                ['name' => 'Ipava', 'state_id' => 3935],
                ['name' => 'Marietta', 'state_id' => 3935],
                ['name' => 'Smithfield', 'state_id' => 3935],
                ['name' => 'Table Grove', 'state_id' => 3935],
                ['name' => 'Vermont', 'state_id' => 3935],
                ['name' => 'Astoria', 'state_id' => 3935],
                ['name' => 'Bryant', 'state_id' => 3935],
                ['name' => 'Canton', 'state_id' => 3935],
                ['name' => 'Dunfermline', 'state_id' => 3935],
                ['name' => 'Farmington', 'state_id' => 3935],
                ['name' => 'Lewistown', 'state_id' => 3935],
                ['name' => 'Liverpool', 'state_id' => 3935],
                ['name' => 'London Mills', 'state_id' => 3935],
                ['name' => 'Norris', 'state_id' => 3935],
                ['name' => 'Saint David', 'state_id' => 3935],
                ['name' => 'New Haven', 'state_id' => 3935],
                ['name' => 'Omaha', 'state_id' => 3935],
                ['name' => 'Equality', 'state_id' => 3935],
                ['name' => 'Junction', 'state_id' => 3935],
                ['name' => 'Ridgway', 'state_id' => 3935],
                ['name' => 'Shawneetown', 'state_id' => 3935],
                ['name' => 'Carrollton', 'state_id' => 3935],
                ['name' => 'Eldred', 'state_id' => 3935],
                ['name' => 'Greenfield', 'state_id' => 3935],
                ['name' => 'Hillview', 'state_id' => 3935],
                ['name' => 'Kane', 'state_id' => 3935],
                ['name' => 'Patterson', 'state_id' => 3935],
                ['name' => 'Rockbridge', 'state_id' => 3935],
                ['name' => 'Roodhouse', 'state_id' => 3935],
                ['name' => 'White Hall', 'state_id' => 3935],
                ['name' => 'Wrights', 'state_id' => 3935],
                ['name' => 'Braceville', 'state_id' => 3935],
                ['name' => 'Coal City', 'state_id' => 3935],
                ['name' => 'Gardner', 'state_id' => 3935],
                ['name' => 'Kinsman', 'state_id' => 3935],
                ['name' => 'Mazon', 'state_id' => 3935],
                ['name' => 'Minooka', 'state_id' => 3935],
                ['name' => 'Morris', 'state_id' => 3935],
                ['name' => 'South Wilmington', 'state_id' => 3935],
                ['name' => 'Verona', 'state_id' => 3935],
                ['name' => 'Broughton', 'state_id' => 3935],
                ['name' => 'Dahlgren', 'state_id' => 3935],
                ['name' => 'Dale', 'state_id' => 3935],
                ['name' => 'Mc Leansboro', 'state_id' => 3935],
                ['name' => 'Macedonia', 'state_id' => 3935],
                ['name' => 'La Harpe', 'state_id' => 3935],
                ['name' => 'Augusta', 'state_id' => 3935],
                ['name' => 'Basco', 'state_id' => 3935],
                ['name' => 'Bowen', 'state_id' => 3935],
                ['name' => 'Carthage', 'state_id' => 3935],
                ['name' => 'Colusa', 'state_id' => 3935],
                ['name' => 'Dallas City', 'state_id' => 3935],
                ['name' => 'Elvaston', 'state_id' => 3935],
                ['name' => 'Ferris', 'state_id' => 3935],
                ['name' => 'Hamilton', 'state_id' => 3935],
                ['name' => 'Nauvoo', 'state_id' => 3935],
                ['name' => 'Niota', 'state_id' => 3935],
                ['name' => 'Plymouth', 'state_id' => 3935],
                ['name' => 'Sutter', 'state_id' => 3935],
                ['name' => 'Warsaw', 'state_id' => 3935],
                ['name' => 'West Point', 'state_id' => 3935],
                ['name' => 'Cave In Rock', 'state_id' => 3935],
                ['name' => 'Elizabethtown', 'state_id' => 3935],
                ['name' => 'Karbers Ridge', 'state_id' => 3935],
                ['name' => 'Rosiclare', 'state_id' => 3935],
                ['name' => 'Biggsville', 'state_id' => 3935],
                ['name' => 'Carman', 'state_id' => 3935],
                ['name' => 'Gladstone', 'state_id' => 3935],
                ['name' => 'Lomax', 'state_id' => 3935],
                ['name' => 'Media', 'state_id' => 3935],
                ['name' => 'Oquawka', 'state_id' => 3935],
                ['name' => 'Raritan', 'state_id' => 3935],
                ['name' => 'Stronghurst', 'state_id' => 3935],
                ['name' => 'Andover', 'state_id' => 3935],
                ['name' => 'Annawan', 'state_id' => 3935],
                ['name' => 'Atkinson', 'state_id' => 3935],
                ['name' => 'Cambridge', 'state_id' => 3935],
                ['name' => 'Colona', 'state_id' => 3935],
                ['name' => 'Geneseo', 'state_id' => 3935],
                ['name' => 'Hooppole', 'state_id' => 3935],
                ['name' => 'Lynn Center', 'state_id' => 3935],
                ['name' => 'Orion', 'state_id' => 3935],
                ['name' => 'Osco', 'state_id' => 3935],
                ['name' => 'Alpha', 'state_id' => 3935],
                ['name' => 'Bishop Hill', 'state_id' => 3935],
                ['name' => 'Galva', 'state_id' => 3935],
                ['name' => 'Kewanee', 'state_id' => 3935],
                ['name' => 'Ophiem', 'state_id' => 3935],
                ['name' => 'Woodhull', 'state_id' => 3935],
                ['name' => 'Ashkum', 'state_id' => 3935],
                ['name' => 'Beaverville', 'state_id' => 3935],
                ['name' => 'Buckley', 'state_id' => 3935],
                ['name' => 'Chebanse', 'state_id' => 3935],
                ['name' => 'Cissna Park', 'state_id' => 3935],
                ['name' => 'Claytonville', 'state_id' => 3935],
                ['name' => 'Clifton', 'state_id' => 3935],
                ['name' => 'Crescent City', 'state_id' => 3935],
                ['name' => 'Danforth', 'state_id' => 3935],
                ['name' => 'Donovan', 'state_id' => 3935],
                ['name' => 'Gilman', 'state_id' => 3935],
                ['name' => 'Goodwine', 'state_id' => 3935],
                ['name' => 'Iroquois', 'state_id' => 3935],
                ['name' => 'Loda', 'state_id' => 3935],
                ['name' => 'Martinton', 'state_id' => 3935],
                ['name' => 'Milford', 'state_id' => 3935],
                ['name' => 'Onarga', 'state_id' => 3935],
                ['name' => 'Papineau', 'state_id' => 3935],
                ['name' => 'Sheldon', 'state_id' => 3935],
                ['name' => 'Stockland', 'state_id' => 3935],
                ['name' => 'Thawville', 'state_id' => 3935],
                ['name' => 'Watseka', 'state_id' => 3935],
                ['name' => 'Wellington', 'state_id' => 3935],
                ['name' => 'Woodland', 'state_id' => 3935],
                ['name' => 'Carbondale', 'state_id' => 3935],
                ['name' => 'Ava', 'state_id' => 3935],
                ['name' => 'Campbell Hill', 'state_id' => 3935],
                ['name' => 'De Soto', 'state_id' => 3935],
                ['name' => 'Dowell', 'state_id' => 3935],
                ['name' => 'Elkville', 'state_id' => 3935],
                ['name' => 'Gorham', 'state_id' => 3935],
                ['name' => 'Grand Tower', 'state_id' => 3935],
                ['name' => 'Jacob', 'state_id' => 3935],
                ['name' => 'Makanda', 'state_id' => 3935],
                ['name' => 'Murphysboro', 'state_id' => 3935],
                ['name' => 'Oraville', 'state_id' => 3935],
                ['name' => 'Pomona', 'state_id' => 3935],
                ['name' => 'Vergennes', 'state_id' => 3935],
                ['name' => 'Hidalgo', 'state_id' => 3935],
                ['name' => 'Newton', 'state_id' => 3935],
                ['name' => 'Sainte Marie', 'state_id' => 3935],
                ['name' => 'West Liberty', 'state_id' => 3935],
                ['name' => 'Wheeler', 'state_id' => 3935],
                ['name' => 'Willow Hill', 'state_id' => 3935],
                ['name' => 'Yale', 'state_id' => 3935],
                ['name' => 'Belle Rive', 'state_id' => 3935],
                ['name' => 'Bluford', 'state_id' => 3935],
                ['name' => 'Bonnie', 'state_id' => 3935],
                ['name' => 'Dix', 'state_id' => 3935],
                ['name' => 'Ina', 'state_id' => 3935],
                ['name' => 'Mount Vernon', 'state_id' => 3935],
                ['name' => 'Nason', 'state_id' => 3935],
                ['name' => 'Opdyke', 'state_id' => 3935],
                ['name' => 'Scheller', 'state_id' => 3935],
                ['name' => 'Texico', 'state_id' => 3935],
                ['name' => 'Waltonville', 'state_id' => 3935],
                ['name' => 'Woodlawn', 'state_id' => 3935],
                ['name' => 'Brighton', 'state_id' => 3935],
                ['name' => 'Dow', 'state_id' => 3935],
                ['name' => 'Elsah', 'state_id' => 3935],
                ['name' => 'Fidelity', 'state_id' => 3935],
                ['name' => 'Fieldon', 'state_id' => 3935],
                ['name' => 'Grafton', 'state_id' => 3935],
                ['name' => 'Jerseyville', 'state_id' => 3935],
                ['name' => 'Medora', 'state_id' => 3935],
                ['name' => 'Apple River', 'state_id' => 3935],
                ['name' => 'East Dubuque', 'state_id' => 3935],
                ['name' => 'Elizabeth', 'state_id' => 3935],
                ['name' => 'Galena', 'state_id' => 3935],
                ['name' => 'Hanover', 'state_id' => 3935],
                ['name' => 'Nora', 'state_id' => 3935],
                ['name' => 'Scales Mound', 'state_id' => 3935],
                ['name' => 'Stockton', 'state_id' => 3935],
                ['name' => 'Warren', 'state_id' => 3935],
                ['name' => 'Belknap', 'state_id' => 3935],
                ['name' => 'Boles', 'state_id' => 3935],
                ['name' => 'Buncombe', 'state_id' => 3935],
                ['name' => 'Cypress', 'state_id' => 3935],
                ['name' => 'Goreville', 'state_id' => 3935],
                ['name' => 'Grantsburg', 'state_id' => 3935],
                ['name' => 'New Burnside', 'state_id' => 3935],
                ['name' => 'Ozark', 'state_id' => 3935],
                ['name' => 'Simpson', 'state_id' => 3935],
                ['name' => 'Vienna', 'state_id' => 3935],
                ['name' => 'Burlington', 'state_id' => 3935],
                ['name' => 'Carpentersville', 'state_id' => 3935],
                ['name' => 'Dundee', 'state_id' => 3935],
                ['name' => 'Elburn', 'state_id' => 3935],
                ['name' => 'Elgin', 'state_id' => 3935],
                ['name' => 'Geneva', 'state_id' => 3935],
                ['name' => 'Gilberts', 'state_id' => 3935],
                ['name' => 'Hampshire', 'state_id' => 3935],
                ['name' => 'Kaneville', 'state_id' => 3935],
                ['name' => 'Lafox', 'state_id' => 3935],
                ['name' => 'Maple Park', 'state_id' => 3935],
                ['name' => 'Saint Charles', 'state_id' => 3935],
                ['name' => 'South Elgin', 'state_id' => 3935],
                ['name' => 'Wasco', 'state_id' => 3935],
                ['name' => 'Batavia', 'state_id' => 3935],
                ['name' => 'Big Rock', 'state_id' => 3935],
                ['name' => 'Mooseheart', 'state_id' => 3935],
                ['name' => 'North Aurora', 'state_id' => 3935],
                ['name' => 'Sugar Grove', 'state_id' => 3935],
                ['name' => 'Kankakee', 'state_id' => 3935],
                ['name' => 'Aroma Park', 'state_id' => 3935],
                ['name' => 'Bonfield', 'state_id' => 3935],
                ['name' => 'Bourbonnais', 'state_id' => 3935],
                ['name' => 'Bradley', 'state_id' => 3935],
                ['name' => 'Buckingham', 'state_id' => 3935],
                ['name' => 'Essex', 'state_id' => 3935],
                ['name' => 'Grant Park', 'state_id' => 3935],
                ['name' => 'Herscher', 'state_id' => 3935],
                ['name' => 'Hopkins Park', 'state_id' => 3935],
                ['name' => 'Manteno', 'state_id' => 3935],
                ['name' => 'Momence', 'state_id' => 3935],
                ['name' => 'Pembroke Township', 'state_id' => 3935],
                ['name' => 'Reddick', 'state_id' => 3935],
                ['name' => 'Saint Anne', 'state_id' => 3935],
                ['name' => 'Union Hill', 'state_id' => 3935],
                ['name' => 'Bristol', 'state_id' => 3935],
                ['name' => 'Millbrook', 'state_id' => 3935],
                ['name' => 'Millington', 'state_id' => 3935],
                ['name' => 'Montgomery', 'state_id' => 3935],
                ['name' => 'Newark', 'state_id' => 3935],
                ['name' => 'Oswego', 'state_id' => 3935],
                ['name' => 'Plano', 'state_id' => 3935],
                ['name' => 'Yorkville', 'state_id' => 3935],
                ['name' => 'Galesburg', 'state_id' => 3935],
                ['name' => 'Abingdon', 'state_id' => 3935],
                ['name' => 'Altona', 'state_id' => 3935],
                ['name' => 'Dahinda', 'state_id' => 3935],
                ['name' => 'East Galesburg', 'state_id' => 3935],
                ['name' => 'Gilson', 'state_id' => 3935],
                ['name' => 'Henderson', 'state_id' => 3935],
                ['name' => 'Knoxville', 'state_id' => 3935],
                ['name' => 'Maquon', 'state_id' => 3935],
                ['name' => 'Oneida', 'state_id' => 3935],
                ['name' => 'Rio', 'state_id' => 3935],
                ['name' => 'Saint Augustine', 'state_id' => 3935],
                ['name' => 'Victoria', 'state_id' => 3935],
                ['name' => 'Wataga', 'state_id' => 3935],
                ['name' => 'Williamsfield', 'state_id' => 3935],
                ['name' => 'Yates City', 'state_id' => 3935],
                ['name' => 'Antioch', 'state_id' => 3935],
                ['name' => 'Barrington', 'state_id' => 3935],
                ['name' => 'Deerfield', 'state_id' => 3935],
                ['name' => 'Fox Lake', 'state_id' => 3935],
                ['name' => 'Grayslake', 'state_id' => 3935],
                ['name' => 'Gurnee', 'state_id' => 3935],
                ['name' => 'Highland Park', 'state_id' => 3935],
                ['name' => 'Fort Sheridan', 'state_id' => 3935],
                ['name' => 'Highwood', 'state_id' => 3935],
                ['name' => 'Ingleside', 'state_id' => 3935],
                ['name' => 'Island Lake', 'state_id' => 3935],
                ['name' => 'Lake Bluff', 'state_id' => 3935],
                ['name' => 'Lake Forest', 'state_id' => 3935],
                ['name' => 'Lake Villa', 'state_id' => 3935],
                ['name' => 'Lake Zurich', 'state_id' => 3935],
                ['name' => 'Libertyville', 'state_id' => 3935],
                ['name' => 'Mundelein', 'state_id' => 3935],
                ['name' => 'Vernon Hills', 'state_id' => 3935],
                ['name' => 'North Chicago', 'state_id' => 3935],
                ['name' => 'Lincolnshire', 'state_id' => 3935],
                ['name' => 'Round Lake', 'state_id' => 3935],
                ['name' => 'Russell', 'state_id' => 3935],
                ['name' => 'Waukegan', 'state_id' => 3935],
                ['name' => 'Wadsworth', 'state_id' => 3935],
                ['name' => 'Wauconda', 'state_id' => 3935],
                ['name' => 'Great Lakes', 'state_id' => 3935],
                ['name' => 'Buffalo Grove', 'state_id' => 3935],
                ['name' => 'Winthrop Harbor', 'state_id' => 3935],
                ['name' => 'Zion', 'state_id' => 3935],
                ['name' => 'Ransom', 'state_id' => 3935],
                ['name' => 'Earlville', 'state_id' => 3935],
                ['name' => 'Leland', 'state_id' => 3935],
                ['name' => 'Serena', 'state_id' => 3935],
                ['name' => 'Sheridan', 'state_id' => 3935],
                ['name' => 'Wedron', 'state_id' => 3935],
                ['name' => 'La Salle', 'state_id' => 3935],
                ['name' => 'Cedar Point', 'state_id' => 3935],
                ['name' => 'Dana', 'state_id' => 3935],
                ['name' => 'Grand Ridge', 'state_id' => 3935],
                ['name' => 'Leonore', 'state_id' => 3935],
                ['name' => 'Lostant', 'state_id' => 3935],
                ['name' => 'Marseilles', 'state_id' => 3935],
                ['name' => 'Mendota', 'state_id' => 3935],
                ['name' => 'Oglesby', 'state_id' => 3935],
                ['name' => 'Ottawa', 'state_id' => 3935],
                ['name' => 'Peru', 'state_id' => 3935],
                ['name' => 'Rutland', 'state_id' => 3935],
                ['name' => 'Seneca', 'state_id' => 3935],
                ['name' => 'Streator', 'state_id' => 3935],
                ['name' => 'Tonica', 'state_id' => 3935],
                ['name' => 'Triumph', 'state_id' => 3935],
                ['name' => 'Troy Grove', 'state_id' => 3935],
                ['name' => 'Utica', 'state_id' => 3935],
                ['name' => 'Bridgeport', 'state_id' => 3935],
                ['name' => 'Lawrenceville', 'state_id' => 3935],
                ['name' => 'Saint Francisville', 'state_id' => 3935],
                ['name' => 'Sumner', 'state_id' => 3935],
                ['name' => 'Lee', 'state_id' => 3935],
                ['name' => 'Steward', 'state_id' => 3935],
                ['name' => 'Ashton', 'state_id' => 3935],
                ['name' => 'Dixon', 'state_id' => 3935],
                ['name' => 'Franklin Grove', 'state_id' => 3935],
                ['name' => 'Harmon', 'state_id' => 3935],
                ['name' => 'Nachusa', 'state_id' => 3935],
                ['name' => 'Amboy', 'state_id' => 3935],
                ['name' => 'Compton', 'state_id' => 3935],
                ['name' => 'Eldena', 'state_id' => 3935],
                ['name' => 'Lee Center', 'state_id' => 3935],
                ['name' => 'Paw Paw', 'state_id' => 3935],
                ['name' => 'Sublette', 'state_id' => 3935],
                ['name' => 'West Brooklyn', 'state_id' => 3935],
                ['name' => 'Dwight', 'state_id' => 3935],
                ['name' => 'Odell', 'state_id' => 3935],
                ['name' => 'Campus', 'state_id' => 3935],
                ['name' => 'Chatsworth', 'state_id' => 3935],
                ['name' => 'Cullom', 'state_id' => 3935],
                ['name' => 'Emington', 'state_id' => 3935],
                ['name' => 'Ancona', 'state_id' => 3935],
                ['name' => 'Blackstone', 'state_id' => 3935],
                ['name' => 'Cornell', 'state_id' => 3935],
                ['name' => 'Long Point', 'state_id' => 3935],
                ['name' => 'Fairbury', 'state_id' => 3935],
                ['name' => 'Flanagan', 'state_id' => 3935],
                ['name' => 'Forrest', 'state_id' => 3935],
                ['name' => 'Graymont', 'state_id' => 3935],
                ['name' => 'Pontiac', 'state_id' => 3935],
                ['name' => 'Saunemin', 'state_id' => 3935],
                ['name' => 'Strawn', 'state_id' => 3935],
                ['name' => 'Atlanta', 'state_id' => 3935],
                ['name' => 'Lawndale', 'state_id' => 3935],
                ['name' => 'Beason', 'state_id' => 3935],
                ['name' => 'Chestnut', 'state_id' => 3935],
                ['name' => 'Cornland', 'state_id' => 3935],
                ['name' => 'Lake Fork', 'state_id' => 3935],
                ['name' => 'Latham', 'state_id' => 3935],
                ['name' => 'Mount Pulaski', 'state_id' => 3935],
                ['name' => 'Elkhart', 'state_id' => 3935],
                ['name' => 'Emden', 'state_id' => 3935],
                ['name' => 'Hartsburg', 'state_id' => 3935],
                ['name' => 'Lincoln', 'state_id' => 3935],
                ['name' => 'Middletown', 'state_id' => 3935],
                ['name' => 'New Holland', 'state_id' => 3935],
                ['name' => 'Adair', 'state_id' => 3935],
                ['name' => 'Bardolph', 'state_id' => 3935],
                ['name' => 'Blandinsville', 'state_id' => 3935],
                ['name' => 'Bushnell', 'state_id' => 3935],
                ['name' => 'Good Hope', 'state_id' => 3935],
                ['name' => 'Industry', 'state_id' => 3935],
                ['name' => 'Macomb', 'state_id' => 3935],
                ['name' => 'Prairie City', 'state_id' => 3935],
                ['name' => 'Sciota', 'state_id' => 3935],
                ['name' => 'Colchester', 'state_id' => 3935],
                ['name' => 'Tennessee', 'state_id' => 3935],
                ['name' => 'Alden', 'state_id' => 3935],
                ['name' => 'Crystal Lake', 'state_id' => 3935],
                ['name' => 'Cary', 'state_id' => 3935],
                ['name' => 'Fox River Grove', 'state_id' => 3935],
                ['name' => 'Harvard', 'state_id' => 3935],
                ['name' => 'Hebron', 'state_id' => 3935],
                ['name' => 'Mchenry', 'state_id' => 3935],
                ['name' => 'Richmond', 'state_id' => 3935],
                ['name' => 'Ringwood', 'state_id' => 3935],
                ['name' => 'Spring Grove', 'state_id' => 3935],
                ['name' => 'Wonder Lake', 'state_id' => 3935],
                ['name' => 'Woodstock', 'state_id' => 3935],
                ['name' => 'Algonquin', 'state_id' => 3935],
                ['name' => 'Huntley', 'state_id' => 3935],
                ['name' => 'Marengo', 'state_id' => 3935],
                ['name' => 'Lake In The Hills', 'state_id' => 3935],
                ['name' => 'Union', 'state_id' => 3935],
                ['name' => 'Bloomington', 'state_id' => 3935],
                ['name' => 'Anchor', 'state_id' => 3935],
                ['name' => 'Arrowsmith', 'state_id' => 3935],
                ['name' => 'Bellflower', 'state_id' => 3935],
                ['name' => 'Carlock', 'state_id' => 3935],
                ['name' => 'Chenoa', 'state_id' => 3935],
                ['name' => 'Colfax', 'state_id' => 3935],
                ['name' => 'Cooksville', 'state_id' => 3935],
                ['name' => 'Cropsey', 'state_id' => 3935],
                ['name' => 'Danvers', 'state_id' => 3935],
                ['name' => 'Downs', 'state_id' => 3935],
                ['name' => 'Ellsworth', 'state_id' => 3935],
                ['name' => 'Gridley', 'state_id' => 3935],
                ['name' => 'Heyworth', 'state_id' => 3935],
                ['name' => 'Hudson', 'state_id' => 3935],
                ['name' => 'Le Roy', 'state_id' => 3935],
                ['name' => 'Lexington', 'state_id' => 3935],
                ['name' => 'Mc Lean', 'state_id' => 3935],
                ['name' => 'Merna', 'state_id' => 3935],
                ['name' => 'Normal', 'state_id' => 3935],
                ['name' => 'Saybrook', 'state_id' => 3935],
                ['name' => 'Shirley', 'state_id' => 3935],
                ['name' => 'Stanford', 'state_id' => 3935],
                ['name' => 'Towanda', 'state_id' => 3935],
                ['name' => 'Maroa', 'state_id' => 3935],
                ['name' => 'Argenta', 'state_id' => 3935],
                ['name' => 'Blue Mound', 'state_id' => 3935],
                ['name' => 'Boody', 'state_id' => 3935],
                ['name' => 'Decatur', 'state_id' => 3935],
                ['name' => 'Elwin', 'state_id' => 3935],
                ['name' => 'Forsyth', 'state_id' => 3935],
                ['name' => 'Harristown', 'state_id' => 3935],
                ['name' => 'Macon', 'state_id' => 3935],
                ['name' => 'Mt Zion', 'state_id' => 3935],
                ['name' => 'Niantic', 'state_id' => 3935],
                ['name' => 'Oreana', 'state_id' => 3935],
                ['name' => 'Warrensburg', 'state_id' => 3935],
                ['name' => 'Benld', 'state_id' => 3935],
                ['name' => 'Bunker Hill', 'state_id' => 3935],
                ['name' => 'Eagarville', 'state_id' => 3935],
                ['name' => 'Gillespie', 'state_id' => 3935],
                ['name' => 'Mount Olive', 'state_id' => 3935],
                ['name' => 'Piasa', 'state_id' => 3935],
                ['name' => 'Sawyerville', 'state_id' => 3935],
                ['name' => 'Staunton', 'state_id' => 3935],
                ['name' => 'Wilsonville', 'state_id' => 3935],
                ['name' => 'Carlinville', 'state_id' => 3935],
                ['name' => 'Chesterfield', 'state_id' => 3935],
                ['name' => 'Girard', 'state_id' => 3935],
                ['name' => 'Hettick', 'state_id' => 3935],
                ['name' => 'Modesto', 'state_id' => 3935],
                ['name' => 'Nilwood', 'state_id' => 3935],
                ['name' => 'Palmyra', 'state_id' => 3935],
                ['name' => 'Scottville', 'state_id' => 3935],
                ['name' => 'Shipman', 'state_id' => 3935],
                ['name' => 'Virden', 'state_id' => 3935],
                ['name' => 'Alhambra', 'state_id' => 3935],
                ['name' => 'Alton', 'state_id' => 3935],
                ['name' => 'Bethalto', 'state_id' => 3935],
                ['name' => 'Cottage Hills', 'state_id' => 3935],
                ['name' => 'Dorsey', 'state_id' => 3935],
                ['name' => 'East Alton', 'state_id' => 3935],
                ['name' => 'Edwardsville', 'state_id' => 3935],
                ['name' => 'Glen Carbon', 'state_id' => 3935],
                ['name' => 'Godfrey', 'state_id' => 3935],
                ['name' => 'Granite City', 'state_id' => 3935],
                ['name' => 'Hamel', 'state_id' => 3935],
                ['name' => 'Hartford', 'state_id' => 3935],
                ['name' => 'Livingston', 'state_id' => 3935],
                ['name' => 'Madison', 'state_id' => 3935],
                ['name' => 'Marine', 'state_id' => 3935],
                ['name' => 'Maryville', 'state_id' => 3935],
                ['name' => 'Moro', 'state_id' => 3935],
                ['name' => 'New Douglas', 'state_id' => 3935],
                ['name' => 'Roxana', 'state_id' => 3935],
                ['name' => 'South Roxana', 'state_id' => 3935],
                ['name' => 'Venice', 'state_id' => 3935],
                ['name' => 'Wood River', 'state_id' => 3935],
                ['name' => 'Worden', 'state_id' => 3935],
                ['name' => 'Collinsville', 'state_id' => 3935],
                ['name' => 'Highland', 'state_id' => 3935],
                ['name' => 'Saint Jacob', 'state_id' => 3935],
                ['name' => 'Troy', 'state_id' => 3935],
                ['name' => 'Centralia', 'state_id' => 3935],
                ['name' => 'Alma', 'state_id' => 3935],
                ['name' => 'Iuka', 'state_id' => 3935],
                ['name' => 'Kell', 'state_id' => 3935],
                ['name' => 'Kinmundy', 'state_id' => 3935],
                ['name' => 'Odin', 'state_id' => 3935],
                ['name' => 'Patoka', 'state_id' => 3935],
                ['name' => 'Salem', 'state_id' => 3935],
                ['name' => 'Sandoval', 'state_id' => 3935],
                ['name' => 'Vernon', 'state_id' => 3935],
                ['name' => 'Walnut Hill', 'state_id' => 3935],
                ['name' => 'Toluca', 'state_id' => 3935],
                ['name' => 'Varna', 'state_id' => 3935],
                ['name' => 'Wenona', 'state_id' => 3935],
                ['name' => 'Camp Grove', 'state_id' => 3935],
                ['name' => 'Henry', 'state_id' => 3935],
                ['name' => 'Lacon', 'state_id' => 3935],
                ['name' => 'La Rose', 'state_id' => 3935],
                ['name' => 'Sparland', 'state_id' => 3935],
                ['name' => 'Washburn', 'state_id' => 3935],
                ['name' => 'Forest City', 'state_id' => 3935],
                ['name' => 'Manito', 'state_id' => 3935],
                ['name' => 'Topeka', 'state_id' => 3935],
                ['name' => 'Bath', 'state_id' => 3935],
                ['name' => 'Easton', 'state_id' => 3935],
                ['name' => 'Havana', 'state_id' => 3935],
                ['name' => 'Kilbourne', 'state_id' => 3935],
                ['name' => 'Mason City', 'state_id' => 3935],
                ['name' => 'San Jose', 'state_id' => 3935],
                ['name' => 'Brookport', 'state_id' => 3935],
                ['name' => 'Joppa', 'state_id' => 3935],
                ['name' => 'Metropolis', 'state_id' => 3935],
                ['name' => 'Athens', 'state_id' => 3935],
                ['name' => 'Greenview', 'state_id' => 3935],
                ['name' => "Lincoln'S New Salem", 'state_id' => 3935],
                ['name' => 'Oakford', 'state_id' => 3935],
                ['name' => 'Petersburg', 'state_id' => 3935],
                ['name' => 'Tallula', 'state_id' => 3935],
                ['name' => 'Aledo', 'state_id' => 3935],
                ['name' => 'Joy', 'state_id' => 3935],
                ['name' => 'Matherville', 'state_id' => 3935],
                ['name' => 'New Boston', 'state_id' => 3935],
                ['name' => 'Preemption', 'state_id' => 3935],
                ['name' => 'Sherrard', 'state_id' => 3935],
                ['name' => 'Alexis', 'state_id' => 3935],
                ['name' => 'Keithsburg', 'state_id' => 3935],
                ['name' => 'New Windsor', 'state_id' => 3935],
                ['name' => 'North Henderson', 'state_id' => 3935],
                ['name' => 'Seaton', 'state_id' => 3935],
                ['name' => 'Viola', 'state_id' => 3935],
                ['name' => 'Columbia', 'state_id' => 3935],
                ['name' => 'Fults', 'state_id' => 3935],
                ['name' => 'Hecker', 'state_id' => 3935],
                ['name' => 'Maeystown', 'state_id' => 3935],
                ['name' => 'Renault', 'state_id' => 3935],
                ['name' => 'Valmeyer', 'state_id' => 3935],
                ['name' => 'Waterloo', 'state_id' => 3935],
                ['name' => 'Butler', 'state_id' => 3935],
                ['name' => 'Coffeen', 'state_id' => 3935],
                ['name' => 'Fillmore', 'state_id' => 3935],
                ['name' => 'Hillsboro', 'state_id' => 3935],
                ['name' => 'Irving', 'state_id' => 3935],
                ['name' => 'Litchfield', 'state_id' => 3935],
                ['name' => 'Nokomis', 'state_id' => 3935],
                ['name' => 'Ohlman', 'state_id' => 3935],
                ['name' => 'Panama', 'state_id' => 3935],
                ['name' => 'Taylor Springs', 'state_id' => 3935],
                ['name' => 'Walshville', 'state_id' => 3935],
                ['name' => 'Witt', 'state_id' => 3935],
                ['name' => 'Farmersville', 'state_id' => 3935],
                ['name' => 'Harvel', 'state_id' => 3935],
                ['name' => 'Raymond', 'state_id' => 3935],
                ['name' => 'Waggoner', 'state_id' => 3935],
                ['name' => 'Alexander', 'state_id' => 3935],
                ['name' => 'Chapin', 'state_id' => 3935],
                ['name' => 'Concord', 'state_id' => 3935],
                ['name' => 'Franklin', 'state_id' => 3935],
                ['name' => 'Jacksonville', 'state_id' => 3935],
                ['name' => 'Literberry', 'state_id' => 3935],
                ['name' => 'Meredosia', 'state_id' => 3935],
                ['name' => 'Murrayville', 'state_id' => 3935],
                ['name' => 'Waverly', 'state_id' => 3935],
                ['name' => 'Woodson', 'state_id' => 3935],
                ['name' => 'Bethany', 'state_id' => 3935],
                ['name' => 'Dalton City', 'state_id' => 3935],
                ['name' => 'Gays', 'state_id' => 3935],
                ['name' => 'Lovington', 'state_id' => 3935],
                ['name' => 'Sullivan', 'state_id' => 3935],
                ['name' => 'Creston', 'state_id' => 3935],
                ['name' => 'Baileyville', 'state_id' => 3935],
                ['name' => 'Byron', 'state_id' => 3935],
                ['name' => 'Chana', 'state_id' => 3935],
                ['name' => 'Davis Junction', 'state_id' => 3935],
                ['name' => 'Forreston', 'state_id' => 3935],
                ['name' => 'Holcomb', 'state_id' => 3935],
                ['name' => 'Leaf River', 'state_id' => 3935],
                ['name' => 'Lindenwood', 'state_id' => 3935],
                ['name' => 'Monroe Center', 'state_id' => 3935],
                ['name' => 'Mount Morris', 'state_id' => 3935],
                ['name' => 'Oregon', 'state_id' => 3935],
                ['name' => 'Polo', 'state_id' => 3935],
                ['name' => 'Rochelle', 'state_id' => 3935],
                ['name' => 'Stillman Valley', 'state_id' => 3935],
                ['name' => 'Woosung', 'state_id' => 3935],
                ['name' => 'Laura', 'state_id' => 3935],
                ['name' => 'Brimfield', 'state_id' => 3935],
                ['name' => 'Chillicothe', 'state_id' => 3935],
                ['name' => 'Dunlap', 'state_id' => 3935],
                ['name' => 'Edelstein', 'state_id' => 3935],
                ['name' => 'Edwards', 'state_id' => 3935],
                ['name' => 'Elmwood', 'state_id' => 3935],
                ['name' => 'Glasford', 'state_id' => 3935],
                ['name' => 'Hanna City', 'state_id' => 3935],
                ['name' => 'Kingston Mines', 'state_id' => 3935],
                ['name' => 'Mapleton', 'state_id' => 3935],
                ['name' => 'Mossville', 'state_id' => 3935],
                ['name' => 'Rome', 'state_id' => 3935],
                ['name' => 'Trivoli', 'state_id' => 3935],
                ['name' => 'Peoria', 'state_id' => 3935],
                ['name' => 'Peoria Heights', 'state_id' => 3935],
                ['name' => 'Cutler', 'state_id' => 3935],
                ['name' => 'Pinckneyville', 'state_id' => 3935],
                ['name' => 'Du Quoin', 'state_id' => 3935],
                ['name' => 'Tamaroa', 'state_id' => 3935],
                ['name' => 'Willisville', 'state_id' => 3935],
                ['name' => 'Bement', 'state_id' => 3935],
                ['name' => 'Cerro Gordo', 'state_id' => 3935],
                ['name' => 'Cisco', 'state_id' => 3935],
                ['name' => 'De Land', 'state_id' => 3935],
                ['name' => 'Mansfield', 'state_id' => 3935],
                ['name' => 'Milmine', 'state_id' => 3935],
                ['name' => 'Monticello', 'state_id' => 3935],
                ['name' => 'White Heath', 'state_id' => 3935],
                ['name' => 'Hammond', 'state_id' => 3935],
                ['name' => 'La Place', 'state_id' => 3935],
                ['name' => 'Barry', 'state_id' => 3935],
                ['name' => 'Baylis', 'state_id' => 3935],
                ['name' => 'Chambersburg', 'state_id' => 3935],
                ['name' => 'Griggsville', 'state_id' => 3935],
                ['name' => 'Hull', 'state_id' => 3935],
                ['name' => 'Kinderhook', 'state_id' => 3935],
                ['name' => 'Milton', 'state_id' => 3935],
                ['name' => 'Nebo', 'state_id' => 3935],
                ['name' => 'New Canton', 'state_id' => 3935],
                ['name' => 'New Salem', 'state_id' => 3935],
                ['name' => 'Pearl', 'state_id' => 3935],
                ['name' => 'Perry', 'state_id' => 3935],
                ['name' => 'Pittsfield', 'state_id' => 3935],
                ['name' => 'Pleasant Hill', 'state_id' => 3935],
                ['name' => 'Rockport', 'state_id' => 3935],
                ['name' => 'Eddyville', 'state_id' => 3935],
                ['name' => 'Golconda', 'state_id' => 3935],
                ['name' => 'Herod', 'state_id' => 3935],
                ['name' => 'Grand Chain', 'state_id' => 3935],
                ['name' => 'Karnak', 'state_id' => 3935],
                ['name' => 'Mound City', 'state_id' => 3935],
                ['name' => 'Mounds', 'state_id' => 3935],
                ['name' => 'Olmsted', 'state_id' => 3935],
                ['name' => 'Perks', 'state_id' => 3935],
                ['name' => 'Pulaski', 'state_id' => 3935],
                ['name' => 'Ullin', 'state_id' => 3935],
                ['name' => 'Villa Ridge', 'state_id' => 3935],
                ['name' => 'Granville', 'state_id' => 3935],
                ['name' => 'Hennepin', 'state_id' => 3935],
                ['name' => 'Mc Nabb', 'state_id' => 3935],
                ['name' => 'Magnolia', 'state_id' => 3935],
                ['name' => 'Mark', 'state_id' => 3935],
                ['name' => 'Standard', 'state_id' => 3935],
                ['name' => 'Putnam', 'state_id' => 3935],
                ['name' => 'Baldwin', 'state_id' => 3935],
                ['name' => 'Chester', 'state_id' => 3935],
                ['name' => 'Coulterville', 'state_id' => 3935],
                ['name' => 'Ellis Grove', 'state_id' => 3935],
                ['name' => 'Evansville', 'state_id' => 3935],
                ['name' => 'Menard', 'state_id' => 3935],
                ['name' => 'Modoc', 'state_id' => 3935],
                ['name' => 'Percy', 'state_id' => 3935],
                ['name' => 'Prairie Du Rocher', 'state_id' => 3935],
                ['name' => 'Red Bud', 'state_id' => 3935],
                ['name' => 'Rockwood', 'state_id' => 3935],
                ['name' => 'Sparta', 'state_id' => 3935],
                ['name' => 'Steeleville', 'state_id' => 3935],
                ['name' => 'Tilden', 'state_id' => 3935],
                ['name' => 'Walsh', 'state_id' => 3935],
                ['name' => 'Calhoun', 'state_id' => 3935],
                ['name' => 'Claremont', 'state_id' => 3935],
                ['name' => 'Dundas', 'state_id' => 3935],
                ['name' => 'Olney', 'state_id' => 3935],
                ['name' => 'Parkersburg', 'state_id' => 3935],
                ['name' => 'Noble', 'state_id' => 3935],
                ['name' => 'Rock Island', 'state_id' => 3935],
                ['name' => 'Andalusia', 'state_id' => 3935],
                ['name' => 'Barstow', 'state_id' => 3935],
                ['name' => 'Buffalo Prairie', 'state_id' => 3935],
                ['name' => 'Carbon Cliff', 'state_id' => 3935],
                ['name' => 'Coal Valley', 'state_id' => 3935],
                ['name' => 'Cordova', 'state_id' => 3935],
                ['name' => 'East Moline', 'state_id' => 3935],
                ['name' => 'Hampton', 'state_id' => 3935],
                ['name' => 'Hillsdale', 'state_id' => 3935],
                ['name' => 'Illinois City', 'state_id' => 3935],
                ['name' => 'Milan', 'state_id' => 3935],
                ['name' => 'Moline', 'state_id' => 3935],
                ['name' => 'Port Byron', 'state_id' => 3935],
                ['name' => 'Rapids City', 'state_id' => 3935],
                ['name' => 'Reynolds', 'state_id' => 3935],
                ['name' => 'Silvis', 'state_id' => 3935],
                ['name' => 'Taylor Ridge', 'state_id' => 3935],
                ['name' => 'Lovejoy', 'state_id' => 3935],
                ['name' => 'National Stock Yards', 'state_id' => 3935],
                ['name' => 'East Saint Louis', 'state_id' => 3935],
                ['name' => 'Fairview Heights', 'state_id' => 3935],
                ['name' => 'Belleville', 'state_id' => 3935],
                ['name' => 'Scott Air Force Base', 'state_id' => 3935],
                ['name' => 'Caseyville', 'state_id' => 3935],
                ['name' => 'Dupo', 'state_id' => 3935],
                ['name' => 'East Carondelet', 'state_id' => 3935],
                ['name' => 'Freeburg', 'state_id' => 3935],
                ['name' => 'Lebanon', 'state_id' => 3935],
                ['name' => 'Lenzburg', 'state_id' => 3935],
                ['name' => 'Marissa', 'state_id' => 3935],
                ['name' => 'Mascoutah', 'state_id' => 3935],
                ['name' => 'Millstadt', 'state_id' => 3935],
                ['name' => 'New Athens', 'state_id' => 3935],
                ['name' => 'O Fallon', 'state_id' => 3935],
                ['name' => 'Saint Libory', 'state_id' => 3935],
                ['name' => 'Smithton', 'state_id' => 3935],
                ['name' => 'Summerfield', 'state_id' => 3935],
                ['name' => 'Carrier Mills', 'state_id' => 3935],
                ['name' => 'Eldorado', 'state_id' => 3935],
                ['name' => 'Galatia', 'state_id' => 3935],
                ['name' => 'Harrisburg', 'state_id' => 3935],
                ['name' => 'Muddy', 'state_id' => 3935],
                ['name' => 'Raleigh', 'state_id' => 3935],
                ['name' => 'Stonefort', 'state_id' => 3935],
                ['name' => 'Buffalo', 'state_id' => 3935],
                ['name' => 'Dawson', 'state_id' => 3935],
                ['name' => 'Divernon', 'state_id' => 3935],
                ['name' => 'Glenarm', 'state_id' => 3935],
                ['name' => 'Illiopolis', 'state_id' => 3935],
                ['name' => 'Mechanicsburg', 'state_id' => 3935],
                ['name' => 'Pawnee', 'state_id' => 3935],
                ['name' => 'Riverton', 'state_id' => 3935],
                ['name' => 'Rochester', 'state_id' => 3935],
                ['name' => 'Auburn', 'state_id' => 3935],
                ['name' => 'Cantrall', 'state_id' => 3935],
                ['name' => 'Chatham', 'state_id' => 3935],
                ['name' => 'Loami', 'state_id' => 3935],
                ['name' => 'Lowder', 'state_id' => 3935],
                ['name' => 'New Berlin', 'state_id' => 3935],
                ['name' => 'Pleasant Plains', 'state_id' => 3935],
                ['name' => 'Sherman', 'state_id' => 3935],
                ['name' => 'Thayer', 'state_id' => 3935],
                ['name' => 'Williamsville', 'state_id' => 3935],
                ['name' => 'Springfield', 'state_id' => 3935],
                ['name' => 'Littleton', 'state_id' => 3935],
                ['name' => 'Camden', 'state_id' => 3935],
                ['name' => 'Huntsville', 'state_id' => 3935],
                ['name' => 'Browning', 'state_id' => 3935],
                ['name' => 'Frederick', 'state_id' => 3935],
                ['name' => 'Rushville', 'state_id' => 3935],
                ['name' => 'Alsey', 'state_id' => 3935],
                ['name' => 'Bluffs', 'state_id' => 3935],
                ['name' => 'Manchester', 'state_id' => 3935],
                ['name' => 'Winchester', 'state_id' => 3935],
                ['name' => 'Windsor', 'state_id' => 3935],
                ['name' => 'Cowden', 'state_id' => 3935],
                ['name' => 'Herrick', 'state_id' => 3935],
                ['name' => 'Lakewood', 'state_id' => 3935],
                ['name' => 'Mode', 'state_id' => 3935],
                ['name' => 'Sigel', 'state_id' => 3935],
                ['name' => 'Stewardson', 'state_id' => 3935],
                ['name' => 'Strasburg', 'state_id' => 3935],
                ['name' => 'Findlay', 'state_id' => 3935],
                ['name' => 'Moweaqua', 'state_id' => 3935],
                ['name' => 'Oconee', 'state_id' => 3935],
                ['name' => 'Shelbyville', 'state_id' => 3935],
                ['name' => 'Tower Hill', 'state_id' => 3935],
                ['name' => 'Bradford', 'state_id' => 3935],
                ['name' => 'Castleton', 'state_id' => 3935],
                ['name' => 'La Fayette', 'state_id' => 3935],
                ['name' => 'Speer', 'state_id' => 3935],
                ['name' => 'Toulon', 'state_id' => 3935],
                ['name' => 'Wyoming', 'state_id' => 3935],
                ['name' => 'Princeville', 'state_id' => 3935],
                ['name' => 'Cedarville', 'state_id' => 3935],
                ['name' => 'Dakota', 'state_id' => 3935],
                ['name' => 'Davis', 'state_id' => 3935],
                ['name' => 'Eleroy', 'state_id' => 3935],
                ['name' => 'Freeport', 'state_id' => 3935],
                ['name' => 'German Valley', 'state_id' => 3935],
                ['name' => 'Kent', 'state_id' => 3935],
                ['name' => 'Lena', 'state_id' => 3935],
                ['name' => 'Mc Connell', 'state_id' => 3935],
                ['name' => 'Orangeville', 'state_id' => 3935],
                ['name' => 'Pearl City', 'state_id' => 3935],
                ['name' => 'Ridott', 'state_id' => 3935],
                ['name' => 'Rock City', 'state_id' => 3935],
                ['name' => 'Winslow', 'state_id' => 3935],
                ['name' => 'Green Valley', 'state_id' => 3935],
                ['name' => 'Groveland', 'state_id' => 3935],
                ['name' => 'Morton', 'state_id' => 3935],
                ['name' => 'Pekin', 'state_id' => 3935],
                ['name' => 'South Pekin', 'state_id' => 3935],
                ['name' => 'Tremont', 'state_id' => 3935],
                ['name' => 'Washington', 'state_id' => 3935],
                ['name' => 'Creve Coeur', 'state_id' => 3935],
                ['name' => 'East Peoria', 'state_id' => 3935],
                ['name' => 'Armington', 'state_id' => 3935],
                ['name' => 'Deer Creek', 'state_id' => 3935],
                ['name' => 'Delavan', 'state_id' => 3935],
                ['name' => 'Hopedale', 'state_id' => 3935],
                ['name' => 'Mackinaw', 'state_id' => 3935],
                ['name' => 'Minier', 'state_id' => 3935],
                ['name' => 'Alto Pass', 'state_id' => 3935],
                ['name' => 'Anna', 'state_id' => 3935],
                ['name' => 'Cobden', 'state_id' => 3935],
                ['name' => 'Dongola', 'state_id' => 3935],
                ['name' => 'Jonesboro', 'state_id' => 3935],
                ['name' => 'Millcreek', 'state_id' => 3935],
                ['name' => 'Wolf Lake', 'state_id' => 3935],
                ['name' => 'East Lynn', 'state_id' => 3935],
                ['name' => 'Hoopeston', 'state_id' => 3935],
                ['name' => 'Rankin', 'state_id' => 3935],
                ['name' => 'Rossville', 'state_id' => 3935],
                ['name' => 'Allerton', 'state_id' => 3935],
                ['name' => 'Alvin', 'state_id' => 3935],
                ['name' => 'Armstrong', 'state_id' => 3935],
                ['name' => 'Bismarck', 'state_id' => 3935],
                ['name' => 'Catlin', 'state_id' => 3935],
                ['name' => 'Collison', 'state_id' => 3935],
                ['name' => 'Danville', 'state_id' => 3935],
                ['name' => 'Tilton', 'state_id' => 3935],
                ['name' => 'Fairmount', 'state_id' => 3935],
                ['name' => 'Fithian', 'state_id' => 3935],
                ['name' => 'Georgetown', 'state_id' => 3935],
                ['name' => 'Henning', 'state_id' => 3935],
                ['name' => 'Indianola', 'state_id' => 3935],
                ['name' => 'Muncie', 'state_id' => 3935],
                ['name' => 'Oakwood', 'state_id' => 3935],
                ['name' => 'Potomac', 'state_id' => 3935],
                ['name' => 'Ridge Farm', 'state_id' => 3935],
                ['name' => 'Sidell', 'state_id' => 3935],
                ['name' => 'Westville', 'state_id' => 3935],
                ['name' => 'Allendale', 'state_id' => 3935],
                ['name' => 'Bellmont', 'state_id' => 3935],
                ['name' => 'Keensburg', 'state_id' => 3935],
                ['name' => 'Lancaster', 'state_id' => 3935],
                ['name' => 'Mount Carmel', 'state_id' => 3935],
                ['name' => 'Berwick', 'state_id' => 3935],
                ['name' => 'Cameron', 'state_id' => 3935],
                ['name' => 'Gerlaw', 'state_id' => 3935],
                ['name' => 'Kirkwood', 'state_id' => 3935],
                ['name' => 'Little York', 'state_id' => 3935],
                ['name' => 'Monmouth', 'state_id' => 3935],
                ['name' => 'Roseville', 'state_id' => 3935],
                ['name' => 'Smithshire', 'state_id' => 3935],
                ['name' => 'Addieville', 'state_id' => 3935],
                ['name' => 'Nashville', 'state_id' => 3935],
                ['name' => 'Oakdale', 'state_id' => 3935],
                ['name' => 'Okawville', 'state_id' => 3935],
                ['name' => 'Hoyleton', 'state_id' => 3935],
                ['name' => 'Ashley', 'state_id' => 3935],
                ['name' => 'Du Bois', 'state_id' => 3935],
                ['name' => 'Irvington', 'state_id' => 3935],
                ['name' => 'Radom', 'state_id' => 3935],
                ['name' => 'Richview', 'state_id' => 3935],
                ['name' => 'Mount Erie', 'state_id' => 3935],
                ['name' => 'Barnhill', 'state_id' => 3935],
                ['name' => 'Cisne', 'state_id' => 3935],
                ['name' => 'Fairfield', 'state_id' => 3935],
                ['name' => 'Geff', 'state_id' => 3935],
                ['name' => 'Golden Gate', 'state_id' => 3935],
                ['name' => 'Johnsonville', 'state_id' => 3935],
                ['name' => 'Keenes', 'state_id' => 3935],
                ['name' => 'Rinard', 'state_id' => 3935],
                ['name' => 'Sims', 'state_id' => 3935],
                ['name' => 'Wayne City', 'state_id' => 3935],
                ['name' => 'Burnt Prairie', 'state_id' => 3935],
                ['name' => 'Carmi', 'state_id' => 3935],
                ['name' => 'Crossville', 'state_id' => 3935],
                ['name' => 'Emma', 'state_id' => 3935],
                ['name' => 'Enfield', 'state_id' => 3935],
                ['name' => 'Grayville', 'state_id' => 3935],
                ['name' => 'Maunie', 'state_id' => 3935],
                ['name' => 'Mill Shoals', 'state_id' => 3935],
                ['name' => 'Norris City', 'state_id' => 3935],
                ['name' => 'Springerton', 'state_id' => 3935],
                ['name' => 'Galt', 'state_id' => 3935],
                ['name' => 'Rock Falls', 'state_id' => 3935],
                ['name' => 'Sterling', 'state_id' => 3935],
                ['name' => 'Albany', 'state_id' => 3935],
                ['name' => 'Deer Grove', 'state_id' => 3935],
                ['name' => 'Erie', 'state_id' => 3935],
                ['name' => 'Fenton', 'state_id' => 3935],
                ['name' => 'Fulton', 'state_id' => 3935],
                ['name' => 'Lyndon', 'state_id' => 3935],
                ['name' => 'Morrison', 'state_id' => 3935],
                ['name' => 'Prophetstown', 'state_id' => 3935],
                ['name' => 'Tampico', 'state_id' => 3935],
                ['name' => 'Beecher', 'state_id' => 3935],
                ['name' => 'Crest Hill', 'state_id' => 3935],
                ['name' => 'Shorewood', 'state_id' => 3935],
                ['name' => 'Braidwood', 'state_id' => 3935],
                ['name' => 'Channahon', 'state_id' => 3935],
                ['name' => 'Crete', 'state_id' => 3935],
                ['name' => 'Elwood', 'state_id' => 3935],
                ['name' => 'Frankfort', 'state_id' => 3935],
                ['name' => 'Markham', 'state_id' => 3935],
                ['name' => 'Joliet', 'state_id' => 3935],
                ['name' => 'Bolingbrook', 'state_id' => 3935],
                ['name' => 'Lockport', 'state_id' => 3935],
                ['name' => 'Manhattan', 'state_id' => 3935],
                ['name' => 'Romeoville', 'state_id' => 3935],
                ['name' => 'Mokena', 'state_id' => 3935],
                ['name' => 'Monee', 'state_id' => 3935],
                ['name' => 'New Lenox', 'state_id' => 3935],
                ['name' => 'Peotone', 'state_id' => 3935],
                ['name' => 'Wilmington', 'state_id' => 3935],
                ['name' => 'University Park', 'state_id' => 3935],
                ['name' => 'Homer Glen', 'state_id' => 3935],
                ['name' => 'Plainfield', 'state_id' => 3935],
                ['name' => 'Freeman Spur', 'state_id' => 3935],
                ['name' => 'Cambria', 'state_id' => 3935],
                ['name' => 'Carterville', 'state_id' => 3935],
                ['name' => 'Colp', 'state_id' => 3935],
                ['name' => 'Creal Springs', 'state_id' => 3935],
                ['name' => 'Energy', 'state_id' => 3935],
                ['name' => 'Herrin', 'state_id' => 3935],
                ['name' => 'Hurst', 'state_id' => 3935],
                ['name' => 'Johnston City', 'state_id' => 3935],
                ['name' => 'Marion', 'state_id' => 3935],
                ['name' => 'Pittsburg', 'state_id' => 3935],
                ['name' => 'Cherry Valley', 'state_id' => 3935],
                ['name' => 'Durand', 'state_id' => 3935],
                ['name' => 'Pecatonica', 'state_id' => 3935],
                ['name' => 'Rockton', 'state_id' => 3935],
                ['name' => 'Roscoe', 'state_id' => 3935],
                ['name' => 'Seward', 'state_id' => 3935],
                ['name' => 'Shirland', 'state_id' => 3935],
                ['name' => 'South Beloit', 'state_id' => 3935],
                ['name' => 'Winnebago', 'state_id' => 3935],
                ['name' => 'Rockford', 'state_id' => 3935],
                ['name' => 'Loves Park', 'state_id' => 3935],
                ['name' => 'Machesney Park', 'state_id' => 3935],
                ['name' => 'Benson', 'state_id' => 3935],
                ['name' => 'Eureka', 'state_id' => 3935],
                ['name' => 'Lowpoint', 'state_id' => 3935],
                ['name' => 'Metamora', 'state_id' => 3935],
                ['name' => 'Roanoke', 'state_id' => 3935],
                ['name' => 'Congerville', 'state_id' => 3935],
                ['name' => 'El Paso', 'state_id' => 3935],
                ['name' => 'Goodfield', 'state_id' => 3935],
                ['name' => 'Minonk', 'state_id' => 3935],
                ['name' => 'Secor', 'state_id' => 3935]
            ]);
        }
    }
}
