<?php

use Illuminate\Database\Seeder;

class state46TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         //Create Cities for the state of VA - Virginia.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                [  'name' => 'Accomac', 'state_id' => 3975],
                [  'name' => 'Assawoman', 'state_id' => 3975],
                [  'name' => 'Atlantic', 'state_id' => 3975],
                [  'name' => 'Belle Haven', 'state_id' => 3975],
                [  'name' => 'Bloxom', 'state_id' => 3975],
                [  'name' => 'Chincoteague Island', 'state_id' => 3975],
                [  'name' => 'Wallops Island', 'state_id' => 3975],
                [  'name' => 'Craddockville', 'state_id' => 3975],
                [  'name' => 'Davis Wharf', 'state_id' => 3975],
                [  'name' => 'Greenbackville', 'state_id' => 3975],
                [  'name' => 'Greenbush', 'state_id' => 3975],
                [  'name' => 'Hacksneck', 'state_id' => 3975],
                [  'name' => 'Hallwood', 'state_id' => 3975],
                [  'name' => 'Harborton', 'state_id' => 3975],
                [  'name' => 'Horntown', 'state_id' => 3975],
                [  'name' => 'Oak Hall', 'state_id' => 3975],
                [  'name' => 'Jenkins Bridge', 'state_id' => 3975],
                [  'name' => 'Keller', 'state_id' => 3975],
                [  'name' => 'Locustville', 'state_id' => 3975],
                [  'name' => 'Mappsville', 'state_id' => 3975],
                [  'name' => 'Mears', 'state_id' => 3975],
                [  'name' => 'Melfa', 'state_id' => 3975],
                [  'name' => 'Modest Town', 'state_id' => 3975],
                [  'name' => 'Nelsonia', 'state_id' => 3975],
                [  'name' => 'New Church', 'state_id' => 3975],
                [  'name' => 'Onancock', 'state_id' => 3975],
                [  'name' => 'Onley', 'state_id' => 3975],
                [  'name' => 'Painter', 'state_id' => 3975],
                [  'name' => 'Parksley', 'state_id' => 3975],
                [  'name' => 'Pungoteague', 'state_id' => 3975],
                [  'name' => 'Quinby', 'state_id' => 3975],
                [  'name' => 'Sanford', 'state_id' => 3975],
                [  'name' => 'Saxis', 'state_id' => 3975],
                [  'name' => 'Tangier', 'state_id' => 3975],
                [  'name' => 'Tasley', 'state_id' => 3975],
                [  'name' => 'Temperanceville', 'state_id' => 3975],
                [  'name' => 'Wachapreague', 'state_id' => 3975],
                [  'name' => 'Wattsville', 'state_id' => 3975],
                [  'name' => 'Withams', 'state_id' => 3975],
                [  'name' => 'Charlottesville', 'state_id' => 3975],
                [  'name' => 'Batesville', 'state_id' => 3975],
                [  'name' => 'Covesville', 'state_id' => 3975],
                [  'name' => 'Crozet', 'state_id' => 3975],
                [  'name' => 'Earlysville', 'state_id' => 3975],
                [  'name' => 'Esmont', 'state_id' => 3975],
                [  'name' => 'Free Union', 'state_id' => 3975],
                [  'name' => 'Greenwood', 'state_id' => 3975],
                [  'name' => 'Ivy', 'state_id' => 3975],
                [  'name' => 'Keene', 'state_id' => 3975],
                [  'name' => 'Keswick', 'state_id' => 3975],
                [  'name' => 'North Garden', 'state_id' => 3975],
                [  'name' => 'White Hall', 'state_id' => 3975],
                [  'name' => 'Howardsville', 'state_id' => 3975],
                [  'name' => 'Scottsville', 'state_id' => 3975],
                [  'name' => 'Clifton Forge', 'state_id' => 3975],
                [  'name' => 'Iron Gate', 'state_id' => 3975],
                [  'name' => 'Low Moor', 'state_id' => 3975],
                [  'name' => 'Selma', 'state_id' => 3975],
                [  'name' => 'Amelia Court House', 'state_id' => 3975],
                [  'name' => 'Jetersville', 'state_id' => 3975],
                [  'name' => 'Mannboro', 'state_id' => 3975],
                [  'name' => 'Amherst', 'state_id' => 3975],
                [  'name' => 'Clifford', 'state_id' => 3975],
                [  'name' => 'Madison Heights', 'state_id' => 3975],
                [  'name' => 'Monroe', 'state_id' => 3975],
                [  'name' => 'Sweet Briar', 'state_id' => 3975],
                [  'name' => 'Evergreen', 'state_id' => 3975],
                [  'name' => 'Pamplin', 'state_id' => 3975],
                [  'name' => 'Appomattox', 'state_id' => 3975],
                [  'name' => 'Spout Spring', 'state_id' => 3975],
                [  'name' => 'Arlington', 'state_id' => 3975],
                [  'name' => 'Fort Myer', 'state_id' => 3975],
                [  'name' => 'Mount Solon', 'state_id' => 3975],
                [  'name' => 'Fishersville', 'state_id' => 3975],
                [  'name' => 'Lyndhurst', 'state_id' => 3975],
                [  'name' => 'Augusta Springs', 'state_id' => 3975],
                [  'name' => 'Churchville', 'state_id' => 3975],
                [  'name' => 'Craigsville', 'state_id' => 3975],
                [  'name' => 'Crimora', 'state_id' => 3975],
                [  'name' => 'Deerfield', 'state_id' => 3975],
                [  'name' => 'Fort Defiance', 'state_id' => 3975],
                [  'name' => 'Greenville', 'state_id' => 3975],
                [  'name' => 'Middlebrook', 'state_id' => 3975],
                [  'name' => 'Mint Spring', 'state_id' => 3975],
                [  'name' => 'Mount Sidney', 'state_id' => 3975],
                [  'name' => 'New Hope', 'state_id' => 3975],
                [  'name' => 'Steeles Tavern', 'state_id' => 3975],
                [  'name' => 'Stuarts Draft', 'state_id' => 3975],
                [  'name' => 'Swoope', 'state_id' => 3975],
                [  'name' => 'Verona', 'state_id' => 3975],
                [  'name' => 'West Augusta', 'state_id' => 3975],
                [  'name' => 'Weyers Cave', 'state_id' => 3975],
                [  'name' => 'Bacova', 'state_id' => 3975],
                [  'name' => 'Hot Springs', 'state_id' => 3975],
                [  'name' => 'Millboro', 'state_id' => 3975],
                [  'name' => 'Warm Springs', 'state_id' => 3975],
                [  'name' => 'Williamsville', 'state_id' => 3975],
                [  'name' => 'Goodview', 'state_id' => 3975],
                [  'name' => 'Hardy', 'state_id' => 3975],
                [  'name' => 'Huddleston', 'state_id' => 3975],
                [  'name' => 'Moneta', 'state_id' => 3975],
                [  'name' => 'Montvale', 'state_id' => 3975],
                [  'name' => 'Thaxton', 'state_id' => 3975],
                [  'name' => 'Villamont', 'state_id' => 3975],
                [  'name' => 'Big Island', 'state_id' => 3975],
                [  'name' => 'Coleman Falls', 'state_id' => 3975],
                [  'name' => 'Forest', 'state_id' => 3975],
                [  'name' => 'Goode', 'state_id' => 3975],
                [  'name' => 'Lowry', 'state_id' => 3975],
                [  'name' => 'Bastian', 'state_id' => 3975],
                [  'name' => 'Bland', 'state_id' => 3975],
                [  'name' => 'Ceres', 'state_id' => 3975],
                [  'name' => 'Rocky Gap', 'state_id' => 3975],
                [  'name' => 'Roanoke', 'state_id' => 3975],
                [  'name' => 'Blue Ridge', 'state_id' => 3975],
                [  'name' => 'Buchanan', 'state_id' => 3975],
                [  'name' => 'Cloverdale', 'state_id' => 3975],
                [  'name' => 'Daleville', 'state_id' => 3975],
                [  'name' => 'Eagle Rock', 'state_id' => 3975],
                [  'name' => 'Fincastle', 'state_id' => 3975],
                [  'name' => 'Oriskany', 'state_id' => 3975],
                [  'name' => 'Troutville', 'state_id' => 3975],
                [  'name' => 'Glen Wilton', 'state_id' => 3975],
                [  'name' => 'Alberta', 'state_id' => 3975],
                [  'name' => 'Dolphin', 'state_id' => 3975],
                [  'name' => 'Ebony', 'state_id' => 3975],
                [  'name' => 'Freeman', 'state_id' => 3975],
                [  'name' => 'Gasburg', 'state_id' => 3975],
                [  'name' => 'Lawrenceville', 'state_id' => 3975],
                [  'name' => 'Meredithville', 'state_id' => 3975],
                [  'name' => 'Rawlings', 'state_id' => 3975],
                [  'name' => 'Valentines', 'state_id' => 3975],
                [  'name' => 'Warfield', 'state_id' => 3975],
                [  'name' => 'White Plains', 'state_id' => 3975],
                [  'name' => 'Brodnax', 'state_id' => 3975],
                [  'name' => 'Davenport', 'state_id' => 3975],
                [  'name' => 'Big Rock', 'state_id' => 3975],
                [  'name' => 'Grundy', 'state_id' => 3975],
                [  'name' => 'Hurley', 'state_id' => 3975],
                [  'name' => 'Keen Mountain', 'state_id' => 3975],
                [  'name' => 'Mavisdale', 'state_id' => 3975],
                [  'name' => 'Maxie', 'state_id' => 3975],
                [  'name' => 'Oakwood', 'state_id' => 3975],
                [  'name' => 'Pilgrims Knob', 'state_id' => 3975],
                [  'name' => 'Raven', 'state_id' => 3975],
                [  'name' => 'Rowe', 'state_id' => 3975],
                [  'name' => 'Shortt Gap', 'state_id' => 3975],
                [  'name' => 'Vansant', 'state_id' => 3975],
                [  'name' => 'Whitewood', 'state_id' => 3975],
                [  'name' => 'Wolford', 'state_id' => 3975],
                [  'name' => 'Arvonia', 'state_id' => 3975],
                [  'name' => 'New Canton', 'state_id' => 3975],
                [  'name' => 'Buckingham', 'state_id' => 3975],
                [  'name' => 'Dillwyn', 'state_id' => 3975],
                [  'name' => 'Lynchburg', 'state_id' => 3975],
                [  'name' => 'Altavista', 'state_id' => 3975],
                [  'name' => 'Brookneal', 'state_id' => 3975],
                [  'name' => 'Concord', 'state_id' => 3975],
                [  'name' => 'Evington', 'state_id' => 3975],
                [  'name' => 'Gladys', 'state_id' => 3975],
                [  'name' => 'Long Island', 'state_id' => 3975],
                [  'name' => 'Lynch Station', 'state_id' => 3975],
                [  'name' => 'Naruna', 'state_id' => 3975],
                [  'name' => 'Rustburg', 'state_id' => 3975],
                [  'name' => 'Bowling Green', 'state_id' => 3975],
                [  'name' => 'Corbin', 'state_id' => 3975],
                [  'name' => 'Ladysmith', 'state_id' => 3975],
                [  'name' => 'Milford', 'state_id' => 3975],
                [  'name' => 'Port Royal', 'state_id' => 3975],
                [  'name' => 'Rappahannock Academy', 'state_id' => 3975],
                [  'name' => 'Ruther Glen', 'state_id' => 3975],
                [  'name' => 'Sparta', 'state_id' => 3975],
                [  'name' => 'Woodford', 'state_id' => 3975],
                [  'name' => 'Cana', 'state_id' => 3975],
                [  'name' => 'Dugspur', 'state_id' => 3975],
                [  'name' => 'Fancy Gap', 'state_id' => 3975],
                [  'name' => 'Hillsville', 'state_id' => 3975],
                [  'name' => 'Lambsburg', 'state_id' => 3975],
                [  'name' => 'Laurel Fork', 'state_id' => 3975],
                [  'name' => 'Woodlawn', 'state_id' => 3975],
                [  'name' => 'Charles City', 'state_id' => 3975],
                [  'name' => 'Ruthville', 'state_id' => 3975],
                [  'name' => 'Charlotte Court House', 'state_id' => 3975],
                [  'name' => 'Cullen', 'state_id' => 3975],
                [  'name' => 'Drakes Branch', 'state_id' => 3975],
                [  'name' => 'Keysville', 'state_id' => 3975],
                [  'name' => 'Phenix', 'state_id' => 3975],
                [  'name' => 'Randolph', 'state_id' => 3975],
                [  'name' => 'Red House', 'state_id' => 3975],
                [  'name' => 'Red Oak', 'state_id' => 3975],
                [  'name' => 'Saxe', 'state_id' => 3975],
                [  'name' => 'Wylliesburg', 'state_id' => 3975],
                [  'name' => 'Midlothian', 'state_id' => 3975],
                [  'name' => 'Moseley', 'state_id' => 3975],
                [  'name' => 'Richmond', 'state_id' => 3975],
                [  'name' => 'Chester', 'state_id' => 3975],
                [  'name' => 'Chesterfield', 'state_id' => 3975],
                [  'name' => 'Berryville', 'state_id' => 3975],
                [  'name' => 'Boyce', 'state_id' => 3975],
                [  'name' => 'Millwood', 'state_id' => 3975],
                [  'name' => 'White Post', 'state_id' => 3975],
                [  'name' => 'New Castle', 'state_id' => 3975],
                [  'name' => 'Paint Bank', 'state_id' => 3975],
                [  'name' => 'Culpeper', 'state_id' => 3975],
                [  'name' => 'Boston', 'state_id' => 3975],
                [  'name' => 'Brandy Station', 'state_id' => 3975],
                [  'name' => 'Elkwood', 'state_id' => 3975],
                [  'name' => 'Jeffersonton', 'state_id' => 3975],
                [  'name' => 'Lignum', 'state_id' => 3975],
                [  'name' => 'Mitchells', 'state_id' => 3975],
                [  'name' => 'Rapidan', 'state_id' => 3975],
                [  'name' => 'Reva', 'state_id' => 3975],
                [  'name' => 'Richardsville', 'state_id' => 3975],
                [  'name' => 'Rixeyville', 'state_id' => 3975],
                [  'name' => 'Stevensburg', 'state_id' => 3975],
                [  'name' => 'Cartersville', 'state_id' => 3975],
                [  'name' => 'Cumberland', 'state_id' => 3975],
                [  'name' => 'Bee', 'state_id' => 3975],
                [  'name' => 'Birchleaf', 'state_id' => 3975],
                [  'name' => 'Clinchco', 'state_id' => 3975],
                [  'name' => 'Clintwood', 'state_id' => 3975],
                [  'name' => 'Haysi', 'state_id' => 3975],
                [  'name' => 'Mc Clure', 'state_id' => 3975],
                [  'name' => 'Nora', 'state_id' => 3975],
                [  'name' => 'Breaks', 'state_id' => 3975],
                [  'name' => 'Ammon', 'state_id' => 3975],
                [  'name' => 'Carson', 'state_id' => 3975],
                [  'name' => 'Church Road', 'state_id' => 3975],
                [  'name' => 'Dewitt', 'state_id' => 3975],
                [  'name' => 'Dinwiddie', 'state_id' => 3975],
                [  'name' => 'Ford', 'state_id' => 3975],
                [  'name' => 'Mc Kenney', 'state_id' => 3975],
                [  'name' => 'Sutherland', 'state_id' => 3975],
                [  'name' => 'Wilsons', 'state_id' => 3975],
                [  'name' => 'Caret', 'state_id' => 3975],
                [  'name' => 'Center Cross', 'state_id' => 3975],
                [  'name' => 'Champlain', 'state_id' => 3975],
                [  'name' => 'Dunnsville', 'state_id' => 3975],
                [  'name' => 'Hustle', 'state_id' => 3975],
                [  'name' => 'Laneview', 'state_id' => 3975],
                [  'name' => 'Loretto', 'state_id' => 3975],
                [  'name' => 'Tappahannock', 'state_id' => 3975],
                [  'name' => 'Millers Tavern', 'state_id' => 3975],
                [  'name' => 'Centreville', 'state_id' => 3975],
                [  'name' => 'Clifton', 'state_id' => 3975],
                [  'name' => 'Chantilly', 'state_id' => 3975],
                [  'name' => 'Herndon', 'state_id' => 3975],
                [  'name' => 'Reston', 'state_id' => 3975],
                [  'name' => 'Annandale', 'state_id' => 3975],
                [  'name' => 'Burke', 'state_id' => 3975],
                [  'name' => 'Dunn Loring', 'state_id' => 3975],
                [  'name' => 'Fairfax', 'state_id' => 3975],
                [  'name' => 'Fairfax Station', 'state_id' => 3975],
                [  'name' => 'Falls Church', 'state_id' => 3975],
                [  'name' => 'Fort Belvoir', 'state_id' => 3975],
                [  'name' => 'Great Falls', 'state_id' => 3975],
                [  'name' => 'Greenway', 'state_id' => 3975],
                [  'name' => 'Lorton', 'state_id' => 3975],
                [  'name' => 'Merrifield', 'state_id' => 3975],
                [  'name' => 'Mc Lean', 'state_id' => 3975],
                [  'name' => 'West Mclean', 'state_id' => 3975],
                [  'name' => 'Mount Vernon', 'state_id' => 3975],
                [  'name' => 'Newington', 'state_id' => 3975],
                [  'name' => 'Oakton', 'state_id' => 3975],
                [  'name' => 'Springfield', 'state_id' => 3975],
                [  'name' => 'Vienna', 'state_id' => 3975],
                [  'name' => 'Alexandria', 'state_id' => 3975],
                [  'name' => 'Marshall', 'state_id' => 3975],
                [  'name' => 'Catlett', 'state_id' => 3975],
                [  'name' => 'Orlean', 'state_id' => 3975],
                [  'name' => 'Paris', 'state_id' => 3975],
                [  'name' => 'Broad Run', 'state_id' => 3975],
                [  'name' => 'Calverton', 'state_id' => 3975],
                [  'name' => 'Casanova', 'state_id' => 3975],
                [  'name' => 'Rectortown', 'state_id' => 3975],
                [  'name' => 'Delaplane', 'state_id' => 3975],
                [  'name' => 'Upperville', 'state_id' => 3975],
                [  'name' => 'Warrenton', 'state_id' => 3975],
                [  'name' => 'The Plains', 'state_id' => 3975],
                [  'name' => 'Hume', 'state_id' => 3975],
                [  'name' => 'Markham', 'state_id' => 3975],
                [  'name' => 'Bealeton', 'state_id' => 3975],
                [  'name' => 'Goldvein', 'state_id' => 3975],
                [  'name' => 'Midland', 'state_id' => 3975],
                [  'name' => 'Remington', 'state_id' => 3975],
                [  'name' => 'Somerville', 'state_id' => 3975],
                [  'name' => 'Sumerduck', 'state_id' => 3975],
                [  'name' => 'Check', 'state_id' => 3975],
                [  'name' => 'Copper Hill', 'state_id' => 3975],
                [  'name' => 'Floyd', 'state_id' => 3975],
                [  'name' => 'Indian Valley', 'state_id' => 3975],
                [  'name' => 'Willis', 'state_id' => 3975],
                [  'name' => 'Palmyra', 'state_id' => 3975],
                [  'name' => 'Troy', 'state_id' => 3975],
                [  'name' => 'Bremo Bluff', 'state_id' => 3975],
                [  'name' => 'Fork Union', 'state_id' => 3975],
                [  'name' => 'Kents Store', 'state_id' => 3975],
                [  'name' => 'Boones Mill', 'state_id' => 3975],
                [  'name' => 'Callaway', 'state_id' => 3975],
                [  'name' => 'Ferrum', 'state_id' => 3975],
                [  'name' => 'Glade Hill', 'state_id' => 3975],
                [  'name' => 'Henry', 'state_id' => 3975],
                [  'name' => 'Penhook', 'state_id' => 3975],
                [  'name' => 'Redwood', 'state_id' => 3975],
                [  'name' => 'Rocky Mount', 'state_id' => 3975],
                [  'name' => 'Union Hall', 'state_id' => 3975],
                [  'name' => 'Wirtz', 'state_id' => 3975],
                [  'name' => 'Winchester', 'state_id' => 3975],
                [  'name' => 'Brucetown', 'state_id' => 3975],
                [  'name' => 'Clear Brook', 'state_id' => 3975],
                [  'name' => 'Cross Junction', 'state_id' => 3975],
                [  'name' => 'Gore', 'state_id' => 3975],
                [  'name' => 'Middletown', 'state_id' => 3975],
                [  'name' => 'Star Tannery', 'state_id' => 3975],
                [  'name' => 'Stephens City', 'state_id' => 3975],
                [  'name' => 'Stephenson', 'state_id' => 3975],
                [  'name' => 'Eggleston', 'state_id' => 3975],
                [  'name' => 'Glen Lyn', 'state_id' => 3975],
                [  'name' => 'Narrows', 'state_id' => 3975],
                [  'name' => 'Newport', 'state_id' => 3975],
                [  'name' => 'Pearisburg', 'state_id' => 3975],
                [  'name' => 'Pembroke', 'state_id' => 3975],
                [  'name' => 'Rich Creek', 'state_id' => 3975],
                [  'name' => 'Ripplemead', 'state_id' => 3975],
                [  'name' => 'Staffordsville', 'state_id' => 3975],
                [  'name' => 'Achilles', 'state_id' => 3975],
                [  'name' => 'Ark', 'state_id' => 3975],
                [  'name' => 'Bena', 'state_id' => 3975],
                [  'name' => 'Dutton', 'state_id' => 3975],
                [  'name' => 'Gloucester', 'state_id' => 3975],
                [  'name' => 'Gloucester Point', 'state_id' => 3975],
                [  'name' => 'Hayes', 'state_id' => 3975],
                [  'name' => 'Maryus', 'state_id' => 3975],
                [  'name' => 'Ordinary', 'state_id' => 3975],
                [  'name' => 'Schley', 'state_id' => 3975],
                [  'name' => 'Severn', 'state_id' => 3975],
                [  'name' => 'Ware Neck', 'state_id' => 3975],
                [  'name' => 'White Marsh', 'state_id' => 3975],
                [  'name' => 'Wicomico', 'state_id' => 3975],
                [  'name' => 'Woods Cross Roads', 'state_id' => 3975],
                [  'name' => 'Beaumont', 'state_id' => 3975],
                [  'name' => 'Columbia', 'state_id' => 3975],
                [  'name' => 'Crozier', 'state_id' => 3975],
                [  'name' => 'Goochland', 'state_id' => 3975],
                [  'name' => 'Gum Spring', 'state_id' => 3975],
                [  'name' => 'Hadensville', 'state_id' => 3975],
                [  'name' => 'Maidens', 'state_id' => 3975],
                [  'name' => 'Manakin Sabot', 'state_id' => 3975],
                [  'name' => 'Oilville', 'state_id' => 3975],
                [  'name' => 'Sandy Hook', 'state_id' => 3975],
                [  'name' => 'State Farm', 'state_id' => 3975],
                [  'name' => 'Whitetop', 'state_id' => 3975],
                [  'name' => 'Elk Creek', 'state_id' => 3975],
                [  'name' => 'Fries', 'state_id' => 3975],
                [  'name' => 'Independence', 'state_id' => 3975],
                [  'name' => 'Mouth Of Wilson', 'state_id' => 3975],
                [  'name' => 'Troutdale', 'state_id' => 3975],
                [  'name' => 'Dyke', 'state_id' => 3975],
                [  'name' => 'Quinque', 'state_id' => 3975],
                [  'name' => 'Ruckersville', 'state_id' => 3975],
                [  'name' => 'Stanardsville', 'state_id' => 3975],
                [  'name' => 'Jarratt', 'state_id' => 3975],
                [  'name' => 'Skippers', 'state_id' => 3975],
                [  'name' => 'Alton', 'state_id' => 3975],
                [  'name' => 'Clover', 'state_id' => 3975],
                [  'name' => 'Cluster Springs', 'state_id' => 3975],
                [  'name' => 'Crystal Hill', 'state_id' => 3975],
                [  'name' => 'Halifax', 'state_id' => 3975],
                [  'name' => 'Nathalie', 'state_id' => 3975],
                [  'name' => 'Scottsburg', 'state_id' => 3975],
                [  'name' => 'South Boston', 'state_id' => 3975],
                [  'name' => 'Vernon Hill', 'state_id' => 3975],
                [  'name' => 'Virgilina', 'state_id' => 3975],
                [  'name' => 'Ashland', 'state_id' => 3975],
                [  'name' => 'Beaverdam', 'state_id' => 3975],
                [  'name' => 'Doswell', 'state_id' => 3975],
                [  'name' => 'Glen Allen', 'state_id' => 3975],
                [  'name' => 'Hanover', 'state_id' => 3975],
                [  'name' => 'Mechanicsville', 'state_id' => 3975],
                [  'name' => 'Rockville', 'state_id' => 3975],
                [  'name' => 'Studley', 'state_id' => 3975],
                [  'name' => 'Montpelier', 'state_id' => 3975],
                [  'name' => 'Henrico', 'state_id' => 3975],
                [  'name' => 'Sandston', 'state_id' => 3975],
                [  'name' => 'Axton', 'state_id' => 3975],
                [  'name' => 'Bassett', 'state_id' => 3975],
                [  'name' => 'Collinsville', 'state_id' => 3975],
                [  'name' => 'Fieldale', 'state_id' => 3975],
                [  'name' => 'Ridgeway', 'state_id' => 3975],
                [  'name' => 'Spencer', 'state_id' => 3975],
                [  'name' => 'Stanleytown', 'state_id' => 3975],
                [  'name' => 'Blue Grass', 'state_id' => 3975],
                [  'name' => 'Doe Hill', 'state_id' => 3975],
                [  'name' => 'Head Waters', 'state_id' => 3975],
                [  'name' => 'Mc Dowell', 'state_id' => 3975],
                [  'name' => 'Monterey', 'state_id' => 3975],
                [  'name' => 'Mustoe', 'state_id' => 3975],
                [  'name' => 'Battery Park', 'state_id' => 3975],
                [  'name' => 'Carrollton', 'state_id' => 3975],
                [  'name' => 'Carrsville', 'state_id' => 3975],
                [  'name' => 'Isle Of Wight', 'state_id' => 3975],
                [  'name' => 'Rescue', 'state_id' => 3975],
                [  'name' => 'Smithfield', 'state_id' => 3975],
                [  'name' => 'Windsor', 'state_id' => 3975],
                [  'name' => 'Zuni', 'state_id' => 3975],
                [  'name' => 'Jamestown', 'state_id' => 3975],
                [  'name' => 'Norge', 'state_id' => 3975],
                [  'name' => 'Toano', 'state_id' => 3975],
                [  'name' => 'Williamsburg', 'state_id' => 3975],
                [  'name' => 'Bruington', 'state_id' => 3975],
                [  'name' => 'King And Queen Court House', 'state_id' => 3975],
                [  'name' => 'Little Plymouth', 'state_id' => 3975],
                [  'name' => 'Mascot', 'state_id' => 3975],
                [  'name' => 'Mattaponi', 'state_id' => 3975],
                [  'name' => 'Newtown', 'state_id' => 3975],
                [  'name' => 'Saint Stephens Church', 'state_id' => 3975],
                [  'name' => 'Shacklefords', 'state_id' => 3975],
                [  'name' => 'Stevensville', 'state_id' => 3975],
                [  'name' => 'Walkerton', 'state_id' => 3975],
                [  'name' => 'Dahlgren', 'state_id' => 3975],
                [  'name' => 'Dogue', 'state_id' => 3975],
                [  'name' => 'Jersey', 'state_id' => 3975],
                [  'name' => 'King George', 'state_id' => 3975],
                [  'name' => 'Ninde', 'state_id' => 3975],
                [  'name' => 'Rollins Fork', 'state_id' => 3975],
                [  'name' => 'Sealston', 'state_id' => 3975],
                [  'name' => 'Aylett', 'state_id' => 3975],
                [  'name' => 'King William', 'state_id' => 3975],
                [  'name' => 'Manquin', 'state_id' => 3975],
                [  'name' => 'West Point', 'state_id' => 3975],
                [  'name' => 'Irvington', 'state_id' => 3975],
                [  'name' => 'Kilmarnock', 'state_id' => 3975],
                [  'name' => 'Lancaster', 'state_id' => 3975],
                [  'name' => 'Lively', 'state_id' => 3975],
                [  'name' => 'Merry Point', 'state_id' => 3975],
                [  'name' => 'Mollusk', 'state_id' => 3975],
                [  'name' => 'Morattico', 'state_id' => 3975],
                [  'name' => 'Nuttsville', 'state_id' => 3975],
                [  'name' => 'Weems', 'state_id' => 3975],
                [  'name' => 'White Stone', 'state_id' => 3975],
                [  'name' => 'Ben Hur', 'state_id' => 3975],
                [  'name' => 'Blackwater', 'state_id' => 3975],
                [  'name' => 'Dryden', 'state_id' => 3975],
                [  'name' => 'Ewing', 'state_id' => 3975],
                [  'name' => 'Jonesville', 'state_id' => 3975],
                [  'name' => 'Keokee', 'state_id' => 3975],
                [  'name' => 'Pennington Gap', 'state_id' => 3975],
                [  'name' => 'Rose Hill', 'state_id' => 3975],
                [  'name' => 'Saint Charles', 'state_id' => 3975],
                [  'name' => 'Dulles', 'state_id' => 3975],
                [  'name' => 'Aldie', 'state_id' => 3975],
                [  'name' => 'Middleburg', 'state_id' => 3975],
                [  'name' => 'Paeonian Springs', 'state_id' => 3975],
                [  'name' => 'Philomont', 'state_id' => 3975],
                [  'name' => 'Purcellville', 'state_id' => 3975],
                [  'name' => 'Bluemont', 'state_id' => 3975],
                [  'name' => 'Round Hill', 'state_id' => 3975],
                [  'name' => 'Ashburn', 'state_id' => 3975],
                [  'name' => 'Hamilton', 'state_id' => 3975],
                [  'name' => 'Lincoln', 'state_id' => 3975],
                [  'name' => 'Sterling', 'state_id' => 3975],
                [  'name' => 'Leesburg', 'state_id' => 3975],
                [  'name' => 'Lovettsville', 'state_id' => 3975],
                [  'name' => 'Waterford', 'state_id' => 3975],
                [  'name' => 'Dhs', 'state_id' => 3975],
                [  'name' => 'Bumpass', 'state_id' => 3975],
                [  'name' => 'Louisa', 'state_id' => 3975],
                [  'name' => 'Mineral', 'state_id' => 3975],
                [  'name' => 'Trevilians', 'state_id' => 3975],
                [  'name' => 'Dundas', 'state_id' => 3975],
                [  'name' => 'Fort Mitchell', 'state_id' => 3975],
                [  'name' => 'Kenbridge', 'state_id' => 3975],
                [  'name' => 'Lunenburg', 'state_id' => 3975],
                [  'name' => 'Victoria', 'state_id' => 3975],
                [  'name' => 'Aroda', 'state_id' => 3975],
                [  'name' => 'Banco', 'state_id' => 3975],
                [  'name' => 'Brightwood', 'state_id' => 3975],
                [  'name' => 'Etlan', 'state_id' => 3975],
                [  'name' => 'Haywood', 'state_id' => 3975],
                [  'name' => 'Hood', 'state_id' => 3975],
                [  'name' => 'Leon', 'state_id' => 3975],
                [  'name' => 'Madison', 'state_id' => 3975],
                [  'name' => 'Oakpark', 'state_id' => 3975],
                [  'name' => 'Pratts', 'state_id' => 3975],
                [  'name' => 'Radiant', 'state_id' => 3975],
                [  'name' => 'Rochelle', 'state_id' => 3975],
                [  'name' => 'Syria', 'state_id' => 3975],
                [  'name' => 'Wolftown', 'state_id' => 3975],
                [  'name' => 'Locust Dale', 'state_id' => 3975],
                [  'name' => 'Woodberry Forest', 'state_id' => 3975],
                [  'name' => 'Bohannon', 'state_id' => 3975],
                [  'name' => 'Cardinal', 'state_id' => 3975],
                [  'name' => 'Cobbs Creek', 'state_id' => 3975],
                [  'name' => 'Diggs', 'state_id' => 3975],
                [  'name' => 'Foster', 'state_id' => 3975],
                [  'name' => 'Grimstead', 'state_id' => 3975],
                [  'name' => 'Gwynn', 'state_id' => 3975],
                [  'name' => 'Hallieford', 'state_id' => 3975],
                [  'name' => 'Hudgins', 'state_id' => 3975],
                [  'name' => 'Mathews', 'state_id' => 3975],
                [  'name' => 'Moon', 'state_id' => 3975],
                [  'name' => 'New Point', 'state_id' => 3975],
                [  'name' => 'North', 'state_id' => 3975],
                [  'name' => 'Onemo', 'state_id' => 3975],
                [  'name' => 'Port Haywood', 'state_id' => 3975],
                [  'name' => 'Susan', 'state_id' => 3975],
                [  'name' => 'Baskerville', 'state_id' => 3975],
                [  'name' => 'Boydton', 'state_id' => 3975],
                [  'name' => 'Bracey', 'state_id' => 3975],
                [  'name' => 'Chase City', 'state_id' => 3975],
                [  'name' => 'Clarksville', 'state_id' => 3975],
                [  'name' => 'La Crosse', 'state_id' => 3975],
                [  'name' => 'Skipwith', 'state_id' => 3975],
                [  'name' => 'South Hill', 'state_id' => 3975],
                [  'name' => 'Buffalo Junction', 'state_id' => 3975],
                [  'name' => 'Nelson', 'state_id' => 3975],
                [  'name' => 'Christchurch', 'state_id' => 3975],
                [  'name' => 'Church View', 'state_id' => 3975],
                [  'name' => 'Deltaville', 'state_id' => 3975],
                [  'name' => 'Hardyville', 'state_id' => 3975],
                [  'name' => 'Hartfield', 'state_id' => 3975],
                [  'name' => 'Jamaica', 'state_id' => 3975],
                [  'name' => 'Locust Hill', 'state_id' => 3975],
                [  'name' => 'Saluda', 'state_id' => 3975],
                [  'name' => 'Topping', 'state_id' => 3975],
                [  'name' => 'Urbanna', 'state_id' => 3975],
                [  'name' => 'Wake', 'state_id' => 3975],
                [  'name' => 'Water View', 'state_id' => 3975],
                [  'name' => 'Blacksburg', 'state_id' => 3975],
                [  'name' => 'Christiansburg', 'state_id' => 3975],
                [  'name' => 'Mc Coy', 'state_id' => 3975],
                [  'name' => 'Pilot', 'state_id' => 3975],
                [  'name' => 'Riner', 'state_id' => 3975],
                [  'name' => 'Shawsville', 'state_id' => 3975],
                [  'name' => 'Afton', 'state_id' => 3975],
                [  'name' => 'Arrington', 'state_id' => 3975],
                [  'name' => 'Faber', 'state_id' => 3975],
                [  'name' => 'Lovingston', 'state_id' => 3975],
                [  'name' => 'Nellysford', 'state_id' => 3975],
                [  'name' => 'Piney River', 'state_id' => 3975],
                [  'name' => 'Roseland', 'state_id' => 3975],
                [  'name' => 'Schuyler', 'state_id' => 3975],
                [  'name' => 'Shipman', 'state_id' => 3975],
                [  'name' => 'Tyro', 'state_id' => 3975],
                [  'name' => 'Montebello', 'state_id' => 3975],
                [  'name' => 'Gladstone', 'state_id' => 3975],
                [  'name' => 'Norwood', 'state_id' => 3975],
                [  'name' => 'Wingina', 'state_id' => 3975],
                [  'name' => 'Barhamsville', 'state_id' => 3975],
                [  'name' => 'Lanexa', 'state_id' => 3975],
                [  'name' => 'New Kent', 'state_id' => 3975],
                [  'name' => 'Providence Forge', 'state_id' => 3975],
                [  'name' => 'Quinton', 'state_id' => 3975],
                [  'name' => 'Birdsnest', 'state_id' => 3975],
                [  'name' => 'Cape Charles', 'state_id' => 3975],
                [  'name' => 'Capeville', 'state_id' => 3975],
                [  'name' => 'Cheriton', 'state_id' => 3975],
                [  'name' => 'Eastville', 'state_id' => 3975],
                [  'name' => 'Exmore', 'state_id' => 3975],
                [  'name' => 'Franktown', 'state_id' => 3975],
                [  'name' => 'Jamesville', 'state_id' => 3975],
                [  'name' => 'Machipongo', 'state_id' => 3975],
                [  'name' => 'Marionville', 'state_id' => 3975],
                [  'name' => 'Nassawadox', 'state_id' => 3975],
                [  'name' => 'Oyster', 'state_id' => 3975],
                [  'name' => 'Seaview', 'state_id' => 3975],
                [  'name' => 'Townsend', 'state_id' => 3975],
                [  'name' => 'Wardtown', 'state_id' => 3975],
                [  'name' => 'Willis Wharf', 'state_id' => 3975],
                [  'name' => 'Burgess', 'state_id' => 3975],
                [  'name' => 'Callao', 'state_id' => 3975],
                [  'name' => 'Edwardsville', 'state_id' => 3975],
                [  'name' => 'Heathsville', 'state_id' => 3975],
                [  'name' => 'Lottsburg', 'state_id' => 3975],
                [  'name' => 'Ophelia', 'state_id' => 3975],
                [  'name' => 'Reedville', 'state_id' => 3975],
                [  'name' => 'Wicomico Church', 'state_id' => 3975],
                [  'name' => 'Blackstone', 'state_id' => 3975],
                [  'name' => 'Burkeville', 'state_id' => 3975],
                [  'name' => 'Crewe', 'state_id' => 3975],
                [  'name' => 'Nottoway', 'state_id' => 3975],
                [  'name' => 'Burr Hill', 'state_id' => 3975],
                [  'name' => 'Locust Grove', 'state_id' => 3975],
                [  'name' => 'Rhoadesville', 'state_id' => 3975],
                [  'name' => 'Unionville', 'state_id' => 3975],
                [  'name' => 'Barboursville', 'state_id' => 3975],
                [  'name' => 'Gordonsville', 'state_id' => 3975],
                [  'name' => 'Montpelier Station', 'state_id' => 3975],
                [  'name' => 'Orange', 'state_id' => 3975],
                [  'name' => 'Somerset', 'state_id' => 3975],
                [  'name' => 'Rileyville', 'state_id' => 3975],
                [  'name' => 'Luray', 'state_id' => 3975],
                [  'name' => 'Shenandoah', 'state_id' => 3975],
                [  'name' => 'Stanley', 'state_id' => 3975],
                [  'name' => 'Ararat', 'state_id' => 3975],
                [  'name' => 'Claudville', 'state_id' => 3975],
                [  'name' => 'Critz', 'state_id' => 3975],
                [  'name' => 'Meadows Of Dan', 'state_id' => 3975],
                [  'name' => 'Patrick Springs', 'state_id' => 3975],
                [  'name' => 'Stuart', 'state_id' => 3975],
                [  'name' => 'Vesta', 'state_id' => 3975],
                [  'name' => 'Woolwine', 'state_id' => 3975],
                [  'name' => 'Cascade', 'state_id' => 3975],
                [  'name' => 'Pittsville', 'state_id' => 3975],
                [  'name' => 'Sandy Level', 'state_id' => 3975],
                [  'name' => 'Blairs', 'state_id' => 3975],
                [  'name' => 'Callands', 'state_id' => 3975],
                [  'name' => 'Chatham', 'state_id' => 3975],
                [  'name' => 'Dry Fork', 'state_id' => 3975],
                [  'name' => 'Gretna', 'state_id' => 3975],
                [  'name' => 'Hurt', 'state_id' => 3975],
                [  'name' => 'Java', 'state_id' => 3975],
                [  'name' => 'Keeling', 'state_id' => 3975],
                [  'name' => 'Ringgold', 'state_id' => 3975],
                [  'name' => 'Sutherlin', 'state_id' => 3975],
                [  'name' => 'Powhatan', 'state_id' => 3975],
                [  'name' => 'Farmville', 'state_id' => 3975],
                [  'name' => 'Green Bay', 'state_id' => 3975],
                [  'name' => 'Hampden Sydney', 'state_id' => 3975],
                [  'name' => 'Meherrin', 'state_id' => 3975],
                [  'name' => 'Prospect', 'state_id' => 3975],
                [  'name' => 'Rice', 'state_id' => 3975],
                [  'name' => 'Fort Lee', 'state_id' => 3975],
                [  'name' => 'Disputanta', 'state_id' => 3975],
                [  'name' => 'Prince George', 'state_id' => 3975],
                [  'name' => 'Bristow', 'state_id' => 3975],
                [  'name' => 'Catharpin', 'state_id' => 3975],
                [  'name' => 'Gainesville', 'state_id' => 3975],
                [  'name' => 'Haymarket', 'state_id' => 3975],
                [  'name' => 'Nokesville', 'state_id' => 3975],
                [  'name' => 'Dumfries', 'state_id' => 3975],
                [  'name' => 'Occoquan', 'state_id' => 3975],
                [  'name' => 'Quantico', 'state_id' => 3975],
                [  'name' => 'Triangle', 'state_id' => 3975],
                [  'name' => 'Woodbridge', 'state_id' => 3975],
                [  'name' => 'Belspring', 'state_id' => 3975],
                [  'name' => 'Dublin', 'state_id' => 3975],
                [  'name' => 'Newbern', 'state_id' => 3975],
                [  'name' => 'New River', 'state_id' => 3975],
                [  'name' => 'Parrott', 'state_id' => 3975],
                [  'name' => 'Pulaski', 'state_id' => 3975],
                [  'name' => 'Draper', 'state_id' => 3975],
                [  'name' => 'Hiwassee', 'state_id' => 3975],
                [  'name' => 'Amissville', 'state_id' => 3975],
                [  'name' => 'Chester Gap', 'state_id' => 3975],
                [  'name' => 'Flint Hill', 'state_id' => 3975],
                [  'name' => 'Huntly', 'state_id' => 3975],
                [  'name' => 'Castleton', 'state_id' => 3975],
                [  'name' => 'Sperryville', 'state_id' => 3975],
                [  'name' => 'Viewtown', 'state_id' => 3975],
                [  'name' => 'Washington', 'state_id' => 3975],
                [  'name' => 'Woodville', 'state_id' => 3975],
                [  'name' => 'Farnham', 'state_id' => 3975],
                [  'name' => 'Haynesville', 'state_id' => 3975],
                [  'name' => 'Sharps', 'state_id' => 3975],
                [  'name' => 'Village', 'state_id' => 3975],
                [  'name' => 'Warsaw', 'state_id' => 3975],
                [  'name' => 'Bent Mountain', 'state_id' => 3975],
                [  'name' => 'Catawba', 'state_id' => 3975],
                [  'name' => 'Elliston', 'state_id' => 3975],
                [  'name' => 'Vinton', 'state_id' => 3975],
                [  'name' => 'Brownsburg', 'state_id' => 3975],
                [  'name' => 'Fairfield', 'state_id' => 3975],
                [  'name' => 'Goshen', 'state_id' => 3975],
                [  'name' => 'Raphine', 'state_id' => 3975],
                [  'name' => 'Rockbridge Baths', 'state_id' => 3975],
                [  'name' => 'Vesuvius', 'state_id' => 3975],
                [  'name' => 'Glasgow', 'state_id' => 3975],
                [  'name' => 'Natural Bridge', 'state_id' => 3975],
                [  'name' => 'Natural Bridge Station', 'state_id' => 3975],
                [  'name' => 'Harrisonburg', 'state_id' => 3975],
                [  'name' => 'Bergton', 'state_id' => 3975],
                [  'name' => 'Bridgewater', 'state_id' => 3975],
                [  'name' => 'Broadway', 'state_id' => 3975],
                [  'name' => 'Criders', 'state_id' => 3975],
                [  'name' => 'Dayton', 'state_id' => 3975],
                [  'name' => 'Elkton', 'state_id' => 3975],
                [  'name' => 'Fulks Run', 'state_id' => 3975],
                [  'name' => 'Hinton', 'state_id' => 3975],
                [  'name' => 'Keezletown', 'state_id' => 3975],
                [  'name' => 'Lacey Spring', 'state_id' => 3975],
                [  'name' => 'Linville', 'state_id' => 3975],
                [  'name' => 'Mc Gaheysville', 'state_id' => 3975],
                [  'name' => 'Mount Crawford', 'state_id' => 3975],
                [  'name' => 'Penn Laird', 'state_id' => 3975],
                [  'name' => 'Pleasant Valley', 'state_id' => 3975],
                [  'name' => 'Singers Glen', 'state_id' => 3975],
                [  'name' => 'Timberville', 'state_id' => 3975],
                [  'name' => 'Grottoes', 'state_id' => 3975],
                [  'name' => 'Port Republic', 'state_id' => 3975],
                [  'name' => 'Castlewood', 'state_id' => 3975],
                [  'name' => 'Cleveland', 'state_id' => 3975],
                [  'name' => 'Dante', 'state_id' => 3975],
                [  'name' => 'Honaker', 'state_id' => 3975],
                [  'name' => 'Lebanon', 'state_id' => 3975],
                [  'name' => 'Rosedale', 'state_id' => 3975],
                [  'name' => 'Swords Creek', 'state_id' => 3975],
                [  'name' => 'Duffield', 'state_id' => 3975],
                [  'name' => 'Dungannon', 'state_id' => 3975],
                [  'name' => 'Fort Blackmore', 'state_id' => 3975],
                [  'name' => 'Gate City', 'state_id' => 3975],
                [  'name' => 'Hiltons', 'state_id' => 3975],
                [  'name' => 'Nickelsville', 'state_id' => 3975],
                [  'name' => 'Weber City', 'state_id' => 3975],
                [  'name' => 'Fishers Hill', 'state_id' => 3975],
                [  'name' => 'Strasburg', 'state_id' => 3975],
                [  'name' => 'Maurertown', 'state_id' => 3975],
                [  'name' => 'Fort Valley', 'state_id' => 3975],
                [  'name' => 'Toms Brook', 'state_id' => 3975],
                [  'name' => 'Woodstock', 'state_id' => 3975],
                [  'name' => 'Basye', 'state_id' => 3975],
                [  'name' => 'Edinburg', 'state_id' => 3975],
                [  'name' => 'Mount Jackson', 'state_id' => 3975],
                [  'name' => 'New Market', 'state_id' => 3975],
                [  'name' => 'Orkney Springs', 'state_id' => 3975],
                [  'name' => 'Quicksburg', 'state_id' => 3975],
                [  'name' => 'Atkins', 'state_id' => 3975],
                [  'name' => 'Broadford', 'state_id' => 3975],
                [  'name' => 'Chilhowie', 'state_id' => 3975],
                [  'name' => 'Marion', 'state_id' => 3975],
                [  'name' => 'Saltville', 'state_id' => 3975],
                [  'name' => 'Sugar Grove', 'state_id' => 3975],
                [  'name' => 'Boykins', 'state_id' => 3975],
                [  'name' => 'Branchville', 'state_id' => 3975],
                [  'name' => 'Capron', 'state_id' => 3975],
                [  'name' => 'Courtland', 'state_id' => 3975],
                [  'name' => 'Drewryville', 'state_id' => 3975],
                [  'name' => 'Ivor', 'state_id' => 3975],
                [  'name' => 'Newsoms', 'state_id' => 3975],
                [  'name' => 'Sedley', 'state_id' => 3975],
                [  'name' => 'Fredericksburg', 'state_id' => 3975],
                [  'name' => 'Partlow', 'state_id' => 3975],
                [  'name' => 'Spotsylvania', 'state_id' => 3975],
                [  'name' => 'Thornburg', 'state_id' => 3975],
                [  'name' => 'Brooke', 'state_id' => 3975],
                [  'name' => 'Garrisonville', 'state_id' => 3975],
                [  'name' => 'Hartwood', 'state_id' => 3975],
                [  'name' => 'Ruby', 'state_id' => 3975],
                [  'name' => 'Stafford', 'state_id' => 3975],
                [  'name' => 'Dendron', 'state_id' => 3975],
                [  'name' => 'Elberon', 'state_id' => 3975],
                [  'name' => 'Spring Grove', 'state_id' => 3975],
                [  'name' => 'Surry', 'state_id' => 3975],
                [  'name' => 'Claremont', 'state_id' => 3975],
                [  'name' => 'Stony Creek', 'state_id' => 3975],
                [  'name' => 'Sussex', 'state_id' => 3975],
                [  'name' => 'Wakefield', 'state_id' => 3975],
                [  'name' => 'Waverly', 'state_id' => 3975],
                [  'name' => 'Yale', 'state_id' => 3975],
                [  'name' => 'Tannersville', 'state_id' => 3975],
                [  'name' => 'Amonate', 'state_id' => 3975],
                [  'name' => 'Bandy', 'state_id' => 3975],
                [  'name' => 'Bishop', 'state_id' => 3975],
                [  'name' => 'Bluefield', 'state_id' => 3975],
                [  'name' => 'Boissevain', 'state_id' => 3975],
                [  'name' => 'Burkes Garden', 'state_id' => 3975],
                [  'name' => 'Cedar Bluff', 'state_id' => 3975],
                [  'name' => 'Doran', 'state_id' => 3975],
                [  'name' => 'Falls Mills', 'state_id' => 3975],
                [  'name' => 'Horsepen', 'state_id' => 3975],
                [  'name' => 'Jewell Ridge', 'state_id' => 3975],
                [  'name' => 'North Tazewell', 'state_id' => 3975],
                [  'name' => 'Pocahontas', 'state_id' => 3975],
                [  'name' => 'Pounding Mill', 'state_id' => 3975],
                [  'name' => 'Red Ash', 'state_id' => 3975],
                [  'name' => 'Richlands', 'state_id' => 3975],
                [  'name' => 'Tazewell', 'state_id' => 3975],
                [  'name' => 'Bentonville', 'state_id' => 3975],
                [  'name' => 'Front Royal', 'state_id' => 3975],
                [  'name' => 'Linden', 'state_id' => 3975],
                [  'name' => 'Abingdon', 'state_id' => 3975],
                [  'name' => 'Damascus', 'state_id' => 3975],
                [  'name' => 'Mendota', 'state_id' => 3975],
                [  'name' => 'Emory', 'state_id' => 3975],
                [  'name' => 'Glade Spring', 'state_id' => 3975],
                [  'name' => 'Meadowview', 'state_id' => 3975],
                [  'name' => 'Coles Point', 'state_id' => 3975],
                [  'name' => 'Colonial Beach', 'state_id' => 3975],
                [  'name' => 'Hague', 'state_id' => 3975],
                [  'name' => 'Kinsale', 'state_id' => 3975],
                [  'name' => 'Montross', 'state_id' => 3975],
                [  'name' => 'Mount Holly', 'state_id' => 3975],
                [  'name' => 'Oldhams', 'state_id' => 3975],
                [  'name' => 'Stratford', 'state_id' => 3975],
                [  'name' => 'Sandy Point', 'state_id' => 3975],
                [  'name' => 'Zacata', 'state_id' => 3975],
                [  'name' => 'Andover', 'state_id' => 3975],
                [  'name' => 'Appalachia', 'state_id' => 3975],
                [  'name' => 'Big Stone Gap', 'state_id' => 3975],
                [  'name' => 'Coeburn', 'state_id' => 3975],
                [  'name' => 'East Stone Gap', 'state_id' => 3975],
                [  'name' => 'Pound', 'state_id' => 3975],
                [  'name' => 'Saint Paul', 'state_id' => 3975],
                [  'name' => 'Wise', 'state_id' => 3975],
                [  'name' => 'Austinville', 'state_id' => 3975],
                [  'name' => 'Barren Springs', 'state_id' => 3975],
                [  'name' => 'Cripple Creek', 'state_id' => 3975],
                [  'name' => 'Crockett', 'state_id' => 3975],
                [  'name' => 'Ivanhoe', 'state_id' => 3975],
                [  'name' => 'Max Meadows', 'state_id' => 3975],
                [  'name' => 'Rural Retreat', 'state_id' => 3975],
                [  'name' => 'Speedwell', 'state_id' => 3975],
                [  'name' => 'Wytheville', 'state_id' => 3975],
                [  'name' => 'Lightfoot', 'state_id' => 3975],
                [  'name' => 'Yorktown', 'state_id' => 3975],
                [  'name' => 'Lackey', 'state_id' => 3975],
                [  'name' => 'Seaford', 'state_id' => 3975],
                [  'name' => 'Bedford', 'state_id' => 3975],
                [  'name' => 'Bristol', 'state_id' => 3975],
                [  'name' => 'Buena Vista', 'state_id' => 3975],
                [  'name' => 'Chesapeake', 'state_id' => 3975],
                [  'name' => 'Colonial Heights', 'state_id' => 3975],
                [  'name' => 'Covington', 'state_id' => 3975],
                [  'name' => 'Danville', 'state_id' => 3975],
                [  'name' => 'Emporia', 'state_id' => 3975],
                [  'name' => 'Franklin', 'state_id' => 3975],
                [  'name' => 'Galax', 'state_id' => 3975],
                [  'name' => 'Hampton', 'state_id' => 3975],
                [  'name' => 'Fort Monroe', 'state_id' => 3975],
                [  'name' => 'Hopewell', 'state_id' => 3975],
                [  'name' => 'Lexington', 'state_id' => 3975],
                [  'name' => 'Manassas', 'state_id' => 3975],
                [  'name' => 'Martinsville', 'state_id' => 3975],
                [  'name' => 'Newport News', 'state_id' => 3975],
                [  'name' => 'Fort Eustis', 'state_id' => 3975],
                [  'name' => 'Norfolk', 'state_id' => 3975],
                [  'name' => 'Norton', 'state_id' => 3975],
                [  'name' => 'Petersburg', 'state_id' => 3975],
                [  'name' => 'Virginia State University', 'state_id' => 3975],
                [  'name' => 'Poquoson', 'state_id' => 3975],
                [  'name' => 'Portsmouth', 'state_id' => 3975],
                [  'name' => 'Radford', 'state_id' => 3975],
                [  'name' => 'Salem', 'state_id' => 3975],
                [  'name' => 'Staunton', 'state_id' => 3975],
                [  'name' => 'Suffolk', 'state_id' => 3975],
                [  'name' => 'Virginia Beach', 'state_id' => 3975],
                [  'name' => 'Waynesboro', 'state_id' => 3975]
            ]);
       }
    }
}
