<?php

use Illuminate\Database\Seeder;

class state37TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of OK - Oklahoma.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Proctor', 'state_id' => 3961],
                ['name' => 'Bunch', 'state_id' => 3961],
                ['name' => 'Stilwell', 'state_id' => 3961],
                ['name' => 'Watts', 'state_id' => 3961],
                ['name' => 'Westville', 'state_id' => 3961],
                ['name' => 'Aline', 'state_id' => 3961],
                ['name' => 'Amorita', 'state_id' => 3961],
                ['name' => 'Burlington', 'state_id' => 3961],
                ['name' => 'Carmen', 'state_id' => 3961],
                ['name' => 'Cherokee', 'state_id' => 3961],
                ['name' => 'Goltry', 'state_id' => 3961],
                ['name' => 'Helena', 'state_id' => 3961],
                ['name' => 'Jet', 'state_id' => 3961],
                ['name' => 'Atoka', 'state_id' => 3961],
                ['name' => 'Caney', 'state_id' => 3961],
                ['name' => 'Daisy', 'state_id' => 3961],
                ['name' => 'Lane', 'state_id' => 3961],
                ['name' => 'Stringtown', 'state_id' => 3961],
                ['name' => 'Gate', 'state_id' => 3961],
                ['name' => 'Balko', 'state_id' => 3961],
                ['name' => 'Beaver', 'state_id' => 3961],
                ['name' => 'Forgan', 'state_id' => 3961],
                ['name' => 'Turpin', 'state_id' => 3961],
                ['name' => 'Carter', 'state_id' => 3961],
                ['name' => 'Elk City', 'state_id' => 3961],
                ['name' => 'Erick', 'state_id' => 3961],
                ['name' => 'Sayre', 'state_id' => 3961],
                ['name' => 'Texola', 'state_id' => 3961],
                ['name' => 'Geary', 'state_id' => 3961],
                ['name' => 'Greenfield', 'state_id' => 3961],
                ['name' => 'Canton', 'state_id' => 3961],
                ['name' => 'Hitchcock', 'state_id' => 3961],
                ['name' => 'Longdale', 'state_id' => 3961],
                ['name' => 'Okeene', 'state_id' => 3961],
                ['name' => 'Southard', 'state_id' => 3961],
                ['name' => 'Watonga', 'state_id' => 3961],
                ['name' => 'Mead', 'state_id' => 3961],
                ['name' => 'Durant', 'state_id' => 3961],
                ['name' => 'Achille', 'state_id' => 3961],
                ['name' => 'Albany', 'state_id' => 3961],
                ['name' => 'Bennington', 'state_id' => 3961],
                ['name' => 'Bokchito', 'state_id' => 3961],
                ['name' => 'Caddo', 'state_id' => 3961],
                ['name' => 'Calera', 'state_id' => 3961],
                ['name' => 'Cartwright', 'state_id' => 3961],
                ['name' => 'Colbert', 'state_id' => 3961],
                ['name' => 'Hendrix', 'state_id' => 3961],
                ['name' => 'Kemp', 'state_id' => 3961],
                ['name' => 'Kenefic', 'state_id' => 3961],
                ['name' => 'Platter', 'state_id' => 3961],
                ['name' => 'Albert', 'state_id' => 3961],
                ['name' => 'Anadarko', 'state_id' => 3961],
                ['name' => 'Apache', 'state_id' => 3961],
                ['name' => 'Binger', 'state_id' => 3961],
                ['name' => 'Carnegie', 'state_id' => 3961],
                ['name' => 'Cement', 'state_id' => 3961],
                ['name' => 'Cyril', 'state_id' => 3961],
                ['name' => 'Eakly', 'state_id' => 3961],
                ['name' => 'Fort Cobb', 'state_id' => 3961],
                ['name' => 'Gracemont', 'state_id' => 3961],
                ['name' => 'Hinton', 'state_id' => 3961],
                ['name' => 'Hydro', 'state_id' => 3961],
                ['name' => 'Lookeba', 'state_id' => 3961],
                ['name' => 'Calumet', 'state_id' => 3961],
                ['name' => 'Concho', 'state_id' => 3961],
                ['name' => 'El Reno', 'state_id' => 3961],
                ['name' => 'Mustang', 'state_id' => 3961],
                ['name' => 'Piedmont', 'state_id' => 3961],
                ['name' => 'Yukon', 'state_id' => 3961],
                ['name' => 'Union City', 'state_id' => 3961],
                ['name' => 'Ardmore', 'state_id' => 3961],
                ['name' => 'Fox', 'state_id' => 3961],
                ['name' => 'Gene Autry', 'state_id' => 3961],
                ['name' => 'Graham', 'state_id' => 3961],
                ['name' => 'Healdton', 'state_id' => 3961],
                ['name' => 'Lone Grove', 'state_id' => 3961],
                ['name' => 'Springer', 'state_id' => 3961],
                ['name' => 'Wilson', 'state_id' => 3961],
                ['name' => 'Ratliff City', 'state_id' => 3961],
                ['name' => 'Tatums', 'state_id' => 3961],
                ['name' => 'Tussy', 'state_id' => 3961],
                ['name' => 'Cookson', 'state_id' => 3961],
                ['name' => 'Hulbert', 'state_id' => 3961],
                ['name' => 'Moodys', 'state_id' => 3961],
                ['name' => 'Park Hill', 'state_id' => 3961],
                ['name' => 'Peggs', 'state_id' => 3961],
                ['name' => 'Tahlequah', 'state_id' => 3961],
                ['name' => 'Welling', 'state_id' => 3961],
                ['name' => 'Boswell', 'state_id' => 3961],
                ['name' => 'Fort Towson', 'state_id' => 3961],
                ['name' => 'Grant', 'state_id' => 3961],
                ['name' => 'Hugo', 'state_id' => 3961],
                ['name' => 'Sawyer', 'state_id' => 3961],
                ['name' => 'Soper', 'state_id' => 3961],
                ['name' => 'Spencerville', 'state_id' => 3961],
                ['name' => 'Swink', 'state_id' => 3961],
                ['name' => 'Boise City', 'state_id' => 3961],
                ['name' => 'Felt', 'state_id' => 3961],
                ['name' => 'Kenton', 'state_id' => 3961],
                ['name' => 'Keyes', 'state_id' => 3961],
                ['name' => 'Norman', 'state_id' => 3961],
                ['name' => 'Lexington', 'state_id' => 3961],
                ['name' => 'Noble', 'state_id' => 3961],
                ['name' => 'Oklahoma City', 'state_id' => 3961],
                ['name' => 'Centrahoma', 'state_id' => 3961],
                ['name' => 'Clarita', 'state_id' => 3961],
                ['name' => 'Coalgate', 'state_id' => 3961],
                ['name' => 'Lehigh', 'state_id' => 3961],
                ['name' => 'Tupelo', 'state_id' => 3961],
                ['name' => 'Lawton', 'state_id' => 3961],
                ['name' => 'Fort Sill', 'state_id' => 3961],
                ['name' => 'Cache', 'state_id' => 3961],
                ['name' => 'Chattanooga', 'state_id' => 3961],
                ['name' => 'Elgin', 'state_id' => 3961],
                ['name' => 'Faxon', 'state_id' => 3961],
                ['name' => 'Fletcher', 'state_id' => 3961],
                ['name' => 'Geronimo', 'state_id' => 3961],
                ['name' => 'Indiahoma', 'state_id' => 3961],
                ['name' => 'Medicine Park', 'state_id' => 3961],
                ['name' => 'Meers', 'state_id' => 3961],
                ['name' => 'Sterling', 'state_id' => 3961],
                ['name' => 'Devol', 'state_id' => 3961],
                ['name' => 'Randlett', 'state_id' => 3961],
                ['name' => 'Temple', 'state_id' => 3961],
                ['name' => 'Walters', 'state_id' => 3961],
                ['name' => 'Vinita', 'state_id' => 3961],
                ['name' => 'Big Cabin', 'state_id' => 3961],
                ['name' => 'Bluejacket', 'state_id' => 3961],
                ['name' => 'Welch', 'state_id' => 3961],
                ['name' => 'Bristow', 'state_id' => 3961],
                ['name' => 'Depew', 'state_id' => 3961],
                ['name' => 'Drumright', 'state_id' => 3961],
                ['name' => 'Kellyville', 'state_id' => 3961],
                ['name' => 'Kiefer', 'state_id' => 3961],
                ['name' => 'Mannford', 'state_id' => 3961],
                ['name' => 'Milfay', 'state_id' => 3961],
                ['name' => 'Mounds', 'state_id' => 3961],
                ['name' => 'Oilton', 'state_id' => 3961],
                ['name' => 'Sapulpa', 'state_id' => 3961],
                ['name' => 'Shamrock', 'state_id' => 3961],
                ['name' => 'Slick', 'state_id' => 3961],
                ['name' => 'Tulsa', 'state_id' => 3961],
                ['name' => 'Weatherford', 'state_id' => 3961],
                ['name' => 'Clinton', 'state_id' => 3961],
                ['name' => 'Arapaho', 'state_id' => 3961],
                ['name' => 'Butler', 'state_id' => 3961],
                ['name' => 'Custer City', 'state_id' => 3961],
                ['name' => 'Thomas', 'state_id' => 3961],
                ['name' => 'Colcord', 'state_id' => 3961],
                ['name' => 'Eucha', 'state_id' => 3961],
                ['name' => 'Grove', 'state_id' => 3961],
                ['name' => 'Jay', 'state_id' => 3961],
                ['name' => 'Kansas', 'state_id' => 3961],
                ['name' => 'Oaks', 'state_id' => 3961],
                ['name' => 'Twin Oaks', 'state_id' => 3961],
                ['name' => 'Fay', 'state_id' => 3961],
                ['name' => 'Leedey', 'state_id' => 3961],
                ['name' => 'Oakwood', 'state_id' => 3961],
                ['name' => 'Putnam', 'state_id' => 3961],
                ['name' => 'Seiling', 'state_id' => 3961],
                ['name' => 'Taloga', 'state_id' => 3961],
                ['name' => 'Camargo', 'state_id' => 3961],
                ['name' => 'Vici', 'state_id' => 3961],
                ['name' => 'Arnett', 'state_id' => 3961],
                ['name' => 'Fargo', 'state_id' => 3961],
                ['name' => 'Gage', 'state_id' => 3961],
                ['name' => 'Shattuck', 'state_id' => 3961],
                ['name' => 'Enid', 'state_id' => 3961],
                ['name' => 'Bison', 'state_id' => 3961],
                ['name' => 'Carrier', 'state_id' => 3961],
                ['name' => 'Covington', 'state_id' => 3961],
                ['name' => 'Douglas', 'state_id' => 3961],
                ['name' => 'Drummond', 'state_id' => 3961],
                ['name' => 'Fairmont', 'state_id' => 3961],
                ['name' => 'Garber', 'state_id' => 3961],
                ['name' => 'Hillsdale', 'state_id' => 3961],
                ['name' => 'Kremlin', 'state_id' => 3961],
                ['name' => 'Lahoma', 'state_id' => 3961],
                ['name' => 'Waukomis', 'state_id' => 3961],
                ['name' => 'Hunter', 'state_id' => 3961],
                ['name' => 'Lindsay', 'state_id' => 3961],
                ['name' => 'Maysville', 'state_id' => 3961],
                ['name' => 'Paoli', 'state_id' => 3961],
                ['name' => 'Pauls Valley', 'state_id' => 3961],
                ['name' => 'Wynnewood', 'state_id' => 3961],
                ['name' => 'Elmore City', 'state_id' => 3961],
                ['name' => 'Hennepin', 'state_id' => 3961],
                ['name' => 'Stratford', 'state_id' => 3961],
                ['name' => 'Alex', 'state_id' => 3961],
                ['name' => 'Amber', 'state_id' => 3961],
                ['name' => 'Bradley', 'state_id' => 3961],
                ['name' => 'Chickasha', 'state_id' => 3961],
                ['name' => 'Minco', 'state_id' => 3961],
                ['name' => 'Ninnekah', 'state_id' => 3961],
                ['name' => 'Pocasset', 'state_id' => 3961],
                ['name' => 'Rush Springs', 'state_id' => 3961],
                ['name' => 'Tuttle', 'state_id' => 3961],
                ['name' => 'Verden', 'state_id' => 3961],
                ['name' => 'Manchester', 'state_id' => 3961],
                ['name' => 'Medford', 'state_id' => 3961],
                ['name' => 'Nash', 'state_id' => 3961],
                ['name' => 'Pond Creek', 'state_id' => 3961],
                ['name' => 'Wakita', 'state_id' => 3961],
                ['name' => 'Deer Creek', 'state_id' => 3961],
                ['name' => 'Lamont', 'state_id' => 3961],
                ['name' => 'Granite', 'state_id' => 3961],
                ['name' => 'Mangum', 'state_id' => 3961],
                ['name' => 'Willow', 'state_id' => 3961],
                ['name' => 'Gould', 'state_id' => 3961],
                ['name' => 'Hollis', 'state_id' => 3961],
                ['name' => 'Vinson', 'state_id' => 3961],
                ['name' => 'Buffalo', 'state_id' => 3961],
                ['name' => 'Laverne', 'state_id' => 3961],
                ['name' => 'May', 'state_id' => 3961],
                ['name' => 'Rosston', 'state_id' => 3961],
                ['name' => 'Hoyt', 'state_id' => 3961],
                ['name' => 'Stigler', 'state_id' => 3961],
                ['name' => 'Whitefield', 'state_id' => 3961],
                ['name' => 'Kinta', 'state_id' => 3961],
                ['name' => 'Keota', 'state_id' => 3961],
                ['name' => 'Lequire', 'state_id' => 3961],
                ['name' => 'Mccurtain', 'state_id' => 3961],
                ['name' => 'Calvin', 'state_id' => 3961],
                ['name' => 'Stuart', 'state_id' => 3961],
                ['name' => 'Atwood', 'state_id' => 3961],
                ['name' => 'Dustin', 'state_id' => 3961],
                ['name' => 'Holdenville', 'state_id' => 3961],
                ['name' => 'Lamar', 'state_id' => 3961],
                ['name' => 'Wetumka', 'state_id' => 3961],
                ['name' => 'Altus', 'state_id' => 3961],
                ['name' => 'Altus Afb', 'state_id' => 3961],
                ['name' => 'Blair', 'state_id' => 3961],
                ['name' => 'Duke', 'state_id' => 3961],
                ['name' => 'Eldorado', 'state_id' => 3961],
                ['name' => 'Elmer', 'state_id' => 3961],
                ['name' => 'Headrick', 'state_id' => 3961],
                ['name' => 'Martha', 'state_id' => 3961],
                ['name' => 'Olustee', 'state_id' => 3961],
                ['name' => 'Ringling', 'state_id' => 3961],
                ['name' => 'Addington', 'state_id' => 3961],
                ['name' => 'Hastings', 'state_id' => 3961],
                ['name' => 'Oscar', 'state_id' => 3961],
                ['name' => 'Ryan', 'state_id' => 3961],
                ['name' => 'Terral', 'state_id' => 3961],
                ['name' => 'Waurika', 'state_id' => 3961],
                ['name' => 'Coleman', 'state_id' => 3961],
                ['name' => 'Mannsville', 'state_id' => 3961],
                ['name' => 'Milburn', 'state_id' => 3961],
                ['name' => 'Ravia', 'state_id' => 3961],
                ['name' => 'Tishomingo', 'state_id' => 3961],
                ['name' => 'Wapanucka', 'state_id' => 3961],
                ['name' => 'Bromide', 'state_id' => 3961],
                ['name' => 'Connerville', 'state_id' => 3961],
                ['name' => 'Mill Creek', 'state_id' => 3961],
                ['name' => 'Ponca City', 'state_id' => 3961],
                ['name' => 'Blackwell', 'state_id' => 3961],
                ['name' => 'Braman', 'state_id' => 3961],
                ['name' => 'Kaw City', 'state_id' => 3961],
                ['name' => 'Nardin', 'state_id' => 3961],
                ['name' => 'Newkirk', 'state_id' => 3961],
                ['name' => 'Tonkawa', 'state_id' => 3961],
                ['name' => 'Cashion', 'state_id' => 3961],
                ['name' => 'Dover', 'state_id' => 3961],
                ['name' => 'Hennessey', 'state_id' => 3961],
                ['name' => 'Kingfisher', 'state_id' => 3961],
                ['name' => 'Loyal', 'state_id' => 3961],
                ['name' => 'Okarche', 'state_id' => 3961],
                ['name' => 'Omega', 'state_id' => 3961],
                ['name' => 'Gotebo', 'state_id' => 3961],
                ['name' => 'Mountain View', 'state_id' => 3961],
                ['name' => 'Mountain Park', 'state_id' => 3961],
                ['name' => 'Roosevelt', 'state_id' => 3961],
                ['name' => 'Snyder', 'state_id' => 3961],
                ['name' => 'Hobart', 'state_id' => 3961],
                ['name' => 'Lone Wolf', 'state_id' => 3961],
                ['name' => 'Gowen', 'state_id' => 3961],
                ['name' => 'Panola', 'state_id' => 3961],
                ['name' => 'Red Oak', 'state_id' => 3961],
                ['name' => 'Wilburton', 'state_id' => 3961],
                ['name' => 'Honobia', 'state_id' => 3961],
                ['name' => 'Talihina', 'state_id' => 3961],
                ['name' => 'Whitesboro', 'state_id' => 3961],
                ['name' => 'Arkoma', 'state_id' => 3961],
                ['name' => 'Pocola', 'state_id' => 3961],
                ['name' => 'Bokoshe', 'state_id' => 3961],
                ['name' => 'Cameron', 'state_id' => 3961],
                ['name' => 'Fanshawe', 'state_id' => 3961],
                ['name' => 'Heavener', 'state_id' => 3961],
                ['name' => 'Hodgen', 'state_id' => 3961],
                ['name' => 'Howe', 'state_id' => 3961],
                ['name' => 'Leflore', 'state_id' => 3961],
                ['name' => 'Monroe', 'state_id' => 3961],
                ['name' => 'Muse', 'state_id' => 3961],
                ['name' => 'Panama', 'state_id' => 3961],
                ['name' => 'Poteau', 'state_id' => 3961],
                ['name' => 'Shady Point', 'state_id' => 3961],
                ['name' => 'Spiro', 'state_id' => 3961],
                ['name' => 'Wister', 'state_id' => 3961],
                ['name' => 'Davenport', 'state_id' => 3961],
                ['name' => 'Stroud', 'state_id' => 3961],
                ['name' => 'Agra', 'state_id' => 3961],
                ['name' => 'Carney', 'state_id' => 3961],
                ['name' => 'Chandler', 'state_id' => 3961],
                ['name' => 'Meeker', 'state_id' => 3961],
                ['name' => 'Prague', 'state_id' => 3961],
                ['name' => 'Sparks', 'state_id' => 3961],
                ['name' => 'Tryon', 'state_id' => 3961],
                ['name' => 'Wellston', 'state_id' => 3961],
                ['name' => 'Coyle', 'state_id' => 3961],
                ['name' => 'Crescent', 'state_id' => 3961],
                ['name' => 'Guthrie', 'state_id' => 3961],
                ['name' => 'Langston', 'state_id' => 3961],
                ['name' => 'Marshall', 'state_id' => 3961],
                ['name' => 'Meridian', 'state_id' => 3961],
                ['name' => 'Mulhall', 'state_id' => 3961],
                ['name' => 'Orlando', 'state_id' => 3961],
                ['name' => 'Burneyville', 'state_id' => 3961],
                ['name' => 'Leon', 'state_id' => 3961],
                ['name' => 'Marietta', 'state_id' => 3961],
                ['name' => 'Overbrook', 'state_id' => 3961],
                ['name' => 'Thackerville', 'state_id' => 3961],
                ['name' => 'Blanchard', 'state_id' => 3961],
                ['name' => 'Dibble', 'state_id' => 3961],
                ['name' => 'Newcastle', 'state_id' => 3961],
                ['name' => 'Purcell', 'state_id' => 3961],
                ['name' => 'Washington', 'state_id' => 3961],
                ['name' => 'Wayne', 'state_id' => 3961],
                ['name' => 'Byars', 'state_id' => 3961],
                ['name' => 'Battiest', 'state_id' => 3961],
                ['name' => 'Bethel', 'state_id' => 3961],
                ['name' => 'Broken Bow', 'state_id' => 3961],
                ['name' => 'Eagletown', 'state_id' => 3961],
                ['name' => 'Garvin', 'state_id' => 3961],
                ['name' => 'Golden', 'state_id' => 3961],
                ['name' => 'Haworth', 'state_id' => 3961],
                ['name' => 'Idabel', 'state_id' => 3961],
                ['name' => 'Millerton', 'state_id' => 3961],
                ['name' => 'Pickens', 'state_id' => 3961],
                ['name' => 'Ringold', 'state_id' => 3961],
                ['name' => 'Rufe', 'state_id' => 3961],
                ['name' => 'Valliant', 'state_id' => 3961],
                ['name' => 'Wright City', 'state_id' => 3961],
                ['name' => 'Smithville', 'state_id' => 3961],
                ['name' => 'Watson', 'state_id' => 3961],
                ['name' => 'Checotah', 'state_id' => 3961],
                ['name' => 'Eufaula', 'state_id' => 3961],
                ['name' => 'Hitchita', 'state_id' => 3961],
                ['name' => 'Rentiesville', 'state_id' => 3961],
                ['name' => 'Stidham', 'state_id' => 3961],
                ['name' => 'Hanna', 'state_id' => 3961],
                ['name' => 'Ames', 'state_id' => 3961],
                ['name' => 'Cleo Springs', 'state_id' => 3961],
                ['name' => 'Fairview', 'state_id' => 3961],
                ['name' => 'Isabella', 'state_id' => 3961],
                ['name' => 'Meno', 'state_id' => 3961],
                ['name' => 'Ringwood', 'state_id' => 3961],
                ['name' => 'Chester', 'state_id' => 3961],
                ['name' => 'Kingston', 'state_id' => 3961],
                ['name' => 'Lebanon', 'state_id' => 3961],
                ['name' => 'Madill', 'state_id' => 3961],
                ['name' => 'Adair', 'state_id' => 3961],
                ['name' => 'Chouteau', 'state_id' => 3961],
                ['name' => 'Disney', 'state_id' => 3961],
                ['name' => 'Ketchum', 'state_id' => 3961],
                ['name' => 'Langley', 'state_id' => 3961],
                ['name' => 'Locust Grove', 'state_id' => 3961],
                ['name' => 'Pryor', 'state_id' => 3961],
                ['name' => 'Rose', 'state_id' => 3961],
                ['name' => 'Salina', 'state_id' => 3961],
                ['name' => 'Spavinaw', 'state_id' => 3961],
                ['name' => 'Strang', 'state_id' => 3961],
                ['name' => 'Davis', 'state_id' => 3961],
                ['name' => 'Dougherty', 'state_id' => 3961],
                ['name' => 'Sulphur', 'state_id' => 3961],
                ['name' => 'Muskogee', 'state_id' => 3961],
                ['name' => 'Boynton', 'state_id' => 3961],
                ['name' => 'Braggs', 'state_id' => 3961],
                ['name' => 'Council Hill', 'state_id' => 3961],
                ['name' => 'Fort Gibson', 'state_id' => 3961],
                ['name' => 'Haskell', 'state_id' => 3961],
                ['name' => 'Oktaha', 'state_id' => 3961],
                ['name' => 'Porum', 'state_id' => 3961],
                ['name' => 'Taft', 'state_id' => 3961],
                ['name' => 'Wainwright', 'state_id' => 3961],
                ['name' => 'Warner', 'state_id' => 3961],
                ['name' => 'Webbers Falls', 'state_id' => 3961],
                ['name' => 'Morrison', 'state_id' => 3961],
                ['name' => 'Perry', 'state_id' => 3961],
                ['name' => 'Lucien', 'state_id' => 3961],
                ['name' => 'Billings', 'state_id' => 3961],
                ['name' => 'Marland', 'state_id' => 3961],
                ['name' => 'Red Rock', 'state_id' => 3961],
                ['name' => 'Delaware', 'state_id' => 3961],
                ['name' => 'Lenapah', 'state_id' => 3961],
                ['name' => 'Nowata', 'state_id' => 3961],
                ['name' => 'S Coffeyville', 'state_id' => 3961],
                ['name' => 'Wann', 'state_id' => 3961],
                ['name' => 'Boley', 'state_id' => 3961],
                ['name' => 'Castle', 'state_id' => 3961],
                ['name' => 'Okemah', 'state_id' => 3961],
                ['name' => 'Paden', 'state_id' => 3961],
                ['name' => 'Weleetka', 'state_id' => 3961],
                ['name' => 'Edmond', 'state_id' => 3961],
                ['name' => 'Arcadia', 'state_id' => 3961],
                ['name' => 'Bethany', 'state_id' => 3961],
                ['name' => 'Choctaw', 'state_id' => 3961],
                ['name' => 'Harrah', 'state_id' => 3961],
                ['name' => 'Jones', 'state_id' => 3961],
                ['name' => 'Luther', 'state_id' => 3961],
                ['name' => 'Nicoma Park', 'state_id' => 3961],
                ['name' => 'Spencer', 'state_id' => 3961],
                ['name' => 'Wheatland', 'state_id' => 3961],
                ['name' => 'Newalla', 'state_id' => 3961],
                ['name' => 'Beggs', 'state_id' => 3961],
                ['name' => 'Dewar', 'state_id' => 3961],
                ['name' => 'Henryetta', 'state_id' => 3961],
                ['name' => 'Morris', 'state_id' => 3961],
                ['name' => 'Okmulgee', 'state_id' => 3961],
                ['name' => 'Preston', 'state_id' => 3961],
                ['name' => 'Schulter', 'state_id' => 3961],
                ['name' => 'Avant', 'state_id' => 3961],
                ['name' => 'Barnsdall', 'state_id' => 3961],
                ['name' => 'Hominy', 'state_id' => 3961],
                ['name' => 'Osage', 'state_id' => 3961],
                ['name' => 'Pawhuska', 'state_id' => 3961],
                ['name' => 'Prue', 'state_id' => 3961],
                ['name' => 'Skiatook', 'state_id' => 3961],
                ['name' => 'Wynona', 'state_id' => 3961],
                ['name' => 'Burbank', 'state_id' => 3961],
                ['name' => 'Fairfax', 'state_id' => 3961],
                ['name' => 'Shidler', 'state_id' => 3961],
                ['name' => 'Afton', 'state_id' => 3961],
                ['name' => 'Cardin', 'state_id' => 3961],
                ['name' => 'Commerce', 'state_id' => 3961],
                ['name' => 'Fairland', 'state_id' => 3961],
                ['name' => 'Miami', 'state_id' => 3961],
                ['name' => 'North Miami', 'state_id' => 3961],
                ['name' => 'Picher', 'state_id' => 3961],
                ['name' => 'Quapaw', 'state_id' => 3961],
                ['name' => 'Wyandotte', 'state_id' => 3961],
                ['name' => 'Cleveland', 'state_id' => 3961],
                ['name' => 'Hallett', 'state_id' => 3961],
                ['name' => 'Jennings', 'state_id' => 3961],
                ['name' => 'Maramec', 'state_id' => 3961],
                ['name' => 'Pawnee', 'state_id' => 3961],
                ['name' => 'Terlton', 'state_id' => 3961],
                ['name' => 'Ralston', 'state_id' => 3961],
                ['name' => 'Cushing', 'state_id' => 3961],
                ['name' => 'Glencoe', 'state_id' => 3961],
                ['name' => 'Perkins', 'state_id' => 3961],
                ['name' => 'Ripley', 'state_id' => 3961],
                ['name' => 'Stillwater', 'state_id' => 3961],
                ['name' => 'Yale', 'state_id' => 3961],
                ['name' => 'Canadian', 'state_id' => 3961],
                ['name' => 'Crowder', 'state_id' => 3961],
                ['name' => 'Indianola', 'state_id' => 3961],
                ['name' => 'Mcalester', 'state_id' => 3961],
                ['name' => 'Alderson', 'state_id' => 3961],
                ['name' => 'Blanco', 'state_id' => 3961],
                ['name' => 'Blocker', 'state_id' => 3961],
                ['name' => 'Haileyville', 'state_id' => 3961],
                ['name' => 'Hartshorne', 'state_id' => 3961],
                ['name' => 'Kiowa', 'state_id' => 3961],
                ['name' => 'Krebs', 'state_id' => 3961],
                ['name' => 'Pittsburg', 'state_id' => 3961],
                ['name' => 'Quinton', 'state_id' => 3961],
                ['name' => 'Savanna', 'state_id' => 3961],
                ['name' => 'Wardville', 'state_id' => 3961],
                ['name' => 'Ada', 'state_id' => 3961],
                ['name' => 'Allen', 'state_id' => 3961],
                ['name' => 'Fittstown', 'state_id' => 3961],
                ['name' => 'Fitzhugh', 'state_id' => 3961],
                ['name' => 'Francis', 'state_id' => 3961],
                ['name' => 'Roff', 'state_id' => 3961],
                ['name' => 'Stonewall', 'state_id' => 3961],
                ['name' => 'Shawnee', 'state_id' => 3961],
                ['name' => 'Asher', 'state_id' => 3961],
                ['name' => 'Earlsboro', 'state_id' => 3961],
                ['name' => 'Mcloud', 'state_id' => 3961],
                ['name' => 'Macomb', 'state_id' => 3961],
                ['name' => 'Maud', 'state_id' => 3961],
                ['name' => 'Saint Louis', 'state_id' => 3961],
                ['name' => 'Tecumseh', 'state_id' => 3961],
                ['name' => 'Wanette', 'state_id' => 3961],
                ['name' => 'Albion', 'state_id' => 3961],
                ['name' => 'Antlers', 'state_id' => 3961],
                ['name' => 'Clayton', 'state_id' => 3961],
                ['name' => 'Finley', 'state_id' => 3961],
                ['name' => 'Moyers', 'state_id' => 3961],
                ['name' => 'Nashoba', 'state_id' => 3961],
                ['name' => 'Rattan', 'state_id' => 3961],
                ['name' => 'Snow', 'state_id' => 3961],
                ['name' => 'Tuskahoma', 'state_id' => 3961],
                ['name' => 'Cheyenne', 'state_id' => 3961],
                ['name' => 'Crawford', 'state_id' => 3961],
                ['name' => 'Durham', 'state_id' => 3961],
                ['name' => 'Hammon', 'state_id' => 3961],
                ['name' => 'Reydon', 'state_id' => 3961],
                ['name' => 'Sweetwater', 'state_id' => 3961],
                ['name' => 'Catoosa', 'state_id' => 3961],
                ['name' => 'Chelsea', 'state_id' => 3961],
                ['name' => 'Claremore', 'state_id' => 3961],
                ['name' => 'Foyil', 'state_id' => 3961],
                ['name' => 'Inola', 'state_id' => 3961],
                ['name' => 'Oologah', 'state_id' => 3961],
                ['name' => 'Talala', 'state_id' => 3961],
                ['name' => 'Seminole', 'state_id' => 3961],
                ['name' => 'Bowlegs', 'state_id' => 3961],
                ['name' => 'Cromwell', 'state_id' => 3961],
                ['name' => 'Konawa', 'state_id' => 3961],
                ['name' => 'Sasakwa', 'state_id' => 3961],
                ['name' => 'Wewoka', 'state_id' => 3961],
                ['name' => 'Gore', 'state_id' => 3961],
                ['name' => 'Gans', 'state_id' => 3961],
                ['name' => 'Marble City', 'state_id' => 3961],
                ['name' => 'Moffett', 'state_id' => 3961],
                ['name' => 'Muldrow', 'state_id' => 3961],
                ['name' => 'Roland', 'state_id' => 3961],
                ['name' => 'Sallisaw', 'state_id' => 3961],
                ['name' => 'Vian', 'state_id' => 3961],
                ['name' => 'Marlow', 'state_id' => 3961],
                ['name' => 'Countyline', 'state_id' => 3961],
                ['name' => 'Foster', 'state_id' => 3961],
                ['name' => 'Loco', 'state_id' => 3961],
                ['name' => 'Velma', 'state_id' => 3961],
                ['name' => 'Comanche', 'state_id' => 3961],
                ['name' => 'Duncan', 'state_id' => 3961],
                ['name' => 'Adams', 'state_id' => 3961],
                ['name' => 'Goodwell', 'state_id' => 3961],
                ['name' => 'Guymon', 'state_id' => 3961],
                ['name' => 'Hardesty', 'state_id' => 3961],
                ['name' => 'Hooker', 'state_id' => 3961],
                ['name' => 'Texhoma', 'state_id' => 3961],
                ['name' => 'Tyrone', 'state_id' => 3961],
                ['name' => 'Davidson', 'state_id' => 3961],
                ['name' => 'Frederick', 'state_id' => 3961],
                ['name' => 'Grandfield', 'state_id' => 3961],
                ['name' => 'Hollister', 'state_id' => 3961],
                ['name' => 'Loveland', 'state_id' => 3961],
                ['name' => 'Manitou', 'state_id' => 3961],
                ['name' => 'Tipton', 'state_id' => 3961],
                ['name' => 'Bixby', 'state_id' => 3961],
                ['name' => 'Broken Arrow', 'state_id' => 3961],
                ['name' => 'Collinsville', 'state_id' => 3961],
                ['name' => 'Glenpool', 'state_id' => 3961],
                ['name' => 'Jenks', 'state_id' => 3961],
                ['name' => 'Leonard', 'state_id' => 3961],
                ['name' => 'Oakhurst', 'state_id' => 3961],
                ['name' => 'Owasso', 'state_id' => 3961],
                ['name' => 'Sand Springs', 'state_id' => 3961],
                ['name' => 'Sperry', 'state_id' => 3961],
                ['name' => 'Coweta', 'state_id' => 3961],
                ['name' => 'Okay', 'state_id' => 3961],
                ['name' => 'Porter', 'state_id' => 3961],
                ['name' => 'Redbird', 'state_id' => 3961],
                ['name' => 'Wagoner', 'state_id' => 3961],
                ['name' => 'Bartlesville', 'state_id' => 3961],
                ['name' => 'Copan', 'state_id' => 3961],
                ['name' => 'Dewey', 'state_id' => 3961],
                ['name' => 'Ochelata', 'state_id' => 3961],
                ['name' => 'Ramona', 'state_id' => 3961],
                ['name' => 'Vera', 'state_id' => 3961],
                ['name' => 'Colony', 'state_id' => 3961],
                ['name' => 'Corn', 'state_id' => 3961],
                ['name' => 'Bessie', 'state_id' => 3961],
                ['name' => 'Burns Flat', 'state_id' => 3961],
                ['name' => 'Canute', 'state_id' => 3961],
                ['name' => 'Cordell', 'state_id' => 3961],
                ['name' => 'Dill City', 'state_id' => 3961],
                ['name' => 'Foss', 'state_id' => 3961],
                ['name' => 'Rocky', 'state_id' => 3961],
                ['name' => 'Sentinel', 'state_id' => 3961],
                ['name' => 'Alva', 'state_id' => 3961],
                ['name' => 'Dacoma', 'state_id' => 3961],
                ['name' => 'Hopeton', 'state_id' => 3961],
                ['name' => 'Freedom', 'state_id' => 3961],
                ['name' => 'Waynoka', 'state_id' => 3961],
                ['name' => 'Woodward', 'state_id' => 3961],
                ['name' => 'Fort Supply', 'state_id' => 3961],
                ['name' => 'Mooreland', 'state_id' => 3961],
                ['name' => 'Mutual', 'state_id' => 3961],
                ['name' => 'Sharon', 'state_id' => 3961]
            ]);
        }
    }
}
